### ISSUE TITLE
ClassNotFound exceptions makes DAS inaccesible if wrong JACC settings are provided

### ISSUE THREAD

**Issue by ggam** [payara/Payara#1015]
Steps to reproduce:
- Create and enable a new JACC provider with wrong settings (unexistent classes).
- Restart the server for the changes to take effect.
- Try to access the admin console. A blank page is returned.

Checking the logs, you can see that it is unable to create the JACC policy:

```
[2016-08-10T13:03:40.508+0200] [Payara 4.1] [SEVERE] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=110 _ThreadName=Thread-19] [timeMillis: 1470827020508] [levelValue: 1000] [[
  Exception during lifecycle processing
MultiException stack 1 of 2
com.sun.enterprise.security.SecurityLifecycleException
    at com.sun.enterprise.security.SecurityLifecycle.onInitialization(SecurityLifecycle.java:184)
    at com.sun.enterprise.security.SecurityLifecycle.postConstruct(SecurityLifecycle.java:208)
    at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:326)
    at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:374)
    at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
    at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83)
    at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71)
    at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154)
    at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199)
    at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122)
    at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
    at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
    at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
    at com.sun.enterprise.security.ee.SecuritySniffer.setup(SecuritySniffer.java:115)
    at com.sun.enterprise.v3.server.ContainerStarter.startContainer(ContainerStarter.java:97)
    at com.sun.enterprise.v3.server.ApplicationLifecycle.setupContainer(ApplicationLifecycle.java:998)
    at com.sun.enterprise.v3.server.ApplicationLifecycle.setupContainerInfos(ApplicationLifecycle.java:703)
    at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:379)
    at com.sun.enterprise.v3.server.ApplicationLoaderService.processApplication(ApplicationLoaderService.java:406)
    at com.sun.enterprise.v3.admin.adapter.InstallerThread.load(InstallerThread.java:211)
    at com.sun.enterprise.v3.admin.adapter.InstallerThread.run(InstallerThread.java:100)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: jsdjsjdjsdsd
    at com.sun.enterprise.security.PolicyLoader.loadPolicy(PolicyLoader.java:189)
    at com.sun.enterprise.security.SecurityLifecycle.onInitialization(SecurityLifecycle.java:163)
    ... 22 more
Caused by: java.lang.ClassNotFoundException: jsdjsjdjsdsd
    at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1795)
    at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1645)
    at com.sun.enterprise.security.PolicyLoader.loadPolicy(PolicyLoader.java:154)
    ... 23 more
MultiException stack 2 of 2
java.lang.IllegalStateException: Unable to perform operation: post construct on com.sun.enterprise.security.SecurityLifecycle
    at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:392)
    at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
    at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83)
    at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71)
    at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154)
    at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199)
    at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122)
    at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
    at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
    at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
    at com.sun.enterprise.security.ee.SecuritySniffer.setup(SecuritySniffer.java:115)
    at com.sun.enterprise.v3.server.ContainerStarter.startContainer(ContainerStarter.java:97)
    at com.sun.enterprise.v3.server.ApplicationLifecycle.setupContainer(ApplicationLifecycle.java:998)
    at com.sun.enterprise.v3.server.ApplicationLifecycle.setupContainerInfos(ApplicationLifecycle.java:703)
    at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:379)
    at com.sun.enterprise.v3.server.ApplicationLoaderService.processApplication(ApplicationLoaderService.java:406)
    at com.sun.enterprise.v3.admin.adapter.InstallerThread.load(InstallerThread.java:211)
    at com.sun.enterprise.v3.admin.adapter.InstallerThread.run(InstallerThread.java:100)
]]

[2016-08-10T13:03:40.539+0200] [Payara 4.1] [SEVERE] [NCLS-CORE-00041] [javax.enterprise.system.core] [tid: _ThreadID=110 _ThreadName=Thread-19] [timeMillis: 1470827020539] [levelValue: 1000] [[
  Application deployment failed: Exception while deploying the app [__admingui]]]
```

My proposal is to:
- Add a check to verify that the classes exist before creating/enabling the JACC provider.
- If possible, show a more informative error page on the DAS. Sometimes users are given access to the admin console, but not to SSH. An error page with some indications would be useful in that cases.

**Comment by OndrejM** [comment]
@ggam, could you give us a pointer in the code where to verify that JACC provider can be created? Or even better, would you be able to submit a pull request?

**Comment by OndroMih** [comment]
Unfortunately, we’re not able to fit this feature request into our current roadmap. I’m closing this issue. I hope you understand.
