### ISSUE TITLE
java.lang.RuntimeException: java.lang.NullPointerException while uploading e.g. via SSH to autodeploy

### ISSUE THREAD

**Issue by Quix0r** [payara/Payara#1080]
The following exception occurs with 163 when a JAR/WAR is being currently uploaded (e.g. slow SSH connection) to domain's autodeploy folder and the server tries to open it while it is still incomplete:
````
[2016-09-03T17:05:29.028+0200] [Payara 4.1] [SEVERE] [NCLS-ADMIN-00011] [javax.enterprise.system.tools.admin.security.authorization] [tid: _ThreadID=69 _ThreadName=AutoDeployer] [timeMillis: 1472915129028] [levelValue: 1000] [[
  An unexpected exception occurred.
java.lang.RuntimeException: java.lang.NullPointerException
        at org.glassfish.deployment.admin.DeployCommand.preAuthorization(DeployCommand.java:311)
        at com.sun.enterprise.admin.util.CommandSecurityChecker$1.run(CommandSecurityChecker.java:187)
        at com.sun.enterprise.admin.util.CommandSecurityChecker$1.run(CommandSecurityChecker.java:183)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:356)
        at com.sun.enterprise.admin.util.CommandSecurityChecker.authorize(CommandSecurityChecker.java:183)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1239)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
        at org.glassfish.deployment.autodeploy.AutoOperation.run(AutoOperation.java:164)
        at org.glassfish.deployment.autodeploy.AutoDeployer.deploy(AutoDeployer.java:597)
        at org.glassfish.deployment.autodeploy.AutoDeployer.deployAll(AutoDeployer.java:484)
        at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:412)
        at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:403)
        at org.glassfish.deployment.autodeploy.AutoDeployService$1.run(AutoDeployService.java:233)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.NullPointerException
        at java.util.zip.ZipFile.getZipEntry(ZipFile.java:531)
        at java.util.zip.ZipFile.access$900(ZipFile.java:56)
        at java.util.zip.ZipFile$1.nextElement(ZipFile.java:513)
        at java.util.zip.ZipFile$1.nextElement(ZipFile.java:483)
        at java.util.jar.JarFile$1.nextElement(JarFile.java:244)
        at java.util.jar.JarFile$1.nextElement(JarFile.java:239)
        at com.sun.enterprise.deployment.deploy.shared.InputJarArchive$ArchiveJarEntrySource.getNextJarEntry(InputJarArchive.java:590)
        at com.sun.enterprise.deployment.deploy.shared.InputJarArchive$EntryEnumeration.getNextJarEntry(InputJarArchive.java:512)
        at com.sun.enterprise.deployment.deploy.shared.InputJarArchive$TopLevelDirectoryEntryEnumeration.skipToNextMatchingEntry(InputJarArchive.java:646)
        at com.sun.enterprise.deployment.deploy.shared.InputJarArchive$EntryEnumeration.completeInit(InputJarArchive.java:493)
        at com.sun.enterprise.deployment.deploy.shared.InputJarArchive$TopLevelDirectoryEntryEnumeration.<init>(InputJarArchive.java:633)
        at com.sun.enterprise.deployment.deploy.shared.InputJarArchive$TopLevelDirectoryEntryEnumeration.<init>(InputJarArchive.java:629)
        at com.sun.enterprise.deployment.deploy.shared.InputJarArchive.createEntryEnumeration(InputJarArchive.java:455)
        at com.sun.enterprise.deployment.deploy.shared.InputJarArchive.entries(InputJarArchive.java:203)
        at com.sun.enterprise.deployment.deploy.shared.InputJarArchive.access$100(InputJarArchive.java:74)
        at com.sun.enterprise.deployment.deploy.shared.InputJarArchive$1.enumeration(InputJarArchive.java:166)
        at com.sun.enterprise.deployment.deploy.shared.InputJarArchive$CollectionWrappedEnumeration.<init>(InputJarArchive.java:728)
        at com.sun.enterprise.deployment.deploy.shared.InputJarArchive.getDirectories(InputJarArchive.java:161)
        at org.glassfish.javaee.full.deployment.EarDetector.isEARFromIntrospecting(EarDetector.java:142)
        at org.glassfish.javaee.full.deployment.EarDetector.handles(EarDetector.java:110)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.getArchiveHandler(ApplicationLifecycle.java:212)
        at org.glassfish.deployment.admin.DeployCommand.preAuthorization(DeployCommand.java:243)
        ... 16 more
````
Using latest **163** build. This is easy reproduceable by uploading an incomplete WAR (because the upload is in progress).

**Comment by smillidge** [comment]
Have you tried using the asadmin deploy command or using the administration console to deploy rather than the autodeploy directory if you are on a slow link.

**Comment by Quix0r** [comment]
Not yet but I expect to have it working. Still I would like to see something like:
- pre-check if uploaded file is complete/readable
- if not, ignore it
- if so, process it

**Comment by smillidge** [comment]
I'm not sure how the autodeployer could know you are uploading the file. When the admin console and asadmin commands upload a file they upload to a temp directory first then copy over the file when the upload is complete. Could you not upload via ssh to a temp directory then cp into the autodeploy directory once the upload is complete?

**Comment by Quix0r** [comment]
Hmm, then still I need to SSH to the server. Well, it was an idea when I saw the error message.
