### ISSUE TITLE
Hazelcast serialization issue when sending events

### ISSUE THREAD

**Issue by dorpsidioot** [payara/Payara#1093]
We would like to be able to signal all the members of a hazelcast payara cluster that a certain resource has been invalidated and should be reloaded. Say for example that on node1 a request has arrived which causes an invalidation of the internal workings of a singleton implementation, then the other nodes have to do the same as node1.

So I was thinking of using the hazelcast functionality to do this, and it works to some degree:
- I can get the HazelcastInstance from the JNDI context
- I can create a new hazelcast topic
- I can publish messages to that topic
- I can receive messages from that topic in a different handler

However, when the messages are something other than a default java class, it all goes down the drain. I then get these exceptions when trying to get the internal object from the message's instance:
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException.

I've tried to set the classloader of hazelcast to the war's classloader but no avail. From what I can see when I debug is that the serialization works ok, because there he uses the correct classloader, but when it's deserialized then it's using the payara's classloader instead.

The singleton which instantiates the topics and sends the messages:
```java
@Singleton
@Startup
@LocalBean
public class HazelcastController {
    
    private HazelcastInstance hazelcastInstance;
    private ITopic topic;
    
    private static final Logger log = Logger.getLogger(HazelcastController.class.getName());
    
    @PostConstruct
    public void onInit() {
        try {

	    log.log(Level.INFO, "initializing {0}", this.getClass().toString());

	    Context ctx = new InitialContext();
	    hazelcastInstance = (HazelcastInstance) ctx.lookup("payara/Hazelcast");
	    if (hazelcastInstance != null) {
		// Setup classloader so it can find the necessary stuff
		Config config = hazelcastInstance.getConfig();
		if (config != null) {
		    config.setClassLoader(Thread.currentThread().getContextClassLoader());
		}		
		topic = hazelcastInstance.getTopic("default");
		topic.addMessageListener(new HazelcastMessageListener());

		log.log(Level.INFO, "Done initializing {0}", this.getClass().toString());
	    } else {
		log.log(Level.SEVERE, "Hazelcast instance not found");
	    }
        } catch (Exception ex) {
            log.log(Level.SEVERE, "An error has occurred while initializing HazelcastListener - Error: {0}", ex.getMessage());
        }
    }
    
    @Schedule(second = "0/15", minute = "*", hour = "*")
    public void sendMessage() {
	if (topic != null) {
	    topic.publish(new BasicEvent("TEST 123"));
	}
    }    
}
```

The message listener class:
```java
public class HazelcastMessageListener implements MessageListener<BasicEvent> {

    private static final Logger log = Logger.getLogger(HazelcastMessageListener.class.getName());
    
    @Override
    public void onMessage(Message<BasicEvent> message) {
	if (message != null) {
	    log.log(Level.INFO, "Received message from cluster member {0}", message.getPublishingMember());
	    BasicEvent event = message.getMessageObject();
	    log.log(Level.INFO, "Message: {0}", event.getMessage());
	}
    }
    
}
```

The BasicEvent class(message object)
```java
public class BasicEvent implements Serializable {    
    private static final long serialVersionUID = 1L;
    
    private String message;

    public String getMessage() {
	return message;
    }

    public void setMessage(String message) {
	this.message = message;
    }
    
    protected BasicEvent() {}

    public BasicEvent(String message) {
	this.message = message;
    }
}
```

Stack trace when the message is received
```
Info: Received message from cluster member Member [192.168.0.249]:5900 this
Severe: [192.168.0.249]:5900 [development] [3.6.4] hz._hzInstance_1_development.event-1 caught an exception while processing task:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@47dfa96f
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: be.powerdale.hazelcast.BasicEvent
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:224)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:170)
	at com.hazelcast.topic.impl.DataAwareMessage.getMessageObject(DataAwareMessage.java:44)
	at be.powerdale.hazelcast.HazelcastMessageListener.onMessage(HazelcastMessageListener.java:21)
	at com.hazelcast.topic.impl.TopicService.dispatchEvent(TopicService.java:131)
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:56)
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:187)
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:171)
Caused by: java.lang.ClassNotFoundException: be.powerdale.hazelcast.BasicEvent
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.sun.enterprise.loader.CurrentBeforeParentClassLoader.loadClass(CurrentBeforeParentClassLoader.java:82)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:137)
	at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:115)
	at com.hazelcast.nio.IOUtil$1.resolveClass(IOUtil.java:114)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:219)
	... 8 more
```

**Comment by smillidge** [comment]
The problem is caused by Hazelcast threads which are started before your application is deployed and therefore know nothing about your application classes.  We are working on this at the moment to see if we can initialize Hazelcast with a specialised classloader that looks into the application classloaders to load objects. 

One solution is to write a library for message objects and place it in the glassfish lib directory. An alternative is to write a holder class that serializes and deserializes your application classes into a byte array in the event object and place the jar containing this message object into the glassfish lib directory.

**Comment by dorpsidioot** [comment]
I'll try by providing a custom serializer which gets the correct context or just send strings(json) or byte arrays which contain the data itself and deserialize them locally as you suggested(json has the advantage that it's easily kept backwards compatible).
