### ISSUE TITLE
CDI deployment failure:WELD-001408:com.sun.enterprise.config.serverbeans.ConfigBeansUtilities(Applications, Domain)

### ISSUE THREAD

**Issue by RaZv** [payara/Payara#1114]
hi,
I am trying to port my Arquillian tests to java8 with Payara (test are working with java6 and Glassfish 3.1).
It is failing in one of the Payara internal classes - ConfigBeansUtilities, when trying to deploy the .ear file:

org.glassfish.deployment.common.DeploymentException: CDI deployment failure:WELD-001408: Unsatisfied dependencies for type Domain with qualifiers @Default
  at injection point [BackedAnnotatedParameter] Parameter 2 of [BackedAnnotatedConstructor] @Inject public com.sun.enterprise.config.serverbeans.ConfigBeansUtilities(Applications, Domain)
  at com.sun.enterprise.config.serverbeans.ConfigBeansUtilities.<init>(ConfigBeansUtilities.java:0)

	at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:235)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:329)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:497)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:487)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
	at java.security.AccessController.doPrivileged(AccessController.java:529)
	at javax.security.auth.Subject.doAs(Subject.java:488)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
	at java.security.AccessController.doPrivileged(AccessController.java:529)
	at javax.security.auth.Subject.doAs(Subject.java:488)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
	at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:134)
	at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:110)
	at org.jboss.arquillian.container.glassfish.embedded_3_1.GlassFishContainer.deploy(GlassFishContainer.java:195)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$3.call(ContainerDeployController.java:161)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$3.call(ContainerDeployController.java:128)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.executeOperation(ContainerDeployController.java:271)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.deploy(ContainerDeployController.java:127)

**Comment by mulderbaba** [comment]
@RaZv Is it possible to share your reproducer with us? Which version of Payara embedded are you using with Arquillian? It'd be great if we can get more information from your side, regarding arquillian config also.

**Comment by RaZv** [comment]
@mulderbaba thank you for taking this up, I am quite desperate to get it working.

I have two flavors of arquillian tests. One that is only deploying a .jar file and then does some operations on the in memory db (storing, finding deleting) - this one works fine. 
The other flavor, is an .ear file, and the tests are starting up the browser and mimicking the user input using selenium webdriver. The changes on the screens are verified as well as the db state. These tests are suffering from this cdi deployment failure. Any help would be highly appreciated it.

Please find below my arquillian.xml
`
<?xml version="1.0" encoding="UTF-8"?>
<arquillian xmlns="http://jboss.org/schema/arquillian"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="
        http://jboss.org/schema/arquillian
        http://jboss.org/schema/arquillian/arquillian_1_0.xsd">

	<extension qualifier="webdriver">
		<property name="browser">firefox</property>
		
		<property name="ignoreProtectedModeSettings">true</property>
		<property name="acceptSslCerts">true</property>
		<property name="ignoreZoomSetting">true</property>
		
		<property name="remote">true</property>
		<property name="remoteAddress">http://10.92.8.99:80/wd/hub</property>
		<property name="remoteReusable">false</property>
	</extension>
	
	<extension qualifier="graphene">
   		<property name="waitGuiInterval">10</property>
	</extension>
	
    <container qualifier="glassfish-embedded" default="true">
        <configuration>
            <property name="resourcesXml">src/test/resources-glassfish-embedded/glassfish-resources.xml</property>
            <property name="bindHttpPort">8096</property>
        </configuration>
    </container>  
 </arquillian>
`
Extrace from my pom.xml
`
				<dependency>
					<groupId>org.jboss.arquillian.extension</groupId>
					<artifactId>arquillian-warp</artifactId>
					<version>${warp.version}</version>
					<type>pom</type>
					<scope>test</scope>
				</dependency>

				<dependency>
					<groupId>org.jboss.arquillian.container</groupId>
					<artifactId>arquillian-glassfish-embedded-3.1</artifactId>
					<version>1.0.0.Final</version>
					<scope>test</scope>
				</dependency>

				<dependency>
					 <groupId>fish.payara.extras</groupId>
				   <artifactId>payara-embedded-all</artifactId>
				   <version>4.1.1.163.0.1</version>
				   <scope>test</scope>
				</dependency>
`

**Comment by mikecroft** [comment]
@RaZv could you create a new repository here on GitHub with the sources of your WAR?

**Comment by RaZv** [comment]
hi,
I have added the war file here : https://github.com/RaZv/cdi-war-problem
thank you

**Comment by RaZv** [comment]
Interesting, I have changed to pom to use Glassfish 4.1.1 and I get the exact same error as when I was using Payara 4.1.1.163.0.1
'23227  2016-10-05 10:01:10,381 WARN  [main] weld.Event.? (?:?) - WELD-000411: Observer method [BackedAnnotatedMethod] private org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider.processAnnotatedType(@Observes ProcessAnnotatedType<Object>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
23237  2016-10-05 10:01:10,391 WARN  [main] weld.Event.? (?:?) - WELD-000411: Observer method [BackedAnnotatedMethod] org.glassfish.sse.impl.ServerSentEventCdiExtension.processAnnotatedType(@Observes ProcessAnnotatedType<Object>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
23244  2016-10-05 10:01:10,398 WARN  [main] weld.Event.? (?:?) - WELD-000411: Observer method [BackedAnnotatedMethod] public org.glassfish.jms.injection.JMSCDIExtension.processAnnotatedType(@Observes ProcessAnnotatedType<Object>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
Oct 05, 2016 10:01:11 AM com.sun.enterprise.v3.server.ApplicationLifecycle deploy
SEVERE: Exception during lifecycle processing
org.glassfish.deployment.common.DeploymentException: CDI deployment failure:WELD-001408: Unsatisfied dependencies for type Domain with qualifiers @Default
  at injection point [BackedAnnotatedParameter] Parameter 2 of [BackedAnnotatedConstructor] @Inject public com.sun.enterprise.config.serverbeans.ConfigBeansUtilities(Applications, Domain)
  at com.sun.enterprise.config.serverbeans.ConfigBeansUtilities.<init>(ConfigBeansUtilities.java:0)

	at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:234)'

**Comment by mulderbaba** [comment]
@RaZv thanks for the war file. is it possible to upload the source of that war file as well in order to build the project on our local and test it through the IDE?

**Comment by RaZv** [comment]
@mulderbaba I wish I could, but it is not possible :( ... anyways, have you ever tried to deploy a .war file using arquillian ? my guess is that the cdi problem is related to glassfish and not to the specific source code of the project

**Comment by smillidge** [comment]
Your war file contains internal Payara Server api classes in /WEB-INF/classes/com/sun/enterprise/config/serverbeans/ these are being scanned as CDI beans as they contain annotations however they are not valid CDI beans. These classes are provided by the Payara runtime and should be excluded from your war file.

**Comment by RaZv** [comment]
@smillidge you were completely right... I have refactored the code and removed these classes and I am able to deploy the war file to the Payara container. Thank you for your help!

**Comment by smillidge** [comment]
Good to know
