### ISSUE TITLE
ActiveMQ RAR adapter on cluster enviroment

### ISSUE THREAD

**Issue by bozic** [payara/Payara#1165]
# Description #
----------

When trying to configure ActiveMQ RAR adapter on Payara cluster, we can't configure RA adapter that is deployed only on cluster. Every time we try to open configuration screen on admin console we get the error that ```ActiveMQActivationSpec``` class can't be found. We checked the source code of RAR adapter and class is indeed in RAR so there must be some class loading issue.

## Expected Outcome

Same behavior as in non cluster configuration.

## Current Outcome

When we try to create new Resource Adapter Config, and when we chose activemq-rar as resource adapter name we get following error: 

```
[2016-11-07T10:21:04.221+0100] [Payara 4.1] [WARNING] [] [javax.enterprise.resource.resourceadapter.com.sun.enterprise.connectors.deployment.util] [tid: _ThreadID=345 _ThreadName=admin-thread-pool(11)] [timeMillis: 1478510464221] [levelValue: 900] [[
  Unable to load class [ org.apache.activemq.ra.ActiveMQActivationSpec ]
java.lang.ClassNotFoundException: org.apache.activemq.ra.ActiveMQActivationSpec
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at com.sun.enterprise.loader.CurrentBeforeParentClassLoader.loadClass(CurrentBeforeParentClassLoader.java:82)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.sun.enterprise.connectors.deployment.util.ConnectorValidator.getClass(ConnectorValidator.java:239)
        at com.sun.enterprise.connectors.deployment.util.ConnectorValidator.validateActivationSpec(ConnectorValidator.java:155)
        at com.sun.enterprise.connectors.deployment.util.ConnectorValidator.accept(ConnectorValidator.java:79)
        at com.sun.enterprise.connectors.deployment.util.ConnectorValidator.accept(ConnectorValidator.java:72)
        at com.sun.enterprise.deployment.BundleDescriptor.visit(BundleDescriptor.java:625)
        at com.sun.enterprise.connectors.deployment.util.ConnectorArchivist.postOpen(ConnectorArchivist.java:173)
        at com.sun.enterprise.connectors.deployment.util.ConnectorArchivist.postOpen(ConnectorArchivist.java:72)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:273)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:280)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:241)
        at com.sun.enterprise.connectors.util.ConnectorDDTransformUtils.getConnectorDescriptor(ConnectorDDTransformUtils.java:236)
        at com.sun.enterprise.connectors.service.ConnectorService.getConnectorDescriptor(ConnectorService.java:283)
        at com.sun.enterprise.connectors.service.ConnectorConfigurationParserServiceImpl.getConnectorConfigJavaBeans(ConnectorConfigurationParserServiceImpl.java:285)
        at com.sun.enterprise.connectors.service.ConnectorConfigurationParserServiceImpl.getResourceAdapterConfigProps(ConnectorConfigurationParserServiceImpl.java:186)
        at com.sun.enterprise.connectors.ConnectorRuntime.getResourceAdapterConfigProps(ConnectorRuntime.java:735)
        at org.glassfish.connectors.admin.cli.internal.GetResourceAdapterConfigProperties.execute(GetResourceAdapterConfigProperties.java:91)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
        at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:263)
        at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:234)
        at org.glassfish.admin.rest.resources.TemplateExecCommand.executeCommandLegacyFormat(TemplateExecCommand.java:159)
        at org.glassfish.admin.rest.resources.TemplateCommandGetResource.processGetLegacyFormat(TemplateCommandGetResource.java:77)
        at sun.reflect.GeneratedMethodAccessor130.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384)
        at org.glassfish.admin.rest.adapter.RestAdapter$2.service(RestAdapter.java:316)
        at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:179)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:466)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:169)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:231)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:231)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
        at java.lang.Thread.run(Thread.java:745)
]]
```

## Steps to reproduce (Only for bug reports) 

1. Create cluster following the steps on http://blog.payara.fish/creating-a-simple-cluster-with-payara-server
2. Deploy ActiveMQ RAR adapter on cluster following steps on http://blog.payara.fish/connecting-to-activemq-with-payara-server (RAR version doesn't matter)
2.1. On step "Configuring the ActiveMQ Connector" we get the above listed error.

## Context (Optional)

When the ActiveMQ RAR adapter deploy on cluster AND on DAS (on both targets), the settings are displayed properly. We are working with 5.7.0. version of adapter, but same problem occurred with 5.14.1. (latest at the moment).

## Environment ##

- **Payara Version**: 4.1.1.163 #badassfish (build 215)
- **Edition**: Full
- **JDK Version**: 8  - 1.8.0_102 Oracle
- **Operating System**: Linux SUSE Linux Enterprise Server 11 SP3  (x86_64)

**Comment by fturizo** [comment]
Hi @bozic,

I tried to reproduce this bug by following your steps by in my test scenario everything worked out fine. I tested this with the latest **ActiveMQ** RAR connector module (5.14.1). After I created the Hazelcast enabled cluster, I could deploy the RAR module to all of the cluster instances and the _DAS_ without experiencing the classloading exception. Did you remove the default **OpenMQ** connector modules and connection pools before attempting to install and configure the **ActiveMQ** connector module?

Let us know of any other configuration details that you might think are causing this problem in your environment.

**Comment by bozic** [comment]
The issue occurs only when RAR module is deployed on clustery, and not on DAS. When RAR module is deployed on cluster and on DAS, everything works as expected.
This "old" behavior works on Glassfish 3, so in process of migration we notice that this isn't working as before. If this is changed by purpose, then I stand corrected, but then it should be better documented maybe?

**Comment by fturizo** [comment]
Hello @bozic, in this case the encountered error is expected since the **DAS**' classloader expects to reach the appropriate classes of the resource adapter (`activemq-rar-5.14.1.rar`) and since the adapter was not deployed on the **DAS**, they are unreachable to the resource adapter configuration.  Keep in mind that the Oracle Glassfish 3 used Project Shoal to configure clustering while in your scenario you are using Hazelcast, which possess it's own classloaders to maintain both clustering and cache services.

I agree with your suggestions for a better documentation on this specific scenario. What do you propose? Should we make an [user guide](https://payara.gitbooks.io/payara-server/content/documentation/user-guides/user-guides.html) in the official Payara Server Documentation?

**Comment by bozic** [comment]
For this specific issue a paragraph in blog post about connecting to ActiveMQ would be sufficient, but we also encountered the change in JDBC properties configuration that is also changed and it isn't documented anywhere...

So maybe, some sort of "change list" in official documentation where all those changed behaviors from Glassfish would be listed? That would make it a little more user friendly than going thru code and/or reporting false bugs when things don't work as expected.

**Comment by fturizo** [comment]
@bozic, can you reference which was change to the JDBC property configuration?

**Comment by bozic** [comment]
@fturizo ```IfxDELIMIDENT``` for Informix JDBC connetction pool. In Glassfish 3 value for true was ```y```, but on Payara value for true is ```true```. There is no log message indicating that this is changed or that value is invalid.

Since JDCB driver is the same version (3.7) on both installations (Payara and Glassfish 3) we checked Payaras source code to see how to set this parameter. Tbh, we didn't check if this change was pulled from Glassfish 4 to Payara or it is made in Payara, but in any case this things are very tricky to trace.

**Comment by fturizo** [comment]
Hi @bozic, sorry for the late reply. Your comments make sense so we'll proceed to update the official docs and blog posts with this observations. Regarding the _Informix_ JDBC connection pool, I'm afraid that change is very peculiar since it's tied to the specifics of the workings of the JDBC driver, so in this case it's outside of the documentation for Payara Server.

Since the main issue was solved, I'm going to mark the issue as closed then.
