### ISSUE TITLE
after redeploy ClassCastException __EJB31_Generated__EjbBooks__Intf____Bean__ cannot be cast to EjbBooks during JNDI lookup for EJB from Hazelcast MapLoader implementation

### ISSUE THREAD

**Issue by sorinpopa82** [payara/Payara#1169]
# Description #
----------
Our application (.war) implements Hazelcast map loaders which perform JNDI lookups `new InitialContext().lookup("java:module/" + SomeEjb.class.getSimpleName())` to inject different EJBs (everything is packed inside our .war).
The map loaders work fine at first deployment or after a server stop/start. However, after each redeployment of the application, the map loaders fail to inject the EJBs with 
`java.lang.ClassCastException: paya.hz.test.__EJB31_Generated__EjbBooks__Intf____Bean__ cannot be cast to paya.hz.test.EjbBooks` like exceptions.

Note: this behaviour is not present in Glassfish 4.1, 4.1.1 (the app pom.xml must be modified to include hazelcast and cache-api in the app) - the jndi lookups inside the map loaders are successful after redeployments too.

## Expected Outcome
The JNDI lookup performed in the map loaders should work after redeployments of the app too.

## Current Outcome
Starting with the first redeployment of the application, the JNDI lookup fails with the following ClassCastException:
```
[2016-11-09T10:10:45.663+0200] [Payara 4.1] [INFO] [] [com.hazelcast.internal.cluster.impl.MulticastJoiner] [tid: _ThreadID=25 _ThreadName=http-thread-pool(2)] [timeMillis: 1478679045663] [levelValue: 800] [[
  [192.168.1.119]:5701 [dev] [3.7.2] 


Members [1] {
	Member [192.168.1.119]:5701 - f0a96bc5-8b57-47dd-8301-f37feb97a0f1 this
}
]]

[2016-11-09T10:10:45.664+0200] [Payara 4.1] [INFO] [] [com.hazelcast.core.LifecycleService] [tid: _ThreadID=25 _ThreadName=http-thread-pool(2)] [timeMillis: 1478679045664] [levelValue: 800] [[
  [192.168.1.119]:5701 [dev] [3.7.2] [192.168.1.119]:5701 is STARTED]]

[2016-11-09T10:10:45.667+0200] [Payara 4.1] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=25 _ThreadName=http-thread-pool(2)] [timeMillis: 1478679045667] [levelValue: 900] [[
  StandardWrapperValve[paya.hz.test.App]: Servlet.service() for servlet paya.hz.test.App threw exception
java.lang.ClassCastException: paya.hz.test.__EJB31_Generated__EjbBooks__Intf____Bean__ cannot be cast to paya.hz.test.EjbBooks
	at paya.hz.test.MapLoaderBooks.<init>(MapLoaderBooks.java:12)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.hazelcast.nio.ClassLoaderUtil.newInstance(ClassLoaderUtil.java:71)
	at com.hazelcast.map.impl.mapstore.StoreConstructor.getStoreFromClassOrNull(StoreConstructor.java:82)
	at com.hazelcast.map.impl.mapstore.StoreConstructor.createStore(StoreConstructor.java:46)
	at com.hazelcast.map.impl.mapstore.BasicMapStoreContext.create(BasicMapStoreContext.java:124)
	at com.hazelcast.map.impl.mapstore.MapStoreContextFactory.createMapStoreContext(MapStoreContextFactory.java:48)
	at com.hazelcast.map.impl.MapContainer.<init>(MapContainer.java:114)
	at com.hazelcast.map.impl.MapServiceContextImpl$1.createNew(MapServiceContextImpl.java:91)
	at com.hazelcast.map.impl.MapServiceContextImpl$1.createNew(MapServiceContextImpl.java:87)
	at com.hazelcast.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:79)
	at com.hazelcast.map.impl.MapServiceContextImpl.getMapContainer(MapServiceContextImpl.java:162)
	at com.hazelcast.map.impl.operation.MapOperationProviders.getOperationProvider(MapOperationProviders.java:47)
	at com.hazelcast.map.impl.MapServiceContextImpl.getMapOperationProvider(MapServiceContextImpl.java:569)
	at com.hazelcast.map.impl.proxy.MapProxySupport.<init>(MapProxySupport.java:203)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.<init>(MapProxyImpl.java:86)
	at com.hazelcast.map.impl.MapRemoteService.createDistributedObject(MapRemoteService.java:54)
	at com.hazelcast.map.impl.MapService.createDistributedObject(MapService.java:140)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.doCreateProxy(ProxyRegistry.java:177)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.createProxy(ProxyRegistry.java:170)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.getOrCreateProxy(ProxyRegistry.java:139)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.getDistributedObject(ProxyServiceImpl.java:147)
	at com.hazelcast.instance.HazelcastInstanceImpl.getDistributedObject(HazelcastInstanceImpl.java:372)
	at com.hazelcast.instance.HazelcastInstanceImpl.getMap(HazelcastInstanceImpl.java:178)
	at com.hazelcast.instance.HazelcastInstanceProxy.getMap(HazelcastInstanceProxy.java:92)
	at paya.hz.test.RestBooks.getCache(RestBooks.java:33)
	at paya.hz.test.RestBooks.find(RestBooks.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:223)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1681)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:318)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:416)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:466)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:169)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
]]

[2016-11-09T10:28:25.358+0200] [Payara 4.1] [INFO] [] [com.hazelcast.nio.tcp.SocketAcceptorThread] [tid: _ThreadID=216 _ThreadName=hz._hzInstance_2_dev.IO.thread-Acceptor] [timeMillis: 1478680105358] [levelValue: 800] [[
  [192.168.1.119]:5701 [dev] [3.7.2] Accepting socket connection from /192.168.1.108:63683]]


```

## Steps to reproduce (Only for bug reports) 
1. Unpack Full Payara 4.1.1.163 Full (the behaviour is exhibited also in 153, and 164 Snapshot) from a untouched zip (as in just downloaded from the site).
1. Set JAVA_HOME=$HOME/jdk1.8.0_92
2. `./asadmin start-domain domain1`
3. Deploy the sample app [books-shelf.war.zip](https://github.com/payara/Payara/files/580320/books-shelf.war.zip) from the admin console (after removing the .zip extension).
4. Access http://localhost:8080/books-shelf/api/books?ids=1 from a browser
5. Should display text: 
> Title: Title 1
> Author: Author 1
6. Undeploy the sample app from the admin console.
7. Deploy the sample app from the admin console (1st redeployment)
8. Access http://localhost:8080/books-shelf/api/books?ids=1 from a browser
9. The page should display *HTTP Status 500 - Internal Server Error* with last root cause:
`java.lang.ClassCastException: paya.hz.test.__EJB31_Generated__EjbBooks__Intf____Bean__ cannot be cast to paya.hz.test.EjbBooks`
10. `./asadmin stop-domain domain1`
11. `./asadmin start-domain domain1`
12. Access http://localhost:8080/books-shelf/api/books?ids=1 from a browser
13. Should display text:
> Title: Title 1
> Author: Author 1

### Samples
Source (Maven project): https://github.com/sorinpopa82/books-shelf
War: [books-shelf.war.zip](https://github.com/payara/Payara/files/580320/books-shelf.war.zip)

## Context (Optional)
We want to provide Hazelcast based caching in our application for user data.
Our target environment consists of Payara >=163, Oracle JDK 8 u92, Ubuntu Server LTS >= 14.04, Hazelcast >= 3.7.1 (we've noticed Hz 3.7.1 is included in Payara 164 Snapshot).
At the moment, we did not setup clustering, but our plan is to do it based on Hazelcast, too.
What we want to achieve with the cache implementation is to have loose coupling between the cache structures (mostly maps) and the data sources for those (JPA, web service clients, other perhaps).
We would also like to make use of the advantages provided by the Hazelcast MapLoader and MapStore mechanisms.

## Environment ##

- **Payara Version**: 4.1.1.163
- **Edition**: Full
- **JDK Version**: 8 u92 - Oracle
- **Operating System**: Linux

**Comment by smillidge** [comment]
The symptoms look like a Classloader leak. 

As you are bootstrapping Hazelcast from within your web app, Hazelcast spawns threads which will inherit the Thread Context Class Loader which will be your previous web app classloader after redeploy. If you want to bootstrap Hazelcast from within your application to prevent classloader leaks you need to set the thread context classloader during boot to something which is not your web app classloader.

Have you tried just enabling the Hazelcast instance within Payara and using that directly?

**Comment by sorinpopa82** [comment]
Enabling Hz instance in Payara and using that in the sample app works as expected after redeployments. (I've  just tried it on Payara 163 Full).
This is acceptable as a workaround for now.
However, we would like to be able to choose whether to use Hz within Payara or a different one.

**Comment by sorinpopa82** [comment]
When using the Hazelcast instance within Payara from our application (not the sample app), we consistently experience the following exception after redeployments:
```
Caused by: javax.ejb.EJBException: Attempt to invoke when container is in Undeployed
        at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:1997)
        at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:1992)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
        ...
        [equivalent of sample app 
        at com.sun.proxy.$Proxy233.getOne(Unknown Source)
        at paya.hz.test.__EJB31_Generated__EjbBooks__Intf____Bean__.getOne(Unknown Source)
        at paya.hz.test.MapLoaderBooks.loadAllKeys(MapLoaderBooks.java:...)
        ]
        ...
        at com.hazelcast.map.impl.MapStoreWrapper.loadAllKeys(MapStoreWrapper.java:119)
        at com.hazelcast.map.impl.mapstore.BasicMapStoreContext.loadAllKeys(BasicMapStoreContext.java:179)
        at com.hazelcast.map.impl.MapKeyLoader.sendKeysInBatches(MapKeyLoader.java:295)
        at com.hazelcast.map.impl.MapKeyLoader.access$200(MapKeyLoader.java:72)
        at com.hazelcast.map.impl.MapKeyLoader$1.call(MapKeyLoader.java:192)
        at com.hazelcast.map.impl.MapKeyLoader$1.call(MapKeyLoader.java:189)
        at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:67)
        at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:212)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
        at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
        at ------ submitted from ------.(Unknown Source)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:111)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:74)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:158)
        at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:377)
        at com.hazelcast.map.impl.proxy.MapProxySupport.getInternal(MapProxySupport.java:308)
        at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:94)
        ...
        [one of our EJBs reading the cache]
        ...
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4762)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
        at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
        at sun.reflect.GeneratedMethodAccessor74.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
        at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:374)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4734)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4722)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
        ... 113 more
```
I will try to narrow it down somehow, or try to reproduce it with a modified sample app.

**Comment by mikecroft** [comment]
Hi @sorinpopa82 - we haven't heard from you on this in a while, is it still an issue for you?

**Comment by mikecroft** [comment]
Since @smillidge already gave an explanation as to why this may be happening and we haven't heard from @sorinpopa82 for a while, I'll close this issue.

It doesn't appear to be a problem with Payara as much as with the way Hazelcast is being used, therefore a better place for further discussions about this would be the [Payara Forum](https://groups.google.com/forum/#!forum/payara-forum)
