### ISSUE TITLE
payara 4.1.1.164 error when deploy ear : LinkageError: loader constraint violation: when resolving overridden method "org.apache.xerces.jaxp.SAXParserImpl.getXMLReader()Lorg/xml/sax/XMLReader;"

### ISSUE THREAD

**Issue by omarbr** [payara/Payara#1185]
When deploy ear on 4.1.1.164:
```
[2016-11-17T09:46:13.567+0100] [Payara 4.1] [SEVERE] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=72 _ThreadName=admin-thread-pool(3)] [timeMillis: 1479372373567] [levelValue: 1000] [[
  Exception during lifecycle processing
java.lang.LinkageError: loader constraint violation: when resolving overridden method "org.apache.xerces.jaxp.SAXParserImpl.getXMLReader()Lorg/xml/sax/XMLReader;" the class loader (instance of org/glassfish/javaee/full/deployment/EarLibClassLoader) of the current class, org/apache/xerces/jaxp/SAXParserImpl, and its superclass loader (instance of <bootloader>), have different Class objects for the type org/xml/sax/XMLReader used in the signature
	at org.apache.xerces.jaxp.SAXParserFactoryImpl.newSAXParser(Unknown Source)
........
[2016-11-17T09:46:13.588+0100] [Payara 4.1] [WARNING] [NCLS-CORE-00069] [javax.enterprise.system.core] [tid: _ThreadID=54 _ThreadName=Executor-Service-9] [timeMillis: 1479372373588] [levelValue: 900] [[
  Exception while dispatching an event
java.lang.NullPointerException
	at com.sun.enterprise.container.common.impl.ComponentEnvManagerImpl.undeployAllDescriptors(ComponentEnvManagerImpl.java:422)
	at com.sun.enterprise.container.common.impl.ComponentEnvManagerImpl.unbindFromComponentNamespace(ComponentEnvManagerImpl.java:377)
	at com.sun.enterprise.web.WebContainer.event(WebContainer.java:891)
	at org.glassfish.kernel.event.EventsImpl$1.run(EventsImpl.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]

[2016-11-17T09:46:13.589+0100] [Payara 4.1] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=72 _ThreadName=admin-thread-pool(3)] [timeMillis: 1479372373589] [levelValue: 1000] [[
  Exception while deploying the app [pripper-ear] : loader constraint violation: when resolving overridden method "org.apache.xerces.jaxp.SAXParserImpl.getXMLReader()Lorg/xml/sax/XMLReader;" the class loader (instance of org/glassfish/javaee/full/deployment/EarLibClassLoader) of the current class, org/apache/xerces/jaxp/SAXParserImpl, and its superclass loader (instance of <bootloader>), have different Class objects for the type org/xml/sax/XMLReader used in the signature]]
```

work on 4.1.1.163 and 4.1.152

**Comment by mikecroft** [comment]
What are the steps to reproduce? Is this with any EAR? Do you have a test case which shows the issue?

**Comment by omarbr** [comment]
I identify a steps to reproduce:
add 
```
  	<dependency>
  		<groupId>xerces</groupId>
  		<artifactId>xercesImpl</artifactId>
  		<version>2.11.0</version>
  	</dependency>
```
on pom

**Comment by lprimak** [comment]
I believe I've encountered this problem in the past.
The issue is the services/ directory in the xercesImpl that conflicts with the one bundled in Payara.  I would suggest re-jarring the file without the services/ directory.

You can currently try with the following in your pom.xml:

```
 <repositories>
        <repository>
            <id>flowlogix-maven2</id>
            <url>http://raw.github.com/flowlogix/flowlogix-m2/master</url>
        </repository>
    </repositories>
...
        <dependency>
            <groupId>xerces</groupId>
            <artifactId>xercesImpl</artifactId>
            <type>jar</type>
            <version>2.11.0-no-services</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <artifactId>xml-apis</artifactId>
                    <groupId>xml-apis</groupId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by omarbr** [comment]
with 2.11.0-no-services work, but it's possible fix this for use standard xerces jar?

**Comment by lprimak** [comment]
Not sure.  I suspect it would take some doing

**Comment by mikecroft** [comment]
I've created internal issue `PAYARA-1239` for this. We're handling it as an improvement because currently there is an accepted way to get this working and it's not clear how complex this could be.

**Comment by smillidge** [comment]
Please remove Xerces from your war file it is extremely old and the same features are provided by modern JDKs. See http://www.odi.ch/weblog/posting.php?posting=689 for a good rant on this issue :-)
