### ISSUE TITLE
JCache Listener with Payara Cluster

### ISSUE THREAD

**Issue by stePrime** [payara/Payara#1203]
# Description #

Hi Team,

I have a Cluster as Standalone Instances. I added JCache in my project to share websockets messages among the nodes. I want store in the Cache a simple Custom Object called Cluster Object.

`

     public class ClusterObject implements Serializable {

         String nameNode;
         String message;

        public ClusterObject(String nameNode, String message) {
           this.nameNode = nameNode;
           this.message = message;
        }

        (getters / setters methods)

    }

`

I use JCache in this way : 

`

    @Inject
    CacheManager cacheManager;

    @PostConstruct
    public void init() {
        Configuration<?, ?> configuration
                = new MutableConfiguration<>()
                .setExpiryPolicyFactory(
                        CreatedExpiryPolicy
                        .factoryOf(new Duration(TimeUnit.SECONDS, 10)))
                ;

        if (cacheManager.getCache("custom") == null) {
            cacheManager.createCache("custom", configuration);
        }
    }`

In put method: 

`

        Cache<Integer, ClusterObject> cache = cacheManager.getCache("custom");
        cache.put(1, new ClusterObject(this.getInstance(), message));

`

Ok, it seems to work.
Now, I need of "CacheEntryListener" in order to each Node woken up by put event.
I have seen Hazelcast Documentation and I replaced the PostConstruct code in this way:

`

    @PostConstruct
    public void init() {
        Configuration<Integer, ClusterObject> configuration
                = new MutableConfiguration<Integer, ClusterObject>()
                .setTypes(Integer.class, ClusterObject.class)
                .setExpiryPolicyFactory(
                        CreatedExpiryPolicy
                        .factoryOf(new Duration(TimeUnit.SECONDS, 10))) 
                 .addCacheEntryListenerConfiguration(
                        new MutableCacheEntryListenerConfiguration<Integer, ClusterObject>(
                                new ClusterCacheEntryListenerFactory(),
                                null, true, true
                        ))
                ;

        if (cacheManager.getCache("custom", Integer.class, ClusterObject.class) == null) {
            cacheManager.createCache("custom", configuration);
        }
    }

`

and I added belowe Classes:

ClusterCacheEntryListenerFactory:

`

      public class ClusterCacheEntryListenerFactory implements Factory<CacheEntryListener<Integer, ClusterObject>>, Serializable {

         @Override
         public CacheEntryListener<Integer, ClusterObject> create() {
             // just create a new listener instance
             return new ClusterCacheListener();
          }
      }

`

ClusterCacheListener:

`

     public class ClusterCacheListener implements CacheEntryCreatedListener<Integer, ClusterObject>,
            CacheEntryUpdatedListener<Integer, ClusterObject>,
            CacheEntryRemovedListener<Integer, ClusterObject>,
            CacheEntryExpiredListener<Integer, ClusterObject> {

               @Override
               public void onCreated(Iterable<CacheEntryEvent<? extends Integer, ? extends ClusterObject>>              cacheEntryEvents) throws CacheEntryListenerException {
                      printEvents(cacheEntryEvents);
                }

               @Override
               public void onUpdated(Iterable<CacheEntryEvent<? extends Integer, ? extends ClusterObject>> cacheEntryEvents) throws CacheEntryListenerException {
                      printEvents(cacheEntryEvents);
               }

               @Override
               public void onRemoved(Iterable<CacheEntryEvent<? extends Integer, ? extends ClusterObject>> cacheEntryEvents) throws CacheEntryListenerException {
                     printEvents(cacheEntryEvents);
               }

               @Override
               public void onExpired(Iterable<CacheEntryEvent<? extends Integer, ? extends ClusterObject>> cacheEntryEvents) throws CacheEntryListenerException {
                   printEvents(cacheEntryEvents);
                }

               private void printEvents(Iterable<CacheEntryEvent<? extends Integer, ? extends ClusterObject>> cacheEntryEvents) {
                       Iterator<CacheEntryEvent<? extends Integer, ? extends ClusterObject>> iterator =           cacheEntryEvents.iterator();
                       while (iterator.hasNext()) {
                           CacheEntryEvent<? extends Integer, ? extends ClusterObject> next = iterator.next();
                           System.out.println(next.getEventType());
                       }
               }

    }

`

But these changes cause this Exception:

`

    [2016-11-23T16:58:03.481+0100] [Payara 4.1] [SEVERE] []      [com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor] [tid: _ThreadID=65 _ThreadName=hz._hzInstance_1_development.generic-operation.thread-1] [timeMillis: 1479916683481]      [levelValue: 1000] [[
      [10.0.0.166]:5901 [development] [3.6.4] Failed to process packet: Packet{header=1, isResponse=false, isOperation=true, isEvent=false, partitionId=-1, conn=Connection [/10.0.0.166:5901 -> /10.0.0.195:16498], endpoint=Address[10.0.0.195]:5902, alive=true, type=MEMBER} on hz._hzInstance_1_development.generic-operation.thread-1
    [development] [3.6.4] java.lang.ClassNotFoundException: com.ClusterObject
    com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: com.ClusterObject
	   at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$ClassSerializer.read(JavaDefaultSerializers.java:181)
	   at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$ClassSerializer.read(JavaDefaultSerializers.java:169)
	   at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
	   at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:214)
	   at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:600)
	   at com.hazelcast.config.CacheConfig.readData(CacheConfig.java:543)
	   at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:121)
	   at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:47)
	   at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
	   at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:214)
	   at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:600)
	   at com.hazelcast.cache.impl.operation.CacheCreateConfigOperation.readInternal(CacheCreateConfigOperation.java:166)
	   at com.hazelcast.spi.Operation.readData(Operation.java:557)
	   at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:121)
	   at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:47)
	   at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
	   at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:170)
	   at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:234)
	   at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:378)
	   at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:184)
	   at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:137)
	   at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124)
	   at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99)
    Caused by: java.lang.ClassNotFoundException: com.ClusterObject
	    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	    at com.sun.enterprise.loader.CurrentBeforeParentClassLoader.loadClass(CurrentBeforeParentClassLoader.java:82)
	    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	    at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:137)
	    at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:115)
	    at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$ClassSerializer.read(JavaDefaultSerializers.java:179)
	... 22 more
    ]]

`
and...

`

    [2016-11-23T16:58:03.517+0100] [Payara 4.1] [SEVERE] [] [com.hazelcast.spi.OperationService] [tid: _ThreadID=65 _ThreadName=hz._hzInstance_1_development.generic-operation.thread-1] [timeMillis: 1479916683517] [levelValue: 1000] [[
      [10.0.0.166]:5901 [development] [3.6.4] java.lang.ClassNotFoundException: com.ClusterCacheEntryListenerFactory
    com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException:     com.ClusterCacheEntryListenerFactory
	    at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:224)
	    at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
	    at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:214)
	    at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:600)
	    at com.hazelcast.config.CacheConfig.readData(CacheConfig.java:563)
	    at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:121)
	    at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:47)
	    at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:214)
	    at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:600)
	    at com.hazelcast.cache.impl.operation.CacheCreateConfigOperation.readInternal(CacheCreateConfigOperation.java:166)
	    at com.hazelcast.spi.Operation.readData(Operation.java:557)
	    at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:121)
	    at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:47)
	    at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
	    at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:170)
	    at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:234)
	    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:378)
	    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:184)
	    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:137)
	    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124)
	    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99)
    Caused by: java.lang.ClassNotFoundException: com.ClusterCacheEntryListenerFactory
	    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	    at com.sun.enterprise.loader.CurrentBeforeParentClassLoader.loadClass(CurrentBeforeParentClassLoader.java:82)
	    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	    at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:137)
	    at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:115)
	    at com.hazelcast.nio.IOUtil$1.resolveClass(IOUtil.java:114)
	    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620)
	    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
	    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
	    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	    at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:219)
	... 21 more
    ]]

`

Have you any ideas?

## Environment ##

- **Payara Version**: 4.1.1.163
- **Edition**: Full
- **JDK Version**:  8  - Oracle
- **Operating System**: Linux

**Comment by stePrime** [comment]
I tried to share websockets message by Hazelcast executor service. My task implements Runnable & Serializable but when i called executorService.executeOnAllMembers(new MyTask(input)), this throws com.hazelcast.nio.serialization.HazelcastSerializationExcept‌​ion: java.lang.ClassNotFoundException: com.MyTask on the other Nodes. Just, FYI I retrieve Hazelcast Instance in this way :

`

    Context ctx = new InitialContext(); 
    HazelcastInstance instance = (HazelcastInstance) ctx.lookup("payara/Hazelcast"); 

`

**Comment by smillidge** [comment]
Problem with these capabilities is classloading. As the Hazelcast operations threads are created at server boot they do not have access to the classloader for the application. The simplest solution is to create a library just for your executors or listeners and add it to the glassfish/lib directory so that these classes are on the server classpath.

We are working on a way to get application modules loaded by the Hazelcast internal threads but we don't have it fixed yet.

**Comment by fturizo** [comment]
@smillidge, is this issue related to the same classloading issue reported on issue #759? Should we move this issue to JIRA to track the progress done on it?

@stePrime, did @smillidge suggested workaround of using a common library with the listener classes on the lib directory solve the issue?

**Comment by stePrime** [comment]
I have done several tests and I can confirm that create a library has solved the problem. 
Now, I close the issue. Thank you for the support.

**Comment by jerrinot** [comment]
I presume this could be workarounded by Payara: Start Hazelcast member per Payara instance and Hazelcast client per each webapp deployed: This way you can configure clients to use the right webapp classloader. 

This could solve problems with listeners, or in general everywhere where a client is deserializing stuff.  However it won't solve the issue from #759 - as in this case it's always a member deserializing binary data.

**Comment by lprimak** [comment]
Yes indeed, and I have some ideas of #759
