### ISSUE TITLE
Custom JAAS module not working in 4.1.1.164

### ISSUE THREAD

**Issue by peraxel** [payara/Payara#1214]
# Description #
----------

I built a custom JAAS module to handle user auth. Worked like a charm in Payara 4.1.1.163, but in 4.1.1.164 it causes start up crash due to ClassCastException.

## Expected Outcome

Expected JAAS module to work as in 4.1.1.163.

## Current Outcome

Causes start up crash with log output as follows. In this case I only added my JAAS module JAR-file to domain/lib and added configuration to config/login.conf. So no configuration in config/domain.xml yet.

Warning:   Disabled realm [admin-realm] due to errors.
Warning:   Caught exception.
java.lang.ClassCastException: com.sun.enterprise.security.auth.realm.file.FileRealm cannot be cast to com.sun.enterprise.security.auth.realm.Realm
	at com.sun.enterprise.security.auth.realm.Realm.doInstantiate(Realm.java:325)
	at com.sun.enterprise.security.auth.realm.Realm.instantiate(Realm.java:225)
	at com.sun.enterprise.security.auth.realm.RealmConfig.createRealms(RealmConfig.java:83)
	at com.sun.enterprise.security.auth.realm.RealmsManager.createRealms(RealmsManager.java:278)
	at com.sun.enterprise.security.auth.realm.RealmsManager.createRealms(RealmsManager.java:211)
	at com.sun.enterprise.security.SecurityLifecycle.onInitialization(SecurityLifecycle.java:165)
	at com.sun.enterprise.security.SecurityLifecycle.postConstruct(SecurityLifecycle.java:208)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:326)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:374)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154)
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199)
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
	at com.sun.enterprise.security.ee.SecuritySniffer.setup(SecuritySniffer.java:115)
	at com.sun.enterprise.v3.server.ContainerStarter.startContainer(ContainerStarter.java:97)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.setupContainer(ApplicationLifecycle.java:998)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.setupContainerInfos(ApplicationLifecycle.java:703)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:378)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.processApplication(ApplicationLoaderService.java:406)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.postConstruct(ApplicationLoaderService.java:243)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:326)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:374)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:228)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Warning:   Disabled realm [file] due to errors.
Warning:   Caught exception.
java.lang.ClassCastException: com.sun.enterprise.security.auth.realm.file.FileRealm cannot be cast to com.sun.enterprise.security.auth.realm.Realm
	at com.sun.enterprise.security.auth.realm.Realm.doInstantiate(Realm.java:325)
	at com.sun.enterprise.security.auth.realm.Realm.instantiate(Realm.java:225)
	at com.sun.enterprise.security.auth.realm.RealmConfig.createRealms(RealmConfig.java:83)
	at com.sun.enterprise.security.auth.realm.RealmsManager.createRealms(RealmsManager.java:278)
	at com.sun.enterprise.security.auth.realm.RealmsManager.createRealms(RealmsManager.java:211)
	at com.sun.enterprise.security.SecurityLifecycle.onInitialization(SecurityLifecycle.java:165)
	at com.sun.enterprise.security.SecurityLifecycle.postConstruct(SecurityLifecycle.java:208)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:326)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:374)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154)
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199)
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
	at com.sun.enterprise.security.ee.SecuritySniffer.setup(SecuritySniffer.java:115)
	at com.sun.enterprise.v3.server.ContainerStarter.startContainer(ContainerStarter.java:97)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.setupContainer(ApplicationLifecycle.java:998)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.setupContainerInfos(ApplicationLifecycle.java:703)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:378)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.processApplication(ApplicationLoaderService.java:406)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.postConstruct(ApplicationLoaderService.java:243)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:326)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:374)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:228)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Warning:   Disabled realm [certificate] due to errors.
Warning:   Caught exception.
java.lang.ClassCastException: com.sun.enterprise.security.auth.realm.certificate.CertificateRealm cannot be cast to com.sun.enterprise.security.auth.realm.Realm
	at com.sun.enterprise.security.auth.realm.Realm.doInstantiate(Realm.java:325)
	at com.sun.enterprise.security.auth.realm.Realm.instantiate(Realm.java:225)
	at com.sun.enterprise.security.auth.realm.RealmConfig.createRealms(RealmConfig.java:83)
	at com.sun.enterprise.security.auth.realm.RealmsManager.createRealms(RealmsManager.java:278)
	at com.sun.enterprise.security.auth.realm.RealmsManager.createRealms(RealmsManager.java:211)
	at com.sun.enterprise.security.SecurityLifecycle.onInitialization(SecurityLifecycle.java:165)
	at com.sun.enterprise.security.SecurityLifecycle.postConstruct(SecurityLifecycle.java:208)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:326)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:374)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154)
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199)
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
	at com.sun.enterprise.security.ee.SecuritySniffer.setup(SecuritySniffer.java:115)
	at com.sun.enterprise.v3.server.ContainerStarter.startContainer(ContainerStarter.java:97)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.setupContainer(ApplicationLifecycle.java:998)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.setupContainerInfos(ApplicationLifecycle.java:703)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:378)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.processApplication(ApplicationLoaderService.java:406)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.postConstruct(ApplicationLoaderService.java:243)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:326)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:374)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:228)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

## Discussion

This is not really a bug report. I think the error is on my side as I think I'm using the wrong dependency to include import com.sun.enterprise.security.auth.realm.Realm in my custom JAAS module. My Maven dependencies are:
```
        <dependency>
            <groupId>org.glassfish.main.common</groupId>
            <artifactId>glassfish-ee-api</artifactId>
            <version>4.1.1</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.main.security</groupId>
            <artifactId>security</artifactId>
            <version>4.1</version>
        </dependency>
```

I guess you've made some custom packages for Payara with other versions than the ones above, but they are not available on Maven Central. What's the preferred way of referencing Payara packages as dependencies for this use-case?

**Comment by OndrejM** [comment]
I don't think that there was any change in security classes between Payara 163 and 164.

Would you check if the JAR file of the JAAS module contains any of the following classes?
 - `com.sun.enterprise.security.auth.realm.Realm`
 - `com.sun.enterprise.security.auth.realm.file.FileRealm`
 - `com.sun.enterprise.security.auth.realm.certificate.CertificateRealm` 

I would also rather build against GlassFish 4.1.1 dependencies, but that should also apply for Payara 163.

**Comment by peraxel** [comment]
Corrected the scope of the dependencies in pom.xml to 'provided'. That seems to have resolved the issue on 164. The server starts without errors now. Will verify functionality of the JAAS module asap.

**Comment by peraxel** [comment]
Works like a charm!
I admit the error was in my JAAS module, but still strange that it did work on 163 but not on 164. 
Closing.
