### ISSUE TITLE
URLs containing colons will fail

### ISSUE THREAD

**Issue by hobrom** [payara/Payara#1243]
# Description #
----------

regarding security fix [PAYARA-989 #1024](https://github.com/payara/Payara/pull/1024)

## Current Outcome

`Paths.get( xxx )` will throw an `InvalidPathException` if the originating request URL contains characters not allowed in your operating system's file-system path (e.g. colon ':' on Windows).

## Steps to reproduce
I'm using apache isis, which heavily depends on URLs like `http://localhost:8080/myapp/w/entity/domainapp.dom.refund.WorkContract:1`. Note the colon at the end! Those URLs provoke an exception!

```
java.nio.file.InvalidPathException: Illegal char <:> at index 43: /w/entity/domainapp.dom.refund.WorkContract:1
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.apache.catalina.core.StandardContextValve.preInvoke(StandardContextValve.java:291)
```

## Environment ##

- **Payara Version**: 4.1.1.164
- **Edition**: Full
- **JDK Version**:  8 OracleJDK
- **Operating System**: Windows

**Comment by lprimak** [comment]
On the list... who knew?

**Comment by lprimak** [comment]
Fixed in the next Payara release
