### ISSUE TITLE
Sporadic lookup failure when injecting EJB into Singleton Startup EJB

### ISSUE THREAD

**Issue by chrjohn** [payara/Payara#1279]
# Description #
----------

Sometimes we get Exceptions on Payara startup that a Singleton Startup bean could not be correctly initialized. The reason for this is that an EJB (Stateless non-Singleton) which should get injected into the Singleton bean is not yet available.

The Singleton bean is part of a WAB (web application bundle, OSGi), so it is a WAR file. I heard somewhere that WARs are deployed differently from JARs (even concurrently?), so maybe this is the basic problem.

I have condensed a minimal test case which exhibits the problem.

## Expected Outcome

I would expect that Payara handles the deployment in a way that it should deploy dependent EJBs first. When starting up the the Singleton bean, the needed EJBs need to be available.

## Current Outcome

In about one third of the cases the startup of the bundle which contains the Singleton bean fails. It might be happening more frequently when clearing the osgi-cache folder before startup of Payara. But this might have been coincidental.

## Steps to reproduce (Only for bug reports) 

1 - setup a new domain
2 - start the domain
3 - deploy attached bundles (rename to have JAR/WAR ending) - payarabug-singletonstartup-0.0.1-SNAPSHOT needs WAR ending, the others JAR ending
```
asadmin --terse deploy --force --type osgi payarabug-singletonstartup-interface-0.0.1-SNAPSHOT.jar
asadmin --terse deploy --force --type osgi payarabug-singletonstartup-implementation-0.0.1-SNAPSHOT.jar
asadmin --terse deploy --force --type osgi payarabug-singletonstartup-0.0.1-SNAPSHOT.war
```
4- restart Payara a few times and wait for an error like this:

```
[2017-01-10T16:56:30.777+0100] [Payara 4.1] [WARNING] [] [org.glassfish.osgijavaeebase] [tid: _ThreadID=71 _ThreadName=Thread-16] [timeMillis: 1484063790777] [levelValue: 900] [[
  Failed to deploy bundle com.macd.payarabug-singletonstartup [322]
org.glassfish.osgijavaeebase.DeploymentException: Deployment of com.macd.payarabug-singletonstartup [322] failed because of following reason: Failed while deploying bundle com.macd.payarabug-singletonstartup [322] : java.lang.RuntimeException: Failed to deploy bundl
e [ com.macd.payarabug-singletonstartup [322] ], root cause: Exception while loading the app
        at org.glassfish.osgijavaeebase.AbstractOSGiDeployer.deploy(AbstractOSGiDeployer.java:127)
        at org.glassfish.osgijavaeebase.OSGiContainer.deploy(OSGiContainer.java:154)
        at org.glassfish.osgijavaeebase.OSGiContainer.redeploy(OSGiContainer.java:113)
        at org.glassfish.osgijavaeebase.OSGiContainer.access$500(OSGiContainer.java:61)
        at org.glassfish.osgijavaeebase.OSGiContainer$DeployerAddedThread.run(OSGiContainer.java:305)
Caused by: java.lang.RuntimeException: Failed to deploy bundle [ com.macd.payarabug-singletonstartup [322] ], root cause: Exception while loading the app
        at org.glassfish.osgijavaeebase.OSGiDeploymentRequest.deploy(OSGiDeploymentRequest.java:198)
        at org.glassfish.osgijavaeebase.OSGiDeploymentRequest.execute(OSGiDeploymentRequest.java:120)
        at org.glassfish.osgijavaeebase.AbstractOSGiDeployer.deploy(AbstractOSGiDeployer.java:123)
        ... 4 more
Caused by: javax.ejb.EJBException: javax.ejb.CreateException: Initialization failed for Singleton PayaraBugSingleton
        at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:649)
        at com.sun.ejb.containers.AbstractSingletonContainer.instantiateSingletonInstance(AbstractSingletonContainer.java:389)
        at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:219)
        at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:180)
        at org.glassfish.ejb.startup.SingletonLifeCycleManager.doStartup(SingletonLifeCycleManager.java:158)
        at org.glassfish.ejb.startup.EjbApplication.start(EjbApplication.java:169)
        at org.glassfish.internal.data.EngineRef.start(EngineRef.java:122)
        at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:291)
        at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:353)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:501)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
        at org.glassfish.osgijavaeebase.OSGiDeploymentRequest.deploy(OSGiDeploymentRequest.java:185)
        ... 6 more
... and so on
```

## Environment ##

- **Payara Version**: 4.1.1.162 / 4.1.1.164
- **Edition**: Full
- **JDK Version**: 1.8.0_112-b15
- **Operating System**: Linux

## Files ##

[payarabug-singletonstartup-interface-0.0.1-SNAPSHOT.ZIP](https://github.com/payara/Payara/files/696649/payarabug-singletonstartup-interface-0.0.1-SNAPSHOT.ZIP)
Contains interface of the EJB to be injected into the Singleton Startup EJB.

[payarabug-singletonstartup-implementation-0.0.1-SNAPSHOT.ZIP](https://github.com/payara/Payara/files/696648/payarabug-singletonstartup-implementation-0.0.1-SNAPSHOT.ZIP)
Contains implementation of the EJB to be injected into the Singleton Startup EJB.

[payarabug-singletonstartup-0.0.1-SNAPSHOT.ZIP](https://github.com/payara/Payara/files/696647/payarabug-singletonstartup-0.0.1-SNAPSHOT.ZIP)
Contains the Singleton Startup EJB.

**Comment by smillidge** [comment]
Please try Payara 5 and see if it is still a problem there.

**Comment by OndroMih** [comment]
Hi, we weren't able to reproduce this issue on the latest Payara 5. We'll reopen this issue if you provide us a reproducer for the latest version of Payara Server.

**Comment by chrjohn** [comment]
Hi @OndroMih , @smillidge ,

the problem seems to persist on newer versions of Payara. I have opened #4945 since the problem seems to be a little different.
