### ISSUE TITLE
ConcurrentModificationException in HazelcastTimerStore

### ISSUE THREAD

**Issue by maxencelaurent** [payara/Payara#1314]
# Description #
----------
When adding a micro instance within a running cluster, a ConcurrentModificationException is (sometimes) thrown by HazelcastTimerStore. This occurs while restoring  timers during deployment.

This issue has been mentioned by @dorpsidioot in #1112. 

## Expected Outcome

war deployed without exceptions and a running app 

## Current Outcome

war not deployed, need to try several times until the deploy success...

Stack trace :
```
 [2017-01-25T08:40:53.669+0100] [Payara Micro 4.1] [SEVERE] [] [javax.enterprise.system.tools.deployment.common] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1485330053669] [levelValue: 1000] [[
  Exception while invoking class org.glassfish.ejb.startup.EjbApplication start method
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1471)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1469)
        at fish.payara.ejb.timer.hazelcast.HazelcastTimerStore.recoverAndCreateSchedules(HazelcastTimerStore.java:605)
        at com.sun.ejb.containers.BaseContainer.startApplication(BaseContainer.java:3955)
        at org.glassfish.ejb.startup.EjbApplication.start(EjbApplication.java:166)
        at org.glassfish.internal.data.EngineRef.start(EngineRef.java:122)
        at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:291)
        at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:353)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:501)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:487)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
        at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:134)
        at fish.payara.micro.PayaraMicro.deployAll(PayaraMicro.java:1594)
        at fish.payara.micro.PayaraMicro.bootStrap(PayaraMicro.java:1092)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:180)
]]
```

## Environment ##

- **Payara Version**: 4.1.1.164
- **Edition**:Micro
- **JDK Version**: OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14)
- **Operating System**: Linux 4.4.0-59

**Comment by maxencelaurent** [comment]
The exception is thrown because a map is modified while it is iterated, which is strictly forbidden. The fix is quite straightforward. Just use an iterator and its remove method

**Comment by mikecroft** [comment]
Hi, @maxencelaurent thanks for the fix! If you could sign [our CLA](https://github.com/payara/Payara/blob/master/PayaraCLA.pdf) and send a PR, we'd love to include it

https://github.com/payara/Payara/blob/master/.github/CONTRIBUTING.md

**Comment by maxencelaurent** [comment]
CLA signed and sent, PR sent !
