### ISSUE TITLE
Payara-micro-171-SNAPSHOT and JDBC Connection pool registration failure 

### ISSUE THREAD

**Issue by maxencelaurent** [payara/Payara#1323]
# Description #
----------

PayaraMicro 171-snapshot fails to register jdbc-connection-pools defined in domain.xml.

Relevant log messages are:
```
[2017-01-27T10:04:09.756+0100] [] [WARNING] [] [javax.enterprise.resource.resourceadapter.org.glassfish.jdbc.util] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1485507849756] [levelValue: 900] RAR8068: Using default datasource : __ds_jdbc_ra for pool : jdbc/dummy_pool

[2017-01-27T10:04:09.758+0100] [] [WARNING] [] [javax.enterprise.resource.resourceadapter.org.glassfish.jdbc.deployer] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1485507849758] [levelValue: 900] error.creating.jdbc.pool

[2017-01-27T10:04:09.759+0100] [] [SEVERE] [] [javax.enterprise.resource.resourceadapter.com.sun.enterprise.connectors.service] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1485507849759] [levelValue: 1000] RAR8060: Unable to lookup pool [ jdbc/dummy_pool ], javax.naming.NamingException: Lookup failed for '__SYSTEM/pools/jdbc/dummy_pool' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: pools]

[2017-01-27T11:20:28.504+0100] [] [WARNING] [] [javax.enterprise.resource.resourceadapter.com.sun.enterprise.connectors.service] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1485512428504] [levelValue: 900] RAR5114 : Error allocating connection : [This pool is not registered with the runtime environment : jdbc/dummy_pool]
```

The first log message shows something went wrong with JDBC resource adapter "__ds_jdbc_ra".

Previous to version 171, jdbc resource adapters stand in the lib/install/applications domain directory :
```
cd  defaultPayaraMicro-4.1.1.164-RootDir:
ls lib/install/applications/*
lib/install/applications/__cp_jdbc_ra:
__cp_jdbc_ra.jar  META-INF

lib/install/applications/__dm_jdbc_ra:
__dm_jdbc_ra.jar  META-INF

lib/install/applications/__ds_jdbc_ra:
__ds_jdbc_ra.jar  META-INF

lib/install/applications/__xa_jdbc_ra:
META-INF  __xa_jdbc_ra.jar
```

With the new Payara Micro structure, those JAR are archived within RAR files and stand within the runtime directory:
```
cd defaultPayaraMicro-4.1.1.164-RootDir
find . -name "*_jdbc_ra*"
./runtime/__xa_jdbc_ra.rar
./runtime/__ds_jdbc_ra.rar
./runtime/__cp_jdbc_ra.rar
./runtime/__dm_jdbc_ra.rar
```

by the way, unrar-ing one of them give: 

```
unrar l __xa_jdbc_ra.rar 
__xa_jdbc_ra.rar is not RAR archive
```

but unzip-ing it is successfull:
```
unzip -l __xa_jdbc_ra.rar
Archive:  __xa_jdbc_ra.rar
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2017-01-26 13:49   META-INF/
      101  2017-01-26 13:49   META-INF/MANIFEST.MF
        0  2017-01-26 13:49   lib/
        0  2017-01-26 13:48   lib/install/
        0  2017-01-26 13:49   lib/install/applications/
        0  2017-01-26 13:49   lib/install/applications/__xa_jdbc_ra/
        0  2017-01-26 13:49   lib/install/applications/__xa_jdbc_ra/META-INF/
      512  2017-01-26 13:48   lib/install/applications/__xa_jdbc_ra/META-INF/MANIFEST.MF
   170954  2017-01-26 13:48   lib/install/applications/__xa_jdbc_ra/__xa_jdbc_ra.jar
---------                     -------
   171567                     9 files
```

Put those four resource adapters in the PayaraMicro-171 rootDir/lib/install/applications back resolves the problem.

## Steps to reproduce 

1. populate a rootdir
2. add a jdbc-resource in the domain.xml
3. deploy an app that use this jdbc-resource

### Sample
Here is some steps to reproduce this issue using a postgresql server (running on localhost) and a test app I wrote (https://github.com/maxencelaurent/DummyJdbcConnectionPool) :   

Create postgres user and db
```
createuser --pwprompt dummyUser
  Enter password for new role: dummyPassword
  Enter it again: dummyPassword
createdb -O dummyUser dummy_db
```

Create a sandbox directory and get payara-micro-prerelease.jar (171-SNAPSHOT)
```
mkdir testJdbcResource
cd testJdbcResource
wget https://s3-eu-west-1.amazonaws.com/payara.fish/payara-micro-prerelease.jar
```

Fetch and build test application
```
git clone https://github.com/maxencelaurent/DummyJdbcConnectionPool.git
cd DummyJdbcConnectionPool
mvn install
cd ..
```

Create and populate rootDir
```
mkdir brandNewRootDir

java -jar payara-micro-prerelease.jar  --autoBindHttp  --rootDir brandNewRootDir --clustername hz-testJdbcResource
```

Kill micro instance with Ctrl^c once instance is ready.

Add postgresql driver
```
wget https://jdbc.postgresql.org/download/postgresql-9.4.1212.jar -P brandNewRootDir/lib/
# use the domain.xml from DummyJdbcConnectionPool (it just define the jdbc-resource and the jdbc-connection-pool) 
cp  DummyJdbcConnectionPool/domain.xml brandNewRootDir/config/domain.xml
```

restart instance
```
java -jar payara-micro-prerelease.jar --autoBindHttp --rootDir brandNewRootDir --clustername hz-testJdbcResource --deploy DummyJdbcConnectionPool/target/TestJdbcConnectionPool-1.0-SNAPSHOT.war
```

Voilà !

#### To Solve
To solve the problem, put jdbc resource adapters back and restart instance
```
cp -R DummyJdbcConnectionPool/lib/install brandNewRootDir/lib/
java -jar payara-micro-prerelease.jar --autoBindHttp --rootDir brandNewRootDir --clustername hz-testJdbcResource --deploy DummyJdbcConnectionPool/target/TestJdbcConnectionPool-1.0-SNAPSHOT.war
```

To test, simply run: 
` echo "\d"  | psql -U dummyUser dummy_db `

output should be something like: 
```
            List of relations
 Schema |    Name     | Type  |   Owner   
--------+-------------+-------+-----------
 public | dummyentity | table | dummyUser
 public | sequence    | table | dummyUser
(2 rows)
```

### Clean SandBox
remove psql user and db: 
```
dropdb dummy_db
dropuser dummyUser
```

Remove your testJdbcResource directory 

## Environment ##

- **Payara Version**: 4.1.1.171 (SNAPSHOT)
- **Edition**: Micro
- **JDK Version**: OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14)
- **Operating System**: Linux

**Comment by smillidge** [comment]
Thanks for the report we'll investigate. Have you also tried deploying a datasource within the war file?

**Comment by maxencelaurent** [comment]
Nope, I didn't try. I'll test right now

**Comment by maxencelaurent** [comment]
I checked out https://github.com/payara/Payara-Examples/tree/master/Payara-Micro/datasource-example and made some changes in order to use a postgresql database.

I got almost the same error when  loading : http://localhost:8080/datasource-example-1.0-SNAPSHOT/SelectServlet

```
[2017-01-27T16:51:48.451+0100] [] [WARNING] [] [javax.enterprise.resource.resourceadapter.org.glassfish.jdbc.deployer] [tid: _ThreadID=18 _ThreadName=http-thread-pool::http-listener(1)] [timeMillis: 1485532308451] [levelValue: 900] error.creating.jdbc.pool

[2017-01-27T16:51:48.461+0100] [] [INFO] [] [javax.enterprise.web] [tid: _ThreadID=18 _ThreadName=http-thread-pool::http-listener(1)] [timeMillis: 1485532308461] [levelValue: 800] WebModule[null] ServletContext.log():Marking servlet SelectServlet as unavailable

[2017-01-27T16:51:48.463+0100] [] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=18 _ThreadName=http-thread-pool::http-listener(1)] [timeMillis: 1485532308463] [levelValue: 900] [[
  StandardWrapperValve[SelectServlet]: Allocate exception for servlet SelectServlet
java.lang.RuntimeException: No pool by name [ __SYSTEM/pools/__datasource_definition/java:global/ExampleDataSource ] found
	at com.sun.enterprise.connectors.ConnectorRuntime.getConnectionPoolConfig(ConnectorRuntime.java:1156)
	at com.sun.enterprise.connectors.service.ConnectorService.checkAndLoadPool(ConnectorService.java:321)
	at com.sun.enterprise.connectors.service.ConnectorResourceAdminServiceImpl.createConnectorResource(ConnectorResourceAdminServiceImpl.java:99)
	at com.sun.enterprise.connectors.ConnectorRuntime.createConnectorResource(ConnectorRuntime.java:345)
	at org.glassfish.jdbc.deployer.JdbcResourceDeployer.deployResource(JdbcResourceDeployer.java:111)
	at org.glassfish.jdbc.deployer.JdbcResourceDeployer.deployResource(JdbcResourceDeployer.java:130)
	at org.glassfish.jdbc.deployer.DataSourceDefinitionDeployer.deployResource(DataSourceDefinitionDeployer.java:134)
	at org.glassfish.javaee.services.CommonResourceProxy.create(CommonResourceProxy.java:88)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:480)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:438)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at com.sun.enterprise.naming.util.JndiNamingObjectFactory.create(JndiNamingObjectFactory.java:90)
	at com.sun.enterprise.naming.util.JndiInitializationNamingObjectFactory.create(JndiInitializationNamingObjectFactory.java:110)
	at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.lookup(GlassfishNamingManagerImpl.java:745)
	at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.lookup(GlassfishNamingManagerImpl.java:715)
	at com.sun.enterprise.naming.impl.JavaURLContext.lookup(JavaURLContext.java:159)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:471)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:438)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl._inject(InjectionManagerImpl.java:636)
	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl.inject(InjectionManagerImpl.java:507)
	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl.injectInstance(InjectionManagerImpl.java:141)
	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl.injectInstance(InjectionManagerImpl.java:127)
	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl.createManagedObject(InjectionManagerImpl.java:347)
	at com.sun.enterprise.web.WebContainer.createServletInstance(WebContainer.java:1001)
	at com.sun.enterprise.web.WebModule.createServletInstance(WebModule.java:2134)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1405)
	at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:1212)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:237)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:416)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:466)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:169)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:745)
]]
```

After restoring the lib/install/applications/__{cp,dm,ds,xa}_jdbc_ra.jar, everything works fine !

->  Executed PostgreSQL statement and got true

**Comment by maxencelaurent** [comment]
I only checked against a postgresql database. Both datasource-example and jpa-datasource-example adaptation for PostgreSQL can be found here: https://github.com/maxencelaurent/Payara-Examples/tree/psql-datasources (datasource-example-psql and jpa-datasource-example-psql modules in the Payara-Micro directory)

**Comment by smillidge** [comment]
Thanks we are just entering testing so good catch. 👍
