### ISSUE TITLE
Unable to deploy exploded war with payara-micro

### ISSUE THREAD

**Issue by maxencelaurent** [payara/Payara#1355]
# Description #
----------

According to [the documentation](https://payara.gitbooks.io/payara-server/content/documentation/payara-micro/deploying/deploy-cmd-line.html), one should be able to deploy an exploded war using the --deploy command-line option.

This is not working because fish.payara.micro.cmd.options.RUNTIME_OPTION.deploy defines a FileValidator that prevent the given file being a directory.
 
Commenting the !isDirectory assertion in fish.payara.micro.cmd.options.FileValidator resolves the bug :

```
/*
if (file.isDirectory()) {
            throw new ValidationException(MessageFormat.format(RuntimeOptions.bundle.getString("fileIsDirectory"),optionValue));
}
*/
```

After the fix, I'm able to deploy such an exploded war.

## Expected Outcome
exploded war specified using the payara-micro --deploy option shall be deployed.

## Current Outcome
```
$ java -jar payara-micro-171-SNAPSHOT.jar --deploy MyApp/
Feb 08, 2017 2:41:18 PM fish.payara.micro.impl.PayaraMicroImpl scanArgs
SEVERE: --deploy File MyApp/ is a directory

```

## Steps to reproduce

1. let MyApp.war be a valid war: explode it (eg. unzip -x MyApp.war -d MyApp)
2. java -jar payara-micro.jar --deploy MyApp

## Environment ##

- **Payara Version**: 4.1.1.171-SNAPSHOT
- **Edition**: Micro
- **JDK Version**: 8u121 OpenJDK
- **Operating System**: Linux

**Comment by maxencelaurent** [comment]
I quickly wrote a fix by adding a FileSystemItemValidator (extended by FileValidator and DirectoryValidator). The new validator allow to specify whether files and/or directories are allowed. 

Moreover, I detect another small issue, which is also address by the fix. If a file is given instead of a directory, DirectoryValidator does't throw an error.

Before the fix:
```
$ touch aFile
$ java -jar payara-micro-171-SNAPSHOT.jar --deployDir aFile
[2017-02-08T16:39:07.945+0100] [] [INFO] [] [fish.payara.micro.boot.runtime.PayaraMicroRuntimeBuilder] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1486568347945] [levelValue: 800] Built Payara Micro Runtime
[...]
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
	at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:72)
	at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:358)
Caused by: java.lang.NullPointerException
	at fish.payara.micro.impl.PayaraMicroImpl.deployAll(PayaraMicroImpl.java:1344)
	at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1005)
	at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:201)
```

After the fix:
```
$ touch aFile
$ java -jar payara-micro-171-SNAPSHOT.jar --deployDir aFile
Feb 08, 2017 5:01:44 PM fish.payara.micro.impl.PayaraMicroImpl scanArgs
SEVERE: --deployDir Directory aFile does not exist
```

**Comment by mikecroft** [comment]
Hi @maxencelaurent thanks! I've confirmed the bug, it's a regression in 171-SNAPSHOT. We already have a CLA from you, so could you make a PR with your fix please?

**Comment by mikecroft** [comment]
Internal issue ID: `PAYARA-1421`
