### ISSUE TITLE
Payara Micro 4.1.1.171 don't run on Windows 10

### ISSUE THREAD

**Issue by khasunuma** [payara/Payara#1396]
# Description #
----------

Payara Micro 4.1.1.171 don't run on Windows 10 with throwing exceptions. 

On Solaris 11.2, it runs well.

## Expected Outcome

Payara Micro should be run only following command;

```
java -jar payara-micro-4.1.1.171.jar
```

Then it shows log messages to console and wait. For example, Payara Micro 4.1.1.164 on same environment shows such log messages.

```
C:\Users\Kenji\Downloads>java -jar payara-micro-4.1.1.164.jar
[2017-02-18T23:46:32.762+0900] [Payara Micro 4.1] [INFO] [NCLS-CORE-00087] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429192762] [levelValue: 800] Grizzly Framework 2.3.28 started in: 138ms - bound to [/0.0.0.0:8080]

[2017-02-18T23:46:32.796+0900] [Payara Micro 4.1] [INFO] [NCLS-CORE-00058] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429192796] [levelValue: 800] Network listener https-listener on port 8443 disabled per domain.xml

[2017-02-18T23:46:32.916+0900] [Payara Micro 4.1] [INFO] [SEC-SVCS-00100] [javax.enterprise.security.services] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429192916] [levelValue: 800] Authorization Service has successfully initialized.

[2017-02-18T23:46:32.950+0900] [Payara Micro 4.1] [INFO] [] [org.glassfish.ha.store.spi.BackingStoreFactoryRegistry] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429192950] [levelValue: 800] Registered fish.payara.ha.hazelcast.store.HazelcastBackingStoreFactoryProxy for persistence-type = hazelcast in BackingStoreFactoryRegistry

[2017-02-18T23:46:32.951+0900] [Payara Micro 4.1] [INFO] [] [fish.payara.ha.hazelcast.store.HazelcastBackingStoreFactory] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429192951] [levelValue: 800] Registered Hazelcast BackingStoreFactory with persistence-type = hazelcast

[2017-02-18T23:46:33.319+0900] [Payara Micro 4.1] [INFO] [] [org.hibernate.validator.internal.util.Version] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429193319] [levelValue: 800] HV000001: Hibernate Validator 5.1.2.Final

[2017-02-18T23:46:33.759+0900] [Payara Micro 4.1] [INFO] [] [com.hazelcast.instance.DefaultAddressPicker] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429193759] [levelValue: 800] [LOCAL] [development] [3.7.1] Prefer IPv4 stack is true.

[2017-02-18T23:46:33.801+0900] [Payara Micro 4.1] [INFO] [] [com.hazelcast.instance.DefaultAddressPicker] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429193801] [levelValue: 800] [LOCAL] [development] [3.7.1] Picked [192.168.184.67]:5900, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5900], bind any local is true

[2017-02-18T23:46:33.817+0900] [Payara Micro 4.1] [INFO] [] [com.hazelcast.system] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429193817] [levelValue: 800] [192.168.184.67]:5900 [development] [3.7.1] Hazelcast 3.7.1 (20160905 - 1f47990) starting at [192.168.184.67]:5900

[2017-02-18T23:46:33.818+0900] [Payara Micro 4.1] [INFO] [] [com.hazelcast.system] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429193818] [levelValue: 800] [192.168.184.67]:5900 [development] [3.7.1] Copyright (c) 2008-2016, Hazelcast, Inc. All Rights Reserved.

[2017-02-18T23:46:33.819+0900] [Payara Micro 4.1] [INFO] [] [com.hazelcast.system] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429193819] [levelValue: 800] [192.168.184.67]:5900 [development] [3.7.1] Configured Hazelcast Serialization version : 1

[2017-02-18T23:46:33.946+0900] [Payara Micro 4.1] [INFO] [] [com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429193946] [levelValue: 800] [192.168.184.67]:5900 [development] [3.7.1] Backpressure is disabled

[2017-02-18T23:46:34.663+0900] [Payara Micro 4.1] [INFO] [] [com.hazelcast.instance.Node] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429194663] [levelValue: 800] [192.168.184.67]:5900 [development] [3.7.1] Creating MulticastJoiner

[2017-02-18T23:46:34.674+0900] [Payara Micro 4.1] [INFO] [] [com.hazelcast.core.LifecycleService] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429194674] [levelValue: 800] [192.168.184.67]:5900 [development] [3.7.1] [192.168.184.67]:5900 is STARTING

[2017-02-18T23:46:34.855+0900] [Payara Micro 4.1] [INFO] [] [com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429194855] [levelValue: 800] [192.168.184.67]:5900 [development] [3.7.1] Starting 4 partition threads

[2017-02-18T23:46:34.858+0900] [Payara Micro 4.1] [INFO] [] [com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429194858] [levelValue: 800] [192.168.184.67]:5900 [development] [3.7.1] Starting 3 generic threads (1 dedicated for priority tasks)

[2017-02-18T23:46:34.878+0900] [Payara Micro 4.1] [INFO] [] [com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThreadingModel] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429194878] [levelValue: 800] [192.168.184.67]:5900 [development] [3.7.1] TcpIpConnectionManager configured with Non Blocking IO-threading model: 3 input threads and 3 output threads

[2017-02-18T23:46:37.570+0900] [Payara Micro 4.1] [INFO] [] [com.hazelcast.internal.cluster.impl.MulticastJoiner] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429197570] [levelValue: 800] [192.168.184.67]:5900 [development] [3.7.1] 


Members [1] {
        Member [192.168.184.67]:5900 - c9cd6bc9-2b44-4f8b-8f70-a89d9dc93655 this
}


[2017-02-18T23:46:37.635+0900] [Payara Micro 4.1] [INFO] [] [com.hazelcast.internal.jmx.ManagementService] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429197635] [levelValue: 800] [192.168.184.67]:5900 [development] [3.7.1] Hazelcast JMX agent enabled.

[2017-02-18T23:46:37.786+0900] [Payara Micro 4.1] [INFO] [] [com.hazelcast.core.LifecycleService] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429197786] [levelValue: 800] [192.168.184.67]:5900 [development] [3.7.1] [192.168.184.67]:5900 is STARTED

[2017-02-18T23:46:37.840+0900] [Payara Micro 4.1] [INFO] [NCLS-CORE-00017] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429197840] [levelValue: 800] Payara Micro  4.1.1.164 #badassmicrofish (28) startup time : Embedded (654ms), startup services(5,890ms), total(6,544ms)

[2017-02-18T23:46:37.858+0900] [Payara Micro 4.1] [INFO] [] [fish.payara.nucleus.notification.NotificationService] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429197858] [levelValue: 800] Payara Notification Service Started with configuration: NotificationExecutionOptions{enabled=true, notifierConfigurationExecutionOptionsList={LOG=NotifierConfigurationExecutionOptions{notifierType=LOG, enabled=true}}}

[2017-02-18T23:46:37.892+0900] [Payara Micro 4.1] [INFO] [] [fish.payara.nucleus.hazelcast.HazelcastCore] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429197892] [levelValue: 800] Hazelcast Instance Bound to JNDI at payara/Hazelcast

[2017-02-18T23:46:37.893+0900] [Payara Micro 4.1] [INFO] [] [fish.payara.nucleus.hazelcast.HazelcastCore] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429197893] [levelValue: 800] JSR107 Caching Provider Bound to JNDI at payara/CachingProvider

[2017-02-18T23:46:37.902+0900] [Payara Micro 4.1] [INFO] [] [fish.payara.nucleus.hazelcast.HazelcastCore] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429197902] [levelValue: 800] JSR107 Default Cache Manager Bound to JNDI at payara/CacheManager

[2017-02-18T23:46:37.930+0900] [Payara Micro 4.1] [INFO] [] [fish.payara.nucleus.util.CleanupPostBoot] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429197930] [levelValue: 800] Cleaning JarFileFactory Cache to prevent jar FD leaks

[2017-02-18T23:46:37.939+0900] [Payara Micro 4.1] [INFO] [] [com.hazelcast.internal.partition.impl.PartitionStateManager] [tid: _ThreadID=34 _ThreadName=Executor-Service-6] [timeMillis: 1487429197939] [levelValue: 800] [192.168.184.67]:5900 [development] [3.7.1] Initializing cluster partition table arrangement...

[2017-02-18T23:46:38.083+0900] [Payara Micro 4.1] [INFO] [NCLS-JMX-00006] [javax.enterprise.system.jmx] [tid: _ThreadID=86 _ThreadName=Thread-4] [timeMillis: 1487429198083] [levelValue: 800] JMXStartupService has disabled JMXConnector system

[2017-02-18T23:46:38.137+0900] [Payara Micro 4.1] [INFO] [] [PayaraMicro] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429198137] [levelValue: 800] No META-INF/deploy directory

[2017-02-18T23:46:38.145+0900] [Payara Micro 4.1] [INFO] [] [PayaraMicro] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429198145] [levelValue: 800] Deployed 0 archives

[2017-02-18T23:46:38.175+0900] [Payara Micro 4.1] [INFO] [] [PayaraMicro] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429198175] [levelValue: 800] Payara Micro  4.1.1.164 #badassmicrofish (build 28) ready in 7063 (ms)
```

## Current Outcome

Payara Micro 4.1.1.174 shows such log messages and abort.

```
C:\Users\Kenji\Downloads>java -jar payara-micro-4.1.1.171.jar
[2017-02-18T23:43:52.523+0900] [] [INFO] [] [fish.payara.micro.boot.runtime.PayaraMicroRuntimeBuilder] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487429032523] [levelValue: 800] Built Payara Micro Runtime

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:72)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:358)
Caused by: A MultiException has 7 exceptions.  They are:
1. org.glassfish.hk2.api.UnsatisfiedDependencyException: There was no object available for injection at SystemInjecteeImpl(requiredType=AuthorizationService,parent=CommandSecurityChecker,qualifiers={},position=-1,optional=false,self=false,unqualified=null,1262237002)
2. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of com.sun.enterprise.admin.util.CommandSecurityChecker errors were found
3. java.lang.IllegalStateException: Unable to perform operation: resolve on com.sun.enterprise.admin.util.CommandSecurityChecker
4. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of com.sun.enterprise.v3.admin.CommandRunnerImpl errors were found
5. java.lang.IllegalStateException: Unable to perform operation: resolve on com.sun.enterprise.v3.admin.CommandRunnerImpl
6. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl errors were found
7. java.lang.IllegalStateException: Unable to perform operation: resolve on com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl

        at org.jvnet.hk2.internal.Collector.throwIfErrors(Collector.java:89)
        at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:249)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:357)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
        at org.jvnet.hk2.internal.PerLookupContext.findOrCreate(PerLookupContext.java:70)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:766)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:705)
        at fish.payara.micro.boot.runtime.MicroGlassFish.getService(MicroGlassFish.java:93)
        at fish.payara.micro.boot.runtime.MicroGlassFish.getCommandRunner(MicroGlassFish.java:108)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:999)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:201)
        ... 9 more
Caused by: org.glassfish.hk2.api.UnsatisfiedDependencyException: There was no object available for injection at SystemInjecteeImpl(requiredType=AuthorizationService,parent=CommandSecurityChecker,qualifiers={},position=-1,optional=false,self=false,unqualified=null,1262237002)
        at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:75)
        at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:211)
        at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:234)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:357)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
        at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83)
        at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71)
        at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154)
        at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199)
        at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:693)
        at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:78)
        at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:211)
        at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:234)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:357)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
        at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83)
        at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71)
        at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154)
        at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199)
        at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:680)
        at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:78)
        at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:211)
        at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:234)
        ... 19 more
java.lang.RuntimeException: Orb initialization erorr
        at org.glassfish.enterprise.iiop.api.GlassFishORBHelper.getORB(GlassFishORBHelper.java:191)
        at com.sun.enterprise.naming.impl.SerialContext.getORB(SerialContext.java:347)
        at com.sun.enterprise.naming.impl.SerialContext.getProviderCacheKey(SerialContext.java:354)
        at com.sun.enterprise.naming.impl.SerialContext.getRemoteProvider(SerialContext.java:384)
        at com.sun.enterprise.naming.impl.SerialContext.getProvider(SerialContext.java:329)
        at com.sun.enterprise.naming.impl.SerialContext.rebind(SerialContext.java:675)
        at com.sun.enterprise.naming.impl.SerialContext.rebind(SerialContext.java:692)
        at javax.naming.InitialContext.rebind(InitialContext.java:437)
        at javax.naming.InitialContext.rebind(InitialContext.java:437)
        at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.publishObject(GlassfishNamingManagerImpl.java:210)
        at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.publishObject(GlassfishNamingManagerImpl.java:196)
        at org.glassfish.kernel.javaee.MEJBService.postConstruct(MEJBService.java:88)
        at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:326)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:374)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:228)
        at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpOneLevel.run(CurrentTaskFuture.java:762)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpAllTheWay.go(CurrentTaskFuture.java:561)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpAllTheWay.access$100(CurrentTaskFuture.java:443)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture.go(CurrentTaskFuture.java:154)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture.go(CurrentTaskFuture.java:149)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.proceedTo(AsyncRunLevelContext.java:436)
        at org.glassfish.hk2.runlevel.internal.RunLevelControllerImpl.proceedTo(RunLevelControllerImpl.java:71)
        at com.sun.enterprise.v3.server.AppServerStartup.proceedTo(AppServerStartup.java:534)
        at com.sun.enterprise.v3.server.AppServerStartup.stop(AppServerStartup.java:487)
        at fish.payara.micro.boot.runtime.MicroGlassFish.stop(MicroGlassFish.java:75)
        at fish.payara.micro.impl.PayaraMicroImpl$1.run(PayaraMicroImpl.java:1434)
Caused by: java.lang.NullPointerException
        at org.glassfish.enterprise.iiop.api.GlassFishORBHelper.getORB(GlassFishORBHelper.java:163)
        ... 32 more
java.lang.RuntimeException: Orb initialization erorr
        at org.glassfish.enterprise.iiop.api.GlassFishORBHelper.getORB(GlassFishORBHelper.java:191)
        at com.sun.enterprise.naming.impl.SerialContext.getORB(SerialContext.java:347)
        at com.sun.enterprise.naming.impl.SerialContext.getProviderCacheKey(SerialContext.java:354)
        at com.sun.enterprise.naming.impl.SerialContext.getRemoteProvider(SerialContext.java:384)
        at com.sun.enterprise.naming.impl.SerialContext.getProvider(SerialContext.java:329)
        at com.sun.enterprise.naming.impl.SerialContext.rebind(SerialContext.java:675)
        at com.sun.enterprise.naming.impl.SerialContext.rebind(SerialContext.java:692)
        at javax.naming.InitialContext.rebind(InitialContext.java:437)
        at javax.naming.InitialContext.rebind(InitialContext.java:437)
        at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.publishObject(GlassfishNamingManagerImpl.java:210)
        at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.publishObject(GlassfishNamingManagerImpl.java:196)
        at org.glassfish.kernel.javaee.MEJBService.postConstruct(MEJBService.java:88)
        at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:326)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:374)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:228)
        at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpOneLevel.run(CurrentTaskFuture.java:762)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpAllTheWay.go(CurrentTaskFuture.java:561)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpAllTheWay.access$100(CurrentTaskFuture.java:443)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture.go(CurrentTaskFuture.java:154)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture.go(CurrentTaskFuture.java:149)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.proceedTo(AsyncRunLevelContext.java:436)
        at org.glassfish.hk2.runlevel.internal.RunLevelControllerImpl.proceedTo(RunLevelControllerImpl.java:71)
        at com.sun.enterprise.v3.server.AppServerStartup.proceedTo(AppServerStartup.java:534)
        at com.sun.enterprise.v3.server.AppServerStartup.stop(AppServerStartup.java:487)
        at fish.payara.micro.boot.runtime.MicroGlassFish.stop(MicroGlassFish.java:75)
        at fish.payara.micro.impl.PayaraMicroImpl$1.run(PayaraMicroImpl.java:1434)
Caused by: java.lang.NullPointerException
        at org.glassfish.enterprise.iiop.api.GlassFishORBHelper.getORB(GlassFishORBHelper.java:163)
        ... 32 more
java.lang.RuntimeException: Orb initialization erorr
        at org.glassfish.enterprise.iiop.api.GlassFishORBHelper.getORB(GlassFishORBHelper.java:191)
        at com.sun.enterprise.naming.impl.SerialContext.getORB(SerialContext.java:347)
        at com.sun.enterprise.naming.impl.SerialContext.getProviderCacheKey(SerialContext.java:354)
        at com.sun.enterprise.naming.impl.SerialContext.getRemoteProvider(SerialContext.java:384)
        at com.sun.enterprise.naming.impl.SerialContext.getProvider(SerialContext.java:329)
        at com.sun.enterprise.naming.impl.SerialContext.rebind(SerialContext.java:675)
        at com.sun.enterprise.naming.impl.SerialContext.rebind(SerialContext.java:692)
        at javax.naming.InitialContext.rebind(InitialContext.java:437)
        at javax.naming.InitialContext.rebind(InitialContext.java:437)
        at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.publishObject(GlassfishNamingManagerImpl.java:210)
        at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.publishObject(GlassfishNamingManagerImpl.java:196)
        at org.glassfish.kernel.javaee.MEJBService.postConstruct(MEJBService.java:88)
        at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:326)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:374)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:228)
        at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpOneLevel.run(CurrentTaskFuture.java:762)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpAllTheWay.go(CurrentTaskFuture.java:561)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpAllTheWay.access$100(CurrentTaskFuture.java:443)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture.go(CurrentTaskFuture.java:154)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture.go(CurrentTaskFuture.java:149)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.proceedTo(AsyncRunLevelContext.java:436)
        at org.glassfish.hk2.runlevel.internal.RunLevelControllerImpl.proceedTo(RunLevelControllerImpl.java:71)
        at com.sun.enterprise.v3.server.AppServerStartup.proceedTo(AppServerStartup.java:534)
        at com.sun.enterprise.v3.server.AppServerStartup.stop(AppServerStartup.java:487)
        at fish.payara.micro.boot.runtime.MicroGlassFish.stop(MicroGlassFish.java:75)
        at fish.payara.micro.impl.PayaraMicroImpl$1.run(PayaraMicroImpl.java:1434)
Caused by: java.lang.NullPointerException
        at org.glassfish.enterprise.iiop.api.GlassFishORBHelper.getORB(GlassFishORBHelper.java:163)
        ... 32 more
```

## Steps to reproduce (Only for bug reports) 

On Windows 10 console (command line), run `java -jar payara-micro-4.1.1.171.jar` command. Any options except `--help` are not influence to the result. (When to set `--help` option, it shows help messages.)

I test on Windows 10 Version 1607 (build 14393) and Solaris 11 Version 11.2 but not reproduce on Solaris 11. Perhaps it is happened only on Windows 10.

### Samples

No samples are needed to reproduce.

## Context (Optional)

I tried to read the source code of Payara Micro 4.1.1.171. But it is rewritten completely from Payara Micro 4.1.1.164 or earlier, so I can't resolve the problem immediately.

## Environment ##

- **Payara Version**: 4.1.1.171
- **Edition**: Micro
- **JDK Version**: 8 u121 - Oracle JDK
- **Operating System**: Windows

**Comment by smillidge** [comment]
Not sure how this got through automated testing. It looks like an error in the Java.policy file. I will investigate.

**Comment by smillidge** [comment]
This is due to a spurious '/' in the server.policy file packaged with payara micro. If you open up your Payara Micro jar and look for server.policy file in th MICRO-INF/domain/config directory in the jar you need to change the line;
```java
grant codeBase "file://${fish.payara.micro.UnpackDir}/-" {
```
to 
```java
grant codeBase "file:/${fish.payara.micro.UnpackDir}/-" {
```
Note the single '\'

**Comment by khasunuma** [comment]
I modified server.policy file and Payara Micro can run on Windows 10 OS. Thank you for your information.
