### ISSUE TITLE
Payara 171 Web Profile does not startup on macOS

### ISSUE THREAD

**Issue by VeitWeber** [payara/Payara#1408]
# Description #
----------
Payara 171 Web Profile does not startup on macOS, while full profile is fine. There are several exceptions in server.log:

```
[2017-02-22T13:35:00.769+0100] [] [INFO] [NCLS-GFLAUNCHER-00005] 
[javax.enterprise.launcher] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1487766900769] [levelValue: 800] [[
  JVM invocation command line:
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java
-cp
/Users/veit/Development/tooling/java/ee/appserver/payara/payara41117101_web/glassfish/modules/glassfish.jar
-XX:+UnlockDiagnosticVMOptions
-XX:NewRatio=2
-XX:+UseStringDeduplication
-XX:+UseG1GC
-Xmx2g
-Xms2g
-server
-javaagent:/Users/veit/Development/tooling/java/ee/appserver/payara/payara41117101_web/glassfish/lib/monitor/flashlight-agent.jar
-Djavax.xml.accessExternalSchema=all
-Djava.security.auth.login.config=/Users/veit/Development/tooling/java/ee/appserver/payara/payara41117101_web/glassfish/domains/payaradomain/config/login.conf
-Djavax.net.ssl.trustStore=/Users/veit/Development/tooling/java/ee/appserver/payara/payara41117101_web/glassfish/domains/payaradomain/config/cacerts.jks
-Dorg.glassfish.grizzly.DEFAULT_MEMORY_MANAGER=org.glassfish.grizzly.memory.HeapMemoryManager
-Djdk.tls.rejectClientInitiatedRenegotiation=true
-Djdk.corba.allowOutputStreamSubclass=true
-Dcom.sun.aas.instanceRoot=/Users/veit/Development/tooling/java/ee/appserver/payara/payara41117101_web/glassfish/domains/payaradomain
-Dcom.sun.aas.installRoot=/Users/veit/Development/tooling/java/ee/appserver/payara/payara41117101_web/glassfish
-Dcom.sun.enterprise.security.httpsOutboundKeyAlias=s1as
-Djava.endorsed.dirs=/Users/veit/Development/tooling/java/ee/appserver/payara/payara41117101_web/glassfish/modules/endorsed:/Users/veit/Development/tooling/java/ee/appserver/payara/payara41117101_web/glassfish/lib/endorsed
-Djava.security.policy=/Users/veit/Development/tooling/java/ee/appserver/payara/payara41117101_web/glassfish/domains/payaradomain/config/server.policy
-Dorg.jboss.weld.serialization.beanIdentifierIndexOptimization=false
-Dcom.sun.enterprise.config.config_environment_factory_class=com.sun.enterprise.config.serverbeans.AppserverConfigEnvironmentFactory
-DANTLR_USE_DIRECT_CLASS_LOADING=true
-Djava.awt.headless=true
-Djava.ext.dirs=/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/ext:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext:/Users/veit/Development/tooling/java/ee/appserver/payara/payara41117101_web/glassfish/domains/payaradomain/lib/ext
-Djdbc.drivers=org.apache.derby.jdbc.ClientDriver
-Djavax.net.ssl.keyStore=/Users/veit/Development/tooling/java/ee/appserver/payara/payara41117101_web/glassfish/domains/payaradomain/config/keystore.jks
-Djava.library.path=/Users/veit/Development/tooling/java/ee/appserver/payara/payara41117101_web/glassfish/lib:/Users/veit/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:/Users/veit/Development/tooling/java/ee/appserver/payara/payara41117101_web/bin
com.sun.enterprise.glassfish.bootstrap.ASMain
-upgrade
false
-domaindir
/Users/veit/Development/tooling/java/ee/appserver/payara/payara41117101_web/glassfish/domains/payaradomain
-read-stdin
true
-asadmin-args
--host,,,localhost,,,--port,,,4848,,,--secure=false,,,--terse=false,,,--echo=false,,,--interactive=true,,,start-domain,,,--verbose=false,,,--watchdog=false,,,--debug=false,,,--domaindir,,,/Users/veit/Development/tooling/java/ee/appserver/payara/payara41117101_web/glassfish/domains,,,payaradomain
-domainname
payaradomain
-instancename
server
-type
DAS
-verbose
false
-asadmin-classpath
/Users/veit/Development/tooling/java/ee/appserver/payara/payara41117101_web/glassfish/lib/client/appserver-cli.jar
-debug
false
-asadmin-classname
com.sun.enterprise.admin.cli.AdminMain
-watchdog
false]]

[2017-02-22T13:35:02.649+0100] [Payara 4.1] [INFO] [NCLS-LOGGING-00009] [javax.enterprise.logging] [tid: _ThreadID=18 _ThreadName=RunLevelControllerThread-1487766902573] [timeMillis: 1487766902649] [levelValue: 800] [[
  Running Payara Version: Payara Server  4.1.1.171 #badassfish (build 137)]]

[2017-02-22T13:35:02.651+0100] [Payara 4.1] [INFO] [NCLS-LOGGING-00010] [javax.enterprise.logging] [tid: _ThreadID=18 _ThreadName=RunLevelControllerThread-1487766902573] [timeMillis: 1487766902651] [levelValue: 800] [[
  Server log file is using Formatter class: com.sun.enterprise.server.logging.ODLLogFormatter]]

[2017-02-22T13:35:02.730+0100] [Payara 4.1] [INFO] [] [org.glassfish.ha.store.spi.BackingStoreFactoryRegistry] [tid: _ThreadID=19 _ThreadName=RunLevelControllerThread-1487766902579] [timeMillis: 1487766902730] [levelValue: 800] [[
  Registered org.glassfish.ha.store.adapter.cache.ShoalBackingStoreProxy for persistence-type = replicated in BackingStoreFactoryRegistry]]

[2017-02-22T13:35:02.747+0100] [Payara 4.1] [INFO] [NCLS-CORE-00015] [javax.enterprise.system.core] [tid: _ThreadID=17 _ThreadName=RunLevelControllerThread-1487766902572] [timeMillis: 1487766902747] [levelValue: 800] [[
  Shutdown requested
MultiException stack 1 of 2
com.sun.enterprise.module.ResolveError: Failed to start OSGiModuleImpl:: Bundle = [fish.payara.appserver.notification-jms-core [185]], State = [NEW]
	at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:217)
	at org.jvnet.hk2.osgiadapter.OsgiPopulatorPostProcessor$1.loadClass(OsgiPopulatorPostProcessor.java:78)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2173)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:454)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:473)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.isWouldBlockRightNow(CurrentTaskFuture.java:1170)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1206)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.osgi.framework.BundleException: Unresolved constraint in bundle fish.payara.appserver.notification-jms-core [185]: Unable to resolve 185.0: missing requirement [185.0] osgi.wiring.package; (osgi.wiring.package=javax.jms)
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:3974)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2037)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:955)
	at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:209)
	... 10 more
MultiException stack 2 of 2
java.lang.IllegalStateException: Could not load descriptor SystemDescriptor(
	implementation=fish.payara.notification.jms.JmsMessageQueue
	contracts={fish.payara.notification.jms.JmsMessageQueue,fish.payara.nucleus.notification.service.MessageQueue}
	scope=org.glassfish.hk2.runlevel.RunLevel
	qualifiers={}
	descriptorType=CLASS
	descriptorVisibility=NORMAL
	metadata=runLevelValue={10},Bundle-SymbolicName={fish.payara.appserver.notification-jms-core},Bundle-Version={4.1.1.171_0_1}
	rank=0
	loader=OsgiPopulatorPostProcessor.HK2Loader(OSGiModuleImpl:: Bundle = [fish.payara.appserver.notification-jms-core [185]], State = [NEW],1132890243)
	proxiable=null
	proxyForSameScope=null
	analysisName=null
	id=431
	locatorId=0
	identityHashCode=1122617030
	reified=false)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2182)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:454)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:473)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.isWouldBlockRightNow(CurrentTaskFuture.java:1170)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1206)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]

[2017-02-22T13:35:02.747+0100] [Payara 4.1] [INFO] [] [org.glassfish.ha.store.spi.BackingStoreFactoryRegistry] [tid: _ThreadID=19 _ThreadName=RunLevelControllerThread-1487766902579] [timeMillis: 1487766902747] [levelValue: 800] [[
  Registered fish.payara.ha.hazelcast.store.HazelcastBackingStoreFactoryProxy for persistence-type = hazelcast in BackingStoreFactoryRegistry]]

[2017-02-22T13:35:02.748+0100] [Payara 4.1] [SEVERE] [NCLS-CORE-00016] [javax.enterprise.system.core] [tid: _ThreadID=17 _ThreadName=RunLevelControllerThread-1487766902572] [timeMillis: 1487766902748] [levelValue: 1000] [[
  Startup service failed to start
MultiException stack 1 of 2
com.sun.enterprise.module.ResolveError: Failed to start OSGiModuleImpl:: Bundle = [fish.payara.appserver.notification-jms-core [185]], State = [NEW]
	at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:217)
	at org.jvnet.hk2.osgiadapter.OsgiPopulatorPostProcessor$1.loadClass(OsgiPopulatorPostProcessor.java:78)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2173)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:454)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:473)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.isWouldBlockRightNow(CurrentTaskFuture.java:1170)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1206)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.osgi.framework.BundleException: Unresolved constraint in bundle fish.payara.appserver.notification-jms-core [185]: Unable to resolve 185.0: missing requirement [185.0] osgi.wiring.package; (osgi.wiring.package=javax.jms)
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:3974)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2037)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:955)
	at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:209)
	... 10 more
MultiException stack 2 of 2
java.lang.IllegalStateException: Could not load descriptor SystemDescriptor(
	implementation=fish.payara.notification.jms.JmsMessageQueue
	contracts={fish.payara.notification.jms.JmsMessageQueue,fish.payara.nucleus.notification.service.MessageQueue}
	scope=org.glassfish.hk2.runlevel.RunLevel
	qualifiers={}
	descriptorType=CLASS
	descriptorVisibility=NORMAL
	metadata=runLevelValue={10},Bundle-SymbolicName={fish.payara.appserver.notification-jms-core},Bundle-Version={4.1.1.171_0_1}
	rank=0
	loader=OsgiPopulatorPostProcessor.HK2Loader(OSGiModuleImpl:: Bundle = [fish.payara.appserver.notification-jms-core [185]], State = [NEW],1132890243)
	proxiable=null
	proxyForSameScope=null
	analysisName=null
	id=431
	locatorId=0
	identityHashCode=1122617030
	reified=false)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2182)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:454)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:473)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.isWouldBlockRightNow(CurrentTaskFuture.java:1170)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1206)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]

[2017-02-22T13:35:02.749+0100] [Payara 4.1] [INFO] [] [fish.payara.ha.hazelcast.store.HazelcastBackingStoreFactory] [tid: _ThreadID=19 _ThreadName=RunLevelControllerThread-1487766902579] [timeMillis: 1487766902749] [levelValue: 800] [[
  Registered Hazelcast BackingStoreFactory with persistence-type = hazelcast]]

[2017-02-22T13:35:02.791+0100] [Payara 4.1] [INFO] [SEC-SVCS-00100] [javax.enterprise.security.services] [tid: _ThreadID=17 _ThreadName=RunLevelControllerThread-1487766902572] [timeMillis: 1487766902791] [levelValue: 800] [[
  Authorization Service has successfully initialized.]]

[2017-02-22T13:35:02.862+0100] [Payara 4.1] [INFO] [NCLS-SECURITY-01115] [javax.enterprise.system.core.security] [tid: _ThreadID=17 _ThreadName=RunLevelControllerThread-1487766902572] [timeMillis: 1487766902862] [levelValue: 800] [[
  Realm [admin-realm] of classtype [com.sun.enterprise.security.auth.realm.file.FileRealm] successfully created.]]

[2017-02-22T13:35:02.863+0100] [Payara 4.1] [INFO] [NCLS-SECURITY-01115] [javax.enterprise.system.core.security] [tid: _ThreadID=17 _ThreadName=RunLevelControllerThread-1487766902572] [timeMillis: 1487766902863] [levelValue: 800] [[
  Realm [file] of classtype [com.sun.enterprise.security.auth.realm.file.FileRealm] successfully created.]]

[2017-02-22T13:35:02.868+0100] [Payara 4.1] [INFO] [NCLS-SECURITY-01115] [javax.enterprise.system.core.security] [tid: _ThreadID=17 _ThreadName=RunLevelControllerThread-1487766902572] [timeMillis: 1487766902868] [levelValue: 800] [[
  Realm [certificate] of classtype [com.sun.enterprise.security.auth.realm.certificate.CertificateRealm] successfully created.]]

[2017-02-22T13:35:02.948+0100] [Payara 4.1] [INFO] [] [org.hibernate.validator.internal.util.Version] [tid: _ThreadID=17 _ThreadName=RunLevelControllerThread-1487766902572] [timeMillis: 1487766902948] [levelValue: 800] [[
  HV000001: Hibernate Validator 5.1.2.Final]]

[2017-02-22T13:35:03.026+0100] [Payara 4.1] [INFO] [NCLS-CORE-00092] [javax.enterprise.system.core] [tid: _ThreadID=31 _ThreadName=Thread-10] [timeMillis: 1487766903026] [levelValue: 800] [[
  Server shutdown initiated]]

[2017-02-22T13:35:03.026+0100] [Payara 4.1] [INFO] [NCLS-CORE-00015] [javax.enterprise.system.core] [tid: _ThreadID=18 _ThreadName=RunLevelControllerThread-1487766902573] [timeMillis: 1487766903026] [levelValue: 800] [[
  Shutdown requested
MultiException stack 1 of 2
com.sun.enterprise.module.ResolveError: Failed to start OSGiModuleImpl:: Bundle = [fish.payara.appserver.notification-jms-core [185]], State = [NEW]
	at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:217)
	at org.jvnet.hk2.osgiadapter.OsgiPopulatorPostProcessor$1.loadClass(OsgiPopulatorPostProcessor.java:78)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2173)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:454)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:473)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.isWouldBlockRightNow(CurrentTaskFuture.java:1170)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1206)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.osgi.framework.BundleException: Unresolved constraint in bundle fish.payara.appserver.notification-jms-core [185]: Unable to resolve 185.0: missing requirement [185.0] osgi.wiring.package; (osgi.wiring.package=javax.jms)
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:3974)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2037)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:955)
	at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:209)
	... 10 more
MultiException stack 2 of 2
java.lang.IllegalStateException: Could not load descriptor SystemDescriptor(
	implementation=fish.payara.notification.jms.JmsNotificationEventFactory
	contracts={fish.payara.notification.jms.JmsNotificationEventFactory,fish.payara.nucleus.notification.domain.NotificationEventFactory}
	scope=org.glassfish.hk2.runlevel.RunLevel
	qualifiers={}
	descriptorType=CLASS
	descriptorVisibility=NORMAL
	metadata=runLevelValue={10},Bundle-SymbolicName={fish.payara.appserver.notification-jms-core},Bundle-Version={4.1.1.171_0_1}
	rank=0
	loader=OsgiPopulatorPostProcessor.HK2Loader(OSGiModuleImpl:: Bundle = [fish.payara.appserver.notification-jms-core [185]], State = [NEW],1369434324)
	proxiable=null
	proxyForSameScope=null
	analysisName=null
	id=433
	locatorId=0
	identityHashCode=1725669991
	reified=false)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2182)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:454)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:473)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.isWouldBlockRightNow(CurrentTaskFuture.java:1170)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1206)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]

[2017-02-22T13:35:03.027+0100] [Payara 4.1] [SEVERE] [NCLS-CORE-00016] [javax.enterprise.system.core] [tid: _ThreadID=18 _ThreadName=RunLevelControllerThread-1487766902573] [timeMillis: 1487766903027] [levelValue: 1000] [[
  Startup service failed to start
MultiException stack 1 of 2
com.sun.enterprise.module.ResolveError: Failed to start OSGiModuleImpl:: Bundle = [fish.payara.appserver.notification-jms-core [185]], State = [NEW]
	at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:217)
	at org.jvnet.hk2.osgiadapter.OsgiPopulatorPostProcessor$1.loadClass(OsgiPopulatorPostProcessor.java:78)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2173)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:454)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:473)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.isWouldBlockRightNow(CurrentTaskFuture.java:1170)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1206)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.osgi.framework.BundleException: Unresolved constraint in bundle fish.payara.appserver.notification-jms-core [185]: Unable to resolve 185.0: missing requirement [185.0] osgi.wiring.package; (osgi.wiring.package=javax.jms)
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:3974)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2037)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:955)
	at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:209)
	... 10 more
MultiException stack 2 of 2
java.lang.IllegalStateException: Could not load descriptor SystemDescriptor(
	implementation=fish.payara.notification.jms.JmsNotificationEventFactory
	contracts={fish.payara.notification.jms.JmsNotificationEventFactory,fish.payara.nucleus.notification.domain.NotificationEventFactory}
	scope=org.glassfish.hk2.runlevel.RunLevel
	qualifiers={}
	descriptorType=CLASS
	descriptorVisibility=NORMAL
	metadata=runLevelValue={10},Bundle-SymbolicName={fish.payara.appserver.notification-jms-core},Bundle-Version={4.1.1.171_0_1}
	rank=0
	loader=OsgiPopulatorPostProcessor.HK2Loader(OSGiModuleImpl:: Bundle = [fish.payara.appserver.notification-jms-core [185]], State = [NEW],1369434324)
	proxiable=null
	proxyForSameScope=null
	analysisName=null
	id=433
	locatorId=0
	identityHashCode=1725669991
	reified=false)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2182)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:454)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:473)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.isWouldBlockRightNow(CurrentTaskFuture.java:1170)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1206)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]

[2017-02-22T13:35:03.029+0100] [Payara 4.1] [INFO] [NCLS-CORE-00092] [javax.enterprise.system.core] [tid: _ThreadID=32 _ThreadName=Thread-11] [timeMillis: 1487766903029] [levelValue: 800] [[
  Server shutdown initiated]]
```

## Expected Outcome

Payara should start up ;). 

## Current Outcome

The start-domain commands waits forever.

## Steps to reproduce (Only for bug reports) 

1 -**  Start the domain

    ./asadmin start-domain payaradomain

## Environment ##

- **Payara Version**: 4.1.1.171 #badassfish (build 137)
- **Edition**: Web
- **JDK Version**: Oracle JDK 1.8.0_121-b13
- **Operating System**: macOS 10.12.3

**Comment by mikecroft** [comment]
I've confirmed this on Ubuntu Linux as well. Thanks for the report, we'll get on it!

**Comment by mikecroft** [comment]
Internal issue ID `PAYARA-1480`

The cause of this is that the notification service packages a JMS notifier but since JMS isn't part of the web profile, the server fails to start

**Comment by mikecroft** [comment]
As a workaround, you can simply remove the JAR file which contains the JMS notifier:
`rm payara41/glassfish/modules/notification-jms-core.jar`

and the admin console plugin:
`rm payara41/glassfish/modules/jms-notifier-console-plugin.jar`
