### ISSUE TITLE
Payara Micro, bootstrap and jdbc resource adapters

### ISSUE THREAD

**Issue by maxencelaurent** [payara/Payara#1414]
# Description #
----------
__*_jdbc_ra.rar setup fails while unpacking runtime directory, because archives extracted from payara-micro.jar to the rootdir are empty.

This is not happening while using the command line (ie java -jar payara-micro.jar); only when bootstrapping an instance programatically.

Any jdbc-resouce/connection-pool defined within a domain config file or web.xml is ignored and any reference to such a resource throw :  
`Internal Exception: java.sql.SQLException: This pool is not registered with the runtime environment : jdbc/my_pool`

## Expected Outcome
The same as running java -jar "payara-micro.jar"

## Current Outcome

Durring boostrap (PayaraMicro.getInstance.bootstrap()) : 
```
java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:130)
	at com.sun.enterprise.glassfish.bootstrap.JarUtil.extractJar(JarUtil.java:196)
	at com.sun.enterprise.glassfish.bootstrap.JarUtil.extractRar(JarUtil.java:178)
	at com.sun.enterprise.glassfish.bootstrap.JarUtil.extractRars(JarUtil.java:122)
	at fish.payara.micro.impl.RuntimeDirectory.unpackRuntime(RuntimeDirectory.java:166)
	at fish.payara.micro.impl.RuntimeDirectory.<init>(RuntimeDirectory.java:98)
	at fish.payara.micro.impl.PayaraMicroImpl.unPackRuntime(PayaraMicroImpl.java:2171)
	at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:964)
	at fish.payara.micro.PayaraMicro.bootStrap(PayaraMicro.java:119)
```

```
cd /tmp/payaramicro-881136696100254077tmp
ls -l *.rar
```
```
-rw-rw-r-- 1 maxence maxence 0 fév 24 11:54 __cp_jdbc_ra.rar
-rw-rw-r-- 1 maxence maxence 0 fév 24 11:54 __dm_jdbc_ra.rar
-rw-rw-r-- 1 maxence maxence 0 fév 24 11:54 __ds_jdbc_ra.rar
-rw-rw-r-- 1 maxence maxence 0 fév 24 11:54 __xa_jdbc_ra.rar
```

## Steps to reproduce
checkout Payara_Examples and run Payara-Micro/simplest-bootstrap

## Environment ##

- **Payara Version**: 4.1.1.171.0.1
- **Edition**: Micro
- **JDK Version**: OpenJDK 8u121
- **Operating System**: Linux

**Comment by maxencelaurent** [comment]
Issue is related to RandomAccessDataFile.DataInputStream which does not override InputStream.available() method

PR is coming
