### ISSUE TITLE
NPE when using Primefaces/schedule on payara micro

### ISSUE THREAD

**Issue by thomas-mc-work** [payara/Payara#1420]
# Description #
----------

I've got a project which leads to a NPE only in conjunction with payara micro. The same project runs fine with payara full. I was able to shrink the problem to a very minimal project: https://github.com/thomas-mc-work/micro-demo

## Expected Outcome

Should work without any flaws on payara micro.

## Current Outcome

[2017-02-28T13:26:26.264+0100] [] [FATAL] [] [javax.enterprise.resource.webcontainer.jsf.context] [tid: _ThreadID=18 _ThreadName=http-thread-pool::http-listener(1)] [timeMillis: 1488284786264] [levelValue: 1100] [[
      No associated message
    java.lang.NullPointerException
	    at org.primefaces.component.schedule.ScheduleRenderer.encodeScript(ScheduleRenderer.java:135)
	    at org.primefaces.component.schedule.ScheduleRenderer.encodeEnd(ScheduleRenderer.java:64)
	    at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
	    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
	    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	    at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:458)
	    at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:134)
	    at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
	    at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	    at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
	    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:659)
	    at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1693)
	    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:318)
	    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	    at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	    at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	    at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	    at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:416)
	    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
	    at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:466)
	    at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:169)
	    at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	    at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	    at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	    at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	    at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	    at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	    at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	    at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	    at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	    at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
	    at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	    at java.lang.Thread.run(Thread.java:745)
    ]]

## Steps to reproduce (Only for bug reports) 

1 -**  Build [the project](https://github.com/thomas-mc-work/micro-demo): `mvn package`

2 -**  Deploy on payara micro: `java -jar payara-micro-4.1.1.171.jar --deploy target/micro-demo-1.0-SNAPSHOT.war`

## Environment ##

- **Payara version**: 4.1.1.171 (and 4.1.1.164)
- **Edition**: Micro
- **JDK Version**:
  - OpenJDK 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13 @ubuntu 16.04.1
  - also on Openjdk version 1.8.0_121 @CentOS 7

**Comment by mulderbaba** [comment]
@thomas-mc-work this is related to Micro's handling CDI annotations. Internal issue PAYARA-1503 is created. Since @Model is a composite annotation for @Named and @RequestScoped, you can replace it with those and continue.
