### ISSUE TITLE
[Payara Micro] How to register a DB Driver like ojdbc.jar

### ISSUE THREAD

**Issue by deratzmann** [payara/Payara#1423]
# Description #
----------
I think this is not a bug, but a big feature is missing in payara micro.
Right now I'm doing the payara Micro bootrap prgrammatically like this
`PayaraMicro.getInstance()
                .addDeployment(warfile.getAbsolutePath())
                .setAlternateDomainXML(domainxmlAsFile)
                .setUserLogFile(rootDir + File.separator + "server.log")
                .bootStrap();`
I like this approach very much, but for my application I need an ojdbc connection pool with an OracleDataSource. If I would do it the old payara full version way I would put the ojdbc (ORacle JDBC) jar into an ext lib folder in payara-installation folder (which is not available with payara micro) and do sth like
`asadmin create-jdbc-connection-pool --datasourceclassname oracle.jdbc.pool.OracleDataSource --restype javax.sql.DataSource --isconnectvalidatereq true --validationmethod table --validationtable dual --steadypoolsize 1 --leakreclaim true --statementtimeout 340 --leaktimeout 200 --statementleakreclaim=true --statementleaktimeout 170 --failconnection true --property user=username:password=password:url="jdbc:oracle:thin:@host:1521/DBNAME" MYCONNPOOL`

Currently I see no chance to do this with the programmatic Payara Micro. Is there any way to do this, which I didn't see?
BTW: putting the ojdbc.jar in the WEB-INF/lib folder of the application will fail (Dirver is not registered Exception)
## Environment ##

- **Payara Version**: payara-micro-4.1.1.171.0.1
- **JDK Version**: OpenJDK8
- **Operating System**: alpine docker image

**Comment by michaelranaldo** [comment]
Hi @deratzmann,

Payara Micro does happily support the Payara Server method - if you add ojdbc.jar to the Micro archive at MICRO-INF/lib/ojdbc.jar you should get your intended functionality!

**Comment by deratzmann** [comment]
Ok, I'll try tomorrow. Did I understand it correct: I have to "patch" the jar file with my ojdbc.jar? But aren't there any licensing issues when I "patch" the jar? Some people would call that redistribution or am I wrong?

**Comment by smillidge** [comment]
Have you tried just packaging this into the war file and declaring the datasource in the war file like; 
https://github.com/payara/Payara-Examples/tree/master/Payara-Micro/datasource-example

**Comment by smillidge** [comment]
On the classpath question the Payara Micro uberjar supports what @michaelranaldo suggests. As you are bootstrapping the server programmatically with your own classes have you though of just adding the driver to your classpath or am I missing something?

**Comment by deratzmann** [comment]
When I put it on classpath like this
`java -cp /opt/my-microservice.jar:/opt/payara-micro-4.1.1.171.0.1.jar:/opt/ojdbc7.jar de.otto.microservice.payara.BootstrapPayara`

**same error occurs:**

`[2017-03-02T15:25:41.890+0100] [] [WARNING] [] [javax.enterprise.resource.resourceadapter.org.glassfish.jdbc.deployer] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1488464741890] [levelValue: 900] error.creating.jdbc.pool

[2017-03-02T15:25:41.890+0100] [] [SEVERE] [] [javax.enterprise.resource.resourceadapter.com.sun.enterprise.connectors.service] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1488464741890] [levelValue: 1000] RAR8060: Unable to lookup pool [ MYCONNPOOL ], javax.naming.NamingException: Lookup failed for '__SYSTEM/pools/MYCONNPOOL' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: pools]

[2017-03-02T15:25:41.891+0100] [] [SEVERE] [] [javax.enterprise.resource.resourceadapter.com.sun.enterprise.connectors.service] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1488464741891] [levelValue: 1000] RAR6017 : Failed to get connection pool object jdbc/NOADS via JNDI lookup : com.sun.appserv.connectors.internal.api.ConnectorRuntimeException: Lookup failed for '__SYSTEM/pools/MYCONNPOOL' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl}

[2017-03-02T15:25:41.894+0100] [] [WARNING] [] [javax.enterprise.resource.resourceadapter.org.glassfish.jdbc.deployer] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1488464741894] [levelValue: 900] error.creating.jdbc.pool

[2017-03-02T15:25:41.895+0100] [] [SEVERE] [] [javax.enterprise.resource.resourceadapter.com.sun.enterprise.connectors.service] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1488464741895] [levelValue: 1000] RAR8060: Unable to lookup pool [ MYCONNPOOL ], javax.naming.NamingException: Lookup failed for '__SYSTEM/pools/MYCONNPOOL' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: pools]

[2017-03-02T15:25:41.895+0100] [] [SEVERE] [] [javax.enterprise.resource.resourceadapter.com.sun.enterprise.connectors.service] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1488464741895] [levelValue: 1000] RAR6017 : Failed to get connection pool object jdbc/NOADS via JNDI lookup : com.sun.appserv.connectors.internal.api.ConnectorRuntimeException: Lookup failed for '__SYSTEM/pools/MYCONNPOOL' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl}

[2017-03-02T15:25:43.342+0100] [] [INFO] [] [org.eclipse.persistence.session./file:/tmp/payaramicro-3540353786399241004tmp/applications/artikel/WEB-INF/classes/_noa] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1488464743342] [levelValue: 800] EclipseLink, version: Eclipse Persistence Services - 2.6.4.qualifier

[2017-03-02T15:25:43.350+0100] [] [WARNING] [] [javax.enterprise.resource.resourceadapter.org.glassfish.jdbc.deployer] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1488464743350] [levelValue: 900] error.creating.jdbc.pool

[2017-03-02T15:25:43.351+0100] [] [WARNING] [] [javax.enterprise.resource.resourceadapter.org.glassfish.jdbc.deployer] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1488464743351] [levelValue: 900] error.creating.jdbc.pool

[2017-03-02T15:25:43.351+0100] [] [WARNING] [] [javax.enterprise.resource.resourceadapter.com.sun.enterprise.connectors.service] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1488464743351] [levelValue: 900] RAR7010: Pool not reachable.

[2017-03-02T15:25:43.352+0100] [] [WARNING] [] [javax.enterprise.resource.resourceadapter.com.sun.enterprise.connectors.service] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1488464743352] [levelValue: 900] RAR5114 : Error allocating connection : [This pool is not registered with the runtime environment : MYCONNPOOL]

[2017-03-02T15:25:43.356+0100] [] [SEVERE] [] [org.eclipse.persistence.session./file:/tmp/payaramicro-3540353786399241004tmp/applications/artikel/WEB-INF/classes/_noa.ejb] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1488464743356] [levelValue: 1000] [[

Local Exception Stack:
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.4.qualifier): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: This pool is not registered with the runtime environment : MYCONNPOOL
Error Code: 0
        at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:316)
        at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:147)
        at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162)
        at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.setOrDetectDatasource(DatabaseSessionImpl.java:207)
        at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:760)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:265)
        at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:731)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:205)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:305)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:337)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:303)
        at org.glassfish.persistence.jpa.JPADeployer$2.visitPUD(JPADeployer.java:451)
        at org.glassfish.persistence.jpa.JPADeployer$PersistenceUnitDescriptorIterator.iteratePUDs(JPADeployer.java:510)
        at org.glassfish.persistence.jpa.JPADeployer.iterateInitializedPUsAtApplicationPrepare(JPADeployer.java:492)
        at org.glassfish.persistence.jpa.JPADeployer.event(JPADeployer.java:398)
        at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:488)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:487)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
        at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:134)
        at fish.payara.micro.impl.PayaraMicroImpl.deployAll(PayaraMicroImpl.java:1333)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1005)
        at fish.payara.micro.PayaraMicro.bootStrap(PayaraMicro.java:119)
        at de.otto.verfuegbarkeit.payara.BootstrapPayara.initPayaraMicro(BootstrapPayara.java:73)
        at de.otto.verfuegbarkeit.payara.BootstrapPayara.<init>(BootstrapPayara.java:37)
        at de.otto.verfuegbarkeit.payara.BootstrapPayara.main(BootstrapPayara.java:85)
Caused by: java.sql.SQLException: This pool is not registered with the runtime environment : MYCONNPOOL
        at com.sun.enterprise.connectors.service.ConnectorConnectionPoolAdminServiceImpl.getConnection(ConnectorConnectionPoolAdminServiceImpl.java:1558)
        at com.sun.enterprise.connectors.ConnectorRuntime.getConnection(ConnectorRuntime.java:639)
        at org.glassfish.jdbcruntime.service.JdbcDataSource.getConnection(JdbcDataSource.java:88)
        at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:135)
        ... 38 more
Caused by: javax.resource.ResourceException: This pool is not registered with the runtime environment : MYCONNPOOL
        at com.sun.enterprise.connectors.service.ConnectorConnectionPoolAdminServiceImpl.getUnpooledConnection(ConnectorConnectionPoolAdminServiceImpl.java:583)
        at com.sun.enterprise.connectors.service.ConnectorConnectionPoolAdminServiceImpl.getConnection(ConnectorConnectionPoolAdminServiceImpl.java:1550)
        ... 41 more
Caused by: com.sun.appserv.connectors.internal.api.ConnectorRuntimeException: This pool is not bound in JNDI : MYCONNPOOL
        at com.sun.enterprise.connectors.service.ConnectorConnectionPoolAdminServiceImpl.obtainManagedConnectionFactory(ConnectorConnectionPoolAdminServiceImpl.java:1022)
        at com.sun.enterprise.connectors.service.ConnectorConnectionPoolAdminServiceImpl.obtainManagedConnectionFactory(ConnectorConnectionPoolAdminServiceImpl.java:911)
        at com.sun.enterprise.connectors.service.ConnectorConnectionPoolAdminServiceImpl.getUnpooledConnection(ConnectorConnectionPoolAdminServiceImpl.java:576)
        ... 42 more
Caused by: javax.naming.NamingException: Lookup failed for '__SYSTEM/pools/MYCONNPOOL' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: pools]
        at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:491)
        at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:438)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at org.glassfish.resourcebase.resources.naming.ResourceNamingService.lookup(ResourceNamingService.java:238)
        at com.sun.enterprise.connectors.service.ConnectorConnectionPoolAdminServiceImpl.getConnectorConnectionPool(ConnectorConnectionPoolAdminServiceImpl.java:798)
        at com.sun.enterprise.connectors.service.ConnectorConnectionPoolAdminServiceImpl.obtainManagedConnectionFactory(ConnectorConnectionPoolAdminServiceImpl.java:938)
        ... 44 more
Caused by: javax.naming.NameNotFoundException: pools
        at com.sun.enterprise.naming.impl.TransientContext.resolveContext(TransientContext.java:299)
        at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:207)
        at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:208)
        at com.sun.enterprise.naming.impl.SerialContextProviderImpl.lookup(SerialContextProviderImpl.java:66)
        at com.sun.enterprise.naming.impl.LocalSerialContextProviderImpl.lookup(LocalSerialContextProviderImpl.java:114)
        at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:478)
        ... 50 more
]]

[2017-03-02T15:25:43.358+0100] [] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1488464743358] [levelValue: 1000] Exception while deploying the app [artikel]

[2017-03-02T15:25:43.359+0100] [] [SEVERE] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1488464743359] [levelValue: 1000] [[
  Exception during lifecycle processing
org.glassfish.deployment.common.DeploymentException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.4.qualifier): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: This pool is not registered with the runtime environment : MYCONNPOOL
Error Code: 0
        at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:815)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:205)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:305)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:337)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:303)
        at org.glassfish.persistence.jpa.JPADeployer$2.visitPUD(JPADeployer.java:451)
        at org.glassfish.persistence.jpa.JPADeployer$PersistenceUnitDescriptorIterator.iteratePUDs(JPADeployer.java:510)
        at org.glassfish.persistence.jpa.JPADeployer.iterateInitializedPUsAtApplicationPrepare(JPADeployer.java:492)
        at org.glassfish.persistence.jpa.JPADeployer.event(JPADeployer.java:398)
        at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:488)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:487)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
        at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:134)
        at fish.payara.micro.impl.PayaraMicroImpl.deployAll(PayaraMicroImpl.java:1333)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1005)
        at fish.payara.micro.PayaraMicro.bootStrap(PayaraMicro.java:119)
        at de.otto.verfuegbarkeit.payara.BootstrapPayara.initPayaraMicro(BootstrapPayara.java:73)
        at de.otto.verfuegbarkeit.payara.BootstrapPayara.<init>(BootstrapPayara.java:37)
        at de.otto.verfuegbarkeit.payara.BootstrapPayara.main(BootstrapPayara.java:85)
]]

[2017-03-02T15:25:43.365+0100] [] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1488464743365] [levelValue: 1000] [[
  Exception while deploying the app [artikel] : Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.4.qualifier): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: This pool is not registered with the runtime environment : MYCONNPOOL
Error Code: 0]]
`

**Comment by smillidge** [comment]
Please try on 164 as it could be you are hitting https://github.com/payara/Payara/issues/1414

**Comment by deratzmann** [comment]
You're right, with Payara micro 164 it works. So this is a duplicate? Any Ideas when the fix will be available?

**Comment by michaelranaldo** [comment]
The fix has been merged into master - the 171 prelease available at http://www.payara.fish/upstream_builds should contain a fix for your issue, although the build may be unstable.

**Comment by mikecroft** [comment]
Since this is docker, we also provide a docker prerelease image which should contain the latest build:

`docker run -it payara/micro:prerelease...etc`
