### ISSUE TITLE
JasperReport has Linkage Error with payara41 but working fine with Glassfish 4.1

### ISSUE THREAD

**Issue by Taymindis** [payara/Payara#1430]
Having Error while generating Excel Report by using JasperReport shown as below. 
All along using Glassfish 4.1 is wokring fine

java.lang.LinkageError: loader constraint violation: when resolving method "javax.xml.parsers.DocumentBuilder.setErrorHandler(Lorg/xml/sax/ErrorHandler;)V" the class loader (instance of org/glassfish/web/loader/WebappClassLoader) of the current class, net/sf/jasperreports/engine/fonts/SimpleFontExtensionHelper, and the class loader (instance of <bootloader>) for the method's defining class, javax/xml/parsers/DocumentBuilder, have different Class objects for the type org/xml/sax/ErrorHandler used in the signature
	at net.sf.jasperreports.engine.fonts.SimpleFontExtensionHelper.<init>(SimpleFontExtensionHelper.java:135)
	at net.sf.jasperreports.engine.fonts.SimpleFontExtensionHelper.getInstance(SimpleFontExtensionHelper.java:114)
	at net.sf.jasperreports.engine.fonts.FontExtensionsRegistry.getExtensions(FontExtensionsRegistry.java:56)
	at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.getExtensions(DefaultExtensionsRegistry.java:110)
	at net.sf.jasperreports.engine.util.JRStyledTextParser.<clinit>(JRStyledTextParser.java:83)
	at net.sf.jasperreports.engine.fill.JRBaseFiller.<init>(JRBaseFiller.java:121)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.<init>(JRVerticalFiller.java:88)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.<init>(JRVerticalFiller.java:103)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.<init>(JRVerticalFiller.java:61)
	at net.sf.jasperreports.engine.fill.JRFiller.createFiller(JRFiller.java:153)
	at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:82)
	at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:653)
	at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:969)
	at net.sf.dynamicreports.jasper.builder.JasperReportBuilder.toJasperPrint(JasperReportBuilder.java:308)

**Comment by smillidge** [comment]
Please check you do not have jar files relating to xml parsing in your war/ear file.

**Comment by Taymindis** [comment]
currently My reporting running on production via Glassfish 4.1 and it does not have jar file missing issue. I doubt that the payara giving me the same classpath which have javax/xml/parsers/DocumentBuilder. it has conflict with jasperreports when classloader

**Comment by lprimak** [comment]
It's not that the files are missing, you probably have xerces (or other xml parser JARs) in your WAR/EARs.  They have been upgraded in Payara and are incompatible with your files now. 
If you remove them from you WAR/EAR files, your application should work.

**Comment by Taymindis** [comment]
Yup, After I removed the jaxp-api.jar, everything is working fine now. Thnaks!
