### ISSUE TITLE
Payara Micro v4.1.1.171.0.1 Maven Plugin 

### ISSUE THREAD

**Issue by jGauravGupta** [payara/Payara#1441]
# Description #
----------
The maven plugin mentioned here (http://blog.payara.fish/creating-uber-jar-with-payara-micro) is working fine for Payar Micro v4.1.1.162 

```xml
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>java</goal>
                        </goals>
                        <configuration>
                            <mainClass>fish.payara.micro.PayaraMicro</mainClass>
                            <arguments>
                                <argument>--deploy</argument>
                                <argument>${basedir}/target/${project.build.finalName}.war</argument>
                                <argument>--outputUberJar</argument>
                                <argument>${basedir}/target/${project.build.finalName}.jar</argument>
                            </arguments>
                            <includeProjectDependencies>false</includeProjectDependencies>
                            <includePluginDependencies>true</includePluginDependencies>
                            <executableDependency>
                                <groupId>fish.payara.extras</groupId>
                                <artifactId>payara-micro</artifactId>
                            </executableDependency>
                        </configuration>
                        <id>payara-uber-jar</id>
                        <phase>package</phase>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>fish.payara.extras</groupId>
                        <artifactId>payara-micro</artifactId>
                        <version>${version.payara.micro}</version>
                    </dependency>
                </dependencies>
                <version>1.5.0</version>
            </plugin>
```

but if dependency upgraded to **v4.1.1.171.0.1**, it results to following error : 

```
Downloaded: https://repo.maven.apache.org/maven2/fish/payara/extras/payara-micro/4.1.1.171.0.1/payara-micro-4.1.1.171.0.1.jar (61678 KB at 2434.4 KB/sec)

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: fish/payara/micro/boot/PayaraMicroBoot
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:45)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
	at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:72)
	at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:358)
	... 6 more
Caused by: java.lang.ClassNotFoundException: fish.payara.micro.boot.PayaraMicroBoot
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 22 more
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
```

## Steps to reproduce

Generate the Payara Micro appliaction from JPA Modeler or Create new appliaction with Maven plugin mentioned here (http://blog.payara.fish/creating-uber-jar-with-payara-micro) and change the version 4.1.1.162  to 4.1.1.171.0.1 .

## Environment ##

- **Payara Version**: v4.1.1.171.0.1
- **Edition**: Micro
- **JDK Version**: Oracle 1.8.0_45
- **Operating System**: Windows

**Comment by mulderbaba** [comment]
@jGauravGupta  Payara Micro's jar architecture changed to a nested jar so you need to use exec:exec instead of exec:java.
sample pom would be as follows:

```
<plugin>
    <artifactId>maven-dependency-plugin</artifactId>
    <version>2.6</version>
    <executions>
        <execution>
            <id>copy-payara-micro</id>
            <goals>
<goal>copy</goal>
            </goals>
            <configuration>
<outputDirectory>target</outputDirectory>
<stripVersion>true</stripVersion>
<silent>true</silent>
<artifactItems>
    <artifactItem>
        <groupId>fish.payara.extras</groupId>
        <artifactId>payara-micro</artifactId>
        <type>jar</type>
    </artifactItem>
</artifactItems>
            </configuration>
        </execution>
    </executions>
</plugin>

<plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>1.6.0</version>
        <executions>
          <execution>
            <goals>
              <goal>exec</goal>
            </goals>
          </execution>
        </executions>
<configuration>
          <executable>java</executable>
          <arguments>
            <argument>-jar</argument>
            <argument>target/payara-micro.jar</argument>
            <argument>--deploy</argument>
            <argument>target/application.war</argument>
          </arguments>
        </configuration>      
</plugin>
```

**Comment by jGauravGupta** [comment]
Thanks @mulderbaba :)
