### ISSUE TITLE
payara-4.1.1.171.0.1: start-domain fails on VPS running CentOS 6-8 and OpenJDK 1.8.0_121: 'Address already in use' and 'java.lang.IllegalArgumentException: missing event subscriber for an annotated method. Is fish.payara.notification.email.EmailNotifierService@5e671e20 registered'

### ISSUE THREAD

**Issue by webelcomau** [payara/Payara#1442]
# Description #
----------
Fresh install.  Only happens on VPS running CentOS 6-8 and OpenJDK 1.8.0_121 (does not happen on other machines such as MacBook Pro development machine).

asadmin> start-domain

Takes ages then reports failed to start.

## Expected Outcome

domain1 should start.

## Current Outcome

Takes ages then reports failed to start.

Server log claims two separate sets of errors.

The first one makes little sense alone, as clearly the address is not already in use:

[2017-03-08T13:29:29.989+1100] [Payara 4.1] [SEVERE] [NCLS-CORE-00019] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1488940169989] [levelValue: 1000] [[
  Shutting down server due to startup exception
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.glassfish.grizzly.nio.transport.TCPNIOBindingHandler.bindToChannelAndAddress(TCPNIOBindingHandler.java:131)
	at org.glassfish.grizzly.nio.transport.TCPNIOBindingHandler.bind(TCPNIOBindingHandler.java:88)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:238)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:227)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:76)
	at org.glassfish.grizzly.config.GenericGrizzlyListener.start(GenericGrizzlyListener.java:185)
	at com.sun.enterprise.v3.services.impl.GlassfishNetworkListener.start(GlassfishNetworkListener.java:110)
	at com.sun.enterprise.v3.services.impl.GrizzlyProxy.start0(GrizzlyProxy.java:269)
	at com.sun.enterprise.v3.services.impl.GrizzlyProxy.start(GrizzlyProxy.java:242)
	at com.sun.enterprise.v3.services.impl.GrizzlyService.createNetworkProxy(GrizzlyService.java:567)
	at com.sun.enterprise.v3.services.impl.GrizzlyService.postConstruct(GrizzlyService.java:490)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:326)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:374)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:228)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]

Second series of related errors may be side-effect of first error:

[2017-03-08T13:29:30.033+1100] [Payara 4.1] [WARNING] [NCLS-CORE-00069] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1488940170033] [levelValue: 900] [[
  Exception while dispatching an event
java.lang.IllegalArgumentException: missing event subscriber for an annotated method. Is fish.payara.notification.email.EmailNotifierService@5e671e20 registered?
	at com.google.common.eventbus.SubscriberRegistry.unregister(SubscriberRegistry.java:115)
	at com.google.common.eventbus.EventBus.unregister(EventBus.java:198)
	at fish.payara.nucleus.notification.NotificationEventBus.unregister(NotificationEventBus.java:40)
	at fish.payara.nucleus.notification.service.BaseNotifierService.reset(BaseNotifierService.java:128)
	at fish.payara.nucleus.notification.service.QueueBasedNotifierService.reset(QueueBasedNotifierService.java:89)
	at fish.payara.notification.email.EmailNotifierService.shutdown(EmailNotifierService.java:106)
	at fish.payara.nucleus.notification.service.BaseNotifierService.event(BaseNotifierService.java:89)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at com.sun.enterprise.v3.server.AppServerStartup.postStartupJob(AppServerStartup.java:396)
	at com.sun.enterprise.v3.server.AppServerStartup.run(AppServerStartup.java:336)
	at com.sun.enterprise.v3.server.AppServerStartup.doStart(AppServerStartup.java:228)
	at com.sun.enterprise.v3.server.AppServerStartup.start(AppServerStartup.java:219)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishImpl.start(GlassFishImpl.java:79)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishDecorator.start(GlassFishDecorator.java:63)
	at com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishImpl.start(EmbeddedOSGiGlassFishImpl.java:75)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishDecorator.start(GlassFishDecorator.java:63)
	at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishImpl.start(OSGiGlassFishImpl.java:71)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:97)
	at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:54)
]]

[2017-03-08T13:29:30.035+1100] [Payara 4.1] [WARNING] [NCLS-CORE-00069] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1488940170035] [levelValue: 900] [[
  Exception while dispatching an event
java.lang.IllegalArgumentException: missing event subscriber for an annotated method. Is fish.payara.notification.snmp.SnmpNotifierService@61a1ea2c registered?
	at com.google.common.eventbus.SubscriberRegistry.unregister(SubscriberRegistry.java:115)
	at com.google.common.eventbus.EventBus.unregister(EventBus.java:198)
	at fish.payara.nucleus.notification.NotificationEventBus.unregister(NotificationEventBus.java:40)
	at fish.payara.nucleus.notification.service.BaseNotifierService.reset(BaseNotifierService.java:128)
	at fish.payara.nucleus.notification.service.QueueBasedNotifierService.reset(QueueBasedNotifierService.java:89)
	at fish.payara.notification.snmp.SnmpNotifierService.shutdown(SnmpNotifierService.java:126)
	at fish.payara.nucleus.notification.service.BaseNotifierService.event(BaseNotifierService.java:89)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at com.sun.enterprise.v3.server.AppServerStartup.postStartupJob(AppServerStartup.java:396)
	at com.sun.enterprise.v3.server.AppServerStartup.run(AppServerStartup.java:336)
	at com.sun.enterprise.v3.server.AppServerStartup.doStart(AppServerStartup.java:228)
	at com.sun.enterprise.v3.server.AppServerStartup.start(AppServerStartup.java:219)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishImpl.start(GlassFishImpl.java:79)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishDecorator.start(GlassFishDecorator.java:63)
	at com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishImpl.start(EmbeddedOSGiGlassFishImpl.java:75)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishDecorator.start(GlassFishDecorator.java:63)
	at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishImpl.start(OSGiGlassFishImpl.java:71)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:97)
	at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:54)
]]

[2017-03-08T13:29:30.036+1100] [Payara 4.1] [WARNING] [NCLS-CORE-00069] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1488940170036] [levelValue: 900] [[
  Exception while dispatching an event
java.lang.IllegalArgumentException: missing event subscriber for an annotated method. Is fish.payara.notification.slack.SlackNotifierService@25cd49a4 registered?

## Steps to reproduce (Only for bug reports) 

1. Install fresh.

2.  Ensure no other payara or glassfish instances are running.

3 -**  Start the domain

    ./asadmin start-domain

## Environment ##

- **Payara Version**: payara-4.1.1.171.0.1
- **Edition**: Full
- **JDK Version**:  OpenJDK 1.8.0_121
- **Operating System**: CentOS Linux

**Comment by webelcomau** [comment]
Solved. Tomcat was running on the VPS on 8080, changed default Payara HTTP port (by direct editing of domain.xml) of http-listener-1 then could start domain.

**Comment by mikecroft** [comment]
An alternative method might be to create a new domain using `--portbase`, e.g:

`asadmin create-domain --portbase 5000 myDomain`

This will then use the final 2 digits of each default port number and add them to the port base you've given, so you will get:

* Admin port: 5048
* http: 5080
* https: 5081

This can make life easier when working with multiple domains on a single host.

Note: Since you're using domain1 here already, then this command will use domain1 as the default template. If you wanted to base your new domain off the payaradomain, you could specify that using `--template payaradomain`.
