### ISSUE TITLE
Cannot use Hazelcast in Singleton bean's PostConstruct

### ISSUE THREAD

**Issue by dmatej** [payara/Payara#1444]
# Description #
----------

Hazelcast JNDI is initialized too late (after the bean initialization and complete application startup).

## Expected Outcome

The payara/CacheManager JNDI accessible from Startup bean method annotated with the PostConstruct annotation (just as are JDBC resources).

## Current Outcome

```
Caused by: java.lang.IllegalStateException: Could not find 'payara/CacheManager' via the JNDI
        at cz.i.cis.appl.core.cache.CodebookCacheInitializer.getCacheManager(CodebookCacheInitializer.java:59)
        at cz.i.cis.appl.core.cache.CodebookCacheInitializer.reinitialize(CodebookCacheInitializer.java:32)
        at cz.i.cis.appl.core.start.CisCoreInitializer.reconfigure(CisCoreInitializer.java:79)
        at cz.i.cis.appl.core.start.CisCoreInitializer.init(CisCoreInitializer.java:54)
        at cz.i.cis.appl.core.start.CisInitialisationSingleton.init(CisInitialisationSingleton.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.BeanCallbackInterceptor.intercept(InterceptorManager.java:1047)
        at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
        at com.sun.ejb.containers.interceptors.CallbackInvocationContext.proceed(CallbackInvocationContext.java:205)
        at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:73)
        at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.CallbackInterceptor.intercept(InterceptorManager.java:998)
        at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
        at com.sun.ejb.containers.interceptors.CallbackInvocationContext.proceed(CallbackInvocationContext.java:205)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.init(SystemInterceptorProxy.java:125)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.CallbackInterceptor.intercept(InterceptorManager.java:998)
        at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:417)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:380)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:1962)
        at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:468)
        ... 26 more
Caused by: javax.naming.NamingException: **Lookup failed for 'payara/CacheManager'** in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rm
i.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming} [Root exception is javax.naming.NameNotFoundException: payara]
        at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:491)
        at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:438)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at cz.i.cis.appl.core.cache.CodebookCacheInitializer.getCacheManager(CodebookCacheInitializer.java:47)
        ... 58 more
Caused by: javax.naming.NameNotFoundException: payara
        at com.sun.enterprise.naming.impl.TransientContext.resolveContext(TransientContext.java:299)
        at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:207)
        at com.sun.enterprise.naming.impl.SerialContextProviderImpl.lookup(SerialContextProviderImpl.java:66)
        at com.sun.enterprise.naming.impl.LocalSerialContextProviderImpl.lookup(LocalSerialContextProviderImpl.java:114)
        at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:478)
        ... 62 more
.....
[2017-03-08T15:58:41.707+0100] [Payara 4.1] [SEVERE] [NCLS-CORE-00041] [javax.enterprise.system.core] [tid: _ThreadID=24 _ThreadName=RunLevelControllerThread-1488985020183] [timeMillis: 1488985121707] [levelValue: 1000] [[
  Application deployment failed: Exception while loading the app]]

[2017-03-08T15:58:41.722+0100] [Payara 4.1] [INFO] [NCLS-CORE-00017] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1488985121722] [levelValue: 800] [[
  Payara Server  4.1.1.172-SNAPSHOT #badassfish (4.1.1.171.0.1-ICZ170308) startup time : Felix (5 550ms), startup services(102 637ms), total(108 187ms)]]

[2017-03-08T15:58:41.727+0100] [Payara 4.1] [INFO] [] [fish.payara.nucleus.notification.NotificationService] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1488985121727] [levelValue: 800] [[
  Payara Notification Service bootstrapped with configuration: NotificationExecutionOptions{enabled=true, notifierConfigurationExecutionOptionsList={LOG=NotifierConfigurationExecutionOptions{notifierType=LOG, enabled=true}}}]]

[2017-03-08T15:58:41.777+0100] [Payara 4.1] [INFO] [] [fish.payara.nucleus.hazelcast.HazelcastCore] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1488985121777] [levelValue: 800] [[
  Hazelcast Instance Bound to JNDI at payara/Hazelcast]]

[2017-03-08T15:58:41.778+0100] [Payara 4.1] [INFO] [] [fish.payara.nucleus.hazelcast.HazelcastCore] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1488985121778] [levelValue: 800] [[
  JSR107 Caching Provider Bound to JNDI at payara/CachingProvider]]

[2017-03-08T15:58:41.778+0100] [Payara 4.1] [INFO] [] [fish.payara.nucleus.hazelcast.HazelcastCore] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1488985121778] [levelValue: 800] [[
  **JSR107 Default Cache Manager Bound to JNDI at payara/CacheManager**]]
```

## Steps to reproduce

1. Create EJB module with **@Startup** bean with a method annotated with **@PostConstruct** annotation and accessing to JNDI payara/CacheManager
2. Include it into EAR and deploy - deploy will be successful, because the manager is already accessible.
3. Restart domain - application will be unloaded because JNDI is activated after the application startup that already needs the JNDI.

## Environment ##

- **Payara Version**: 4.1.1.171.0.1
- **Edition**: Full
- **JDK Version**: 8u121 - Oracle
- **Operating System**: Linux

**Comment by lprimak** [comment]
Thanks, @dmatej will fix this as part of #759

**Comment by lprimak** [comment]
internal issue PAYARA-1006

**Comment by smillidge** [comment]
Does this happen with the pre-release version as well?

**Comment by lprimak** [comment]
@smillidge good point, this may already be fixed

**Comment by dmatej** [comment]
I have tried current snapshot (commit 78ee09c3), but it is still the same. Weird is also that Hazelcast JNDI is initialized by the **main** thread:
`
[2017-03-08T20:36:06.269+0100] [Payara 4.1] [INFO] [] [fish.payara.nucleus.hazelcast.HazelcastCore] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1489001766269] [levelValue: 800] [[
  JSR107 Default Cache Manager Bound to JNDI at payara/CacheManager]]
`

But application is loaded by another thread, probably started by the main thread, that waits until RunLevelControllerThread ends or sends some signal:
`[2017-03-08T20:35:44.820+0100] [Payara 4.1] [INFO] [NCLS-CORE-00022] [javax.enterprise.system.core] [tid: _ThreadID=17 _ThreadName=RunLevelControllerThread-1489001611514] [timeMillis: 1489001744820] [levelValue: 800] [[
  Loading application cis-web-ui done in 132 002 ms]]
`
(Loading is successful now because the access to the cache is surrounded by try-catch block) 

But JDBC is initialized before the application and by the same RunLevelControllerThread:
```
[2017-03-08T20:33:58.477+0100] [Payara 4.1] [WARNING] [] [javax.enterprise.resource.resourceadapter.org.glassfish.jdbc.util] [tid: _ThreadID=17 _ThreadName=**RunLevelControllerThread**-1489001611514] [timeMillis: 1489001638477] [levelValue: 900] [[
  RAR8068: Using default datasource : __ds_jdbc_ra for pool : myCis]]
```

I'm not sure, but I think that this might be a part of the problem.

**Comment by dmatej** [comment]
I have merged snapshot with @lprimak branch PAYARA-1006 and I can confirm that it is correct :)
`[2017-03-09T10:23:25.192+0100] [Payara 4.1] [INFO] [] [fish.payara.nucleus.hazelcast.HazelcastCore] [tid: _ThreadID=17 _ThreadName=RunLevelControllerThread-1489051395552] [timeMillis: 1489051405192] [levelValue: 800] [[
  JSR107 Default Cache Manager Bound to JNDI at payara/CacheManager]]
`
...
`[2017-03-09T10:25:21.005+0100] [Payara 4.1] [INFO] [NCLS-CORE-00022] [javax.enterprise.system.core] [tid: _ThreadID=19 _ThreadName=RunLevelControllerThread-1489051395572] [timeMillis: 1489051521005] [levelValue: 800] [[
  Loading application cis-web-ui done in 123 973 ms]]
`

And no stacktrace in application's log:
`10:24:39,308|INFO |RunLevelControllerThread-1489051395572|core.cache.CodebookCacheInitializer|Codebook caches initialized.
`

**Comment by lprimak** [comment]
thanks for testing @dmatej

**Comment by fransflippo** [comment]
Was this fixed for Payara Micro too? I have a similar situation, `@javax.ejb.Singleton` bean with an `@Resource(lookup = "payara/Hazelcast")` reference that is failing. Payara Micro 5.192.

```2019-08-13 14:15:11 SEVERE com.sun.enterprise.v3.server.ApplicationLifecycle prepare Exception during lifecycle processing
org.glassfish.deployment.common.DeploymentException: JNDI lookup failed for the resource: Name: [java:module/env/*******.PropertiesLoader/instance], Lookup: [payara/Hazelcast], Type: [java.lang.String]
	at com.sun.enterprise.deployment.util.ResourceValidator.validateJNDIRefs(ResourceValidator.java:896)
	at com.sun.enterprise.deployment.util.ResourceValidator.validateResources(ResourceValidator.java:742)
	at com.sun.enterprise.deployment.util.ResourceValidator.event(ResourceValidator.java:146)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:421)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:540)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:557)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:553)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:552)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:583)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:575)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:574)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1483)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:119)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1865)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1741)
	at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:136)
	at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:151)
	at fish.payara.micro.impl.PayaraMicroImpl.deployAll(PayaraMicroImpl.java:1532)
	at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1043)
	at fish.payara.micro.impl.PayaraMicroImpl.create(PayaraMicroImpl.java:210)
	at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:50)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:112)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:71)
	at fish.payara.micro.boot.PayaraMicroLauncher.create(PayaraMicroLauncher.java:87)
	at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:72)
	at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:397)
Caused by: javax.naming.NamingException: Lookup failed for 'payara/Hazelcast' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: payara]
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:496)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:442)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at com.sun.enterprise.deployment.util.ResourceValidator.validateJNDIRefs(ResourceValidator.java:891)
	... 35 more
Caused by: javax.naming.NameNotFoundException: payara
	at com.sun.enterprise.naming.impl.TransientContext.resolveContext(TransientContext.java:299)
	at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:207)
	at com.sun.enterprise.naming.impl.SerialContextProviderImpl.lookup(SerialContextProviderImpl.java:70)
	at com.sun.enterprise.naming.impl.LocalSerialContextProviderImpl.lookup(LocalSerialContextProviderImpl.java:114)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:483)
	... 39 more
```
