### ISSUE TITLE
Deploying application with a version causing WELD-000163 error

### ISSUE THREAD

**Issue by acbeech** [payara/Payara#1464]
# Description #
----------
After upgrading from version 4.1.1.163 to 4.1.1.171.0.1 we noticed that our versioned CDI application will no longer deploy. Removing the version fixes the issue. Seems related to this bug fix - https://github.com/payara/Payara/pull/1234

## Expected Outcome
Deploying a versioned application with the name test-app:1.0.0 should work. Changing the name to test-app-1.0.0 fixes the issue.

## Current Outcome
Fails the deploy with the following errors:
[2017-03-17 15:40:26] ERROR [javax.enterprise.system.core] [] - Exception during lifecycle processing
org.glassfish.deployment.common.DeploymentException: CDI deployment failure:WELD-000163: Non-unique bean deployment identifier detected: 
  - BeanDeployment [beanDeploymentArchiveId=test:1.1.war, beanManagerId=test.war],
  - BeanDeployment [beanDeploymentArchiveId=test:1.1.war/WEB-INF/lib/deltaspike-core-api-1.4.1, beanManagerId=test.1],
  - BeanDeployment [beanDeploymentArchiveId=test:1.1.war/WEB-INF/lib/test-services-0.0.5-SNAPSHOT, beanManagerId=test.5-SNAPSHOT],
  - BeanDeployment [beanDeploymentArchiveId=test:1.1.war/WEB-INF/lib/test-persistence-0.0.5-SNAPSHOT, beanManagerId=test.5-SNAPSHOT],
  - BeanDeployment [beanDeploymentArchiveId=root_test:1.1.war, beanManagerId=root_test.war],
  - BeanDeployment [beanDeploymentArchiveId=test:1.1.war/WEB-INF/lib/deltaspike-core-impl-1.4.1, beanManagerId=test.1],
  - BeanDeployment [beanDeploymentArchiveId=test:1.1.war/WEB-INF/lib/vaadin-cdi-1.0.3, beanManagerId=test.3]
	at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:236)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:329)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:497)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:487)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:263)
	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:234)
	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:285)
	at org.glassfish.admin.rest.resources.TemplateListOfResource.createResource(TemplateListOfResource.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43)

## Steps to reproduce (Only for bug reports) 
Deploy application with name test-app:1.0.0 on Payara version 4.1.1.171.0.1. Remove the colon to see it deploy correctly.

## Environment ##
- **Payara Version**: 4.1.1.171.0.1
- **Edition**: Full
- **JDK Version**: java version "1.8.0_73"
- **Operating System**: Windows

**Comment by lprimak** [comment]
Can you upload a small reproducer app?  Our tests work and your failure may be because we've overlooked something your application has or uses. 

Thanks.

**Comment by acbeech** [comment]
[app2.zip](https://github.com/payara/Payara/files/856288/app2.zip)

**Comment by acbeech** [comment]
Uploaded a simple project that can be deployed to Payara 4.1.1.171.0.1 to reproduce the issue. Change the application name to app2:1 or something when deploying. It appears to be with the deltaspike-core-impl dependency. We tried deploying it to an older version of Payara and it deployed fine. We are using Vaadin, and the version we are on uses the deltaspike-core-impl 1.4.1 dependency, but I tested with version 1.7.2 and it also has the issue.

**Comment by lprimak** [comment]
Sorry. I am confused, "version 1.7.2" of what?

**Comment by acbeech** [comment]
That's the latest version of the deltaspike-core-impl dependency, which seems to be causing the reported error - https://mvnrepository.com/artifact/org.apache.deltaspike.core/deltaspike-core-impl/1.7.2

**Comment by lprimak** [comment]
ok, got it
