### ISSUE TITLE
[SEVERE] [] [fish.payara.notification.email.EmailNotificationRunnable] [tid: _ThreadID=75 _ThreadName=email-message-consumer-1] [timeMillis: 1490682895323] [levelValue: 1000] [[   Username and Password not accepted.

### ISSUE THREAD

**Issue by Taymindis** [payara/Payara#1487]
![image](https://cloud.githubusercontent.com/assets/14217761/24392038/c5526e7c-13c4-11e7-9349-635812cd038a.png)

![image](https://cloud.githubusercontent.com/assets/14217761/24392060/dd226ae8-13c4-11e7-8d82-a164ca1013f2.png)

Property i follow the guideline from http://blog.payara.fish/how-to-configure-the-email-notifier-with-payara-server-171-gmail.

**Comment by mulderbaba** [comment]
have you followed [this](http://blog.payara.fish/how-to-configure-the-email-notifier-with-payara-server-171-gmail) @Taymindis? For gmail, you need to configure additional properties.

**Comment by Taymindis** [comment]
Hi Mulderbaba,
yup. I follow the guideline. addition property has added. port, password, email everything hard coded.

**Comment by mulderbaba** [comment]
@Taymindis can you share screenshot of your properties from your JNDI configuration if possible?

**Comment by Taymindis** [comment]
[2017-03-28T23:02:58.872+0800] [Payara 4.1] [SEVERE] [] [fish.payara.notification.email.EmailNotificationRunnable] [tid: _ThreadID=150 _ThreadName=email-message-consumer-1] [timeMillis: 1490713378872] [levelValue: 1000] [[
  Username and Password not accepted.
javax.mail.AuthenticationFailedException: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt……



534 5.7.14  https://support.google.com/mail/answer/78754 t133sm8108248pgc.24 - gsmtp

	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:932)
	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:843)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:748)
	at javax.mail.Service.connect(Service.java:388)
	at javax.mail.Service.connect(Service.java:246)
	at javax.mail.Service.connect(Service.java:195)
	at javax.mail.Transport.send0(Transport.java:254)
	at javax.mail.Transport.send(Transport.java:124)
	at fish.payara.notification.email.EmailNotificationRunnable.run(EmailNotificationRunnable.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]

**Comment by Taymindis** [comment]
![image](https://cloud.githubusercontent.com/assets/14217761/24412481/29438ee8-140b-11e7-8bc4-4c57a99a0614.png)

**Comment by Taymindis** [comment]
Dear Payara Team, has this issue found?

**Comment by mikecroft** [comment]
Have you verified the user and password that you are using, independently of Payara Server, @Taymindis? It looks like you have followed the instructions in the blog post correctly, but the error is coming from Google's authentication. If you have used the `${ALIAS=myPasswordAlias}` feature for the password, have you made sure to create the alias properly?

**Comment by Taymindis** [comment]
I've Fixed the issue by login sender email and turn on less sucure app sign in (means allow other apps sign in to google).
