### ISSUE TITLE
EntityManager.createNativeQuery results in unloadAndKillPool

### ISSUE THREAD

**Issue by clive-jevons** [payara/Payara#1577]
# Description #
----------

When using JPA to create and run a native query, the call results in unloadAndKillPool from being called. When you have multiple threads doing this concurrently, then you end up getting ConcurrentModificationException from the JDBC Monitor, and if you fix that, you end up with NPEs when trying to access the pool, because another thread has just caused it to be removed.

Here's the top of a call stack from our application which shows what's happening (I forked the project, and fixed the ConcurrentModificationException with synchronisation, then added a new Exception().printStackTrace() at the point where unloadAndKillPool was being called to see where this was coming from).

```
java.lang.RuntimeException: Marker for use of unloadAndKillPool
        at com.sun.enterprise.connectors.service.ConnectorConnectionPoolAdminServiceImpl.unloadAndKillPool(ConnectorConnectionPoolAdminServiceImpl.java:1319)
        at com.sun.enterprise.connectors.service.ConnectorConnectionPoolAdminServiceImpl.getUnpooledConnection(ConnectorConnectionPoolAdminServiceImpl.java:545)
        at com.sun.enterprise.connectors.service.ConnectorConnectionPoolAdminServiceImpl.getConnection(ConnectorConnectionPoolAdminServiceImpl.java:1551)
        at com.sun.enterprise.connectors.ConnectorRuntime.getConnection(ConnectorRuntime.java:639)
        at org.glassfish.jdbcruntime.service.JdbcDataSource.getConnection(JdbcDataSource.java:88)
        at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:135)
        at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162)
        at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.connectInternal(DatasourceAccessor.java:346)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.connectInternal(DatabaseAccessor.java:309)
        at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.reconnect(DatasourceAccessor.java:581)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.reconnect(DatabaseAccessor.java:1634)
        at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.incrementCallCount(DatasourceAccessor.java:321)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:615)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:560)
        at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2056)
        at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:306)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:299)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelect(DatasourceCallQueryMechanism.java:281)
        at org.eclipse.persistence.queries.DataReadQuery.executeNonCursor(DataReadQuery.java:197)
        at org.eclipse.persistence.queries.DataReadQuery.executeDatabaseQuery(DataReadQuery.java:152)
        at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:904)
        at org.eclipse.persistence.queries.DataReadQuery.execute(DataReadQuery.java:137)
        at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:803)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1857)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1839)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1804)
        at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:258)
        at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:473)
```

According to the JavaDoc from the ConnectorRuntime on, the whole getConnection part is intended for internal use by the DAS. In that context the unloadAndKillPool makes sense, but obviously it's sub-optimal in the case were you're trying to execute business code.

## Expected Outcome

Using createNativeQuery / getResultList thereon should not result in the connection pool being removed.

## Current Outcome

Results in the connection pool being removed and re-created on each call.

## Steps to reproduce (Only for bug reports) 

In an application using JPA, make a call to EntityManager.createNativeQuery() and then call .getResultList() on the query.

### Samples

None at this time.

## Context (Optional)

Our application is performing lots of geo-spatial queries against a PostgreSQL, so we need to formulate them in native syntax. The service is then being called very frequently from many clients, which results in the high-concurrency which then leads to the behaviour described above.

## Environment ##

- **Payara Version**: 4.1.1.171.1
- **Edition**: Micro
- **JDK Version**: 8
- **Operating System**: Mac, Linux (haven't tested on Windows)

**Comment by clive-jevons** [comment]
@fturizo Just wanted to say that I'd be more than happy to help in getting this fixed. More than anything, though, I'm not sure about what the correct strategy would be to satisfy the two, apparently entirely disparate requirements of EclipseLink on the one hand, and the DAS features on the other hand. If someone could provide some guidance or a vision of how this bug should be resolved, I can have a go at creating a patch / PR for it :)

**Comment by smillidge** [comment]
Thanks for your offer to help produce a PR. Can you provide a very simple reproducer? We can then provide some guidance on a fix?

**Comment by fturizo** [comment]
@clive-jevons, as @smillidge mentioned we'd happy to help with guidance if you can produce a sample reproducer for this case. It would also help to know what driver are you using to connect to the PostgreSQL database as well.

**Comment by clive-jevons** [comment]
[payara-native-query-bug.zip](https://github.com/payara/Payara/files/1008118/payara-native-query-bug.zip)

@fturizo @smillidge Please find attached a little project which demonstrates the behaviour. There's a README.md in the root which explains how to get it set up and running. Please let me know if you have any trouble getting this working :)

**Comment by clive-jevons** [comment]
@fturizo Hi :) Just checking in to see if you've had a chance to try out the example project I attached previously?

**Comment by fturizo** [comment]
Hi @clive-jevons, sorry for not replying earlier. Many thanks for the sample reproducer, I'll examine it and identify the possible bug you are encountering and come back to you with my findings.

**Comment by clive-jevons** [comment]
Hi @fturizo , no worries, and thanks for taking a look at it :)
I've created a work around: https://github.com/clive-jevons/Payara/commit/e7ef2feb580329346e3df5aa0086752869e6d7ab
After commenting out the part of the code as seen in that commit the bug doesn't occur any more.
Hope that helps :)
Cheers,
C

**Comment by fturizo** [comment]
Greetings @clive-jevons 

After running multiple tests and evaluating the scenario that you presented I came up with the following observations:

* The issue only manifests when using **Payara Micro**. I ran up multiples tests on **Payara Server** with the same configuration and had no exceptions or errors running concurrent threads.
* As you mentioned, the issue appears when using JPA native queries. I tried using JPQL named queries and no problems manifest when this happens, however, when I tried to inject or lookup the data source into the EJB to run the same SQL query I found out that Payara Micro can't find the JDBC resource in the JNDI namespace, which is odd since the EntityManager can do it without issues. This is a major bug that I reported to the developers so it can be worked on. Due to this behaviour, I couldn't confirm if the cause of the error is EclipseLink's usage of the connection pool or rather GlassFish/Payara's own code as you marked it on your PR.
* The error you are encountering can only be triggered when enabling the `associate-with-thread` attribute on the JDBC connection pool (this attribute allows the reuse of a connection located on the same thread). When this attribute is not enabled (which is the default setting), the **_Failed to remove the MCF: postgresPool_** message doesn't appear; instead, a full stack trace is thrown in the same erratic manner showing that the `EntityManager` couldn't locate the data source. 

Due to these observations, I think that the issue is quite complex and should get input from the developers so I've opened the internal issue `PAYARA-1735` so they can get a deeper look into it. We'll let you know once we have more information about it.

**Comment by clive-jevons** [comment]
@fturizo thanks for the update and the insights 😊👍

**Comment by clive-jevons** [comment]
@fturizo any update on this issue?

**Comment by clive-jevons** [comment]
@fturizo @smillidge is there an ETA for a fix yet? 174, maybe? :)

**Comment by mikecroft** [comment]
Hi @clive-jevons - no ETA yet, looking at the internal issue. I can say that it won't be in 174, though, that's going to be out very soon! We need to prioritise bug fixes for support customers, so if you were interested in a support contract I could guarantee that the issue would jump up the priority list!
https://www.payara.fish/support

**Comment by clive-jevons** [comment]
@mikecroft Thanks for the update. Since we've hit another bug with Payara Micro (involving logging in JSON) and are currently moving to a new platform, we're considering other options also. I'll discuss with the client how important it is for them to keep developing on Payara Micro.

**Comment by clive-jevons** [comment]
I can confirm that this issue does not occur with 4.1.2.174 any more! Thanks :)
