### ISSUE TITLE
payara-embedded-all no longer standalone in 4.1.2.172

### ISSUE THREAD

**Issue by realityforge** [payara/Payara#1615]
The `payara-embedded-all` artifact `fish.payara.extras:payara-embedded-all:jar:4.1.2.172` no longer contains all the classes required to run Payara. This is of particular importance as the `payara-embedded-all` artifact is often used for executing tests. It seems like it would be sufficient to merge the contents of the artifact`fish.payara.api:payara-api:jar:4.1.2.172` into `payara-embedded-all` to restore the ability to run Payara from the jar

**Comment by arjantijms** [comment]
I was able to confirm this using Soteria

```
mvn clean install -Ppayara-embedded,bundled
```

Results in:


```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.glassfish.soteria.test.AppSecurityContextIT


May 23, 2017 3:05:12 PM org.glassfish.security.services.impl.authorization.AuthorizationServiceImpl initialize
INFO: Authorization Service has successfully initialized.


May 23, 2017 3:05:13 PM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 5.1.2.Final

May 23, 2017 3:05:15 PM com.sun.enterprise.v3.services.impl.GrizzlyProxy start0
INFO: Grizzly Framework 2.3.29 started in: 42ms - bound to [/0.0.0.0:8181]
May 23, 2017 3:05:15 PM com.sun.enterprise.v3.services.impl.GrizzlyService createNetworkProxy
INFO: Network listener https-listener on port 0 disabled per domain.xml
May 23, 2017 3:05:15 PM com.sun.enterprise.v3.admin.adapter.AdminEndpointDecider setGuiContextRoot
INFO: Admin Console Adapter: context root: /admin
May 23, 2017 3:05:15 PM com.sun.enterprise.v3.admin.adapter.AdminEndpointDecider setGuiContextRoot
INFO: Admin Console Adapter: context root: /admin
May 23, 2017 3:05:15 PM com.sun.enterprise.v3.admin.adapter.AdminEndpointDecider setGuiContextRoot
INFO: Admin Console Adapter: context root: /admin
May 23, 2017 3:05:15 PM com.sun.enterprise.v3.server.AppServerStartup$MasterRunLevelListener onError
INFO: Shutdown requested
java.lang.NoClassDefFoundError: fish/payara/notification/eventbus/EventbusMessage
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
```

**Comment by mikecroft** [comment]
Created internal issue `PAYARA-1701`
