### ISSUE TITLE
Problem deploying JCA Connector

### ISSUE THREAD

**Issue by dstutz** [payara/Payara#1616]
# Description #
----------

With Payara 172 I am unable to deploy XADisk 1.2.2 JCA Connector which worked fine in 171.

## Expected Outcome

XADisk.rar should deploy.

## Current Outcome

Through admin UI, attempting to deploy will just hang and sit there.  I see the following in the logs:
Info:   GUI deployment: uploadToTempfile
Info:   uploadFileName=XADisk.rar

Through asadmin CLI, it basically does the same thing, the command just sits there and never returns.

## Context (Optional)

We're using XADisk 1.2.2 and it runs fine on Payara 164 and currently using on 171.  I **can** deploy the same rar file to a freshly unzipped Glassfish 4.1.2 so I'm assuming it's some customization done for Payara 172.

In 172, when I shut down the server after attempting to deploy XADisk I get the following output/stacktrace:
`Info:   GUI deployment: uploadToTempfile
Info:   uploadFileName=XADisk.rar
Info:   Server shutdown initiated
Info:   Unregistered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishImpl@3f0d6038 from service registry.
Info:   FileMonitoring shutdown
Info:   JMXStartupService: Stopped JMXConnectorServer: null
Info:   JMXStartupService and JMXConnectors have been shut down.
Severe:   RAR6035 : Resource adapter start failed.
javax.resource.spi.ResourceAdapterInternalException: org.xadisk.filesystem.exceptions.XASystemBootFailureException: The XADisk instance has encoutered a critial issue and could not be booted. Such a condition is very rare. If you think you have setup everything right for XADisk to work, please consider discussing in XADisk forums, or raising a bug with details.
	at org.xadisk.connector.XADiskResourceAdapter.start(XADiskResourceAdapter.java:40)
	at com.sun.enterprise.connectors.ActiveOutboundResourceAdapter.startResourceAdapter(ActiveOutboundResourceAdapter.java:183)
	at com.sun.enterprise.connectors.ActiveOutboundResourceAdapter.init(ActiveOutboundResourceAdapter.java:130)
	at com.sun.enterprise.connectors.inbound.ActiveInboundResourceAdapterImpl.init(ActiveInboundResourceAdapterImpl.java:90)
	at com.sun.enterprise.connectors.ActiveRAFactory.instantiateActiveResourceAdapter(ActiveRAFactory.java:141)
	at com.sun.enterprise.connectors.ActiveRAFactory.createActiveResourceAdapter(ActiveRAFactory.java:108)
	at com.sun.enterprise.connectors.service.ResourceAdapterAdminServiceImpl.createActiveResourceAdapter(ResourceAdapterAdminServiceImpl.java:210)
	at com.sun.enterprise.connectors.ConnectorRuntime.createActiveResourceAdapter(ConnectorRuntime.java:412)
	at com.sun.enterprise.connectors.module.ConnectorDeployer.load(ConnectorDeployer.java:197)
	at com.sun.enterprise.connectors.module.ConnectorDeployer.load(ConnectorDeployer.java:92)
	at org.glassfish.internal.data.ModuleInfo.load(ModuleInfo.java:206)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:314)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:497)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:487)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:263)
	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:234)
	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:285)
	at org.glassfish.admin.rest.resources.TemplateListOfResource.createResource(TemplateListOfResource.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384)
	at org.glassfish.admin.rest.adapter.RestAdapter$2.service(RestAdapter.java:316)
	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:179)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:466)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:169)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.xadisk.filesystem.exceptions.XASystemBootFailureException: The XADisk instance has encoutered a critial issue and could not be booted. Such a condition is very rare. If you think you have setup everything right for XADisk to work, please consider discussing in XADisk forums, or raising a bug with details.
	at org.xadisk.filesystem.NativeXAFileSystem.<init>(NativeXAFileSystem.java:192)
	at org.xadisk.filesystem.NativeXAFileSystem.bootXAFileSystem(NativeXAFileSystem.java:208)
	at org.xadisk.connector.XADiskResourceAdapter.start(XADiskResourceAdapter.java:38)
	... 75 more
Caused by: javax.resource.spi.work.WorkRejectedException: java.lang.InterruptedException, error code: 0
	at com.sun.enterprise.connectors.work.WorkCoordinator.setException(WorkCoordinator.java:333)
	at com.sun.enterprise.connectors.work.WorkCoordinator.lock(WorkCoordinator.java:383)
	at com.sun.enterprise.connectors.work.CommonWorkManager.startWork(CommonWorkManager.java:299)
	at com.sun.enterprise.connectors.work.WorkManagerProxy.startWork(WorkManagerProxy.java:94)
	at org.xadisk.filesystem.NativeXAFileSystem.<init>(NativeXAFileSystem.java:188)
	... 77 more
Caused by: java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at com.sun.enterprise.connectors.work.WorkCoordinator.lock(WorkCoordinator.java:364)
	... 80 more`

## Environment ##

- **Payara Version**: 4.1.2.172 #badassfish (build 235)
- **Edition**: Full
- **JDK Version**: Oracle 8_121
- **Operating System**: Windows 7

**Comment by smillidge** [comment]
Can you post a thread dump taken while the server is hanging?

**Comment by dstutz** [comment]
[thread-dump-connector-deploy.txt](https://github.com/payara/Payara/files/1022983/thread-dump-connector-deploy.txt)

**Comment by smillidge** [comment]
This may sound weird but increase the minimum number of threads from 5 to say 10 in "thread-pool-1" for the server config using the admin console and try deploying again.

**Comment by dstutz** [comment]
Guess it wasn't that weird...Thank you very much.

Info:   GUI deployment: uploadToTempfile
Info:   uploadFileName=XADisk.rar
Info:   XADisk was successfully deployed in 400 milliseconds.

**Comment by smillidge** [comment]
Your adapter requires a lot of threads at boot from that threadpool. In 172 another Payara service increased it's use of that pool by 2 threads.
