### ISSUE TITLE
'xxx' REST Endpoints: java.lang.NullPointerExceptionjava.lang.NullPointerExceptesion for JAX-RS applications not using packag

### ISSUE THREAD

**Issue by mkarg** [payara/Payara#1632]
# Description #
----------

Payara Micro says "java.lang.NullPointerException" instead of the name of the REST Endpoints.

## Expected Outcome

```
'mywar' REST Endpoints
app/helloworld
```

## Current Outcome

```
[TIMESTAMP] [] [SEVERE] [NCLS-CORE-00003] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: nnn] [levelValue: 1000] [[
  Exception while running a command
java.lang.NullPointerException
        at fish.payara.appserver.rest.endpoints.config.admin.ListRestEndpointsCommand.getClasses(ListRestEndpointsCommand.java:323)
        at fish.payara.appserver.rest.endpoints.config.admin.ListRestEndpointsCommand.execute(ListRestEndpointsCommand.java:174)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Unknown Source)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Unknown Source)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:169)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:94)
        at fish.payara.micro.impl.PayaraMicroImpl.dumpFinalStatus(PayaraMicroImpl.java:2242)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:991)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:181)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:79)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:358)
]]

[TIMESTAMP] [] [INFO] [] [PayaraMicro] [tid: _ThreadID=1 _ThreadName=main][timeMillis: nnn] [levelValue: 800]
Payara Micro URLs
http://myhost:8080/mywar

'mywar' REST Endpoints
java.lang.NullPointerExceptionjava.lang.NullPointerException

```
## Steps to reproduce (Only for bug reports) 

Deploy the below code as a .war using `java -jar payara-micro-4.1.2.172.jar --deploy helloWorld.war`.

### Samples

The deployed helloworld.war solely consists of the following classes:

```java
import javax.ws.rs.GET;
import javax.ws.rs.Path;

@Path("/helloworld")
public class HelloWorld {
  @GET
  public String sayHello() {
    return "Hello World";
  }
}
```

```java
import javax.ws.rs.core.Application;
import javax.ws.rs.ApplicationPath;

@ApplicationPath("/app")
public class App extends Application { }
```

## Environment ##

- **Payara Version**: 4.1.1.172
- **Edition**: Micro
- **JDK Version**: Oracle JRE 8u121
- **Operating System**: Windows
- **Database**: none

**Comment by fturizo** [comment]
Greetings @mkarg, unfortunately, I couldn't reproduce the `NullPointerException` that you encountered. At the moment, when running the simple application you described I got the following output:

```
[2017-05-30T18:46:29.196-0500] [] [INFO] [] [PayaraMicro] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1496187989196] [levelValue: 800]
Payara Micro URLs
http://FT-POWER-LAPTOP:8080/SampleRestTest-1.0.0

'SampleRestTest-1.0.0' REST Endpoints
GET     /SampleRestTest-1.0.0/app/helloworld

[2017-05-30T18:46:29.197-0500] [] [INFO] [] [PayaraMicro] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1496187989197] [levelValue: 800] Payara Micro  4.1.2.172 #badassmicrofish (build 235) ready in 8.499 (ms)
```

Do you recall any other details of this scenario that can help reproduce this issue? Maybe a custom configuration on the _web.xml_ or _glassfish-web.xml_ deployment descriptors for example?

**Comment by mkarg** [comment]
@fturizo There are not more details. Here is what I did: Build a war file out of the above two source files. Downloaded Payara Micro 4.1.2.172. Started it using `java.exe -jar payara-micro--4.1.2.172.jar --deploy helloworld-1.0.0-SNAPSHOT.war`. I did not provide any configuration files or deployment descriptors.

**Comment by mkarg** [comment]
@fturizo By simply looking at the failing code line [ListRestEndpointsCommand.java:323](https://github.com/payara/Payara/blob/91f0ec82384521139ce5e085b756320f3755dac3/appserver/payara-appserver-modules/payara-rest-endpoints/src/main/java/fish/payara/appserver/rest/endpoints/config/admin/ListRestEndpointsCommand.java#L323) it was pretty clear why it fails here but not on your side. I used _exactly_ the same code as shown above (it has _no_ package). Apparently you did not use _exactly_ the same code (yours _has_ a package).

Workaround: Once I use packages, the bug does not appear anymore.

Solution: The bug apparently is that in line 323 you must check whether `Class::getPackage` returned `null`!

**Comment by fturizo** [comment]
Thanks for the clarification and for submitting the PR @mkarg! The use of the default package is not recommended on real world scenarios but is nice to have that condition guarded in the code!

**Comment by mkarg** [comment]
@fturizo See, _not recommended_ is something different that _forbidden_. As a JSR 370 EG member, for me only the terms _allowed_ and _forbidden_ exist when testing software. ;-)

**Comment by esafzay** [comment]
A similar NullPointerException is on [ListRestEndpointsCommand.java:267](https://github.com/payara/Payara/blob/034208b3ecae94085412a02d77a093277e57d4a8/appserver/payara-appserver-modules/payara-rest-endpoints/src/main/java/fish/payara/appserver/rest/endpoints/config/admin/ListRestEndpointsCommand.java#L267)
