### ISSUE TITLE
java.lang.NoClassDefFoundError when using Payara Micro with hazelcast-aws

### ISSUE THREAD

**Issue by robelcik** [payara/Payara#1674]
# Description #
----------
`java.lang.NoClassDefFoundError: com/hazelcast/spi/discovery/DiscoveryStrategyFactory` is thrown when using Payara Micro 172 with external hazelcast-aws 2.0.1. Everything is fine when hazelcast-aws.jar is embedded in payara-micro.jar.

## Expected Outcome
I expect hazelcast-aws working when included in the classpath, e.g. `java -cp payara-micro.jar:hazelcast-aws-2.0.1.jar ...`

## Current Outcome
`NoClassDefFoundError` is thrown.

Payara and Hazelcast start with success when hazelcast-aws-2.0.1.jar is placed into payara-micro.jar (./MICRO-INF/lib)

```
java.lang.NoClassDefFoundError: com/hazelcast/spi/discovery/DiscoveryStrategyFactory
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:146)
        at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:105)
        at com.hazelcast.nio.ClassLoaderUtil.newInstance(ClassLoaderUtil.java:74)
        at com.hazelcast.util.ServiceLoader$NewInstanceIterator.next(ServiceLoader.java:329)
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryStrategies(DefaultDiscoveryService.java:147)
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.<init>(DefaultDiscoveryService.java:60)
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryServiceProvider.newDiscoveryService(DefaultDiscoveryServiceProvider.java:29)
        at com.hazelcast.instance.Node.createDiscoveryService(Node.java:263)
        at com.hazelcast.instance.Node.<init>(Node.java:212)
        at com.hazelcast.instance.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:163)
        at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:130)
        at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:176)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:126)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
        at fish.payara.nucleus.hazelcast.HazelcastCore.bootstrapHazelcast(HazelcastCore.java:311)
        at fish.payara.nucleus.hazelcast.HazelcastCore.getMemberName(HazelcastCore.java:140)
```

## Steps to reproduce (Only for bug reports) 
I run Payara Micro with following command:

`java -cp payara-micro.jar:hazelcast-aws-2.0.1.jar:mysql-connector-java-5.1.42.jar fish.payara.micro.PayaraMicro --prebootcommandfile preboot-commands.txt --hzconfigfile hazelcast-config.xml --deploy my-app.war`

Contents of preboot-commands.txt:

```
create-jdbc-connection-pool --datasourceclassname com.mysql.jdbc.jdbc2.optional.MysqlDataSource --restype javax.sql.DataSource --property User=root:Password=mypass:DatabaseName=mydb:ServerName=myserver.amazonaws.com:Port=3306 MyPool
create-jdbc-resource --connectionpoolid MyPool jdbc/MyJdbc
```

Contents of hazelcast-config.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.8.xsd"
           xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <properties>
     <property name="hazelcast.discovery.enabled">true</property>
  </properties>
  <network>
    <join>
      <tcp-ip enabled="false" />
      <multicast enabled="false"/>
      <aws enabled="false" />
      <discovery-strategies>
        <discovery-strategy enabled="true" class="com.hazelcast.aws.AwsDiscoveryStrategy">
          <properties>
            <property name="access-key">MY_ACCESS_KEY</property>
            <property name="secret-key">MY_SECRET_KEY</property>
            <property name="region">eu-west-1</property>
            <property name="tag-key">Name</property>
            <property name="tag-value">MyName</property>
          </properties>
        </discovery-strategy>
      </discovery-strategies>
    </join>
  </network>
</hazelcast>
```

## Environment ##

- **Payara Version**: 4.1.2.172
- **Edition**: Micro
- **JDK Version**:  8 u131 - OpenJDK
- **Operating System**: Linux
- **Database**: MySQL

**Comment by OndrejM** [comment]
Hi @robelcik, adding JAR files to the classpath won't work with Payara Micro, because it uses classloaders to load server modules and libraries and won't consider libraries placed on the root classpath.

In version 4.1.2.173, there's a new command line argument `--addJars` which should be used to add additional libraries instead of `-cp`:

```
java fish.payara.micro.PayaraMicro --addJars payara-micro.jar:hazelcast-aws-2.0.1.jar:mysql-connector-java-5.1.42.jar --prebootcommandfile preboot-commands.txt --hzconfigfile hazelcast-config.xml --deploy my-app.war
```

In version 4.1.2.172 which you are using, the only way to add libraries is to drp them inside payara-micro.jar into `MICRO-INF/runtime` inside `payara-micro.jar`

More documentation about the `--addJars` option is in our documentation about [Adding Third-Party JARs](https://docs.payara.fish/documentation/payara-micro/adding-jars.html).

**Comment by mikecroft** [comment]
Hi @robelcik - to illustrate @OndrejM's comment, I have created a simple demo to illustrate the AWS joiner which you can find here:
https://github.com/mikecroft/payara-hazelcast-aws

**Comment by robelcik** [comment]
Thank you a lot, @OndrejM and @mikecroft!
