### ISSUE TITLE
Remote EJB lookup failed after upgrade from 171 to 172

### ISSUE THREAD

**Issue by z-mathe** [payara/Payara#1677]
Hi,

After upgrade from v171 to v172 community stream version, an error occured if we lookup from backend clustered system to the frontend clustered system (with unchanged applications and configurations).
Other local type lookups work well.

Backend EJB configuration files:
```
<ejb-jar>
  <enterprise-beans>
    ...
    <session>
      <ejb-name>BackendSFBean</ejb-name>
      <transaction-type>Container</transaction-type>
      <ejb-ref>
        <ejb-ref-name>ejb/FrontendSFBean</ejb-ref-name>
        <ejb-ref-type>Session</ejb-ref-type>
        <remote>mycompany.sf.FrontendSFRemote</remote>
      </ejb-ref>
    </session>
    ...
  </enterprise-beans>
</ejb-jar>

<glassfish-ejb-jar>
  <enterprise-beans>
    ...
    <ejb>
      <ejb-name>BackendSFBean</ejb-name>
      <jndi-name>ejb/BackendSFBean</jndi-name>
      <ejb-ref>
        <ejb-ref-name>ejb/FrontendSFBean</ejb-ref-name>
        <jndi-name>corbaname:iiop:ejbfrontendhost1:33700,iiop:ejbfrontendhost2:33700#ejb/FrontendSFBean</jndi-name>
      </ejb-ref>
    </ejb>
    ...
  </enterprise-beans>
</glassfish-ejb-jar>
```
backend code:
```
javax.naming.Context ctx = new javax.naming.InitialContext();
FrontendSFRemote remote = (FrontendSFRemote)ctx.lookup("java:comp/env/ejb/FrontendSFBean"); //this JNDI subcontext originally from external properties file
```
server.log:
```
...
javax.naming.NamingException: Lookup failed for 'java:comp/env/ejb/FrontendSFBean' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming} [Root exception is javax.naming.NamingException: Exception resolving Ejb for 'Remote ejb-ref name=ejb/FrontendSFBean,Remote 3.x interface =mycompany.sf.FrontendSFRemote,ejb-link=null,lookup=,mappedName=,jndi-name=corbaname:iiop:ejbfrontendhost1:33700,iiop:ejbfrontendhost2:33700#ejb/FrontendSFBean,refType=Session' .  Actual (possibly internal) Remote JNDI name used for lookup is 'corbaname:iiop:ejbfrontendhost1:33700,iiop:ejbfrontendhost2:33700#ejb/FrontendSFBean__3_x_Internal_RemoteBusinessHome__' [Root exception is org.omg.CORBA.BAD_PARAM: FINE: 00100009: string_to_object conversion failed due to bad schema specific part in name ejb/FrontendSFBean__3_x_Internal_RemoteBusinessHome__  vmcid: SUN  minor code: 9  completed: No]]
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:494)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:440)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at mycompany.sf.BackendSFBean.anyBackendMethod(BackendSFBean.java:9640)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4762)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at mycompany.interceptor.AuditInterceptor.logMethodCall(AuditInterceptor.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:73)
	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor138.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor92.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:374)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4734)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4722)
	at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:205)
	at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:123)
	at com.sun.proxy.$Proxy538.anyBackendMethod(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie.dispatchToMethod(ReflectiveTie.java:143)
	at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie._invoke(ReflectiveTie.java:173)
	at com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatchToServant(ServerRequestDispatcherImpl.java:528)
	at com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatch(ServerRequestDispatcherImpl.java:199)
	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequestRequest(MessageMediatorImpl.java:1564)
	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequest(MessageMediatorImpl.java:1440)
	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleInput(MessageMediatorImpl.java:945)
	at com.sun.corba.ee.impl.protocol.giopmsgheaders.RequestMessage_1_2.callback(RequestMessage_1_2.java:213)
	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequest(MessageMediatorImpl.java:709)
	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.dispatch(MessageMediatorImpl.java:508)
	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.doWork(MessageMediatorImpl.java:2237)
	at com.sun.corba.ee.impl.threadpool.ThreadPoolImpl$TaskRunner.run(ThreadPoolImpl.java:178)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.naming.NamingException: Exception resolving Ejb for 'Remote ejb-ref name=ejb/FrontendSFBean,Remote 3.x interface =mycompany.sf.FrontendSFRemote,ejb-link=null,lookup=,mappedName=,jndi-name=corbaname:iiop:ejbfrontendhost1:33700,iiop:ejbfrontendhost2:33700#ejb/FrontendSFBean,refType=Session' .  Actual (possibly internal) Remote JNDI name used for lookup is 'corbaname:iiop:ejbfrontendhost1:33700,iiop:ejbfrontendhost2:33700#ejb/FrontendSFBean__3_x_Internal_RemoteBusinessHome__' [Root exception is org.omg.CORBA.BAD_PARAM: FINE: 00100009: string_to_object conversion failed due to bad schema specific part in name ejb/FrontendSFBean__3_x_Internal_RemoteBusinessHome__  vmcid: SUN  minor code: 9  completed: No]
	at com.sun.ejb.EjbNamingReferenceManagerImpl.resolveEjbReference(EjbNamingReferenceManagerImpl.java:188)
	at com.sun.enterprise.container.common.impl.ComponentEnvManagerImpl$EjbReferenceProxy.create(ComponentEnvManagerImpl.java:1015)
	at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.lookup(GlassfishNamingManagerImpl.java:745)
	at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.lookup(GlassfishNamingManagerImpl.java:715)
	at com.sun.enterprise.naming.impl.JavaURLContext.lookup(JavaURLContext.java:159)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:474)
	... 67 more
Caused by: org.omg.CORBA.BAD_PARAM: FINE: 00100009: string_to_object conversion failed due to bad schema specific part in name ejb/FrontendSFBean__3_x_Internal_RemoteBusinessHome__  vmcid: SUN  minor code: 9  completed: No
	at com.sun.proxy.$Proxy227.soBadSchemaSpecific(Unknown Source)
	at com.sun.corba.ee.impl.resolver.INSURLOperationImpl.resolveCorbaname(INSURLOperationImpl.java:227)
	at com.sun.corba.ee.impl.resolver.INSURLOperationImpl.resolveINSURL(INSURLOperationImpl.java:154)
	at com.sun.corba.ee.impl.resolver.INSURLOperationImpl.operate(INSURLOperationImpl.java:145)
	at com.sun.corba.ee.impl.orb.ORBImpl.string_to_object(ORBImpl.java:977)
	at com.sun.ejb.EjbNamingReferenceManagerImpl.resolveEjbReference(EjbNamingReferenceManagerImpl.java:181)
	... 72 more
Caused by: org.omg.CosNaming.NamingContextPackage.NotFound: IDL:omg.org/CosNaming/NamingContext/NotFound:1.0
	at org.omg.CosNaming.NamingContextPackage.NotFoundHelper.read(NotFoundHelper.java:72)
	at org.omg.CosNaming._NamingContextExtStub.resolve_str(_NamingContextExtStub.java:165)
	at com.sun.corba.ee.impl.resolver.INSURLOperationImpl.resolveCorbaname(INSURLOperationImpl.java:222)
	... 76 more
```

## Environment ##

- **Payara Version**: 4.1.1.172
- **Edition**: Full
- **JDK Version**: 8 u131 Oracle
- **Operating System**: Windows

**Comment by dorpsidioot** [comment]
It's not only happening with remote EJB's either. I've seen these issues with lookups of an EJB within an EAR project too. When a REST service in the WAR injects via @EJB a @Stateless @LocalBean EJB from within an accompanied ejb-jar, it also fails.
171.1 is fine, 172 fails miserably here.

**Comment by smillidge** [comment]
Can you help us create a test case to narrow this down?

**Comment by dorpsidioot** [comment]
I'll see if I can setup a small test project to recreate the issue itself.

**Comment by lprimak** [comment]
Added PAYARA-1753 to track this issue

**Comment by z-mathe** [comment]
I'll have time for the weekend and then I'll make a test package focusing on this case.

**Comment by lprimak** [comment]
@z-mathe I was not able to get your example above to work in .171 either
Can you please post a complete example (http://sscce.org) compilable / runnable etc.
Thank you

**Comment by lprimak** [comment]
I have uploaded an example that I am working with.
If you can modify and re-upload it here it would be great, thanks!

**Comment by lprimak** [comment]
[CorbaLookupExample.zip](https://github.com/payara/Payara/files/1100688/CorbaLookupExample.zip)

**Comment by lprimak** [comment]
[CorbaLookupReproducer.zip](https://github.com/payara/Payara/files/1100894/CorbaLookupReproducer.zip)

**Comment by z-mathe** [comment]
@lprimak: Please wait a few more days, unfortunately on this week, I have to go through an OpenAM migration (I don't have enough time for an accurate analysis).
In our Payara v172 environments as a workaround, we have replaced the four CORBA jars from version 164 due to the #1673 (although version 171 works as well).

**Comment by lprimak** [comment]
@z-mathe Will be looking forward to the modified reproducer app
thanks!

**Comment by lprimak** [comment]
@z-mathe any progress on the reproducer?
Thank you

**Comment by z-mathe** [comment]
@lprimak  Unfortunately, it is still in progress. We know, that the simple remote lookup works well, but the double Corba remote lookup (e.g. front->back->front or delphi corba app->back->front) does not work. We try to paste it into the reproducer app.
In the big environment, if we lookup e.q. from a timer (this is similar with your @Startup annotation in the ClientBean), everything is alright, but if you had a previous corba remote lookup, the above exception occured.

**Comment by z-mathe** [comment]
@lprimak the modified reproducer: [CorbaLookupReproducer.zip](https://github.com/payara/Payara/files/1153466/CorbaLookupReproducer.zip) (need to deploy the backend to one backendhost, and the frontend + webclient together to another frontendhost). Running the webclient, if no problem, an "It works!" title displayed on the browser, otherwise the exception callstack can be viewed (like a similar with the original callstack).

But the proplem occured only, if the backend and frontend EJB module located on different hosts (on localhost with 2 wellconfigured payara server (different orb ports, e.g. 3700/23700) instances does not occur), and the real remote lookup count is more than one (we tried these lookups: j2se->backend->frontend, frontend->backend->frontend with deployed enterprise archives originated from the above reproducer code without maven configs).

We have the feeling, that a similar behaviour may be the reason: #1566, would you confirm your testing? The second lookup context for something to go wrong, if we first lookup instantly for the second iiop address, there's no problem. But it's strange that there are good iiop server addresses located in the error messages of the second lookup trying (so the #1566 cannot not be the solution). :(

Thank you.

**Comment by z-mathe** [comment]
The version change of Payara between 172 and 171 (back and forth), the following is sufficient:
- after server shutdown, replace in the \module\ folder the 4 Corba jars (glassfish-corba*.jar) to the necessary version and remove the \felix folder from \osgi-cache folder, then start the server again to rebuild the osgi cache.

**Comment by lprimak** [comment]
Ok, it's in my queue, I will try to reproduce it given your explanation and code
Created internal JIRA PAYARA-1861

**Comment by z-mathe** [comment]
@lprimak Sorry, some pom xml contained unnecessary parent references (which caused some build exceptions), the corrected sorce: [CorbaLookupReproducer.zip](https://github.com/payara/Payara/files/1155156/CorbaLookupReproducer.zip). This morning we re-tested this source with my colleagues between our own remote machines.

**Comment by lprimak** [comment]
Yea, no worries.  Given my schedule I won't get to this for about a week or two anyway.

**Comment by lprimak** [comment]
I tried to follow your instructions but now I can't get it to succeed at all.
I replaced the Payara .164 CORBA modules into my workspace and I am still getting the exception
Are you sure you can get this reproducer to run at all?

**Comment by lprimak** [comment]
Never mind, it was a setup problem on my side, but now I am getting an opposite problem, I still cannot get it to fail.  Are you saying that you absolutely need more than one host for this to fail?  VPN on the same host won't work or something like that?

**Comment by lprimak** [comment]
Good news, I was able to reproduce this, issue.

**Comment by z-mathe** [comment]
Wow! I've been worried about seeing previous posts. :)

**Comment by lprimak** [comment]
Hi, @z-mathe Can you test the patched CORBA module?
[glassfish-corba-orb.jar.zip](https://github.com/payara/Payara/files/1180846/glassfish-corba-orb.jar.zip)
just replace the one from .172 in ```<payara>modules/``` directory and remove all the appropriate ```<domain>/osgi-cache/``` directories.

Thank you

**Comment by z-mathe** [comment]
Hi, @lprimak Perfect! :) (not just this, but the #1673 also works well)
Thank you.

**Comment by lprimak** [comment]
Glad to hear it works for you in a real environment
