### ISSUE TITLE
NoSuchFieldError: applicationMap at server stopping

### ISSUE THREAD

**Issue by z-mathe** [payara/Payara#1683]
Hi,

After shutting down the Payara server, we get the error message below for all web applications one after the other. What configuration can you get rid of this (I did not think about loglevel filter)?

```
[#|2017-06-16T10:43:12.752+0200|SEVERE|Payara 4.1|javax.enterprise.web|_ThreadID=461;_ThreadName=RunLevelControllerThread-1497602589485;_TimeMillis=1497602592752;_LevelValue=1000;|WebModule[/anyWebApp]Exception sending context destroyed event to listener instance of class com.sun.faces.config.ConfigureListener
java.lang.NoSuchFieldError: applicationMap
	at javax.faces.FactoryFinder.releaseFactories(FactoryFinder.java:330)
	at com.sun.faces.config.ConfigureListener.contextDestroyed(ConfigureListener.java:369)
	at org.apache.catalina.core.StandardContext.contextListenerStop(StandardContext.java:5480)
	at org.apache.catalina.core.StandardContext.stop(StandardContext.java:6177)
	at com.sun.enterprise.web.WebModule.stop(WebModule.java:725)
	at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:1172)
	at com.sun.enterprise.web.WebContainer.unloadWebModule(WebContainer.java:2452)
	at com.sun.enterprise.web.WebContainer.unloadWebModule(WebContainer.java:2407)
	at com.sun.enterprise.web.WebApplication.stop(WebApplication.java:190)
	at org.glassfish.internal.data.EngineRef.stop(EngineRef.java:161)
	at org.glassfish.internal.data.ModuleInfo.stop(ModuleInfo.java:324)
	at org.glassfish.internal.data.ApplicationInfo.stop(ApplicationInfo.java:381)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.unload(ApplicationLifecycle.java:1060)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.disable(ApplicationLifecycle.java:2128)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.disable(ApplicationLifecycle.java:114)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.stopApplication(ApplicationLoaderService.java:496)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.preDestroy(ApplicationLoaderService.java:464)
	at org.jvnet.hk2.internal.ClazzCreator.preDestroyMe(ClazzCreator.java:339)
	at org.jvnet.hk2.internal.ClazzCreator.dispose(ClazzCreator.java:404)
	at org.jvnet.hk2.internal.SystemDescriptor.dispose(SystemDescriptor.java:526)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.destroyOne(AsyncRunLevelContext.java:328)
	at org.glassfish.hk2.runlevel.RunLevelContext.destroyOne(RunLevelContext.java:101)
	at org.jvnet.hk2.internal.ServiceHandleImpl.destroy(ServiceHandleImpl.java:183)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$DownQueueRunner.run(CurrentTaskFuture.java:1270)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
|#]

[#|2017-06-16T10:43:12.753+0200|SEVERE|Payara 4.1|javax.enterprise.resource.webcontainer.jsf.config|_ThreadID=461;_ThreadName=RunLevelControllerThread-1497602589485;_TimeMillis=1497602592753;_LevelValue=1000;|Unexpected state during contextDestroyed: no ConfigManager instance in current ServletContext but one is expected to exist.|#]
```

## Environment ##

- **Payara Version**: 4.1.1.171
- **Edition**: Full
- **JDK Version**: 8 u131 - Oracle
- **Operating System**: Windows

**Comment by lprimak** [comment]
Are you shipping your own version of JSF (Mojarra) with your applications?
Maybe javax.sevlet JARs?
I extensively use JSF and never seen this

Sounds like there are some duplicate incompatible Java EE components in your WARs (or EARs)

**Comment by z-mathe** [comment]
Thank you, this excpetion is my mistake. Sorry for time wasting. Closing this issue.

**Comment by z-mathe** [comment]
I've examined all applications, but there is only one javax.faces.jar under the glassfish folder (in the \modules\ folder). From applications \WEB-INF\ folder had been removed earlier the bundled own version of javax.faces.jar-s (originated from old Glassfish 3.1.2 environment). So I don't know why.

**Comment by z-mathe** [comment]
It's over, so I'll finish it. Sorry for the time wasting...

**Comment by z-mathe** [comment]
The \osgi-cache\felix folder delete than regenerate by next restart resolved this case.
Thank you.
