### ISSUE TITLE
Payara micro startup problems when starting multiple instances

### ISSUE THREAD

**Issue by larslorenzen** [payara/Payara#1684]
# Description #
----------
When starting new micro payara instances that join an existing cluster which is under load then those won't start.

We are using payara micro inside a docker container running in kubernetes.
When the autoscaler begins starting new pods, those pods won't start.
Our application uses the hazelcast kubernetes plugin to form a cluster and JCache.

When the cluster is idle and not receiving any requests, the problem does not occur and new instances start without problems.

## Expected Outcome
New instances start and join the cluster without problems.

Just checked: works with payara micro 164.

## Current Outcome

The following exception is thrown:
```
[2017-06-16T11:51:22.608+0000] [] [INFO] [] [org.glassfish.ha.store.spi.BackingStoreFactoryRegistry] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1497613882608] [levelValue: 800] Registered fish.payara.ha.hazelcast.store.HazelcastBackingStoreFactoryProxy for persistence-type = hazelcast in BackingStoreFactoryRegistry

[2017-06-16T11:51:22.609+0000] [] [INFO] [] [fish.payara.ha.hazelcast.store.HazelcastBackingStoreFactory] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1497613882609] [levelValue: 800] Registered Hazelcast BackingStoreFactory with persistence-type = hazelcast

[2017-06-16T11:51:22.741+0000] [] [INFO] [] [com.hazelcast.config.UrlXmlConfig] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1497613882741] [levelValue: 800] Configuring Hazelcast from 'file:/tmp/payaramicro-rt1542412495098867746tmp/config/hazelcast.xml'.

[2017-06-16T11:51:22.781+0000] [] [WARNING] [] [com.hazelcast.config.AbstractXmlConfigHelper] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1497613882781] [levelValue: 900] Name of the hazelcast schema location incorrect using default

[2017-06-16T11:51:22.950+0000] [] [INFO] [] [com.hazelcast.instance.DefaultAddressPicker] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1497613882950] [levelValue: 800] [LOCAL] [dev] [3.8] Prefer IPv4 stack is true.

[2017-06-16T11:51:22.955+0000] [] [INFO] [] [com.hazelcast.instance.DefaultAddressPicker] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1497613882955] [levelValue: 800] [LOCAL] [dev] [3.8] Picked [10.43.160.5]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true

[2017-06-16T11:51:22.968+0000] [] [INFO] [] [com.hazelcast.system] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1497613882968] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] Hazelcast 3.8 (20170217 - d7998b4) starting at [10.43.160.5]:5701

[2017-06-16T11:51:22.968+0000] [] [INFO] [] [com.hazelcast.system] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1497613882968] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] Copyright (c) 2008-2017, Hazelcast, Inc. All Rights Reserved.

[2017-06-16T11:51:22.969+0000] [] [INFO] [] [com.hazelcast.system] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1497613882969] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] Configured Hazelcast Serialization version : 1

[2017-06-16T11:51:23.192+0000] [] [INFO] [] [com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1497613883192] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] Backpressure is disabled

[2017-06-16T11:51:23.630+0000] [] [INFO] [] [com.hazelcast.spi.discovery.integration.DiscoveryService] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1497613883630] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] Kubernetes Discovery properties: { service-dns: null, service-dns-timeout: 5, service-name: ils-rng-hazelcast, service-label: app, service-label-value: ils-rng, namespace: ring, kubernetes-master: https://kubernetes.default.svc}

[2017-06-16T11:51:23.634+0000] [] [INFO] [] [com.hazelcast.spi.discovery.integration.DiscoveryService] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1497613883634] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] Kubernetes Discovery: Bearer Token { null }

[2017-06-16T11:51:23.700+0000] [] [INFO] [] [com.hazelcast.spi.discovery.integration.DiscoveryService] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1497613883700] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] Kubernetes Discovery activated resolver: ServiceEndpointResolver

[2017-06-16T11:51:23.700+0000] [] [INFO] [] [com.hazelcast.instance.Node] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1497613883700] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] Activating Discovery SPI Joiner

[2017-06-16T11:51:23.887+0000] [] [INFO] [] [com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1497613883887] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] Starting 8 partition threads

[2017-06-16T11:51:23.889+0000] [] [INFO] [] [com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1497613883889] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] Starting 5 generic threads (1 dedicated for priority tasks)

[2017-06-16T11:51:23.897+0000] [] [INFO] [] [com.hazelcast.core.LifecycleService] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1497613883897] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] [10.43.160.5]:5701 is STARTING

[2017-06-16T11:51:29.396+0000] [] [INFO] [] [com.hazelcast.nio.tcp.InitConnectionTask] [tid: _ThreadID=71 _ThreadName=hz._hzInstance_1_dev.cached.thread-2] [timeMillis: 1497613889396] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] Connecting to /10.43.160.1:5701, timeout: 0, bind-any: true

[2017-06-16T11:51:29.396+0000] [] [INFO] [] [com.hazelcast.nio.tcp.InitConnectionTask] [tid: _ThreadID=80 _ThreadName=hz._hzInstance_1_dev.cached.thread-3] [timeMillis: 1497613889396] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] Connecting to /10.43.208.3:5701, timeout: 0, bind-any: true

[2017-06-16T11:51:29.396+0000] [] [INFO] [] [com.hazelcast.nio.tcp.InitConnectionTask] [tid: _ThreadID=69 _ThreadName=hz._hzInstance_1_dev.cached.thread-1] [timeMillis: 1497613889396] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] Connecting to /10.43.224.2:5701, timeout: 0, bind-any: true

[2017-06-16T11:51:29.401+0000] [] [INFO] [] [com.hazelcast.nio.tcp.TcpIpConnectionManager] [tid: _ThreadID=71 _ThreadName=hz._hzInstance_1_dev.cached.thread-2] [timeMillis: 1497613889401] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] Established socket connection between /10.43.160.5:40509 and /10.43.160.1:5701

[2017-06-16T11:51:29.402+0000] [] [INFO] [] [com.hazelcast.nio.tcp.TcpIpConnectionManager] [tid: _ThreadID=69 _ThreadName=hz._hzInstance_1_dev.cached.thread-1] [timeMillis: 1497613889402] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] Established socket connection between /10.43.160.5:42063 and /10.43.224.2:5701

[2017-06-16T11:51:29.403+0000] [] [INFO] [] [com.hazelcast.nio.tcp.TcpIpConnectionManager] [tid: _ThreadID=80 _ThreadName=hz._hzInstance_1_dev.cached.thread-3] [timeMillis: 1497613889403] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] Established socket connection between /10.43.160.5:39401 and /10.43.208.3:5701

[2017-06-16T11:51:35.402+0000] [] [INFO] [] [com.hazelcast.nio.tcp.SocketAcceptorThread] [tid: _ThreadID=79 _ThreadName=hz._hzInstance_1_dev.IO.thread-Acceptor] [timeMillis: 1497613895402] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] Accepting socket connection from /10.43.208.4:45750

[2017-06-16T11:51:35.403+0000] [] [INFO] [] [com.hazelcast.nio.tcp.SocketAcceptorThread] [tid: _ThreadID=79 _ThreadName=hz._hzInstance_1_dev.IO.thread-Acceptor] [timeMillis: 1497613895403] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] Accepting socket connection from /10.43.224.4:32890

[2017-06-16T11:51:35.404+0000] [] [INFO] [] [com.hazelcast.nio.tcp.TcpIpConnectionManager] [tid: _ThreadID=80 _ThreadName=hz._hzInstance_1_dev.cached.thread-3] [timeMillis: 1497613895404] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] Established socket connection between /10.43.160.5:5701 and /10.43.208.4:45750

[2017-06-16T11:51:35.405+0000] [] [INFO] [] [com.hazelcast.nio.tcp.TcpIpConnectionManager] [tid: _ThreadID=71 _ThreadName=hz._hzInstance_1_dev.cached.thread-2] [timeMillis: 1497613895405] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] Established socket connection between /10.43.160.5:5701 and /10.43.224.4:32890

[2017-06-16T11:51:35.424+0000] [] [INFO] [] [com.hazelcast.system] [tid: _ThreadID=57 _ThreadName=hz._hzInstance_1_dev.generic-operation.thread-2] [timeMillis: 1497613895424] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] Cluster version set to 3.8

[2017-06-16T11:51:35.426+0000] [] [INFO] [] [com.hazelcast.internal.cluster.ClusterService] [tid: _ThreadID=57 _ThreadName=hz._hzInstance_1_dev.generic-operation.thread-2] [timeMillis: 1497613895426] [levelValue: 800] [[
  [10.43.160.5]:5701 [dev] [3.8] 

Members [6] {
	Member [10.43.160.1]:5701 - 5e451e6a-d3c7-404e-85a6-d796ee939c84
	Member [10.43.208.3]:5701 - b14c12ec-0479-464d-9859-928717af4917
	Member [10.43.224.2]:5701 - 0496c197-d440-4af0-b02a-4b4081489cd1
	Member [10.43.208.4]:5701 - 3a7a0e1c-b781-4c4e-aaab-19981937e992
	Member [10.43.224.4]:5701 - 42646dc6-70a4-4782-9c7c-49701c28d579
	Member [10.43.160.5]:5701 - c99c8876-476e-4a47-bf79-6bcd65065d31 this
}
]]

Exception in thread "hz._hzInstance_1_dev.cached.thread-1" Exception in thread "hz._hzInstance_1_dev.cached.thread-4" com.hazelcast.cache.CacheNotExistsException: Couldn't find cache config with name configs
	at com.hazelcast.cache.impl.AbstractCacheService.checkCacheSimpleConfig(AbstractCacheService.java:213)
	at com.hazelcast.cache.impl.AbstractCacheService.createDistributedObject(AbstractCacheService.java:193)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.doCreateProxy(ProxyRegistry.java:174)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.createProxy(ProxyRegistry.java:167)
	at com.hazelcast.spi.impl.proxyservice.impl.operations.PostJoinProxyOperation$1.run(PostJoinProxyOperation.java:63)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
com.hazelcast.cache.CacheNotExistsException: Couldn't find cache config with name gameConfigs
	at com.hazelcast.cache.impl.AbstractCacheService.checkCacheSimpleConfig(AbstractCacheService.java:213)
	at com.hazelcast.cache.impl.AbstractCacheService.createDistributedObject(AbstractCacheService.java:193)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.doCreateProxy(ProxyRegistry.java:174)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.createProxy(ProxyRegistry.java:167)
	at com.hazelcast.spi.impl.proxyservice.impl.operations.PostJoinProxyOperation$1.run(PostJoinProxyOperation.java:63)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
[2017-06-16T11:51:35.462+0000] [] [INFO] [] [com.hazelcast.cache.impl.CacheService] [tid: _ThreadID=57 _ThreadName=hz._hzInstance_1_dev.generic-operation.thread-2] [timeMillis: 1497613895462] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] Added cache config: CacheConfig{name='configs', managerPrefix='/hz/', inMemoryFormat=BINARY, backupCount=1, hotRestart=HotRestartConfig{enabled=false, fsync=false}}

[2017-06-16T11:51:35.463+0000] [] [INFO] [] [com.hazelcast.cache.impl.CacheService] [tid: _ThreadID=57 _ThreadName=hz._hzInstance_1_dev.generic-operation.thread-2] [timeMillis: 1497613895463] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] Added cache config: CacheConfig{name='gameConfigs', managerPrefix='/hz/', inMemoryFormat=BINARY, backupCount=1, hotRestart=HotRestartConfig{enabled=false, fsync=false}}

[2017-06-16T11:51:35.957+0000] [] [WARNING] [] [com.hazelcast.internal.partition.InternalPartitionService] [tid: _ThreadID=54 _ThreadName=hz._hzInstance_1_dev.priority-generic-operation.thread-0] [timeMillis: 1497613895957] [levelValue: 900] [10.43.160.5]:5701 [dev] [3.8] Master version should be greater than ours! Local version: 60720, Master version: 60719 Master: [10.43.160.1]:5701

[2017-06-16T11:51:37.428+0000] [] [INFO] [] [com.hazelcast.core.LifecycleService] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1497613897428] [levelValue: 800] [10.43.160.5]:5701 [dev] [3.8] [10.43.160.5]:5701 is STARTED

[2017-06-16T11:51:37.431+0000] [] [INFO] [NCLS-CORE-00015] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1497613897431] [levelValue: 800] [[
  Shutdown requested
MultiException stack 1 of 2
java.lang.NullPointerException
	at fish.payara.nucleus.hazelcast.HazelcastCore.bootstrapHazelcast(HazelcastCore.java:324)
	at fish.payara.nucleus.hazelcast.HazelcastCore.getMemberName(HazelcastCore.java:140)
	at fish.payara.appserver.micro.services.PayaraInstanceImpl.initialiseInstanceDescriptor(PayaraInstanceImpl.java:327)
	at fish.payara.appserver.micro.services.PayaraInstanceImpl.postConstruct(PayaraInstanceImpl.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1262)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:332)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:374)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:228)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpOneLevel.run(CurrentTaskFuture.java:762)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpAllTheWay.go(CurrentTaskFuture.java:561)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpAllTheWay.access$100(CurrentTaskFuture.java:443)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture.go(CurrentTaskFuture.java:154)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture.go(CurrentTaskFuture.java:149)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.proceedTo(AsyncRunLevelContext.java:436)
	at org.glassfish.hk2.runlevel.internal.RunLevelControllerImpl.proceedTo(RunLevelControllerImpl.java:71)
	at com.sun.enterprise.v3.server.AppServerStartup.proceedTo(AppServerStartup.java:534)
	at com.sun.enterprise.v3.server.AppServerStartup.run(AppServerStartup.java:331)
	at com.sun.enterprise.v3.server.AppServerStartup.doStart(AppServerStartup.java:228)
	at com.sun.enterprise.v3.server.AppServerStartup.start(AppServerStartup.java:219)
	at fish.payara.micro.boot.runtime.MicroGlassFish.start(MicroGlassFish.java:68)
	at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:980)
	at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
	at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:79)
	at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:358)
MultiException stack 2 of 2
java.lang.IllegalStateException: Unable to perform operation: post construct on fish.payara.appserver.micro.services.PayaraInstanceImpl
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:392)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:228)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpOneLevel.run(CurrentTaskFuture.java:762)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpAllTheWay.go(CurrentTaskFuture.java:561)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpAllTheWay.access$100(CurrentTaskFuture.java:443)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture.go(CurrentTaskFuture.java:154)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture.go(CurrentTaskFuture.java:149)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.proceedTo(AsyncRunLevelContext.java:436)
	at org.glassfish.hk2.runlevel.internal.RunLevelControllerImpl.proceedTo(RunLevelControllerImpl.java:71)
	at com.sun.enterprise.v3.server.AppServerStartup.proceedTo(AppServerStartup.java:534)
	at com.sun.enterprise.v3.server.AppServerStartup.run(AppServerStartup.java:331)
	at com.sun.enterprise.v3.server.AppServerStartup.doStart(AppServerStartup.java:228)
	at com.sun.enterprise.v3.server.AppServerStartup.start(AppServerStartup.java:219)
	at fish.payara.micro.boot.runtime.MicroGlassFish.start(MicroGlassFish.java:68)
	at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:980)
	at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
	at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:79)
	at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:358)
]]
```
sorry for the long logs ;)

### Samples

I created a small example project which already produces the exception but not sure if it's really connected:
https://github.com/larslorenzen/micro-jcache

## Environment ##

- **Payara Version**: 4.1.2.172
- **Edition**: Micro
- **JDK Version**: 8 OpenJDK
- **Operating System**: Kubernetes-Docker
- **Database**: MongoDB

**Comment by smillidge** [comment]
Looks like a simple race condition whereby the new member hasn't put into the internal cache the member name before the second member tries to read it.

Internal issue PAYARA-1762 created.

**Comment by smillidge** [comment]
Fixed the race however when starting a data grid like Hazelcast it is best to add a little pause between instances while adding additional nodes. This gives Hazelcast time to rebalance the cluster data. Similarly, when doing controlled shutdown it is best to kill nodes one at a time to avoid killing both the primary and backup data node at the same time.
