### ISSUE TITLE
JDBC cannot reconnect after 'Connection Reset' on Azure SQL

### ISSUE THREAD

**Issue by snipking** [payara/Payara#1720]
# Description #
----------

Create JDBC pool connect to Azure SQL. Sometimes Azure SQL reset the connection when reach some limits. Then the connection pool cannot drop the invalid connection and create new one.

## Expected Outcome

Drop the invalid connection and create new one for following queries.

## Current Outcome

Still using the invalid connection for further queries. Then throw 'The connection is closed' exception.

## Connection pool configuration

```
    <jdbc-connection-pool match-connections="true" validate-atmost-once-period-in-seconds="60" connection-creation-retry-attempts="15" statement-leak-reclaim="true" validation-table-name="dbo.UBConnectionTest" res-type="javax.sql.ConnectionPoolDataSource" connection-creation-retry-interval-in-seconds="6" max-pool-size="30" max-wait-time-in-millis="30000" datasource-classname="com.microsoft.sqlserver.jdbc.SQLServerXADataSource" idle-timeout-in-seconds="1500" name="studentPool" is-connection-validation-required="true" init-sql="select 1 from UBConnectionTest">
      <property name="serverName" value="xxxxxx.database.chinacloudapi.cn"></property>
      <property name="portNumber" value="1433"></property>
      <property name="databaseName" value="xxxxxx"></property>
      <property name="user" value="xxxxxx"></property>
      <property name="password" value="xxxxxxxx"></property>
      <property name="encrypt" value="true"></property>
      <property name="url" value="jdbc:sqlserver://xxxxxx.database.chinacloudapi.cn:1433;database=xxxxxx;user=xxxxxx;password=xxxxxxxx;encrypt=true;hostNameInCertificate=*.database.chinacloudapi.cn;loginTimeout=30;trustServerCertificate=true;"></property>
    </jdbc-connection-pool>
```

## log

```
[#|2017-06-06T05:40:53.597+0000|INFO|Payara 4.1|org.eclipse.persistence.session./file:/opt/payara41/glassfish/domains/domain1/applications/HEMPlatform-ear/HEMPlatform-ejb_jar/_HEMPlatformFNDPU.query|_ThreadID=25;_ThreadName=http-thread-pool(1);_TimeMillis=1496727653597;_LevelValue=800;|
  Communication failure detected when attempting to perform read query outside of a transaction. Attempting to retry query. Error was: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.3.qualifier): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.microsoft.sqlserver.jdbc.SQLServerException: Connection reset
Error Code: 0
Call: SELECT ......

......

[#|2017-06-06T05:41:03.594+0000|WARNING|Payara 4.1|org.eclipse.persistence.session./file:/opt/payara41/glassfish/domains/domain1/applications/HEMPlatform-ear/HEMPlatform-ejb_jar/_HEMPlatformFNDPU|_ThreadID=25;_ThreadName=http-thread-pool(1);_TimeMillis=1496727663594;_LevelValue=900;|
  Local Exception Stack: 
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.3.qualifier): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.microsoft.sqlserver.jdbc.SQLServerException: The connection is closed.
Error Code: 0
Call: SELECT ......
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:340)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.processExceptionForCommError(DatabaseAccessor.java:1620)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:676)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:560)
	at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2056)
	at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:570)
	at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:258)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:299)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectAllRows(DatasourceCallQueryMechanism.java:694)
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRowsFromTable(ExpressionQueryMechanism.java:2740)
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRows(ExpressionQueryMechanism.java:2693)
	at org.eclipse.persistence.queries.ReadAllQuery.executeObjectLevelReadQuery(ReadAllQuery.java:559)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1175)
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:904)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1134)
	at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:460)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1222)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1857)
	at org.eclipse.persistence.internal.sessions.AbstractSession.retryQuery(AbstractSession.java:1928)
	at org.eclipse.persistence.sessions.server.ClientSession.retryQuery(ClientSession.java:694)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.retryQuery(UnitOfWorkImpl.java:5536)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1894)
	at org.eclipse.persistence.internal.sessions.AbstractSession.retryQuery(AbstractSession.java:1928)
	at org.eclipse.persistence.sessions.server.ClientSession.retryQuery(ClientSession.java:694)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.retryQuery(UnitOfWorkImpl.java:5536)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1894)
	at org.eclipse.persistence.internal.sessions.AbstractSession.retryQuery(AbstractSession.java:1928)
	at org.eclipse.persistence.sessions.server.ClientSession.retryQuery(ClientSession.java:694)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.retryQuery(UnitOfWorkImpl.java:5536)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1894)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1839)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1804)
	at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:258)
	at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:473)
	at com.hand.emp.model.facades.UBUserFacade.findByUsername(UBUserFacade.java:51)
	at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4762)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:374)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4734)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4722)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
	at com.sun.proxy.$Proxy239.findByUsername(Unknown Source)
	at com.hand.emp.model.facades.__EJB31_Generated__UBUserFacade__Intf____Bean__.findByUsername(Unknown Source)
	at com.hand.emp.service.base.filter.HEMPSessionFilter.doFilter(HEMPSessionFilter.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:678)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:416)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:466)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:169)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The connection is closed.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:191)
	at com.microsoft.sqlserver.jdbc.SQLServerConnectionPoolProxy.checkClosed(SQLServerConnectionPoolProxy.java:61)
	at com.microsoft.sqlserver.jdbc.SQLServerConnectionPoolProxy.prepareStatement(SQLServerConnectionPoolProxy.java:264)
	at com.sun.gjc.spi.base.ConnectionHolder.prepareStatement(ConnectionHolder.java:583)
	at com.sun.gjc.spi.jdbc40.ConnectionWrapper40.prepareCachedStatement(ConnectionWrapper40.java:255)
	at com.sun.gjc.spi.jdbc40.ConnectionWrapper40.prepareCachedStatement(ConnectionWrapper40.java:52)
	at com.sun.gjc.spi.ManagedConnectionImpl.prepareCachedStatement(ManagedConnectionImpl.java:1049)
	at com.sun.gjc.spi.jdbc40.ConnectionWrapper40.prepareStatement(ConnectionWrapper40.java:173)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.prepareStatement(DatabaseAccessor.java:1565)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.prepareStatement(DatabaseAccessor.java:1514)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseCall.prepareStatement(DatabaseCall.java:778)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:621)
	... 96 more
|#]

```

## Environment ##

- **Payara Version**: 4.1.1.164 #badassfish (build 28)
- **Edition**: 
- **JDK Version**: oracle jdk 1.8.0_112-b15
- **Operating System**: Linux
- **Database**: SQL Server on Azure

**Comment by svendiedrichsen** [comment]
Doesn't this configuration cause some problems?

validate-atmost-once-period-in-seconds="60"

If your reset happens within the 60 seconds since last validation then a reset/closed connection is handed out to the client.

**Comment by mikecroft** [comment]
Indeed, @svendiedrichsen, that's exactly what that property does. Try making sure the timeout is less than the timeout setting for the database, which is apparently 15 seconds by default for SQL server:
https://stackoverflow.com/questions/9158695/whats-the-default-value-of-connecttimeout-in-connection-string
Maybe try a setting of 14 seconds.

**Comment by svendiedrichsen** [comment]
I'd prefer this option to be set:

isconnectvalidatereq=true

Which will validate connections before they are handed out from the pool.
See https://docs.oracle.com/cd/E26576_01/doc.312/e24938/create-jdbc-connection-pool.htm#GSRFM00036

**Comment by mikecroft** [comment]
That can still be set @svendiedrichsen but your `validateatmostonceperiod` (also documented in that link) will modify the behaviour of that property, so the validation will **only** occur if the connection has not been validated within that period.

The default value for the `validateatmostonceperiod` property is `0`, which effectively disables this behaviour and connections will be validated every time (as long as the `isconnectvalidatereq` property is true).

Validation every time a connection is borrowed will incur some performance cost, which is why the period exists. It does need to be balanced with the database and the behaviour of the app in question, though, and may not always be the best option.

**Comment by snipking** [comment]
@svendiedrichsen @mikecroft 

Thanks and I tested set `validate-atmost-once-period-in-seconds="10"`. Indeed when I kill session on DB side this setting will let payara rebuild the pool quicker. But in my case when the `connection reset` happened payara cannot reconnect anymore, even wait more than 10 minutes.

And when this happens we did a `tcpdump`. It seems like under this status connection pool successfully reconnected to DB and close it immediately.

**Comment by mikecroft** [comment]
What does your `findByUsername` method look like?
 (`com.hand.emp.model.facades.UBUserFacade.findByUsername`)

**Comment by snipking** [comment]
```
@Stateless
public class UBUserFacade extends UBAbstractFacade<UBUser> {

    private static final Logger logger = Logger.getLogger(UBUserFacade.class.getName());

    @PersistenceContext(unitName = "HEMPlatformFNDPU")
    private EntityManager em;

    @SuppressWarnings("unchecked")
    public UBUser findByUsername(String username) {
        List<UBUser> user = null;
        Query query1 = em.createNamedQuery("UBUser.findByUsername", UBUser.class);
        query1.setParameter("username", username);
        logger.log(Level.FINE, "find user by username: {0}", username);
        try {
            user = query1.getResultList();
        } catch (Exception ex) {
            logger.log(Level.SEVERE, null, ex);
        }
        if (user == null || user.isEmpty()) {
            return null;
        }
        return user.get(0);
    }
}
```

And the named query `UBUser.findByUsername` is simple query like

```
SELECT xxx, xxx, xxx, xxx, xxx FROM UBUser WHERE ((Username = ?) AND (IsDeleted = ?))
```

And the connection reset occurred randomly. Not only on this query. And sometimes occurred every one or two days, sometimes don't show in several months.

**Comment by mikecroft** [comment]
Hi @snipking some other settings you can try on the connection pool would be to set `idletimeout` to less than the DB timeout, so 14s. When you find you're in a state where one connection has grown stale and timed out, it is likely that many other connections have timed out by then too. The `idletimeout` will not allow a connection to be unused in the pool for longer than that time.

If the validation reduces the frequency of reset connections, and an idle timeout reduces the frequency even more, then to deal with any other times that the pool may have reset connections, the property `failconnection` can be set to true. This means that, if any failure is detected, then the whole pool is immediately marked as failed. You should then find that any unhealthy state is recovered more quickly than the 10 minutes you found earlier.

There doesn't appear to be any problem or bug with Payara here, so I'll close this issue too.

**Comment by frostarun** [comment]
@snipking I would like to know how you solved this ? I have similar problem but not in payara..

**Comment by snipking** [comment]
@frostarun 

Just follow Azure documents. They have many time/connection count limits. Use Azure support request to get exact limit.
