### ISSUE TITLE
Add security dependency broke deployment

### ISSUE THREAD

**Issue by crashko** [payara/Payara#1765]
# Description #
I need to use AppservPasswordLoginModule, but after adding dependency
      <dependency>
            <groupId>org.glassfish.main.security</groupId>
            <artifactId>security-ee</artifactId>
            <version>4.1.2</version>
        </dependency>
I cant deploy application due to exception:

`[2017-07-14T12:42:29.374+0200] [Payara 4.1] [SEVERE] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=75 _ThreadName=admin-thread-pool(1)] [timeMillis: 1500028949374] [levelValue: 1000] [[
  Exception during lifecycle processing
org.glassfish.deployment.common.DeploymentException: CDI deployment failure:WELD-001301: Annotation @org.glassfish.api.admin.RestEndpoints(value=[@org.glassfish.api.admin.RestEndpoint(useForAuthorization=false, description=Update Users, path=update-user, params=[@org.glassfish.api.admin.RestParam(name=authrealmname, value=$parent)], opType=POST, configBean=interface com.sun.enterprise.config.serverbeans.AuthRealm)]) is not a qualifier
	at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:235)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:329)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:497)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:487)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
	at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:534)
	at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:224)
	at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:189)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:466)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:169)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jboss.weld.exceptions.IllegalArgumentException: WELD-001301: Annotation @org.glassfish.api.admin.RestEndpoints(value=[@org.glassfish.api.admin.RestEndpoint(useForAuthorization=false, description=Update Users, path=update-user, params=[@org.glassfish.api.admin.RestParam(name=authrealmname, value=$parent)], opType=POST, configBean=interface com.sun.enterprise.config.serverbeans.AuthRealm)]) is not a qualifier
	at org.jboss.weld.resolution.ResolvableBuilder.checkQualifier(ResolvableBuilder.java:205)
	at org.jboss.weld.resolution.ResolvableBuilder.addQualifier(ResolvableBuilder.java:171)
	at org.jboss.weld.resolution.ResolvableBuilder.addQualifiers(ResolvableBuilder.java:198)
	at org.jboss.weld.resolution.ResolvableBuilder.addQualifiers(ResolvableBuilder.java:193)
	at org.jboss.weld.manager.BeanManagerImpl.resolveDecorators(BeanManagerImpl.java:887)
	at org.jboss.weld.injection.producer.BeanInjectionTarget.initializeAfterBeanDiscovery(BeanInjectionTarget.java:109)
	at org.jboss.weld.injection.producer.InjectionTargetInitializationContext.initialize(InjectionTargetInitializationContext.java:42)
	at org.jboss.weld.injection.producer.InjectionTargetService.initialize(InjectionTargetService.java:63)
	at org.jboss.weld.bootstrap.WeldStartup.deployBeans(WeldStartup.java:442)
	at org.jboss.weld.bootstrap.WeldBootstrap.deployBeans(WeldBootstrap.java:83)
	at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:223)
	... 41 more
]]
`
- **Payara Version**: 4.1.1.164
- **Edition**: Full
- **JDK Version**:  8 OpenJDK
- **Operating System**: Linux
- **Database**: MySQL

**Comment by smillidge** [comment]
Add any Payara/GlassFish dependencies as provided so they are not packaged into your war file?

**Comment by crashko** [comment]
sorry Not fully understand your question :( . I have working application with container-Based Authentication, but now I have to use custom Auth. I found out that I have to extends AppservPasswordLoginModule and tried to added provided maven dependency to project. After that application deployment failed on provided exception.

**Comment by mikecroft** [comment]
Make sure your dependencies have "provided" scope. Otherwise they will cause problems:

```XML
  <groupId>org.glassfish.main.security</groupId>
  <artifactId>security-ee</artifactId>
  <version>4.1.2</version>
  <scope>provided</scope>
```

**Comment by crashko** [comment]
thanks guys! it reasonably helped :)
