### ISSUE TITLE
NoClassDefFoundError: com/hazelcast/com/eclipsesource/json/JsonObject   when using Payara Server and hazelcast-aws

### ISSUE THREAD

**Issue by Imadevops** [payara/Payara#1806]
# Description #
----------

`java.lang.ClassNotFoundException: com.hazelcast.com.eclipsesource.json.JsonObject` is thrown when using Payara 171.1 with the external hazelcast-aws-2.0.1 jar and trying to use the `iam-role` for the SPI Discovery Strategy

## Expected Outcome

I expect Payara to start and for it to use the SPI Discovery Strategy to locate the other AWS instances using the `iam-role` and tag provided in the hazelcast-config.xml

## Current Outcome

When I use `iam-role` with the correct IAM Role, I receive the stacktrace below. This class is located in the default `payara41/glassfish/modules/hazelcast.jar`.  

```
[2017-07-24T16:06:25.366-0400] [Payara 4.1] [SEVERE] [] [com.hazelcast.internal.cluster.impl.DiscoveryJoiner] [tid: _ThreadID=22 _ThreadName=RunLevelControllerThread-1500926780786] [timeMillis: 1500926785366] [levelValue: 1000] [[
  [192.168.136.159]:5701 [dev] [3.7.4] com/hazelcast/com/eclipsesource/json/JsonObject
java.lang.NoClassDefFoundError: com/hazelcast/com/eclipsesource/json/JsonObject
        at com.hazelcast.aws.impl.DescribeInstances.parseAndStoreRoleCreds(DescribeInstances.java:197)
        at com.hazelcast.aws.impl.DescribeInstances.getKeysFromIamRole(DescribeInstances.java:183)
        at com.hazelcast.aws.impl.DescribeInstances.checkKeysFromIamRoles(DescribeInstances.java:98)
        at com.hazelcast.aws.impl.DescribeInstances.<init>(DescribeInstances.java:65)
        at com.hazelcast.aws.AWSClient.getAddresses(AWSClient.java:52)
        at com.hazelcast.aws.AwsDiscoveryStrategy.discoverNodes(AwsDiscoveryStrategy.java:96)
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.discoverNodes(DefaultDiscoveryService.java:74)
        at com.hazelcast.internal.cluster.impl.DiscoveryJoiner.getPossibleAddresses(DiscoveryJoiner.java:43)
        at com.hazelcast.cluster.impl.TcpIpJoiner.joinViaPossibleMembers(TcpIpJoiner.java:135)
        at com.hazelcast.cluster.impl.TcpIpJoiner.doJoin(TcpIpJoiner.java:93)
        at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:135)
        at com.hazelcast.instance.Node.join(Node.java:650)
        at com.hazelcast.instance.Node.start(Node.java:362)
        at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:132)
        at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:176)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:126)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
        at fish.payara.nucleus.hazelcast.HazelcastCore.bootstrapHazelcast(HazelcastCore.java:257)
        at fish.payara.nucleus.hazelcast.HazelcastCore.getMemberName(HazelcastCore.java:105)
        at fish.payara.appserver.micro.services.PayaraInstance.initialiseInstanceDescriptor(PayaraInstance.java:305)
        at fish.payara.appserver.micro.services.PayaraInstance.postConstruct(PayaraInstance.java:179)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1262)
        at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:332)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:374)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:228)
        at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.hazelcast.com.eclipsesource.json.JsonObject
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at com.sun.enterprise.loader.CurrentBeforeParentClassLoader.loadClass(CurrentBeforeParentClassLoader.java:83)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 40 more
]]

```
## Steps to reproduce (Only for bug reports) 

1. Create basic Payara installation on a DAS. 
2. Create 'hazelcast-config'
3. Enable Hazelcast on 'hazelcast-config'
4. Copy hazelcast-config.xml to `config/` folder
5. Create at least one SSH Node with 'install' selected
6. Create one standalone instance on each node referencing 'hazelcast-config'
7. Ensure master-password is on all instances
8. Start one instance
9. Error should be visible in server.log on instance

Contents of hazelcast-config.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.7.xsd"
           xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <group>
        <name>group-name</name>
        <password>group-pass</password>
    </group>
  <properties>
     <property name="hazelcast.discovery.enabled">true</property>
  </properties>
   <network>
        <port auto-increment="false">5700</port>
        <outbound-ports>
            <ports>0</ports>
        </outbound-ports>
        <join>
            <multicast enabled="false" />
            <tcp-ip enabled="false" />
            <aws enabled="false" />
           <discovery-strategies>
              <discovery-strategy  enabled="true" class="com.hazelcast.aws.AwsDiscoveryStrategy">
                <properties>
                   <property name="access-key">my-access-key</property>
                   <property name="secret-key">my-secret-key</property>
                   <property name="iam-role">IAM_ROLE</property>
                   <property name="region">us-west-1</property>
                   <property name="tag-key">TagName</property>
                   <property name="tag-value">TagValue</property>
                   <property name="hz-port">5700</property>
                </properties>
              </discovery-strategy>
            </discovery-strategies>
        </join>
      </network>
</hazelcast>
```
## Context (Optional)

If I enter in the wrong `iam-role`, I receive a stack trace that it could not load the credentials from the AWS meta-data service.  This lets me know that Hazelcast is at least querying the meta-data service to get the credentials.

If I exclude the `iam-role` and use a least-privileged account that only has describe-instances access, instances with the proper tags are discovered and join the Hazelcast cluster.  **This is a workaround at the moment. Obviously an iam-role is preferred**

## Environment ##

- **Payara Version**: 4.1.1.171.1
- **Edition**: Full
- **JDK Version**: 8 u131 - OpenJDK
- **Operating System**: Linux - Amazon Linux
- **Database**: AWS Aurora

**Comment by smillidge** [comment]
The class ```com.hazelcast.com.eclipsesource.json.JsonObject``` is present in the hazelcast jar file shipped with Payara. However Payara is an OSGI environment and these packages are note exported in the OSGI metadata in the MANIFEST of the hazelcast jar. Therefore can not be loaded by classes in the hazelcast-aws-2.0.1 jar. This is a hazelcast bug. Can you raise this on the Hazelcast GitHub?

**Comment by smillidge** [comment]
You could try manually editing the hazelcast.jar manifest file to export the non-visible package and see if that fixes your problem as a workaround.

**Comment by smillidge** [comment]
https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22fish.payara.maven.plugins%22

**Comment by Imadevops** [comment]
Thanks @smillidge . Your suggestion to export the non-visible package worked!  I will raise this on the Hazelcast GitHub
