### ISSUE TITLE
Client with gf-client.jar hangs up forever

### ISSUE THREAD

**Issue by angtes** [payara/Payara#1819]
I'm trying to run a simple java client that lookups a jdbc resource from the server.
In Glassfish 3, I run the client adding gf-client.jar to the classpath and runs ok.
In Payara 4 I've done the same. It runs, but hangs up when it finished and never end.

I've attached the java source of the client and the .class file.
[TestJNDI.zip](https://github.com/payara/Payara/files/1187188/TestJNDI.zip)

## Steps to reproduce

1.- Copy TestJNDI.class file to /var/tmp/test/TestJNDI.class
2.- export CLASSPATH=/var/tmp:/opt/payara41/glassfish/lib/gf-client.jar
3.- Start DAS (asadmin start-domain)
4.- Create a jdbc resource (jdbc/test). For the purpose of the test it's not necessary to create the resource. The client returns a NameNotFoundException and hangs up.
5.- java -Dorg.omg.CORBA.ORBInitialHost=127.0.0.1 -Dorg.omg.CORBA.ORBInitialPort=3700 test.TestJNDI

Output:
jul 31, 2017 9:51:33 AM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 5.1.2.Final
OK
END TEST

The client hangs up. The OS prompt never appears and I've to kill the java process.

## Environment ##
- **Payara Version**: 4.1.2.172
- **Edition**: Full
- **JDK Version**: 1.8.0_131 Oracle
- **Operating System**: CentOS 6.9

**Comment by roslaw-md** [comment]
We experienced the same problem when we upgraded from Payara 4.1.1_171 to 4.1.2_172, using a default InitialContext.

With Payara 4.1.1_171, the client application created daemon-threads like these:
`"p: default-threadpool; w: 2" #13 daemon prio=5 os_prio=0 tid=0x00007f052c010800 nid=0x2d5d in Object.wait() [0x00007f05506ef000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000000d7158ce0> (a com.sun.corba.ee.impl.threadpool.WorkQueueImpl)
        at com.sun.corba.ee.impl.threadpool.WorkQueueImpl.requestWork(WorkQueueImpl.java:124)
        - locked <0x00000000d7158ce0> (a com.sun.corba.ee.impl.threadpool.WorkQueueImpl)
        at com.sun.corba.ee.impl.threadpool.ThreadPoolImpl$WorkerThread.run(ThreadPoolImpl.java:518)
`

With Payara 4.1.2_172, non-daemon threads are created:
`"orb-default-threadpool (pool #1): worker-2" #13 prio=5 os_prio=0 tid=0x00007f3db0010800 nid=0x1a92 waiting on condition [0x00007f3df9572000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000d75ba978> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)`

Calling close() on the InitialContext doesn't terminate the non-daemon threads.

**Comment by lprimak** [comment]
Assigned Internal issue ```PAYARA-2014``` to track this
