### ISSUE TITLE
None bean discovery mode leads to UnsupportedOperationException

### ISSUE THREAD

**Issue by kvalev** [payara/Payara#1825]
# Description #
----------

We encountered the following exception after switching from Payara 161 to 172:
```
java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at org.glassfish.weld.DeploymentImpl.loadBeanDeploymentArchive(DeploymentImpl.java:443)
	at org.jboss.weld.util.DeploymentStructures.getOrCreateBeanDeployment(DeploymentStructures.java:37)
	at org.jboss.weld.bootstrap.ExtensionBeanDeployer.deployBean(ExtensionBeanDeployer.java:79)
	at org.jboss.weld.bootstrap.ExtensionBeanDeployer.deployBeans(ExtensionBeanDeployer.java:72)
	at org.jboss.weld.bootstrap.WeldStartup.startInitialization(WeldStartup.java:366)
	at org.jboss.weld.bootstrap.WeldBootstrap.startInitialization(WeldBootstrap.java:76)
	at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:222)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:329)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:497)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:487)
```

After some debugging it seems that the issue is caused by setting`bean-discovery-mode` is set to `none` in `beans.xml`; switching to `annotated` fixes the issue. The problem stems from the fact, that whenever bean discovery is disabled, [no bean deployment archives are added to the deployment](https://github.com/payara/Payara/blob/payara-server-4.1.2.172/appserver/web/weld-integration/src/main/java/org/glassfish/weld/DeploymentImpl.java#L726-L729). Subsequently in case of no bdas, [this method](https://github.com/payara/Payara/blob/payara-server-4.1.2.172/appserver/web/weld-integration/src/main/java/org/glassfish/weld/DeploymentImpl.java#L348-L351) returns a `Collections.emptyList`, which prohibits adding new elements, so loading the `WeldExtension` fails with the stacktrace above.

**Comment by fturizo** [comment]
@kvalev, do you have a sample reproducer for this scenario? We have tested EAR assemblies with CDI archive deployment disabled and they are working fine on release 4.1.2.172. It'd be good if you include a copy of your _beans.xml_ file inside this reproducer.

**Comment by kvalev** [comment]
I dont have a minimal sample project right now, but will try to provide one. For the time being here is the beans.xml file (fairly straightforward):

```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://xmlns.jcp.org/xml/ns/javaee"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:weld="http://jboss.org/schema/weld/beans" 
       xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/beans_1_1.xsd" 
       version="1.1" bean-discovery-mode="none">
</beans>
```

You mentioned EAR, however in our case we are deploying WAR archives.

**Comment by fturizo** [comment]
@kvalev, thanks for posting the CDI configuration file. It looks fine and indeed should work out like that. When you can try to provide the sample reproducer to see if we can provide further assistance. Also, the test that we did were with multimodule EAR assemblies with WAR artefacts inside, each one with their respective _beans.xml_ file.

**Comment by fturizo** [comment]
Any progress on the sample reproducer, @kvalev?

**Comment by lprimak** [comment]
This may be related to something I have done, but maybe not, I will take a look

**Comment by kvalev** [comment]
Sorry, I didnt have much time to work on that recently... I will give it another go in the next few days.

**Comment by lprimak** [comment]
Looks like this might be an issue, another user reported it
Duplicates #2112
