### ISSUE TITLE
Payara overwriting Hazelcast serialization XML configuration

### ISSUE THREAD

**Issue by scottg88** [payara/Payara#1872]
# Description #
----------

Payara appears to overwrite Serialization configuration in built-in Hazelcast.

## Expected Outcome

DataSerialization factories specified in hazelcast.xml configuration should flow through to the configuration used by built-in Hazelcast.

## Current Outcome

There are no configured factories in the running configuration of Hazelcast after startup.

## Steps to reproduce (Only for bug reports) 

Configure hazelcast.xml with:

```xml
<serialization>
  <data-serializable-factories>
    <data-serializable-factory factory-id="111">
      com.example.ExampleDataSerializableFactory
    </data-serializable-factory>
  </data-serializable-factories>
</serialization>
```

Bundle `com.example.ExampleDataSerializableFactory` with Payara Micro/place in Payara lib directory to ensure it's available during Hazelcast startup.

Attempt to pull a custom POJO requiring deserialization from a distributed object (e.g. queue). Receive error message indicating factory was not registered:

```
[2017-08-17T15:52:58.993+1000] [] [SEVERE] [] [com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl] [tid: _ThreadID=88 _ThreadName=hz._hzInstance_1_dev.event-4] [timeMillis: 1502949178993] [levelValue: 1000] [[
  [192.168.56.1]:5701 [dev] [3.8] hz._hzInstance_1_dev.event-4 caught an exception while processing task:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@1c02c7aa
com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: 111
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:134)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:103)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:49)
        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:184)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:106)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:75)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
        at com.hazelcast.collection.impl.queue.QueueProxySupport.invokeAndGet(QueueProxySupport.java:177)
        at com.hazelcast.collection.impl.queue.QueueProxySupport.pollInternal(QueueProxySupport.java:124)
        at com.hazelcast.collection.impl.queue.QueueProxyImpl.poll(QueueProxyImpl.java:88)
        at com.hazelcast.collection.impl.queue.QueueProxyImpl.poll(QueueProxyImpl.java:139)
        at com.example.QueueListener.processQueue(QueueListener.java:30)
        at com.example.QueueListener.itemAdded(QueueListener.java:21)
        at com.hazelcast.collection.impl.queue.QueueService.dispatchEvent(QueueService.java:225)
        at com.hazelcast.collection.impl.queue.QueueService.dispatchEvent(QueueService.java:75)
        at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:56)
        at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:221)
        at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:204)
```

Viewing running configuration of `HazelcastInstance` via debugging shows the factory is not registered.

### Samples

https://github.com/scottg88/payara1872

## Context (Optional)

It seems this might be related to this code:

https://github.com/payara/Payara/blob/0b66716db8b963a0e37784b3216e99ddf7a38246/nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java#L230

If a GlobalSerializer is not configured in the configuration this appears to be overwriting the whole configuration rather than adding the Payara serializer to the existing configuration.

Distributed objects are working fine with primitive types or POJOs implementing `Serializable`. This seems to be simply related to the configuration not passing through from the hazelcast.xml file.

I should be able to workaround this using a different serialization method for the time being but this prevents using non-Java Hazelcast clients which I need to account for.

## Environment ##

- **Payara Version**: 4.1.2.173
- **Edition**: Micro
- **JDK Version**: Oracle JDK 8
- **Operating System**: Windows
- **Database**: N/A

**Comment by lprimak** [comment]
Assigned internal issue ```PAYARA-1962``` to track this

**Comment by scottg88** [comment]
Please find an example project at:

https://github.com/scottg88/payara1872

**Comment by lprimak** [comment]
Please review #1915
Thanks
