### ISSUE TITLE
CDI container should be able to inject Cache

### ISSUE THREAD

**Issue by jerrinot** [payara/Payara#188]
currently the JCache CDI extension can inject CacheProvider and CacheManager. It mean a user still has to get a cache programmatically. I'd like to use:
```java
    @Inject
    private Cache<String, Integer> cache2;
```

Currently it throws an exception during application deployment:
```
[2015-01-30T21:08:51.381+0000] [Payara 4.1] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=44 _ThreadName=admin-listener(5)] [timeMillis: 1422652131381] [levelValue: 1000] [[
  Exception while loading the app : CDI deployment failure:WELD-001408: Unsatisfied dependencies for type Cache<String, Integer> with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private info.jerrinot.demo.websession.CdiServlet.cache2
  at info.jerrinot.demo.websession.CdiServlet.cache2(CdiServlet.java:0)

org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type Cache<String, Integer> with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private info.jerrinot.demo.websession.CdiServlet.cache2
  at info.jerrinot.demo.websession.CdiServlet.cache2(CdiServlet.java:0)

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:371)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:293)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:134)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:167)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:530)
	at org.jboss.weld.bootstrap.Validator.validateBeans(Validator.java:516)
	at org.jboss.weld.bootstrap.Validator.validateDeployment(Validator.java:491)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:437)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)
	at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:225)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:328)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:496)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:219)
	at org.glassfish.deployment.admin.InstanceDeployCommand.execute(InstanceDeployCommand.java:213)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
[...]
```

**Comment by smillidge** [comment]
We didn't have time to do this as it needs a little more thought.

For example what is the semantics of 
@Inject
    private Cache<String, Integer> cache1;

@Inject
    private Cache<String, Integer> cache2;

Does it inject the same cache or a different cache? 
What is the name of the injected cache?
Also it would be good to be able to inject a Named Cache explicitly.

**Comment by smillidge** [comment]
What do you think the default name should be when a user doesn't specify one. I've got working code for;
```java
@NamedCache(value="MyCache")
@Inject
private Cache cache;
```

What will be the name for;
```java
@Inject
private Cache cache;
```

JSR107 spec CacheMethodDetails Annotation used by interceptors uses a cache name fully qualified class name + . + method name + all parameters.

So I was thinking a raw class injection should use the fully qualified class name as the cache name?

Thoughts?

**Comment by Quix0r** [comment]
`@NamedCache` is Payara-specific. Is there any portable way available? I like to to get rid of the *annotation*, not Payara to have it (my WAR project) fully portable (also runs the same way on any web container.
