### ISSUE TITLE
Problem creating connection-pool from --postbootcommandfile

### ISSUE THREAD

**Issue by pblew** [payara/Payara#1910]
# Description #
----------

When using `--postbootcommandfile` I am unable to create a `jdbc-connection-pool` using a file containing:

```
create-jdbc-connection-pool --datasourceclassname=org.apache.derby.jdbc.ClientDataSource --restype=javax.sql.DataSource --property=ServerName=db:port=1527:DatabaseName=MyDB:user=aUser:password=aP@ssw0rd:connectionAttributes=\;create\\=true my-pool
```

The same file works using `./asadmin multimode --file asadmin.txt`

## Expected Outcome

The `jdbc-connection-pool` should be created with the attributes specified

## Current Outcome

```
[#|2017-08-30T13:54:47.325+0100|INFO|Payara 4.1||_ThreadID=1;_ThreadName=main;_TimeMillis=1504097687325;_LevelValue=800;|
  Reading in commandments from /home/pblew/IdeaProjects/asadmin.txt|#]

[#|2017-08-30T13:54:47.327+0100|INFO|Payara 4.1||_ThreadID=1;_ThreadName=main;_TimeMillis=1504097687327;_LevelValue=800;|
  Running command: create-jdbc-connection-pool --datasourceclassname=org.apache.derby.jdbc.ClientDataSource --restype=javax.sql.DataSource --property=ServerName=db:port=1527:DatabaseName=MyDB:user=aUser:password=aP@ssw0rd:connectionAttributes=\;create\\=true my-pool|#]

[#|2017-08-30T13:54:47.367+0100|SEVERE|Payara 4.1|javax.enterprise.system.core|_ThreadID=1;_ThreadName=main;_TimeMillis=1504097687367;_LevelValue=1000;_MessageID=NCLS-CORE-00003;|
  Exception while running a command
java.util.regex.PatternSyntaxException: Illegal repetition near index 1
\${.+}
 ^
	at java.util.regex.Pattern.error(Pattern.java:1955)
	at java.util.regex.Pattern.closure(Pattern.java:3157)
	at java.util.regex.Pattern.sequence(Pattern.java:2134)
	at java.util.regex.Pattern.expr(Pattern.java:1996)
	at java.util.regex.Pattern.compile(Pattern.java:1696)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at java.lang.String.replaceAll(String.java:2223)
	at org.glassfish.common.util.admin.MapInjectionResolver.convertStringToProperties(MapInjectionResolver.java:525)
	at org.glassfish.common.util.admin.MapInjectionResolver.convertStringToObject(MapInjectionResolver.java:376)
	at org.glassfish.common.util.admin.MapInjectionResolver.getValue(MapInjectionResolver.java:180)
	at org.jvnet.hk2.config.InjectionManager.syncDoInject(InjectionManager.java:169)
	at org.jvnet.hk2.config.InjectionManager.inject(InjectionManager.java:74)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.injectParameters(CommandRunnerImpl.java:373)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1229)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1851)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1727)
	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:169)
	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:94)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.runCommand(GlassFishMain.java:231)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.doBootCommands(GlassFishMain.java:269)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:102)
	at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:54)
|#]

[#|2017-08-30T13:54:47.372+0100|INFO|Payara 4.1||_ThreadID=1;_ThreadName=main;_TimeMillis=1504097687372;_LevelValue=800;|
  PlainTextActionReporterFAILUREjava.util.regex.PatternSyntaxException: Illegal repetition near index 1
\${.+}
 ^Description: create-jdbc-connection-pool commandIllegal repetition near index 1
\${.+}
 ^
    Usage: create-jdbc-connection-pool [--datasourceclassname=datasourceclassname] [--restype=restype] [--steadypoolsize=8] [--maxpoolsize=32] [--maxwait=60000] [--poolresize=2] [--idletimeout=300] [--initsql=initsql] [--isolationlevel=isolationlevel] [--isisolationguaranteed=true] [--isconnectvalidatereq=false] [--validationmethod=table] [--validationtable=validationtable] [--failconnection=false] [--allownoncomponentcallers=false] [--nontransactionalconnections=false] [--validateatmostonceperiod=0] [--leaktimeout=0] [--leakreclaim=false] [--creationretryattempts=0] [--creationretryinterval=10] [--sqltracelisteners=fish.payara.jdbc.SilentSqlTraceListener] [--statementtimeout=-1] [--statementleaktimeout=0] [--statementleakreclaim=false] [--lazyconnectionenlistment=false] [--lazyconnectionassociation=false] [--associatewiththread=false] [--driverclassname=driverclassname] [--matchconnections=false] [--maxconnectionusagecount=0] [--ping=false] [--pooling=true] [--statementcachesize=0] [--validationclassname=validationclassname] [--wrapjdbcobjects=true] [--description=description] [--property=property] jdbc_connection_pool_id 
|#]

[#|2017-08-30T13:54:47.373+0100|SEVERE|Payara 4.1||_ThreadID=1;_ThreadName=main;_TimeMillis=1504097687373;_LevelValue=1000;|
  java.util.regex.PatternSyntaxException: Illegal repetition near index 1
\${.+}
 ^
	at java.util.regex.Pattern.error(Pattern.java:1955)
	at java.util.regex.Pattern.closure(Pattern.java:3157)
	at java.util.regex.Pattern.sequence(Pattern.java:2134)
	at java.util.regex.Pattern.expr(Pattern.java:1996)
	at java.util.regex.Pattern.compile(Pattern.java:1696)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at java.lang.String.replaceAll(String.java:2223)
	at org.glassfish.common.util.admin.MapInjectionResolver.convertStringToProperties(MapInjectionResolver.java:525)
	at org.glassfish.common.util.admin.MapInjectionResolver.convertStringToObject(MapInjectionResolver.java:376)
	at org.glassfish.common.util.admin.MapInjectionResolver.getValue(MapInjectionResolver.java:180)
	at org.jvnet.hk2.config.InjectionManager.syncDoInject(InjectionManager.java:169)
	at org.jvnet.hk2.config.InjectionManager.inject(InjectionManager.java:74)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.injectParameters(CommandRunnerImpl.java:373)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1229)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1851)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1727)
	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:169)
	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:94)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.runCommand(GlassFishMain.java:231)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.doBootCommands(GlassFishMain.java:269)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:102)
	at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:54)
|#]
```

## Steps to reproduce (Only for bug reports) 

1. Create `asadmin.txt` containing:
    ```
    create-jdbc-connection-pool --datasourceclassname=org.apache.derby.jdbc.ClientDataSource --restype=javax.sql.DataSource --property=ServerName=db:port=1527:DatabaseName=MyDB:user=aUser:password=aP@ssw0rd:connectionAttributes=\;create\\=true my-pool
    ```
2. Attempt to start the domain:
    ```
    ./asadmin start-domain --verbose --postbootcommandfile asadmin.txt payaradomain
    ```

## Environment ##

- **Payara Version**: 4.1.2.173
- **Edition**: Full
- **JDK Version**: 8u141 - OpenJDK 
- **Operating System**: Linux
- **Database**: Derby

**Comment by pblew** [comment]
The stack trace indicates a problem with the regex parameter in [MapInjectionResolver at line 525](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fpayara%2FPayara%2Fblob%2F3535066cef25ec5f2b27e62dffe4986f81fb6201%2Fnucleus%2Fcommon%2Fcommon-util%2Fsrc%2Fmain%2Fjava%2Forg%2Fglassfish%2Fcommon%2Futil%2Fadmin%2FMapInjectionResolver.java%23L525&sa=D&sntz=1&usg=AFQjCNEcLOWJznko1C5DS4WaYSxAR68t2A) - it looks like the `{` has not been escaped when it should be.  This can be quickly proven running line 525 in isolation using:

```java
public class TestIt {
    public static void main(String[] args) {
        String secPart = "ServerName=db:port=1527:DatabaseName=MyDB:user=aUser:password=aP@ssw0rd:connectionAttributes=\\;create\\\\=true";
        try {
            String outside = secPart.replaceAll("\\${.+}", "");
            System.out.println(outside);
        } catch (Exception e) {
            System.err.println("This fails as expected:\n" + e);
        }
        try {
            String outside = secPart.replaceAll("\\$\\{.+}", "");
            System.out.println(outside);
        } catch (Exception e) {
            System.err.println("This won't happen:\n" + e);
        }
    }
}
```

**Comment by MattGill98** [comment]
Hi Paul,

Thanks for the reproducer as well as looking through the source! You're absolutely right, the brackets don't seem to be getting escaped. I've created internal issue PAYARA-2034 to address this bug.

As a temporary fix, changing `connectionAttributes=\;create\\=true` to `connectionAttributes=\;create\=true` seems to work for me.

Hope this helps.

Kind regards,

Matt

**Comment by pblew** [comment]
Thanks Matt.

I had meant to get a pull request submitted (regex fixed + unit test) over the weekend, but time just ran away from me.

I've attached it to this comment as a zipped patch ([issue-1910.zip](https://github.com/payara/Payara/files/1274635/issue-1910.zip)) in case it is of any use.

Warm regards,
Paul

**Comment by MattGill98** [comment]
Hi Paul,

That's fantastic! You're welcome to make a PR for that fix if you want to, which will mean you get credited with the solution! You'll just need to sign a CLA; you can find more information on this from: http://blog.payara.fish/how-to-contribute-to-payara-server.

Kind regards,

Matt

**Comment by pblew** [comment]
I'll try and get it done this weekend
