### ISSUE TITLE
Payara micro does not replace environment/system variables in descriptor file

### ISSUE THREAD

**Issue by fstorz** [payara/Payara#1935]
# Description #
----------

Payara micro does not replace environment/system variables in descriptor file persistence.xml correctly when using EclipseLink's NoSQL feature. To use the docker image based on payara/micro in all stages (e.g. dev, int, prod) with different config it would be great to have this working.
The [documentation](https://payara.gitbooks.io/payara-server/documentation/core-documentation/configuration/var-substitution/usage-of-variables.html) says 
```
Variable references can be used inside text values also in the following places within deployed applications and modules:
...
Framework descriptors:
persistence.xml
```

Current configuration in a simple jee-web-app.
```xml
<persistence version="2.1" xmlns="http://xmlns.jcp.org/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence http://xmlns.jcp.org/xml/ns/persistence/persistence_2_1.xsd">
	<persistence-unit name="mongo" transaction-type="JTA">
        <class>com.example.ExampleModel</class>
        <properties>
            <property name="eclipselink.target-database" value="org.eclipse.persistence.nosql.adapters.mongo.MongoPlatform"/>
            <property name="eclipselink.nosql.connection-spec" value="org.eclipse.persistence.nosql.adapters.mongo.MongoConnectionSpec"/>
            <property name="eclipselink.nosql.property.mongo.port" value="${mongo.port}"/>
            <property name="eclipselink.nosql.property.mongo.host" value="${mongo.host}"/>
            <property name="eclipselink.nosql.property.mongo.db" value="${ENV=DB_NAME}"/>
            <property name="eclipselink.logging.level" value="FINEST"/>
        </properties>
    </persistence-unit>
</persistence>
```

## Expected Outcome

Variables are replaced also in properties and mongo database connection is successful.

## Current Outcome

```
[2017-09-04T12:50:05.394+0200] [] [FINE] [] [org.eclipse.persistence.session./file:/C:/WINDOWS/TEMP/payaramicro-rt3295860088960591661tmp/applications/mongo/WEB-INF/classes/_mongo.server] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1504522205394] [levelValue: 500] Configured server platform: org.eclipse.persistence.platform.server.glassfish.GlassfishPlatform

[2017-09-04T12:50:05.587+0200] [] [CONFIG] [] [org.eclipse.persistence.session./file:/C:/WINDOWS/TEMP/payaramicro-rt3295860088960591661tmp/applications/mongo/WEB-INF/classes/_mongo.metadata] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1504522205587] [levelValue: 700] The access type for the persistent class [class com.exmaple.ExampleModel] is set to [FIELD].

[2017-09-04T12:50:05.652+0200] [] [CONFIG] [] [org.eclipse.persistence.session./file:/C:/WINDOWS/TEMP/payaramicro-rt3295860088960591661tmp/applications/mongo/WEB-INF/classes/_mongo.metadata] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1504522205652] [levelValue: 700] The alias name for the entity class [class com.exmaple.ExampleModel] is being defaulted to: ExampleModel.

[2017-09-04T12:50:05.688+0200] [] [CONFIG] [] [org.eclipse.persistence.session./file:/C:/WINDOWS/TEMP/payaramicro-rt3295860088960591661tmp/applications/mongo/WEB-INF/classes/_mongo.metadata] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1504522205688] [levelValue: 700] The column name for element [address] is being defaulted to: ADDRESS.

[2017-09-04T12:50:05.703+0200] [] [CONFIG] [] [org.eclipse.persistence.session./file:/C:/WINDOWS/TEMP/payaramicro-rt3295860088960591661tmp/applications/mongo/WEB-INF/classes/_mongo.metadata] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1504522205703] [levelValue: 700] The column name for element [importance] is being defaulted to: IMPORTANCE.

[2017-09-04T12:50:05.717+0200] [] [CONFIG] [] [org.eclipse.persistence.session./file:/C:/WINDOWS/TEMP/payaramicro-rt3295860088960591661tmp/applications/mongo/WEB-INF/classes/_mongo.metadata] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1504522205717] [levelValue: 700] The column name for element [name] is being defaulted to: NAME.

[2017-09-04T12:50:05.756+0200] [] [CONFIG] [] [org.eclipse.persistence.session./file:/C:/WINDOWS/TEMP/payaramicro-rt3295860088960591661tmp/applications/mongo/WEB-INF/classes/_mongo.metadata] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1504522205756] [levelValue: 700] The column name for element [version] is being defaulted to: VERSION.

[2017-09-04T12:50:05.978+0200] [] [INFO] [] [org.eclipse.persistence.session./file:/C:/WINDOWS/TEMP/payaramicro-rt3295860088960591661tmp/applications/mongo/WEB-INF/classes/_mongo] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1504522205978] [levelValue: 800] EclipseLink, version: Eclipse Persistence Services - 2.6.4.qualifier

[2017-09-04T12:50:05.990+0200] [] [CONFIG] [] [org.eclipse.persistence.session./file:/C:/WINDOWS/TEMP/payaramicro-rt3295860088960591661tmp/applications/mongo/WEB-INF/classes/_mongo.connection] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1504522205990] [levelValue: 700] [[
  connecting(EISLogin(
        platform=> MongoPlatform
        user name=> ""
        MongoConnectionSpec()
))]]

[2017-09-04T12:50:06.014+0200] [] [SEVERE] [] [org.eclipse.persistence.session./file:/C:/WINDOWS/TEMP/payaramicro-rt3295860088960591661tmp/applications/mongo/WEB-INF/classes/_mongo] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1504522206014] [levelValue: 1000] [[

java.lang.NumberFormatException: For input string: "${mongo.port}"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:569)
        at java.lang.Integer.<init>(Integer.java:867)
        at org.eclipse.persistence.nosql.adapters.mongo.MongoConnectionSpec.connectToDataSource(MongoConnectionSpec.java:73)
        at org.eclipse.persistence.eis.EISLogin.connectToDatasource(EISLogin.java:73)
        at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.connectInternal(DatasourceAccessor.java:346)
        at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.connect(DatasourceAccessor.java:434)
        at org.eclipse.persistence.sessions.server.ConnectionPool.buildConnection(ConnectionPool.java:217)
        at org.eclipse.persistence.sessions.server.ConnectionPool.startUp(ConnectionPool.java:505)
        at org.eclipse.persistence.sessions.server.ServerSession.connect(ServerSession.java:488)
        at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.login(DatabaseSessionImpl.java:774)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:267)
        at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:731)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:205)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:305)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:337)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:303)
        at org.glassfish.persistence.jpa.JPADeployer$2.visitPUD(JPADeployer.java:461)
        at org.glassfish.persistence.jpa.JPADeployer$PersistenceUnitDescriptorIterator.iteratePUDs(JPADeployer.java:520)
        at org.glassfish.persistence.jpa.JPADeployer.iterateInitializedPUsAtApplicationPrepare(JPADeployer.java:502)
        at org.glassfish.persistence.jpa.JPADeployer.event(JPADeployer.java:408)
        at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:488)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:488)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:544)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:540)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:539)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:570)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:562)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:561)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1469)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1851)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1727)
        at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:134)
        at fish.payara.micro.impl.PayaraMicroImpl.deployAll(PayaraMicroImpl.java:1396)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:993)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:186)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:79)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:361)
]]
```

## Environment ##

- **Payara Version**: 4.1.2.173
- **Edition**: Micro
- **JDK Version**: openjdk:8u131-jdk-alpine
- **Operating System**: Linux

**Comment by MattGill98** [comment]
Hi @fstorz,

It does seem that environment variables aren't being substituted in the persistence.xml file. I've raised internal issue PAYARA-2037 to address this issue.

In the meantime, I'd suggest taking a look at the command `--systemProperties` for Payara Micro. It allows you to pass a file containing system properties.

Hope this helps,

Matt

**Comment by fstorz** [comment]
Hi @MattGill98,

thx for your help.

I use a post boot script using --postbootcommandfile to execute the _create-system-properties_ command. I hope this is an equivalent to your suggestion.

Greetings,
Florian

**Comment by MattGill98** [comment]
Yes this should do a similar thing.

Best regards,

Matt

**Comment by gjelenc** [comment]
Also in @DataSourceDefinition environment variables aren't being substituted if I use ${ENV=mysql_url}.

**Comment by smillidge** [comment]
Can you paste the annotation you are using?

**Comment by gjelenc** [comment]
@DataSourceDefinition(name="java:global/DSFProject",
        className="com.mysql.jdbc.jdbc2.optional.MysqlConnectionPoolDataSource",
        user="${ENV=mysql_user}",
        password="${ENV=mysql_pass}",
        databaseName="${ENV=mysql_dbname}",
        serverName="${ENV=mysql_url}",
        portNumber=3306,
        initialPoolSize = 8,
        minPoolSize = 8,
        maxPoolSize = 32,
        properties = {  "ZeroDateTimeBehavior=convertToNull",
                        "characterEncoding=UTF-8",
                        "characterSetResults=UTF-8",
                        "autoReconnect=true",
                        "useSSL=false" }
)
public class DataSourceConfiguration {
}

**Comment by MattGill98** [comment]
Hi Gregor,

Substitution seems to work for me in the annotations. What's the error you're getting? Also, make sure you're running `export name=value` for each variable before you run Payara Micro.

Let me know if you have any problems,

Matt

**Comment by aosama** [comment]
is this feature of environment variable replacement supported in Payara Web Profile?

**Comment by aosama** [comment]
just tried annotation based definition with environment variables on PAYARA web profile  5.181 and it work fine
