### ISSUE TITLE
payara 4.1.1.171 :: eclipselink issue with case when condition

### ISSUE THREAD

**Issue by vikramalvaj** [payara/Payara#1941]
# Description #
Query with constructor query, CASE and boolean literals causes IllegalArgumentException

With case and when condition observing illegal argument exception. EclipseLink bug id https://bugs.eclipse.org/bugs/show_bug.cgi?id=462663

## Expected Outcome

it should work as working in earlier version of glassfish 3

## Current Outcome

it throws the below error log
_Caused by: java.lang.IllegalArgumentException: argument type mismatch
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.eclipse.persistence.internal.security.PrivilegedAccessHelper.invokeConstructor(PrivilegedAccessHelper.java:471)
        at org.eclipse.persistence.queries.ReportQueryResult.buildResult(ReportQueryResult.java:122)
        at org.eclipse.persistence.queries.ReportQueryResult.<init>(ReportQueryResult.java:79)
        at org.eclipse.persistence.queries.ReportQuery.buildObject(ReportQuery.java:598)
        at org.eclipse.persistence.queries.ReportQuery.buildObjects(ReportQuery.java:649)
        at org.eclipse.persistence.queries.ReportQuery.executeDatabaseQuery(ReportQuery.java:852)
        at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:904)
        at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1134)
        at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:460)
        at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1222)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1857)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1839)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1804)
        at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:258)
        at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:473)_

## Steps to reproduce (Only for bug reports) 
JPA named query with CASE and name condition

## Environment ##

- **Payara Version**: 4.1.1.171
- **Edition**: 
- **JDK Version**:  1.7/1.8
- **Operating System**: Windows / Linux
- **Database**: informix

**Comment by MattGill98** [comment]
Hi @vikramalvaj,

This does seem to be a problem with EclipseLink. Unfortunately since it's not an issue with Payara, the best I can do is suggest that you raise the problem with EclipseLink directly again. In the meantime, the workaround would be casting to a boolean when fetching the result.

Kind regards,

Matt

**Comment by fturizo** [comment]
Closing this issue since a workaround has been provided.
