### ISSUE TITLE
Returned ClassCastException: Object is not of remote type java.rmi.Remote

### ISSUE THREAD

**Issue by Quix0r** [payara/Payara#1955]
# Description #
----------

The said exception (compare to #1035) has returned again. It happens randomly and only annotations are used to lookup EJBs, like `@EJB(lookup="java:global/project-ejb/contact!org.example.foo.model.FooSessionBeanRemote)` The interface is annotated with the usual `@javax.ejb.Remote` and does not extend `java.rmi.Remote` but only the usual `java.io.Serializable`.

## Expected Outcome

The application should work uninterrupted, such exception may indicate (according to my JavaEE trainer a "confusion" within the Glassfish/Payara instance.

## Current Outcome

The said exception happens randomly.

## Steps to reproduce (Only for bug reports) 

1) Write a "complex" web application with the usual annotations, do not do JNDI lookup in constructors or `@PostConstruct` annotated methods as has caused in #1035 the bug and is now replaced with `@EJB (lookup="bla bla bla")`.
2) Try to re-deploy the application and much as possible while you develop it.
3) Try to click on some links, do some actions (triggering action methods)
4) In short: do the usual stuff you do on development.

### Samples

- Exception log file: https://cloud.mxchange.org/index.php/s/149vSQYmDeENiuY/download?path=%2FPayara&files=20170910%20-%20class-cast-exception.log
- More being added

## Environment ##

- **Payara Version**: 4.1.2.173
- **Edition**: Full
- **JDK Version**: openjdk version "1.8.0_141"
- **Operating System**: Debian Linux
- **Database**: MariaDB

**Comment by lprimak** [comment]
@Quix0r Sorry, but unfortunately we cannot help you further without a reproducer.
I spent countless hours trying to reproduce this, and the answers in #1035 is the only thing I could come up with.

However, if you are able to provide a reproducer, feel free to reopen #1035.
- According to http://sscce.org

Alternatively, if you have an appropriate support contract and able to provide us full access to the environment where you can consistently reproduce the problem (including source code etc) we can have another look.

**Comment by Quix0r** [comment]
I cannot reopen it because @mikecroft has locked it. So I opened another one and this one is slightly different as no `@PostConstruct` will do any JNDI lookup (thank you, it really helped already a lot).

Sorry for being a bit persistent but I would like to help out, making Payara better.

**Comment by lprimak** [comment]
Can you please test it and make sure it works.
I cannot really spend any more time on this unless I am sure it's reproducible on my end.
Thank you!

**Comment by Quix0r** [comment]
When I try to deploy the EAR project, I get missing dependency:

````
[2017-09-14T20:37:22.664+0200] [Payara 4.1] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=210 _ThreadName=admin-thread-pool::admin-listener(8)] [timeMillis: 1505414242664] [levelValue: 1000] [[
  Exception while preparing the app : Could not resolve a persistence unit corresponding to the persistence-context-ref-name [org.mxchange.jcoreee.database.BaseDatabaseBean/entityManager] in the scope of the module called [jfinancials#jcore-logger-ejb.jar]. Please verify your application.
java.lang.RuntimeException: Could not resolve a persistence unit corresponding to the persistence-context-ref-name [org.mxchange.jcoreee.database.BaseDatabaseBean/entityManager] in the scope of the module called [jfinancials#jcore-logger-ejb.jar]. Please verify your application.
        at com.sun.enterprise.deployment.BundleDescriptor.findReferencedPUViaEMRef(BundleDescriptor.java:733)
        at org.glassfish.ejb.deployment.descriptor.EjbBundleDescriptorImpl.findReferencedPUs(EjbBundleDescriptorImpl.java:889)
        at org.glassfish.persistence.jpa.JPADeployer.createEMFs(JPADeployer.java:188)
        at org.glassfish.persistence.jpa.JPADeployer.prepare(JPADeployer.java:170)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.prepareModule(ApplicationLifecycle.java:926)
        at org.glassfish.javaee.full.deployment.EarDeployer.prepareBundle(EarDeployer.java:309)
        at org.glassfish.javaee.full.deployment.EarDeployer.access$200(EarDeployer.java:88)
        at org.glassfish.javaee.full.deployment.EarDeployer$1.doBundle(EarDeployer.java:155)
        at org.glassfish.javaee.full.deployment.EarDeployer$1.doBundle(EarDeployer.java:152)
        at org.glassfish.javaee.full.deployment.EarDeployer.doOnBundles(EarDeployer.java:232)
        at org.glassfish.javaee.full.deployment.EarDeployer.doOnAllTypedBundles(EarDeployer.java:241)
        at org.glassfish.javaee.full.deployment.EarDeployer.doOnAllBundles(EarDeployer.java:267)
        at org.glassfish.javaee.full.deployment.EarDeployer.prepare(EarDeployer.java:152)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.prepareModule(ApplicationLifecycle.java:926)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:435)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:488)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:544)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:540)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:539)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:570)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:562)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:561)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1469)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1851)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1727)
        at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:263)
        at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:234)
        at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:285)
        at org.glassfish.admin.rest.resources.TemplateListOfResource.createResource(TemplateListOfResource.java:136)
        at sun.reflect.GeneratedMethodAccessor1725.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384)
        at org.glassfish.admin.rest.adapter.RestAdapter$2.service(RestAdapter.java:316)
        at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:179)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:480)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:180)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
        at java.lang.Thread.run(Thread.java:748)
````
That however does not happen with each project deployed separately.

**Comment by Quix0r** [comment]
And then you may not encounter it immediately as it happens randomly and after some time.

**Comment by lprimak** [comment]
Please take a look again here:
https://github.com/payara/Payara/issues/1955#issuecomment-328372105

I cannot do anything without a reliable reproducer according to http://sscce.org
Without a support contract, we cannot do what will amount to debugging your application.

- You can try Payara 5 as deployment there has been reworked for a little bit
- Try packaging your application into a single EAR file

**Comment by Quix0r** [comment]
I write it again:
- this and some other projects are (A)GPLv3 licensed software and will be for **non-profit**.
- I do not wish to pay support for a 3rd-party app when I develop GPL'ed software as I don't make any profit with it, not even support.
- Sure, I cannot support all revisions, only `HEAD` in `master` or latest stable, if available, will be supported.
- Again, this is for **non-profit**, _not_ profit! I do it in my *spare-time*.
- I will release the source code soon on my GIT repository at https://git.mxchange.org so don't worry that you don't see it there, it is just unreleased but is there.

So I may have to look around for an alternative, like WildFly is ...

**Comment by mikecroft** [comment]
Hi @Quix0r - I appreciate that this is a non-profit application for you, and we're very happy you chose to use Payara Server for your project. We always do our best to support the community where we can, with a regular release cycle, fixing bugs here on GitHub or answering questions on our forum or StackOverflow.

Unfortunately, we are limited in the amount of time we can dedicate to work for the community. We do not have the kind of resources that, for example, Red Hat may have. We are, as @lprimak has said, happy to help you with your issue, provided you can supply a [reliable reproducer](http://sscce.org).

Since we must always prioritise work for our paying customers, with whom we have signed contracts, the amount of time left to work on issues which only affect a single community user is small. As @lprimak has already said, much time has already been spent on this and we cannot reproduce it. The vast majority of issues which we successfully resolve here on GitHub have straightforward reproduction steps or the user will supply an application to recreate the problem.

The current status here, from our perspective, is that there is an issue which only affects a single user, which we cannot independently reproduce. Our only conclusion at this stage is that the error is not in Payara Server (though, again, a reliable reproducer would help us see otherwise). I'm sorry that we can't justify spending any more effort in trying to reproduce this ourselves but please let us know if you make any progress yourself.

**Comment by Quix0r** [comment]
Can you at least give me hint, from where this is caused? EJB project or WAR project? For the second backtrace, I may have an idea, I still had same JARs in `~/personal_domain/lib/`. Will clean that up when I'm home.

**Comment by smillidge** [comment]
The problem is a ClassCastException can have many causes. 

The most likely is a classloader leak in the application and as your reproducer instructions include redeployment this is likely. A ClassCastException can be thrown when the object is of the class specified but the class is loaded from a different class loader than currently loaded the class i.e. an old classloader. 
Classloader leaks need to be tracked down via heap dumps before and after undeployment of the application and look for instances of old classloaders and determine which objects have referenced them.

Classloader leaks are pretty difficult to track down in the application as they can be caused by many incorrect programming techniques; spawning threads either directly, using java.util.Timer or via other 3rd party libraries; pushing ejb stubs into sessions; use of Threadlocals anything that is not correctly cleaned down by the application developer during a redeployment. 

If you application works correctly on initial deployment but fails after redeployment I would suspect a classloader leak.

**Comment by Quix0r** [comment]
Thank you for the explanation. Yes, such exceptions are hard to track why they occur.

Sorry to ask but what do you mean with my "reproducer"?

Can I somehow track it for you?

**Comment by lprimak** [comment]
Please follow the steps here, and that is what we mean by Reproducer: 
http://sscce.org/
