### ISSUE TITLE
Not working with Java 9 

### ISSUE THREAD

**Issue by scrmtrey91** [payara/Payara#2030]
Latest payara avaliable for download as zip (4.1.2.173) not working with official java 9 version.

Error description:
```
C:\Users\Tadej\payara\glassfish\bin\asadmin.bat start-domain --debug payaradomain
Exception in thread "main" java.lang.NullPointerException
	at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.initializeServiceLocator(AbstractModulesRegistryImpl.java:152)
	at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.newServiceLocator(AbstractModulesRegistryImpl.java:144)
	at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.createServiceLocator(AbstractModulesRegistryImpl.java:218)
	at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.createServiceLocator(AbstractModulesRegistryImpl.java:224)
	at com.sun.enterprise.module.single.StaticModulesRegistry.createServiceLocator(StaticModulesRegistry.java:88)
	at com.sun.enterprise.admin.cli.CLIContainer.getServiceLocator(CLIContainer.java:216)
	at com.sun.enterprise.admin.cli.CLIContainer.getLocalCommand(CLIContainer.java:254)
	at com.sun.enterprise.admin.cli.CLICommand.getCommand(CLICommand.java:231)
	at com.sun.enterprise.admin.cli.AdminMain.executeCommand(AdminMain.java:370)
	at com.sun.enterprise.admin.cli.AdminMain.doMain(AdminMain.java:305)
	at org.glassfish.admin.cli.AsadminMain.main(AsadminMain.java:56)
```

**Comment by arjantijms** [comment]
Latest version of Payara 5 alpha has an outstanding PR that makes it to some degree compatible with JDK.

**Comment by smillidge** [comment]
Payara 4 is not targeted currently for Java 9 support. Payara 5 will have Java 9 support at some point. JDK 9 is not an LTS Java release.
