### ISSUE TITLE
java.lang.NoSuchMethodException: org.eclipse.persistence.platform.server.glassfish.GlassfishPlatform.<init>

### ISSUE THREAD

**Issue by chilliwebs** [payara/Payara#2067]
# Description #
----------

I recently upgraded our payara server from:
Payara Server 4.1.1.162 #badassfish (build 116)
to:
Payara Server 4.1.2.173 #badassfish (build 24)

I deployed and application that successfully deployed on a previous version and I'm now getting an exception:

Exception Description: Predeployment of PersistenceUnit [Default] failed.
Internal Exception: Exception [EclipseLink-28007] (Eclipse Persistence Services - 2.6.4.qualifier): org.eclipse.persistence.exceptions.EntityManagerSetupException
Exception Description: Failed to instantiate ServerPlatform of type [org.eclipse.persistence.platform.server.glassfish.GlassfishPlatform] specified in [eclipselink.target-server] property.
Internal Exception: java.lang.NoSuchMethodException: org.eclipse.persistence.platform.server.glassfish.GlassfishPlatform.<init>(org.eclipse.persistence.sessions.DatabaseSession)

## Expected Outcome

[2017-10-09T09:35:34.334-0400] [Payara 4.1] [INFO] [NCLS-DEPLOYMENT-02027] [javax.enterprise.system.tools.deployment.autodeploy] [tid: _ThreadID=214 _ThreadName=AutoDeployer] [timeMillis: 1507556134334] [levelValue: 800] [[
  Selecting file C:\payara41\glassfish\domains\domain1\autodeploy\SUISModulesEar.ear for autodeployment]]

[2017-10-09T09:35:41.521-0400] [Payara 4.1] [INFO] [] [javax.enterprise.system.container.ejb.com.sun.ejb.containers] [tid: _ThreadID=214 _ThreadName=AutoDeployer] [timeMillis: 1507556141521] [levelValue: 800] [[
  [2] timers deleted for id: 98776975897788416]]

[2017-10-09T09:35:41.615-0400] [Payara 4.1] [INFO] [] [javax.enterprise.system.container.ejb.com.sun.ejb.containers] [tid: _ThreadID=214 _ThreadName=AutoDeployer] [timeMillis: 1507556141615] [levelValue: 800] [[
  No timers to be deleted for id: 98776975897788416]]

...

[2017-10-09T09:35:41.693-0400] [Payara 4.1] [INFO] [] [javax.enterprise.system.container.ejb.com.sun.ejb.containers] [tid: _ThreadID=214 _ThreadName=AutoDeployer] [timeMillis: 1507556141693] [levelValue: 800] [[
  No timers to be deleted for id: 98776975897788416]]

[2017-10-09T09:35:50.084-0400] [Payara 4.1] [INFO] [] [javax.enterprise.system.core] [tid: _ThreadID=214 _ThreadName=AutoDeployer] [timeMillis: 1507556150084] [levelValue: 800] [[
  PostUndeployCommand starting]]

[2017-10-09T09:35:50.084-0400] [Payara 4.1] [INFO] [] [javax.enterprise.system.core] [tid: _ThreadID=214 _ThreadName=AutoDeployer] [timeMillis: 1507556150084] [levelValue: 800] [[
  PostUndeployCommand done successfully]]

...
...
...

[2017-10-09T09:36:50.945-0400] [Payara 4.1] [INFO] [] [com.dmainc.suis.service.impl.StartupService] [tid: _ThreadID=117 _ThreadName=p: thread-pool-1; w: 1] [timeMillis: 1507556210945] [levelValue: 800] [[
  Initializer Finished.]]

## Current Outcome

[2017-10-11T15:33:33.857-0400] [Payara 4.1] [SEVERE] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=197 _ThreadName=AutoDeployer] [timeMillis: 1507750413857] [levelValue: 1000] [[
  Exception during lifecycle processing
org.glassfish.deployment.common.DeploymentException: Exception [EclipseLink-28018] (Eclipse Persistence Services - 2.6.4.qualifier): org.eclipse.persistence.exceptions.EntityManagerSetupException
Exception Description: Predeployment of PersistenceUnit [Default] failed.
Internal Exception: Exception [EclipseLink-28007] (Eclipse Persistence Services - 2.6.4.qualifier): org.eclipse.persistence.exceptions.EntityManagerSetupException
Exception Description: Failed to instantiate ServerPlatform of type [org.eclipse.persistence.platform.server.glassfish.GlassfishPlatform] specified in [eclipselink.target-server] property.
Internal Exception: java.lang.NoSuchMethodException: org.eclipse.persistence.platform.server.glassfish.GlassfishPlatform.<init>(org.eclipse.persistence.sessions.DatabaseSession)
	at org.glassfish.javaee.full.deployment.EarDeployer.prepare(EarDeployer.java:182)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.prepareModule(ApplicationLifecycle.java:926)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:435)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:488)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:544)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:540)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:570)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:562)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:561)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1469)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1851)
	at org.glassfish.deployment.autodeploy.AutoOperation.run(AutoOperation.java:164)
	at org.glassfish.deployment.autodeploy.AutoDeployer.deploy(AutoDeployer.java:597)
	at org.glassfish.deployment.autodeploy.AutoDeployer.deployAll(AutoDeployer.java:484)
	at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:412)
	at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:403)
	at org.glassfish.deployment.autodeploy.AutoDeployService$1.run(AutoDeployService.java:233)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: javax.persistence.PersistenceException: Exception [EclipseLink-28018] (Eclipse Persistence Services - 2.6.4.qualifier): org.eclipse.persistence.exceptions.EntityManagerSetupException
Exception Description: Predeployment of PersistenceUnit [Default] failed.
Internal Exception: Exception [EclipseLink-28007] (Eclipse Persistence Services - 2.6.4.qualifier): org.eclipse.persistence.exceptions.EntityManagerSetupException
Exception Description: Failed to instantiate ServerPlatform of type [org.eclipse.persistence.platform.server.glassfish.GlassfishPlatform] specified in [eclipselink.target-server] property.
Internal Exception: java.lang.NoSuchMethodException: org.eclipse.persistence.platform.server.glassfish.GlassfishPlatform.<init>(org.eclipse.persistence.sessions.DatabaseSession)
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.createPredeployFailedPersistenceException(EntityManagerSetupImpl.java:2035)
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.predeploy(EntityManagerSetupImpl.java:2026)
	at org.eclipse.persistence.jpa.PersistenceProvider.createContainerEntityManagerFactoryImpl(PersistenceProvider.java:347)
	at org.eclipse.persistence.jpa.PersistenceProvider.createContainerEntityManagerFactory(PersistenceProvider.java:313)
	at org.glassfish.persistence.jpa.PersistenceUnitLoader.loadPU(PersistenceUnitLoader.java:207)
	at org.glassfish.persistence.jpa.PersistenceUnitLoader.<init>(PersistenceUnitLoader.java:114)
	at org.glassfish.persistence.jpa.JPADeployer$1.visitPUD(JPADeployer.java:225)
	at org.glassfish.persistence.jpa.JPADeployer$PersistenceUnitDescriptorIterator.iteratePUDs(JPADeployer.java:520)
	at org.glassfish.persistence.jpa.JPADeployer.createEMFs(JPADeployer.java:240)
	at org.glassfish.persistence.jpa.JPADeployer.prepare(JPADeployer.java:170)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.prepareModule(ApplicationLifecycle.java:926)
	at org.glassfish.javaee.full.deployment.EarDeployer.prepareBundle(EarDeployer.java:309)
	at org.glassfish.javaee.full.deployment.EarDeployer.access$200(EarDeployer.java:88)
	at org.glassfish.javaee.full.deployment.EarDeployer$1.doBundle(EarDeployer.java:155)
	at org.glassfish.javaee.full.deployment.EarDeployer$1.doBundle(EarDeployer.java:152)
	at org.glassfish.javaee.full.deployment.EarDeployer.doOnAllBundles(EarDeployer.java:255)
	at org.glassfish.javaee.full.deployment.EarDeployer.prepare(EarDeployer.java:152)
	... 25 more
Caused by: Exception [EclipseLink-28018] (Eclipse Persistence Services - 2.6.4.qualifier): org.eclipse.persistence.exceptions.EntityManagerSetupException
Exception Description: Predeployment of PersistenceUnit [Default] failed.
Internal Exception: Exception [EclipseLink-28007] (Eclipse Persistence Services - 2.6.4.qualifier): org.eclipse.persistence.exceptions.EntityManagerSetupException
Exception Description: Failed to instantiate ServerPlatform of type [org.eclipse.persistence.platform.server.glassfish.GlassfishPlatform] specified in [eclipselink.target-server] property.
Internal Exception: java.lang.NoSuchMethodException: org.eclipse.persistence.platform.server.glassfish.GlassfishPlatform.<init>(org.eclipse.persistence.sessions.DatabaseSession)
	at org.eclipse.persistence.exceptions.EntityManagerSetupException.predeployFailed(EntityManagerSetupException.java:231)
	... 42 more
Caused by: Exception [EclipseLink-28007] (Eclipse Persistence Services - 2.6.4.qualifier): org.eclipse.persistence.exceptions.EntityManagerSetupException
Exception Description: Failed to instantiate ServerPlatform of type [org.eclipse.persistence.platform.server.glassfish.GlassfishPlatform] specified in [eclipselink.target-server] property.
Internal Exception: java.lang.NoSuchMethodException: org.eclipse.persistence.platform.server.glassfish.GlassfishPlatform.<init>(org.eclipse.persistence.sessions.DatabaseSession)
	at org.eclipse.persistence.exceptions.EntityManagerSetupException.failedToInstantiateServerPlatform(EntityManagerSetupException.java:143)
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.updateServerPlatform(EntityManagerSetupImpl.java:1018)
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.predeploy(EntityManagerSetupImpl.java:1721)
	... 40 more
Caused by: java.lang.NoSuchMethodException: org.eclipse.persistence.platform.server.glassfish.GlassfishPlatform.<init>(org.eclipse.persistence.sessions.DatabaseSession)
	at java.lang.Class.getConstructor0(Class.java:3074)
	at java.lang.Class.getConstructor(Class.java:1817)
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.updateServerPlatform(EntityManagerSetupImpl.java:996)
	... 41 more
]]

## Steps to reproduce (Only for bug reports) 

I have an application war that i deploy to both servers and it fails in the latest glassfish

## Environment ##

- **Payara Version**:  4.1.2.173
- **Edition**: Full
- **JDK Version**: jdk1.8.0_25 - Oracle
- **Operating System**: Windows Server 2012
- **Database**: SQL Server 2016

**Comment by lprimak** [comment]
Sounds like you are including a previous version of EclipseLink with your application.
You either need to remove it or use class loader priority / isolation techniques from Payara

**Comment by chilliwebs** [comment]
Sorry for the Delay, I have been working on upgrading our server the last couple days :D.
This was exactly the cause, we had some other issue that where related as well. I should of captured the stack trace for them, but ultimately we needed to remove the following jars from our ear.

org.eclipse.persistence.jpa.jar
org.eclipse.persistence.core.jar
org.eclipse.persistence.moxy.jar
jersey-media-multipart.jar

Thank you for your help!

**Comment by lprimak** [comment]
Fantastic, Glad it worked for you
