### ISSUE TITLE
Unable to open nested entry 'MICRO-INF/runtime/annotation-framework.jar'

### ISSUE THREAD

**Issue by deratzmann** [payara/Payara#2077]
# Description #
----------

My Goal was: Building a Uberjar with the maven payara plugin and load this uberjar in another project right before running failsafe:integration-test

## Expected Outcome
A running instance of my uberjar, when failsafe:integration-test begins.

## Current Outcome

Exception is thrown when starting the server with payara maven plugin (annotation-framework.jar is an example, it is everytime another jar file e.g. also client-cli.jar or others):
`java.lang.IllegalStateException: Unable to open nested entry 'MICRO-INF/runtime/annotation-framework.jar'. It has been compressed and nested jar files must be stored without compression. Please check the mechanism used to create your executable jar file
	at fish.payara.micro.boot.loader.jar.JarFile.createJarFileFromFileEntry(JarFile.java:285)
	at fish.payara.micro.boot.loader.jar.JarFile.createJarFileFromEntry(JarFile.java:260)
	at fish.payara.micro.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:248)
	at fish.payara.micro.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:237)
	at fish.payara.micro.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:103)
	at fish.payara.micro.boot.loader.archive.JarFileArchive.getNestedArchives(JarFileArchive.java:87)
	at fish.payara.micro.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:73)
	at fish.payara.micro.boot.PayaraMicroLauncher.getBootClass(PayaraMicroLauncher.java:108)
	at fish.payara.micro.PayaraMicro.<init>(PayaraMicro.java:369)
	at fish.payara.micro.PayaraMicro.getInstance(PayaraMicro.java:92)
	at fish.payara.micro.PayaraMicro.getInstance(PayaraMicro.java:69)
	at de.otto.verfuegbarkeit.SystemTestBase.initSuite(SystemTestBase.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:206)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:160)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:83)
	at org.apache.maven.plugin.surefire.InPluginVMSurefireStarter.runSuitesInProcess(InPluginVMSurefireStarter.java:84)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1107)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:954)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:832)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)`

## Steps to reproduce (Only for bug reports) 
1. creating uberjar with maven and install in maven repo:

`
<plugin>
                <groupId>fish.payara.maven.plugins</groupId>
                <artifactId>payara-micro-maven-plugin</artifactId>
                <version>1.0.0</version>
                <executions>
                    <execution>
                        <phase>install</phase>
                        <goals>
                            <goal>bundle</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <payaraVersion>4.1.2.173</payaraVersion>
                    <deployArtifacts>
                        <artifactItem>
                            <groupId>${project.groupId}</groupId>
                            <artifactId>${project.artifactId}</artifactId>
                            <version>${project.version}</version>
                            <type>war</type>
                        </artifactItem>
                    </deployArtifacts>
                    <customJars>
                        <artifactItem>
                            <groupId>oracle</groupId>
                            <artifactId>ojdbc7</artifactId>
                            <version>12.1.0.1.0</version>
                        </artifactItem>
                    </customJars>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
                <version>2.5.2</version>
                <configuration>
                    <groupId>${project.groupId}</groupId>
                    <artifactId>${project.artifactId}-microbundle</artifactId>
                    <version>${project.version}</version>
                    <packaging>jar</packaging>
                    <file>${basedir}/target/${project.artifactId}-microbundle.jar</file>
                    <generatePom>true</generatePom>
                </configuration>             
                <executions>
                    <execution>
                        <id>install-jar-lib</id>
                        <goals>
                            <goal>install-file</goal>
                        </goals>
                        <phase>install</phase>
                    </execution>
                </executions>
            </plugin>
`
2. copy the uber jar and Use the uber jar hooked into maven integration-test Process:

            `<plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>install</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/dependencies</outputDirectory>
                            <includeArtifactIds>serviceangebot-testdaten-microbundle</includeArtifactIds>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.20.1</version>
                <configuration>
                    <systemPropertyVariables>
                        <jdbcUrl>myjdbcURL</jdbcUrl>
                        <jdbcUser>myjdbcUser</jdbcUser>
                        <jdbcPassword>myjdbcPW</jdbcPassword>
                        <buildDirectory>${project.build.directory}</buildDirectory>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
            <plugin>
                <groupId>fish.payara.maven.plugins</groupId>
                <artifactId>payara-micro-maven-plugin</artifactId>
                <version>1.0.0</version>
                <executions>
                    <execution>
                        <phase>integration-test</phase>
                        <goals>
                            <goal>start</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <daemon>true</daemon>
                    <payaraMicroAbsolutePath>target/dependencies/serviceangebot-testdaten-microbundle-1.0-SNAPSHOT.jar</payaraMicroAbsolutePath>
                    <copySystemProperties>true</copySystemProperties>
                    <commandLineOptions>
                        <option>
                            <key>--autoBindHttp</key>
                            <value>true</value>
                        </option>
                    </commandLineOptions>
                </configuration>
            </plugin>`

## Context (Optional)
For creating testdata which will be used in Systemtests I reuse a existing Webapplication deployed on a payara micro. Every Test creates the data by sending json to the webapplication.

## Environment ##

- **Payara Version**: 4.1.2.173
- **Edition**: Micro
- **JDK Version**: openjdk 8
- **Operating System**: Windows
- **Database**: oracle

**Comment by deratzmann** [comment]
Any ideas here? Maybe I do sth. wrong?

**Comment by smillidge** [comment]
As this seems to be related to the maven plugin I would raise the issue on that project.

**Comment by smillidge** [comment]
Maven plugin issue
