### ISSUE TITLE
Unable to start domain after enabling secure admin

### ISSUE THREAD

**Issue by jschuck9** [payara/Payara#2146]
# Description #
----------

Unable to start domain after issuing enable-secure-admin on a newly created domain or on domain1.

## Expected Outcome

Domain should restart after issuing enable-secure-admin via asadmin, however, an exception is thrown and the domain does not start.

## Current Outcome

No errors are thrown when issuing enable-secure-admin on a domain, however, during restart the following exception is thrown in the server.log file:

`java.lang.NoSuchFieldError: DEFAULT
        at sun.security.ssl.HandshakeMessage$ClientHello.<init>(HandshakeMessage.java:354)
        at sun.security.ssl.ClientHandshaker.getKickstartMessage(ClientHandshaker.java:1433)
        at sun.security.ssl.Handshaker.kickstart(Handshaker.java:1019)
        at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1497)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1361)
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:757)
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at java.io.DataOutputStream.flush(DataOutputStream.java:123)
        at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:229)
        at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
        at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:338)
        at sun.rmi.registry.RegistryImpl_Stub.rebind(RegistryImpl_Stub.java:147)
        at com.sun.jndi.rmi.registry.RegistryContext.rebind(RegistryContext.java:175)
        at com.sun.jndi.toolkit.url.GenericURLContext.rebind(GenericURLContext.java:251)
        at javax.naming.InitialContext.rebind(InitialContext.java:433)
        at javax.naming.InitialContext.rebind(InitialContext.java:433)
        at javax.management.remote.rmi.RMIConnectorServer.bind(RMIConnectorServer.java:642)
        at javax.management.remote.rmi.RMIConnectorServer.start(RMIConnectorServer.java:427)
        at org.glassfish.admin.mbeanserver.RMIConnectorStarter.start(RMIConnectorStarter.java:318)
        at org.glassfish.admin.mbeanserver.JMXStartupService$JMXConnectorsStarterThread.startConnector(JMXStartupService.java:313)
        at org.glassfish.admin.mbeanserver.JMXStartupService$JMXConnectorsStarterThread.run(JMXStartupService.java:350)`

## Steps to reproduce (Only for bug reports) 

Prerequisites - ** On a newly created domain or domain1

1- ** asadmin enable-secure-admin --port 4848 --user admin
2- ** asadmin stop-domain domain1
3- ** asadmin start-domain domain1

## Environment ##

- **Payara Version**: 5.0.0 Alpha 3
- **Edition**: Full
- **JDK Version**: 8 u151 Oracle (with Unlimited JCE)
- **Operating System**: Linux
- **Database**:

**Comment by smillidge** [comment]
please remove the -Xbootclasspath setting in the JVM Options in the administration console for the server-config and default-config and then test again.

**Comment by smillidge** [comment]
Fixed by #2148
