### ISSUE TITLE
com.sun.gjc.spi.jdbc40.ProfiledConnectionWrapper40 changes Exception thrown by wrapped jdbc Connection (fix inside)

### ISSUE THREAD

**Issue by aojava** [payara/Payara#216]
This is, because Method.invoke throws a InvocationTargetException instead of the original Exception, when the invoked method throws an exception.

Fix:

In ProfiledConnectionWrapper40 ( https://github.com/payara/Payara/tree/master/appserver/jdbc/jdbc-ra/jdbc40/src/main/java/com/sun/gjc/spi/jdbc40 ), change

    return method.invoke(actualObject, args);

in line 435 in Method getProxyObject

to

        try {
          return method.invoke(actualObject, args);
        } catch (InvocationTargetException ex) {
          Throwable cause = ex.getCause();
          if (cause != null) {
            throw cause;
          } else {
            throw ex;
          }
        }

**Comment by smillidge** [comment]
Just wondering why you see this as a problem as typically the InvocationTargetException is wrapped in a SQLException by the public methods and the original SQLException is not lost just wrapped twice over?
So the type doesn't change, my concern in implementing your change is the involvement of the ProfiledConnectionWrapper will be "lost" in the exception trace and I don't like losing diagnostic information.

**Comment by aojava** [comment]
I've made a small example to demonstrate the issue. I will first show you the example java class and then the results without using the ConnectionWrapper and then with using it (but without my changes).

This is the demonstration class:

    package com.mycompany.mavenproject1;
    
    import java.sql.Connection;
    import java.sql.SQLException;
    import java.sql.Statement;
    import javax.annotation.PostConstruct;
    import javax.annotation.Resource;
    import javax.ejb.Singleton;
    import javax.ejb.Startup;
    import javax.sql.DataSource;
    
    @Singleton
    @Startup
    public class PrepareDatabase {
    
      @Resource
      private DataSource dataSource;
    
      @PostConstruct
      private void init() {
        System.out.println(" = = = BEGIN = = =");
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement();) {
          statement.execute("just_invalid_foo_to_throw_an_SQLException");
        } catch (SQLException ex) {
          System.out.println("Something bad happend: " + ex.getMessage());
        }
        System.out.println(" = = = END = = =");
      }
    
    }
    
This is the (expected and correct) result without the connection wrapper:

    Information:   = = = BEGIN = = =
    Information:   Something bad happend: Syntaxfehler: Encountered "just_invalid_foo_to_throw_an_SQLException" at line 1, column 1.
    Information:   = = = END = = =

Now we activate the ConnectionWrapper by adding the following attribute to the DerbyPool in the domain.xml:

    sql-trace-listeners="com.sun.gjc.util.SQLTraceLogger"

This is how the connection-pool-configuration looks after that change:

    <jdbc-connection-pool is-isolation-level-guaranteed="false" datasource-classname="org.apache.derby.jdbc.ClientDataSource" name="DerbyPool" res-type="javax.sql.DataSource" sql-trace-listeners="com.sun.gjc.util.SQLTraceLogger">
      <property name="PortNumber" value="1527"></property>
      <property name="Password" value="APP"></property>
      <property name="User" value="APP"></property>
      <property name="serverName" value="localhost"></property>
      <property name="DatabaseName" value="sun-appserv-samples"></property>
      <property name="connectionAttributes" value=";create=true"></property>
    </jdbc-connection-pool>

And here is the result with the active Connection-Pool-Wrapper. Note, that the line "System.out.println(" = = = END = = =");" is no longer reached now. More, the web app will no longer deploy / startup.

    Information:   = = = BEGIN = = =
    Fein:   ThreadID=18 | ThreadName=RunLevelControllerThread-1425284204856 | TimeStamp=1425284210037 | ClassName=org.apache.derby.client.net.NetConnection40 | MethodName=createStatement | 
    Fein:   ThreadID=18 | ThreadName=RunLevelControllerThread-1425284204856 | TimeStamp=1425284210051 | ClassName=com.sun.gjc.spi.jdbc40.StatementWrapper40 | MethodName=execute | arg[0]=just_invalid_foo_to_throw_an_SQLException | 
    Fein:   ThreadID=18 | ThreadName=RunLevelControllerThread-1425284204856 | TimeStamp=1425284210060 | ClassName=com.sun.gjc.spi.jdbc40.StatementWrapper40 | MethodName=close | 
    Schwerwiegend:   Exception while invoking class org.glassfish.ejb.startup.EjbApplication start method
    javax.ejb.EJBException: javax.ejb.CreateException: Initialization failed for Singleton PrepareDatabase
    	at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:649)
    	at com.sun.ejb.containers.AbstractSingletonContainer.instantiateSingletonInstance(AbstractSingletonContainer.java:389)
    	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:219)
    	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:180)
    	at org.glassfish.ejb.startup.SingletonLifeCycleManager.doStartup(SingletonLifeCycleManager.java:158)
    	at org.glassfish.ejb.startup.EjbApplication.start(EjbApplication.java:166)
    	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:122)
    	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:291)
    	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:352)
    	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:500)
    	at com.sun.enterprise.v3.server.ApplicationLoaderService.processApplication(ApplicationLoaderService.java:406)
    	at com.sun.enterprise.v3.server.ApplicationLoaderService.postConstruct(ApplicationLoaderService.java:243)
    	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:329)
    	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:377)
    	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:461)
    	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:227)
    	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:84)
    	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2258)
    	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:105)
    	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:87)
    	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1162)
    	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1147)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: javax.ejb.CreateException: Initialization failed for Singleton PrepareDatabase
    	at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:476)
    	at com.sun.ejb.containers.AbstractSingletonContainer.access$000(AbstractSingletonContainer.java:74)
    	at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:647)
    	... 24 more
    Caused by: java.lang.reflect.UndeclaredThrowableException
    	at com.sun.proxy.$Proxy185.execute(Unknown Source)
    	at com.mycompany.mavenproject1.PrepareDatabase.init(PrepareDatabase.java:32)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at com.sun.ejb.containers.interceptors.BeanCallbackInterceptor.intercept(InterceptorManager.java:1035)
    	at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
    	at com.sun.ejb.containers.interceptors.CallbackInvocationContext.proceed(CallbackInvocationContext.java:205)
    	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:55)
    	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at com.sun.ejb.containers.interceptors.CallbackInterceptor.intercept(InterceptorManager.java:986)
    	at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
    	at com.sun.ejb.containers.interceptors.CallbackInvocationContext.proceed(CallbackInvocationContext.java:205)
    	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
    	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.init(SystemInterceptorProxy.java:125)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at com.sun.ejb.containers.interceptors.CallbackInterceptor.intercept(InterceptorManager.java:986)
    	at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
    	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:412)
    	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)
    	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:2014)
    	at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:468)
    	... 26 more
    Caused by: java.lang.reflect.InvocationTargetException
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at com.sun.gjc.spi.jdbc40.ProfiledConnectionWrapper40$1.invoke(ProfiledConnectionWrapper40.java:435)
    	... 56 more
    Caused by: java.sql.SQLSyntaxErrorException: Syntaxfehler: Encountered "just_invalid_foo_to_throw_an_SQLException" at line 1, column 1.
    	at org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)
    	at org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)
    	at org.apache.derby.client.am.Statement.execute(Unknown Source)
    	at com.sun.gjc.spi.base.StatementWrapper.execute(StatementWrapper.java:360)
    	... 61 more
    Caused by: org.apache.derby.client.am.SqlException: Syntaxfehler: Encountered "just_invalid_foo_to_throw_an_SQLException" at line 1, column 1.
    	at org.apache.derby.client.am.Statement.completeSqlca(Unknown Source)
    	at org.apache.derby.client.am.Statement.completeExecuteImmediate(Unknown Source)
    	at org.apache.derby.client.net.NetStatementReply.parseEXCSQLIMMreply(Unknown Source)
    	at org.apache.derby.client.net.NetStatementReply.readExecuteImmediate(Unknown Source)
    	at org.apache.derby.client.net.StatementReply.readExecuteImmediate(Unknown Source)
    	at org.apache.derby.client.net.NetStatement.readExecuteImmediate_(Unknown Source)
    	at org.apache.derby.client.am.Statement.readExecuteImmediate(Unknown Source)
    	at org.apache.derby.client.am.Statement.flowExecute(Unknown Source)
    	at org.apache.derby.client.am.Statement.executeX(Unknown Source)
    	... 63 more
    
    Schwerwiegend:   Exception during lifecycle processing
    javax.ejb.EJBException: javax.ejb.CreateException: Initialization failed for Singleton PrepareDatabase
    	at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:649)
    	at com.sun.ejb.containers.AbstractSingletonContainer.instantiateSingletonInstance(AbstractSingletonContainer.java:389)
    	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:219)
    	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:180)
    	at org.glassfish.ejb.startup.SingletonLifeCycleManager.doStartup(SingletonLifeCycleManager.java:158)
    	at org.glassfish.ejb.startup.EjbApplication.start(EjbApplication.java:166)
    	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:122)
    	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:291)
    	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:352)
    	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:500)
    	at com.sun.enterprise.v3.server.ApplicationLoaderService.processApplication(ApplicationLoaderService.java:406)
    	at com.sun.enterprise.v3.server.ApplicationLoaderService.postConstruct(ApplicationLoaderService.java:243)
    	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:329)
    	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:377)
    	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:461)
    	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:227)
    	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:84)
    	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2258)
    	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:105)
    	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:87)
    	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1162)
    	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1147)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: javax.ejb.CreateException: Initialization failed for Singleton PrepareDatabase
    	at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:476)
    	at com.sun.ejb.containers.AbstractSingletonContainer.access$000(AbstractSingletonContainer.java:74)
    	at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:647)
    	... 24 more
    Caused by: java.lang.reflect.UndeclaredThrowableException
    	at com.sun.proxy.$Proxy185.execute(Unknown Source)
    	at com.mycompany.mavenproject1.PrepareDatabase.init(PrepareDatabase.java:32)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at com.sun.ejb.containers.interceptors.BeanCallbackInterceptor.intercept(InterceptorManager.java:1035)
    	at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
    	at com.sun.ejb.containers.interceptors.CallbackInvocationContext.proceed(CallbackInvocationContext.java:205)
    	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:55)
    	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at com.sun.ejb.containers.interceptors.CallbackInterceptor.intercept(InterceptorManager.java:986)
    	at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
    	at com.sun.ejb.containers.interceptors.CallbackInvocationContext.proceed(CallbackInvocationContext.java:205)
    	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
    	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.init(SystemInterceptorProxy.java:125)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at com.sun.ejb.containers.interceptors.CallbackInterceptor.intercept(InterceptorManager.java:986)
    	at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
    	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:412)
    	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)
    	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:2014)
    	at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:468)
    	... 26 more
    Caused by: java.lang.reflect.InvocationTargetException
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at com.sun.gjc.spi.jdbc40.ProfiledConnectionWrapper40$1.invoke(ProfiledConnectionWrapper40.java:435)
    	... 56 more
    Caused by: java.sql.SQLSyntaxErrorException: Syntaxfehler: Encountered "just_invalid_foo_to_throw_an_SQLException" at line 1, column 1.
    	at org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)
    	at org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)
    	at org.apache.derby.client.am.Statement.execute(Unknown Source)
    	at com.sun.gjc.spi.base.StatementWrapper.execute(StatementWrapper.java:360)
    	... 61 more
    Caused by: org.apache.derby.client.am.SqlException: Syntaxfehler: Encountered "just_invalid_foo_to_throw_an_SQLException" at line 1, column 1.
    	at org.apache.derby.client.am.Statement.completeSqlca(Unknown Source)
    	at org.apache.derby.client.am.Statement.completeExecuteImmediate(Unknown Source)
    	at org.apache.derby.client.net.NetStatementReply.parseEXCSQLIMMreply(Unknown Source)
    	at org.apache.derby.client.net.NetStatementReply.readExecuteImmediate(Unknown Source)
    	at org.apache.derby.client.net.StatementReply.readExecuteImmediate(Unknown Source)
    	at org.apache.derby.client.net.NetStatement.readExecuteImmediate_(Unknown Source)
    	at org.apache.derby.client.am.Statement.readExecuteImmediate(Unknown Source)
    	at org.apache.derby.client.am.Statement.flowExecute(Unknown Source)
    	at org.apache.derby.client.am.Statement.executeX(Unknown Source)
    	... 63 more
    
    Schwerwiegend:   Exception while loading the app
    Schwerwiegend:   Undeployment failed for context /mavenproject1
    Schwerwiegend:   Application deployment failed: Exception while loading the app

**Comment by aojava** [comment]
An additional comment about your statement "I don't like losing diagnostic information": Because the InvocationTargetException is (nearly) a wrapper excpetion, you don't loose the information about the invovled ProfiledConnectionWrapper. Here is, how the stack trace looks, if you would apply my changes:

    Caused by: java.sql.SQLException: [LNA][Pervasive][ODBC Engine Interface][Data Record Manager][SPEng][Pervasive][ODBC Engine Interface]Invalid column name: 'Anlege_User'.
    	at com.pervasive.jdbc.lna.LNAObject.getErrors(LNAObject.java:213)
    	at com.pervasive.jdbc.lna.LNAStatement.getErrors(LNAStatement.java:937)
    	at com.pervasive.jdbc.lna.LNAObject.checkError(LNAObject.java:256)
    	at com.pervasive.jdbc.lna.LNAStatement.execute(LNAStatement.java:310)
    	at com.pervasive.jdbc.v2.PreparedStatement.execute(PreparedStatement.java:466)
    	at com.sun.gjc.spi.base.PreparedStatementWrapper.execute(PreparedStatementWrapper.java:508)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    ==> at com.sun.gjc.spi.jdbc40.ProfiledConnectionWrapper40$1.invoke(ProfiledConnectionWrapper40.java:461)
    	at com.sun.proxy.$Proxy293.execute(Unknown Source)
    	at de.aidaorga.aida.ewas.central.database.business.control.StoredProcedures.queryDb(StoredProcedures.java:684)
    	at de.aidaorga.aida.ewas.central.database.business.control.StoredProcedures.addApplication(StoredProcedures.java:554)
        ...

**Comment by smillidge** [comment]
OK we'll incorporate this. I was struggling to see how the invoke web being called outside of the class but I see now that the proxy object is directly passed out. Do you want to sign a CLA https://github.com/payara/Payara/blob/master/PayaraCLA.pdf  and create a pull request or shall we fix directly?

**Comment by aojava** [comment]
For this small change, I think, the simplest thing is, if you would fix it directly.
