### ISSUE TITLE
No SSL access on Payara 5.0.0.Alpha3 (NoSuchMethod: SupportedEllipticCurvesExtension)

### ISSUE THREAD

**Issue by simdevmon** [payara/Payara#2168]
# Description #
----------

Payara 5.0.0.Alpha3 does not respond to https access (SSL).

## Expected Outcome
I would expect that access via https is possible like in Payara 4.1.1.173

## Current Outcome
A request causes the following error message:
```
[#|2017-11-20T14:08:32.907+0000|WARNING|Payara 5.0.Alpha3|org.glassfish.grizzly.filterchain.DefaultFilterChain||
  GRIZZLY0013: Exception during FilterChain execution
java.lang.NoSuchMethodError: sun.security.ssl.SupportedEllipticCurvesExtension.curveIds()[I
        at sun.security.ssl.ServerHandshaker.setupEphemeralECDHKeys(ServerHandshaker.java:1499)
        at sun.security.ssl.ServerHandshaker.trySetCipherSuite(ServerHandshaker.java:1301)
        at sun.security.ssl.ServerHandshaker.chooseCipherSuite(ServerHandshaker.java:1105)
        at sun.security.ssl.ServerHandshaker.clientHello(ServerHandshaker.java:806)
        at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:226)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:984)
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:924)
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:921)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1379)
        at org.glassfish.grizzly.ssl.SSLUtils.executeDelegatedTask(SSLUtils.java:274)
        at org.glassfish.grizzly.ssl.SSLBaseFilter.doHandshakeStep(SSLBaseFilter.java:708)
        at org.glassfish.grizzly.ssl.SSLBaseFilter.doHandshakeStep(SSLBaseFilter.java:622)
        at org.glassfish.grizzly.ssl.SSLBaseFilter.handleRead(SSLBaseFilter.java:334)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:231)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
        at java.lang.Thread.run(Thread.java:748)

```

## Steps to reproduce (Only for bug reports) 
I use this docker image for testing. After successful startup http://localhost:4848 will provide this error.
```
FROM ubuntu
MAINTAINER Simdevmon <simdevmon@gmail.com>

# Install packages on ubuntu base image
RUN \
 apt-get update && \
 apt-get install -y unzip curl software-properties-common python-software-properties

# Install Java 8, agree to oracle jdk license
RUN \
  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get install -y oracle-java8-installer && \
  rm -rf /var/lib/apt/lists/* && \
  rm -rf /var/cache/oracle-jdk8-installer
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle

# Download JaCoCo
ENV JACOCO_VERSION 0.7.9
ENV JACOCO_URL http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/${JACOCO_VERSION}/jacoco-${JACOCO_VERSION}.zip
ENV JACOCO_FILENAME jacoco-${JACOCO_VERSION}.zip
RUN mkdir /opt/JaCoCo && \
  curl -o /opt/${JACOCO_FILENAME} -L ${JACOCO_URL} && unzip /opt/${JACOCO_FILENAME} -d /opt/JaCoCo && \
  chmod -R 755 /opt/JaCoCo

# Settings application server
ENV PAYARA_VERSION 5.0.0.Alpha3
ENV PAYARA_URL https://s3-eu-west-1.amazonaws.com/payara.fish/Payara+Downloads/Payara+${PAYARA_VERSION}/payara-${PAYARA_VERSION}.zip
ENV PAYARA_FILENAME payara-${PAYARA_VERSION}.zip
ENV PAYARA_FOLDER payara5
ENV DOMAIN_NAME nmc

# Install Payara application server
RUN curl -o /opt/${PAYARA_FILENAME}.zip -L ${PAYARA_URL} && unzip /opt/${PAYARA_FILENAME}.zip -d /opt
WORKDIR /opt/${PAYARA_FOLDER}/bin

# Setup domain
RUN \
  # https://github.com/payara/docker-payaraserver-full/issues/8
  #./asadmin delete-domain domain1 && \
  #./asadmin delete-domain payaradomain && \
  ./asadmin create-domain --nopassword=true --domainproperties domain.instancePort=8082:http.ssl.port=8081 nmc

RUN echo "admin;{SSHA256}80e0NeB6XBWXsIPa7pT54D9JZ5DR5hGQV1kN1OAsgJePNXY6Pl0EIw==;asadmin" > /opt/${PAYARA_FOLDER}/glassfish/domains/${DOMAIN_NAME}/config/admin-keyfile
RUN echo "AS_ADMIN_PASSWORD=glassfish" > pwdfile

# Database settings for PostgreSQL
ENV JDBC_DRIVER_VERSION 42.1.4
ENV JDBC_DRIVER_URL http://central.maven.org/maven2/org/postgresql/postgresql/${JDBC_DRIVER_VERSION}/postgresql-${JDBC_DRIVER_VERSION}.jar
ENV JDBC_DRIVER_FILENAME postgresql-${JDBC_DRIVER_VERSION}.jar
ENV DB_DRIVER_CLASS org.postgresql.Driver
ENV DB_URL 'jdbc\:postgresql\://nmc-db\:5432/nmcdb'

ENV DB_USER nmc
ENV DB_PASSWORD testpw
ENV JDBC_RESOURCE NMCDB
ENV JDBC_POOL jdbc/NMC

# Install JDBC driver
RUN curl -o /opt/${PAYARA_FOLDER}/glassfish/domains/${DOMAIN_NAME}/lib/${JDBC_DRIVER_FILENAME} -L ${JDBC_DRIVER_URL}

RUN \
  ./asadmin start-domain ${DOMAIN_NAME} && \
  ./asadmin --user admin --passwordfile pwdfile enable-secure-admin && \
  ./asadmin --user admin --passwordfile pwdfile delete-jvm-options -client && \
  ./asadmin --user admin --passwordfile pwdfile create-jvm-options '-server' && \
  ./asadmin --user admin --passwordfile pwdfile delete-jvm-options -Xmx512m && \
  ./asadmin --user admin --passwordfile pwdfile create-jvm-options -Xms1024m && \
  ./asadmin --user admin --passwordfile pwdfile create-jvm-options -Xmx1024m && \
  ./asadmin --user admin --passwordfile pwdfile delete-jvm-options '-XX\:MaxPermSize=192m' && \
  ./asadmin --user admin --passwordfile pwdfile create-jvm-options '-XX\:MetaspaceSize=512m' && \
  ./asadmin --user admin --passwordfile pwdfile create-jdbc-connection-pool --driverclassname ${DB_DRIVER_CLASS} --restype java.sql.Driver --property user=${DB_USER}:password=${DB_PASSWORD}:url=${DB_URL} ${JDBC_RESOURCE} && \
  ./asadmin --user admin --passwordfile pwdfile create-jdbc-resource --connectionpoolid ${JDBC_RESOURCE} ${JDBC_POOL} && \
  ./asadmin --user admin --passwordfile pwdfile set resources.jdbc-connection-pool.${JDBC_RESOURCE}.connection-validation-method=auto-commit && \
  ./asadmin --user admin --passwordfile pwdfile set resources.jdbc-connection-pool.${JDBC_RESOURCE}.is-connection-validation-required=true && \
  ./asadmin --user admin --passwordFile pwdfile create-jvm-options '-javaagent\:/opt/JaCoCo/lib/jacocoagent.jar=output=tcpserver,address=*' && \
  ./asadmin --user admin --passwordFile pwdfile create-javamail-resource --mailhost=localhost --mailuser=user --fromaddress=user@localhost.com javamail/nmc && \
  ./asadmin --user admin --passwordfile pwdfile set configs.config.server-config.jms-service.type=DISABLED && \
  ./asadmin --user admin --passwordfile pwdfile set configs.config.server-config.iiop-service.iiop-listener.SSL.enabled=false && \
  ./asadmin --user admin --passwordfile pwdfile set configs.config.server-config.iiop-service.iiop-listener.SSL_MUTUALAUTH.enabled=false && \
  ./asadmin --user admin --passwordfile pwdfile set configs.config.server-config.iiop-service.iiop-listener.orb-listener-1.enabled=false && \
  ./asadmin --user admin --passwordfile pwdfile set configs.config.server-config.network-config.transports.transport.tcp.acceptor-threads=4 && \
  ./asadmin --user admin --passwordfile pwdfile set configs.config.server-config.thread-pools.thread-pool.http-thread-pool.min-thread-pool-size=4 && \
  ./asadmin --user admin --passwordfile pwdfile set configs.config.server-config.thread-pools.thread-pool.http-thread-pool.max-thread-pool-size=8 && \
  ./asadmin --user admin --passwordfile pwdfile set configs.config.server-config.thread-pools.thread-pool.thread-pool-1.min-thread-pool-size=4 && \
  ./asadmin --user admin --passwordfile pwdfile set-log-attributes --target=server-config com.sun.enterprise.server.logging.GFFileHandler.excludeFields='tid,userId,ecid,timeMillis,levelValue' && \
  ./asadmin --user admin --passwordfile pwdfile set-log-attributes --target=server-config com.sun.enterprise.server.logging.GFFileHandler.rotationOnDateChange='true' && \
  ./asadmin --user admin --passwordfile pwdfile set-log-attributes --target=server-config com.sun.enterprise.server.logging.GFFileHandler.maxHistoryFiles='30' && \
  ./asadmin --user admin --passwordfile pwdfile set-log-attributes --target=server-config com.sun.enterprise.server.logging.GFFileHandler.rotationLimitInBytes='10485760' && \
  ./asadmin --user admin --passwordfile pwdfile set-log-attributes --target=server-config com.sun.enterprise.server.logging.GFFileHandler.formatter='com.sun.enterprise.server.logging.UniformLogFormatter' && \
  ./asadmin --user admin --passwordfile pwdfile set configs.config.server-config.admin-service.das-config.dynamic-reload-enabled=false && \
  ./asadmin --user admin --passwordfile pwdfile set configs.config.server-config.admin-service.das-config.autodeploy-enabled=false && \
  ./asadmin --user admin --passwordfile pwdfile set configs.config.server-config.network-config.protocols.protocol.http-listener-1.http.file-cache.enabled=true && \
  ./asadmin --user admin --passwordfile pwdfile set configs.config.server-config.network-config.protocols.protocol.http-listener-1.http.file-cache.max-age-seconds=900 && \
  ./asadmin --user admin --passwordfile pwdfile set configs.config.server-config.network-config.protocols.protocol.http-listener-2.http.file-cache.enabled=true && \
  ./asadmin --user admin --passwordfile pwdfile set configs.config.server-config.network-config.protocols.protocol.http-listener-2.http.file-cache.max-age-seconds=900 && \
  ./asadmin --user admin --passwordfile pwdfile set configs.config.server-config.network-config.protocols.protocol.http-listener-1.http.compressable-mime-type=text/html,text/xml,text/plain,text/css,text/javascript,application/json,application/xml && \
  ./asadmin --user admin --passwordfile pwdfile set configs.config.server-config.network-config.protocols.protocol.http-listener-1.http.compression=on && \
  ./asadmin --user admin --passwordfile pwdfile set configs.config.server-config.network-config.protocols.protocol.http-listener-2.http.compressable-mime-type=text/html,text/xml,text/plain,text/css,text/javascript,application/json,application/xml && \
  ./asadmin --user admin --passwordfile pwdfile set configs.config.server-config.network-config.protocols.protocol.http-listener-2.http.compression=on && \
  ./asadmin stop-domain ${DOMAIN_NAME}

EXPOSE 8081 8082 4848

# Boot application server on container start (verbose to keep the process in foreground)
CMD ["/opt/payara5/bin/asadmin", "start-domain", "--verbose", "nmc"]
```

## Environment ##

- **Payara Version**: 5.0.0.Alpha3
- **Edition**: Full
- **JDK Version**: 8 u151 Oracle
- **Operating System**: Linux Ubuntu 4.4.0-97.120-generic 4.4.87
- **Database**: PostgreSQL

**Comment by smillidge** [comment]
Fixed by #2148
