### ISSUE TITLE
EJB webservice with wssecurity policy gets NoClassDefFoundError: org/apache/commons/logging/LogFactory

### ISSUE THREAD

**Issue by bdrx312** [payara/Payara#218]
We have an ejb soap webservice with a ws security policy. We get a NoClassDefFoundError when receiving a message.

    [..][Payara 4.1][SEVERE][][com.sun.xml.ws.transport.http.HttpAdapter][tid: _ThreadID=40 _ThreadName=http-listener-2(3)][timeMillis:...][levelValue:1000][[
    org/apache/commons/logging/LogFactory
    java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
    at org.apache.xml.security.Init.<clinit>(Init.java:59)
    at com.sun.xml.ws.security.opt.impl.incoming.SecurityRecipient.<clint>(SecurityRecipient.java:132)
    at com.sun.xml.wss.provider.wsit.WSITServerAuthContext.verifyInboundMessage(WSITServerAuthContext.java:587)
    at com.sun.xml.wss.provider.wsit.WSITServerAuthContext.validateRequest(WSITServerAuthContext.java:364)
    at com.sun.xml.wss.provider.wsit.WSITServerAuthContext.validateRequest(WSITServerAuthContext.java:267)
    at com.sun.enterprise.security.webservices.CommonServerSecurityPipe.process(CommonServerSecurityPipe.java:141)
    at com.sun.xml.ws.api.pipe.helper.PipeAdapter.processRequest(PipeAdapter.java:119)
    at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:1136)
    at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:1050)
    at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:1019)
    at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:877)
    at (WSEndpointImpl.java:419)
    at (HttpAdapter.java:868)
    at (HttpAdapter.java:422)
    at (ServletAdapter.java:169)
    at (Ejb3MessageDispatcher.java:110)
    at (Ejb3MessageDispatcher.java:80)
    at (EjbWebServiceServlet.java:210)
    at (EjbWebServiceServlet.java:153)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.glassfish.grizzly.servlet.ServletHandler.doServletService(ServletHandler.java:227)
    at (ServletHandler:179)
    at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
    at (ContainerMapper.java:167)
    at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:204)
    at (HttpHandler.java:178)
    at (HttpServerFilter.java:235)
    at (ExecutorResolver.java:119)
    at (DefaultFilterChange.java:283)
    at (DefaultFilterChange.java:200)
    at (DefaultFilterChange.java:131)
    at (DefaultFilterChange.java:111)
    at (ProcessExecutor.java:77)
    ...
    at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory not found by org.glassfish.metro.webservices-osgi [217]
       at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1532)
       at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:75)
       at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1955)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
       ... 42 more
    ]]

**Comment by smillidge** [comment]
This could be related to the upgrade of metro we inherited from the GF source tree as the trunk source for metro pulls in Apache XML security classes. I'll revert to the latest metro 2.3.1 and if you can retest when we have the build ready.

**Comment by smillidge** [comment]
I have committed a change I hope will fix this. Can you try the latest prerelease build (should be build-159 or greater) from http://www.payara.co/upstream_builds and let me know if the problem is fixed.

**Comment by smillidge** [comment]
Did this fix work for you?

**Comment by bdrx312** [comment]
Sorry we have not had an opportunity to try the fix yet due the the development stage we are in. As a work-around we had just put the apache-logging jar into the lib directory.

**Comment by smillidge** [comment]
I will close for now as I beleive this is fixed. Please reopen if I'm wrong.

**Comment by carlosmoh** [comment]
put commons-logging jar lib into dir C:\glassfish4\glassfish\modules, did fix this for me
