### ISSUE TITLE
Turning off dynamic reloading in Micro 174 results in NPE in the logs

### ISSUE THREAD

**Issue by ljnelson** [payara/Payara#2184]
# Description #
----------

Turning off dynamic reloading results in a `NullPointerException` in the logs.

## Steps to reproduce (Only for bug reports) 

1. Use Payara Micro 174.
2. Create a `prebootcommands` file that contains this line:
`set configs.config.server-config.admin-service.das-config.dynamic-reload-enabled=false`
3. Observe the following in the logs on startup:
```
[2017-11-27T17:09:54.210-0800] [] [INFO] [AS-WEB-GLUE-00172] [javax.enterprise.web] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1511831394210] [levelValue: 800] Loading application [argle-bargle-0.0.1-SNAPSHOT] at [/]

java.lang.NullPointerException
	at java.net.URI$Parser.parse(URI.java:3042)
	at java.net.URI.<init>(URI.java:588)
	at com.sun.enterprise.v3.server.DynamicReloader$AppReloadInfo.<init>(DynamicReloader.java:292)
	at com.sun.enterprise.v3.server.DynamicReloader$AppReloadInfo.<init>(DynamicReloader.java:279)
	at com.sun.enterprise.v3.server.DynamicReloader.findOrCreateAppReloadInfo(DynamicReloader.java:217)
	at com.sun.enterprise.v3.server.DynamicReloader.chooseAppsToReload(DynamicReloader.java:192)
	at com.sun.enterprise.v3.server.DynamicReloader.reloadApps(DynamicReloader.java:163)
	at com.sun.enterprise.v3.server.DynamicReloader.run(DynamicReloader.java:146)
	at com.sun.enterprise.v3.server.DynamicReloadService$1.run(DynamicReloadService.java:164)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```
## Environment ##

- **Payara Version**: Payara Micro 174
- **Edition**: Micro
- **JDK Version**: 8
- **Operating System**: Mac

**Comment by ljnelson** [comment]
Hi; thanks for a great product.  I hope the description above is sufficient; let me know if you have any questions.  The `NullPointerException` does not seem to affect the deployment in any way.

**Comment by smillidge** [comment]
I can't reproduce this on the current master.

**Comment by lprimak** [comment]
I have seen this. It happens sporadically

**Comment by smillidge** [comment]
Must be a timing thing as the code checks whether it is enabled so the Timer thread shouldn't be created if it is disabled. A simple null check will likely remove the stack trace.

**Comment by lprimak** [comment]
Indeed

**Comment by lprimak** [comment]
Assigned Payara internal issue ```PAYARA-2311```
