### ISSUE TITLE
Payara 5 Alpha4 with Java 9 not working on Windows

### ISSUE THREAD

**Issue by farrelmr** [payara/Payara#2200]
# Description #
----------
Im aware its an early release, but I;ve been experimenting with payara 5 on Java 9 - but still getting NullPointer on Windows. Can try different OS - 

C:\payara-5.0.0.Alpha4-20171117.004238-21\payara5\bin>java -version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

C:\payara-5.0.0.Alpha4-20171117.004238-21\payara5\bin>asadmin.bat start-domain payaradomain
Exception in thread "main" java.lang.NullPointerException
        at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.initializeServiceLocator(AbstractModulesRegistryImpl.java:152)
        at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.newServiceLocator(AbstractModulesRegistryImpl.java:144)
        at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.createServiceLocator(AbstractModulesRegistryImpl.java:218)
        at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.createServiceLocator(AbstractModulesRegistryImpl.java:224)
        at com.sun.enterprise.module.single.StaticModulesRegistry.createServiceLocator(StaticModulesRegistry.java:88)
        at com.sun.enterprise.admin.cli.CLIContainer.getServiceLocator(CLIContainer.java:216)
        at com.sun.enterprise.admin.cli.CLIContainer.getLocalCommand(CLIContainer.java:254)
        at com.sun.enterprise.admin.cli.CLICommand.getCommand(CLICommand.java:231)
        at com.sun.enterprise.admin.cli.AdminMain.executeCommand(AdminMain.java:370)
        at com.sun.enterprise.admin.cli.AdminMain.doMain(AdminMain.java:305)
        at org.glassfish.admin.cli.AsadminMain.main(AsadminMain.java:56)

## Expected Outcome

payaradomain should work on Java 9

## Current Outcome

NullPointerException

## Environment ##

- **Payara Version**: payara-5.0.0.Alpha4-20171207.004701-41
- **Edition**: Full
- **JDK Version**: Java 9.0.1
- **Operating System**: Windows
- **Database**: N/a

**Comment by Cousjava** [comment]
Thank you for reporting this, internal issue number for JDK9 support is PAYARA-579.

**Comment by smillidge** [comment]
Jdk 9 is not an LTS Java version so we haven't decided whether to formally support it in Payara 5

**Comment by smillidge** [comment]
Closed as Duplicate.
