### ISSUE TITLE
Repeated NPE printed to console with Payara Micro after sitting idle

### ISSUE THREAD

**Issue by marcreichman** [payara/Payara#2258]
# Description #
----------

I'm seeing a situation with Payara Micro 174 (have not tried full or other profiles), where after an app is running for a while, with no trouble in the application, I get this repeated log message printed to the console, every 2 seconds:
```
[2018-01-12T08:12:55.301-0600] [] [SEVERE] [] [] [tid: _ThreadID=103 _ThreadName=AutoDeployer] [timeMillis: 1515766375301] [levelValue: 1000] [[
  NCLS-DEPLOYMENT-00040
java.lang.NullPointerException
]]

[2018-01-12T08:12:57.302-0600] [] [SEVERE] [] [] [tid: _ThreadID=103 _ThreadName=AutoDeployer] [timeMillis: 1515766377302] [levelValue: 1000] [[
  NCLS-DEPLOYMENT-00040
java.lang.NullPointerException
]]
```

My deployment is a war file, and my only two command-line options to payara micro are `--deploy mywar.war --port myport`.

This is running on JDK 1.8.0_144 at the moment, but I've seen it in the past on other versions as well.

*Most importantly* This doesn't seem to happen until the app is running for several hours unattended.

### Samples

https://github.com/marcreichman/payara-micro-npe-sample

## Context (Optional)

Just trying to avoid error noise to the log

## Environment ##

- **Payara Version**: 4.1.2.174
- **Edition**: Micro
- **JDK Version**: 8u144
- **Operating System**: Windows (testing Linux)
- **Database**: n/a

**Comment by marcreichman** [comment]
Just a small update. I can only get this to happen in Windows.

**Comment by smillidge** [comment]
Thanks for the information we'll take a look.

**Comment by marcreichman** [comment]
I just experienced this again today with a Payara Micro 5.183 instance which has been deployed/running (on Windows) for 24h or so. The console rolled unfortunately so I don't have the start, but here are some samples:

```[2019-03-26T08:09:37.501-0500] [] [SEVERE] [] [] [tid: _ThreadID=54 _ThreadName=AutoDeployer] [timeMillis: 1553605777501] [levelValue: 1000] [[
  NCLS-DEPLOYMENT-00040
java.lang.NullPointerException
]]

[2019-03-26T08:09:39.502-0500] [] [SEVERE] [] [] [tid: _ThreadID=54 _ThreadName=AutoDeployer] [timeMillis: 1553605779502] [levelValue: 1000] [[
  NCLS-DEPLOYMENT-00040
java.lang.NullPointerException
]]

[2019-03-26T08:09:41.502-0500] [] [SEVERE] [] [] [tid: _ThreadID=54 _ThreadName=AutoDeployer] [timeMillis: 1553605781502] [levelValue: 1000] [[
  NCLS-DEPLOYMENT-00040
java.lang.NullPointerException
]]```

Different application than last time, JDK is 8u171, command line is just `--disablephonehome --deploy build/libs/myapp.war --port 8246`

**Comment by smillidge** [comment]
Please try Payara 5 and see if it is still a problem there.

**Comment by marcreichman** [comment]
Hi @smillidge -- I apologize if there was any ambiguity. The most recent was with 5.

Thanks!

Marc

**Comment by smillidge** [comment]
yes sorry missed that.

**Comment by marmots** [comment]
I'm getting this exact problem running 
- payara-micro 5.192 
- zulu8 jdk on 
- windows server 2016

```
[2019-06-13T08:57:08.684+0200] [] [[1;91mGRAVE[0m] [] [[1;94m[0m] [tid: _ThreadID=32 _ThreadName=payara-executor-service-scheduled-task] [timeMillis: 1560409028684] [levelValue: 1000] [[
  NCLS-DEPLOYMENT-00040
java.lang.NullPointerException
        at org.glassfish.deployment.autodeploy.AutoDeployDirectoryScanner.getListOfFilesAsSet(AutoDeployDirectoryScanner.java:182)
        at org.glassfish.deployment.autodeploy.AutoDeployedFilesManager.getFilesForUndeployment(AutoDeployedFilesManager.java:245)
        at org.glassfish.deployment.autodeploy.AutoDeployDirectoryScanner.getAllFilesForUndeployment(AutoDeployDirectoryScanner.java:136)
        at org.glassfish.deployment.autodeploy.AutoDeployer.undeployAll(AutoDeployer.java:467)
        at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:372)
        at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:362)
        at org.glassfish.deployment.autodeploy.AutoDeployService$1.run(AutoDeployService.java:231)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

after a long time unnattended it starts throwing this exception every some seconds and stops working.

i've tested with some microservices, also those running perfectly in our linux environment and they also end with this exception.

Don't know if it's better create a new issue or continue with this one (sorry if I decide the wrong option)

Thanks,

**Comment by smillidge** [comment]
This one is closed because code has been merged to master. You could try a nightly build as that should contain the fix. https://www.payara.fish/software/downloads/pre-release-builds/

**Comment by marmots** [comment]
Started with nightly build, sunday morning i will tell you. Thanks and have a good weekend
