### ISSUE TITLE
Adding a @Observes @Initialized(ApplicationScoped.class) CDI observer to a JSF backing bean causes @EJB injection to fail in the same

### ISSUE THREAD

**Issue by krichter722** [payara/Payara#2281]
# Description #
----------

Adding

    public void initEagerly( @Observes @Initialized( ApplicationScoped.class ) Object init ) {
        init();
    }

to a `@Named` JSF backing bean causes its `@PostConstruct` method to be invoked when `@EJB` aren't set, i.e. `null`.

## Expected Outcome

I'm not a Java EE expert, but afaik `@PostConstruct` methods always should guarantee that `@EJB` fields are initialized when invoked.

## Current Outcome

If the `@EJB` reference is used in the `@PostConstruct` method `NullPointerException` with stacktrace

```
SCHWERWIEGEND:   Exception while loading the app
SCHWERWIEGEND:   Undeployment failed for context /payara-no-valid-ee-environment-web
SCHWERWIEGEND:   Exception while loading the app : CDI deployment failure:WELD-000049: Unable to invoke private void richtercloud.payara.no.valid.ee.environment.web.Init.init() on richtercloud.payara.no.valid.ee.environment.web.Init@2102abc3
org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke private void richtercloud.payara.no.valid.ee.environment.web.Init.init() on richtercloud.payara.no.valid.ee.environment.web.Init@2102abc3
	at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:99)
	at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.postConstruct(DefaultLifecycleCallbackInvoker.java:80)
	at org.jboss.weld.injection.producer.BasicInjectionTarget.postConstruct(BasicInjectionTarget.java:122)
	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:172)
	at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
	at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:140)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:67)
	at org.jboss.weld.event.ObserverMethodImpl.getReceiver(ObserverMethodImpl.java:329)
	at org.jboss.weld.event.ObserverMethodImpl.getReceiverIfExists(ObserverMethodImpl.java:316)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:274)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:255)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:269)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:258)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:154)
	at org.jboss.weld.bootstrap.BeanDeploymentModule.fireEvent(BeanDeploymentModule.java:94)
	at org.jboss.weld.bootstrap.WeldStartup.endInitialization(WeldStartup.java:549)
	at org.jboss.weld.bootstrap.WeldBootstrap.endInitialization(WeldBootstrap.java:97)
	at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:262)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:333)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:497)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:508)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:544)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:540)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:570)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:562)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:561)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1469)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1851)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1727)
	at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:534)
	at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:224)
	at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:189)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:483)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:180)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:97)
	... 59 more
Caused by: java.lang.NullPointerException
	at richtercloud.payara.no.valid.ee.environment.web.Init.init(Init.java:30)
	... 64 more
```

occur, for example.

The reference seems to be never injected (assuming that it makes sense to do an ugly workaround and start a thread which periodically checks the reference value and sleeps) and thus remain `null` forever.

## Steps to reproduce (Only for bug reports) 

1 - ** Build the [SSCCE](https://gitlab.com/krichter/payara-no-valid-ee-environment) with `mvn install`

2 -**  Start the domain

    ./asadmin start-domain payaradomain

3 -**  Deploy the EAR created in the build

### Samples

see SSCCE link above

## Context (Optional)

I was testing this approach in order to make an application scoped JSF backing bean loader eagerly as described at https://stackoverflow.com/questions/3600534/how-do-i-force-an-application-scoped-bean-to-instantiate-at-application-startup.

## Environment ##

- **Payara Version**: 4.1.2.174
- **Edition**: Full
- **JDK Version**: 8 u151 - OpenJDK
- **Operating System**: Ubuntu 17.10
- **Database**: None

**Comment by smillidge** [comment]
Please try Payara 5 and see if it is still a problem there.

**Comment by rdebusscher** [comment]
Hi,

I tried to reproduce this on Payara 5.194, with the following code and there is no issue with injecting EJB. (no nullpointer and both messages in the log can be found during startup)

```
@ApplicationScoped
@Named
public class HelloBean {

    @EJB
    private DemoService demoService;

    @PostConstruct
    public void init() {
        System.out.println("From PostConstruct ");
        demoService.doSomething();
    }

    public void initEagerly(@Observes @Initialized(ApplicationScoped.class) Object init) {
        System.out.println("From Initialized ");
        demoService.doSomething();
    }
```

If you encounter still this issue, please make a small reproducer to demonstrate the problem and we will have a look at it.

Regards
Rudy
