### ISSUE TITLE
Upgrade Guava due to NoSuchMethodError during Arquillian Drone Test

### ISSUE THREAD

**Issue by aweinitschke** [payara/Payara#2287]
# Description #
----------

I have encountered a problem by using the maven artifact:

```xml
<dependency>
            <groupId>fish.payara.arquillian</groupId>
            <artifactId>arquillian-payara-server-4-embedded</artifactId>
            <version>1.0.Beta2</version>
            <scope>test</scope>
</dependency>
```

While using Arquillian Drone. 
The `com.google.guava` dependency seems to be deprecated, due to the selenium WebDriver for Chrome cannot resolve the Method `ImmutableList.toImmutableList()` from Class `<ChromeOptions>` which is using the payara libraries.

### The TestClass:

```java
package com.example.hello;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.container.test.api.RunAsClient;
import org.jboss.arquillian.drone.api.annotation.Drone;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.arquillian.test.api.ArquillianResource;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.asset.EmptyAsset;
import org.jboss.shrinkwrap.api.spec.JavaArchive;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.openqa.selenium.WebDriver;

import javax.inject.Inject;
import java.net.URL;

import static org.junit.Assert.assertEquals;


@RunWith(Arquillian.class)
public class GreeterTest {

    @Drone
    private WebDriver browser;

    @ArquillianResource
    private URL deploymentUrl;


    @Deployment
    public static JavaArchive createDeployment() {
        return ShrinkWrap.create(JavaArchive.class)
                .addClass(Greeter.class)
                .addAsManifestResource(EmptyAsset.INSTANCE, "beans.xml");
    }

    @Inject
    Greeter greeter;

    @Test
    public void greet() throws Exception {
        String name="Arquillian";
        assertEquals("Hello, Arquillian!", greeter.createGreeting(name));
        greeter.greet(System.out, name);
    }

    @Test
    @RunAsClient
    public void testMixedMode(){
        browser.get("http://google.de");
        String pageTitle = browser.getTitle();

        assertEquals("Google", pageTitle);
    }
}
```

### Arquillian.xml

```xml
<arquillian xmlns="http://jboss.org/schema/arquillian"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://jboss.org/schema/arquillian
            http://jboss.org/schema/arquillian/arquillian_1_0.xsd">

    <container qualifier="glassfish-managed">
        <configuration>
            <property name="debug">true</property>
        </configuration>
    </container>
    <extension qualifier="webdriver">
        <property name="browser">chrome</property>
        <property name="chromeDriverBinary">path/to/WebDriver/chromedriver_win32/chromedriver.exe</property>
    </extension>
</arquillian>
```

### POM

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>groupId</groupId>
    <artifactId>HelloArquillian</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.jboss.arquillian</groupId>
                <artifactId>arquillian-bom</artifactId>
                <version>1.2.0.Final</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>org.jboss.arquillian.selenium</groupId>
                <artifactId>selenium-bom</artifactId>
                <version>3.8.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>23.6-jre</version>
            </dependency>
            <dependency>
                <groupId>org.jboss.arquillian.extension</groupId>
                <artifactId>arquillian-drone-bom</artifactId>
                <version>2.5.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <version>7.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.arquillian.junit</groupId>
            <artifactId>arquillian-junit-container</artifactId>
            <version>1.2.0.Final</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>fish.payara.arquillian</groupId>
            <artifactId>arquillian-payara-server-4-embedded</artifactId>
            <version>1.0.Beta2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>fish.payara.extras</groupId>
            <artifactId>payara-embedded-all</artifactId>
            <version>4.1.153</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <artifactId>com.google.guava</artifactId>
                    <groupId>guava</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.jboss.arquillian.graphene</groupId>
            <artifactId>graphene-webdriver</artifactId>
            <version>2.1.0.Final</version>
            <type>pom</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>xml-apis</groupId>
            <artifactId>xml-apis</artifactId>
            <version>1.4.01</version>
        </dependency>

        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>3.14</version>
        </dependency>
        <dependency>
            <groupId>org.jboss.shrinkwrap.resolver</groupId>
            <artifactId>shrinkwrap-resolver-impl-maven</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>
</project>
```

## Expected Outcome

The Test was designed to succeed.

## Current Outcome

```
Jan 17, 2018 9:53:51 AM org.openqa.selenium.remote.DesiredCapabilities chrome
INFORMATION: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
Jan 17, 2018 9:53:51 AM org.openqa.selenium.remote.DesiredCapabilities chrome
INFORMATION: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`

java.lang.RuntimeException: com.google.common.collect.ImmutableList.toImmutableList()Ljava/util/stream/Collector;
. . . . .
. . . . . 
Caused by: java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.toImmutableList()Ljava/util/stream/Collector;
	at org.openqa.selenium.chrome.ChromeOptions.asMap(ChromeOptions.java:298)
	at org.openqa.selenium.MutableCapabilities.merge(MutableCapabilities.java:74)
	at org.openqa.selenium.remote.DesiredCapabilities.merge(DesiredCapabilities.java:107)
	at org.openqa.selenium.remote.DesiredCapabilities.merge(DesiredCapabilities.java:33)
	at org.openqa.selenium.MutableCapabilities.setCapability(MutableCapabilities.java:97)
	at org.jboss.arquillian.drone.webdriver.factory.ChromeDriverFactory.setChromeOptions(ChromeDriverFactory.java:132)
	at org.jboss.arquillian.drone.webdriver.factory.ChromeDriverFactory.getCapabilities(ChromeDriverFactory.java:115)
	at org.jboss.arquillian.drone.webdriver.factory.ChromeDriverFactory.createInstance(ChromeDriverFactory.java:80)
	at org.jboss.arquillian.drone.webdriver.factory.ChromeDriverFactory.createInstance(ChromeDriverFactory.java:42)
	at org.jboss.arquillian.drone.webdriver.factory.WebDriverFactory.createInstance(WebDriverFactory.java:127)
	at org.jboss.arquillian.drone.webdriver.factory.WebDriverFactory.createInstance(WebDriverFactory.java:38)
	at org.jboss.arquillian.drone.impl.DroneConfigurator$1.createInstance(DroneConfigurator.java:112)
	at org.jboss.arquillian.drone.impl.CachingCallableImpl.call(CachingCallableImpl.java:44)
	at org.jboss.arquillian.core.impl.threading.ThreadedExecutorService$ContextualCallable.call(ThreadedExecutorService.java:88)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

## Steps to reproduce (Only for bug reports) 

1 -** Create the Arquillian-Test using the Tutorial http://arquillian.org/guides/getting_started/ 
2 -** Advance it by using Drone http://arquillian.org/guides/functional_testing_using_graphene/
3 -** Import the Project-independent Test-Method from the Description
4 -** Run the mixed-Mode arquillian Test

## Environment ##

- **Payara Version**: 4.1.153
- **Edition**: Embedded
- **JDK Version**: Oracle 1.8.0_144
- **Operating System**: Windows 10
- **Database**: None

**Comment by smillidge** [comment]
Have you thought about trying a later version of Payara as 153 is over two years old. Try 4.1.1.174 as a dependency.

**Comment by aweinitschke** [comment]
Thanks for reply, 
Its the same problem for this version of payara.
I've had a look at the repository for this version(and the current master) and the guava dependency versions are in range from 18-19 and should be at least 21. 
I will try to update those dependencies and will keep you in track.
