### ISSUE TITLE
ManagedExecutorService does not execute tasks when enabling application.

### ISSUE THREAD

**Issue by otukatigayim** [payara/Payara#2305]
# Description #
----------

ManagedExecutorService does not execute tasks when enabling application.

## Expected Outcome

ManagedExecutorService execute tasks when enabling application.

## Current Outcome

ManagedExecutorService does not execute tasks when enabling application.

## Steps to reproduce (Only for bug reports) 

1. Build the following Appilication. ``mvn clean package``
  https://github.com/otukatigayim/payara-test-app
1. Deploy application. ``bin/asadmin deploy --contextroot=test-app --name=test-app --virtualservers=server test-app.war``
  -> MyTask was executed.
1. Disable application with asadmin. ``bin/asadmin disable test-app``
1. Enable application with asadmin. ``bin/asadmin enable test-app``
  -> MyTask was not executed.

## Environment ##

- **Payara Version**: payara-5.Beta1
- **Edition**: Full
- **JDK Version**: Oracle JDK 1.8.0_151
- **Operating System**: Windows 7 64bit
- **Database**: none

**Comment by michaelranaldo** [comment]
Hi @otukatigayim ,

Thanks for reporting this issue. I've not been able to reproduce the error - would you please be able to post the error generated in the server log?

**Comment by afrunt** [comment]
@michaelranaldo it looks similar to https://github.com/payara/Payara/issues/2302

**Comment by otukatigayim** [comment]
Hi @michaelranaldo,

Thanks for investigating. No error was generated in server log. But MyTask was not run.
I investigated and found that MyTask was aborted, so i added MyTaskListener as follows.
- https://github.com/otukatigayim/payara-test-app/pull/1/files

And i got the following log.
1. Deploy an application.
```
[2018-01-24T13:05:29.491+0900] [Payara 5..Beta1] [INFO] [] [] [tid: _ThreadID=46 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1516766729491] [levelValue: 800] [[
  Cannot find the resource bundle for the name com.sun.logging.enterprise.system.core.naming for class org.glassfish.concurrent.runtime.deployer.ConcurrentObjectFactory using org.glassfish.main.concurrent.impl [40]]]

[2018-01-24T13:05:29.564+0900] [Payara 5..Beta1] [INFO] [jsf.config.listener.version] [javax.enterprise.resource.webcontainer.jsf.config] [tid: _ThreadID=46 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1516766729564] [levelValue: 800] [[
  Initializing Mojarra 2.4.0-m01-SNAPSHOT for context '/test-app']]

[2018-01-24T13:05:30.284+0900] [Payara 5..Beta1] [INFO] [] [] [tid: _ThreadID=46 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1516766730284] [levelValue: 800] [[
  MyTaskListener#taskSubmitted]]

[2018-01-24T13:05:30.286+0900] [Payara 5..Beta1] [INFO] [] [javax.enterprise.concurrent] [tid: _ThreadID=163 _ThreadName=concurrent/__defaultManagedExecutorService-managedThreadFactory-Thread-1] [timeMillis: 1516766730286] [levelValue: 800] [[
  Job submitted for test-app likely during deployment. Continuing...]]

[2018-01-24T13:05:30.288+0900] [Payara 5..Beta1] [INFO] [] [] [tid: _ThreadID=163 _ThreadName=concurrent/__defaultManagedExecutorService-managedThreadFactory-Thread-1] [timeMillis: 1516766730288] [levelValue: 800] [[
  MyTaskListener#taskStarting]]

[2018-01-24T13:05:30.288+0900] [Payara 5..Beta1] [INFO] [] [] [tid: _ThreadID=163 _ThreadName=concurrent/__defaultManagedExecutorService-managedThreadFactory-Thread-1] [timeMillis: 1516766730288] [levelValue: 800] [[
  [TASK:RUN] MyTask#run]]

[2018-01-24T13:05:30.288+0900] [Payara 5..Beta1] [INFO] [] [] [tid: _ThreadID=163 _ThreadName=concurrent/__defaultManagedExecutorService-managedThreadFactory-Thread-1] [timeMillis: 1516766730288] [levelValue: 800] [[
  MyTaskListener#taskDone]]

[2018-01-24T13:05:30.299+0900] [Payara 5..Beta1] [INFO] [AS-WEB-GLUE-00172] [javax.enterprise.web] [tid: _ThreadID=46 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1516766730299] [levelValue: 800] [[
  Loading application [test-app] at [/test-app]]]

[2018-01-24T13:05:30.392+0900] [Payara 5..Beta1] [INFO] [] [javax.enterprise.system.core] [tid: _ThreadID=46 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1516766730392] [levelValue: 800] [[
  test-app was successfully deployed in 2,558 milliseconds.]]

[2018-01-24T13:07:10.708+0900] [Payara 5..Beta1] [INFO] [jsf.config.listener.version] [javax.enterprise.resource.webcontainer.jsf.config] [tid: _ThreadID=46 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1516766830708] [levelValue: 800] [[
  Initializing Mojarra 2.4.0-m01-SNAPSHOT for context '/test-app']]
```
2. Disable an application.
3. Enable an application.
```
[2018-01-24T13:07:10.841+0900] [Payara 5..Beta1] [INFO] [] [] [tid: _ThreadID=46 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1516766830841] [levelValue: 800] [[
  MyTaskListener#taskSubmitted]]

[2018-01-24T13:07:10.842+0900] [Payara 5..Beta1] [INFO] [] [] [tid: _ThreadID=188 _ThreadName=concurrent/__defaultManagedExecutorService-managedThreadFactory-Thread-2] [timeMillis: 1516766830842] [levelValue: 800] [[
  MyTaskListener#taskStarting]]

[2018-01-24T13:07:10.842+0900] [Payara 5..Beta1] [INFO] [] [] [tid: _ThreadID=188 _ThreadName=concurrent/__defaultManagedExecutorService-managedThreadFactory-Thread-2] [timeMillis: 1516766830842] [levelValue: 800] [[
  MyTaskListener#taskAborted]]

[2018-01-24T13:07:10.844+0900] [Payara 5..Beta1] [SEVERE] [] [] [tid: _ThreadID=188 _ThreadName=concurrent/__defaultManagedExecutorService-managedThreadFactory-Thread-2] [timeMillis: 1516766830844] [levelValue: 1000] [[
  javax.enterprise.concurrent.AbortedException: Module test-app is disabled
	at org.glassfish.enterprise.concurrent.internal.ManagedFutureTask.run(ManagedFutureTask.java:146)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)
]]

[2018-01-24T13:07:10.844+0900] [Payara 5..Beta1] [INFO] [] [] [tid: _ThreadID=188 _ThreadName=concurrent/__defaultManagedExecutorService-managedThreadFactory-Thread-2] [timeMillis: 1516766830844] [levelValue: 800] [[
  MyTaskListener#taskDone]]

[2018-01-24T13:07:10.862+0900] [Payara 5..Beta1] [INFO] [AS-WEB-GLUE-00172] [javax.enterprise.web] [tid: _ThreadID=46 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1516766830862] [levelValue: 800] [[
  Loading application [test-app] at [/test-app]]]
```

**Comment by michaelranaldo** [comment]
Hi @otukatigayim 

Thanks for adding that pr, I can confirm that I have been able to reproduce the issue. There also appears to be an associated issue when using the commands via the console.
Created internal issues PAYARA-2422 and PAYARA-2430.
