### ISSUE TITLE
Payara 5 Beta 2 cannot run on Google Kubernetes

### ISSUE THREAD

**Issue by blono** [payara/Payara#2360]
# Description #
----------

Payara 5 Beta 2 won't start on Googke Kubernetes.

## Expected Outcome

--host,,,localhost,,,--port,,,4848,,,--secure=false,,,--terse=false,,,--echo=false,,,--interactive=true,,,start-domain,,,--verbose=true,,,--watchdog=false,,,--debug=false,,,--domaindir,,,/var/payara/payara5/glassfish/domains,,,domain1
-domainname
domain1
-instancename
server
-type
DAS
-verbose
true
-asadmin-classpath
/var/payara/payara5/glassfish/modules/admin-cli.jar
-debug
false
-asadmin-classname
com.sun.enterprise.admin.cli.AdminMain
-watchdog
false
Launching Payara Server on Felix platform
Feb 02, 2018 11:30:01 PM com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner createBundleProvisioner
INFO: Create bundle provisioner class = class com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner.
Registered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishRuntime@7e4cb579 in service registry.

#!## LogManagerService.postConstruct : rootFolder=/var/payara/payara5/glassfish
#!## LogManagerService.postConstruct : templateDir=/var/payara/payara5/glassfish/lib/templates
#!## LogManagerService.postConstruct : src=/var/payara/payara5/glassfish/lib/templates/logging.properties
#!## LogManagerService.postConstruct : dest=/var/payara/payara5/glassfish/domains/domain1/config/logging.properties

## Current Outcome

--host,,,localhost,,,--port,,,4848,,,--secure=false,,,--terse=false,,,--echo=false,,,--interactive=false,,,start-domain,,,--verbose=true,,,--watchdog=false,,,--debug=false,,,--domaindir,,,/var/payara/payara5/glassfish/domains,,,domain1
-domainname
domain1
-instancename
server
-type
DAS
-verbose
true
-asadmin-classpath
/var/payara/payara5/glassfish/modules/admin-cli.jar
-debug
false
-asadmin-classname
com.sun.enterprise.admin.cli.AdminMain
-watchdog
false
Launching Payara Server on Felix platform
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:104)
	at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:54)
Caused by: org.glassfish.embeddable.GlassFishException: java.lang.IllegalArgumentException: invalid version "4.4.86.": invalid format
	at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishRuntimeBuilder.build(OSGiGlassFishRuntimeBuilder.java:170)
	at org.glassfish.embeddable.GlassFishRuntime._bootstrap(GlassFishRuntime.java:157)
	at org.glassfish.embeddable.GlassFishRuntime.bootstrap(GlassFishRuntime.java:110)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:121)
	... 6 more
Caused by: java.lang.IllegalArgumentException: invalid version "4.4.86.": invalid format
	at org.osgi.framework.Version.<init>(Version.java:147)
	at org.apache.felix.framework.util.manifestparser.NativeLibraryClause.normalizeOSVersion(NativeLibraryClause.java:770)
	at org.apache.felix.framework.Felix.initializeFrameworkProperties(Felix.java:4617)
	at org.apache.felix.framework.Felix.<init>(Felix.java:384)
	at org.apache.felix.framework.FrameworkFactory.newFramework(FrameworkFactory.java:28)
	at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiFrameworkLauncher.launchOSGiFrameWork(OSGiFrameworkLauncher.java:80)
	at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishRuntimeBuilder.build(OSGiGlassFishRuntimeBuilder.java:130)
	... 9 more
Caused by: java.util.NoSuchElementException
	at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
	at java.util.StringTokenizer.nextToken(StringTokenizer.java:377)
	at org.osgi.framework.Version.<init>(Version.java:138)
	... 15 more
Error stopping framework: java.lang.NullPointerException
java.lang.NullPointerException
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher$1.run(GlassFishMain.java:209)
Command start-domain failed.
The DAS was stopped.

## Steps to reproduce (Only for bug reports) 

Just run Payara 5 beta 2(payara5/glassfish/bin/startserv) on Google Kubernetes.

## Context (Optional)

Felix v5.6.6 has a bug in parsing os version.
https://issues.apache.org/jira/browse/FELIX-5672
https://luceeserver.atlassian.net/browse/LDEV-1597

I replaced payara5/glassfish/osgi/felix/bin/felix.jar with Felix v5.6.10 and confirmed no error occurs.

## Environment ##

- **Payara Version**: Payara 5 Beta 2
- **Edition**: Full
- **JDK Version**: jdk8u152
- **Operating System**: Linux
- **Database**:

**Comment by mikecroft** [comment]
Hi @blono - do you have a simple test case (like a Kubernetes YAML file) that we can use to reproduce the error?

**Comment by smillidge** [comment]
We'll do the Felix upgrade prior to the 5 final release
