### ISSUE TITLE
Unable to Create Uber Jar With MQTT Rar 4.1.2.172 or Later 

### ISSUE THREAD

**Issue by oxley-calabrio** [payara/Payara#2438]
# Description #
----------

See #2437 for additional background information.  I tried creating an Uber jar based on http://blog.payara.fish/payara-micro-jca-adapters-mqtt and it did not work.  I am able to use Payara Micro when I invoke outside the uber jar --deploy mqtt-rar and --deploy mywar.war.

This works:
`java -jar payara-micro.jar --autobindhttp --deploy mqtt-rar.rar --deploy mywar.war`

`java -jar payara-micro.jar --autobindhttp --deploy mqtt-rar.rar --deploy mywar.war --outputUberjar dist.jar`
then
`java -jar dist.jar` 
does not work.
 

## Expected Outcome

I should be able to output an Uber Jar with the MQTT Cloud Connectors and start up Payara Micro as I normally would be able to.

## Current Outcome

I tried with various switches and combinations of including jars in question and --nested flag but to no avail.  Here is a stacktrace to my current outcome:

>[2018-02-21T16:45:03.467-0600] [] [WARNING] [] [javax.enterprise.system.tools.deployment.dol] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1519253103467] [levelValue: 900] [[
  AS-DEPLOYMENT-00011
java.lang.NoClassDefFoundError: fish/payara/cloud/connectors/mqtt/api/MQTTListener
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at org.glassfish.web.loader.WebappClassLoader.findClass(WebappClassLoader.java:1089)
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1620)
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1501)
        at com.sun.enterprise.deployment.annotation.impl.ModuleScanner.getElements(ModuleScanner.java:297)
        at com.sun.enterprise.deployment.archivist.Archivist.processAnnotations(Archivist.java:586)
        at org.glassfish.web.embed.impl.EmbeddedWebArchivist.processAnnotations(EmbeddedWebArchivist.java:144)
        at com.sun.enterprise.deployment.archivist.Archivist.readAnnotations(Archivist.java:463)
        at com.sun.enterprise.deployment.archivist.Archivist.readAnnotations(Archivist.java:447)
        at com.sun.enterprise.deployment.archivist.Archivist.readRestDeploymentDescriptors(Archivist.java:419)
        at com.sun.enterprise.deployment.archivist.Archivist.readDeploymentDescriptors(Archivist.java:396)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:271)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:280)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:241)
        at com.sun.enterprise.deployment.archivist.ApplicationFactory.openArchive(ApplicationFactory.java:161)
        at org.glassfish.javaee.core.deployment.DolProvider.processDOL(DolProvider.java:199)
        at org.glassfish.javaee.core.deployment.DolProvider.load(DolProvider.java:223)
        at org.glassfish.javaee.core.deployment.DolProvider.load(DolProvider.java:91)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.loadDeployer(ApplicationLifecycle.java:882)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.setupContainerInfos(ApplicationLifecycle.java:822)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:378)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:487)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
        at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:134)
        at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:149)
        at fish.payara.micro.impl.PayaraMicroImpl.deployAll(PayaraMicroImpl.java:1346)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:985)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:181)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:79)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:358)
Caused by: java.lang.ClassNotFoundException: fish.payara.cloud.connectors.mqtt.api.MQTTListener
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1655)
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1501)
        ... 53 more
]]

[2018-02-21T16:45:03.497-0600] [] [WARNING] [] [javax.enterprise.system.tools.deployment.dol] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1519253103497] [levelValue: 900] [[
  AS-DEPLOYMENT-00011
java.lang.NoClassDefFoundError: fish/payara/cloud/connectors/mqtt/api/MQTTListener
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at org.glassfish.web.loader.WebappClassLoader.findClass(WebappClassLoader.java:1089)
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1620)
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1501)
        at com.sun.enterprise.deployment.annotation.impl.ModuleScanner.getElements(ModuleScanner.java:297)
        at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:133)
        at com.sun.enterprise.deployment.archivist.Archivist.processAnnotations(Archivist.java:627)
        at org.glassfish.web.embed.impl.EmbeddedWebArchivist.processAnnotations(EmbeddedWebArchivist.java:144)
        at com.sun.enterprise.deployment.archivist.Archivist.readAnnotations(Archivist.java:463)
        at com.sun.enterprise.deployment.archivist.Archivist.readAnnotations(Archivist.java:447)
        at com.sun.enterprise.deployment.archivist.Archivist.readRestDeploymentDescriptors(Archivist.java:419)
        at com.sun.enterprise.deployment.archivist.Archivist.readDeploymentDescriptors(Archivist.java:396)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:271)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:280)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:241)
        at com.sun.enterprise.deployment.archivist.ApplicationFactory.openArchive(ApplicationFactory.java:161)
        at org.glassfish.javaee.core.deployment.DolProvider.processDOL(DolProvider.java:199)
        at org.glassfish.javaee.core.deployment.DolProvider.load(DolProvider.java:223)
        at org.glassfish.javaee.core.deployment.DolProvider.load(DolProvider.java:91)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.loadDeployer(ApplicationLifecycle.java:882)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.setupContainerInfos(ApplicationLifecycle.java:822)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:378)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:487)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
        at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:134)
        at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:149)
        at fish.payara.micro.impl.PayaraMicroImpl.deployAll(PayaraMicroImpl.java:1346)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:985)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:181)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:79)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:358)
Caused by: java.lang.ClassNotFoundException: fish.payara.cloud.connectors.mqtt.api.MQTTListener
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1655)
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1501)
        ... 54 more
]]

[2018-02-21T16:45:03.542-0600] [] [SEVERE] [] [global] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1519253103542] [levelValue: 1000] Class [ Lfish/payara/cloud/connectors/mqtt/api/MQTTConnectionFactory; ] not found. Error while loading [ class com.calabrio.research.microservices.payara.MQTTSendMessage ]

[2018-02-21T16:45:03.549-0600] [] [WARNING] [] [javax.enterprise.system.tools.deployment.dol] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1519253103549] [levelValue: 900] [[
  AS-DEPLOYMENT-00011
java.lang.NoClassDefFoundError: fish/payara/cloud/connectors/mqtt/api/MQTTListener
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at org.glassfish.web.loader.WebappClassLoader.findClass(WebappClassLoader.java:1089)
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1620)
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1501)
        at com.sun.enterprise.deployment.annotation.impl.ModuleScanner.getElements(ModuleScanner.java:297)
        at com.sun.enterprise.deployment.archivist.Archivist.processAnnotations(Archivist.java:586)
        at org.glassfish.web.embed.impl.EmbeddedWebArchivist.processAnnotations(EmbeddedWebArchivist.java:144)
        at com.sun.enterprise.deployment.archivist.Archivist.readAnnotations(Archivist.java:478)
        at com.sun.enterprise.deployment.archivist.Archivist.readAnnotations(Archivist.java:447)
        at com.sun.enterprise.deployment.archivist.Archivist.readRestDeploymentDescriptors(Archivist.java:419)
        at com.sun.enterprise.deployment.archivist.Archivist.readDeploymentDescriptors(Archivist.java:396)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:271)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:280)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:241)
        at com.sun.enterprise.deployment.archivist.ApplicationFactory.openArchive(ApplicationFactory.java:161)
        at org.glassfish.javaee.core.deployment.DolProvider.processDOL(DolProvider.java:199)
        at org.glassfish.javaee.core.deployment.DolProvider.load(DolProvider.java:223)
        at org.glassfish.javaee.core.deployment.DolProvider.load(DolProvider.java:91)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.loadDeployer(ApplicationLifecycle.java:882)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.setupContainerInfos(ApplicationLifecycle.java:822)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:378)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:487)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
        at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:134)
        at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:149)
        at fish.payara.micro.impl.PayaraMicroImpl.deployAll(PayaraMicroImpl.java:1346)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:985)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:181)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:79)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:358)
Caused by: java.lang.ClassNotFoundException: fish.payara.cloud.connectors.mqtt.api.MQTTListener
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1655)
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1501)
        ... 53 more
]]

[2018-02-21T16:45:03.551-0600] [] [WARNING] [] [javax.enterprise.system.tools.deployment.dol] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1519253103551] [levelValue: 900] [[
  AS-DEPLOYMENT-00011
java.lang.NoClassDefFoundError: fish/payara/cloud/connectors/mqtt/api/MQTTListener
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at org.glassfish.web.loader.WebappClassLoader.findClass(WebappClassLoader.java:1089)
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1620)
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1501)
        at com.sun.enterprise.deployment.annotation.impl.ModuleScanner.getElements(ModuleScanner.java:297)
        at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:133)
        at com.sun.enterprise.deployment.archivist.Archivist.processAnnotations(Archivist.java:627)
        at org.glassfish.web.embed.impl.EmbeddedWebArchivist.processAnnotations(EmbeddedWebArchivist.java:144)
        at com.sun.enterprise.deployment.archivist.Archivist.readAnnotations(Archivist.java:478)
        at com.sun.enterprise.deployment.archivist.Archivist.readAnnotations(Archivist.java:447)
        at com.sun.enterprise.deployment.archivist.Archivist.readRestDeploymentDescriptors(Archivist.java:419)
        at com.sun.enterprise.deployment.archivist.Archivist.readDeploymentDescriptors(Archivist.java:396)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:271)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:280)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:241)
        at com.sun.enterprise.deployment.archivist.ApplicationFactory.openArchive(ApplicationFactory.java:161)
        at org.glassfish.javaee.core.deployment.DolProvider.processDOL(DolProvider.java:199)
        at org.glassfish.javaee.core.deployment.DolProvider.load(DolProvider.java:223)
        at org.glassfish.javaee.core.deployment.DolProvider.load(DolProvider.java:91)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.loadDeployer(ApplicationLifecycle.java:882)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.setupContainerInfos(ApplicationLifecycle.java:822)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:378)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:487)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
        at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:134)
        at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:149)
        at fish.payara.micro.impl.PayaraMicroImpl.deployAll(PayaraMicroImpl.java:1346)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:985)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:181)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:79)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:358)
Caused by: java.lang.ClassNotFoundException: fish.payara.cloud.connectors.mqtt.api.MQTTListener
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1655)
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1501)
        ... 54 more
]]

## Steps to reproduce (Only for bug reports) 

Create a project based on this: http://blog.payara.fish/payara-micro-jca-adapters-mqtt (must use 4.1.172 Micro because later versions do not work)

package the project by issuing:
`java -jar payara-micro.jar --autobindhttp --deploy mqtt-rar.rar --deploy mywar.war --outputUberjar dist.jar

execute the uber jar:

`java -jar dist.jar`

## Environment ##

- **Payara Version**: 4.1.2.172
- **Edition**: Micro
- **JDK Version**: Java 8 b101
- **Operating System**: Windows

**Comment by mikecroft** [comment]
Have you made sure to get the `--deploy` commands in the correct order?

**Comment by oxley-calabrio** [comment]
My gradle script executes the commandLine as follows:
`java -jar payara-micro.jar --autobind --deploy mqtt --deploy myapp.war --output myapp.jar`

I will try outside of the gradle script.

**Comment by oxley-calabrio** [comment]
I confirmed outside my gradle script by executing the line posted above that is an issue.

**Comment by oxley-calabrio** [comment]
It looks like the uberjar did not deploy the mqtt rar.

**Comment by smillidge** [comment]
I can't reproduce on the latest 4.182-snapshot with the example application
``` 
java -jar payara-micro.jar --deploy mqtt-rar-0.2.0-SNAPSHOT.rar --deploy mqtt-example-0.2.0-SNAPSHOT.jar  --outputUberJar test.jar
```
Then the uber jar
```
java -jar test.jar
```

with output
```
[2018-02-22T16:48:27.457+0000] [] [INFO] [] [PayaraMicro] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1519318107457] [levelValue: 800] [[
  
Payara Micro URLs
http://steve-N130BU:8080mqtt-rar-0.2.0-SNAPSHOT
http://steve-N130BU:8080mqtt-example-0.2.0-SNAPSHOT

'mqtt-rar-0.2.0-SNAPSHOT' REST Endpoints
Application mqtt-rar-0.2.0-SNAPSHOT contains no web modules


'mqtt-example-0.2.0-SNAPSHOT' REST Endpoints
Application mqtt-example-0.2.0-SNAPSHOT contains no web modules

]]

[2018-02-22T16:48:27.457+0000] [] [INFO] [] [PayaraMicro] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1519318107457] [levelValue: 800] Payara Micro  4.1.2.182-SNAPSHOT #badassmicrofish (build ${build.number}) ready in 8,012 (ms)

Received message on topic test {"test": "Hello World"}
Received message on topic test {"test": "Hello World"}
```

**Comment by oxley-calabrio** [comment]
OOoh, good!  I am going to try it, right now.  I narrowed this issue down to a missing meta-inf/ra.xml file because when the archive is extracted, it does not recognize the extracted archive so it tries to locate that file:

`Payara/appserver/connectors/connectors-connector/src/main/java/com/sun/enterprise/connectors/connector/module/RarDetector.java`


Is there another rar release I need to pick up?
