### ISSUE TITLE
Payara 5.181-SNAPSHOT Embedded with arquillian won't start 

### ISSUE THREAD

**Issue by Henny-cz** [payara/Payara#2509]
# Description #
----------

I have **payara-embedded-all** version **5.181-SNAPSHOT**. 
**arquillian-payara-server-4-embedded** version **1.0.Beta2**
**arquillian-bom** version **1.3.0.Final**.

I have arquillian.xml : 
```xml
<arquillian xmlns="http://jboss.org/schema/arquillian"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://jboss.org/schema/arquillian http://jboss.org/schema/arquillian/arquillian_1_0.xsd">

    <container qualifier="glassfish-embedded" default="true">
        <configuration>
            <property name="bindHttpPort">7070</property>
            <property name="resourcesXml">src/test/resources/glassfish-resources.xml</property>
        </configuration>
    </container>

</arquillian>
```

and glassfish-resources.xml set to H2 database like this:

```xml
<resources>
    <jdbc-resource pool-name="IDM_test_mem"
        jndi-name="jboss/datasources/IDM_test_mem"/>

    <jdbc-connection-pool name="IDM_test_mem"
                          res-type="javax.sql.DataSource"
                          datasource-classname="org.h2.jdbcx.JdbcDataSource">
        <property name="user" value="sa"/>
        <property name="password" value="sa"/>
        <property name="url" value="jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS test"/>
    </jdbc-connection-pool>
</resources>
```

with my persistence.xml

```xml
<persistence-unit name="IDM_test_mem">

        <provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>
        <jta-data-source>jboss/datasources/IDM_test_mem</jta-data-source>
        <properties>
            <property name="hibernate.dialect" value="org.hibernate.dialect.H2Dialect" />
            <property name="hibernate.show_sql" value="false" /> 
            <property name="hibernate.format_sql" value="false"/> 
            <property name="hibernate.cache.use_second_level_cache" value="false" />
            <property name="hibernate.hbm2ddl.auto" value="create-drop"/>
            <property name="hibernate.enable_lazy_load_no_trans" value="true" />
        </properties>
</persistence-unit>
```

Using ShrinkWrap to create WebArchive

```java
@Deployment
    public static WebArchive createDeployment()
    {
        return ShrinkWrap.create(WebArchive.class, "testIDM.war")
                .addPackages(true, "cz.autocont.idm")
                //Resources
                .addAsWebInfResource("test-persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("beans.xml", "META-INF/beans.xml")
                .addAsResource("activiti.cfg.xml", "activiti.cfg.xml")
                .addAsWebInfResource("glassfish-resources.xml")
                .addAsManifestResource("META-INF/services/org.activiti.cdi.spi.ProcessEngineLookup", "services/org.activiti.cdi.spi.ProcessEngineLookup");

    }
```

## Expected Outcome

Server will start with JUNIT testing

## Current Outcome

SEVERE ERROR:

```txt
B�e 07, 2018 2:01:40 ODP. org.glassfish.kernel.event.EventsImpl send
WARNING: Exception while dispatching an event
org.glassfish.api.invocation.InvocationException
	at org.glassfish.api.invocation.InvocationManagerImpl.postInvoke(InvocationManagerImpl.java:178)
	at org.glassfish.weld.WeldDeployer.processApplicationLoaded(WeldDeployer.java:522)
	at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:426)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:333)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:493)
```

```txt
B�e 07, 2018 2:01:44 ODP. org.apache.catalina.core.ContainerBase addChildInternal
SEVERE: ContainerBase.addChild: start: 
org.apache.catalina.LifecycleException: java.lang.IllegalArgumentException: javax.servlet.ServletException: com.sun.enterprise.container.common.spi.util.InjectionException: Error creating managed object for class: class org.jboss.weld.module.web.servlet.WeldListener
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:5688)
	at com.sun.enterprise.web.WebModule.start(WebModule.java:609)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:956)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:939)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:684)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:2099)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1745)
```

```txt
Caused by: java.lang.IllegalArgumentException: javax.servlet.ServletException: com.sun.enterprise.container.common.spi.util.InjectionException: Error creating managed object for class: class org.jboss.weld.module.web.servlet.WeldListener
	at org.apache.catalina.core.StandardContext.addListener(StandardContext.java:3005)
	at org.apache.catalina.core.StandardContext.addApplicationListener(StandardContext.java:2200)
	at com.sun.enterprise.web.TomcatDeploymentConfig.configureApplicationListener(TomcatDeploymentConfig.java:236)
	at com.sun.enterprise.web.TomcatDeploymentConfig.configureWebModule(TomcatDeploymentConfig.java:95)
	at com.sun.enterprise.web.WebModuleContextConfig.start(WebModuleContextConfig.java:239)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:336)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:163)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:5685)
	... 122 more
Caused by: javax.servlet.ServletException: com.sun.enterprise.container.common.spi.util.InjectionException: Error creating managed object for class: class org.jboss.weld.module.web.servlet.WeldListener
	at org.apache.catalina.core.StandardContext.createListener(StandardContext.java:3126)
	at org.apache.catalina.core.StandardContext.loadListener(StandardContext.java:5208)
	at com.sun.enterprise.web.WebModule.loadListener(WebModule.java:1709)
	at org.apache.catalina.core.StandardContext.addListener(StandardContext.java:3003)
	... 129 more
Caused by: com.sun.enterprise.container.common.spi.util.InjectionException: Error creating managed object for class: class org.jboss.weld.module.web.servlet.WeldListener
	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl.createManagedObject(InjectionManagerImpl.java:298)
	at com.sun.enterprise.web.WebContainer.createListenerInstance(WebContainer.java:808)
	at com.sun.enterprise.web.WebModule.createListenerInstance(WebModule.java:2079)
	at org.apache.catalina.core.StandardContext.createListener(StandardContext.java:3124)
	... 132 more
Caused by: java.lang.NullPointerException
	at org.glassfish.weld.services.JCDIServiceImpl.createManagedObject(JCDIServiceImpl.java:463)
	at org.glassfish.weld.services.JCDIServiceImpl.createManagedObject(JCDIServiceImpl.java:314)
	at com.sun.enterprise.container.common.impl.managedbean.ManagedBeanManagerImpl.createManagedBean(ManagedBeanManagerImpl.java:476)
	at com.sun.enterprise.container.common.impl.managedbean.ManagedBeanManagerImpl.createManagedBean(ManagedBeanManagerImpl.java:429)
	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl.createManagedObject(InjectionManagerImpl.java:283)
	... 135 more
```

## Steps to reproduce (Only for bug reports) 

I'm sorry but I cannot provide any code and I know that it will probably close my ticket but it was worth a try

## Context (Optional)

JUNIT testing with arquillian and payara embbeded

## Environment ##

- **Payara Version**: 5.181-SNAPSHOT
- **Edition**:  
- **JDK Version**:  8
- **Operating System**:  Windows 10
- **Database**:  H2

**Comment by smillidge** [comment]
You persistence.xml references Hibernate. Payara uses EclipseLink.

Can you provide a test case if changing persistence.xml to Eclipse Link doesn't resolve things.

**Comment by Henny-cz** [comment]
I'm sorry but I can't. We are using Hibernate because EclipseLink is not compatible with our project. So I am not able to.

**Comment by smillidge** [comment]
I'm afraid we need a reproducible test case if you suspect a Payara bug.

Your shrinkwrap does not contain any hibernate jars. You could also try and run tests using our Arquillian connector for Payara Micro or Payara Server remote.

Alternatively you can raise on the Payara Fourm for community advice. 

Alternatively your company could purchase a support contract for assistance with getting Hibernate to work on Payara Embedded in your specific application. We do offer Project and Migration support.
