### ISSUE TITLE
Fail fast with a descriptive error on Java 9

### ISSUE THREAD

**Issue by ggam** [payara/Payara#2515]
I have Java 9 as my default version, so for running Payara I have to switch to JDK 8. I usually forget to switch the version so it tries to boot with JDK 9, and fails with an unexpected error:

```
[guillermo@localhost bin]$ ./asadmin start-domain production
Exception in thread "main" java.lang.NullPointerException
	at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.initializeServiceLocator(AbstractModulesRegistryImpl.java:152)
	at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.newServiceLocator(AbstractModulesRegistryImpl.java:144)
	at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.createServiceLocator(AbstractModulesRegistryImpl.java:218)
	at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.createServiceLocator(AbstractModulesRegistryImpl.java:224)
	at com.sun.enterprise.module.single.StaticModulesRegistry.createServiceLocator(StaticModulesRegistry.java:88)
	at com.sun.enterprise.admin.cli.CLIContainer.getServiceLocator(CLIContainer.java:216)
	at com.sun.enterprise.admin.cli.CLIContainer.getLocalCommand(CLIContainer.java:254)
	at com.sun.enterprise.admin.cli.CLICommand.getCommand(CLICommand.java:231)
	at com.sun.enterprise.admin.cli.AdminMain.executeCommand(AdminMain.java:370)
	at com.sun.enterprise.admin.cli.AdminMain.doMain(AdminMain.java:305)
	at org.glassfish.admin.cli.AsadminMain.main(AsadminMain.java:56)

```

I know myself that it's due to Java 9, but I guess some people will struggle with this the first time.

## Expected Outcome

I'd like to get a clear error message stating that my Java version is not supported, so I can switch it.

## Current Outcome

Server tries to start, and fails with an unexpected exception, which could be confused with a bug

## Environment ##

- **Payara Version**: 5-SNAPSHOT
- **Edition**: all
- **JDK Version**: 9

**Comment by ggam** [comment]
Another hint: I'm running on a Linux environment. When both `alternatives` and `$JAVA_HOME` point to Java 9, the `NullPointerException` is thrown. Chaning `alternatives` to Java 8 but leaving `$JAVA_HOME` to 9 results in the following error:

```
[guillermo@localhost bin]$ ./asadmin start-domain production
Waiting for production to start Error starting domain production.
The server exited prematurely with exit code 1.
Before it died, it produced the following output:

-Xbootclasspath/p is no longer a supported option.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

Command start-domain failed.
```

**Comment by ggam** [comment]
This also applies to too low versions of Java. #2513 is just one case where versions lower than 1.8.0_162 result in errors.

**Comment by fxrobin** [comment]
Hello, I've got the same trouble trying to use Payara 5 with JDK 9, 10 and 11 through its Dockerfile.
I've changed the base to `FROM openjdk:10-jdk` or `FROM openjdk:11-jdk` and the docker image build process stops on this command :

**Comment by smillidge** [comment]
Closing JDK 11 support issues as this is scheduled soon as a new feature
