### ISSUE TITLE
Deployment failure with CDI related exception: Unable to invoke void fish.payara.micro.cdi.extension.ClusteredCDIEventBusImpl.postConstruct()

### ISSUE THREAD

**Issue by enisinanaj** [payara/Payara#2535]
## Expected Outcome

Application to be deployed

## Current outcome

Exception with the following stack

```
[2018-03-16T11:03:44.452+0100] [Payara 5.181-SNAPSHOT] [SEVERE] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=168 _ThreadName=AutoDeployer] [timeMillis: 1521194624452] [levelValue: 1000] [[
  Exception during lifecycle processing
org.glassfish.deployment.common.DeploymentException: CDI deployment failure:WELD-000049: Unable to invoke void fish.payara.micro.cdi.extension.ClusteredCDIEventBusImpl.postConstruct() on fish.payara.micro.cdi.extension.ClusteredCDIEventBusImpl@2e3a30a9 -- WELD-000049: Unable to invoke void fish.payara.micro.cdi.extension.ClusteredCDIEventBusImpl.postConstruct() on fish.payara.micro.cdi.extension.ClusteredCDIEventBusImpl@2e3a30a9
	at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:85)
	at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.postConstruct(DefaultLifecycleCallbackInvoker.java:66)
	at org.jboss.weld.injection.producer.BasicInjectionTarget.postConstruct(BasicInjectionTarget.java:122)
	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:172)
	at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:96)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
	at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:140)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:67)
	at org.jboss.weld.event.ObserverMethodImpl.getReceiver(ObserverMethodImpl.java:360)
	at org.jboss.weld.event.ObserverMethodImpl.getReceiverIfExists(ObserverMethodImpl.java:347)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:305)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
	at org.jboss.weld.util.Observers.notify(Observers.java:170)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
	at org.jboss.weld.bootstrap.BeanDeploymentModule.fireEvent(BeanDeploymentModule.java:93)
	at org.jboss.weld.bootstrap.WeldStartup.endInitialization(WeldStartup.java:550)
	at org.jboss.weld.bootstrap.WeldBootstrap.endInitialization(WeldBootstrap.java:97)
	at org.glassfish.weld.WeldDeployer.processApplicationLoaded(WeldDeployer.java:516)
	at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:426)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:333)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:494)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:512)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:549)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:545)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:544)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:575)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:567)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:566)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1475)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1857)
	at org.glassfish.deployment.autodeploy.AutoOperation.run(AutoOperation.java:164)
	at org.glassfish.deployment.autodeploy.AutoDeployer.deploy(AutoDeployer.java:597)
	at org.glassfish.deployment.autodeploy.AutoDeployer.deployAll(AutoDeployer.java:484)
	at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:412)
	at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:403)
	at org.glassfish.deployment.autodeploy.AutoDeployService$1.run(AutoDeployService.java:233)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
]]

[2018-03-16T11:03:44.452+0100] [Payara 5.181-SNAPSHOT] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=168 _ThreadName=AutoDeployer] [timeMillis: 1521194624452] [levelValue: 1000] [[
  Exception while loading the app]]

[2018-03-16T11:03:44.452+0100] [Payara 5.181-SNAPSHOT] [SEVERE] [AS-WEB-GLUE-00192] [javax.enterprise.web] [tid: _ThreadID=168 _ThreadName=AutoDeployer] [timeMillis: 1521194624452] [levelValue: 1000] [[
  Undeployment failed for context /test]]

```

## Steps to reproduce

1 - Start the domain

    ./asadmin start-domain payaradomain

2 - Build the attached test case with

	`mvn clean package`

3 - Copy the ear file from *[testproject]/ear/target/hub-test.ear* into *[payara5]/glassfish/domains/domain1/autodeploy/*.

### Sample

 https://github.com/enisinanaj/payara-issue-test-case

## Environment

Payara Version: Payara Server payara-5.181, payara-5.181-20180316.005133-42 #badassfish
Edition: Full
JDK Version:
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

**Comment by siaspa** [comment]
It happens to mee too! same error!

**Comment by enisinanaj** [comment]
It's not only this test application that's not working but also a handful of other webapps, war or ear is independent.

All the apps are deploying fine on Glassfish 5.

**Comment by smillidge** [comment]
This is not reproducible with a clean install of the latest RC downloaded from https://www.payara.fish/upstream_builds on Linux.

**Comment by enisinanaj** [comment]
@smillidge my bad. Actually the problem is due to a missing configuration in `domain.xml`. It's not missing in the default repository but somehow I had deleted it.
That is:
`<managed-executor-service object-type="system-all" jndi-name="concurrent/__defaultManagedExecutorService"></managed-executor-service>`

**Comment by smillidge** [comment]
Thanks looks like we need to log something out to make it obvious in case that happens to others.
