### ISSUE TITLE
Unable to bootstrap Payara Micro programmatically from within JUnit

### ISSUE THREAD

**Issue by tofflos** [payara/Payara#2566]
# Description #
----------

Bootstrapping Payara Micro programmatically from within a main method works fine. Bootstrapping from within JUnit does not.

## Expected Outcome

I expect bootstrapping to work the same inside and outside JUnit.

## Current Outcome

```
javax.validation.BootstrapConfiguration.getClockProviderClassName()Ljava/lang/String;
java.lang.NoSuchMethodError
	at org.hibernate.validator.internal.xml.ValidationBootstrapParameters.<init>(ValidationBootstrapParameters.java:61)
	at org.hibernate.validator.internal.engine.ConfigurationImpl.parseValidationXml(ConfigurationImpl.java:512)
	at org.hibernate.validator.internal.engine.ConfigurationImpl.buildValidatorFactory(ConfigurationImpl.java:317)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.initBeanValidator(CommandRunnerImpl.java:479)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.checkAgainstBeanConstraints(CommandRunnerImpl.java:489)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.injectParameters(CommandRunnerImpl.java:458)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1234)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1857)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1733)
	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:169)
	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:94)
	at fish.payara.micro.boot.runtime.BootCommand.execute(BootCommand.java:65)
	at fish.payara.micro.boot.runtime.BootCommands.executeCommands(BootCommands.java:106)
	at fish.payara.micro.boot.runtime.BootCommands.executeCommands(BootCommands.java:100)
	at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:997)
	at fish.payara.micro.PayaraMicro.bootStrap(PayaraMicro.java:121)
	at com.example.MainIT.beforeClass(MainIT.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

```

## Steps to reproduce (Only for bug reports) 

Describe the test to reproduce the bug in a series of steps. Make each step simple to follow by describing configuration changes, commands to run or simple instructions; for example:

1 -**  Bootstrap Payara Micro from within a  main method:

```
public class Main {

    private static final Logger LOGGER = Logger.getLogger(Main.class.getName());

    public static void main(String[] args) {
        try {
            PayaraMicro server = PayaraMicro.getInstance().setNoCluster(true);
            server.bootStrap();
            server.shutdown();
        } catch (BootstrapException ex) {
            LOGGER.log(Level.SEVERE, null, ex);
        }
    }
}
```

Note that there are no errors.

2 -**  Bootstrap Payara Micro from within JUnit:

```
public class MainIT {

    private static final Logger LOGGER = Logger.getLogger(MainIT.class.getName());

    @BeforeClass
    public static void beforeClass() {
        try {
            PayaraMicro server = PayaraMicro.getInstance().setNoCluster(true);
            server.bootStrap();
            server.shutdown();
        } catch (BootstrapException ex) {
            LOGGER.log(Level.SEVERE, null, ex);
        }
    }

    @Test
    public void dummy() {
        assertTrue(true);
    }
}
```
Note the java.lang.NoSuchMethodError.

## Environment ##

- **Payara Version**: 5.Beta2
- **Edition**: Micro
- **JDK Version**: 8 u161 - Oracle/OpenJDK
- **Operating System**: Windows

**Comment by tofflos** [comment]
Minimal project that reproduces the behavior:
[mavenproject75.zip](https://github.com/payara/Payara/files/1845893/mavenproject75.zip)

**Comment by mikecroft** [comment]
Does this definitely also happen with the released 5.181?

**Comment by mikecroft** [comment]
There should be, as far as I know - @Pandrex247 has there been any change?

**Comment by lprimak** [comment]
GroupId | ArtifactId | Version | Updated | Download
-- | -- | -- | -- | --
fish.payara.extras | payara-micro | 5.181 | 19-Mar-2018 | pom  jar  javadoc.jar  sources.jar
fish.payara.extras | payara-micro | 4.1.2.181 | 09-Feb-2018 | pom  jar  javadoc.jar  sources.jar
fish.payara.extras | payara-micro | 5.Beta2 | 24-Jan-2018 | pom  jar  javadoc.jar  sources.jar
fish.payara.extras | payara-micro | 5.Beta1 | 20-Dec-2017 | pom  jar  javadoc.jar  sources.jar
fish.payara.extras | payara-micro | 4.1.2.174 | 14-Nov-2017 | pom  jar  javadoc.jar  sources.jar

**Comment by lprimak** [comment]
from search.maven.org
Most people are using mvnrepository.com I think it's out of date for a week or so

**Comment by lprimak** [comment]
so it's definitely there

**Comment by tofflos** [comment]
Thank you. I wasn't aware of that.

I've updated the project to use 5.181 and the problem persists:
[mavenproject75.zip](https://github.com/payara/Payara/files/1849193/mavenproject75.zip)

**Comment by rdebusscher** [comment]
Hi @tofflos,

Based on the error, it seems it is missing (or has a wrong version) of Bean Validation on the test classpath.

By adding 
```
        <dependency>
            <groupId>javax.validation</groupId>
            <artifactId>validation-api</artifactId>
            <version>2.0.0.Final</version>
            <scope>test</scope>
        </dependency>
```
the Payara Micro instance can be started from within a test. I did not research the cause of this behavior.

Regards
Rudy
