### ISSUE TITLE
SAAJ0543: Entity References are not allowed in SOAP documents

### ISSUE THREAD

**Issue by justaman4326** [payara/Payara#2592]
# Description #
----------

I am receiving an error when processing a SOAP request/response, specifically when we call SOAPMessageContext.getMessage() in our custom SOAPHandler.  The end user receives an error as a response and the following is printed in the server logs:

[2018-04-02T11:00:10.127-0500] [Payara 5.181] [SEVERE] [SAAJ0543.soap.entity.refs.not.allowed.in.docs] [com.sun.xml.messaging.saaj.soap] [tid: _ThreadID=39 _ThreadName=http-thread-pool::http-listener-2(4)] [timeMillis: 1522684810127] [levelValue: 1000] [[
  SAAJ0543: Entity References are not allowed in SOAP documents]]

[2018-04-02T11:00:10.147-0500] [Payara 5.181] [SEVERE] [AS-WSSECURITY-00001] [javax.enterprise.webservices.security] [tid: _ThreadID=39 _ThreadName=http-thread-pool::http-listener-2(4)] [timeMillis: 1522684810147] [levelValue: 1000] [[
  Request processing failed.
java.lang.UnsupportedOperationException: Entity References are not allowed in SOAP documents
        at com.sun.xml.messaging.saaj.soap.SOAPDocumentImpl.createEntityReference(SOAPDocumentImpl.java:221)
        at com.sun.xml.messaging.saaj.soap.SOAPPartImpl.createEntityReference(SOAPPartImpl.java:515)
        at com.sun.xml.ws.api.message.saaj.SaajStaxWriter.writeEntityRef(SaajStaxWriter.java:267)
        at com.sun.xml.bind.v2.runtime.output.XMLStreamWriterOutput$XmlStreamOutWriterAdapter.writeEntityRef(XMLStreamWriterOutput.java:291)
        at com.sun.xml.bind.v2.runtime.output.XMLStreamWriterOutput$NewLineEscapeHandler.escape(XMLStreamWriterOutput.java:255)
        at com.sun.xml.bind.v2.runtime.output.XMLStreamWriterOutput.text(XMLStreamWriterOutput.java:165)
        at com.sun.xml.bind.v2.runtime.XMLSerializer.leafElement(XMLSerializer.java:328)
        at com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$StringImplImpl.writeLeafElement(RuntimeBuiltinLeafInfoImpl.java:1070)
        at com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$StringImplImpl.writeLeafElement(RuntimeBuiltinLeafInfoImpl.java:1049)
        at com.sun.xml.bind.v2.runtime.reflect.TransducedAccessor$CompositeTransducedAccessorImpl.writeLeafElement(TransducedAccessor.java:254)
        at com.sun.xml.bind.v2.runtime.property.SingleElementLeafProperty.serializeBody(SingleElementLeafProperty.java:130)
        at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.serializeBody(ClassBeanInfoImpl.java:360)
        at com.sun.xml.bind.v2.runtime.XMLSerializer.childAsXsiType(XMLSerializer.java:696)
        at com.sun.xml.bind.v2.runtime.property.SingleElementNodeProperty.serializeBody(SingleElementNodeProperty.java:158)
        at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.serializeBody(ClassBeanInfoImpl.java:360)
        at com.sun.xml.bind.v2.runtime.XMLSerializer.childAsXsiType(XMLSerializer.java:696)
        at com.sun.xml.bind.v2.runtime.property.SingleElementNodeProperty.serializeBody(SingleElementNodeProperty.java:158)
        at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.serializeBody(ClassBeanInfoImpl.java:360)
        at com.sun.xml.bind.v2.runtime.XMLSerializer.childAsXsiType(XMLSerializer.java:696)
        at com.sun.xml.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:276)
        at com.sun.xml.bind.v2.runtime.BridgeImpl.marshal(BridgeImpl.java:94)
        at com.sun.xml.bind.api.Bridge.marshal(Bridge.java:111)
        at com.sun.xml.ws.db.glassfish.BridgeWrapper.marshal(BridgeWrapper.java:192)
        at com.sun.xml.ws.message.jaxb.JAXBMessage.writePayloadTo(JAXBMessage.java:417)
        at com.sun.xml.ws.message.AbstractMessageImpl.writeTo(AbstractMessageImpl.java:192)
        at com.sun.xml.ws.api.message.MessageWrapper.writeTo(MessageWrapper.java:226)
        at com.sun.xml.ws.api.message.saaj.SAAJFactory.readAsSOAPMessage(SAAJFactory.java:295)
        at com.sun.xml.ws.api.message.saaj.SAAJFactory.readAsSAAJ(SAAJFactory.java:222)
        at com.sun.xml.ws.api.message.saaj.SAAJFactory.read(SAAJFactory.java:211)
        at com.sun.xml.ws.message.AbstractMessageImpl.toSAAJ(AbstractMessageImpl.java:236)
        at com.sun.xml.ws.api.message.MessageWrapper.readAsSOAPMessage(MessageWrapper.java:176)
        at com.sun.xml.ws.handler.SOAPMessageContextImpl.getMessage(SOAPMessageContextImpl.java:85)

## Environment ##

- **Payara Version**: 5.181
- **Edition**: Full
- **JDK Version**: Oracle JDK 1.8u162
- **Operating System**: Debian Stretch
- **Database**: Mysql 5.7

**Comment by justaman4326** [comment]
Actually it doesn't seem to be a Payara issue but a JDK one.  I've verified my issue is related to the following bug: https://bugs.openjdk.java.net/browse/JDK-8196491 .  Thanks for your response.

**Comment by smillidge** [comment]
@mikecroft can you raise with Azul to get a fix for support customers in Zulu?

**Comment by bravehorsie** [comment]
Looks like this one: https://bugs.openjdk.java.net/browse/JDK-8196491
