### ISSUE TITLE
Context Classloaders in EAR are set incorrectly with Hazelcast

### ISSUE THREAD

**Issue by sgflt** [payara/Payara#2604]
# Description #
----------

After commit 4c3c798 our application EAR has classloader issues when using Hazelcast caches through payara/CacheManager.
## Expected Outcome

Application is working correctly without StackOverflowErrors and NoClassDefFoundErrors.

JSP files can import java classes from the same WAR module.
JSF application beans are corectly injected.

## Current Outcome
_JSP file that imports java from the same WAR module throws NoClassDefFoundError.
JSF bean are not injected and server ends with 500 StackOverflowError._

## Steps to reproduce (Only for bug reports) 
I am trying to provide minimal reproducible example, but without success.

Our application is deployed as an EAR with at least 3 EJB modules and cca 30 web modules. We use Cache API backed by Hazelcast in clustered environment with SSO login over web modules.

The only way to reproduce this bug is usage of Hazelcast caching. If we stop caching custom JPA Entities or other custom objects in Hazelcast cache, then everything works.

## Context (Optional)
I have been debugging for a while the Payara server and I found that the problem comes out from class PayaraHazelcastSerializer and JavaEEContextUtilImpl. 

In Payara 4.1.2.172, JavaEEContextUtilImpl#setApplicationContext on the line 178 had always appInfo null value and contextClassloader was never set.

Since 4.1.2.173,  JavaEEContextUtilImpl#setApplicationClassLoader on the line 137 is always found and context classloader is changed.

Only and only if JavaEEContextUtilImpl#setApplicationClassLoader is called by PayaraHazelcastSerializer, EAR application throws exceptions from JSP files:
```
java.lang.NoClassDefFoundError: cz/i/Init
	at org.apache.jsp.index_jsp._jspService(index_jsp.java:47)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1692)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:339)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:209)
	at cz.i.cis.appl.core.http.CisFilter.processRequest(CisFilter.java:185)
	at cz.i.cis.appl.core.http.CisFilter.doFilter(CisFilter.java:100)
	at cz.i.cis.appl.core.http.SimpleCisFilter.doFilter(SimpleCisFilter.java:67)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:251)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:256)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:654)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:593)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:159)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:654)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:593)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:368)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:483)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:180)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: cz.i.Init
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1655)
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1501)
	at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:187)
	at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:125)
	... 44 more
```
JSP file contains following content:
```
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html; charset=utf-8" pageEncoding="utf-8" %>
<% cz.i.Init.blah(); %>
```

And StackOverflowError occurs in JSF modules during dependency injection lookup:
```
java.lang.StackOverflowError
        at javax.faces.CurrentThreadToServletContext.getApplicationFactoryManager(CurrentThreadToServletContext.java:102)
        at javax.faces.CurrentThreadToServletContext.getApplicationFactoryManager(CurrentThreadToServletContext.java:91)
        at javax.faces.FactoryFinder.getFactory(FactoryFinder.java:279)
        at com.sun.faces.context.FacesContextImpl.getApplication(FacesContextImpl.java:155)
        at com.sun.faces.util.MessageFactory.getApplication(MessageFactory.java:286)
        at com.sun.faces.util.MessageFactory.getMessage(MessageFactory.java:158)
        at com.sun.faces.util.MessageFactory.getMessage(MessageFactory.java:136)
        at com.sun.faces.util.MessageUtils.getExceptionMessageString(MessageUtils.java:388)
        at com.sun.faces.application.ApplicationAssociate.<init>(ApplicationAssociate.java:234)
        at com.sun.faces.application.ApplicationImpl.<init>(ApplicationImpl.java:212)
        at com.sun.faces.application.ApplicationFactoryImpl.getApplication(ApplicationFactoryImpl.java:107)
        at org.glassfish.weld.jsf.WeldApplicationFactory.getApplication(WeldApplicationFactory.java:69)
        at org.glassfish.weld.jsf.WeldApplicationFactory.getApplication(WeldApplicationFactory.java:69)
        at com.sun.faces.application.InjectionApplicationFactory.getApplication(InjectionApplicationFactory.java:93)
        at com.sun.faces.context.FacesContextImpl.getApplication(FacesContextImpl.java:158)
        at com.sun.faces.util.MessageFactory.getApplication(MessageFactory.java:286)
        at com.sun.faces.util.MessageFactory.getMessage(MessageFactory.java:158)
        at com.sun.faces.util.MessageFactory.getMessage(MessageFactory.java:136)
        at com.sun.faces.util.MessageUtils.getExceptionMessageString(MessageUtils.java:388)
        at com.sun.faces.application.ApplicationAssociate.<init>(ApplicationAssociate.java:234)
        at com.sun.faces.application.ApplicationImpl.<init>(ApplicationImpl.java:212)
        at com.sun.faces.application.ApplicationFactoryImpl.getApplication(ApplicationFactoryImpl.java:107)
        at org.glassfish.weld.jsf.WeldApplicationFactory.getApplication(WeldApplicationFactory.java:69)
        at org.glassfish.weld.jsf.WeldApplicationFactory.getApplication(WeldApplicationFactory.java:69)
        at com.sun.faces.application.InjectionApplicationFactory.getApplication(InjectionApplicationFactory.java:93)
        at com.sun.faces.context.FacesContextImpl.getApplication(FacesContextImpl.java:158)
        at com.sun.faces.util.MessageFactory.getApplication(MessageFactory.java:286)
        at com.sun.faces.util.MessageFactory.getMessage(MessageFactory.java:158)
        at com.sun.faces.util.MessageFactory.getMessage(MessageFactory.java:136)
        at com.sun.faces.util.MessageUtils.getExceptionMessageString(MessageUtils.java:388)
        at com.sun.faces.application.ApplicationAssociate.<init>(ApplicationAssociate.java:234)
        at com.sun.faces.application.ApplicationImpl.<init>(ApplicationImpl.java:212)
        at com.sun.faces.application.ApplicationFactoryImpl.getApplication(ApplicationFactoryImpl.java:107)
        at org.glassfish.weld.jsf.WeldApplicationFactory.getApplication(WeldApplicationFactory.java:69)
        at org.glassfish.weld.jsf.WeldApplicationFactory.getApplication(WeldApplicationFactory.java:69)
        at com.sun.faces.application.InjectionApplicationFactory.getApplication(InjectionApplicationFactory.java:93)
        at com.sun.faces.context.FacesContextImpl.getApplication(FacesContextImpl.java:158)
        at com.sun.faces.util.MessageFactory.getApplication(MessageFactory.java:286)
        at com.sun.faces.util.MessageFactory.getMessage(MessageFactory.java:158)
        at com.sun.faces.util.MessageFactory.getMessage(MessageFactory.java:136)
        at com.sun.faces.util.MessageUtils.getExceptionMessageString(MessageUtils.java:388)
        at com.sun.faces.application.ApplicationAssociate.<init>(ApplicationAssociate.java:234)
        at com.sun.faces.application.ApplicationImpl.<init>(ApplicationImpl.java:212)
        at com.sun.faces.application.ApplicationFactoryImpl.getApplication(ApplicationFactoryImpl.java:107)
        at org.glassfish.weld.jsf.WeldApplicationFactory.getApplication(WeldApplicationFactory.java:69)
        at org.glassfish.weld.jsf.WeldApplicationFactory.getApplication(WeldApplicationFactory.java:69)
        at com.sun.faces.application.InjectionApplicationFactory.getApplication(InjectionApplicationFactory.java:93)
        at com.sun.faces.context.FacesContextImpl.getApplication(FacesContextImpl.java:158)
        at com.sun.faces.util.MessageFactory.getApplication(MessageFactory.java:286)
        at com.sun.faces.util.MessageFactory.getMessage(MessageFactory.java:158)
        at com.sun.faces.util.MessageFactory.getMessage(MessageFactory.java:136)
        at com.sun.faces.util.MessageUtils.getExceptionMessageString(MessageUtils.java:388)
        at com.sun.faces.application.ApplicationAssociate.<init>(ApplicationAssociate.java:234)
        at com.sun.faces.application.ApplicationImpl.<init>(ApplicationImpl.java:212)
        at com.sun.faces.application.ApplicationFactoryImpl.getApplication(ApplicationFactoryImpl.java:107)
        at org.glassfish.weld.jsf.WeldApplicationFactory.getApplication(WeldApplicationFactory.java:69)
        at org.glassfish.weld.jsf.WeldApplicationFactory.getApplication(WeldApplicationFactory.java:69)
        at com.sun.faces.application.InjectionApplicationFactory.getApplication(InjectionApplicationFactory.java:93)
        at com.sun.faces.context.FacesContextImpl.getApplication(FacesContextImpl.java:158)
        at com.sun.faces.util.MessageFactory.getApplication(MessageFactory.java:286)
        at com.sun.faces.util.MessageFactory.getMessage(MessageFactory.java:158)
        at com.sun.faces.util.MessageFactory.getMessage(MessageFactory.java:136)
        at com.sun.faces.util.MessageUtils.getExceptionMessageString(MessageUtils.java:388)
        at com.sun.faces.application.ApplicationAssociate.<init>(ApplicationAssociate.java:234)
        at com.sun.faces.application.ApplicationImpl.<init>(ApplicationImpl.java:212)
...
        at com.sun.faces.application.ApplicationFactoryImpl.getApplication(ApplicationFactoryImpl.java:107)
        at org.glassfish.weld.jsf.WeldApplicationFactory.getApplication(WeldApplicationFactory.java:69)
        at org.glassfish.weld.jsf.WeldApplicationFactory.getApplication(WeldApplicationFactory.java:69)
        at com.sun.faces.application.InjectionApplicationFactory.getApplication(InjectionApplicationFactory.java:93)
        at com.sun.faces.context.FacesContextImpl.getApplication(FacesContextImpl.java:158)
        at com.sun.faces.util.MessageFactory.getApplication(MessageFactory.java:286)
        at com.sun.faces.util.MessageFactory.getMessage(MessageFactory.java:158)
        at com.sun.faces.util.MessageFactory.getMessage(MessageFactory.java:136)
        at com.sun.faces.util.MessageUtils.getExceptionMessageString(MessageUtils.java:388)
        at com.sun.faces.application.ApplicationAssociate.<init>(ApplicationAssociate.java:234)
        at com.sun.faces.application.ApplicationImpl.<init>(ApplicationImpl.java:212)
        at com.sun.faces.application.ApplicationFactoryImpl.getApplication(ApplicationFactoryImpl.java:107)
        at org.glassfish.weld.jsf.WeldApplicationFactory.getApplication(WeldApplicationFactory.java:69)
        at org.glassfish.weld.jsf.WeldApplicationFactory.getApplication(WeldApplicationFactory.java:69)
        at com.sun.faces.application.InjectionApplicationFactory.getApplication(InjectionApplicationFactory.java:93)
        at com.sun.faces.context.FacesContextImpl.getApplication(FacesContextImpl.java:158)
        at com.sun.faces.util.MessageFactory.getApplication(MessageFactory.java:286)
        at com.sun.faces.util.MessageFactory.getMessage(MessageFactory.java:158)
        at com.sun.faces.util.MessageFactory.getMessage(MessageFactory.java:136)
        at com.sun.faces.util.MessageUtils.getExceptionMessageString(MessageUtils.java:388)
        at com.sun.faces.application.ApplicationAssociate.<init>(ApplicationAssociate.java:234)
        at com.sun.faces.application.ApplicationImpl.<init>(ApplicationImpl.java:212)
        at com.sun.faces.application.ApplicationFactoryImpl.getApplication(ApplicationFactoryImpl.java:107)
        at org.glassfish.weld.jsf.WeldApplicationFactory.getApplication(WeldApplicationFactory.java:69)
```

## Environment ##

- **Payara Version**: 4.1.2.173+ since commit 4c3c7988d9e445cd7242536d7315a511f86ac093
- **Edition**: Full 
- **JDK Version**: Oracle 8u161 
- **Operating System**: Linux

**Comment by lprimak** [comment]
Any chance you can try Payara 5?  There is an outstanding issue in Payara 4 that may affect this that hasn't been merged yet:

**Comment by lprimak** [comment]
Also, if that doesn't work, please create a simple reproducer application so I can test it

**Comment by sgflt** [comment]
I've finally created a test case. Suggested commit did not work. https://github.com/sgflt/payara-test-case

**Comment by lprimak** [comment]
Thanks for the reproducer.  Do you have the asadmin commands I would have to run so I don't have to figure it out on my own?  Thank you

**Comment by lprimak** [comment]
Assigned internal Payara issue ID ```PAYARA-2677```

**Comment by smillidge** [comment]
Is this reproducible?
Btw classloading for JSPs is horrible as the jsp compiler takes a string for the classpath deep in the jsp ri code and passes that to javac when compiling the jsp.

**Comment by lprimak** [comment]
Im not sure if it is yet, haven't run the program yet

**Comment by lprimak** [comment]
I was not able to reproduce this specific issue, but I think there is indeed a bug in the code.
PayaraHazelcastSerializer doesn't reset the Thread context ClassLoader to what it was after changing it.
This could conceivably cause this problem.
Since the fix is pretty simple, I will just go ahead and submit a PR
Hopefully this will fix this issue

**Comment by lprimak** [comment]
Let me know if this indeed works & fixes this issue
thanks

**Comment by sgflt** [comment]
There is requested asadmin command (only user without groups is sufficient):
`asadmin create-file-user test-case`

At first glance I can confirm that, your fix for Payara4 is OK. Test case and whole application behaves correctly.

With Payara5 I was not able to reproduce bug with provided test case, even without your fix. But migration of whole application from Payara4 is not currently possible due to some incomaptibilities in domain configuration and Eclipselink implementation.

**Comment by lprimak** [comment]
Glad to hear it.
