### ISSUE TITLE
java.lang.NoSuchMethodError: org.glassfish.external.probe.provider.annotations.Probe.stateful()Z

### ISSUE THREAD

**Issue by mkarg** [payara/Payara#2605]
# Description #
----------

Bootstrapping of Payara Micro fails with `java.lang.NoSuchMethodError: org.glassfish.external.probe.provider.annotations.Probe.stateful()Z` when trying to deploy a JDBC DataSource.

## Expected Outcome

Bootstrapping finished with a correctly set up JDBC Data Source.

## Current Outcome

```
[2018-04-06T14:53:22.541+0200] [] [WARNUNG] [NCLS-CORE-00069] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1523019202541] [levelValue: 900] [[
  Exception while dispatching an event
java.lang.NoSuchMethodError: org.glassfish.external.probe.provider.annotations.Probe.stateful()Z
                at org.glassfish.flashlight.impl.provider.FlashlightProbeProviderFactory.getProbeProvider(FlashlightProbeProviderFactory.java:278)
                at org.glassfish.flashlight.impl.provider.FlashlightProbeProviderFactory.getProbeProvider(FlashlightProbeProviderFactory.java:194)
                at org.glassfish.flashlight.impl.provider.FlashlightProbeProviderFactory.getProbeProvider(FlashlightProbeProviderFactory.java:157)
                at org.glassfish.admin.monitor.MonitoringBootstrap.processProbeProviderClass(MonitoringBootstrap.java:475)
                at org.glassfish.admin.monitor.MonitoringBootstrap.processManifest(MonitoringBootstrap.java:356)
                at org.glassfish.admin.monitor.MonitoringBootstrap.addProvider(MonitoringBootstrap.java:337)
                at org.glassfish.admin.monitor.MonitoringBootstrap.registerProbes(MonitoringBootstrap.java:285)
                at com.sun.enterprise.connectors.service.ConnectorService.loadDeferredResourceAdapter(ConnectorService.java:181)
                at com.sun.enterprise.connectors.service.ConnectorService.ifSystemRarLoad(ConnectorService.java:353)
                at com.sun.enterprise.connectors.service.ConnectorConnectionPoolAdminServiceImpl.getActiveResourceAdapter(ConnectorConnectionPoolAdminServiceImpl.java:846)
                at com.sun.enterprise.connectors.service.ConnectorConnectionPoolAdminServiceImpl.getResourceAdapter(ConnectorConnectionPoolAdminServiceImpl.java:827)
                at com.sun.enterprise.connectors.service.ConnectorConnectionPoolAdminServiceImpl.obtainManagedConnectionFactory(ConnectorConnectionPoolAdminServiceImpl.java:939)
                at com.sun.enterprise.connectors.service.ConnectorConnectionPoolAdminServiceImpl.obtainManagedConnectionFactory(ConnectorConnectionPoolAdminServiceImpl.java:911)
                at com.sun.enterprise.connectors.service.ConnectorConnectionPoolAdminServiceImpl.createManagedConnectionFactory(ConnectorConnectionPoolAdminServiceImpl.java:918)
                at com.sun.enterprise.connectors.service.ConnectorConnectionPoolAdminServiceImpl.createConnectorConnectionPool(ConnectorConnectionPoolAdminServiceImpl.java:191)
                at com.sun.enterprise.connectors.ConnectorRuntime.createConnectorConnectionPool(ConnectorRuntime.java:331)
                at org.glassfish.jdbc.deployer.JdbcConnectionPoolDeployer.actualDeployResource(JdbcConnectionPoolDeployer.java:201)
                at org.glassfish.jdbc.deployer.JdbcConnectionPoolDeployer.deployResource(JdbcConnectionPoolDeployer.java:159)
                at org.glassfish.resources.module.ResourcesDeployer.deployResources(ResourcesDeployer.java:699)
                at org.glassfish.resources.module.ResourcesDeployer.deployResources(ResourcesDeployer.java:680)
                at org.glassfish.resources.module.ResourcesDeployer.processResources(ResourcesDeployer.java:858)
                at org.glassfish.resources.module.ResourcesDeployer.event(ResourcesDeployer.java:804)
                at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
                at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:420)
                at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
                at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:508)
                at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:544)
                at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:540)
                at java.security.AccessController.doPrivileged(Native Method)
                at javax.security.auth.Subject.doAs(Subject.java:360)
                at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:539)
                at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:570)
                at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:562)
                at java.security.AccessController.doPrivileged(Native Method)
                at javax.security.auth.Subject.doAs(Subject.java:360)
                at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:561)
                at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1469)
                at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
                at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1851)
                at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1727)
                at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:134)
                at fish.payara.micro.impl.PayaraMicroImpl.deployAll(PayaraMicroImpl.java:1426)
                at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1001)
                at fish.payara.micro.PayaraMicro.bootStrap(PayaraMicro.java:121)
]]
```

### Samples

```java
PayaraMicro pm= PayaraMicro.getInstance();
                pm.addDeployment(warFile); // Contains glassfish-resources.xml
                pm.addLibrary(Paths.get(System.getenv("SQLANY17"), "Java", "sajdbc4.jar").toFile());
                pm.bootStrap();
```

## Context

*Only* fails when bootstrapping Payara Micro using Java API but *works perfectly* when starting Payara Micro from CLI with the same WAR and driver.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources PUBLIC "-//GlassFish.org//DTD GlassFish Application Server 3.1 Resource Definitions//EN" "http://glassfish.org/dtds/glassfish-resources_1_5.dtd">
<resources>    
	<jdbc-resource 
            enabled="true" jndi-name="jdbc/xxx" object-type="user" pool-name="jdbc/xxx" />		

	<jdbc-connection-pool name="jdbc/xxx" res-type="javax.sql.DataSource" datasource-classname="sap.jdbc4.sqlanywhere.ASADataSource"
		pool-resize-quantity="2" max-pool-size="32" steady-pool-size="8">
		<property name="URL" value="jdbc:sqlanywhere:ENG=xxx;DBN=xxx;UID=xxx;PWD=xxx" />		
	</jdbc-connection-pool>
</resources>
```

## Environment ##

- **Payara Version**: 4.1.2.181
- **Edition**: Micro
- **JDK Version**: JDK 8
- **Operating System**: Win 7 Pro 64 Bit
- **Database**: SQLAnywhere

**Comment by smillidge** [comment]
Does this happen with other drivers or just SQL Anywhere?
Can you create a simple maven test case?

**Comment by mkarg** [comment]
Good question. I'll try to reproduce in a clean-room test case next Friday. Stay tuned. :-)

**Comment by mkarg** [comment]
Apparently the problem was induced by some weird depencency on a glassfish library in the classpath of the application project. As the programmer couldn't tell me what it is good for, I simply adviced him to remove it, and everything was fine then. So I assume there is no bug actually. I will observe the case for one more week and when it is not popping up anymore, I will close this issue then.
