### ISSUE TITLE
Embedded RARs broken NPE at ResourceValidator

### ISSUE THREAD

**Issue by fcorneli** [payara/Payara#2636]
I get an NPE when trying to deploy an EAR with embedded RAR.
```
java.lang.NullPointerException
	at java.util.ArrayList.addAll(ArrayList.java:581)
	at com.sun.enterprise.deployment.util.ResourceValidator$JNDINamespace.storeAppScopedResources(ResourceValidator.java:1110)
	at com.sun.enterprise.deployment.util.ResourceValidator$JNDINamespace.access$1600(ResourceValidator.java:1078)
	at com.sun.enterprise.deployment.util.ResourceValidator$AppResources.storeAppScopedResources(ResourceValidator.java:1069)
	at com.sun.enterprise.deployment.util.ResourceValidator$AppResources.access$100(ResourceValidator.java:1038)
	at com.sun.enterprise.deployment.util.ResourceValidator.parseResources(ResourceValidator.java:192)
	at com.sun.enterprise.deployment.util.ResourceValidator.event(ResourceValidator.java:145)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:423)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:512)
```

Payara version: Payara Server  5.181
Java version: jdk1.8.0_162.jdk
OS: Mac OS X 10.13.4

**Comment by fcorneli** [comment]
Also tested on the latest trunk. Same NPE:
```
java.lang.NullPointerException
	at java.util.ArrayList.addAll(ArrayList.java:581)
	at com.sun.enterprise.deployment.util.ResourceValidator$JNDINamespace.storeAppScopedResources(ResourceValidator.java:1106)
	at com.sun.enterprise.deployment.util.ResourceValidator$JNDINamespace.access$1600(ResourceValidator.java:1074)
	at com.sun.enterprise.deployment.util.ResourceValidator$AppResources.storeAppScopedResources(ResourceValidator.java:1065)
	at com.sun.enterprise.deployment.util.ResourceValidator$AppResources.access$100(ResourceValidator.java:1034)
	at com.sun.enterprise.deployment.util.ResourceValidator.parseResources(ResourceValidator.java:188)
	at com.sun.enterprise.deployment.util.ResourceValidator.event(ResourceValidator.java:141)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:427)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:540)
```

**Comment by fcorneli** [comment]
We will soon open source the project that triggers this issue, so it can be easily replicated by the Payara team.

**Comment by lprimak** [comment]
Any additional hints on how to run / reproduce the problem with the project?

**Comment by lprimak** [comment]
@fcorneli

**Comment by fcorneli** [comment]
Could you try again? web3j 3.4.0 has been released now.

**Comment by fcorneli** [comment]
Could you try again? web3j 3.4.0 has been released now.

**Comment by fcorneli** [comment]
See:
https://www.e-contract.be/sites/ethereum-resource-adapter/demo.html
on how to compile/deploy the demo application on an application server.

**Comment by lprimak** [comment]
Thanks, I will try

**Comment by lprimak** [comment]
Unfortunately, with the latest source, I am getting this:

```
[INFO] Building Ethereum Resource Adapter Demo Model 1.0.0               [6/14]
[INFO] --------------------------------[ ejb ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ ethereum-rar-demo-model ---
[INFO] 
[INFO] --- web3j-maven-plugin:0.2.0:generate-sources (generate-sources) @ ethereum-rar-demo-model ---
[INFO] process 'demo-contract.sol'
[INFO] Solidity Compiler not installed.
[INFO] Solidity Compiler from library is used
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Ethereum JCA Resource Adapter Project 1.0.0 ........ SUCCESS [  0.491 s]
[INFO] Ethereum Resource Adapter API ...................... SUCCESS [  3.957 s]
[INFO] Ethereum Resource Adapter .......................... SUCCESS [  1.677 s]
[INFO] Ethereum Resource Adapter Archive .................. SUCCESS [  2.262 s]
[INFO] Ethereum Resource Adapter JSF Library .............. SUCCESS [  0.672 s]
[INFO] Ethereum Resource Adapter Demo Model ............... FAILURE [  1.724 s]
[INFO] Ethereum Resource Adapter Oracle API ............... SKIPPED
[INFO] Ethereum Resource Adapter Demo Web Application ..... SKIPPED
[INFO] Ethereum Resource Adapter Oracle SPI ............... SKIPPED
[INFO] Ethereum Resource Adapter Oracle ................... SKIPPED
[INFO] Ethereum Resource Adapter Oracle Node .............. SKIPPED
[INFO] Ethereum Resource Adapter Oracle Default ........... SKIPPED
[INFO] Ethereum Resource Adapter Demo EAR ................. SKIPPED
[INFO] Ethereum Resource Adapter Integration Tests 1.0.0 .. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.888 s
[INFO] Finished at: 2018-05-01T01:02:50-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.web3j:web3j-maven-plugin:0.2.0:generate-sources (generate-sources) on project ethereum-rar-demo-model: Could not compile solidity files
[ERROR] Warning: This is a pre-release compiler version, please do not use it in production.
[ERROR] <stdin>:31:23: Error: Expected token Semicolon got 'LParen'
[ERROR]         emit DemoEvent(msg.sender, _value);
[ERROR]                       ^
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ethereum-rar-demo-model
```

**Comment by lprimak** [comment]
@fcorneli

**Comment by fcorneli** [comment]
The Solidity compiler is indeed required. Will add it to the documentation site.

**Comment by lprimak** [comment]
The code for embedded RARs is badly broken.  Do you know by any chance if this works with GlassFish 5?

**Comment by lprimak** [comment]
Is this actually supported by Java EE specs BTW?  Or does this just "happen" to work on WildFly?

**Comment by fcorneli** [comment]
Does not work on GlassFish 5 either. But works on WildFly, JBoss EAP, and WebLogic.

Embedded RAR is part of the JCA specs as far as I can remember.

**Comment by lprimak** [comment]
There are references to java:/EtherimConnectionFactory etc.
I think they should all be java:app/EtheriumConnectionFactory
This may be a part of the problem.  What do you think?

**Comment by lprimak** [comment]
Assigned internal issue ```PAYARA-2719```

**Comment by fcorneli** [comment]
If I replace within `glassfish-resources.xml`the `jndi-name` with
```
java:module/EthereumConnectionFactory
```
I still get the same NPE.

**Comment by lprimak** [comment]
I understand that.  There are other errors as well once I get past that.  I believe it should be java:app/EthereumConnectionFactory to be compliant

**Comment by lprimak** [comment]
I am not saying it's going to work with ```java:app/``` with the current version.
There needs to be additional fixes.  I am able to get past the current issue with my internal fix, but I am getting additional issues, one of which is the ```java:/``` naming which is not correct I believe. 

Can you change your code to use ```java:app/``` and see if it still works with WildFly?
That will be more correct and standards-compliant and will help me come up with Payara fix which is correct.

**Comment by lprimak** [comment]
As I said before, the GlassFish (and also Payara) 5 embedded RAR code is badly broken currently.
There is more likelyhood of a fix for the appropriate use of ```java:app/``` prefixed references

**Comment by smillidge** [comment]
Have you tried the deployment without Resource Validation by using the system property `-Ddeployment.resource.validation=false`

We've had a lot of trouble with Resource Validation brought in from upstream GlassFish.

**Comment by lprimak** [comment]
that's the first thing I tried, but there are other issues.  Clearly this scenario wasn't tested in a while in upstream

**Comment by fcorneli** [comment]
Changing the naming to:
```
java:app/EthereumConnectionFactory
```
unfortunately gives me the following error under WildFly:
```
Caused by: java.lang.RuntimeException: WFLYNAM0030: Illegal context in name: java:app/EthereumConnectionFactory
```

**Comment by lprimak** [comment]
Unfortunately, I found that the whole embedded RAR functionality is hopelessly broken in Payara as well as upstream GlassFish.  The RAR needs to be deployed separately

**Comment by fcorneli** [comment]
Tested again on Payara Server version 5.19, still receiving the same NPE. Anyone working on resolving the issue with embedded RARs?

**Comment by lprimak** [comment]
No. It is very difficul to resolve and the easier solution is to deploy RAR separately

**Comment by rdebusscher** [comment]
Closing this issue as the separate deployment of RAR is recommended and tested approach by TCK.
