### ISSUE TITLE
Deploy a @Singleton and @Startup bean that has an @Inject causes NullPointerException

### ISSUE THREAD

**Issue by cristiG** [payara/Payara#2640]
# Description #
----------

Deploying an EAR with a `@Singleton` and `@Startup` bean that has an `@Injected` bean fails with a NullPointerException:
```text
Caused by: java.lang.NullPointerException
	at org.glassfish.weld.services.JCDIServiceImpl.createInterceptorInstance(JCDIServiceImpl.java:397)
	at com.sun.ejb.containers.BaseContainer.createEjbInterceptors(BaseContainer.java:1799)
	at com.sun.ejb.containers.BaseContainer.createEmptyContextAndInterceptors(BaseContainer.java:1694)
	at com.sun.ejb.containers.BaseContainer.createEjbInstanceAndContext(BaseContainer.java:1708)
```

## Expected Outcome

We are trying to migrate an application from GF 3 to Payara 5.181 and we had some problems during the deployment.
In the application deployed to GF 3 we have a `@Singleton` and `@Startup` bean that has inside `@Inject` another bean.
We have created a small ear package just with this bean:

```java
@Singleton
@Startup
 public class MySingletonBean implements MySingletonBeanLocal {
    private static final Logger LOG = LoggerFactory.getLogger(MySingletonBean.class);
   `@Inject`
    private InjectedBean someInjectedBean;

    public MySingletonBean() {
        LOG.debug("Constructed");
    }

    @Override
    public int someMethod(int input, String another) {
        return 0;
    }

    @Override
    public void businessMethod() {
    }
}
```
The project with these simple beans is attached
[TestPayaraMigration.zip](https://github.com/payara/Payara/files/1919564/TestPayaraMigration.zip)

Deploying this in GF 3 works without any exceptions

## Current Outcome

Deploying in Payara by coping in autodeploy (the same also when calling asadmin deploy) fails:
```text
[2018-04-17T14:44:48.333+0300] [Payara 5.181] [SEVERE] [] [javax.enterprise.system.tools.deployment.common] [tid: _ThreadID=67 _ThreadName=AutoDeployer] [timeMillis: 1523965488333] [levelValue: 1000] [[
  Exception while invoking class org.glassfish.ejb.startup.EjbApplication start method
javax.ejb.EJBException: javax.ejb.CreateException: Initialization failed for Singleton MySingletonBean
	at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:736)
	at com.sun.ejb.containers.AbstractSingletonContainer.instantiateSingletonInstance(AbstractSingletonContainer.java:438)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:219)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:180)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.doStartup(SingletonLifeCycleManager.java:158)
	at org.glassfish.ejb.startup.EjbApplication.start(EjbApplication.java:169)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:294)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:357)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:538)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:514)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:549)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:545)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:544)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:575)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:567)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:566)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1475)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1857)
	at org.glassfish.deployment.autodeploy.AutoOperation.run(AutoOperation.java:164)
	at org.glassfish.deployment.autodeploy.AutoDeployer.deploy(AutoDeployer.java:597)
	at org.glassfish.deployment.autodeploy.AutoDeployer.deployAll(AutoDeployer.java:484)
	at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:412)
	at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:403)
	at org.glassfish.deployment.autodeploy.AutoDeployService$1.run(AutoDeployService.java:233)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: javax.ejb.CreateException: Initialization failed for Singleton MySingletonBean
	at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:564)
	at com.sun.ejb.containers.AbstractSingletonContainer.access$000(AbstractSingletonContainer.java:78)
	at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:734)
	... 31 more
Caused by: java.lang.reflect.InvocationTargetException
	at com.sun.ejb.containers.BaseContainer.createEjbInstanceAndContext(BaseContainer.java:1730)
	at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:512)
	... 33 more
Caused by: java.lang.NullPointerException
	at org.glassfish.weld.services.JCDIServiceImpl.createInterceptorInstance(JCDIServiceImpl.java:397)
	at com.sun.ejb.containers.BaseContainer.createEjbInterceptors(BaseContainer.java:1799)
	at com.sun.ejb.containers.BaseContainer.createEmptyContextAndInterceptors(BaseContainer.java:1694)
	at com.sun.ejb.containers.BaseContainer.createEjbInstanceAndContext(BaseContainer.java:1708)
	... 34 more
]]

[2018-04-17T14:44:48.335+0300] [Payara 5.181] [SEVERE] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=67 _ThreadName=AutoDeployer] [timeMillis: 1523965488335] [levelValue: 1000] [[
  Exception during lifecycle processing
javax.ejb.EJBException: javax.ejb.CreateException: Initialization failed for Singleton MySingletonBean
	at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:736)
	at com.sun.ejb.containers.AbstractSingletonContainer.instantiateSingletonInstance(AbstractSingletonContainer.java:438)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:219)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:180)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.doStartup(SingletonLifeCycleManager.java:158)
	at org.glassfish.ejb.startup.EjbApplication.start(EjbApplication.java:169)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:294)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:357)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:538)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:514)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:549)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:545)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:544)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:575)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:567)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:566)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1475)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1857)
	at org.glassfish.deployment.autodeploy.AutoOperation.run(AutoOperation.java:164)
	at org.glassfish.deployment.autodeploy.AutoDeployer.deploy(AutoDeployer.java:597)
	at org.glassfish.deployment.autodeploy.AutoDeployer.deployAll(AutoDeployer.java:484)
	at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:412)
	at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:403)
	at org.glassfish.deployment.autodeploy.AutoDeployService$1.run(AutoDeployService.java:233)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: javax.ejb.CreateException: Initialization failed for Singleton MySingletonBean
	at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:564)
	at com.sun.ejb.containers.AbstractSingletonContainer.access$000(AbstractSingletonContainer.java:78)
	at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:734)
	... 31 more
Caused by: java.lang.reflect.InvocationTargetException
	at com.sun.ejb.containers.BaseContainer.createEjbInstanceAndContext(BaseContainer.java:1730)
	at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:512)
	... 33 more
Caused by: java.lang.NullPointerException
	at org.glassfish.weld.services.JCDIServiceImpl.createInterceptorInstance(JCDIServiceImpl.java:397)
	at com.sun.ejb.containers.BaseContainer.createEjbInterceptors(BaseContainer.java:1799)
	at com.sun.ejb.containers.BaseContainer.createEmptyContextAndInterceptors(BaseContainer.java:1694)
	at com.sun.ejb.containers.BaseContainer.createEjbInstanceAndContext(BaseContainer.java:1708)
	... 34 more
]]

[2018-04-17T14:44:48.335+0300] [Payara 5.181] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=67 _ThreadName=AutoDeployer] [timeMillis: 1523965488335] [levelValue: 1000] [[
  Exception while loading the app]]

[2018-04-17T14:44:48.361+0300] [Payara 5.181] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=67 _ThreadName=AutoDeployer] [timeMillis: 1523965488361] [levelValue: 1000] [[
  Exception while loading the app : javax.ejb.CreateException: Initialization failed for Singleton MySingletonBean
javax.ejb.CreateException: Initialization failed for Singleton MySingletonBean
	at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:564)
	at com.sun.ejb.containers.AbstractSingletonContainer.access$000(AbstractSingletonContainer.java:78)
	at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:734)
	at com.sun.ejb.containers.AbstractSingletonContainer.instantiateSingletonInstance(AbstractSingletonContainer.java:438)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:219)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:180)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.doStartup(SingletonLifeCycleManager.java:158)
	at org.glassfish.ejb.startup.EjbApplication.start(EjbApplication.java:169)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:294)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:357)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:538)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:514)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:549)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:545)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:544)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:575)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:567)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:566)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1475)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1857)
	at org.glassfish.deployment.autodeploy.AutoOperation.run(AutoOperation.java:164)
	at org.glassfish.deployment.autodeploy.AutoDeployer.deploy(AutoDeployer.java:597)
	at org.glassfish.deployment.autodeploy.AutoDeployer.deployAll(AutoDeployer.java:484)
	at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:412)
	at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:403)
	at org.glassfish.deployment.autodeploy.AutoDeployService$1.run(AutoDeployService.java:233)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.reflect.InvocationTargetException
	at com.sun.ejb.containers.BaseContainer.createEjbInstanceAndContext(BaseContainer.java:1730)
	at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:512)
	... 33 more
Caused by: java.lang.NullPointerException
	at org.glassfish.weld.services.JCDIServiceImpl.createInterceptorInstance(JCDIServiceImpl.java:397)
	at com.sun.ejb.containers.BaseContainer.createEjbInterceptors(BaseContainer.java:1799)
	at com.sun.ejb.containers.BaseContainer.createEmptyContextAndInterceptors(BaseContainer.java:1694)
	at com.sun.ejb.containers.BaseContainer.createEjbInstanceAndContext(BaseContainer.java:1708)
	... 34 more
]]

[2018-04-17T14:44:48.384+0300] [Payara 5.181] [WARNING] [NCLS-DEPLOYMENT-02036] [javax.enterprise.system.tools.deployment.autodeploy] [tid: _ThreadID=67 _ThreadName=AutoDeployer] [timeMillis: 1523965488384] [levelValue: 900] [[
  Error occurred during deployment: Exception while loading the app : javax.ejb.CreateException: Initialization failed for Singleton MySingletonBean. Please see server.log for more details.]]

[2018-04-17T14:44:48.385+0300] [Payara 5.181] [WARNING] [NCLS-DEPLOYMENT-02036] [javax.enterprise.system.tools.deployment.autodeploy] [tid: _ThreadID=67 _ThreadName=AutoDeployer] [timeMillis: 1523965488385] [levelValue: 900] [[
  [AutoDeploy] Autodeploy failed : C:\payara\payara-5.181\payara5\glassfish\domains\domain1\autodeploy\TestPayaraMigration-ear-1.0-SNAPSHOT.ear.]]
```

## Steps to reproduce (Only for bug reports) 

* Create a simple EAR project with a bean `@Singleton` and `@Startup` and `@Inject` in it another bean or build the attached project

* Deploy the ear in Payara

### Samples

Maven project with beans
[TestPayaraMigration.zip](https://github.com/payara/Payara/files/1919564/TestPayaraMigration.zip)

## Context (Optional)

We are trying to migrate a project from GF3 to Payara 5.

## Environment ##

- **Payara Version**: 5.181
- **Edition**: Full
- **JDK Version**: 1.8.0_131
- **Operating System**: Windows
- **Database**: None

**Comment by lprimak** [comment]
Your example did not run correctly due to numerous issues with the code.
I fixed it (uploaded here) but the problem is not reproducible with the current master source tree.

[TestPayaraMigration.zip](https://github.com/payara/Payara/files/1922541/TestPayaraMigration.zip)

Could you please try to reproduce with the latest source tree build and please
upload a program that works / reproduces the problem without changes / fixes

**Comment by cristiG** [comment]
Thanks for looking at this.

The example provided was as close as possible to some parts from a bigger project that we want to migrate from GF3 to Payara 5. Our hope was to migrate with as little as possible changes (those 'numerous issues' derive from this and they can be deployed like that on GF3)

The fixed example deployed successfully on Payara 5.181
Looks like we will have to do some changes on the existing project if we want to migrate. 

Thank you again for this.

**Comment by lprimak** [comment]
You are very welcome

**Comment by dmatej** [comment]
On 5.181 I have a problem with the NPE on the same line. But my singleton bean is not the cause, the cause is in another beans (@Produces and @Inject); singleton has nothing to do with that but container still says "javax.ejb.EJBException: javax.ejb.CreateException: Initialization failed for Singleton xxx". It does not help much ...
If I remove the problematic code, the application works.

**Comment by shaap** [comment]
I have the same problem with another project, now on Payara 5.2022.1. Even if I completely clear the content of the offending Bean, only leaving 
`@Startup
@Singleton
class StartupBean
{

}`

it results in the same Error. However, if I comment out Singleton or Startup annotation, it works (but does not run the code, of course...)
