### ISSUE TITLE
GlassFish 3 to Payara Migration issue - Getting exception related to CDI when deploying the war on Payara which works on GlassFish 3

### ISSUE THREAD

**Issue by Rajvinder** [payara/Payara#2711]
# Description #
----------
I am trying to port an application war file deployed on Glassfish 3 to Payara 4.1.2. There are EJB components in the application but it builds into a war file and deploys and run on GlassFish 3 server. But, when I try to deploy on Payara 4, CDI error is displayed as:

**Error occurred during deployment: Exception while loading the app : CDI definition failure:HV000151: A method overriding another method must not alter the parameter constraint configuration....**

**Error StackTrace:**
Caused by: javax.validation.ConstraintDeclarationException: HV000151: A method overriding another method must not alter the parameter constraint configuration,...
at org.hibernate.validator.internal.metadata.aggregated.rule.OverridingMethodMustNotAlterParameterConstraints.apply(OverridingMethodMustNotAlterParameterConstraints.java:24)
	at org.hibernate.validator.internal.metadata.aggregated.ExecutableMetaData$Builder.assertCorrectnessOfConfiguration(ExecutableMetaData.java:460)
	at org.hibernate.validator.internal.metadata.aggregated.ExecutableMetaData$Builder.build(ExecutableMetaData.java:378)
	at org.hibernate.validator.internal.metadata.aggregated.BeanMetaDataImpl$BuilderDelegate.build(BeanMetaDataImpl.java:677)
	
Since I have EJB jars referred in the war file, I cannot disable Implicit CDI option because doing so following error is displayed on console:
Exception while loading the app : javax.ejb.CreateException: Initialization failed for Singleton {Class referring EJB objects} 

## Environment ##

- **Payara Version**: 4.1.2
- **Edition**: Full
- **JDK Version**: 8-Oracle
- **Operating System**: Windows
- **Database**: Oracle

**Comment by Rajvinder** [comment]
[test.zip](https://github.com/payara/Payara/files/1983677/test.zip)
Attaching a dummy project scenario where I am getting same issue. Please change the extension from zip to jar and try to deploy this jar file on Payara

**Comment by smillidge** [comment]
Hi this isn't a support portal. We do offer commercial support and assistance with application migration through www.payara.fish 

The error message is explicit `A method overriding another method must not alter the parameter constraint configuration,` this is the case in your sample code with your Bean Validation constraints.
