### ISSUE TITLE
ConcurrentModificationException when using WebFilters

### ISSUE THREAD

**Issue by parysto** [payara/Payara#2766]
# Description #
----------
Grizzly throws `ConcurrentModificationException`s when filters (WebFilters) are used and the application is accessed concurrently. As, for example, PrimeFaces implements and uses a filter, it is unusable with the current Payara version.

See https://github.com/eclipse-ee4j/grizzly/issues/1995

 

## Expected Outcome
No exception.

## Current Outcome

    Caused by: java.io.IOException: java.util.ConcurrentModificationException
	    at org.glassfish.grizzly.utils.Exceptions.makeIOException(Exceptions.java:82)
	    at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:160)
	    at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	    at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	    at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
	    at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	... 3 more
    Caused by: java.util.ConcurrentModificationException
	    at java.util.TreeMap$NavigableSubMap$SubMapIterator.nextEntry(Unknown Source)
	    at java.util.TreeMap$NavigableSubMap$SubMapEntryIterator.next(Unknown Source)
	    at java.util.TreeMap$NavigableSubMap$SubMapEntryIterator.next(Unknown Source)
	    at java.util.AbstractMap$2$1.next(Unknown Source)
	    at org.glassfish.grizzly.http2.Http2Session.pruneStreams(Http2Session.java:709)
	    at org.glassfish.grizzly.http2.Http2Session.setGoAwayLocally(Http2Session.java:682)
	    at org.glassfish.grizzly.http2.Http2Session.terminate(Http2Session.java:625)
	    at org.glassfish.grizzly.http2.Http2BaseFilter.processFrames(Http2BaseFilter.java:212)
	    at org.glassfish.grizzly.http2.Http2ServerFilter.handleRead(Http2ServerFilter.java:563)
	    at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	    at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	    at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	    at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	    ... 10 more

As a result, pages fail to load or resources (CSS, JS, ...) cannot be loaded. 

## Steps to reproduce (Only for bug reports) 

Use PrimeFaces 6.2 or add Filter (WebFilter) implementation and access pages concurrently.

### Samples
Sample Filter implementation:

    @WebFilter(servletNames = {"Faces Servlet"})
    public class NoCacheFilter implements Filter {

        @Override
        public void init(FilterConfig filterConfig) throws ServletException {
        }

        @Override
        public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {
            HttpServletRequest httpRequest = (HttpServletRequest) request;
            HttpServletResponse httpResponse = (HttpServletResponse) response;

            // To NOT disable caching on resources!
            if (!httpRequest.getRequestURI().startsWith(httpRequest.getContextPath() + ResourceHandler.RESOURCE_IDENTIFIER)) {
                httpResponse.setHeader(HttpHeaders.CACHE_CONTROL, "no-cache, no-store, must-revalidate");
                httpResponse.setHeader(HttpHeaders.PRAGMA, "no-cache");
                httpResponse.setDateHeader(HttpHeaders.EXPIRES, 0);
            }

            chain.doFilter(request, response);
        }

        @Override
        public void destroy() {
        }

    }

## Environment ##

- **Payara Version**: 5.181
- **Edition**: Full
- **JDK Version**:  Oracle 8u171
- **Operating System**: Windows
- **Database**: PostGres

**Comment by smillidge** [comment]
Looks like a possible HTTP2 problem. Have you tried with HTTP2 disabled?

**Comment by parysto** [comment]
With HTTP/2 disabled, Payara/Grizzly does not throw `ConcurrentModificationException`s anymore.

**Comment by svendiedrichsen** [comment]
I have provided a fix for this bug at the grizzly project. https://github.com/eclipse-ee4j/grizzly/pull/2009

**Comment by smillidge** [comment]
@svendiedrichsen thanks we will patch Grizzly locally for Payara

**Comment by svendiedrichsen** [comment]
@smillidge You are welcome. I will still wait for some reaction from the grizzly team.

**Comment by svendiedrichsen** [comment]
@smillidge The PR as been merged into grizzly master.

**Comment by smillidge** [comment]
I believe this is fixed in 5.183
