### ISSUE TITLE
Hazelcast Topic MessageListener Classloader Bug

### ISSUE THREAD

**Issue by mreppe** [payara/Payara#2777]
# Description #

It is not possible to access CDI Beans from a Hazelcast MessageListener.

## Expected Outcome
Reference to CDI Bean.

## Current Outcome
java.lang.IllegalStateException: Singleton not set for com.sun.enterprise.loader.CurrentBeforeParentClassLoader@228bda54
	at org.glassfish.weld.ACLSingletonProvider$ACLSingleton.get(ACLSingletonProvider.java:116)
	at org.jboss.weld.Container.instance(Container.java:53)
	at org.jboss.weld.SimpleCDI.<init>(SimpleCDI.java:77)
	at org.glassfish.weld.GlassFishWeldProvider$GlassFishEnhancedWeld.<init>(GlassFishWeldProvider.java:57)
	at org.glassfish.weld.GlassFishWeldProvider$GlassFishEnhancedWeld.<init>(GlassFishWeldProvider.java:57)
	at org.glassfish.weld.GlassFishWeldProvider.getCDI(GlassFishWeldProvider.java:96)
	at javax.enterprise.inject.spi.CDI.current(CDI.java:64)
	at com.hazelcast.example.LogMessageListener.getLogSink(LogMessageListener.java:18)
	at com.hazelcast.example.LogMessageListener.onMessage(LogMessageListener.java:14)
	at com.hazelcast.topic.impl.reliable.ReliableMessageListenerRunner.process(ReliableMessageListenerRunner.java:125)
	at com.hazelcast.topic.impl.reliable.ReliableMessageListenerRunner.onResponse(ReliableMessageListenerRunner.java:102)
	at com.hazelcast.topic.impl.reliable.ReliableMessageListenerRunner.onResponse(ReliableMessageListenerRunner.java:42)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:248)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)

## Steps to reproduce (Only for bug reports) 
Deploy hazelcast-cdi-example-client application.
Deploy hazelcast-cdi-example-server application.
GET request to the following URL http://localhost:8080/hazelcast-cdi-example-client/resources/hazelcast
The Server should write a random UUID to System.out.

### Samples
https://github.com/mreppe/hazelcast-cdi-example

## Environment ##
Payara 5.181 Full
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
Ubuntu 16.04

**Comment by lprimak** [comment]
Please add a vote / comment to this: https://github.com/hazelcast/hazelcast/pull/10874

That PR needs to be merged as part of fixes for issues such as this
