### ISSUE TITLE
StackOverflow on war deployment

### ISSUE THREAD

**Issue by ratcashdev** [payara/Payara#2835]
# Description #
----------

Payara console shows the following during a WAR deployment:
```
Warning:   Exception while dispatching an event
java.lang.StackOverflowError
	at java.lang.Class.getSimpleName(Class.java:1306)
	at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.insertObjectReference(ApplicationProcessor.java:928)
	at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.createSchema(ApplicationProcessor.java:897)
	at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.visitSchema(ApplicationProcessor.java:448)
	at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.insertObjectReference(ApplicationProcessor.java:931)
	at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.createSchema(ApplicationProcessor.java:897)
	at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.visitSchema(ApplicationProcessor.java:448)
	at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.insertObjectReference(ApplicationProcessor.java:931)
	at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.createSchema(ApplicationProcessor.java:897)
...
```
The deployment is nevertheless successful. The WAR does not use the microprofile API in any way.

## Expected Outcome

No stackoverflow exception

## Current Outcome

```java.lang.StackOverflowError
	at java.lang.Class.getSimpleName(Class.java:1306)
	at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.insertObjectReference(ApplicationProcessor.java:928)
```

## Steps to reproduce (Only for bug reports) 

Specific to a single WAR of mine. Will try to track it down.

## Environment ##

- **Payara Version**: 5.1.182
- **Edition**: FULL
- **JDK Version**: Oracle 1.8.0u172
- **Operating System**:  WINDOWS
- **Database**: H2
- **Config/domain**: domain1

**Comment by smillidge** [comment]
Fixed by #2837
