### ISSUE TITLE
Injection problems not detailed

### ISSUE THREAD

**Issue by ThomasSousa96** [payara/Payara#2850]
I'm using Payara Micro 5.181 and a dificultily that i have is when occur some injection problem using CDI.

Per exemple when i try inject a instance that have not an provider (@Produces) occurs the below exception:

```
[2018-06-13T16:02:44.924+0000] [] [WARNING] [NCLS-CORE-00069] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1528905764924] [levelValue: 900] [[
 Exception while dispatching an event
org.glassfish.api.invocation.InvocationException
	at org.glassfish.api.invocation.InvocationManagerImpl.postInvoke(InvocationManagerImpl.java:178)
	at org.glassfish.weld.WeldDeployer.processApplicationLoaded(WeldDeployer.java:522)
	at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:426)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:333)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:493)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:512)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:549)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:545)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:544)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:575)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:567)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:566)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1475)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1857)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1733)
	at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:134)
	at fish.payara.micro.impl.PayaraMicroImpl.deployAll(PayaraMicroImpl.java:1555)
	at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1019)
	at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
	at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:79)
	at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:383)
```

This exception not show the exact point of application that occurred the injection problem. This exception could show the cause exception, in other words the class and member that caused this exception.

I already did see another exception that show the dependency problem.

```
[2018-06-13T20:20:05.735+0000] [] [WARNING] [] [org.glassfish.jersey.internal.Errors] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1528921205735] [levelValue: 900] [[
   The following warnings have been detected: WARNING: Unknown HK2 failure detected:
 MultiException stack 1 of 1
 org.glassfish.hk2.api.UnsatisfiedDependencyException: There was no object available for injection at SystemInjecteeImpl(requiredType=Jsonb,parent=JsonWriter,qualifiers={},position=-1,optional=false,self=false,unqualified=null,2141994208)
  at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:75)
  at org.jvnet.hk2.internal.Utilities.justInject(Utilities.java:1012)
  at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:1008)
  at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.inject(AbstractHk2InjectionManager.java:231)
  at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.inject(ImmediateHk2InjectionManager.java:54)
  at org.glassfish.jersey.ext.cdi1x.internal.AbstractCdiBeanSupplier$2.getInstance(AbstractCdiBeanSupplier.java:112)
  at org.glassfish.jersey.ext.cdi1x.internal.AbstractCdiBeanSupplier._provide(AbstractCdiBeanSupplier.java:127)
  at org.glassfish.jersey.ext.cdi1x.internal.GenericCdiBeanSupplier.get(GenericCdiBeanSupplier.java:66)
  at org.glassfish.jersey.inject.hk2.InstanceSupplierFactoryBridge.provide(InstanceSupplierFactoryBridge.java:77)
  at org.jvnet.hk2.internal.FactoryCreator.create(FactoryCreator.java:153)
  at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
  at org.jvnet.hk2.internal.PerLookupContext.findOrCreate(PerLookupContext.java:70)
  at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
  at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
  at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:90)
  at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.lambda$getAllServiceHolders$0(AbstractHk2InjectionManager.java:160)
  at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
  at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
  at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
  at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getAllServiceHolders(AbstractHk2InjectionManager.java:164)
  at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getAllServiceHolders(ImmediateHk2InjectionManager.java:54)
  at org.glassfish.jersey.internal.inject.Providers.getServiceHolders(Providers.java:329)
  at org.glassfish.jersey.internal.inject.Providers.getProviders(Providers.java:157)
  at org.glassfish.jersey.message.internal.MessageBodyFactory.initialize(MessageBodyFactory.java:265)
  at org.glassfish.jersey.message.internal.MessageBodyFactory$MessageBodyWorkersConfigurator.postInit(MessageBodyFactory.java:136)
  at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$2(ApplicationHandler.java:372)
  at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
  at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:372)
  at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:316)
  at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
  at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
  at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:256)
  at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:315)
  at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:282)
  at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:335)
  at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:178)
  at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:370)
  at javax.servlet.GenericServlet.init(GenericServlet.java:244)
  at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1515)
  at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1323)
  at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5494)
  at org.apache.catalina.core.StandardContext.start(StandardContext.java:5739)
  at com.sun.enterprise.web.WebModule.start(WebModule.java:609)
  at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:956)
  at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:939)
  at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:684)
  at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:2099)
  at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1745)
  at com.sun.enterprise.web.WebApplication.start(WebApplication.java:107)
  at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123)
  at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:294)
  at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:357)
  at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:538)
  at fish.payara.deployment.admin.InitializeAllApplicationsCommand.execute(InitializeAllApplicationsCommand.java:75)

  at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:549)
  at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:545)
  at java.security.AccessController.doPrivileged(Native Method)
  at javax.security.auth.Subject.doAs(Subject.java:360)
  at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:544)
  at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:575)
  at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:567)
  at java.security.AccessController.doPrivileged(Native Method)
  at javax.security.auth.Subject.doAs(Subject.java:360)
  at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:566)
  at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1475)
  at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
  at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1857)
  at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1733)

  at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:169)
  at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:94)
  at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1029)

  at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:201)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
  at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
  at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
  at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:79)
  at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:383)

 
 ]]
```

This occurred when i define a @Provider with an dependency without provider.

**Comment by smillidge** [comment]
This is fixed in 5.182 which was released last week. Can you check with that version?

**Comment by ThomasSousa96** [comment]
I did a test with an dependency that is used in various classes. Now is displaying all places that is with dependency problem. Thanks!

**Comment by smillidge** [comment]
Thanks I will close this.
