### ISSUE TITLE
Cannot deploy on payara-full docker

### ISSUE THREAD

**Issue by mbering** [payara/Payara#2868]
# Description #
----------

Trying to deploy a war on the latest payara-full docker image, errors out upon starting container.

## Current Outcome

`Exception in thread "main" java.lang.NullPointerException
	at com.sun.enterprise.admin.launcher.JavaConfig.getJavaHome(JavaConfig.java:63)
	at com.sun.enterprise.admin.launcher.GFLauncher.setup(GFLauncher.java:188)
	at com.sun.enterprise.admin.servermgmt.cli.StartDomainCommand.createLauncher(StartDomainCommand.java:249)
	at com.sun.enterprise.admin.servermgmt.cli.StartDomainCommand.executeCommand(StartDomainCommand.java:143)
	at com.sun.enterprise.admin.cli.CLICommand.execute(CLICommand.java:324)
	at com.sun.enterprise.admin.cli.AdminMain.executeCommand(AdminMain.java:363)
	at com.sun.enterprise.admin.cli.AdminMain.doMain(AdminMain.java:298)
	at org.glassfish.admin.cli.AsadminMain.main(AsadminMain.java:56)`

## Context 

Dockerfile:
FROM payara/server-full
COPY tc.war $AUTODEPLOY_DIR

## Environment ##

- **Payara Version**: Payara 5
- **Edition**: Full
- **JDK Version**: OpenJDK 
- **Operating System**: Linux

**Comment by OndrejM** [comment]
I tried with payara/server-full:LATEST but I couldn't reproduce - the server starts without errors and an application is deployed.

The error is because Payara Server can't find JAVA installation and that's weird because we didn't do anything in the docker container except updating Payara Server.

**Comment by mbering** [comment]
It's working now. Appears to have been a config error on my end, thanks.
