### ISSUE TITLE
java.io.FileNotFoundException: /opt/payara5/glassfish/domains/domain1/keystore.jks

### ISSUE THREAD

**Issue by pioneer2k** [payara/Payara#2887]
# Description #
----------

After switching from Docker-Payara 5.181 to 5.182 we are receiving the exception below (see under 'Current Outcome') when using any of our REST-Services over SSL.

What we found out so far:
- our domain.xml is correct:
<jvm-options>-Djavax.net.ssl.keyStore=${com.sun.aas.instanceRoot}/config/keystore.jks</jvm-options>
- JSSESocketFactory logs this on code line 253, which means that the absolut path to the keystore file has been lost somewhere: 
[2018-06-21T17:23:17.628+0200] [Payara 5.182] [FEIN] [] [javax.enterprise.network.config] [tid: _ThreadID=37 _ThreadName=http-thread-pool::http-listener-2(4)] [timeMillis: 1529594597628] [levelValue: 500] [CLASSNAME: org.glassfish.grizzly.config.ssl.JSSESocketFactory] [METHODNAME: getKeystore] [[
  **Keystore file= keystore.jks**]]
- JSSESocketFactory is missing the absolut path to the keystore file on code line 307:
`                if (!keyStoreFile.isAbsolute()) {`
`                    keyStoreFile = new File(System.getProperty("catalina.base"),path);`
`                }`
- JSSESocketFactory add's the path of "catalina.base" to the keystore file which is only "/opt/payara5/glassfish/domains/domain1/"
- the path results in "/opt/payara5/glassfish/domains/domain1/keystore.jks", which is wrong

## Expected Outcome

No exception should occur.

## Current Outcome

[2018-06-22T11:49:44.465+0200] [Payara 5.182] [WARNUNG] [] [javax.enterprise.network.config] [tid: _ThreadID=34 _ThreadName=http-thread-pool::http-listener-2(1)] [timeMillis: 1529660984465] [levelValue: 900] [[
  GRIZZLY0050: SSL support could not be configured!
java.io.FileNotFoundException: /opt/payara5/glassfish/domains/domain1/keystore.jks (Datei oder Verzeichnis nicht gefunden)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.glassfish.grizzly.config.ssl.JSSESocketFactory.getStore(JSSESocketFactory.java:311)
	at org.glassfish.grizzly.config.ssl.JSSESocketFactory.getKeystore(JSSESocketFactory.java:259)
	at org.glassfish.grizzly.config.ssl.JSSE14SocketFactory.getKeyManagers(JSSE14SocketFactory.java:174)
	at org.glassfish.grizzly.config.ssl.JSSE14SocketFactory.init(JSSE14SocketFactory.java:143)
	at org.glassfish.grizzly.config.SSLConfigurator.initializeSSLContext(SSLConfigurator.java:262)
	at org.glassfish.grizzly.config.SSLConfigurator.configureSSL(SSLConfigurator.java:140)
	at org.glassfish.grizzly.config.SSLConfigurator$InternalSSLContextConfigurator.createSSLContext(SSLConfigurator.java:408)
	at org.glassfish.grizzly.ssl.SSLEngineConfigurator.createSSLEngine(SSLEngineConfigurator.java:185)
	at org.glassfish.grizzly.ssl.SSLEngineConfigurator.createSSLEngine(SSLEngineConfigurator.java:162)
	at org.glassfish.grizzly.ssl.SSLBaseFilter$SSLTransportFilterWrapper.handleRead(SSLBaseFilter.java:1111)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)

## Steps to reproduce (Only for bug reports) 

Implement a simple webservice, for example via Jersey:

`@GET`
`@Path("/healthcheck")`
`@Consumes(MediaType.TEXT_PLAIN + ";charset=utf-8")`
`@ApiOperation("health check operation that can be used for checking if the application is reachable")`
`	public String healthCheck() {`
`		return "OK";`
`	}`

## Environment ##

Payara Version: 5.182 and 5.183-SNAPSHOT
Edition: Docker payara/server-full
JDK Version: 1.8.0_171
Operating System: Linux 4.14.33-51.37.amzn1.x86_64

**Comment by pioneer2k** [comment]
Seems to be a misconfigured domain.xml. We rebuild or domain.xml based on a fresh installation of payara 5.182. Sorry....
