### ISSUE TITLE
Exception in org.eclipse.payara.tools

### ISSUE THREAD

**Issue by axestr** [payara/Payara#2935]
# Description #
----------

Getting exceptions in Eclipse with Payara Tools - is this the right place to report, or should I report to Eclipse developers?

## Expected Outcome

nothing

## Current Outcome

In eclipse log:

```

!ENTRY org.eclipse.jst.common.project.facet.core 4 -1 2018-07-05 11:38:16.580
!MESSAGE No property tester contributes a property org.eclipse.payara.tools.internal.containsRuntimeComponentType to type class org.eclipse.wst.common.project.facet.core.runtime.internal.BridgedRuntime
!STACK 1
org.eclipse.core.runtime.CoreException: No property tester contributes a property org.eclipse.payara.tools.internal.containsRuntimeComponentType to type class org.eclipse.wst.common.project.facet.core.runtime.internal.BridgedRuntime
	at org.eclipse.core.internal.expressions.TypeExtensionManager.getProperty(TypeExtensionManager.java:127)
	at org.eclipse.core.internal.expressions.TestExpression.evaluate(TestExpression.java:97)
	at org.eclipse.core.internal.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:51)
	at org.eclipse.core.internal.expressions.IterateExpression.evaluate(IterateExpression.java:174)
	at org.eclipse.core.internal.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:51)
	at org.eclipse.core.internal.expressions.WithExpression.evaluate(WithExpression.java:75)
	at org.eclipse.core.internal.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:51)
	at org.eclipse.core.internal.expressions.EnablementExpression.evaluate(EnablementExpression.java:55)
	at org.eclipse.jst.common.project.facet.core.libprov.internal.LibraryProvider.isEnabledFor(LibraryProvider.java:287)
	at org.eclipse.jpt.jpa.core.internal.AbstractJpaProject.validateLibraryProvider_(AbstractJpaProject.java:1480)
	at org.eclipse.jpt.jpa.core.internal.AbstractJpaProject.validateLibraryProvider(AbstractJpaProject.java:1466)
	at org.eclipse.jpt.jpa.core.internal.AbstractJpaProject.validate(AbstractJpaProject.java:1459)
	at org.eclipse.jpt.jpa.core.internal.AbstractJpaProject.getValidationMessages(AbstractJpaProject.java:1449)
	at org.eclipse.jpt.jpa.core.internal.InternalJpaProjectManager.buildValidationMessages_(InternalJpaProjectManager.java:585)
	at org.eclipse.jpt.jpa.core.internal.InternalJpaProjectManager$BuildValidationMessagesCommand.execute(InternalJpaProjectManager.java:573)
	at org.eclipse.jpt.common.core.internal.utility.command.CommandJobCommandAdapter.execute(CommandJobCommandAdapter.java:50)
	at org.eclipse.jpt.common.core.internal.utility.command.JobCommandJob.run(JobCommandJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
!SUBENTRY 1 org.eclipse.core.expressions 4 201 2018-07-05 11:38:16.580
!MESSAGE No property tester contributes a property org.eclipse.payara.tools.internal.containsRuntimeComponentType to type class org.eclipse.wst.common.project.facet.core.runtime.internal.BridgedRuntime
```

## Steps to reproduce (Only for bug reports) 

On Win10 machine
- Install jre 1.8.0_172 (8u172) 64bit
- Install Eclipse 4.8 (Photon)
- Install Payara Tools with Eclipse Marketplace (  Payara Tools	1.0.0.201804032346)
- Register a Payara Server with Payara Tools
- In Eclipse, generate new Dynamic Web Project with Target Runtime Payara Server 5 (5.182) and Configuration "Default Configuration for Payara Server 5 (5.182)
- press Next ... Exception wir occur

### Samples

See above

## Environment ##

- **Payara Tools**: 1.0.0.201804032346
- **Payara Version**:  5.1.82
- **Edition**: Full
- **JDK Version**:  8 u172 - OpenJDK 
- **Operating System**:  Eclipse Windows 10, Server CentOS 7
- **Database**:  na

**Comment by smillidge** [comment]
A better place to raise the issue is https://github.com/payara/ecosystem-eclipse-glassfish-plugin

**Comment by axestr** [comment]
thx, redirected to https://github.com/payara/ecosystem-eclipse-glassfish-plugin/issues/3
