### ISSUE TITLE
OutOfMemory and DOS with large number of sessions

### ISSUE THREAD

**Issue by ratcashdev** [payara/Payara#2960]
# Description #
----------

GC overhead limit exceeded when repeatedly accessing a (simple) JSP page (through HTTP, port 8080, `/SimpleHelloWorld/testpage.jsp` ) with multiple threads (20).

## Expected Outcome

Performance of the server is constant, no slowdowns, no OOM.

## Current Outcome

The performance of Payara slows down, ultimately resulting in OOM. The server is not able to recover from this situation.
```
Warning:   GRIZZLY0013: Exception during FilterChain execution
java.lang.IllegalStateException: java.lang.OutOfMemoryError: GC overhead limit exceeded
```
Full log here: https://gist.github.com/ratcashdev/0938d6cc5a0fd527bf0168c9d330de01

## Steps to reproduce (Only for bug reports) 

1 -**Start the domain** from within NetBeans. Alternatively asadmin should also be enough, (although this was not tested by me):

    ./asadmin start-domain domain1

2 -**Deploy a WAR** containing a single (static) JSP file, like this:
```
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>I will cause an OutOfMemory!</h1>
    </body>
</html>
```

3 - **Set up JMeter** to access this page (called testpage.jsp) with 20 threads in a never-ending loop.

## Environment ##

- **Payara Version**: from 4.1.2.181 (possibly even lower versions) up to and including the latest nightly build of 5.1.x by Jenkins from 16/7/2018
- **Edition**: FULL
- **JDK Version**: 1.8.0_u172
- **Operating System**: Windows
- **Database**: N/A
- **JVM Options**
```
-Djava.awt.headless=true
-Djdk.corba.allowOutputStreamSubclass=true
-Djavax.xml.accessExternalSchema=all
-Djavax.management.builder.initial=com.sun.enterprise.v3.admin.AppServerMBeanServerBuilder
-Djava.endorsed.dirs=C:\Users\WindowsUser\Apps\payara41\glassfish/modules/endorsed;C:\Users\WindowsUser\Apps\payara41\glassfish/lib/endorsed
-Djava.security.policy=C:\Users\WindowsUser\Apps\payara41\glassfish\domains\domain1/config/server.policy
-Djava.security.auth.login.config=C:\Users\WindowsUser\Apps\payara41\glassfish\domains\domain1/config/login.conf
-Dcom.sun.enterprise.security.httpsOutboundKeyAlias=s1as
-Xmx512m
-Djavax.net.ssl.keyStore=C:\Users\WindowsUser\Apps\payara41\glassfish\domains\domain1/config/keystore.jks
-Djavax.net.ssl.trustStore=C:\Users\WindowsUser\Apps\payara41\glassfish\domains\domain1/config/cacerts.jks
-Djava.ext.dirs=C:\Program Files\Java\jdk1.8.0_172/lib/ext;C:\Program Files\Java\jdk1.8.0_172/jre/lib/ext;C:\Users\WindowsUser\Apps\payara41\glassfish\domains\domain1/lib/ext
-Djdbc.drivers=org.apache.derby.jdbc.ClientDriver
-DANTLR_USE_DIRECT_CLASS_LOADING=true
-Dcom.sun.enterprise.config.config_environment_factory_class=com.sun.enterprise.config.serverbeans.AppserverConfigEnvironmentFactory
-Dorg.glassfish.additionalOSGiBundlesToStart=org.apache.felix.shell,org.apache.felix.gogo.runtime,org.apache.felix.gogo.shell,org.apache.felix.gogo.command,org.apache.felix.shell.remote,org.apache.felix.fileinstall
-Dosgi.shell.telnet.port=6666
-Dosgi.shell.telnet.maxconn=1
-Dosgi.shell.telnet.ip=127.0.0.1
-Dgosh.args=--nointeractive
-Dfelix.fileinstall.dir=C:\Users\WindowsUser\Apps\payara41\glassfish/modules/autostart/
-Dfelix.fileinstall.poll=5000
-Dfelix.fileinstall.log.level=2
-Dfelix.fileinstall.bundles.new.start=true
-Dfelix.fileinstall.bundles.startTransient=true
-Dfelix.fileinstall.disableConfigSave=false
-Dcom.ctc.wstx.returnNullForDefaultNamespace=true
-Djdk.tls.rejectClientInitiatedRenegotiation=true
-Dorg.jboss.weld.serialization.beanIdentifierIndexOptimization=false
-Dorg.glassfish.grizzly.DEFAULT_MEMORY_MANAGER=org.glassfish.grizzly.memory.HeapMemoryManager
-Dcom.sun.aas.derbyRoot=C:\Users\WindowsUser\Apps\payara41\javadb
-Dcom.sun.aas.instanceRoot=C:\Users\WindowsUser\Apps\payara41\glassfish\domains\domain1
-Dcom.sun.aas.installRoot=C:\Users\WindowsUser\Apps\payara41\glassfish
-Dcom.sun.aas.javaRoot=C:\Program Files\Java\jdk1.8.0_172
```

![payara-memory](https://user-images.githubusercontent.com/2928922/42754349-737de670-88f4-11e8-9b1a-66e0ec07722e.png)

**Comment by MattGill98** [comment]
Hi @ratcashdev,

Thank you for raising this issue. I've reproduced it, and created internal issue `PAYARA-2914` to address it.

Kind regards,

Matt

**Comment by ratcashdev** [comment]
Did a heap-dump.
75% of the memory is used by `org.apache.catalina.session.StandardManager#sessions` field. This explains a lot.
 
By default, Payara (both in `domain1` config and `production` config) stores sessions in memory. Since the JMeter test did not include a Cookie Manager, every request created a new session, which filled up the memory.

This makes it extremely likely (and easy) to DOS a running server in the default config that may never recover and need a hard kill / restart. I would propose to reconsider the defaults.

Somewhat good news is that if the server does not reach a state where OOM exceptions starts to appear, then after the DefaultSessionTimeout expires, the memory is freed up.

What i am missing, however, is that the GUI config does not offer a straightforward way to change the session persistence config for the web-container (no pre-defined values, no help, etc.)

Second, even if I set the `Directory` field for the Store Properties of the Web Container to e.g. `${com.sun.aas.instanceRoot}/sessions`, it does not use it. Sessions are still kept in memory only.

It's strange, according to the sources (`org.glassfish.web.config.serverbeans`) the domain.xml does not allow specifying the (Session) `Manager` interface's implementation (e.g. to use `org.apache.catalina.session.PersistentManager.java`) class.

**Comment by ratcashdev** [comment]
One more thing: even though the GUI says on the `Store Properties` page for Web-Container that:
"Absolute or relative pathname of the directory into which individual session files are written.  "

setting the Directory for session files like ` <store-properties directory="${com.sun.aas.instanceRoot}/sessions"></store-properties>` has no effect. No files were created.

**Comment by smillidge** [comment]
#3048 #2980 #2874 are all related so this will need a retest after 183 release.

**Comment by aapablaza** [comment]
Will the solution be ready for version 5.183?

**Comment by smillidge** [comment]
This should be fixed in 5.183

**Comment by aapablaza** [comment]
@MattGill98 @smillidge please re-open.

**Comment by ratcashdev** [comment]
@MattGill98 kind reminder to reopen this issue.

**Comment by MattGill98** [comment]
Hi @ratcashdev,

The file persistence type defines what should happen to sessions when the maximum number of available sessions is exceeded. As you've correctly noted the default is no maximum. To configure this, you can either do so from the admin console, or from the same glassfish-web.xml like so:

~~~
<session-manager persistence-type="file">
    <manager-properties>
        <property name="maxSessions" value="100" />
    </manager-properties>
</session-manager>
~~~

The fixes made in 5.183 allow the different persistence types to function correctly. In other words once the maximum number of sessions and persistence type is configured, a memory leak should not occur.

Does this answer your question?

Kind regards,

Matt

**Comment by MattGill98** [comment]
Hi @ratcashdev,

This option is found under 'Availability Service' -> 'Web Container'.

**Comment by ratcashdev** [comment]
parts of my domain.xml look like this:
```
...
<web-container>
        <session-config>
          <session-manager>
            <store-properties directory="${com.sun.aas.instanceRoot}/sessions"></store-properties>
            <manager-properties session-file-name="mysession" max-sessions="30"></manager-properties>
          </session-manager>
          <session-properties></session-properties>
        </session-config>
      </web-container>
...
<availability-service>
        <web-container-availability persistence-type="file"></web-container-availability>
        <ejb-container-availability sfsb-store-pool-name="jdbc/hastore"></ejb-container-availability>
        <jms-availability></jms-availability>
      </availability-service>
```
After 30 sessions, all subsequent requests finish with HTTP-500 (NullPointerException):
```
[2018-09-21T14:20:24.548+0200] [Payara 5.183] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=321 _ThreadName=http-thread-pool::http-listener-1(16)] [timeMillis: 1537532424548] [levelValue: 900] [[
  StandardWrapperValve[jsp]: Servlet.service() for servlet jsp threw exception
java.lang.NullPointerException
	at org.apache.jsp.sample_jsp._jspService(sample_jsp.java:37)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1628)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:258)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:755)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:575)

```
Experimented further.
NPE is thrown whenever maxSessions is set (regardless of persistence type and session manager/store settings). I wonder what am I doing wrong, and how did this work for you?

**Comment by MattGill98** [comment]
Hi @ratcashdev,

The difference seemed to be that I was using the `clusterjsp.war` for this - which seems to work. When using a plain JSP I find the same as you. This is certainly strange, thank you for raising it. I'm starting an investigation into previous issue `PAYARA-2926` which I feel potentially caused this issue, or is certainly related.

Kind regards,

Matt

**Comment by ratcashdev** [comment]
Summing up my current findings:

1. if max sessions are not set, sessions are not persisted (regardless of the settings in the web.xml/glassfish.xml/domain.xml). This results in OOM and DoS
2. if max sessions are set, JSPs can't be used (NPE).
3. if max sessions are set, and JSP are not used, sessions are not persisted. Clients connecting after `max-sessions` has been reached receive HTTP 500. Certainly less than ideal, however, OOM and DoS is not a threat.

Thus all-in-all, session persistence still does not work and the out-of-the box configuration is simply dangerous to run in production and not reliable. I very am surprised to see this issue does not have a target milestone set.

**Comment by ratcashdev** [comment]
@MattGill98 Dear Matt, thank you for the investigation. It's good to see that there is a way to make this works. Would nice to have this somewhere documented as well, and your comment in this ticket is a very good start.

So at the end of the day, Payara, out of the box, won't provide resilience against OOM. It's not the admin's job, but the DEV's job (editing web.xml and glassfish-web.xml) to configure it properly, though in days of payara-micro, docker and devops this may be ok. I still find it strange that the dev would need to know the path, where to persist session on a production machine. Don't you think so?

I guess I was looking for behavior similar to Tomcat, where session persistence (without having a MAX) is an application server configuraiton, on by default, w/o any effort of the app's developer to ensure that whatever you deploy is guaranteed to work and not result in OOM.
And what I find really strange is that (at least according to this ticket) I am the only one having these kind of issues. As if everyone else knew how to tackle it. Surely, if they only use Payara to run corporate intranet solutions, this is less of a concern. Would be interesting to do a scan of all the web-apps running on Payara to see how much of them are 'secure' and robust in this sense.
