### ISSUE TITLE
Build of payara-minimal fails if the default JDK in OS is JDK9 or newer

### ISSUE THREAD

**Issue by dmatej** [payara/Payara#3001]
# Description #
----------

Maven build respects JAVA_HOME set in ~/.mavenrc except in the payara-minimal phase where it ignores this setting and runs create-domain with the default java program in the OS, which is in newer systems obviously the newest stable JDK  (f.e. in Kubuntu 18.04 it is JDK 10.0.1]. Build then fails with NPE from create-domain.

## Expected Outcome

The build respects the AS_JAVA environment property. 
In this phase (or the whole build?) it should be set to the same value as JAVA_HOME value.

## Current Outcome

```
[INFO] --- glassfishbuild-maven-plugin:3.2.20.payara-p1:exec (create-domain) @ payara-minimal ---
[INFO] executable: /home/dmatej/work/repo/git/Payara/nucleus/distributions/payara-minimal/target/stage/nucleus/bin/nadmin
[INFO] commandLineArgs: --user admin create-domain --nopassword --savelogin=true --checkports=false --portbase=5000 --keytooloptions CN=localhost domain1
[INFO] [exec] Exception in thread "main" java.lang.NullPointerException
[INFO] [exec]   at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.initializeServiceLocator(AbstractModulesRegistryImpl.java:152)
[INFO] [exec]   at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.newServiceLocator(AbstractModulesRegistryImpl.java:144)
[INFO] [exec]   at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.createServiceLocator(AbstractModulesRegistryImpl.java:218)
[INFO] [exec]   at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.createServiceLocator(AbstractModulesRegistryImpl.java:224)
[INFO] [exec]   at com.sun.enterprise.module.single.StaticModulesRegistry.createServiceLocator(StaticModulesRegistry.java:88)
[INFO] [exec]   at com.sun.enterprise.admin.cli.CLIContainer.getServiceLocator(CLIContainer.java:212)
[INFO] [exec]   at com.sun.enterprise.admin.cli.CLIContainer.getLocalCommand(CLIContainer.java:244)
[INFO] [exec]   at com.sun.enterprise.admin.cli.CLICommand.getCommand(CLICommand.java:229)
[INFO] [exec]   at com.sun.enterprise.admin.cli.AdminMain.executeCommand(AdminMain.java:362)
[INFO] [exec]   at com.sun.enterprise.admin.cli.AdminMain.doMain(AdminMain.java:298)
[INFO] [exec]   at com.sun.enterprise.admin.cli.AdminMain.main(AdminMain.java:206)
```
## Steps to reproduce (Only for bug reports) 

1 -**  Ensure that AS_JAVA is not set (f.e. look to result of ```env | grep AS_JAVA```)

2 - ** Ensure that the default java is JDK9/10 (see ```java -version```)

3 -**  Start the build (f.e. ```mvn clean install```)

**Comment by OndroMih** [comment]
Support for running Payara Server on JDK11 and later also build it on JDK11 is in the roadmap for year 2019. I'll close this issue
