### ISSUE TITLE
asadmin commands with quotes are not parsed properly in postbootcommandfile

### ISSUE THREAD

**Issue by murdos** [payara/Payara#3005]
# Description #
----------

When using a postbootcommandfile, all double quotes are removed and this induces some unexpected behavior and prevents correct usage of asadmin subcommands.
#1866 is marked as fixed, but some cases described bellow are not handled correctly.

## Expected Outcome

The commands are executed successfully, in these specific cases: JDBC connection pool with an URL property, and a simple custom-resource with a description containing spaces.
It's also expected that the same command, tested with asadmin multimode, works in a postbootcommandfile, but it's not true.

## Steps to reproduce (Only for bug reports) 

1 - Create a postboot.cli with the following instructions

    create-jdbc-connection-pool  --datasourceclassname oracle.jdbc.pool.OracleDataSource  --restype javax.sql.DataSource  --property user=USER:password=PASSWORD:URL="jdbc\\:oracle\\:thin\\:DBHOST\\:DBPORT\\:DBNAME"  OraclePool

    create-custom-resource --restype java.lang.String --factoryclass org.glassfish.resources.custom.factory.PrimitivesAndStringFactory --description "My long description" --property value=SystemTest  jsf/ProjectStage

2 -  Create the Dockerfile

    FROM payara/server-full:174
    ADD --chown=payara:payara /postboot.cli ${POSTBOOT_COMMANDS}

3 -  Build the docker image and run it

    docker build -t payara-bug-demo .
    docker run -it payara-bug-demo

Issues are shown in log:

```
  Running command: create-jdbc-connection-pool  --datasourceclassname oracle.jdbc.pool.OracleDataSource  --restype javax.sql.DataSource  --property user=USER:password=PASSWORD:URL=jdbc\\:oracle\\:thin\\:DBHOST\\:DBPORT\\:DBNAME  OraclePool|#]

[#|2018-07-30T14:35:11.403+0000|SEVERE|Payara 4.1|javax.enterprise.system.core|_ThreadID=1;_ThreadName=main;_TimeMillis=1532961311403;_LevelValue=1000;_MessageID=NCLS-CORE-00003;|
  Exception while running a command
java.lang.IllegalArgumentException: Invalid property syntax, missing property value: oracle\\
        at org.glassfish.common.util.admin.MapInjectionResolver.convertStringToProperties(MapInjectionResolver.java:518)
        at org.glassfish.common.util.admin.MapInjectionResolver.convertStringToObject(MapInjectionResolver.java:376)
        at org.glassfish.common.util.admin.MapInjectionResolver.getValue(MapInjectionResolver.java:180)
        at org.jvnet.hk2.config.InjectionManager.syncDoInject(InjectionManager.java:169)
        at org.jvnet.hk2.config.InjectionManager.inject(InjectionManager.java:74)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.injectParameters(CommandRunnerImpl.java:373)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1229)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1851)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1727)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:169)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:94)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.runCommand(GlassFishMain.java:235)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.doBootCommands(GlassFishMain.java:275)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:130)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:104)
        at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:54)
```

And the second one:

```
  Running command: create-custom-resource --restype java.lang.String --factoryclass org.glassfish.resources.custom.factory.PrimitivesAndStringFactory --description My long description --property value=SystemTest  jsf/ProjectStage# deployments after boot|#]

[#|2018-07-30T14:35:11.592+0000|SEVERE|Payara 4.1|javax.enterprise.system.core|_ThreadID=1;_ThreadName=main;_TimeMillis=1532961311592;_LevelValue=1000;_MessageID=NCLS-CORE-00003;|
  Exception while running a command
org.glassfish.common.util.admin.UnacceptableValueException: Invalid parameter: jndi_name.  This parameter may not have more than one value.
        at org.glassfish.common.util.admin.MapInjectionResolver.convertListToObject(MapInjectionResolver.java:413)
        at org.glassfish.common.util.admin.MapInjectionResolver.getValue(MapInjectionResolver.java:141)
        at org.jvnet.hk2.config.InjectionManager.syncDoInject(InjectionManager.java:169)
        at org.jvnet.hk2.config.InjectionManager.inject(InjectionManager.java:74)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.injectParameters(CommandRunnerImpl.java:373)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1229)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1851)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1727)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:169)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:94)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.runCommand(GlassFishMain.java:235)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.doBootCommands(GlassFishMain.java:275)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:130)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:104)
        at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:54)

```

## Comparison with asadmin in multimode

     docker run -it --entrypoint bash payara-bug-demo
     ${PAYARA_PATH}/bin/asadmin start-domain
     echo "AS_ADMIN_PASSWORD=admin" > /tmp/payarapwd
     ${PAYARA_PATH}/bin/asadmin --user admin --passwordfile /tmp/payarapwd multimode < ${POSTBOOT_COMMANDS}

Successful output:
```
Use "exit" to exit and "help" for online help.
JDBC connection pool OraclePool created successfully.
Command create-jdbc-connection-pool executed successfully.
Custom Resource jsf/ProjectStage created.
Command create-custom-resource executed successfully.
Command multimode executed successfully.
```

## Environment ##

- **Payara Version**: 4.1.2.174 - Official Docker image
- **Edition**: Full
- **Database**: Oracle

**Comment by smillidge** [comment]
Have you tried this on Payara 5?

**Comment by murdos** [comment]
I just tried, and the issue is the same:

```
[#|2018-08-27T17:27:13.586+0000|INFO|Payara 5.182||_ThreadID=1;_ThreadName=main;_TimeMillis=1535390833586;_LevelValue=800;|
  Running command: create-jdbc-connection-pool  --datasourceclassname oracle.jdbc.pool.OracleDataSource  --restype javax.sql.DataSource  --property user=USER:password=PASSWORD:URL=jdbc\\:oracle\\:thin\\:DBHOST\\:DBPORT\\:DBNAME  OraclePool|#]

[#|2018-08-27T17:27:13.797+0000|SEVERE|Payara 5.182|javax.enterprise.system.core|_ThreadID=1;_ThreadName=main;_TimeMillis=1535390833797;_LevelValue=1000;_MessageID=NCLS-CORE-00003;|
  Exception while running a command
java.lang.IllegalArgumentException: Invalid property syntax, missing property value: oracle\\
        at org.glassfish.common.util.admin.MapInjectionResolver.convertStringToProperties(MapInjectionResolver.java:518)
        at org.glassfish.common.util.admin.MapInjectionResolver.convertStringToObject(MapInjectionResolver.java:376)
        at org.glassfish.common.util.admin.MapInjectionResolver.getValue(MapInjectionResolver.java:180)
        at org.jvnet.hk2.config.InjectionManager.syncDoInject(InjectionManager.java:170)
        at org.jvnet.hk2.config.InjectionManager.inject(InjectionManager.java:74)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.injectParameters(CommandRunnerImpl.java:378)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1234)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1857)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1733)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:172)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:96)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.runCommand(GlassFishMain.java:235)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.doBootCommands(GlassFishMain.java:275)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:130)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:104)
        at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:54)
|#]
```

**Comment by MattGill98** [comment]
Fixed by https://github.com/payara/Payara/pull/3312.
