### ISSUE TITLE
Very first MessageProducer#send(Message, ...) invocation fails as Transaction is not started

### ISSUE THREAD

**Issue by mkarg** [payara/Payara#3015]
# Description #
----------

After booting Payara 4.1.2.181, the very first invocation of `MessageProduce#send(Message, ...)` fails because the transaction is not started, but all _subsequent_ invocations do work well!

## Expected Outcome

JMS message is sent.

## Current Outcome

JMS message is _not_ sent.

server.log contains:

```
[2018-08-03T10:33:41.121+0200] [Payara 4.1] [SCHWERWIEGEND] [] [de.quipsy.common.AbstractSessionBean] [tid: _ThreadID=26 _ThreadName=http-thread-pool::http-listener-1(2)] [timeMillis: 1533285221121] [levelValue: 1000] [[
  JMSException in AbstractSessionBean.handleJMSException: {0}
javax.jms.JMSException: MQJMSRA_DS4001: JMSServiceException on send message:sendMessage: Sending message failed. Connection ID: 6812649907290049792 Caused by:com.sun.messaging.jmq.jmsserver.util.BrokerException: [B4403]: Exception on processing produced message PacketReference[336-192.168.0.59(cf:14:25:d8:5b:aa)-1-1533285221112][TID=6812649907367895552, null]: Unexpected Broker Exception: [Transaction 6812649907367895552[COMPLETE(4)]: is not in STARTED(1) state]
        at com.sun.messaging.jms.ra.DirectSession._sendMessage(DirectSession.java:1995)
        at com.sun.messaging.jms.ra.DirectProducer._send(DirectProducer.java:1138)
        at com.sun.messaging.jms.ra.DirectProducer.send(DirectProducer.java:490)
```

## Steps to reproduce (Only for bug reports) 

`asadmin start-domain`

Invoke an EJB which does:

```java
Session session = this.beginJmsSession(); // create transacted, auto-ack'ed session
try {
    MessageProducer producer = this.beginJmsMessageProducer(); // create topic producer
    try {
        Message message = session.createObjectMessage(messageObject);
        message.setJMSType("...");
        producer.send(message, deliveryMode, priority, timeToLive); // fails
    } finally {
        this.endJmsMessageProducer();
    }
} finally {
    this.endJmsSession();
}
```

## Environment ##

- **Payara Version**: 4.1.2.181
- **Edition**: Full
- **JDK Version**: Oracle JRE 18.0_161
- **Operating System**: Windows
- **Database**: SQL Anywhere 17
- **JMS Config**: domain1 (EMBEDDED)

**Comment by smillidge** [comment]
Does this happen in Payara 5.x? Payara 4.x is no longer maintained in the community stream.

**Comment by smillidge** [comment]
Closing due to inactivity

**Comment by mkarg** [comment]
FYI I could not test it with 5.x due to the three open bug reports of mine being untouched by you since February.
