### ISSUE TITLE
CDI Injection in entity listener fails most of the times.

### ISSUE THREAD

**Issue by TheOnlyAl** [payara/Payara#3121]
# Description #
----------
CDI injection sometimes does not work for entity listeners after application deployment.

## Expected Outcome

CDI injection into an entity listener always works.

## Current Outcome

Most of the times the injection does not work after application deployment.
After some debugging and enabling of eclipselink logging, I found out that eclpiselink can not create the injection manager since it has problems finding the bean manager:
```
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.eclipse.persistence.internal.security.PrivilegedAccessHelper.invokeConstructor(PrivilegedAccessHelper.java:505)
at org.eclipse.persistence.internal.sessions.AbstractSession.createInjectionManager(AbstractSession.java:1218)
at org.eclipse.persistence.internal.sessions.AbstractSession.getInjectionManager(AbstractSession.java:2338)
at org.eclipse.persistence.mappings.converters.ConverterClass.getAttributeConverterInstance(ConverterClass.java:114)
at org.eclipse.persistence.mappings.converters.ConverterClass.constructAttributeConverter(ConverterClass.java:89)
at org.eclipse.persistence.mappings.converters.ConverterClass.convertClassNamesToClasses(ConverterClass.java:83)
at org.eclipse.persistence.mappings.DatabaseMapping.convertConverterClassNamesToClasses(DatabaseMapping.java:477)
at org.eclipse.persistence.mappings.foundation.AbstractColumnMapping.convertClassNamesToClasses(AbstractColumnMapping.java:137)
at org.eclipse.persistence.mappings.foundation.AbstractDirectMapping.convertClassNamesToClasses(AbstractDirectMapping.java:459)
at org.eclipse.persistence.descriptors.ClassDescriptor.convertClassNamesToClasses(ClassDescriptor.java:1731)
at org.eclipse.persistence.sessions.Project.convertClassNamesToClasses(Project.java:519)
at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:674)
at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:216)
at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:324)
at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:348)
at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:311)
at org.glassfish.persistence.jpa.JPADeployer$2.visitPUD(JPADeployer.java:461)
at org.glassfish.persistence.jpa.JPADeployer$PersistenceUnitDescriptorIterator.iteratePUDs(JPADeployer.java:525)
at org.glassfish.persistence.jpa.JPADeployer.iterateInitializedPUsAtApplicationPrepare(JPADeployer.java:507)
at org.glassfish.persistence.jpa.JPADeployer.event(JPADeployer.java:405)
at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:490)
at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:540)
at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:549)
at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:545)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:360)
at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:544)
at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:575)
at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:567)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:360)
at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:566)
at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1475)
at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1857)
at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1733)
at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:263)
at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:234)
at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:285)
at org.glassfish.admin.rest.resources.TemplateListOfResource.createResource(TemplateListOfResource.java:136)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:704)
at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:377)
at org.glassfish.admin.rest.adapter.RestAdapter$2.service(RestAdapter.java:322)
at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:182)
at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:516)
at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:213)
at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:208)
at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:208)
at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
at java.lang.Thread.run(Thread.java:748)
Caused by: javax.naming.NamingException: Lookup failed for 'java:comp/BeanManager' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming} [Root exception is javax.naming.NamingException: Invocation exception: Got null ComponentInvocation ]
at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:496)
at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:442)
at javax.naming.InitialContext.lookup(InitialContext.java:417)
at javax.naming.InitialContext.lookup(InitialContext.java:417)
at org.eclipse.persistence.internal.sessions.cdi.InjectionManagerImpl.<init&gt;(InjectionManagerImpl.java:47)
... 102 more
Caused by: javax.naming.NamingException: Invocation exception: Got null ComponentInvocation
at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.getComponentId(GlassfishNamingManagerImpl.java:862)
at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.lookup(GlassfishNamingManagerImpl.java:734)
at com.sun.enterprise.naming.impl.JavaURLContext.lookup(JavaURLContext.java:167)
at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:476)
... 106 more
]]
```
## Steps to reproduce (Only for bug reports)

I tried to create a minimalistic project to be able to reproduce this behavior, but did not succeed.

## Context (Optional)

This problem seems like a rather tricky one, here are some additional information:

- The problem does not occur on every deploy. Sometimes injection does just work fine. Since i also could not reproduce it in a minimalistic app, I believe it maybe something like a race condition. But I am not sure.
- The deployed application is rather large and consists of an EAR with two WAR files and an EJB module
- As a workaround i currently check if the injected field is set, otherwise I do manual lookup of the bean
- Listener in question is used for auditing entities

## Environment ##

- **Payara Version**: 5.182
- **Edition**: Full
- **JDK Version**: Oracle JDK 8
- **Operating System**: Linux (Debian)
- **Database**: Postgres

**Comment by TheOnlyAl** [comment]
Hello and thanks for your response.

First of all, I am not sure if I accidentally missed some important details in my text.
The exception above is logged during deployment, but only if you enable the finest logging level for the Eclipselink JPA category. The deployment will still work, even when the exception is logged. This is just an additional information, of why the EntityListener will not have the field injected after creation.

The exception is logged during deployment on the DAS. I did use the payara domain for testing.

I changed the logging level by adding this to the persistence.xml file of the EJB archive:
```xml
...
<property name="eclipselink.logging.level" value="SEVERE" />
<property name="eclipselink.logging.level.jpa" value="FINEST" />
...
```

The structure of the project is somewhat like this:
```
app.ear
├─ lib
│  ├─ lib1.jar
│  ├─ lib2.jar
│  ├─ ...
│ 
├─ META-INF 
│  ├─ application.xml
│ 
├─ ejb.jar
├─ web1.war
├─ web2.war
├─ web3.war
```
The war archives are skinny wars. The libs of the war files are packaged into the `lib` folder. The entities, listeners, and beans to Inject are inside the `ejb.jar` archive which contains EJB and CDI Beans.
I already tried to switch the CDI Bean with an EJB. The error is still the same.

The `application xml` looks something like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<application xmlns="http://xmlns.jcp.org/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee/ http://xmlns.jcp.org/xml/ns/javaee/application_8.xsd" version="8">
  <display-name>app</display-name>
  <module>
    <web>
      <web-uri>web1.war</web-uri>
      <context-root>/web1</context-root>
    </web>
  </module>
  <module>
    <web>
      <web-uri>web2.war</web-uri>
      <context-root>/web2</context-root>
    </web>
  </module>
  <module>
    <web>
      <web-uri>web3.war</web-uri>
      <context-root>/web3</context-root>
    </web>
  </module>
  <module>
    <ejb>ejb.jar</ejb>
  </module>
  <library-directory>lib</library-directory>
</application>
```

As far as i understand the Eclipselink code, the problem is that the injection manager is created during the deployment for the AbstractSession.

1. [AbstractSession getInjectionManager](https://github.com/eclipse-ee4j/eclipselink/blob/9e8e14175db20826979c9f9f2f36b864f7fd9804/foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/AbstractSession.java#L2345) is called when EntityListeners or AttributeConverters are created.
2. [AbstractSession createInjectionManager](https://github.com/eclipse-ee4j/eclipselink/blob/9e8e14175db20826979c9f9f2f36b864f7fd9804/foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/AbstractSession.java#L1229) fails since it can not find the bean manager. This creates a [DisabledInjectionManager](https://github.com/eclipse-ee4j/eclipselink/blob/3668d1a81e3e13d28a63b930de10bece725b0ed5/foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/cdi/DisabledInjectionManager.java#L21), which does no injection on EntityListener creation
3. EntityListener and InjectionManager instances are reused and therefore injection will never work

I hope this helps somehow.

**Comment by smillidge** [comment]
Thanks for the extra detail. As I mentioned EAR files and the interaction with CDI is not very well specified. I'm afraid we will need to reproducer project that demonstrates the error to make any progress.

**Comment by smillidge** [comment]
Closed due to inactivity
