### ISSUE TITLE
Startup of context /osgi failed due to previous errors

### ISSUE THREAD

**Issue by evilrich** [payara/Payara#3122]
# Description #
----------

An OSGi bundle which subscribes to the OSGi HTTPService in its activator causes exceptions in the server.log when deployed.

## Expected Outcome

The bundle is deployed without any exceptions (this is the case with Glassfish 5, for example).

## Current Outcome

The following output is produced in the server log when the bundle is deployed.

```
[2018-09-04T12:20:18.446-0400] [Payara 5.182] [INFO] [] [org.glassfish.osgihttp] [tid: _ThreadID=153 _ThreadName=fileinstall-/Users/drummondr/Downloads/payara5-3/glassfish/domains/domain1/autodeploy/bundles/] [timeMillis: 1536078018446] [levelValue: 800] [[
  defaultVirtualServer = server]]

[2018-09-04T12:20:18.473-0400] [Payara 5.182] [INFO] [AS-WEB-CORE-00418] [javax.enterprise.web.core] [tid: _ThreadID=153 _ThreadName=fileinstall-/Users/drummondr/Downloads/payara5-3/glassfish/domains/domain1/autodeploy/bundles/] [timeMillis: 1536078018473] [levelValue: 800] [[
  No default web.xml]]

[2018-09-04T12:20:18.474-0400] [Payara 5.182] [SEVERE] [AS-WEB-CORE-00174] [javax.enterprise.web.core] [tid: _ThreadID=153 _ThreadName=fileinstall-/Users/drummondr/Downloads/payara5-3/glassfish/domains/domain1/autodeploy/bundles/] [timeMillis: 1536078018474] [levelValue: 1000] [[
  Startup of context /osgi failed due to previous errors]]

[2018-09-04T12:20:18.500-0400] [Payara 5.182] [SEVERE] [AS-WEB-CORE-00175] [javax.enterprise.web.core] [tid: _ThreadID=153 _ThreadName=fileinstall-/Users/drummondr/Downloads/payara5-3/glassfish/domains/domain1/autodeploy/bundles/] [timeMillis: 1536078018500] [levelValue: 1000] [[
  Exception during cleanup after start failed
org.apache.catalina.LifecycleException: Manager has not yet been started
	at org.apache.catalina.session.StandardManager.stop(StandardManager.java:868)
	at org.apache.catalina.core.StandardContext.stop(StandardContext.java:5927)
	at com.sun.enterprise.web.WebModule.stop(WebModule.java:647)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:5743)
	at com.sun.enterprise.web.WebModule.start(WebModule.java:618)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:956)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:939)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:684)
	at org.glassfish.osgihttp.Activator.createRootWebModule(Activator.java:185)
	at org.glassfish.osgihttp.Activator.doActualWork(Activator.java:124)
	at org.glassfish.osgihttp.Activator.access$300(Activator.java:84)
	at org.glassfish.osgihttp.Activator$OSGiHtttpExtender.start(Activator.java:332)
	at org.glassfish.osgijavaeebase.ExtenderManager$ExtenderTracker.addingService(ExtenderManager.java:144)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)
	at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
	at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4595)
	at org.apache.felix.framework.Felix.registerService(Felix.java:3587)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:322)
	at org.glassfish.osgihttp.Activator.start(Activator.java:105)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2224)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1607)
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.felix.framework.BundleWiringImpl.getClassByDelegation(BundleWiringImpl.java:1414)
	at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1660)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1590)
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.rcdrummond.httpservicetest.Activator.start(Activator.java:14)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1221)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:515)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316)
]]

[2018-09-04T12:20:18.501-0400] [Payara 5.182] [SEVERE] [AS-WEB-CORE-00108] [javax.enterprise.web.core] [tid: _ThreadID=153 _ThreadName=fileinstall-/Users/drummondr/Downloads/payara5-3/glassfish/domains/domain1/autodeploy/bundles/] [timeMillis: 1536078018501] [levelValue: 1000] [[
  ContainerBase.addChild: start: 
org.apache.catalina.LifecycleException: java.lang.NullPointerException
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:5747)
	at com.sun.enterprise.web.WebModule.start(WebModule.java:618)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:956)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:939)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:684)
	at org.glassfish.osgihttp.Activator.createRootWebModule(Activator.java:185)
	at org.glassfish.osgihttp.Activator.doActualWork(Activator.java:124)
	at org.glassfish.osgihttp.Activator.access$300(Activator.java:84)
	at org.glassfish.osgihttp.Activator$OSGiHtttpExtender.start(Activator.java:332)
	at org.glassfish.osgijavaeebase.ExtenderManager$ExtenderTracker.addingService(ExtenderManager.java:144)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)
	at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
	at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4595)
	at org.apache.felix.framework.Felix.registerService(Felix.java:3587)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:322)
	at org.glassfish.osgihttp.Activator.start(Activator.java:105)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2224)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1607)
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.felix.framework.BundleWiringImpl.getClassByDelegation(BundleWiringImpl.java:1414)
	at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1660)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1590)
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.rcdrummond.httpservicetest.Activator.start(Activator.java:14)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1221)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:515)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316)
Caused by: java.lang.NullPointerException
	at com.sun.enterprise.web.WebComponentInvocation.<init>(WebComponentInvocation.java:73)
	at com.sun.enterprise.web.WebComponentInvocation.<init>(WebComponentInvocation.java:60)
	at com.sun.enterprise.web.WebModule.callServletContainerInitializers(WebModule.java:734)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:5722)
	... 46 more
]]

[2018-09-04T12:20:18.503-0400] [Payara 5.182] [SEVERE] [] [] [tid: _ThreadID=153 _ThreadName=fileinstall-/Users/drummondr/Downloads/payara5-3/glassfish/domains/domain1/autodeploy/bundles/] [timeMillis: 1536078018503] [levelValue: 1000] [[
  java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: java.lang.NullPointerException
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:960)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:939)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:684)
	at org.glassfish.osgihttp.Activator.createRootWebModule(Activator.java:185)
	at org.glassfish.osgihttp.Activator.doActualWork(Activator.java:124)
	at org.glassfish.osgihttp.Activator.access$300(Activator.java:84)
	at org.glassfish.osgihttp.Activator$OSGiHtttpExtender.start(Activator.java:332)
	at org.glassfish.osgijavaeebase.ExtenderManager$ExtenderTracker.addingService(ExtenderManager.java:144)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)
	at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
	at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4595)
	at org.apache.felix.framework.Felix.registerService(Felix.java:3587)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:322)
	at org.glassfish.osgihttp.Activator.start(Activator.java:105)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2224)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1607)
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.felix.framework.BundleWiringImpl.getClassByDelegation(BundleWiringImpl.java:1414)
	at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1660)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1590)
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.rcdrummond.httpservicetest.Activator.start(Activator.java:14)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1221)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:515)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316)
]]
```

## Steps to reproduce (Only for bug reports) 

* Start with a clean install of Payara 5.182.
* Ensure the OSGi auto deploy directory is present and configured
** mkdir -p  glassfish/domains/domain1/autodeploy/bundles
** Edit glassfish/config/osgi.properties and change line 431 to `felix.fileinstall.dir=${com.sun.aas.instanceRoot}/autodeploy/bundles/`
* From the attached sample, copy target/HTTPServiceTest-1.0.jar to  glassfish/domains/domain1/autodeploy/bundles/HTTPServiceTest-1.0.jar.
* ./bin/asadmin start-domain

### Samples

Use the attached project: [HTTPServiceTest.zip](https://github.com/payara/Payara/files/2349365/HTTPServiceTest.zip)

## Context (Optional)

I am evaluating Payara with the intent of migration of an existing application from Glassfish. This application contains many bundles that contain a servlet that is registered with OSGi HTTPService. This issue is blocking this evaluation.

## Environment ##

- **Payara Version**: Payara 5.182
- **Edition**: Full
- **JDK Version**:  1.8.0_144 Oracle
- **Operating System**: Mac

**Comment by rdebusscher** [comment]
Tested with Payara 5.194 and the recommended approach

`asadmin deploy --type=osgi HTTPServiceTest-1.0.jar`

and the artefact deploys successfully.

Regards
Rudy

**Comment by vaiism** [comment]
This says the 'recommended approach' for deploying, but does this still deploy successfully with the autodeploy in place? This is pretty important, since utilizing the asadmin command is not always the way these are deployed.

Are you saying this is the _only_ approach that worked? Or did you verify - according to the original ticket - to utilize the autodeploy mechanism as well?

**Comment by rdebusscher** [comment]
Hi,

I tried the auto-deploy but probably my setup was wrong (since it didn't pick up the OSGi bundle). I didn't try to find out why auto-deploy didn't pick up the file.

We don't recommend auto-deploy in production because
- It bypasses the security of the server
- Performance degradation since the folder needs to be scanned.

And deploy can always be done during startup of the server with the help of the post-boot command file (see here for more info https://docs.payara.fish/documentation/payara-server/app-deployment/app-deployment.html)

Regards
Rudy
