### ISSUE TITLE
Unhandled Exception When --hzPublicAddress Option is not set with --outputUberJar

### ISSUE THREAD

**Issue by jwadel** [payara/Payara#3166]
https://github.com/payara/Payara/blob/f0786f60e9017179d7a74118e80b731cdeacc326/appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java#L2293

### When a user runs a command to create an UberJar without specifying the --hzPublicAddress option on Windows 10 command line interface, an exception is thrown.

For example,

When a user runs: 

`java -jar payara-micro.jar --deploy my-app.war --port 8080 --outputUberJar myApp.jar`

The following exception is thrown:

```
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:79)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:397)
Caused by: java.lang.NullPointerException
        at java.util.Hashtable.put(Hashtable.java:460)
        at java.util.Properties.setProperty(Properties.java:166)
        at fish.payara.micro.impl.PayaraMicroImpl.packageUberJar(PayaraMicroImpl.java:2293)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:198)
```

**An appropriate error message instructing the user to specify a Public Address using the --hzPublicAddress should at least be shown.**

**Comment by smillidge** [comment]
Hi this is a know issue fixed by #3134
