### ISSUE TITLE
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by fturizo** [payara/Payara#318]
I'm using Payara Full Profile 4.1.152 and i'm having weird issues with a simple implementation of a cache service using JCache.

i'm getting a ClassNotFoundException when the **retrieve** method is called:

``` java
@Singleton
public class MediaCacheService {
    
    private static final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HHmmss");
    
    private final static String CACHE_NAME = "COMPLAINTS_MEDIA";
    private final static String IMAGE_PREFIX = "IM";
    private final static String VIDEO_PREFIX = "VD";
    
    @Inject
    private CacheManager manager;
    private Cache<String, MediaData> mediaCache;
    
    @PostConstruct
    public void prepare(){
        if(manager.getCache(CACHE_NAME) == null){
            manager.createCache(CACHE_NAME, new MutableConfiguration<>()
                       .setExpiryPolicyFactory(CreatedExpiryPolicy.factoryOf(Duration.TEN_MINUTES))) ;
        }
        mediaCache = manager.getCache(CACHE_NAME);
    }
    
    public String store(ComplaintMediaType type, String fileName, long size, byte[] contents){
        String code;
        switch(type){
            case image: code = cacheImage(fileName, size, contents);
                break;
            case video: code = cacheVideo(fileName, size, contents);
                break;
            default : throw new UnsupportedOperationException("Attachment type not supported");
        }
        return code;
    }
    
    private MediaData retrieve(String code){
        return mediaCache.get(code);
    }
    
    public List<MediaData> retrieveMany(List<String> codes){
        return codes.stream().map(c -> retrieve(c)).collect(Collectors.toList());
    }
    
    private String cacheImage(String fileName, long size, byte[] contents){
        String code = IMAGE_PREFIX + timestamp() + "-" + fileName;
        mediaCache.put(code, new MediaData(code, ComplaintMediaType.image, size, fileName, contents));
        return code;
    }
    
    private String cacheVideo(String fileName, long size, byte[] contents){
        String code = VIDEO_PREFIX + timestamp() + "-" + fileName;
        mediaCache.put(code, new MediaData(code, ComplaintMediaType.video, size, fileName, contents));
        return code;
    }
    
    public void clear(String code){
        mediaCache.remove(code);
    }
    
    private static String timestamp(){
        return formatter.format(LocalTime.now());
    }
}
```

And this is the stacktrace:

```
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: co.stackpointer.cercati.gateway.entities.MediaData
	at com.hazelcast.nio.serialization.DefaultSerializers$ObjectSerializer.read(DefaultSerializers.java:201)
	at com.hazelcast.nio.serialization.StreamSerializerAdapter.toObject(StreamSerializerAdapter.java:65)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.toObject(SerializationServiceImpl.java:260)
	at com.hazelcast.cache.impl.CacheRecordStore.dataToValue(CacheRecordStore.java:112)
	at com.hazelcast.cache.impl.CacheRecordStore.recordToValue(CacheRecordStore.java:124)
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.get(AbstractCacheRecordStore.java:766)
	at com.hazelcast.cache.impl.operation.CacheGetOperation.run(CacheGetOperation.java:50)
	at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.handle(BasicOperationService.java:749)
	at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.access$500(BasicOperationService.java:725)
	at com.hazelcast.spi.impl.BasicOperationService$BasicDispatcherImpl.dispatch(BasicOperationService.java:576)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.process(BasicOperationScheduler.java:466)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.doRun(BasicOperationScheduler.java:458)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.run(BasicOperationScheduler.java:432)
Caused by: java.lang.ClassNotFoundException: co.stackpointer.cercati.gateway.entities.MediaData
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:124)
	at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:113)
	at com.hazelcast.nio.IOUtil$1.resolveClass(IOUtil.java:113)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at com.hazelcast.nio.serialization.DefaultSerializers$ObjectSerializer.read(DefaultSerializers.java:196)
	... 12 more
```

The class _MediaData_ is declared as Serializable and of course is packaged into the deployed WAR, so i can't seem to understand this _ClassNotFoundException_.

**Comment by smillidge** [comment]
This is a Hazelcast bug https://github.com/hazelcast/hazelcast/issues/4775 and https://github.com/hazelcast/hazelcast/issues/4632 whch is fixed in the next Hazelcast release.

You can work around by either using the JCache CDI annotations or use the PayaraValueHolder as the object you put in the cache. The CDI annotations use the value holder internally.

e.g. 
```java
    private String cacheImage(String fileName, long size, byte[] contents){
        String code = IMAGE_PREFIX + timestamp() + "-" + fileName;
        mediaCache.put(code, new PayaraValueHolder(new MediaData(code, ComplaintMediaType.image, size, fileName, contents)));
        return code;
    }
```

and 

```java
   private MediaData retrieve(String code){
        return (MediaData)mediaCache.get(code).getValue();
    }
```

once the Hazelcast bug is fixed this will be unnecessary. Although the api will remain.

**Comment by fturizo** [comment]
I see. Where can i find this _PayaraValueHolder_ class? I'd appreciate it if you can give me the Maven coordinates then

**Comment by smillidge** [comment]
Below will give you all the Payara apis including all the Java EE7 apis and should be all you need to build apps for Payara.

```xml
<dependency>
    <groupId>fish.payara.extras</groupId>
    <artifactId>payara-embedded-all</artifactId>
    <version>4.1.152.1</version>
    <type>jar</type>
    <scope>compile</scope>
</dependency>
```

**Comment by fturizo** [comment]
Many thanks, now it's working using PayaraValueHolder for the moment. Another question, though. Could i patch the hazelcast libraries inside the current payara version when those bugs are fixed? Or ould it be better to wait until a new Payara release?

**Comment by smillidge** [comment]
We release Payara every 3 months. The next one is due end of July. If Hazelcast 3.5 is out then we will patch Payara with the latest.

Another option which may work (note I have not tested this) is to replace
```java
@Inject 
private CacheManager manager;
```
with the code
```java
@Inject
private CachingProvider provider;
```
Then change your @PostConstructMethod

```java
    @PostConstruct
    public void prepare(){
        CacheManager manager;
        manager = provider.getCacheManager(provider.getDefaultURI(),Thread.currentThread().getContextClassLoader());
        if(manager.getCache(CACHE_NAME) == null){
            manager.createCache(CACHE_NAME, new MutableConfiguration<>()
                       .setExpiryPolicyFactory(CreatedExpiryPolicy.factoryOf(Duration.TEN_MINUTES))) ;
        }
        mediaCache = manager.getCache(CACHE_NAME);
    }
```

**Comment by fturizo** [comment]
I tried with different flavors of setting the classloader as you suggested but it's now working. For the moment i'll stick to the solution using the _PayaraValueHolder_

Many thanks for your assistance.

**Comment by smillidge** [comment]
#339 references this. When that is closed then the latest builds will remove the need for the ValueHolder.

**Comment by lprimak** [comment]
Relates to https://github.com/hazelcast/hazelcast/issues/10875

**Comment by lprimak** [comment]
This should be resolved since Payara 2018
