### ISSUE TITLE
Payara micro error when loading external libraries: "In TLD scanning, the supplied resource file does not exist"

### ISSUE THREAD

**Issue by seinecle** [payara/Payara#3217]
Trying to deploy an hello world war on Payara Micro with the CLI:

- the server deploys
- but the external libs are not found.
----------
To help with diagnostic, the app is available as a zip here: https://drive.google.com/open?id=1gx-KhQBe6X_I2xGsE1XoTMUF_VAwi1mY

- The hello world app is created from NetBeans, using a template provided by the NB Payara plugin
- I add a dependency utils.1.0 in the pom.xml, which has itself two dependencies: commons-lang3-3.4 and guava.13.0.1 
- I add a plugin in the pom.xml to get external libraries copied in a separate `lib/` folder (because I don't want an uber jar).
- I added a glassfish-web.xml to the project, with `<class-loader delegate="false"/>` to see if changed anything, but no.
- I deploy the app using the CLI:  `java -jar ../payara-micro-5.183.jar qof-back-email-1.0-SNAPSHOT.war --addLibs lib/`

Environment:
- Payara Micro 5.183
- NetBeans 8.2
- deployment tested on Windows 10 and Debian 9, same effect

The error messages when deploying:

`[2018-10-01T09:47:30.837+0200] [] [GRAVE] [] [PayaraMicro] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1538380050837] [levelValue: 1000] Unable to read jar microprofile-2.0.1.pom
`

[...]

```
[2018-10-01T09:47:42.573+0200] [] [AVERTISSEMENT] [] [org.apache.jasper.runtime.TldScanner] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1538380062573] [levelValue: 900] [[
  PWC6351: In TLD scanning, the supplied resource file:/C:/Users/LEVALL~1/AppData/Local/Temp/payaramicro-rt556764687630888028tmp/applications/lib/guava-13.0.1.jar does not exist
java.io.FileNotFoundException: C:\Users\LEVALL~1\AppData\Local\Temp\payaramicro-rt556764687630888028tmp\applications\lib\guava-13.0.1.jar (Le chemin dÆaccÞs spÚcifiÚ est introuvable)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at sun.net.www.protocol.jar.URLJarFile.<init>(Unknown Source)
        at sun.net.www.protocol.jar.URLJarFile.getJarFile(Unknown Source)
        at sun.net.www.protocol.jar.JarFileFactory.get(Unknown Source)
        at sun.net.www.protocol.jar.JarURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.jar.JarURLConnection.getJarFile(Unknown Source)
        at org.apache.jasper.runtime.TldScanner.scanJar(TldScanner.java:445)
        at org.apache.jasper.runtime.TldScanner.scanJars(TldScanner.java:697)
        at org.apache.jasper.runtime.TldScanner.scanTlds(TldScanner.java:353)
        at org.apache.jasper.runtime.TldScanner.onStartup(TldScanner.java:242)
        at org.apache.catalina.core.StandardContext.callServletContainerInitializers(StandardContext.java:5825)
        at com.sun.enterprise.web.WebModule.callServletContainerInitializers(WebModule.java:737)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:5722)
        at com.sun.enterprise.web.WebModule.start(WebModule.java:618)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:956)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:939)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:684)
        at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:2105)
        at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1750)
        at com.sun.enterprise.web.WebApplication.start(WebApplication.java:107)
        at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123)
        at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:294)
        at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:357)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:541)
        at fish.payara.deployment.admin.InitializeAllApplicationsCommand.execute(InitializeAllApplicationsCommand.java:75)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:549)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:545)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Unknown Source)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:544)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:575)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:567)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Unknown Source)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:566)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1475)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1857)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1733)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:172)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:96)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1045)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:200)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:79)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:397)
]]

[2018-10-01T09:47:42.589+0200] [] [AVERTISSEMENT] [] [org.apache.jasper.runtime.TldScanner] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1538380062589] [levelValue: 900] [[
  PWC6351: In TLD scanning, the supplied resource file:/C:/Users/LEVALL~1/AppData/Local/Temp/payaramicro-rt556764687630888028tmp/applications/lib/utils-1.0.jar does not exist
java.io.FileNotFoundException: C:\Users\LEVALL~1\AppData\Local\Temp\payaramicro-rt556764687630888028tmp\applications\lib\utils-1.0.jar (Le chemin dÆaccÞs spÚcifiÚ est introuvable)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at sun.net.www.protocol.jar.URLJarFile.<init>(Unknown Source)
        at sun.net.www.protocol.jar.URLJarFile.getJarFile(Unknown Source)
        at sun.net.www.protocol.jar.JarFileFactory.get(Unknown Source)
        at sun.net.www.protocol.jar.JarURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.jar.JarURLConnection.getJarFile(Unknown Source)
        at org.apache.jasper.runtime.TldScanner.scanJar(TldScanner.java:445)
        at org.apache.jasper.runtime.TldScanner.scanJars(TldScanner.java:697)
        at org.apache.jasper.runtime.TldScanner.scanTlds(TldScanner.java:353)
        at org.apache.jasper.runtime.TldScanner.onStartup(TldScanner.java:242)
        at org.apache.catalina.core.StandardContext.callServletContainerInitializers(StandardContext.java:5825)
        at com.sun.enterprise.web.WebModule.callServletContainerInitializers(WebModule.java:737)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:5722)
        at com.sun.enterprise.web.WebModule.start(WebModule.java:618)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:956)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:939)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:684)
        at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:2105)
        at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1750)
        at com.sun.enterprise.web.WebApplication.start(WebApplication.java:107)
        at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123)
        at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:294)
        at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:357)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:541)
        at fish.payara.deployment.admin.InitializeAllApplicationsCommand.execute(InitializeAllApplicationsCommand.java:75)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:549)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:545)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Unknown Source)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:544)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:575)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:567)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Unknown Source)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:566)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1475)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1857)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1733)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:172)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:96)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1045)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:200)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:79)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:397)
]]

[2018-10-01T09:47:42.598+0200] [] [AVERTISSEMENT] [] [org.apache.jasper.runtime.TldScanner] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1538380062598] [levelValue: 900] [[
  PWC6351: In TLD scanning, the supplied resource file:/C:/Users/LEVALL~1/AppData/Local/Temp/payaramicro-rt556764687630888028tmp/applications/lib/commons-lang3-3.4.jar does not exist
java.io.FileNotFoundException: C:\Users\LEVALL~1\AppData\Local\Temp\payaramicro-rt556764687630888028tmp\applications\lib\commons-lang3-3.4.jar (Le chemin dÆaccÞs spÚcifiÚ est introuvable)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at sun.net.www.protocol.jar.URLJarFile.<init>(Unknown Source)
        at sun.net.www.protocol.jar.URLJarFile.getJarFile(Unknown Source)
        at sun.net.www.protocol.jar.JarFileFactory.get(Unknown Source)
        at sun.net.www.protocol.jar.JarURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.jar.JarURLConnection.getJarFile(Unknown Source)
        at org.apache.jasper.runtime.TldScanner.scanJar(TldScanner.java:445)
        at org.apache.jasper.runtime.TldScanner.scanJars(TldScanner.java:697)
        at org.apache.jasper.runtime.TldScanner.scanTlds(TldScanner.java:353)
        at org.apache.jasper.runtime.TldScanner.onStartup(TldScanner.java:242)
        at org.apache.catalina.core.StandardContext.callServletContainerInitializers(StandardContext.java:5825)
        at com.sun.enterprise.web.WebModule.callServletContainerInitializers(WebModule.java:737)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:5722)
        at com.sun.enterprise.web.WebModule.start(WebModule.java:618)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:956)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:939)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:684)
        at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:2105)
        at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1750)
        at com.sun.enterprise.web.WebApplication.start(WebApplication.java:107)
        at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123)
        at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:294)
        at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:357)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:541)
        at fish.payara.deployment.admin.InitializeAllApplicationsCommand.execute(InitializeAllApplicationsCommand.java:75)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:549)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:545)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Unknown Source)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:544)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:575)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:567)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Unknown Source)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:566)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1475)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1857)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1733)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:172)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:96)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1045)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:200)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:79)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:397)
]]
```

**Comment by rdebusscher** [comment]
Hi Clement,

The `FileNotFound` exception is triggered by the classpath entries which are specified within the MANIFEST.MF file.

```
 <archive>
       <manifest>
              <addClasspath>true</addClasspath>
```
within your POM file, adds your additional dependencies (like your utils jar, commons-lang3 and guava) to the classpath but they are not contained within the WAR file.

When you remove the `addClassPath` entry, the deploy is without any errors.

**Comment by rdebusscher** [comment]
Please also note thet you should add the configuration entry

`<excludeScope>provided</excludeScope>`

to the `maven-dependency-plugin`. Otherwise the lib folder contains also the JavaEE and MicroProfile dependencies which are already contained within Payara Micro (and thus not needed to define them again)

**Comment by seinecle** [comment]
Thanks a lot. Works fine now.
