### ISSUE TITLE
Unable to start payara-embedded-all 5.183 on JDK11

### ISSUE THREAD

**Issue by ctabin** [payara/Payara#3278]
# Description #
----------

We just update to payara 5.183 with OpenJDK 11 and try to start our embedded server (payara-embedded-all). Before reaching this step, we also had to add the dependency below:
```xml
<dependency>
  <groupId>javax.activation</groupId>
  <artifactId>activation</artifactId>
  <version>1.1.1</version>
</dependency>
```

## Current Outcome

During the startup of payara, it crashes with the following stacktrace:
```
INFO: Cannot find javadb client jar file, derby jdbc driver will not be available by default.
Oct 16, 2018 7:41:26 PM com.sun.enterprise.v3.server.CommonClassLoaderServiceImpl findH2Client
INFO: Cannot find h2db client jar file, h2 jdbc driver will not be available by default.
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
Oct 16, 2018 7:41:27 PM com.sun.enterprise.v3.services.impl.GrizzlyProxy start0
INFO: Network Listener http-listener-1 started in: 4ms - bound to [/0.0.0.0:9090]
Oct 16, 2018 7:41:27 PM org.glassfish.grizzly.http2.Http2AddOn setup
WARNING: TLS ALPN (Application-Layer Protocol Negotiation) support is not available. HTTP/2 support will not be enabled.
Oct 16, 2018 7:41:27 PM com.sun.enterprise.v3.services.impl.GrizzlyProxy start0
INFO: Network Listener http-listener-2 started in: 2ms - bound to [/0.0.0.0:9191]
Oct 16, 2018 7:41:27 PM com.sun.enterprise.v3.services.impl.GrizzlyProxy start0
INFO: Network Listener admin-listener started in: 0ms - bound to [/0.0.0.0:5858]
Oct 16, 2018 7:41:27 PM com.sun.enterprise.v3.services.impl.GrizzlyService postConstruct
INFO: Grizzly 2.4.3 started in: 747ms - bound to [http-listener-1:9090, http-listener-2:9191, admin-listener:5858]
Oct 16, 2018 7:41:27 PM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [development] [3.10.2] Using bind address: /192.168.0.54:4900
Oct 16, 2018 7:41:27 PM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [development] [3.10.2] Using public address: /192.168.0.54:4900
Oct 16, 2018 7:41:27 PM com.hazelcast.system
INFO: [192.168.0.54]:4900 [development] [3.10.2] Hazelcast 3.10.2 (20180606 - 84cfd49) starting at [192.168.0.54]:4900
Oct 16, 2018 7:41:27 PM com.hazelcast.system
INFO: [192.168.0.54]:4900 [development] [3.10.2] Copyright (c) 2008-2018, Hazelcast, Inc. All Rights Reserved.
Oct 16, 2018 7:41:27 PM com.hazelcast.system
INFO: [192.168.0.54]:4900 [development] [3.10.2] Configured Hazelcast Serialization version: 1
Oct 16, 2018 7:41:27 PM com.hazelcast.instance.Node
INFO: [192.168.0.54]:4900 [development] [3.10.2] A non-empty group password is configured for the Hazelcast member. Starting with Hazelcast version 3.8.2, members with the same group name, but with different group passwords (that do not use authentication) form a cluster. The group password configuration will be removed completely in a future release.
Oct 16, 2018 7:41:27 PM com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator
INFO: [192.168.0.54]:4900 [development] [3.10.2] Backpressure is disabled
Oct 16, 2018 7:41:27 PM com.hazelcast.spi.impl.operationservice.impl.InboundResponseHandlerSupplier
INFO: [192.168.0.54]:4900 [development] [3.10.2] Running with 2 response threads
Oct 16, 2018 7:41:28 PM com.hazelcast.instance.Node
INFO: [192.168.0.54]:4900 [development] [3.10.2] Activating Discovery SPI Joiner
Oct 16, 2018 7:41:28 PM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
INFO: [192.168.0.54]:4900 [development] [3.10.2] Starting 4 partition threads and 3 generic threads (1 dedicated for priority tasks)
Oct 16, 2018 7:41:28 PM com.hazelcast.internal.diagnostics.Diagnostics
INFO: [192.168.0.54]:4900 [development] [3.10.2] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
Oct 16, 2018 7:41:28 PM com.hazelcast.core.LifecycleService
INFO: [192.168.0.54]:4900 [development] [3.10.2] [192.168.0.54]:4900 is STARTING
Oct 16, 2018 7:41:28 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [192.168.0.54]:4900 [development] [3.10.2] Connecting to /192.168.0.54:5900, timeout: 0, bind-any: true
Oct 16, 2018 7:41:28 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [192.168.0.54]:4900 [development] [3.10.2] Could not connect to: /192.168.0.54:5900. Reason: SocketException[Connection refused to address /192.168.0.54:5900]
Oct 16, 2018 7:41:28 PM com.hazelcast.internal.cluster.impl.DiscoveryJoiner
INFO: [192.168.0.54]:4900 [development] [3.10.2] [192.168.0.54]:5900 is added to the blacklist.
Oct 16, 2018 7:41:29 PM com.hazelcast.system
INFO: [192.168.0.54]:4900 [development] [3.10.2] Cluster version set to 3.10
Oct 16, 2018 7:41:29 PM com.hazelcast.internal.cluster.ClusterService
INFO: [192.168.0.54]:4900 [development] [3.10.2] 

Members {size:1, ver:1} [
        Member [192.168.0.54]:4900 - d4471b5d-9801-475d-981b-f2f7f7333aad this
]

Oct 16, 2018 7:41:29 PM com.hazelcast.internal.jmx.ManagementService
INFO: [192.168.0.54]:4900 [development] [3.10.2] Hazelcast JMX agent enabled.
Oct 16, 2018 7:41:29 PM com.hazelcast.core.LifecycleService
INFO: [192.168.0.54]:4900 [development] [3.10.2] [192.168.0.54]:4900 is STARTED
Oct 16, 2018 7:41:29 PM fish.payara.nucleus.hazelcast.HazelcastCore bindToJNDI
INFO: Hazelcast Instance Bound to JNDI at payara/Hazelcast
Oct 16, 2018 7:41:29 PM fish.payara.nucleus.hazelcast.HazelcastCore bindToJNDI
INFO: JSR107 Caching Provider Bound to JNDI at payara/CachingProvider
Oct 16, 2018 7:41:29 PM fish.payara.nucleus.hazelcast.HazelcastCore bindToJNDI
INFO: JSR107 Default Cache Manager Bound to JNDI at payara/CacheManager
Oct 16, 2018 7:41:29 PM com.sun.enterprise.v3.server.AppServerStartup$MasterRunLevelListener onError
INFO: Shutdown requested
MultiException stack 1 of 2
java.lang.reflect.InaccessibleObjectException: Unable to make public java.util.Enumeration jdk.internal.loader.BuiltinClassLoader.findResources(java.lang.String) throws java.io.IOException accessible: module java.base does not "exports jdk.internal.loader" to unnamed module @d278d2b
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
        at com.sun.enterprise.module.single.ManifestProxy.<init>(ManifestProxy.java:90)
        at com.sun.enterprise.module.single.ProxyModuleDefinition.generate(ProxyModuleDefinition.java:170)
        at com.sun.enterprise.module.single.ProxyModuleDefinition.getMetadata(ProxyModuleDefinition.java:163)
        at com.sun.enterprise.module.single.ProxyModule.getMetadata(ProxyModule.java:101)
        at com.sun.enterprise.v3.server.APIClassLoaderServiceImpl$APIClassLoader.getResource(APIClassLoaderServiceImpl.java:333)
        at java.base/java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:1736)
        at org.apache.xerces.parsers.SecuritySupport$6.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.apache.xerces.parsers.SecuritySupport.getResourceAsStream(Unknown Source)
        at org.apache.xerces.parsers.ObjectFactory.findJarServiceProvider(Unknown Source)
        at org.apache.xerces.parsers.ObjectFactory.createObject(Unknown Source)
        at org.apache.xerces.parsers.ObjectFactory.createObject(Unknown Source)
        at org.apache.xerces.parsers.SAXParser.<init>(Unknown Source)
        at org.apache.xerces.parsers.SAXParser.<init>(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.<init>(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl.<init>(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserFactoryImpl.newSAXParser(Unknown Source)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.getXMLReader(UnmarshallerImpl.java:159)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:291)
        at javax.xml.bind.JAXB.unmarshal(JAXB.java:238)
        at fish.payara.microprofile.metrics.MetricsService.getConfig(MetricsService.java:153)
        at fish.payara.microprofile.metrics.MetricsService.init(MetricsService.java:110)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1287)
        at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:333)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:375)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
        at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:89)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:90)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1237)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpOneLevel.run(CurrentTaskFuture.java:786)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpAllTheWay.go(CurrentTaskFuture.java:585)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpAllTheWay.access$100(CurrentTaskFuture.java:467)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture.go(CurrentTaskFuture.java:157)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture.go(CurrentTaskFuture.java:152)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.proceedTo(AsyncRunLevelContext.java:535)
        at org.glassfish.hk2.runlevel.internal.RunLevelControllerImpl.proceedTo(RunLevelControllerImpl.java:72)
        at com.sun.enterprise.v3.server.AppServerStartup.proceedTo(AppServerStartup.java:556)
        at com.sun.enterprise.v3.server.AppServerStartup.run(AppServerStartup.java:348)
        at com.sun.enterprise.v3.server.AppServerStartup.doStart(AppServerStartup.java:234)
        at com.sun.enterprise.v3.server.AppServerStartup.start(AppServerStartup.java:223)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishImpl.start(GlassFishImpl.java:81)
        at ch.saierp.sainet.embedded.server.SAINetServer.start(SAINetServer.java:918)
        at ch.saierp.sainet.testing.server.SAINetTestServer.before(SAINetTestServer.java:272)
        at ch.saierp.sainet.testing.server.SAINetTestServer$2.evaluate(SAINetTestServer.java:340)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at ch.saierp.sainet.testing.suite.SAINetSuite.run(SAINetSuite.java:26)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
        at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
MultiException stack 2 of 2
java.lang.IllegalStateException: Unable to perform operation: post construct on fish.payara.microprofile.metrics.MetricsService
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:393)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
        at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:89)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:90)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1237)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpOneLevel.run(CurrentTaskFuture.java:786)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpAllTheWay.go(CurrentTaskFuture.java:585)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpAllTheWay.access$100(CurrentTaskFuture.java:467)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture.go(CurrentTaskFuture.java:157)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture.go(CurrentTaskFuture.java:152)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.proceedTo(AsyncRunLevelContext.java:535)
        at org.glassfish.hk2.runlevel.internal.RunLevelControllerImpl.proceedTo(RunLevelControllerImpl.java:72)
        at com.sun.enterprise.v3.server.AppServerStartup.proceedTo(AppServerStartup.java:556)
        at com.sun.enterprise.v3.server.AppServerStartup.run(AppServerStartup.java:348)
        at com.sun.enterprise.v3.server.AppServerStartup.doStart(AppServerStartup.java:234)
        at com.sun.enterprise.v3.server.AppServerStartup.start(AppServerStartup.java:223)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishImpl.start(GlassFishImpl.java:81)
        at ch.saierp.sainet.embedded.server.SAINetServer.start(SAINetServer.java:918)
        at ch.saierp.sainet.testing.server.SAINetTestServer.before(SAINetTestServer.java:272)
        at ch.saierp.sainet.testing.server.SAINetTestServer$2.evaluate(SAINetTestServer.java:340)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at ch.saierp.sainet.testing.suite.SAINetSuite.run(SAINetSuite.java:26)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
        at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)

Oct 16, 2018 7:41:29 PM com.sun.enterprise.v3.server.AppServerStartup$MasterRunLevelListener onError
SEVERE: Startup service failed to start
```

Since Payara doesn't even reach the deployment phase of our EAR, it seems that there are nothing we can do to get around this error.

## Environment ##

- **Payara Version**: 5.183
- **Edition**: payara-embedded-all
- **JDK Version**: OpenJDK 11
- **Operating System**: Linux
- **Database**: H2/GeoDB

Thanks in advance !

**Comment by smillidge** [comment]
The Payara Platform is not supported on JDK 11. I'll tag this with JDK9 tag and close as their are duplicate issued for JDK9+ support

**Comment by ctabin** [comment]
Thanks for the reply, I'll follow #2296 !
