### ISSUE TITLE
Web Console 403 LDAPRealm.getGroupNames Exception

### ISSUE THREAD

**Issue by fz288** [payara/Payara#3301]
# Description #
----------

403 after successful login to web console using LDAP authentication (built from source with fix #3157 included)

asadmin functions properly

## Expected Outcome

Web console should load after successful login

## Current Outcome

403 error and exception thrown in server.log

`[Payara 5.184-SNAPSHOT] [FINE] [] [javax.enterprise.system.core.security] [tid: _ThreadID=199 _ThreadName=admin-thread-pool::admin-listener(8)] [timeMillis: 1540209378780] [levelValue: 500] [CLASSNAME: com.sun.enterprise.security.auth.JaspicToJaasBridge] [METHODNAME: addRealmGroupsToSubject] [[
  Exception when trying to populate groups for CallerPrincipal username
java.lang.ClassCastException: java.util.LinkedList cannot be cast to java.util.Vector
	at com.sun.enterprise.security.auth.realm.ldap.LDAPRealm.getGroupNames(LDAPRealm.java:413)
	at com.sun.enterprise.security.auth.JaspicToJaasBridge.addRealmGroupsToSubject(JaspicToJaasBridge.java:184)
	at com.sun.enterprise.security.jmac.callback.BaseContainerCallbackHandler.processCallerPrincipal(BaseContainerCallbackHandler.java:411)
	at com.sun.enterprise.security.jmac.callback.BaseContainerCallbackHandler.processCallback(BaseContainerCallbackHandler.java:190)
	at com.sun.enterprise.security.jmac.callback.ServerContainerCallbackHandler.handleSupportedCallbacks(ServerContainerCallbackHandler.java:75)
	at com.sun.enterprise.security.jmac.callback.BaseContainerCallbackHandler.handle(BaseContainerCallbackHandler.java:181)
	at com.sun.enterprise.security.jmac.callback.ContainerCallbackHandler.handle(ContainerCallbackHandler.java:82)
	at org.glassfish.admingui.common.security.AdminConsoleAuthModule.notifyContainerAboutLogin(AdminConsoleAuthModule.java:361)
	at org.glassfish.admingui.common.security.AdminConsoleAuthModule.validateRequest(AdminConsoleAuthModule.java:206)
	at com.sun.enterprise.security.jmac.config.GFServerConfigProvider$GFServerAuthContext.validateRequest(GFServerConfigProvider.java:869)
	at com.sun.web.security.realmadapter.JaspicRealm.validateRequest(JaspicRealm.java:389)
	at com.sun.web.security.realmadapter.JaspicRealm.validateRequest(JaspicRealm.java:356)
	at com.sun.web.security.realmadapter.JaspicRealm.validateRequest(JaspicRealm.java:182)
	at com.sun.web.security.RealmAdapter.invokeAuthenticateDelegate(RealmAdapter.java:506)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:724)
	at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:579)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:159)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:516)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:213)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:208)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:208)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
]]`

## Steps to reproduce (Only for bug reports) 

Basic setup and switch from default file authentication to LDAP for administration.

## Environment ##

- **Payara Version**: d875a7748c66a310943460d1575873beb5fde62c (5.183+)
- **Edition**: Full
- **JDK Version**: Oracle 1.8.0_181
- **Operating System**: Windows

**Comment by svendiedrichsen** [comment]
@fz288 Would you mind trying fix #3302 ?

**Comment by fz288** [comment]
@svendiedrichsen just did a quick test and it looks good on my end, thanks!

**Comment by arjantijms** [comment]
@svendiedrichsen @fz288 thanks to you both!

**Comment by svendiedrichsen** [comment]
@fz288 Thanks for the quick check. @arjantijms Thanks for Payara Server and keeping the old Glassfish snappy.

I like open source software. ;)

**Comment by arjantijms** [comment]
Me too. I too have been trying to clean up a bunch of the old code (formatting, variable naming, etc). Great to have some help there ;)

**Comment by arjantijms** [comment]
Tracked internally by PAYARA-3190
