### ISSUE TITLE
asadmin Exceptions

### ISSUE THREAD

**Issue by fz288** [payara/Payara#3306]
# Description #
----------
Throwing these in together, I think they may all be related, sorry for the wall of text...

Running asadmin in interactive mode with no arguments and no domains running a NullPointerException is thrown

When trying to change-admin-password from interactive mode
  Prompted for admin username
  First keystroke goes to password prompt
  Next keystroke throws exception

When running local interactive mode without saved credentials, domain running with non-default admin password
  Prompted to accept cert
  Prompted for admin username
    First keystroke immediately goes to password prompt
    Second keystroke throws exception

When launching in interactive mode, with a local domain running using default master password, runs fine

When launching in interactive mode, non-default admin password, with saved credentials, with a local domain running, runs fine

When running in remote interactive mode with saved credentials, runs fine

## Expected Outcome

No exceptions

## Current Outcome

Various exceptions, see below

## Steps to reproduce (Only for bug reports) 

**No Domains Running**

> C:\payara5\glassfish\bin>asadmin
Use "exit" to exit and "help" for online help.
Exception in thread "main" java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Unknown Source)
        at java.util.Arrays$ArrayList.<init>(Unknown Source)
        at java.util.Arrays.asList(Unknown Source)
        at jline.console.completer.StringsCompleter.<init>(StringsCompleter.java:40)
        at com.sun.enterprise.admin.cli.MultimodeCommand.getAllCommandsCompleter(MultimodeCommand.ja
va:349)
        at com.sun.enterprise.admin.cli.MultimodeCommand.executeCommand(MultimodeCommand.java:171)
        at com.sun.enterprise.admin.cli.CLICommand.execute(CLICommand.java:324)
        at com.sun.enterprise.admin.cli.AdminMain.executeCommand(AdminMain.java:363)
        at com.sun.enterprise.admin.cli.AdminMain.doMain(AdminMain.java:298)
        at org.glassfish.admin.cli.AsadminMain.main(AsadminMain.java:56)

**Local interactive mode without saved credentials, domain running with non-default admin password (already accepted cert)**

> C:\payara5\glassfish\bin>asadmin
Use "exit" to exit and "help" for online help.
Enter admin user name>  Enter admin password for user "a"> Exception in thread "main" java.io.IOErro
r: java.io.IOException: The parameter is incorrect
        at java.io.Console.readPassword(Unknown Source)
        at com.sun.enterprise.admin.cli.CLICommand.readPassword(CLICommand.java:1191)
        at com.sun.enterprise.admin.cli.remote.RemoteCLICommand.access$1600(RemoteCLICommand.java:91
)
        at com.sun.enterprise.admin.cli.remote.RemoteCLICommand$CLIRemoteAdminCommand.updateAuthenti
cation(RemoteCLICommand.java:205)
        at com.sun.enterprise.admin.remote.RemoteRestAdminCommand.doHttpCommand(RemoteRestAdminComma
nd.java:1170)
        at com.sun.enterprise.admin.remote.RemoteRestAdminCommand.doHttpCommand(RemoteRestAdminComma
nd.java:1008)
        at com.sun.enterprise.admin.remote.RemoteRestAdminCommand.executeRemoteCommand(RemoteRestAdm
inCommand.java:759)
        at com.sun.enterprise.admin.remote.RemoteRestAdminCommand.executeCommand(RemoteRestAdminComm
and.java:570)
        at com.sun.enterprise.admin.cli.remote.RemoteCLICommand.executeCommand(RemoteCLICommand.java
:747)
        at com.sun.enterprise.admin.cli.CLICommand.execute(CLICommand.java:324)
        at com.sun.enterprise.admin.cli.remote.RemoteCLICommand.execute(RemoteCLICommand.java:582)
        at com.sun.enterprise.admin.cli.remote.RemoteCLICommand.executeAndReturnActionReport(RemoteC
LICommand.java:834)
        at com.sun.enterprise.admin.cli.CLIUtil.getRemoteCommands(CLIUtil.java:255)
        at com.sun.enterprise.admin.cli.CLIUtil.getAllCommands(CLIUtil.java:204)
        at com.sun.enterprise.admin.cli.MultimodeCommand.getAllCommandsCompleter(MultimodeCommand.ja
va:349)
        at com.sun.enterprise.admin.cli.MultimodeCommand.executeCommand(MultimodeCommand.java:171)
        at com.sun.enterprise.admin.cli.CLICommand.execute(CLICommand.java:324)
        at com.sun.enterprise.admin.cli.AdminMain.executeCommand(AdminMain.java:363)
        at com.sun.enterprise.admin.cli.AdminMain.doMain(AdminMain.java:298)
        at org.glassfish.admin.cli.AsadminMain.main(AsadminMain.java:56)
Caused by: java.io.IOException: The parameter is incorrect
        at java.io.Console.echo(Native Method)
        ... 20 more

C:\payara5\glassfish\bin>

**Local domain running with default admin password, try to change-admin-password from interactive mode**

> C:\payara5\glassfish\bin>asadmin
Use "exit" to exit and "help" for online help.
asadmin> change-admin-password
Enter admin user name [default: admin]>Enter the admin password> Exception in thread "main" java.io.
IOError: java.io.IOException: The parameter is incorrect
        at java.io.Console.readPassword(Unknown Source)
        at com.sun.enterprise.admin.cli.CLICommand.readPassword(CLICommand.java:1191)
        at com.sun.enterprise.admin.cli.CLICommand.getPassword(CLICommand.java:1134)
        at com.sun.enterprise.admin.cli.CLICommand.getPassword(CLICommand.java:1074)
        at com.sun.enterprise.admin.servermgmt.cli.ChangeAdminPasswordCommand.validate(ChangeAdminPa
sswordCommand.java:132)
        at com.sun.enterprise.admin.cli.CLICommand.execute(CLICommand.java:313)
        at com.sun.enterprise.admin.cli.MultimodeCommand.executeCommands(MultimodeCommand.java:274)
        at com.sun.enterprise.admin.cli.MultimodeCommand.executeCommand(MultimodeCommand.java:173)
        at com.sun.enterprise.admin.cli.CLICommand.execute(CLICommand.java:324)
        at com.sun.enterprise.admin.cli.AdminMain.executeCommand(AdminMain.java:363)
        at com.sun.enterprise.admin.cli.AdminMain.doMain(AdminMain.java:298)
        at org.glassfish.admin.cli.AsadminMain.main(AsadminMain.java:56)
Caused by: java.io.IOException: The parameter is incorrect
        at java.io.Console.echo(Native Method)
        ... 12 more

C:\payara5\glassfish\bin>

## Environment ##

- **Payara Version**: d875a77 (5.183+)
- **Edition**: Full
- **JDK Version**: Oracle 1.8.0_181
- **Operating System**: Windows

**Comment by Cousjava** [comment]
This is a known issue that has already been fixed by #3300
