### ISSUE TITLE
DB connection from pool not closing

### ISSUE THREAD

**Issue by bit-ionutursuleanu** [payara/Payara#3352]
Hi,

Sometimes (usually when it's a lot of activity on the server) the DB connections aren't closed immediately. See the below trace. The problem is that this connections are not closed, so the pool is full and new connections aren't allocated and the application freezes

Transaction type: Web
Transaction name: GET /webapi/rest/auth/userRoles
Duration: 3,533,858.0 milliseconds
CPU time: 7.7 milliseconds
"http-thread-pool(32)" #2000
```
   java.lang.Thread.State: WAITING
        at sun.misc.Unsafe.park(Native Method)
        - waiting on java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync@16ee0c5b
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
        at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(ReentrantReadWriteLock.java:943)
        at com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
        at com.sun.enterprise.resource.pool.ConnectionPool.freeResource(ConnectionPool.java:1064)
        at com.sun.enterprise.resource.pool.ConnectionPool.freeUnenlistedResource(ConnectionPool.java:1053)
        at com.sun.enterprise.resource.pool.ConnectionPool.resourceClosed(ConnectionPool.java:1017)
        at com.sun.enterprise.resource.pool.PoolManagerImpl.putbackResourceToPool(PoolManagerImpl.java:426)
        at com.sun.enterprise.resource.pool.PoolManagerImpl.resourceClosed(PoolManagerImpl.java:380)
        at com.sun.enterprise.resource.listener.LocalTxConnectionEventListener.connectionClosed(LocalTxConnectionEventListener.java:77)
        at com.sun.gjc.spi.ManagedConnectionImpl.connectionClosed(ManagedConnectionImpl.java:840)
        at com.sun.gjc.spi.base.ConnectionHolder.close(ConnectionHolder.java:214)
        at com.sun.gjc.spi.jdbc40.ConnectionHolder40.close(ConnectionHolder40.java:604)
        at org.compiere.util.CPreparedStatement.close(CPreparedStatement.java:144)

```

Can't reproduce this so I cant' say if this behaviour is still present on the newer versions.

## Environment ##

- **Payara Version**: 4.164
- **Edition**: Full
- **JDK Version**: 8 
- **Operating System**: Linux
- **Database**: Oracle

**Comment by smillidge** [comment]
This could be due to anything sorry. Also the version quoted is nearly 2 years old. Please try to reproduce on a later version.

**Comment by bit-ionutursuleanu** [comment]
Hi @smillidge ,

I think the issue is with [RWLockDataStructure](https://github.com/payara/Payara/blob/master/appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/datastructure/RWLockDataStructure.java ) According to [docs](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/locks/ReentrantReadWriteLock.html) there is no priority for the writer lock, so starvation could occur I connections not being released

> This class does not impose a reader or writer preference ordering for lock access. However, it does support an optional fairness policy.

Some more details [here](https://www.javaspecialists.eu/archive/Issue165.html) about ReentrantReadWriteLock starvation.

Considering [RWLockDataStructure](https://github.com/payara/Payara/blob/master/appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/datastructure/RWLockDataStructure.java )  isn't modified from 2011 I think this behaviour is present in all payara versions, though is difficult to reproduce

**Comment by smillidge** [comment]
We will need a test case demonstrating the issue on the latest release to do anything with this issue.

**Comment by smillidge** [comment]
Closing this issue due to inactivity by the requestor

**Comment by calentadorsolarpasoapaso** [comment]
The issue can be reproduced easily with an stress test.

Thread "jk-thread-pool1::jk-connector(3)" thread-id: 109 thread-state: WAITING Waiting on lock: java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync@10012f66
	 at: java.base@11.0.11/jdk.internal.misc.Unsafe.park(Native Method)
	 at: java.base@11.0.11/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	 at: java.base@11.0.11/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
	 at: java.base@11.0.11/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
	 at: java.base@11.0.11/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
	 at: java.base@11.0.11/java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(ReentrantReadWriteLock.java:959)
	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	 at: com.sun.enterprise.resource.pool.ConnectionPool.freeResource(ConnectionPool.java:1084)
	 at: com.sun.enterprise.resource.pool.ConnectionPool.transactionCompleted(ConnectionPool.java:1197)
	 at: com.sun.enterprise.resource.pool.PoolManagerImpl.transactionCompleted(PoolManagerImpl.java:315)
	 at: com.sun.enterprise.resource.pool.PoolManagerImpl$SynchronizationListener.afterCompletion(PoolManagerImpl.java:665)
	 at: com.sun.jts.jta.SynchronizationImpl.after_completion(SynchronizationImpl.java:156)
	 at: com.sun.jts.CosTransactions.RegisteredSyncs.distributeAfter(RegisteredSyncs.java:199)
	 at: com.sun.jts.CosTransactions.TopCoordinator.afterCompletion(TopCoordinator.java:2666)
	 at: com.sun.jts.CosTransactions.CoordinatorTerm.commit(CoordinatorTerm.java:414)
	 at: com.sun.jts.CosTransactions.TerminatorImpl.commit(TerminatorImpl.java:231)
	 at: com.sun.jts.CosTransactions.CurrentImpl.commit(CurrentImpl.java:622)
	 at: com.sun.jts.jta.TransactionManagerImpl.commit(TransactionManagerImpl.java:331)
	 at: com.sun.enterprise.transaction.jts.JavaEETransactionManagerJTSDelegate.commitDistributedTransaction(JavaEETransactionManagerJTSDelegate.java:183)
	 at: com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.commit(JavaEETransactionManagerSimplified.java:965)
	 at: com.sun.ejb.containers.EJBContainerTransactionManager.completeNewTx(EJBContainerTransactionManager.java:666)
	 at: com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:482)
	 at: com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4592)
	 at: com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2125)
	 at: com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2095)
	 at: com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:212)
	 at: com.sun.ejb.containers.EJBObjectInvocationHandlerDelegate.invoke(EJBObjectInvocationHandlerDelegate.java:79)
	 at: com.sun.proxy.$Proxy725.processFile(Unknown Source)
	 at: jdk.internal.reflect.GeneratedMethodAccessor1027.invoke(Unknown Source)
	 at: java.base@11.0.11/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at: java.base@11.0.11/java.lang.reflect.Method.invoke(Method.java:566)
	 at: com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.privateInvoke(StubInvocationHandlerImpl.java:229)

**Comment by calentadorsolarpasoapaso** [comment]
earch "RWLockDataStructure" (102 hits in 1 file of 1 searched)
  new 51 (102 hits)
	Line 1606: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 1606: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 1759: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 1759: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 1930: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 1930: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 2308: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 2308: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 2461: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 2461: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 2632: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 2632: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 2785: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 2785: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 3055: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 3055: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 3208: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 3208: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 3397: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 3397: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 3667: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 3667: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 3937: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 3937: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 4207: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 4207: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 4485: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.addResource(RWLockDataStructure.java:98)
	Line 4485: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.addResource(RWLockDataStructure.java:98)
	Line 4758: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 4758: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 5064: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 5064: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 5352: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 5352: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 5523: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 5523: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 5793: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 5793: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 5982: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 5982: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 6252: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 6252: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 6522: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 6522: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 6675: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 6675: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 6846: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 6846: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 7179: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 7179: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 7449: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 7449: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 7602: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 7602: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 7773: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 7773: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 8034: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 8034: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 8304: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 8304: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 8574: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 8574: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 8880: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 8880: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 9168: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 9168: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 9456: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 9456: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.getResource(RWLockDataStructure.java:116)
	Line 9744: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
	Line 9744: 	 at: com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.returnResource(RWLockDataStructure.java:161)
