### ISSUE TITLE
Memory wastage - JavaEETransactionImpl

### ISSUE THREAD

**Issue by mafaul** [payara/Payara#3396]
# Description #
----------
Java EE Transactions - after a transaction has been successfully completed (state == 3), it is not eligible for garbage collection until it times out (300 seconds by default on Payara). On large enterprise applications with lots of users calling lots of EJB methods, this can easily occupy lots of heap space unnecessarily (10GB+). It is not really a memory leak, because it will eventually be reclaimed, but it is an issue because heap space is occupied unnecessarily for quite a while. This issue can have a noticeable impact on high volume applications.

Glassfish issue:
https://github.com/eclipse-ee4j/glassfish/issues/21565

## Expected Outcome
JavaEETranactionImpl objects should be eligible for Garbage Collection once it is done executing (state == 3) OR after it timed out (Whichever comes first)

Alternatively, as a workaround, create an annotation similar to org.jboss.ejb3.annotation.TransactionTimeout or weblogic.javaee.TransactionTimeoutSeconds so that we can set the default Transaction timeout to 20 seconds, but have the option to extend it for certain methods with this new annotation.

## Current Outcome
JavaEETranactionImpl objects are only eligible for Garbage Collection once it timed out, even if it completed a while ago already.

## Steps to reproduce (Sample)
[HeapSpaceApp.zip](https://github.com/payara/Payara/files/2563261/HeapSpaceApp.zip)

Compile (maven) and run the attached source on production domain (Payara 5.183).
Make sure that the Transaction Timout matches the setting in Payara (300) by default.
Open http://localhost:8080/HeapSpaceApp/

What you can expect:
![image](https://user-images.githubusercontent.com/12007706/48223526-f258a100-e39f-11e8-8ef7-af20a8a9d5a9.png)

Note the results:
**Before start:** 
Time: 21:20:25 Used Memory: 747.2 MB

**After transactions created.**
Time: 21:20:27 Used Memory: 1.1 GB

**After possible GC:**
Time: 21:20:29 Used Memory: 796.3 MB
Heap Dump:
![1](https://user-images.githubusercontent.com/12007706/48223623-3c418700-e3a0-11e8-9ff2-69c716d45b26.JPG)

**Waiting 5 minutes for transactions to time out. Will refresh automatically...
After possible GC after waiting 5 minutes for all transactions to expire.**
Time: 21:25:35 Used Memory: 752.0 MB
Heap dump:
![2](https://user-images.githubusercontent.com/12007706/48223657-4cf1fd00-e3a0-11e8-8f48-c95a6da3cb81.JPG)

Estimated heap space wasted for 5 minutes: **44.8 MB** (According to heap dump it's actually 10 MB)
You will see that all the generated records are still available (in bean property as list) at this point in time, just the JavaEETransactionImpl objects were Garbage-collected.

## Environment ##

- **Payara Version**: 5.183
- **Edition**: Full
- **JDK Version**: 8 u181 - Oracle
- **Operating System**: Windows

**Comment by svendiedrichsen** [comment]
@mafaul I'm trying to use your HeapSpaceApp to test a fix but I only get an exception. Do I have to configure it somehow?
```
javax.ejb.AccessLocalException: Client zu diesem Aufruf nicht autorisiert
	at com.sun.ejb.containers.BaseContainer.preInvoke(BaseContainer.java:2016)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:210)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
	at com.sun.proxy.$Proxy290.getEntities(Unknown Source)
	at com.test.__EJB31_Generated__WasteFacade__Intf____Bean__.getEntities(Unknown Source)
	at com.test.WasteBean.doTransactions(WasteBean.java:51)
	at com.test.WasteBean.runAutomateTest(WasteBean.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.el.ELUtil.invokeMethod(ELUtil.java:332)
	at javax.el.BeanELResolver.invoke(BeanELResolver.java:537)
	at javax.el.CompositeELResolver.invoke(CompositeELResolver.java:256)
	at com.sun.el.parser.AstValue.invoke(AstValue.java:283)
	at com.sun.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:304)
	at org.jboss.weld.module.web.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
	at org.jboss.weld.module.web.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
	at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:89)
	at javax.faces.event.MethodExpressionActionListener.processAction(MethodExpressionActionListener.java:148)
	at javax.faces.event.ActionEvent.processListener(ActionEvent.java:96)
	at javax.faces.component.UIComponentBase.broadcast(UIComponentBase.java:514)
	at javax.faces.component.UICommand.broadcast(UICommand.java:235)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:871)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1419)
	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:82)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:201)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:731)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:475)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1628)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:258)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:755)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:575)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:159)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:516)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:213)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
]]
```

**Comment by mafaul** [comment]
@svendiedrichsen please try: https://stackoverflow.com/a/33519020/2359435

**Comment by svendiedrichsen** [comment]
@mafaul Sorry, my fault. Forgot to add maven dependency to the JTA module. Results of your test application are looking better now.

<img width="494" alt="bildschirmfoto 2018-11-09 um 09 41 49" src="https://user-images.githubusercontent.com/3110558/48252050-ee5e6a80-e403-11e8-94e0-da55d6aca29e.png">

**Comment by svendiedrichsen** [comment]
The second run was good now.

<img width="490" alt="bildschirmfoto 2018-11-09 um 09 49 53" src="https://user-images.githubusercontent.com/3110558/48252409-fc60bb00-e404-11e8-8d84-afebeb625c8e.png">

**Comment by svendiedrichsen** [comment]
@mafaul Did you ever tried to set the property `server-config.transaction-service.property.purge-cancelled-transactions-after` of the transaction service? This determines the number of cancelled transactions after which the list of cancelled transactions gets purged. This defaults to 0 which means never.

**Comment by svendiedrichsen** [comment]
@smillidge How do you think about that? Would you rather keep the Timer/TimerTask implementation and improve on the purge trigger or replace it with PayaraExecuterService for scheduling?

**Comment by mafaul** [comment]
@svendiedrichsen, i didn't know about that. We added the server-config.transaction-service.property.purge-cancelled-transactions-after property and it works well in prod. We set it to 1000 and our heap memory footprint reduced from 27 GB to 5 GB. Maybe this should be the default for the **production** domain in Payara?

**Comment by svendiedrichsen** [comment]
@mafaul Thats great news. I have already proposed a change to add this property to the production domain.xml.
