### ISSUE TITLE
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60))

### ISSUE THREAD

**Issue by guogang1990** [payara/Payara#3457]
# Description #
----------

**com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')**

After my springmvc configured MappingJackson2HttpMessageConverter, @ResponseBody still converted me to XML format instead of the json format I want. I am positioning the problem at this step.

The output stream format that I got in the FILTER stream is incorrect.

I tested it with glassfish version 4.1.

Please help me! thinks !

## Expected Outcome
`[2018-11-30T11:16:30.466+0800] [Payara 5.183] [INFO] [] [] [tid: _ThreadID=31 _ThreadName=http-thread-pool::http-listener-1(4)] [timeMillis: 1543547790466] [levelValue: 800] [[
  11:16:30.466 [http-thread-pool::http-listener-1(4)] ERROR javax.servlet.Filter - ContextFilte doExceute Exception
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (String)"<OutResponse><code>0000</code><desc>SUCCESS</desc><data><userId>523</userId><mobile>18642882049</mobile><userImgPath>default_head.png</userImgPath><nickName>xxxx</nickName><guessCoin>0</guessCoin><status>1</status><regTime>2018-11-27 14:22:37</regTime><msgToken/><terminalNumber/><terminalModel/><terminalOS/><sessionId>29e2409c7804d2fa0d6d46e489ea</sessionId></data></OutResponse>"; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804) ~[jackson-core.jar:2.9.5]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:663) ~[jackson-core.jar:2.9.5]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:561) ~[jackson-core.jar:2.9.5]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1892) ~[jackson-core.jar:2.9.5]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:747) ~[jackson-core.jar:2.9.5]
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4129) ~[jackson-databind.jar:2.9.5]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3988) ~[jackson-databind.jar:2.9.5]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992) ~[jackson-databind.jar:2.9.5]
        at com.jlibom.zmEntrance.utils.JsonUtil.convertJsonStr2Obj(JsonUtil.java:23) ~[JsonUtil.class:?]
        at com.jlibom.zmEntrance.filter.ContextFilter.convert(ContextFilter.java:115) ~[ContextFilter.class:?]
        at com.jlibom.zmEntrance.filter.ContextFilter.export(ContextFilter.java:104) ~[ContextFilter.class:?]
        at com.jlibom.zmEntrance.filter.ContextFilter.doExecute(ContextFilter.java:74) [ContextFilter.class:?]
        at com.jlibom.zmEntrance.filter.ContextFilter.doFilter(ContextFilter.java:55) [ContextFilter.class:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:251) [web-core.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:209) [web-core.jar:?]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:256) [web-core.jar:?]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160) [web-core.jar:?]
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:755) [web-core.jar:?]
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:575) [web-core.jar:?]
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99) [web-glue.jar:?]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:159) [web-core.jar:?]
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371) [web-core.jar:?]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238) [web-core.jar:?]
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:516) [kernel.jar:?]
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:213) [kernel.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549) [nucleus-grizzly-all.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
]]
`

### Glassfish 4.1 current output
`[2018-11-30T11:40:49.007+0800] [glassfish 4.1] [WARNING] [] [javax.enterprise.system.container.web.com.sun.web.security] [tid: _ThreadID=27 _ThreadName=http-listener-1(1)] [timeMillis: 1543549249007] [levelValue: 900] [[
  Context path from ServletContext:  differs from path from bundle: /]]

[2018-11-30T11:40:49.121+0800] [glassfish 4.1] [INFO] [] [] [tid: _ThreadID=27 _ThreadName=Thread-8] [timeMillis: 1543549249121] [levelValue: 800] [[
  11:40:49.121 [http-listener-1(1)] INFO  javax.servlet.Filter - ======>ContextFilter start]]

[2018-11-30T11:40:49.152+0800] [glassfish 4.1] [INFO] [] [] [tid: _ThreadID=27 _ThreadName=Thread-8] [timeMillis: 1543549249152] [levelValue: 800] [[
  11:40:49.152 [http-listener-1(1)] INFO  javax.servlet.Filter - input：{"key":"WEHSLh8NZ/JN3TPdxBQ99VXwFpRY6R+Lxt5eSSZGPPYXGhX8S4Ls2xx0UiHkooA6ODnRG9aZ2Vh4Uvf6LaNv0AUPN9PUxTIexQyFlpooVdf8PywmDjxtvWBqF4DEM4oqireYW0zUMBk040PhOauh7qlh/WIxMCLxnRXY/LnTwVs=", "context":"JcLRzyRc79f9s7XUKgkbWTybFXZ4zFYQjNvDLyiqVgYxb7M+CaVzXjn49xntRGh0i+7RqMJWk8sGPVp2guideVuUow20FTb9ftdugc9zJbqsn5tjLzelMhl8QFYavJ/RyvsXGTCojgZxLRMLL7GpvQ=="}]]

[2018-11-30T11:40:49.778+0800] [glassfish 4.1] [INFO] [] [] [tid: _ThreadID=27 _ThreadName=Thread-8] [timeMillis: 1543549249778] [levelValue: 800] [[
  11:40:49.777 [http-listener-1(1)] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'loginController']]

[2018-11-30T11:40:50.098+0800] [glassfish 4.1] [INFO] [] [] [tid: _ThreadID=27 _ThreadName=Thread-8] [timeMillis: 1543549250098] [levelValue: 800] [[
  11:40:50.092 [http-listener-1(1)] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'aopInterceptor']]

[2018-11-30T11:40:50.099+0800] [glassfish 4.1] [INFO] [] [] [tid: _ThreadID=27 _ThreadName=Thread-8] [timeMillis: 1543549250099] [levelValue: 800] [[
  11:40:50.099 [http-listener-1(1)] INFO  com.jlibom.zmEntrance.interceptor.AopInterceptor - @Around:切入contorller --------start]]

[2018-11-30T11:40:50.111+0800] [glassfish 4.1] [INFO] [] [] [tid: _ThreadID=27 _ThreadName=Thread-8] [timeMillis: 1543549250111] [levelValue: 800] [[
  11:40:50.111 [http-listener-1(1)] INFO  com.jlibom.zmEntrance.interceptor.AopInterceptor - @Around:切入contorller target method:com.jlibom.zmEntrance.controller.user.LoginController.pwdLogin]]

[2018-11-30T11:40:50.118+0800] [glassfish 4.1] [INFO] [] [] [tid: _ThreadID=27 _ThreadName=Thread-8] [timeMillis: 1543549250118] [levelValue: 800] [[
  11:40:50.118 [http-listener-1(1)] INFO  com.jlibom.zmEntrance.interceptor.AopInterceptor - @Around:切入contorller paramters:[MsgCodeVo [mobile=18642882049], com.jlibom.zmEntrance.utils.wrapper.RequestWrapper@61f8d446]]]

[2018-11-30T11:40:50.423+0800] [glassfish 4.1] [INFO] [] [] [tid: _ThreadID=27 _ThreadName=Thread-8] [timeMillis: 1543549250423] [levelValue: 800] [[
  11:40:50.423 [http-listener-1(1)] INFO  com.jlibom.zmEntrance.controller.user.LoginController - login sucess！userId：523]]

[2018-11-30T11:40:50.466+0800] [glassfish 4.1] [INFO] [] [] [tid: _ThreadID=27 _ThreadName=Thread-8] [timeMillis: 1543549250466] [levelValue: 800] [[
  11:40:50.465 [http-listener-1(1)] INFO  com.jlibom.zmEntrance.interceptor.AopInterceptor - return orsOutResponse [code=0000, desc=SUCCESS, data=CenterUserLogin [userId=523, mobile=18642882049, password=f3c2a30c7034406e2d0b31103b09ea28]]]]

[2018-11-30T11:40:50.579+0800] [glassfish 4.1] [INFO] [] [] [tid: _ThreadID=27 _ThreadName=Thread-8] [timeMillis: 1543549250579] [levelValue: 800] [[
  11:40:50.579 [http-listener-1(1)] INFO  javax.servlet.Filter - 输出流里获取的报文：{"code":"0000","desc":"SUCCESS","data":{"userId":"523","mobile":"186xxxxxxxx","userImgPath":"default_head.png","nickName":"xxxx","guessCoin":0,"status":"1","regTime":"2018-11-27 14:22:37","msgToken":null,"terminalNumber":null,"terminalModel":null,"terminalOS":null,"sessionId":"2b46b83734ede2ba707ae45ac5f2"}}]]

[2018-11-30T11:40:50.580+0800] [glassfish 4.1] [INFO] [] [] [tid: _ThreadID=27 _ThreadName=Thread-8] [timeMillis: 1543549250580] [levelValue: 800] [[
  11:40:50.580 [http-listener-1(1)] INFO  javax.servlet.Filter - 返回报文加密前报文：{"code":"0000","desc":"SUCCESS","data":{"userId":"523","mobile":"186xxxxxxxx","userImgPath":"default_head.png","nickName":"xxxx","guessCoin":0,"status":"1","regTime":"2018-11-27 14:22:37","msgToken":null,"terminalNumber":null,"terminalModel":null,"terminalOS":null,"sessionId":"2b46b83734ede2ba707ae45ac5f2"}}]]

[2018-11-30T11:40:50.621+0800] [glassfish 4.1] [INFO] [] [] [tid: _ThreadID=27 _ThreadName=Thread-8] [timeMillis: 1543549250621] [levelValue: 800] [[
  11:40:50.621 [http-listener-1(1)] INFO  javax.servlet.Filter - ContextFilter->conver t返回报文加密前报文：{"userId":"523","mobile":"186xxxxxxxx","userImgPath":"default_head.png","nickName":"xxxx","guessCoin":0,"status":"1","regTime":"2018-11-27 14:22:37","msgToken":null,"terminalNumber":null,"terminalModel":null,"terminalOS":null,"sessionId":"2b46b83734ede2ba707ae45ac5f2"}]]

[2018-11-30T11:40:50.625+0800] [glassfish 4.1] [INFO] [] [] [tid: _ThreadID=27 _ThreadName=Thread-8] [timeMillis: 1543549250625] [levelValue: 800] [[
  11:40:50.625 [http-listener-1(1)] INFO  javax.servlet.Filter - 返回报文加密后报文：{"code":"0000","desc":"SUCCESS","data":"Rgp10lvHwPZPP01pvVLLW7gZE6rlMfnOQhTL39R/srGCbzUGgTrgigX7XueI4uttFqtLIxIKJ/Ar77iTBST/Ojrf6fvChNmlvPyC/rDbhdsCGtWS4EqgjfF7pRDrwx4o+zeOpBHCQptq2MWRHsj+hNr8Rc0EZk9a0WeTbfpbAgPtc1qsPKfAB65ZeFc7IRxXg789MaoNvsna4vvK5rd0760xcM/SlOTG4ZMTrUfZyutaFHZ/kxd5ppqLmevMErOQGr321cLJH7JK4us0lRyoFu48hr9Le5sLSYG2rOr5PP08Yr1Q8dHd3UGSPQm1c2wLH0hwZdluiAG+xSHNeJOhTchCCm7YFFtXRN+OZKvjfRyt9PxxPDwj2g=="}]]

[2018-11-30T11:40:50.653+0800] [glassfish 4.1] [INFO] [] [] [tid: _ThreadID=27 _ThreadName=Thread-8] [timeMillis: 1543549250653] [levelValue: 800] [[
  11:40:50.653 [http-listener-1(1)] INFO  javax.servlet.Filter - <======ContextFilter end]]`

## Environment ##

- **Payara Version**: 5.183
- **Edition**: Full
- **JDK Version**: 25.181-b13 OpenJDK 
- **Operating System**: Linux 
- **Database**: MySQL

**Comment by smillidge** [comment]
GlassFish for has Java EE 7 apis. Payara 5 is based on GlassFish 5 which has Java EE 8 apis. Have you done anything to upgrade your application to Java EE 8?

If you think there is a bug in Payara please provide a test case.

**Comment by smillidge** [comment]
Closing this issue due to inactivity by the requestor
