### ISSUE TITLE
Deadlock in FileSystems.getDefault() on Payara startup

### ISSUE THREAD

**Issue by chrjohn** [payara/Payara#3489]
# Description #
----------

This does not occur every time and sadly is not reproducible but it happens about 5-10% of the time when starting up Payara. Tested with 5.183 and 5.184. Strange enough we did not see this with Payara 4.1.2.174.

## Expected Outcome

Payara should startup reliably.

## Current Outcome

A thread and the FelixStartLevel thread both try to access FileSystems.getDefault(), effectively resulting in a deadlock.

[payara-jstack-5184.txt](https://github.com/payara/Payara/files/2644092/payara-jstack-5184.txt)
[payara-jstack-5183.txt](https://github.com/payara/Payara/files/2644093/payara-jstack-5183.txt)

This seems to be a known bug with JDK 8. See here: https://bugs.openjdk.java.net/browse/JDK-8194653
But as long as Payara does not work with JDK 11 we are kind of blocked here since we do not want to use JDK 9 or 10 due to end-of-life.

In the beginning we had this problem when deploying some of our OSGi bundles. We then worked around it by adding a call to FileSystems.getDefault() (on all available classloaders) to the BundleActivator of one of our bundles. But now the problem occurs in Payara code before even starting one of our bundles.

## Steps to reproduce (Only for bug reports) 

Startup Payara and hope that it fails. ;) To be honest it seems to be something special to the JDK version or the OS since I did not find other users of Payara reporting this.
But it seems to be happening in other third party software as well, e.g. https://github.com/gatling/gatling/issues/3411
So maybe Payara can introduce a similar workaround?

## Environment ##

- **Payara Version**: 5.183 / 5.184
- **Edition**: Full
- **JDK Version**: 1.8.0_172
- **Operating System**: Linux
- **Database**: n/a

**Comment by smillidge** [comment]
I have never seen this and start and stop Payara all the time in development

**Comment by chrjohn** [comment]
I was expecting this response, otherwise there probably already would have been a bug report for this.
As I said I suppose this has to do something with a specific JDK/OS combination.
Which OS and JDK version do you use, as a start?

**Comment by Cousjava** [comment]
Payara is tested on Ubuntu, OpenSUSE, CentOS, MacOS, Windows 10 and Windows Server 2016, using the latest JDK8 release (currently 8u192) from Azul.

**Comment by pdudits** [comment]
@chrjohn try single threaded startup mode:

````
asadmin create-jvm-options --target server-config "-Dorg.glassfish.startupThreadPolicy=USE_NO_THREADS"
````

**Comment by smillidge** [comment]
This doesn't look like a deadlock as the thread holding the runtime lock is RUNNABLE it is not blocked on another lock. Is there some locking problem on the filesystem?

**Comment by chrjohn** [comment]
I was just using the same wording as the official JDK bug. It is stated in the bug:

> Note that this is really part of a general race problem between class initialization and classes loading native libraries under a global lock. 

Maybe file system locking plays a role although I am of the assumption that Linux in general has rather minimal file locking. But probably also depends on the implementation.

**Comment by svendiedrichsen** [comment]
In the example for Payara 184 I can see 2 threads in a deadlock:
Thread 1:
{code}
"FelixStartLevel" #23 daemon prio=5 os_prio=0 tid=0x00007f7370c2a000 nid=0x5e48 waiting for monitor entry [0x00007f72ebaf5000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.lang.Runtime.loadLibrary0(Runtime.java:862)
	- waiting to lock <0x00000000815195d8> (a java.lang.Runtime)
	at java.lang.System.loadLibrary(System.java:1122)
	at sun.nio.fs.UnixNativeDispatcher$1.run(UnixNativeDispatcher.java:573)
	at sun.nio.fs.UnixNativeDispatcher$1.run(UnixNativeDispatcher.java:571)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.nio.fs.UnixNativeDispatcher.<clinit>(UnixNativeDispatcher.java:571)
	at sun.nio.fs.UnixFileSystem.<init>(UnixFileSystem.java:67)
	at sun.nio.fs.LinuxFileSystem.<init>(LinuxFileSystem.java:39)
	at sun.nio.fs.LinuxFileSystemProvider.newFileSystem(LinuxFileSystemProvider.java:46)
	at sun.nio.fs.LinuxFileSystemProvider.newFileSystem(LinuxFileSystemProvider.java:39)
	at sun.nio.fs.UnixFileSystemProvider.<init>(UnixFileSystemProvider.java:56)
	at sun.nio.fs.LinuxFileSystemProvider.<init>(LinuxFileSystemProvider.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.nio.fs.DefaultFileSystemProvider.createProvider(DefaultFileSystemProvider.java:48)
	at sun.nio.fs.DefaultFileSystemProvider.create(DefaultFileSystemProvider.java:63)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:108)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.access$000(FileSystems.java:89)
	at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:98)
	at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:96)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.defaultFileSystem(FileSystems.java:96)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.<clinit>(FileSystems.java:90)
	at java.nio.file.FileSystems.getDefault(FileSystems.java:176)
	at java.io.File.toPath(File.java:2234)
	- locked <0x00000000e8a8c298> (a java.io.File)
	at org.apache.felix.fileinstall.internal.Watcher.setRootDirectory(Watcher.java:103)
	at org.apache.felix.fileinstall.internal.WatcherScanner.<init>(WatcherScanner.java:57)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.<init>(DirectoryWatcher.java:197)
	at org.apache.felix.fileinstall.internal.FileInstall.updated(FileInstall.java:248)
	at org.apache.felix.fileinstall.internal.FileInstall.start(FileInstall.java:138)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)
{code}
Thread 2:
{code}
"Thread-11" #62 daemon prio=5 os_prio=0 tid=0x00007f7288169800 nid=0x5e76 in Object.wait() [0x00007f726ddbf000]
   java.lang.Thread.State: RUNNABLE
	at java.nio.file.FileSystems.getDefault(FileSystems.java:176)
	at java.nio.file.Paths.get(Paths.java:138)
	at sun.misc.Launcher$ExtClassLoader.findLibrary(Launcher.java:235)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1830)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	- locked <0x00000000815195d8> (a java.lang.Runtime)
	at java.lang.System.loadLibrary(System.java:1122)
	at sun.security.ec.SunEC$1.run(SunEC.java:60)
	at sun.security.ec.SunEC$1.run(SunEC.java:58)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ec.SunEC.<clinit>(SunEC.java:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:221)
	at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:206)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:206)
	at sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:187)
	- locked <0x0000000081589670> (a sun.security.jca.ProviderConfig)
	at sun.security.jca.ProviderList.getProvider(ProviderList.java:233)
	at sun.security.jca.ProviderList.getService(ProviderList.java:331)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:157)
	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
	at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96)
	- locked <0x00000000e907be30> (a java.lang.Class for javax.net.ssl.SSLContext)
	at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:122)
	- locked <0x00000000e907a660> (a java.lang.Class for javax.net.ssl.SSLSocketFactory)
	at javax.rmi.ssl.SslRMIServerSocketFactory.getDefaultSSLSocketFactory(SslRMIServerSocketFactory.java:368)
	- locked <0x00000000e9074e80> (a java.lang.Class for javax.rmi.ssl.SslRMIServerSocketFactory)
	at javax.rmi.ssl.SslRMIServerSocketFactory.<init>(SslRMIServerSocketFactory.java:180)
	at javax.rmi.ssl.SslRMIServerSocketFactory.<init>(SslRMIServerSocketFactory.java:118)
	at javax.rmi.ssl.SslRMIServerSocketFactory.<init>(SslRMIServerSocketFactory.java:80)
	at org.glassfish.admin.mbeanserver.ssl.SecureRMIServerSocketFactory.<init>(SecureRMIServerSocketFactory.java:92)
	at org.glassfish.admin.mbeanserver.RMIConnectorStarter.<init>(RMIConnectorStarter.java:163)
	at org.glassfish.admin.mbeanserver.JMXStartupService$JMXConnectorsStarterThread.startConnector(JMXStartupService.java:292)
	at org.glassfish.admin.mbeanserver.JMXStartupService$JMXConnectorsStarterThread.run(JMXStartupService.java:332)
	- locked <0x00000000e9e92798> (a java.lang.Object)
{code}

I would suggest, that the Module containing the {{org.glassfish.admin.mbeanserver.JMXStartupService}} should initialize the default filesystem by calling {{FileSystems.getDefault()}} at the most early moment in its initialization. Perhaps using a service with runlevel {{Integer.MIN_VALUE}} and call {{FileSystems.getDefault()}} in its initialization.

**Comment by chrjohn** [comment]
I agree with you although I think that @smillidge 's point was that *technically* it is no deadlock since not both threads are BLOCKED and FelixStartLevel thread holds no resource that Thread-11 wants to acquire.
But yeah, the result is the same. :)

**Comment by svendiedrichsen** [comment]
@chrjohn I can imagine this is a thread dump problem with lazy initialization using private static holder classes.

**Comment by svendiedrichsen** [comment]
@chrjohn I have created a branch with such a service: https://github.com/svendiedrichsen/Payara/tree/mbeanserver-warmup-service
Would you mind trying if this fixes the problem?

**Comment by chrjohn** [comment]
Hi @svendiedrichsen , wow, thanks for that. Just one question: that branch is against master, right? We cannot switch to 5.184 right now because of other problems (still need to find the cause for that).

I will copy your class over to the 5.183 branch and compile that. I'll let you know how it goes.

Thanks again,
Chris.

**Comment by svendiedrichsen** [comment]
@chrjohn Sure, but I will file the PR if this really works and the guys from Payara accept it against master first. If this gets ported back aftwards is none of my business. Backports to 5.183 are not done I believe.

Cheers, Sven

**Comment by chrjohn** [comment]
Hi Sven,

understood. I hope that it gets accepted although it is not reproducable.
Backporting is not necessary, I can do `mvn clean package`. ;)

Cheers,
Chris.

**Comment by chrjohn** [comment]
I have added the patched 5.183 to our CI/CD chain. I will report back in a few days.
Thanks :+1:

**Comment by chrjohn** [comment]
On another note: how can I check if the service was really loaded? I have added some `System.out.println` but it does not show in the log file.

**Comment by svendiedrichsen** [comment]
@chrjohn System.out.println does not go anywhere. You need to have a Logger and write to at least WARNING level. This should be visible.

**Comment by chrjohn** [comment]
Hi @svendiedrichsen ,
it was looking good up to now but just got the same problem as before. Unfortunately I did not manage to get a stack trace this time. All I can see that the problem was after server startup, i.e. there were already some bundles deployed. All I can say is that the deployment of a web bundle seems to be the one that was failing. Maybe web bundles deploy using another classloader?
Thanks,
Chris.

**Comment by svendiedrichsen** [comment]
@chrjohn That's impossible to analyze without any info. A reproducer is the only chance we can narrow this down.

**Comment by svendiedrichsen** [comment]
@chrjohn As far as I understand the problem in Java 8 s single service in one of the modules can't fix this. There needs to be this initialization during the boot of the server provided all modules will derive their classloaders from the one initialized during boot.

**Comment by smillidge** [comment]
Not sure what we can do with this issue. @chrjohn are you still experiencing this on latest JDK and Payara versions?

**Comment by rdebusscher** [comment]
Closing this as the JDK bug is resolved in 8u231.

**Comment by chrjohn** [comment]
Great, thanks for the information.
