### ISSUE TITLE
Cannot rollback application upgrade in web admin console

### ISSUE THREAD

**Issue by peraxel** [payara/Payara#351]
I have a web application (WAR) named e.g. "test-app" version 1.0 deployed on Payara 4.1.152.1 on Context path "test-app". When I release a new version of this app I want to be able to upgrade it on the Payara server with an option to rollback the upgrade if I discover a bug in the new version. I follow the pattern below. In step 4 it fails to enable the old version (doing rollback). 
1. Build new version
2. Disable old version on Payara 
3. Deploy new version on Payara (using the same context path as previous version)
4. If I discover a bug in the new version: Disable the new version and enable the old one. At this point the old version is not loaded and the following error is seen in the Payara log.

[2015-06-25T07:23:18.592+0200] [Payara 4.1] [WARNING] [] [javax.enterprise.system.core] [tid: _ThreadID=42 _ThreadName=admin-listener(1)] [timeMillis: 1435209798592] [levelValue: 900] [[
  failed to set enable attribute for test-app-1.0-SNAPSHOT
org.jvnet.hk2.config.TransactionFailure: Constraints for this Application configuration have been violated: on property [  ] violation reason [ Virtual server already has an application loaded at this context path therefore this application cannot be loaded at this context path on this virtual server ]
	at org.jvnet.hk2.config.WriteableView.canCommit(WriteableView.java:321)
	at org.jvnet.hk2.config.Transaction.canCommit(Transaction.java:89)
	at org.jvnet.hk2.config.Transaction.commit(Transaction.java:108)
	at org.jvnet.hk2.config.ConfigSupport._apply(ConfigSupport.java:181)
	at org.jvnet.hk2.config.ConfigSupport.apply(ConfigSupport.java:138)
	at org.jvnet.hk2.config.ConfigSupport.apply(ConfigSupport.java:117)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.updateAppEnabledAttributeInDomainXML(ApplicationLifecycle.java:1493)
	at org.glassfish.deployment.admin.EnableCommand.execute(EnableCommand.java:268)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:253)
	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:231)
	at org.glassfish.admin.rest.resources.TemplateExecCommand.executeCommandLegacyFormat(TemplateExecCommand.java:157)
	at org.glassfish.admin.rest.resources.TemplateCommandPostResource.processPostLegacyFormat(TemplateCommandPostResource.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:164)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:181)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:158)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:101)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:305)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:288)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1110)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:381)
	at org.glassfish.admin.rest.adapter.RestAdapter$2.service(RestAdapter.java:316)
	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:179)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:536)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.validation.ConstraintViolationException: Constraints for this Application configuration have been violated: on property [  ] violation reason [ Virtual server already has an application loaded at this context path therefore this application cannot be loaded at this context path on this virtual server ]
	at org.jvnet.hk2.config.WriteableView.handleValidationException(WriteableView.java:345)
	at org.jvnet.hk2.config.WriteableView.canCommit(WriteableView.java:319)
	... 68 more
]]

**Comment by smillidge** [comment]
This is similar to #270 does that issue cover your requirement?

**Comment by smillidge** [comment]
The error is actually in writing the domain.xml file. It is failing a validation of the file.

**Comment by mikecroft** [comment]
Hi @peraxel - we've fixed a few things in this area now ( #436 #602  #702 weld/core#1211 ) could you check that this is still an issue for you?

**Comment by mikecroft** [comment]
Hi @peraxel - is this still a problem with Payara Server 163?

**Comment by peraxel** [comment]
@mikecroft No, it's not a problem with Payara 163. Thanks.
