### ISSUE TITLE
Icefaces 1.8.2 + Payara 5.

### ISSUE THREAD

**Issue by vmmaSigmaaie** [payara/Payara#3716]
# Description #

I am facing a problem deploying an application on a Payara 5 server. The application is based on Icefaces 1.8.2 + Spring 3.2.18 and it is packaged as an EAR file.

## Current Outcome

I am getting the error shown bellow:

```
java.lang.IllegalArgumentException: Invalid ejb jar [XXX.jar]: it contains zero ejb.
Note:
1. A valid ejb jar requires at least one session, entity (1.x/2.x style), or message-driven bean.
2. EJB3+ entity beans (@Entity) are POJOs and please package them as library jar.
3. If the jar file contains valid EJBs which are annotated with EJB component level annotations (@Stateless, @Stateful, @MessageDriven, @Singleton), please check server.log to see whether the annotations were processed properly.
        at org.glassfish.ejb.deployment.util.EjbBundleValidator.accept(EjbBundleValidator.java:149)
        at org.glassfish.ejb.deployment.util.EjbBundleValidator.accept(EjbBundleValidator.java:114)
        at com.sun.enterprise.deployment.BundleDescriptor.visit(BundleDescriptor.java:643)
        at org.glassfish.ejb.deployment.descriptor.EjbBundleDescriptorImpl.visit(EjbBundleDescriptorImpl.java:767)
        at com.sun.enterprise.deployment.util.ApplicationValidator.accept(ApplicationValidator.java:121)
        at com.sun.enterprise.deployment.BundleDescriptor.visit(BundleDescriptor.java:643)
        at com.sun.enterprise.deployment.archivist.ApplicationArchivist.validate(ApplicationArchivist.java:723)
        at com.sun.enterprise.deployment.archivist.ApplicationArchivist.openWith(ApplicationArchivist.java:268)
        at com.sun.enterprise.deployment.archivist.ApplicationFactory.openWith(ApplicationFactory.java:232)
        at org.glassfish.javaee.core.deployment.DolProvider.processDOL(DolProvider.java:189)
        at org.glassfish.javaee.core.deployment.DolProvider.load(DolProvider.java:223)
        at org.glassfish.javaee.core.deployment.DolProvider.load(DolProvider.java:91)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.loadDeployer(ApplicationLifecycle.java:934)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.setupContainerInfos(ApplicationLifecycle.java:874)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:384)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:570)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:564)
        at org.glassfish.deployment.admin.InstanceDeployCommand.execute(InstanceDeployCommand.java:223)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:549)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:545)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:544)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:575)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:567)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:566)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1475)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1857)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1733)
        at org.glassfish.admin.rest.resources.admin.CommandResource.executeCommand(CommandResource.java:409)
        at org.glassfish.admin.rest.resources.admin.CommandResource.execCommandMultInMultOut(CommandResource.java:258)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
```

## Context

I suspect the issue is related to the use of an obsolete version of Icefaces (JSF too) since by removing its dependecies from the EAR package the deployment ends with no error.

According to the documentation (https://docs.payara.fish/documentation/payara-server/classloading.html) I have tried to disable classloading delegation at 3 different levels with no success (WAR, EAR, Global). 
In the past I was able to deploy this application on a Glassfish v3 by disabling classloading policy at WAR level and using useJSFBundle property (I`am not sure if  useJSFBundle property is still available).

## Environment ##

  Payara Server 5.184 #badassfish (build 89)
  JDK 1.8.0_201
  CentOS 7

**Comment by rdebusscher** [comment]
Hi,

I’m unable to reproduce the error you encounter. This is what I have tested

- I created an EAR artifact containing an EJB JAR and WAR
- The EJB JAR contains a Stateless bean
- The WAR contains a JSF page which calls the Stateless EJB.
- Within the WAR, I added MyFaces as JSF (class loader delegating and useBundledJSF)

The application deploys fine and works as expected and MyFaces is used (based on the logging)
 
So, can you create a minimal reproducer which demonstrates this error?

Thx
Rudy

**Comment by smillidge** [comment]
Closing due to inactivity
