### ISSUE TITLE
NoSuchMethodError: sun.security.ssl.SignatureAndHashAlgorithm.getSupportedAlgorithms() when Pinging JDBC MySQL8 Connection Pool on Payara 5.184 with Oracle JDK versions 8, 9 & 11

### ISSUE THREAD

**Issue by EdwardQuixote** [payara/Payara#3719]
# Description #
----------

After creating a Connection Pool with the following attributes:
Resource Type: (either) `javax.sql.DataSource` (or) `javax.sql.XADataSource` (or) `javax.sql.ConnectionPoolDataSource`
Datasource Classname: `com.mysql.cj.jdbc.MysqlDataSource` (based on "MySql8" Database Driver Vendor)
I run into a `java.lang.NoSuchMethodError: sun.security.ssl.SignatureAndHashAlgorithm.getSupportedAlgorithms()` as follows:

`[2019-02-12T09:36:46.026+0300] [Payara 5.184] [SEVERE] [] [org.glassfish.admingui] [tid: _ThreadID=183 _ThreadName=admin-thread-pool::admin-listener(6)] [timeMillis: 1549953406026] [levelValue: 1000] [[
`
`  RestResponse.getResponse() gives FAILURE.  endpoint = http://localhost:4848/management/domain/resources/ping-connection-pool.json; attrs = {id=MyConnectionPool}]]
`
`[2019-02-12T09:37:53.858+0300] [Payara 5.184] [SEVERE] [NCLS-CORE-00003] [javax.enterprise.system.core] [tid: _ThreadID=183 _ThreadName=admin-thread-pool::admin-listener(6)] [timeMillis: 1549953473858] [levelValue: 1000] [[
`
`  Exception while running a command`

`java.lang.NoSuchMethodError: sun.security.ssl.SignatureAndHashAlgorithm.getSupportedAlgorithms(Ljava/security/AlgorithmConstraints;Ljava/util/Collection;)Ljava/util/Collection;`

	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:336)

	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:984)

	at sun.security.ssl.Handshaker.process_record(Handshaker.java:919)

	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1043)

	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343)

	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)

	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)

	at com.mysql.cj.protocol.ExportControlled.performTlsHandshake(ExportControlled.java:315)

	at com.mysql.cj.protocol.StandardSocketFactory.performTlsHandshake(StandardSocketFactory.java:188)

	at com.mysql.cj.protocol.a.NativeSocketConnection.performTlsHandshake(NativeSocketConnection.java:99)

	at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:352)

	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.negotiateSSLConnection(NativeAuthenticationProvider.java:777)

	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:486)

	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202)

	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1449)

	at com.mysql.cj.NativeSession.connect(NativeSession.java:165)

	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:955)

	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)

	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)

	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)

	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)

	at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:402)

	at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:125)

	at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:110)

	at com.sun.gjc.spi.DSManagedConnectionFactory.createManagedConnection(DSManagedConnectionFactory.java:115)

	at com.sun.enterprise.connectors.service.ConnectorConnectionPoolAdminServiceImpl.getUnpooledConnection(ConnectorConnectionPoolAdminServiceImpl.java:618)

	at com.sun.enterprise.connectors.service.ConnectorConnectionPoolAdminServiceImpl.testConnectionPool(ConnectorConnectionPoolAdminServiceImpl.java:430)

	at com.sun.enterprise.connectors.ConnectorRuntime.pingConnectionPool(ConnectorRuntime.java:1162)

	at org.glassfish.connectors.admin.cli.PingConnectionPool.execute(PingConnectionPool.java:143)

	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:549)

	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:545)

	at java.security.AccessController.doPrivileged(Native Method)

	at javax.security.auth.Subject.doAs(Subject.java:360)

	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:544)

	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:575)

	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:567)

	at java.security.AccessController.doPrivileged(Native Method)

	at javax.security.auth.Subject.doAs(Subject.java:360)

	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:566)

	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1475)

	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)

	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1857)

	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1733)

	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:263)

	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:234)

	at org.glassfish.admin.rest.resources.TemplateExecCommand.executeCommandLegacyFormat(TemplateExecCommand.java:159)

	at org.glassfish.admin.rest.resources.TemplateCommandGetResource.processGetLegacyFormat(TemplateCommandGetResource.java:77)

	at sun.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:483)

	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)

	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$$Lambda$181/1808433182.invoke(Unknown Source)

	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)

	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)

	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)

	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)

	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)

	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)

	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)

	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)

	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)

	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)

	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)

	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)

	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)

	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)

	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)

	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:704)

	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:377)

	at org.glassfish.admin.rest.adapter.RestAdapter$2.service(RestAdapter.java:322)

	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:182)

	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)

	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)

	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)

	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)

	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)

	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)

	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)

	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)

	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)

	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)

	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)

	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)

	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)

	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)

	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)

	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)

	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)

	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)

	at java.lang.Thread.run(Thread.java:745)

`]]`

## Expected Outcome

A "Ping Succeeded" notification on the Admin GUI.

## Current Outcome

The following notification is thrown on the Admin GUI:
>  An error has occurred 
java.lang.NoSuchMethodError: sun.security.ssl.SignatureAndHashAlgorithm.getSupportedAlgorithms(Ljava/security/AlgorithmConstraints;Ljava/util/Collection;)Ljava/util/Collection; sun.security.ssl.SignatureAndHashAlgorithm.getSupportedAlgorithms(Ljava/security/AlgorithmConstraints;Ljava/util/Collection;)Ljava/util/Collection;

Server then reports error on the log files as described above.

## Steps to reproduce 

Start your MySQL Server, and create the database you want to use then follow these steps:

1 -**  Start the domain

    ./asadmin start-domain domain1

2 -**  Open Payara Admin GUI via accessing `localhost:4848` and navigate to JDBC Connection Pools via the sidebar.

3 -**  Under the "Pools" table, click on "New..." to create a new Connection Pool.

4 -** Under "General Settings" [STEP 1]; Provide your Pool Name of choice (mine is "MyConnectionPool".

4.1 -** Indicate the "Resource Type" as either `javax.sql.DataSource` (or) `javax.sql.XADataSource` (or) `javax.sql.ConnectionPoolDataSource`

4.2 -** Indicate the "Database Driver Vendor" field as: "MySql8"

4.3 -** Click on "Next" to navigate to the next step [STEP 2] of creating the Connection Pool.

5 -** In Step 2, leave properties under "General Settings", "Pool Settings" and "Transaction" as they are, default.
NOTE: Datasource Classname is set to: `com.mysql.cj.jdbc.MySqlDataSource`

5.1 -** Scroll down to "Additional Properties"

5.2 - ** Edit the value of the property "Password" to your database' password.

5.3 -** Edit the values of the properties "URL" and "Url" to your database' URL.

5.4 -** Edit the value of the property "ServerName" to "localhost"

5.5 -** Edit the value of the property "User" to your database' username (in my case: "root")

6 -** Scroll Down to the bottom and click on "Finish" to save your changes. You'll be re-directed to the list of all your connection pools.

7 -** Click on the connection pool you created.

8 -** Click on "Ping" to test the connection.

9 -** View Server Logs to see the reported error.

## Context

I was trying to create a Connection Pool that I'd use in a Java Web App I'm building.
Please note that my Payara 5.184 and MySQL Server 8.0 Installations are fresh/new/(green?), i.e. I had just installed these two.
Also note that my MySQL J-Connector is copied in both `/{payara5-home}/domains/domain1/lib` and `/{payara5-home}/domains/domain1/lib/ext` directories.

## Environment ##

- **Payara Version**: 5.184
- **Edition**: Full
- **JDK Version**: Oracle JDK 8u25, 8u144, 8u151, 8u202, 9u1, 11u1
- **Operating System**: Windows 10 Home
- **Database**: MySQL 8.0
- **MySQL J-Connector**: mysql-connector-java-8.0.15

**Comment by rdebusscher** [comment]
Hi Edward,

Thank you for the detailed description to reproduce the exception.

However, I'm unable to reproduce it (I'm using slightly different versions Payara 5.184 - JDK 8u181 - MySQL 5.5.x and connector 8.0.12)

But it seems that there is an issue with the JVM itself. You indicate that you also tried it with JDK 9 and 11 which is strange because Payara doesn't even start properly on those versions. And the mentioned method `sun.security.ssl.SignatureAndHashAlgorithm.getSupportedAlgorithms(Ljava/security/AlgorithmConstraints;Ljava/util/Collection;)Ljava/util/Collection;`
is available in my jdk 8u181 version.

So can you have a look on which version the server runs? In the server.log, you should see something similar to
```
[2019-02-13T16:33:28.256+0100] [] [INFO] [NCLS-GFLAUNCHER-00005] [javax.enterprise.launcher] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1550072008256] [levelValue: 800] [[
  JVM invocation command line:
/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/bin/java
-cp
/Users/rubus/java/tools/payara5-184/glassfish/modules/glassfish.jar
```

Tip: instead of copying the MySQL J-Connector, you can also use an asadmin command, then you know it is always correctly placed.

`asadmin add-library /path/to/connector.jar`

**Comment by smillidge** [comment]
Closing due to inactivity.
