### ISSUE TITLE
Payara 5.184: AppClient Cannot find scanner for car

### ISSUE THREAD

**Issue by mkarg** [payara/Payara#3731]
# Description #
----------

AppClient fails to load the actual client but prints "Cannot find scanner for car" and four long stack traces. The application actually works, but possibly might show subsequent problems (not checked).

## Expected Outcome

AppClient starts the actual client without printing a stack trace.

## Current Outcome

```
Feb 14, 2019 5:45:12 PM com.sun.enterprise.deployment.archivist.Archivist getScanner
SEVERE: Cannot find scanner for car
MultiException stack 1 of 4
java.lang.NullPointerException
        at fish.payara.nucleus.executorservice.PayaraExecutorService.initialiseThreadPools(PayaraExecutorService.java:133)
        at fish.payara.nucleus.executorservice.PayaraExecutorService.postConstruct(PayaraExecutorService.java:116)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1287)
        at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:333)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:375)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
        at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83)
        at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71)
        at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154)
        at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199)
        at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:685)
        at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:78)
        at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:212)
        at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:235)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:358)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
        at org.jvnet.hk2.internal.PerLookupContext.findOrCreate(PerLookupContext.java:70)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:777)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:740)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:727)
        at com.sun.enterprise.deployment.archivist.Archivist.getScanner(Archivist.java:539)
        at com.sun.enterprise.deployment.archivist.Archivist.readAnnotations(Archivist.java:459)
        at com.sun.enterprise.deployment.archivist.Archivist.readAnnotations(Archivist.java:445)
        at com.sun.enterprise.deployment.archivist.Archivist.readRestDeploymentDescriptors(Archivist.java:417)
        at com.sun.enterprise.deployment.archivist.Archivist.readDeploymentDescriptors(Archivist.java:394)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:269)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:278)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:239)
        at com.sun.enterprise.deployment.archivist.AppClientArchivist.open(AppClientArchivist.java:114)
        at org.glassfish.appclient.client.acc.FacadeLaunchable.getDescriptor(FacadeLaunchable.java:307)
        at org.glassfish.appclient.client.acc.AppClientContainerBuilder.createContainer(AppClientContainerBuilder.java:190)
        at org.glassfish.appclient.client.acc.AppClientContainerBuilder.newContainer(AppClientContainerBuilder.java:171)
        at org.glassfish.appclient.client.AppClientFacade.createContainerForAppClientArchiveOrDir(AppClientFacade.java:460)
        at org.glassfish.appclient.client.AppClientFacade.createContainer(AppClientFacade.java:419)
        at org.glassfish.appclient.client.AppClientFacade.prepareACC(AppClientFacade.java:274)
        at org.glassfish.appclient.client.acc.agent.AppClientContainerAgent.premain(AppClientContainerAgent.java:83)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
MultiException stack 2 of 4
java.lang.IllegalStateException: Unable to perform operation: post construct on fish.payara.nucleus.executorservice.PayaraExecutorService
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:393)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
        at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83)
        at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71)
        at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154)
        at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199)
        at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:685)
        at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:78)
        at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:212)
        at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:235)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:358)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
        at org.jvnet.hk2.internal.PerLookupContext.findOrCreate(PerLookupContext.java:70)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:777)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:740)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:727)
        at com.sun.enterprise.deployment.archivist.Archivist.getScanner(Archivist.java:539)
        at com.sun.enterprise.deployment.archivist.Archivist.readAnnotations(Archivist.java:459)
        at com.sun.enterprise.deployment.archivist.Archivist.readAnnotations(Archivist.java:445)
        at com.sun.enterprise.deployment.archivist.Archivist.readRestDeploymentDescriptors(Archivist.java:417)
        at com.sun.enterprise.deployment.archivist.Archivist.readDeploymentDescriptors(Archivist.java:394)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:269)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:278)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:239)
        at com.sun.enterprise.deployment.archivist.AppClientArchivist.open(AppClientArchivist.java:114)
        at org.glassfish.appclient.client.acc.FacadeLaunchable.getDescriptor(FacadeLaunchable.java:307)
        at org.glassfish.appclient.client.acc.AppClientContainerBuilder.createContainer(AppClientContainerBuilder.java:190)
        at org.glassfish.appclient.client.acc.AppClientContainerBuilder.newContainer(AppClientContainerBuilder.java:171)
        at org.glassfish.appclient.client.AppClientFacade.createContainerForAppClientArchiveOrDir(AppClientFacade.java:460)
        at org.glassfish.appclient.client.AppClientFacade.createContainer(AppClientFacade.java:419)
        at org.glassfish.appclient.client.AppClientFacade.prepareACC(AppClientFacade.java:274)
        at org.glassfish.appclient.client.acc.agent.AppClientContainerAgent.premain(AppClientContainerAgent.java:83)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
MultiException stack 3 of 4
java.lang.IllegalArgumentException: While attempting to resolve the dependencies of com.sun.enterprise.deployment.annotation.impl.AppClientScanner errors were found
        at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:248)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:358)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
        at org.jvnet.hk2.internal.PerLookupContext.findOrCreate(PerLookupContext.java:70)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:777)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:740)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:727)
        at com.sun.enterprise.deployment.archivist.Archivist.getScanner(Archivist.java:539)
        at com.sun.enterprise.deployment.archivist.Archivist.readAnnotations(Archivist.java:459)
        at com.sun.enterprise.deployment.archivist.Archivist.readAnnotations(Archivist.java:445)
        at com.sun.enterprise.deployment.archivist.Archivist.readRestDeploymentDescriptors(Archivist.java:417)
        at com.sun.enterprise.deployment.archivist.Archivist.readDeploymentDescriptors(Archivist.java:394)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:269)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:278)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:239)
        at com.sun.enterprise.deployment.archivist.AppClientArchivist.open(AppClientArchivist.java:114)
        at org.glassfish.appclient.client.acc.FacadeLaunchable.getDescriptor(FacadeLaunchable.java:307)
        at org.glassfish.appclient.client.acc.AppClientContainerBuilder.createContainer(AppClientContainerBuilder.java:190)
        at org.glassfish.appclient.client.acc.AppClientContainerBuilder.newContainer(AppClientContainerBuilder.java:171)
        at org.glassfish.appclient.client.AppClientFacade.createContainerForAppClientArchiveOrDir(AppClientFacade.java:460)
        at org.glassfish.appclient.client.AppClientFacade.createContainer(AppClientFacade.java:419)
        at org.glassfish.appclient.client.AppClientFacade.prepareACC(AppClientFacade.java:274)
        at org.glassfish.appclient.client.acc.agent.AppClientContainerAgent.premain(AppClientContainerAgent.java:83)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
MultiException stack 4 of 4
java.lang.IllegalStateException: Unable to perform operation: resolve on com.sun.enterprise.deployment.annotation.impl.AppClientScanner
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:387)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
        at org.jvnet.hk2.internal.PerLookupContext.findOrCreate(PerLookupContext.java:70)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:777)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:740)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:727)
        at com.sun.enterprise.deployment.archivist.Archivist.getScanner(Archivist.java:539)
        at com.sun.enterprise.deployment.archivist.Archivist.readAnnotations(Archivist.java:459)
        at com.sun.enterprise.deployment.archivist.Archivist.readAnnotations(Archivist.java:445)
        at com.sun.enterprise.deployment.archivist.Archivist.readRestDeploymentDescriptors(Archivist.java:417)
        at com.sun.enterprise.deployment.archivist.Archivist.readDeploymentDescriptors(Archivist.java:394)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:269)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:278)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:239)
        at com.sun.enterprise.deployment.archivist.AppClientArchivist.open(AppClientArchivist.java:114)
        at org.glassfish.appclient.client.acc.FacadeLaunchable.getDescriptor(FacadeLaunchable.java:307)
        at org.glassfish.appclient.client.acc.AppClientContainerBuilder.createContainer(AppClientContainerBuilder.java:190)
        at org.glassfish.appclient.client.acc.AppClientContainerBuilder.newContainer(AppClientContainerBuilder.java:171)
        at org.glassfish.appclient.client.AppClientFacade.createContainerForAppClientArchiveOrDir(AppClientFacade.java:460)
        at org.glassfish.appclient.client.AppClientFacade.createContainer(AppClientFacade.java:419)
        at org.glassfish.appclient.client.AppClientFacade.prepareACC(AppClientFacade.java:274)
        at org.glassfish.appclient.client.acc.agent.AppClientContainerAgent.premain(AppClientContainerAgent.java:83)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
```

## Steps to reproduce (Only for bug reports) 

* Deploy EAR containing CAR containing Hello World using `asadmin deploy --retrieve . ear-1.ear`
* `appclient -client ear-1Client.jar`

### Samples

https://github.com/mkarg/payara-bug-ear/tree/payara-bug-appclient

## Environment ##

- **Payara Version**: 5.184
- **Edition**: Full
- **JDK Version**: Azul Zulu 1.8.0_181-b02
- **Operating System**: Windows
- **Database**: N/A

**Comment by rdebusscher** [comment]
Hi Markus,

Thank you for the description and the reproducer.

But the 'Application Container Client' feature is not a priority for the moment so we put this issue on hold.

Regards
Rudy

**Comment by mkarg** [comment]
Can you at least point me in the right direction so I can debug it on my own? We cannot migrate our customers from Payara 4 to 5 due to this issue.

**Comment by smillidge** [comment]
Looks like PayaraExecutorService is failing to initialise in the ACC as it can't find its configuration here https://github.com/payara/Payara/blob/bc93c5e8948d3cb4a94c321a407d2589cf9cf074/nucleus/payara-modules/payara-executor-service/src/main/java/fish/payara/nucleus/executorservice/PayaraExecutorService.java#L133 

Looks like it should use a default if it can't inject the config or create a default one (which it does try to do).

**Comment by OndroMih** [comment]
Hi @mkarg, do you still face this issue?

**Comment by mkarg** [comment]
Had no time to work on this in the last year, unfortunately. Isn't it still reproducible using the above example?

**Comment by OndroMih** [comment]
I tested this with Payara Server 5.201 and I see the expected behavior. The EAR deploys successfully and running the app client results in the following output with no exceptions:

```
Mar 03, 2020 12:30:51 PM org.glassfish.enterprise.iiop.api.GlassFishORBHelper postConstruct
INFO: GlassFishORBFactory service initialized.
Hello!
```

I consider this as solved. If you still find any issues in the recent Payara Server version, feel free to reopen.
