### ISSUE TITLE
Exception on deploy of Fighterfish HTTP HelloWorld Sample

### ISSUE THREAD

**Issue by dhubbard-ag** [payara/Payara#3755]
# Description #
----------

I am trying to run [fighterfish osgihttp example](https://github.com/eclipse-ee4j/glassfish-fighterfish/tree/master/sample/osgihttp/helloworld) in Payara 5.184 without success 

## Expected Outcome

It should activate and load correctly and make /hello1, /hello2 and /hello.html available for web access 

## Current Outcome

When deploying the built jar file via asadmin command line to a new domain the following exception

```
[2019-02-20T03:06:51.282+0000] [Payara 5.184] [SEVERE] [] [] [tid: _ThreadID=46 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1550632011282] [levelValue: 1000] [[
  java.lang.NullPointerException
        at com.sun.web.security.RealmAdapter.setVirtualServer(RealmAdapter.java:525)
        at com.sun.enterprise.web.WebModule.setParent(WebModule.java:799)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:953)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:939)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:684)
        at org.glassfish.osgihttp.Activator.createRootWebModule(Activator.java:185)
        at org.glassfish.osgihttp.Activator.doActualWork(Activator.java:124)
        at org.glassfish.osgihttp.Activator.access$300(Activator.java:84)
        at org.glassfish.osgihttp.Activator$OSGiHtttpExtender.start(Activator.java:332)
        at org.glassfish.osgijavaeebase.ExtenderManager$ExtenderTracker.addingService(ExtenderManager.java:144)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
        at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)
        at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
        at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
        at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
        at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4595)
        at org.apache.felix.framework.Felix.registerService(Felix.java:3587)
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348)
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:322)
        at org.glassfish.osgihttp.Activator.start(Activator.java:105)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2224)
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1607)
        at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.apache.felix.framework.BundleWiringImpl.getClassByDelegation(BundleWiringImpl.java:1414)
        at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1660)
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1590)
        at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.glassfish.fighterfish.sample.osgihttp.helloworld.HelloWorldHttpActivator.start(HelloWorldHttpActivator.java:39)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)

```
... deleted serveral lines

```
org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.lang.Thread.run(Thread.java:748)
]]
```

The line 

`        at org.glassfish.fighterfish.sample.osgihttp.helloworld.HelloWorldHttpActivator.start(HelloWorldHttpActivator.java:39)`

is 

`	tracker = new ServiceTracker(context, HttpService.class.getName(), null) {`

## Steps to reproduce (Only for bug reports) 

1 -**  Create a new domain

`    ./asadmin create-domain --portbase 16000 osgi-sample`

2 -**  Deploy OSGI bundle via command line

`   ./asadmin --port 16048 deploy --type osgi --force /usr/local/gfdeploy/sample.osgihttp.helloworld.jar`

   the exception (above) should be seen in console

3 -**  If the domain is restarted a different exception is seen in the logs - this does not reference the sample code, but base functionality.

```
[2019-02-20T03:14:12.611+0000] [Payara 5.184] [SEVERE] [] [] [tid: _ThreadID=13 _ThreadName=FelixStartLevel] [timeMillis: 1550632452611] [levelValue: 1000] [[
  java.lang.NullPointerException
        at com.sun.web.security.RealmAdapter.setVirtualServer(RealmAdapter.java:525)
        at com.sun.enterprise.web.WebModule.setParent(WebModule.java:799)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:953)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:939)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:684)
        at org.glassfish.osgihttp.Activator.createRootWebModule(Activator.java:185)
        at org.glassfish.osgihttp.Activator.doActualWork(Activator.java:124)
        at org.glassfish.osgihttp.Activator.access$300(Activator.java:84)
        at org.glassfish.osgihttp.Activator$OSGiHtttpExtender.start(Activator.java:332)
        at org.glassfish.osgijavaeebase.ExtenderManager$ExtenderTracker.addingService(ExtenderManager.java:144)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
        at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)
        at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
        at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
        at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
        at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4595)
        at org.apache.felix.framework.Felix.registerService(Felix.java:3587)
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348)
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:322)
        at org.glassfish.osgihttp.Activator.start(Activator.java:105)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:748)
```

### Samples

[https://github.com/eclipse-ee4j/glassfish-fighterfish/tree/master/sample/osgihttp/helloworld](https://github.com/eclipse-ee4j/glassfish-fighterfish/tree/master/sample/osgihttp/helloworld)

## Context (Optional)

I am trying to get an OSGI HTTP service running in Payara 5.184.  I also tried eclipse-osgi-http example also without success ([different issue here](https://github.com/eclipse-ee4j/jersey/issues/4066) ).  My guess is that i should be using fighterfish rather than org.osgi.service.http directly - based on there being only fighterfish osgi-http 

```
[dhubbard@sp ~]$ /usr/lib/glassfish/bin/asadmin --port 16048 list-modules | grep http                                       OSGiModuleImpl:: Bundle = [org.glassfish.fighterfish.sample.osgihttp.helloworld [408]], State = [READY]
OSGiModuleImpl:: Bundle = [org.glassfish.fighterfish.osgi-http [397]], State = [READY]
OSGiModuleImpl:: Bundle = [org.glassfish.jersey.containers.jersey-container-grizzly2-http [216]], State = [RESOLVED]

```

## Environment ##

- **Payara Version**: 5.184
- **Edition**: Full
- **JDK Version**: 8 Oracle 
- **Operating System**: Linux

**Comment by smillidge** [comment]
We don't have any customer demand to support fighter fish

**Comment by dhubbard-ag** [comment]
Ah ok - my misunderstanding - I thought, from the packaging and that it comes pre-loaded, that fighterfish was part of glassfish/payara.  I will raise the question on the fighterfish site.

**Comment by dhubbard-ag** [comment]
Can I ask a related question - osgi - how do I find out the osgi bundles that payara includes?

If I run asadmin>  list-modules I get (a snippet)

```
OSGiModuleImpl:: Bundle = [fish.payara.admingui.hipchat-notifier-console-plugin [114]], State = [NEW]
OSGiModuleImpl:: Bundle = [org.glassfish.jersey.ext.jersey-proxy-client [281]], State = [NEW]
```

With (I assume) the number being the BundleId but no version number

asadmin > list-modules --help indicates that the output should contain a version number.

  ```
     The list-modules subcommand displays a list of modules that are
       accessible to the GlassFish Server module subsystem. **The version of
       each module is shown.**
```

... plus example 

>             Module : org.glassfish.transaction.jts:3.0.0.b66
>                    Module Characteristics : List of Jars implementing the module
>                        Jar : file:/home/gfuser/GlassFish/glassfishv3/glassfish/modules/jts.jar
>                    Module Characteristics : Provides to following services
>                    Module Characteristics : List of imported modules
>                        Imports : org.glassfish.transaction.jts:3.0.0.b66
> 

I will raise as a seperate question if you think that is appropriate

**Comment by fturizo** [comment]
Closing this issue as questions should be addressed on the [official Payara Forum](https://groups.google.com/forum/#!forum/payara-forum). Please raise your question there as a new topic to engage in further discussion.
