### ISSUE TITLE
javax.ejb.AccessLocalException: Client not authorized for this invocation

### ISSUE THREAD

**Issue by alexvinok** [payara/Payara#3816]
# Description #
----------
Getting error trying to invoke create on the Local home interface (extends EJBLocalHome). Before this I see the following message:

[2019-03-05T15:55:20.466-0500] [Payara 5.184] [INFO] [] [javax.enterprise.system.core.security] [tid: _ThreadID=249 _ThreadName=RunLevelControllerThread-1551819320389] [timeMillis: 1551819320466] [levelValue: 800] [[
  JACC Policy Provider: Failed Permission Check, context(........._jar)- permission(("javax.security.jacc.EJBMethodPermission" ".........Bean" "create,LocalHome,"))]]

[2019-03-05T15:55:20.466-0500] [Payara 5.184] [SEVERE] [] [] [tid: _ThreadID=249 _ThreadName=RunLevelControllerThread-1551819320389] [timeMillis: 1551819320466] [levelValue: 1000] [[
  javax.ejb.AccessLocalException: Client not authorized for this invocation
	at com.sun.ejb.containers.BaseContainer.authorizeLocalMethod(BaseContainer.java:2219)
	at com.sun.ejb.containers.StatelessSessionContainer.createEJBLocalObjectImpl(StatelessSessionContainer.java:335)
	at com.sun.ejb.containers.EJBLocalHomeImpl.createEJBLocalObjectImpl(EJBLocalHomeImpl.java:106)
	at com.sun.ejb.containers.EJBLocalHomeInvocationHandler.invoke(EJBLocalHomeInvocationHandler.java:184)
	at com.sun.proxy.$Proxy426.create(Unknown Source)

## Environment ##

- **Payara Version**:  5.184
- **Edition**: 
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

- **Operating System**: 
- **Database**:

**Comment by alexvinok** [comment]
Actually resolved by updating server.policy with adding 

rant codeBase "file:/appname/-" {
    permission java.security.AllPermission;
};
grant codeBase "file:${com.sun.aas.instanceRoot}/startupjarname/-" {
    permission java.security.AllPermission;
};
