### ISSUE TITLE
gf-client.jar dependencies changed in 5.191 so  that EJB client stopped working 

### ISSUE THREAD

**Issue by alexvinok** [payara/Payara#3829]
# Description #
----------

In 5.184  it was enough to have  gf-client.jar  on the classpath to have our standalone EJB client working with dependencies jar being referenced in its manifest with upgrade to 5.191 the our client stopped working as it is clear that there were changes done to gf-client.jar\META-INF\MANIFEST.MF 

here is the list of the missing dependencies
Caused by: java.lang.ClassNotFoundException: javax.ejb.EJBObject
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

Caused by: java.lang.ClassNotFoundException: com.sun.enterprise.security.ee.auth.login.ProgrammaticLogin
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

## Environment ##

- **Payara Version**: 5.191 
- **Edition**: 
- **JDK Version**: java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
- **Operating System**: 
- **Database**:

**Comment by smillidge** [comment]
Fixed by #3846
