### ISSUE TITLE
Activating OpenIdAuthenticationDefinition fails with "Unsatisfied dependencies for type OAuth2State"

### ISSUE THREAD

**Issue by parysto** [payara/Payara#3862]
# Description #
----------

When "@OpenIdAuthenticationDefinition" is added to activate the OpenID Connect security mechanism (like described here: https://blog.payara.fish/openid-connect-in-the-payara-platform-5.183), deployment fails with "Unsatisfied dependencies for type OAuth2State".

## Expected Outcome

App successfully deployed and OpenID connect activated.

## Current Outcome

Deployment failure:

    INFORMATION:   Activating fish.payara.security.openid.OpenIdIdentityStore identity store from parysto.example.Configuration class
    INFORMATION:   Activating fish.payara.security.openid.OpenIdAuthenticationMechanism authentication mechanism from parysto.example.Configuration class
    SCHWERWIEGEND:   Exception during lifecycle processing
    org.glassfish.deployment.common.DeploymentException: CDI deployment failure:WELD-001408: Unsatisfied dependencies for type OAuth2State with qualifiers @Default
    at injection point [UnbackedAnnotatedField] @Inject private fish.payara.security.oauth2.OAuth2AuthenticationMechanism.state
    at fish.payara.security.oauth2.OAuth2AuthenticationMechanism.state(OAuth2AuthenticationMechanism.java:0)
    -- WELD-001408: Unsatisfied dependencies for type OAuth2State with qualifiers @Default
    at injection point [UnbackedAnnotatedField] @Inject private fish.payara.security.oauth2.OAuth2AuthenticationMechanism.state
    at fish.payara.security.oauth2.OAuth2AuthenticationMechanism.state(OAuth2AuthenticationMechanism.java:0)
        at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:378)
        at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:290)
        at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:143)
        at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:164)
        at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:526)
        at org.jboss.weld.bootstrap.Validator.validateBeans(Validator.java:512)
        at org.jboss.weld.bootstrap.Validator.validateDeployment(Validator.java:487)
        at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:496)
        at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:93)
        at org.glassfish.weld.WeldDeployer.processApplicationLoaded(WeldDeployer.java:517)
        at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:428)
        at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
        at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:333)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:485)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:540)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:557)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:553)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:552)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:583)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:575)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:574)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1483)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:119)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1865)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1741)
        at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:564)
        at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:251)
        at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:166)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$0(WorkerThreadIOStrategy.java:90)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.lang.Thread.run(Thread.java:748)

    SCHWERWIEGEND:   Exception while loading the app
    SCHWERWIEGEND:   Undeployment failed for context /security

## Steps to reproduce (Only for bug reports) 

Try to use OpenID connect with annotation:

    @ApplicationScoped

    @OpenIdAuthenticationDefinition(
            providerURI = "http://http://localhost:18080",
            clientId = "clientid",
            clientSecret = "b1d551d9-483e-4b8b-b0e4-15e9296313f0",
            redirectURI = "http://localhost:8080/myapp/Callback"
    )

    // REST
    @ApplicationPath("api")
    public class Configuration extends Application {

    }

## Environment ##

- **Payara Version**: 5.184 and 5.191 
- **Edition**: Full 
- **JDK Version**: jdk-8u201-linux-x64, OpenJDK 8
- **Operating System**: Linux (Ubuntu 18.10) 
- **Database**: None

**Comment by parysto** [comment]
Issue cause by missing scope "provided" in dependency.
(I copied that from the blog post without noticing the missing scope element)

**Comment by kamlendu** [comment]
so.. what is the solution
