### ISSUE TITLE
Deployment failure with CDI related exception: Unable to invoke void fish.payara.micro.cdi.extension.ClusteredCDIEventBusImpl.postConstruct()

### ISSUE THREAD

**Issue by derari** [payara/Payara#3865]
# Description #
----------

When I try to deploy an Apache Camel example project ([this one](https://github.com/apache/camel/tree/master/examples/camel-example-cdi-rest-servlet)), it fails. An error message is logged, but no error is shown in the Admin interface.

I have found this related issue (https://github.com/payara/Payara/issues/2535), but the solution does not apply in my case (my config is correct).

## Expected Outcome

* Expected successful deployment of war
* Expected an error message in the Admin interface

## Current Outcome

```
org.glassfish.deployment.common.DeploymentException: CDI deployment failure:
WELD-000049: Unable to invoke void fish.payara.micro.cdi.extension.ClusteredCDIEventBusImpl.postConstruct() on fish.payara.micro.cdi.extension.ClusteredCDIEventBusImpl@3e3a8d12 -- 
WELD-000049: Unable to invoke void fish.payara.micro.cdi.extension.ClusteredCDIEventBusImpl.postConstruct() on fish.payara.micro.cdi.extension.ClusteredCDIEventBusImpl@3e3a8d12
        at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:85)
        at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.postConstruct(DefaultLifecycleCallbackInvoker.java:66)
        at org.jboss.weld.injection.producer.BasicInjectionTarget.postConstruct(BasicInjectionTarget.java:122)
        at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:172)
        at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:96)
        at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
        at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:140)
        at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:67)
        at org.jboss.weld.event.ObserverMethodImpl.getReceiver(ObserverMethodImpl.java:360)
        at org.jboss.weld.event.ObserverMethodImpl.getReceiverIfExists(ObserverMethodImpl.java:347)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:305)
        at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
        at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
        at org.jboss.weld.util.Observers.notify(Observers.java:166)
        at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
        at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
        at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
        at org.jboss.weld.bootstrap.BeanDeploymentModule.fireEvent(BeanDeploymentModule.java:93)
        at org.jboss.weld.bootstrap.WeldStartup.endInitialization(WeldStartup.java:570)
        at org.jboss.weld.bootstrap.WeldBootstrap.endInitialization(WeldBootstrap.java:100)
        at org.glassfish.weld.WeldDeployer.processApplicationLoaded(WeldDeployer.java:518)
        at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:428)
        at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
        at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:333)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:497)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:540)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:549)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:545)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:544)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:575)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:567)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:566)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1475)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1857)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1733)
        at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:263)
        at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:234)
        at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:285)
        at org.glassfish.admin.rest.resources.TemplateListOfResource.createResource(TemplateListOfResource.java:136)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:704)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:377)
        at org.glassfish.admin.rest.adapter.RestAdapter$2.service(RestAdapter.java:322)
        at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:182)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:208)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:208)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.lang.Thread.run(Thread.java:748)
|#]
```

## Steps to reproduce (Only for bug reports) 

1) Build this example project: https://github.com/apache/camel/tree/master/examples/camel-example-cdi-rest-servlet
2) Deploy the war file in Payara

## Environment ##

- **Payara Version**: 5.191
- **Edition**: Full
- **JDK Version**: 8 OpenJDK
- **Operating System**: Alpine Linux (docker)

**Comment by svendiedrichsen** [comment]
@derari Are there any more exceptions in the log? Especially any exceptions thrown from the postConstruct Method?

**Comment by derari** [comment]
@svendiedrichsen 
No, no additional exceptions. This is the full output from `server.log`.

```
[2019-03-27T07:28:05.178+0000] [Payara 5.191] [INFO] [] [org.glassfish.admingui] [tid: _ThreadID=199 _ThreadName=admin-thread-pool::admin-listener(6)] [timeMillis: 1553671685178] [levelValue: 800] [[
  GUI deployment: uploadToTempfile]]

[2019-03-27T07:28:05.178+0000] [Payara 5.191] [INFO] [] [org.glassfish.admingui] [tid: _ThreadID=199 _ThreadName=admin-thread-pool::admin-listener(6)] [timeMillis: 1553671685178] [levelValue: 800] [[
  uploadFileName=camel-example-cdi-rest-servlet-3.0.0-SNAPSHOT.war]]

[2019-03-27T07:28:05.186+0000] [Payara 5.191] [INFO] [] [] [tid: _ThreadID=199 _ThreadName=admin-thread-pool::admin-listener(6)] [timeMillis: 1553671685186] [levelValue: 800] [[
  ================== availabilityEnabled  skipped ]]

[2019-03-27T07:28:10.997+0000] [Payara 5.191] [INFO] [] [javax.enterprise.system.tools.deployment.common] [tid: _ThreadID=44 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1553671690997] [levelValue: 800] [[
  visiting unvisited references]]

[2019-03-27T07:28:12.838+0000] [Payara 5.191] [WARNING] [] [org.glassfish.weld.BeanDeploymentArchiveImpl] [tid: _ThreadID=44 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1553671692838] [levelValue: 900] [[
  AS-CDI-00005]]

[2019-03-27T07:28:12.859+0000] [Payara 5.191] [WARNING] [] [org.glassfish.weld.BeanDeploymentArchiveImpl] [tid: _ThreadID=44 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1553671692859] [levelValue: 900] [[
  AS-CDI-00005]]

[2019-03-27T07:28:12.883+0000] [Payara 5.191] [WARNING] [] [org.glassfish.weld.BeanDeploymentArchiveImpl] [tid: _ThreadID=44 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1553671692883] [levelValue: 900] [[
  AS-CDI-00005]]

[2019-03-27T07:28:12.904+0000] [Payara 5.191] [WARNING] [] [org.glassfish.weld.BeanDeploymentArchiveImpl] [tid: _ThreadID=44 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1553671692904] [levelValue: 900] [[
  AS-CDI-00005]]

[2019-03-27T07:28:12.910+0000] [Payara 5.191] [WARNING] [] [org.glassfish.weld.BeanDeploymentArchiveImpl] [tid: _ThreadID=44 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1553671692910] [levelValue: 900] [[
  AS-CDI-00005]]

[2019-03-27T07:28:12.920+0000] [Payara 5.191] [WARNING] [] [org.glassfish.weld.BeanDeploymentArchiveImpl] [tid: _ThreadID=44 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1553671692920] [levelValue: 900] [[
  AS-CDI-00005]]

[2019-03-27T07:28:15.015+0000] [Payara 5.191] [INFO] [] [org.jboss.weld.Event] [tid: _ThreadID=44 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1553671695015] [levelValue: 800] [[
  WELD-000411: Observer method [BackedAnnotatedMethod] private org.apache.camel.cdi.CdiCamelExtension.processAnnotatedType(@Observes ProcessAnnotatedType<?>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.]]

[2019-03-27T07:28:15.400+0000] [Payara 5.191] [WARN] [] [org.jboss.weld.Bootstrap] [tid: _ThreadID=44 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1553671695400] [levelValue: 900] [[
  WELD-001101: Member of array type or annotation type must be annotated @NonBinding:  [EnhancedAnnotatedMethodImpl] public abstract javax.enterprise.inject.Typed.value()]]

[2019-03-27T07:28:16.865+0000] [Payara 5.191] [SEVERE] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=44 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1553671696865] [levelValue: 1000] [[
  Exception during lifecycle processing
org.glassfish.deployment.common.DeploymentException: CDI deployment failure:WELD-000049: Unable to invoke void fish.payara.micro.cdi.extension.ClusteredCDIEventBusImpl.postConstruct() on fish.payara.micro.cdi.extension.ClusteredCDIEventBusImpl@4dc1570b -- WELD-000049: Unable to invoke void fish.payara.micro.cdi.extension.ClusteredCDIEventBusImpl.postConstruct() on fish.payara.micro.cdi.extension.ClusteredCDIEventBusImpl@4dc1570b
	at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:85)
	at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.postConstruct(DefaultLifecycleCallbackInvoker.java:66)
	at org.jboss.weld.injection.producer.BasicInjectionTarget.postConstruct(BasicInjectionTarget.java:122)
	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:172)
	at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:96)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
	at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:140)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:67)
        <stacktrace as above>
]]

[2019-03-27T07:28:16.866+0000] [Payara 5.191] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=44 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1553671696866] [levelValue: 1000] [[
  Exception while loading the app]]

[2019-03-27T07:28:16.866+0000] [Payara 5.191] [SEVERE] [AS-WEB-GLUE-00192] [javax.enterprise.web] [tid: _ThreadID=44 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1553671696866] [levelValue: 1000] [[
  Undeployment failed for context /camel]]

[2019-03-27T07:28:16.868+0000] [Payara 5.191] [SEVERE] [] [javax.enterprise.web.util] [tid: _ThreadID=44 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1553671696868] [levelValue: 1000] [[
  The web application [unknown] created a ThreadLocal with key of type [org.apache.camel.impl.AbstractCamelContext$1] (value [org.apache.camel.impl.AbstractCamelContext$1@13978ace]) and a value of type [java.util.HashSet] (value [[]]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.]]

[2019-03-27T07:28:19.702+0000] [Payara 5.191] [INFO] [] [org.glassfish.admingui] [tid: _ThreadID=199 _ThreadName=admin-thread-pool::admin-listener(6)] [timeMillis: 1553671699702] [levelValue: 800] [[
  Exception Occurred :Error occurred during deployment: Exception while loading the app. Please see server.log for more details.]]
```

**Comment by svendiedrichsen** [comment]
To me this looks like classloading problem. The app you are deploying comes with a lot of JEE dependencies. These might conflict with the already provided ones from the Payara server. You might want to try to tinker with the classloading of the Payara server. 

This might help: https://docs.payara.fish/v/172/documentation/extended-documentation/classloading.html

If it doesn't then the app might not supposed to be run in an JEE server. Considering all the dependencies. Maybe it is supposed to be run in a servlet engine. i.e. Jetty, Tomcat and such

**Comment by smillidge** [comment]
We need a more slim down test case that demonstrates the issue the camel example is too big and is running it's own server and including a CDI engine.

**Comment by derari** [comment]
It was indeed a classloading issue that I was able to fix now by changing some dependencies. This closes this issue for me, although I still think an error message should have been shown in the admin GUI.

**Comment by smillidge** [comment]
Thanks for letting us know it's not a Payara issue
