### ISSUE TITLE
Deploy exception (NullPointerException)

### ISSUE THREAD

**Issue by peterpz1** [payara/Payara#3939]
# Description #
----------

Sometimes deployment fails with NPE in JPA sniffer. Just doing another deployment again results in proper deployment. Problem is random, I don't know when it will fail. The error is occurring both when deploying from GUI or automatically using asadmin commands. What might be important, application does not have any JPA beans, and sniffer is failing at that point.

## Expected Outcome

100% successful deployments.

## Current Outcome

About 5-10% deployment fail ratio (when application is compiled properly).

## Steps to reproduce (Only for bug reports) 

Just do a lot of deployments and the problem will occur. My config is one DAS with 2 instances in deployment group.

### Samples

Log:
```
[2019-05-10T14:48:09.213+0200] [Payara 5.191] [SEVERE] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=193 _ThreadName=admin-thread-pool::admin-listener(4)] [timeMillis: 1557492489213] [levelValue: 1000] [[
  Exception during lifecycle processing
java.lang.NullPointerException
	at org.glassfish.persistence.jpaconnector.JPASniffer.isEntryPresent(JPASniffer.java:137)
	at org.glassfish.persistence.jpaconnector.JPASniffer.scanForPURootsInLibDir(JPASniffer.java:123)
	at org.glassfish.persistence.jpaconnector.JPASniffer.handles(JPASniffer.java:103)
	at org.glassfish.internal.deployment.GenericSniffer.handles(GenericSniffer.java:109)
	at com.sun.enterprise.v3.server.SnifferManagerImpl.getSniffers(SnifferManagerImpl.java:145)
	at com.sun.enterprise.v3.server.SnifferManagerImpl.getSniffers(SnifferManagerImpl.java:132)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.getSniffers(ApplicationLifecycle.java:693)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:355)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:540)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:557)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:553)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:552)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:583)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:575)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:574)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1483)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:119)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1865)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1741)
	at org.glassfish.admin.rest.resources.admin.CommandResource.executeCommand(CommandResource.java:409)
	at org.glassfish.admin.rest.resources.admin.CommandResource.execCommandMultInMultOut(CommandResource.java:258)
	at sun.reflect.GeneratedMethodAccessor267.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:704)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:377)
	at org.glassfish.admin.rest.adapter.JerseyContainerCommandService$3.service(JerseyContainerCommandService.java:179)
	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:192)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:208)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:208)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$0(WorkerThreadIOStrategy.java:90)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
]]
```

## Environment ##

- **Payara Version**: 5.191
- **Edition**: Full
- **JDK Version**: zulu8.38.0.13-ca-jre8.0.212-linux_x64
- **Operating System**: Linux
- **Database**: MySQL (but this has nothing to do with that)
- **Config**: Single DAS having 2 instances in deployment group (app is deployed to that deployment group)

**Comment by svendiedrichsen** [comment]
@peterpz1 I have created a PR #3940 to fix the sporadic NPE. Would you mind testing this fix?

**Comment by peterpz1** [comment]
@svendiedrichsen yes, of course I will be pleased to test the fix

**Comment by svendiedrichsen** [comment]
@peterpz1 Did you find any time to look into this?

**Comment by peterpz1** [comment]
@svendiedrichsen can you please tell me how I can do that? Excuse me but I'm new to that. From where can I get compiled payara version with this fix? Are there any nightly builds available or something like that?

**Comment by svendiedrichsen** [comment]
@peterpz1 No, there aren't any nightly builds from PRs. You would have to clone my repo of the Payara project switch to the PR branch and build the Payara server from it. Then you can use this server to test the fix.

**Comment by peterpz1** [comment]
Ok, I've build this version and it seems to be running (it doesnt display its number):
`2019-05-15 09:58:36 INFO   [com.sun.enterprise.server.logging.LogManagerService postConstruct] Running Payara Version: Payara Server  5 #badassfish (build ${build.number})`

Now I need at least 1 week to say anything, because as reported it was sporadic issue, so we need a lot of redeployments to confirm the fix.

**Comment by svendiedrichsen** [comment]
@peterpz1 Thank you for your effort.

**Comment by svendiedrichsen** [comment]
@peterpz1 The PR has been merged already. From tomorrow on you can use a nightly build to test.

**Comment by peterpz1** [comment]
@svendiedrichsen where are available nightly builds? I'm still testing my build from your branch and up to now no issues with deployment :)

**Comment by svendiedrichsen** [comment]
@peterpz1 Nightly builds are to be found here https://www.payara.fish/software/downloads/pre-release-builds/

**Comment by peterpz1** [comment]
@svendiedrichsen I was testing your fix for a lot of time and no issues. Exception never appeared. On the other hand other our environments running 191 version are constantly having this issue so I mark this issue as resolved for me. Thank you very much.

**Comment by fiermacc** [comment]
I have a similar problem, but this problem shows up when I start the server and then I want to see the applications. Then I just migrated a glassfish server to a payara and it gives me this error: Java.null.pointerException
