### ISSUE TITLE
IllegalArgumentException when starting a payara micro on Windows via cli with --rootDir or --domainConfig

### ISSUE THREAD

**Issue by bseiller** [payara/Payara#395]
starting a micro instance under Windows like this
    `java -jar payara-micro-4.1.153.jar --rootDir c:\path\`
    `java -jar payara-micro-4.1.153.jar --domainConfig c:\path\domain.xml`
results in the following error:
```
Exception in thread "main" fish.payara.micro.BootstrapException: java.lang.IllegalArgumentException: Illegal character in authority at index 7: file://c:\path\domain.xml
                at fish.payara.micro.PayaraMicro.bootStrap(PayaraMicro.java:712)
                at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:105)
Caused by: org.glassfish.embeddable.GlassFishException: java.lang.IllegalArgumentException: Illegal character in authority at index 7: file://c:\path\domain.xml
                at com.sun.enterprise.glassfish.bootstrap.StaticGlassFishRuntime.newGlassFish(StaticGlassFishRuntime.java:139)
                at fish.payara.micro.PayaraMicro.bootStrap(PayaraMicro.java:692)
                ... 1 more
Caused by: java.lang.IllegalArgumentException: Illegal character in authority at index 7: file://c:\path\domain.xml
                at java.net.URI.create(Unknown Source)
                at org.glassfish.kernel.embedded.EmbeddedDomainXml.getDomainXml(EmbeddedDomainXml.java:73)
                at org.glassfish.kernel.embedded.EmbeddedDomainXml.getDomainXml(EmbeddedDomainXml.java:66)
                at org.glassfish.config.support.DomainXml.run(DomainXml.java:117)
                at org.jvnet.hk2.config.ConfigurationPopulator.populateConfig(ConfigurationPopulator.java:58)
                at org.glassfish.hk2.bootstrap.HK2Populator.populateConfig(HK2Populator.java:106)
                at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.populateConfig(AbstractModulesRegistryImpl.java:211)
                at com.sun.enterprise.module.bootstrap.Main.createServiceLocator(Main.java:273)
                at com.sun.enterprise.glassfish.bootstrap.StaticGlassFishRuntime.newGlassFish(StaticGlassFishRuntime.java:112)
                ... 2 more
Caused by: java.net.URISyntaxException: Illegal character in authority at index 7: file://c:\path\domain.xml
                at java.net.URI$Parser.fail(Unknown Source)
                at java.net.URI$Parser.parseAuthority(Unknown Source)
                at java.net.URI$Parser.parseHierarchical(Unknown Source)
                at java.net.URI$Parser.parse(Unknown Source)
                at java.net.URI.<init>(Unknown Source)
                ... 11 more
```
The reason seems to be, that the results of getAbsolutePath calls in the method PayaraMicro.bootStrap that are passed down as parameter via "setConfigFileURI" are not valid URIs and should be escaped/transformed if OS == Windows.

**Comment by bseiller** [comment]
Cool - thanks a lot!
