### ISSUE TITLE
java.lang.NoClassDefFoundError: org/glassfish/grizzly/npn/AlpnServerNegotiator at Linux and Corretto

### ISSUE THREAD

**Issue by diegosilval** [payara/Payara#3967]
# Description #
----------
from Ubuntu Linux 

java -version

`openjdk version "1.8.0_202"
OpenJDK Runtime Environment Corretto-8.202.08.2 (build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM Corretto-8.202.08.2 (build 25.202-b08, mixed mode)
`
Log shows:
`
Launching Payara Server on Felix platform
may 21, 2019 5:46:09 PM com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner createBundleProvisioner
INFORMACIÓN: Create bundle provisioner class = class com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner.
Registered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishRuntime@7e4b683d in service registry.
#!## LogManagerService.postConstruct : rootFolder=/home/diego/payara5/glassfish
#!## LogManagerService.postConstruct : templateDir=/home/diego/payara5/glassfish/lib/templates
#!## LogManagerService.postConstruct : src=/home/diego/payara5/glassfish/lib/templates/logging.properties
#!## LogManagerService.postConstruct : dest=/home/diego/payara5/glassfish/domains/production/config/logging.properties
INFORMACIÓN:   Running Payara Version: Payara Server  5.191 #badassfish (build 94)
INFORMACIÓN:   Server log file is using Formatter class: com.sun.enterprise.server.logging.ODLLogFormatter
ADVERTENCIA:   Unable to construct HTTP/2 Addon
java.lang.NoClassDefFoundError: org/glassfish/grizzly/npn/AlpnServerNegotiator
	at org.glassfish.grizzly.config.GenericGrizzlyListener.configureHttp2Support(GenericGrizzlyListener.java:806)
	at org.glassfish.grizzly.config.GenericGrizzlyListener.configureHttpProtocol(GenericGrizzlyListener.java:782)
	at com.sun.enterprise.v3.services.impl.GlassfishNetworkListener.configureHttpProtocol(GlassfishNetworkListener.java:212)
	at org.glassfish.grizzly.config.GenericGrizzlyListener.configureSubProtocol(GenericGrizzlyListener.java:456)
	at org.glassfish.grizzly.config.GenericGrizzlyListener.configureProtocol(GenericGrizzlyListener.java:445)
	at org.glassfish.grizzly.config.GenericGrizzlyListener.configure(GenericGrizzlyListener.java:341)
	at com.sun.enterprise.v3.services.impl.GrizzlyProxy.initialize(GrizzlyProxy.java:126)
	at com.sun.enterprise.v3.services.impl.GrizzlyService.createNetworkProxy(GrizzlyService.java:637)
	at com.sun.enterprise.v3.services.impl.GrizzlyService.postConstruct(GrizzlyService.java:559)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:327)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:375)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:89)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:90)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1237)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.glassfish.grizzly.npn.AlpnServerNegotiator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.felix.framework.ExtensionManager$ExtensionManagerWiring.getClassByDelegation(ExtensionManager.java:1174)
	at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1618)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1548)
	at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1982)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 22 more

`

## Environment ##

- **Payara Version**: 5.191
- **Edition**: 
- **JDK Version**: OpenJDK Runtime Environment Corretto-8.202.08.2 (build 1.8.0_202-b08)
- **Operating System**: Ubuntu 18.04.2 LTS

**Comment by diegosilval** [comment]
Sorry, it left JAVA_HOME
