### ISSUE TITLE
payara server and payara-embedded-all 5.192 have problems starting on MacOS with screen sharing enabled

### ISSUE THREAD

**Issue by phillipross** [payara/Payara#3995]
# Description #
----------

When attempting to start a brand new installation of payara-5.192 on MacOS, the asadmin start-domain command takes a long time to complete.  When attempting to run arquillian tests with payara-embedded-all, deployment seems to never occur.  Both seem to be related to a hazelcast network problem as they share similar server log output.

## Expected Outcome

domain should start within a few seconds

## Current Outcome

the domain takes a long time to start, and the server.log shows numerous (200+) hazelcast connection failures that look similar to the following:
```
[2019-06-01T01:18:00.746-0400] [Payara 5.192] [WARNING] [] [com.hazelcast.nio.tcp.TcpIpConnection] [tid: _ThreadID=125 _ThreadName=hz._hzInstance_1_development.IO.thread-in-0] [timeMillis: 1559366280746] [levelValue: 900] [[
  [10.1.1.108]:4900 [development] [3.12] Connection[id=1, /10.1.1.108:49796->/10.1.1.108:5900, qualifier=null, endpoint=[10.1.1.108]:5900, alive=false, type=NONE] closed. Reason: Exception in Connection[id=1, /10.1.1.108:49796->/10.1.1.108:5900, qualifier=null, endpoint=[10.1.1.108]:5900, alive=true, type=NONE], thread=hz._hzInstance_1_development.IO.thread-in-0
java.lang.IllegalStateException: Unknown protocol: RFB
        at com.hazelcast.nio.tcp.UnifiedProtocolDecoder.onRead(UnifiedProtocolDecoder.java:107)
        at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:135)
        at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:369)
        at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:354)
        at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:280)
        at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:235)
]]
```

The errors in the server log show what appear to be repeated attempts to create a connection, where the port is incrementing with each attempt, and the IllegalStateException stacktrace being displayed each time (RFB protocol?)  

After the hazelcast connection errors in the server log, the following log entries occur:
```
[2019-06-01T02:04:52.933-0400] [Payara 5.192] [WARNING] [] [com.hazelcast.instance.Node] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1559369092933] [levelValue: 900] [[
  [10.1.1.108]:4900 [development] [3.12] Terminating forcefully...]]

[2019-06-01T02:04:52.951-0400] [Payara 5.192] [WARNING] [] [com.hazelcast.util.PhoneHome] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1559369092951] [levelValue: 900] [[
  [10.1.1.108]:4900 [development] [3.12] Could not schedule phone home task! Most probably Hazelcast failed to start.]]

[2019-06-01T02:04:52.952-0400] [Payara 5.192] [WARNING] [NCLS-CORE-00069] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1559369092952] [levelValue: 900] [[
  Exception while dispatching an event
java.lang.IllegalStateException: Node failed to start!
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:138)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:228)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:207)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:157)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57)
	at fish.payara.nucleus.hazelcast.HazelcastCore.bootstrapHazelcast(HazelcastCore.java:472)
	at fish.payara.nucleus.hazelcast.HazelcastCore.getUUID(HazelcastCore.java:210)
	at fish.payara.appserver.micro.services.PayaraInstanceImpl.initialiseInstanceDescriptor(PayaraInstanceImpl.java:368)
	at fish.payara.appserver.micro.services.PayaraInstanceImpl.event(PayaraInstanceImpl.java:242)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at com.sun.enterprise.v3.server.AppServerStartup.postStartupJob(AppServerStartup.java:431)
	at com.sun.enterprise.v3.server.AppServerStartup.run(AppServerStartup.java:353)
	at com.sun.enterprise.v3.server.AppServerStartup.doStart(AppServerStartup.java:234)
	at com.sun.enterprise.v3.server.AppServerStartup.start(AppServerStartup.java:223)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishImpl.start(GlassFishImpl.java:83)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishDecorator.start(GlassFishDecorator.java:63)
	at com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishImpl.start(EmbeddedOSGiGlassFishImpl.java:75)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishDecorator.start(GlassFishDecorator.java:63)
	at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishImpl.start(OSGiGlassFishImpl.java:71)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:109)
	at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:54)
]]
```

## Steps to reproduce (Only for bug reports) 

1 -**  Start the domain

    ./asadmin start-domain domain1

## Context (Optional)

This seems to only happen on native MacOS and not within linux VMs or docker containers, but the real problem is that it's affecting integration tests using arquillian and payara-embedded-all which are developed locally in MacOS environments.  There are probably workarounds to configuring hazelcast network discovery or something within the domain, but what is really needed would be a way to get the workaround for payara-embedded-all so that integration tests work again.

## Environment ##

- **Payara Version**: 5.192 (works fine on 5.191 and earlier)
- **Edition**: full / embedded-all
- **JDK Version**: Zulu 8.38.0.13-CA-macosx) (build 1.8.0_212-b04)
- **Operating System**: MacOS 10.13 and MacOS 10.14

**Comment by smillidge** [comment]
Do you have VNC running?

**Comment by phillipross** [comment]
Ahhhhhh yeah, I had "screen sharing" turned on.  After disabling the screen sharing, the server starts fine and arquillian integration tests with payara-embedded-all work fine as well.  Thanks!

I imagine this would be a hazelcast port colliding with the vnc server port then?  I wonder what the best way to resolve this would be within the embedded server.

**Comment by jbee** [comment]
@phillipross yes its a hazelcast port collision. We noticed it shortly before you did but didn't have time yet to look into the reason for changed ports.

**Comment by smillidge** [comment]
weird thing is ports haven't changed but this seems to be causing problems on some versions.

**Comment by phillipross** [comment]
Shall I let this issue remain open for investigation?

**Comment by phillipross** [comment]
After playing around with the embedded server, I see with 5.184 and 5.191 that attempts are made on 5900 but it only tries 5 times... and it reports that memcached or ssl is not enabled:
```
Jun 02, 2019 5:32:11 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.1.1.108]:4900 [development] [3.11.1] Connecting to /10.1.1.108:5900, timeout: 0, bind-any: true
Jun 02, 2019 5:32:11 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [10.1.1.108]:4900 [development] [3.11.1] Connection[id=1, /10.1.1.108:51946->/10.1.1.108:5900, endpoint=[10.1.1.108]:5900, alive=false, type=NONE] closed. Reason: Memcached or SSL not enabled
Jun 02, 2019 5:32:12 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.1.1.108]:4900 [development] [3.11.1] Connecting to /10.1.1.108:5900, timeout: 0, bind-any: true
Jun 02, 2019 5:32:12 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [10.1.1.108]:4900 [development] [3.11.1] Connection[id=2, /10.1.1.108:51947->/10.1.1.108:5900, endpoint=[10.1.1.108]:5900, alive=false, type=NONE] closed. Reason: Memcached or SSL not enabled
Jun 02, 2019 5:32:13 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.1.1.108]:4900 [development] [3.11.1] Connecting to /10.1.1.108:5900, timeout: 0, bind-any: true
Jun 02, 2019 5:32:13 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [10.1.1.108]:4900 [development] [3.11.1] Connection[id=3, /10.1.1.108:51948->/10.1.1.108:5900, endpoint=[10.1.1.108]:5900, alive=false, type=NONE] closed. Reason: Memcached or SSL not enabled
Jun 02, 2019 5:32:14 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.1.1.108]:4900 [development] [3.11.1] Connecting to /10.1.1.108:5900, timeout: 0, bind-any: true
Jun 02, 2019 5:32:14 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [10.1.1.108]:4900 [development] [3.11.1] Connection[id=4, /10.1.1.108:51949->/10.1.1.108:5900, endpoint=[10.1.1.108]:5900, alive=false, type=NONE] closed. Reason: Memcached or SSL not enabled
Jun 02, 2019 5:32:15 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.1.1.108]:4900 [development] [3.11.1] Connecting to /10.1.1.108:5900, timeout: 0, bind-any: true
Jun 02, 2019 5:32:15 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [10.1.1.108]:4900 [development] [3.11.1] Connection[id=5, /10.1.1.108:51950->/10.1.1.108:5900, endpoint=[10.1.1.108]:5900, alive=false, type=NONE] closed. Reason: Memcached or SSL not enabled
Jun 02, 2019 5:32:16 PM com.hazelcast.internal.cluster.ClusterService
INFO: [10.1.1.108]:4900 [development] [3.11.1] 

Members {size:1, ver:1} [
	Member [10.1.1.108]:4900 - 3188d592-63d2-42a0-b0b1-06cc07b85df7 this
]
```

with 5.192 the error message is different:
```
Jun 02, 2019 5:33:34 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.1.1.108]:4900 [development] [3.12] Connecting to /10.1.1.108:5900, timeout: 10000, bind-any: true
Jun 02, 2019 5:33:34 PM com.hazelcast.nio.tcp.TcpIpConnection
WARNING: [10.1.1.108]:4900 [development] [3.12] Connection[id=1, /10.1.1.108:51970->/10.1.1.108:5900, qualifier=null, endpoint=[10.1.1.108]:5900, alive=false, type=NONE] closed. Reason: Exception in Connection[id=1, /10.1.1.108:51970->/10.1.1.108:5900, qualifier=null, endpoint=[10.1.1.108]:5900, alive=true, type=NONE], thread=hz._hzInstance_1_development.IO.thread-in-0
java.lang.IllegalStateException: Unknown protocol: RFB
	at com.hazelcast.nio.tcp.UnifiedProtocolDecoder.onRead(UnifiedProtocolDecoder.java:107)
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:135)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:369)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:354)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:280)
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:235)
```

I also notice that with 5.191 the output shows a timeout of 0 but in 5.192 the timeout is 10000.
Prior to 5.192 the ports are conflicting, but hazelcast is reacting differently and giving up quickly, where this newer version of hazelcast reacts very poorly 😆

**Comment by smillidge** [comment]
Leave open as I think we need to track down why the DAS and embedded is eagerly looking for instances on 5900 when there is no instance in the domain.xml. Typically the DAS will do this t reconnect itself into the data grid and 5900 is the managed server port. However if there are no instances defined in the domain.xml it shouldn't need to do it.

**Comment by MonkeySolution** [comment]
On MacOS, Go to Preferences -> Sharing, and then Disable "Screen Sharing".
 Somehow, "Screen sharing" open port 5900 causes the issue.

**Comment by mjhatamy** [comment]
On MacOS, Go to Preferences -> Sharing, and then Disable "Screen Sharing".
Somehow, "Screen sharing" open port 5900 causes the issue.

**Comment by johnmanko** [comment]
This is happening on 5.192 but not 5.191.  I'm running on Linux and it's preventing Netbeans from deploying my application.

> Launching Payara Server on Felix platform
> Jun 05, 2019 5:21:27 PM com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner createBundleProvisioner
> INFO: Create bundle provisioner class = class com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner.
> Registered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishRuntime@73329f83 in service registry.
> #!## LogManagerService.postConstruct : rootFolder=/home/john/dev/servers/payara/payara-5.192/payara5/glassfish
> #!## LogManagerService.postConstruct : templateDir=/home/john/dev/servers/payara/payara-5.192/payara5/glassfish/lib/templates
> #!## LogManagerService.postConstruct : src=/home/john/dev/servers/payara/payara-5.192/payara5/glassfish/lib/templates/logging.properties
> #!## LogManagerService.postConstruct : dest=/home/john/dev/servers/payara/payara-5.192/payara5/glassfish/domains/domain1/config/logging.properties
> Info:   Running Payara Version: Payara Server  5.192 #badassfish (build 115)
> Info:   Server log file is using Formatter class: com.sun.enterprise.server.logging.ODLLogFormatter
> Info:   Registered fish.payara.ha.hazelcast.store.HazelcastBackingStoreFactoryProxy for persistence-type = hazelcast in BackingStoreFactoryRegistry
> Info:   HV000001: Hibernate Validator 6.0.16.Final
> Info:   Network Listener http-listener-1 started in: 27ms - bound to [/0.0.0.0:8080]
> Info:   Network Listener http-listener-2 started in: 163ms - bound to [/0.0.0.0:8181]
> Info:   Network Listener admin-listener started in: 20ms - bound to [/0.0.0.0:4848]
> Info:   Grizzly 2.4.3 started in: 1,171ms - bound to [http-listener-1:8080, http-listener-2:8181, admin-listener:4848]
> Info:   Network Listener iiop-service started in: 14ms - bound to [/0.0.0.0:3700]
> Warning:   [192.168.150.93]:4900 [development] [3.12] Connection[id=1, /172.18.0.1:44069->/172.18.0.1:5900, qualifier=null, endpoint=[172.18.0.1]:5900, alive=false, type=NONE] closed. Reason: Exception in Connection[id=1, /172.18.0.1:44069->/172.18.0.1:5900, qualifier=null, endpoint=[172.18.0.1]:5900, alive=true, type=NONE], thread=hz._hzInstance_1_development.IO.thread-in-0
> java.lang.IllegalStateException: Unknown protocol: RFB
> 	at com.hazelcast.nio.tcp.UnifiedProtocolDecoder.onRead(UnifiedProtocolDecoder.java:107)
> 	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:135)
> 	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:369)
> 	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:354)
> 	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:280)
> 	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:235)

**Comment by phillipross** [comment]
This might help:
https://docs.payara.fish/documentation/payara-server/hazelcast/configuration.html

**Comment by smillidge** [comment]
It's not shown in the XML as it is the default. It is changed in the Data Grid config below each individual config e.g. default-config and server-config

**Comment by johnmanko** [comment]
@phillipross It's odd that the Property/Description table in the documentation are only in human-readable format.  The xml element paths/names should be included.

**Comment by rdebusscher** [comment]
Payara 5.192 is based on Hazelcast 3.12 where the logic has changed around checking the ports.  This is the reason for the changed behaviour.

For future reference:
If you need to combine the screen sharing software with Payara running, you can change the port Hazelcast is using with the command

> ./asadmin set-hazelcast-configuration --startport=5901

or through the WebConsole

**Comment by aortiz49** [comment]
> On MacOS, Go to Preferences -> Sharing, and then Disable "Screen Sharing".
> Somehow, "Screen sharing" open port 5900 causes the issue.

Hey man, thank you so much! This was an issue I've had all semester. Now I can finally test my services with Postman on my localhost.

**Comment by phillipross** [comment]
for reference:
https://twitter.com/Payara_Fish/status/1308029039081390085
https://adambien.blog/roller/abien/entry/payara_the_unknown_protocol_rfb

**Comment by lprimak** [comment]
Hazelcast issue https://github.com/hazelcast/hazelcast/issues/178566

**Comment by tychen742** [comment]
> On MacOS, Go to Preferences -> Sharing, and then Disable "Screen Sharing". Somehow, "Screen sharing" open port 5900 causes the issue.

Man, how do you know about this? I spent hours and your answer solved my problem!

**Comment by phillipross** [comment]
it's annoying and discouraging that this issue has seemingly still not been fixed in hazelcast yet

**Comment by JamesHillyard** [comment]
I agree it is unfortunate that Hazelcast still have not implemented a fix for this. I have added a note of this issue within the documentation to hopefully help people find the known workaround.

I have also prompted for an update on the Hazelcast issue raised by Lenny.

**Comment by phillipross** [comment]
Thanks @JamesHillyard !

Maybe @lprimak or someone else can comment here for an update, but I seem to recall there was some technical difficulty involved on the hazelcast side to get this issue resolved.  Maybe in addition to poking hazelcast folks to see if there's any way to get traction on the issue, we may also drum up support from the communities to help think through any tech challenges on the hazelcast side, or better yet help pitch in whatever implementation-level work might be necessary if it's just a case of refactoring some code or something.  🤔
