### ISSUE TITLE
NPE using JSONLogFormatter when throwing exception with null message

### ISSUE THREAD

**Issue by jeromeky** [payara/Payara#4067]
Hi there,

I'm currently using Payara v5.192 with the JSON log formatter (https://payara.gitbooks.io/payara-server/documentation/payara-server/logging/json-formatter.html).

However, I have an issue when we log an exception without a message.

`log.log(Level.SEVERE, "", new Exception());`

It's throwing an NPE exception

	{
	  "Timestamp": "2019-07-02T04:18:19.667+0000",
	  "Level": "SEVERE",
	  "Version": "Payara 5.192",
	  "LoggerName": "",
	  "ThreadID": "71",
	  "ThreadName": "payara-executor-service-task",
	  "TimeMillis": "1562041099667",
	  "LevelValue": "1000",
	  "LogMessage": "java.util.logging.ErrorManager: 5: Error in formatting Logrecord"
	}
	{
	"Timestamp": "2019-07-02T04:18:19.679+0000",
	"Level": "SEVERE",
	"Version": "Payara 5.192",
	"LoggerName": "",
	"ThreadID": "71",
	"ThreadName": "payara-executor-service-task",
	"TimeMillis": "1562041099679",
	"LevelValue": "1000",
	"LogMessage": "
		java.lang.NullPointerException: Value in JsonObjects name/value pair cannot be null
			at org.glassfish.json.JsonObjectBuilderImpl.validateValue(JsonObjectBuilderImpl.java:222)
			at org.glassfish.json.JsonObjectBuilderImpl.add(JsonObjectBuilderImpl.java:90)
			at fish.payara.enterprise.server.logging.JSONLogFormatter.jsonLogFormat(JSONLogFormatter.java:397)
			at fish.payara.enterprise.server.logging.JSONLogFormatter.format(JSONLogFormatter.java:191)
			at java.util.logging.StreamHandler.publish(StreamHandler.java:211)
			at com.sun.enterprise.server.logging.GFFileHandler.log(GFFileHandler.java:966)
			at com.sun.enterprise.server.logging.GFFileHandler.lambda$initializePump$2(GFFileHandler.java:597)
			at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
			at java.util.concurrent.FutureTask.run(FutureTask.java:266)
			at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
			at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
			at java.lang.Thread.run(Thread.java:748)"
	}

Looks like this is coming from

`traceObject.add(EXCEPTION_KEY, throwable.getMessage());` in JsonLogFormatter class.

### Environment
Payara Version: 5.192

**Comment by khasunuma** [comment]
I reproduced this issue and confirmed the bug.

[JsonObjectBuilder#add(String, String)](https://javaee.github.io/javaee-spec/javadocs/javax/json/JsonObjectBuilder.html#add-java.lang.String-java.lang.String-) is not allowed `null` in each parameter, however the second parameter is `null` in this case. (If to evaluate `new Exception().getMessage()`, the value is `null`.)
