### ISSUE TITLE
asadmin commands in postboot commandfile not resulting in same outcome as running it manually 

### ISSUE THREAD

**Issue by StijnVdd** [payara/Payara#4178]
# Description #
----------

When running a post-boot-command file, creating a auth-relam is not working properly. (in docker container)
I'm able to create some JDBC connection pools, registering some system properties, but creating a custom authentication-realm is not possible.

## Expected Outcome
The commands are executed successfully, in these specific cases: authentication realm with sql statements as one or more properties properties.
It's also expected that the same command, tested with asadmin multimode, works in a postbootcommandfile, but it's not true. 

## Current Outcome
The log reports "This parameter may not have more than one value." when running using a post-boot-command file

`[2019-08-26T05:02:56.870+0000] [Payara 5.192] [SEVERE] [NCLS-CORE-00003] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1566795776870] [levelValue: 1000] [[
  Exception while running a command
org.glassfish.common.util.admin.UnacceptableValueException: Invalid parameter: authrealmname.  This parameter may not have more than one value.
	at org.glassfish.common.util.admin.MapInjectionResolver.convertListToObject(MapInjectionResolver.java:405)
	at org.glassfish.common.util.admin.MapInjectionResolver.getValue(MapInjectionResolver.java:136)
	at org.jvnet.hk2.config.InjectionManager.syncDoInject(InjectionManager.java:170)
	at org.jvnet.hk2.config.InjectionManager.inject(InjectionManager.java:74)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.injectParameters(CommandRunnerImpl.java:386)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1242)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:119)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1865)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1741)
	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:172)
	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:96)
	at fish.payara.boot.runtime.BootCommand.execute(BootCommand.java:69)
	at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:110)
	at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:104)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.doBootCommands(GlassFishMain.java:294)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:109)
	at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:54)
]]

[2019-08-26T05:02:56.882+0000] [Payara 5.192] [WARNING] [] [fish.payara.boot.runtime.BootCommand] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1566795776882] [levelValue: 900] [[
  Boot Command create-auth-realm failed PlainTextActionReporterFAILUREorg.glassfish.common.util.admin.UnacceptableValueException: Invalid parameter: authrealmname.  This parameter may not have more than one value.Description: create-auth-realm commandInvalid parameter: authrealmname.  This parameter may not have more than one value.
    Usage: create-auth-realm --classname=classname [--property=property] [--target=server] [--login-module=login-module] authrealmname 
 ]]
`

## Steps to reproduce (Only for bug reports) 
asAdmin command

Please note that in My case I do use a custom class. I chose here a 'FileRealm' to demonstrate my issue

`create-auth-realm --classname=com.sun.enterprise.security.auth.realm.file.FileRealm --target=server-config --property java.naming.referral=ignore:jaas-context=myMontovaRealm:datasource.jndi=jdbc/SomeJDBC:sql.password="SELECT u.password FROM users u WHERE u.email \= ? AND u.active \= true":sql.groups="SELECT SOME OTHER SQL":sql.impersonate_user="YET ANOTHER":sql.token="SELECT r.token FROM rememberme_token r WHERE r.email \= ? AND r.token \= ?":search-bind-dn=TestUser:search-bind-password=Password:directory=DummyDir:base-dn="DC\=company,DC\=com":file=testFile myRealm`

When running this command in multimode
`PS Desktop\payara-5.192\payara5\bin> .\asadmin create-auth-realm --classname=com.sun.enterprise.security.auth.realm.file.FileRealm --target=server-config --property java.naming.referral=ignore:jaas-context=myMontovaRealm:datasource.jndi=jdbc/SomeJDBC:sql.password="SELECT u.password FROM users u WHERE u.email \= ? AND u.active \= true":sql.groups="SELECT SOME OTHER SQL":sql.impersonate_user="YET ANOTHER":sql.token="SELECT r.token FROM rememberme_token r WHERE r.email \= ? AND r.token \= ?":search-bind-dn=TestUser:search-bind-password=Password:directory=DummyDir:base-dn="DC\=company,DC\=com":file=testFile myRealm                                                                            Command create-auth-realm executed successfully.`
## Context (Optional)

Running the post-boot-command file in a docker container

## Environment ##

- **Payara Version**: 5.192
- **Edition**: Full

**Comment by sm0ke21** [comment]
I am getting the same behaviour with a simple create-jvm-options post-boot command. It works as expected on the cli, but fails as a post-boot command. 

I am using the _payara/server-full_ docker image.

### Sample post-boot-commands.asadmin
create-jvm-options -Dfoo=bar

### Output
```
[#|2019-10-31T14:05:54.428+0000|WARNING|Payara 5.193|fish.payara.boot.runtime.BootCommand|_ThreadID=1;_ThreadName=main;_TimeMillis=1572530754428;_LevelValue=900;|
  Boot Command create-jvm-options failed Exception while executing command. |#]
```

I can't even reproduce any of the examples here: https://github.com/payara/Payara-Server-Documentation/blob/master/documentation/payara-micro/asadmin/pre-and-post-boot-scripts.adoc

**Comment by fturizo** [comment]
@StijnVdd, @sm0ke21, have you been able to reproduce the issue on the latest release of Payara Server 5.x? If the issue is still present, can you please provide a complete reproducer that helps us identify the problem? Attaching the scripts, docker images and any commands run would help.

**Comment by fturizo** [comment]
@StijnVdd, @sm0ke21, have you verified that the issue is still present in the current release of Payara Server 5.x? If we do not receive any updates soon we'll close this issue.

**Comment by fturizo** [comment]
Closing this issue as there's no response from the users involved.

**Comment by ndrgrbr** [comment]
check spaces in values

[structure-of-a-boot-script](https://github.com/payara/Payara-Documentation/blob/master/docs/modules/ROOT/pages/Technical%20Documentation/Payara%20Micro%20Documentation/Payara%20Micro%20Configuration%20and%20Management/Micro%20Management/Asadmin%20Commands/Pre%20and%20Post%20Boot%20Commands.adoc#structure-of-a-boot-script)

Boot scripts are simple text files that contain the _asadmin_ subcommands used to configure the instance. These scripts will follow these set of rules:

...
. Each _asadmin_ command must be formatted on the syntax `subcommand [options] [operands]`,
...
**NOTE: _asadmin_ commands that contain spaces in the value should be surrounded with quotations marks.**

incorrect:
`create-auth-realm --classname=com.sun.enterprise.security.auth.realm.file.FileRealm --target=server-config --property java.naming.referral=ignore:jaas-context=myMontovaRealm:datasource.jndi=jdbc/SomeJDBC:sql.password="SELECT u.password...:file=testFile myRealm`

correct:
`create-auth-realm --classname=com.sun.enterprise.security.auth.realm.file.FileRealm --target=server-config --property "java.naming.referral=ignore:jaas-context=myMontovaRealm:datasource.jndi=jdbc/SomeJDBC:sql.password=SELECT u.password...:file=testFile" myRealm`
