### ISSUE TITLE
"Server failed to start" with "Failed to start OSGiModuleImpl" PAYARA-4122

### ISSUE THREAD

**Issue by deratzmann** [payara/Payara#4182]
# Description #
----------
Hey guys.

Since some days we experienced the issue, that the payara full server does not start from time to time. The Exception seems to be a deep payara system exception.
Do you have any hints where to search for solution? Is this a network or a configuration issue? Or something else?
We also have problems to reproduce it, sometimes the server starts, sometimes not showing these problems.

Here is the exception:
`asadmin --host localhost --port 4848 --user admin --passwordfile /opt/admin_pwds --interactive=false --echo=true --terse=false start-domain --verbose=true --upgrade=false --watchdog=false --debug=false --dry-run=false --drop-interrupted-commands=false --postbootcommandfile /opt/deployApp.cli
Aug 27, 2019 1:08:28 PM com.sun.enterprise.admin.launcher.GFLauncherLogger info
INFO: JVM invocation command line:
/usr/local/openjdk-8/bin/java
-cp
/opt/payara/glassfish/modules/glassfish.jar
-XX:+UnlockDiagnosticVMOptions
-XX:MetaspaceSize=256m
-XX:NewSize=256m
-XX:MaxNewSize=256m
-XX:+DisableExplicitGC
-XX:+UseStringDeduplication
-XX:MaxMetaspaceSize=2g
-XX:ErrorFile=/var/log/4e8b61839cfc/hs_err_pid%p.log
-XX:+PrintGCDateStamps
-XX:+UseG1GC
-XX:MaxGCPauseMillis=500
-Xmx3584m
-Xms3584m
-Xbootclasspath/p:/opt/payara/glassfish/lib/grizzly-npn-bootstrap-1.8.1.jar
-server
-javaagent:/opt/payara/glassfish/lib/monitor/flashlight-agent.jar
-Djavax.xml.accessExternalSchema=all
-Djava.security.auth.login.config=/opt/payara/glassfish/domains/production/config/login.conf
-Djavax.net.ssl.trustStore=/opt/payara/glassfish/domains/production/config/cacerts.jks
-Dorg.glassfish.grizzly.DEFAULT_MEMORY_MANAGER=org.glassfish.grizzly.memory.HeapMemoryManager
-Djdk.tls.rejectClientInitiatedRenegotiation=true
-Djdk.corba.allowOutputStreamSubclass=true
-Dcom.sun.xml.ws.server.http.publishStatusPage=false
-Dproduct.name
-Dcom.sun.xml.ws.transport.http.HttpAdapter.publishStatusPage=false
-Dcom.sun.aas.instanceRoot=/opt/payara/glassfish/domains/production
-Dcom.sun.aas.installRoot=/opt/payara/glassfish
-Djava.security.policy=/opt/payara/glassfish/domains/production/config/server.policy
-Dorg.jboss.weld.serialization.beanIdentifierIndexOptimization=false
-Dfish.payara.classloading.delegate=false
-Dcom.sun.enterprise.config.config_environment_factory_class=com.sun.enterprise.config.serverbeans.AppserverConfigEnvironmentFactory
-Dfile.encoding=UTF8
-DANTLR_USE_DIRECT_CLASS_LOADING=true
-Duser.timezone=Europe/Berlin
-Djava.awt.headless=true
-Dcom.sun.xml.ws.fault.SOAPFaultBuilder.disableCaptureStackTrace=false
-Djdbc.drivers=org.apache.derby.jdbc.ClientDriver
-Dorg.glassfish.grizzly.nio.DefaultSelectorHandler.force-selector-spin-detection=true
-Djavax.net.ssl.keyStore=/opt/payara/glassfish/domains/production/config/keystore.jks
-Djava.library.path=/opt/payara/glassfish/lib:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
com.sun.enterprise.glassfish.bootstrap.ASMain
-upgrade
false
-read-stdin
true
-postbootcommandfile
/opt/deployApp.cli
-domainname
production
-domaindir
/opt/payara/glassfish/domains/production
-asadmin-args
--host,,,localhost,,,--port,,,4848,,,--user,,,admin,,,--passwordfile,,,/opt/admin_pwds,,,--secure=false,,,--terse=false,,,--echo=false,,,--interactive=false,,,start-domain,,,--verbose=true,,,--watchdog=false,,,--debug=false,,,--domaindir,,,/opt/payara/glassfish/domains,,,production
-instancename
server
-type
DAS
-verbose
true
-asadmin-classpath
/opt/payara/glassfish/lib/client/appserver-cli.jar
-debug
false
-asadmin-classname
com.sun.enterprise.admin.cli.AdminMain
-watchdog
false
Launching Payara Server on Felix platform
Aug 27, 2019 1:08:28 PM com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner createBundleProvisioner
INFO: Create bundle provisioner class = class com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner.
Registered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishRuntime@4cda982d in service registry.

#!## LogManagerService.postConstruct : rootFolder=/opt/payara/glassfish
#!## LogManagerService.postConstruct : templateDir=/opt/payara/glassfish/lib/templates
#!## LogManagerService.postConstruct : src=/opt/payara/glassfish/lib/templates/logging.properties
#!## LogManagerService.postConstruct : dest=/opt/payara/glassfish/domains/production/config/logging.properties
[#|2019-08-27T13:08:30.581+0200|INFO|Payara 5.192|javax.enterprise.logging|_ThreadID=22;_ThreadName=RunLevelControllerThread-1566904110439;_TimeMillis=1566904110581;_LevelValue=800;_MessageID=NCLS-LOGGING-00009;|
  Running Payara Version: Payara Server  5.192 #badassfish (build 115)|#]

[#|2019-08-27T13:08:30.587+0200|INFO|Payara 5.192|javax.enterprise.logging|_ThreadID=22;_ThreadName=RunLevelControllerThread-1566904110439;_TimeMillis=1566904110587;_LevelValue=800;_MessageID=NCLS-LOGGING-00010;|
  Server log file is using Formatter class: com.sun.enterprise.server.logging.ODLLogFormatter|#]

[#|2019-08-27T13:08:31.364+0200|INFO|Payara 5.192|javax.enterprise.system.core|_ThreadID=23;_ThreadName=RunLevelControllerThread-1566904110449;_TimeMillis=1566904111364;_LevelValue=800;_MessageID=NCLS-CORE-00015;|
  Shutdown requested
MultiException stack 1 of 2
com.sun.enterprise.module.ResolveError: Failed to start OSGiModuleImpl:: Bundle = [fish.payara.micro.payara-micro-service [61]], State = [NEW]
        at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:217)
        at org.jvnet.hk2.osgiadapter.OsgiPopulatorPostProcessor$1.loadClass(OsgiPopulatorPostProcessor.java:78)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2248)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:459)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:478)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.isWouldBlockRightNow(CurrentTaskFuture.java:1194)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1230)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.osgi.framework.BundleException: Unable to acquire global lock for resolve. Unresolved requirements: []
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4368)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2281)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
        at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:209)
        ... 10 more
MultiException stack 2 of 2
java.lang.IllegalStateException: Could not load descriptor SystemDescriptor(
        implementation=fish.payara.appserver.micro.services.PayaraInstanceImpl
        name=payara-instance
        contracts={fish.payara.appserver.micro.services.PayaraInstanceImpl,fish.payara.micro.PayaraInstance}
        scope=org.glassfish.hk2.runlevel.RunLevel
        qualifiers={}
        descriptorType=CLASS
        descriptorVisibility=NORMAL
        metadata=runLevelValue={10},Bundle-SymbolicName={fish.payara.micro.payara-micro-service},Bundle-Version={5.192.0}
        rank=0
        loader=OsgiPopulatorPostProcessor.HK2Loader(OSGiModuleImpl:: Bundle = [fish.payara.micro.payara-micro-service [61]], State = [NEW],1250759846)
        proxiable=null
        proxyForSameScope=null
        analysisName=null
        id=863
        locatorId=0
        identityHashCode=1039417493
        reified=false)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2257)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:459)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:478)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.isWouldBlockRightNow(CurrentTaskFuture.java:1194)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1230)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
|#]

[#|2019-08-27T13:08:31.365+0200|SEVERE|Payara 5.192|javax.enterprise.system.core|_ThreadID=23;_ThreadName=RunLevelControllerThread-1566904110449;_TimeMillis=1566904111365;_LevelValue=1000;_MessageID=NCLS-CORE-00016;|
  Startup service failed to start
MultiException stack 1 of 2
com.sun.enterprise.module.ResolveError: Failed to start OSGiModuleImpl:: Bundle = [fish.payara.micro.payara-micro-service [61]], State = [NEW]
        at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:217)
        at org.jvnet.hk2.osgiadapter.OsgiPopulatorPostProcessor$1.loadClass(OsgiPopulatorPostProcessor.java:78)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2248)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:459)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:478)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.isWouldBlockRightNow(CurrentTaskFuture.java:1194)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1230)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.osgi.framework.BundleException: Unable to acquire global lock for resolve. Unresolved requirements: []
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4368)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2281)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
        at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:209)
        ... 10 more
MultiException stack 2 of 2
java.lang.IllegalStateException: Could not load descriptor SystemDescriptor(
        implementation=fish.payara.appserver.micro.services.PayaraInstanceImpl
        name=payara-instance
        contracts={fish.payara.appserver.micro.services.PayaraInstanceImpl,fish.payara.micro.PayaraInstance}
        scope=org.glassfish.hk2.runlevel.RunLevel
        qualifiers={}
        descriptorType=CLASS
        descriptorVisibility=NORMAL
        metadata=runLevelValue={10},Bundle-SymbolicName={fish.payara.micro.payara-micro-service},Bundle-Version={5.192.0}
        rank=0
        loader=OsgiPopulatorPostProcessor.HK2Loader(OSGiModuleImpl:: Bundle = [fish.payara.micro.payara-micro-service [61]], State = [NEW],1250759846)
        proxiable=null
        proxyForSameScope=null
        analysisName=null
        id=863
        locatorId=0
        identityHashCode=1039417493
        reified=false)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2257)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:459)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:478)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.isWouldBlockRightNow(CurrentTaskFuture.java:1194)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1230)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
|#]

[#|2019-08-27T13:08:31.426+0200|WARNING|Payara 5.192|fish.payara.nucleus.notification.NotificationEventBus|_ThreadID=23;_ThreadName=RunLevelControllerThread-1566904110449;_TimeMillis=1566904111426;_LevelValue=900;|
  Tried to unregisterfish.payara.notification.eventbus.core.CDIEventbusNotifierService@11592467, it may not have been previously registered|#]

[#|2019-08-27T13:08:31.470+0200|INFO|Payara 5.192|org.hibernate.validator.internal.util.Version|_ThreadID=23;_ThreadName=RunLevelControllerThread-1566904110449;_TimeMillis=1566904111470;_LevelValue=800;|
  HV000001: Hibernate Validator 6.0.16.Final|#]

[#|2019-08-27T13:08:31.536+0200|INFO|Payara 5.192|javax.enterprise.system.core|_ThreadID=24;_ThreadName=RunLevelControllerThread-1566904110450;_TimeMillis=1566904111536;_LevelValue=800;_MessageID=NCLS-CORE-00101;|
  Network Listener http-listener-1 started in: 9ms - bound to [/0.0.0.0:8080]|#]

[#|2019-08-27T13:08:31.554+0200|INFO|Payara 5.192|javax.enterprise.system.core|_ThreadID=24;_ThreadName=RunLevelControllerThread-1566904110450;_TimeMillis=1566904111554;_LevelValue=800;_MessageID=NCLS-CORE-00101;|
  Network Listener http-listener-2 started in: 1ms - bound to [/0.0.0.0:8181]|#]

[#|2019-08-27T13:08:31.558+0200|INFO|Payara 5.192|javax.enterprise.system.core|_ThreadID=24;_ThreadName=RunLevelControllerThread-1566904110450;_TimeMillis=1566904111558;_LevelValue=800;_MessageID=NCLS-CORE-00101;|
  Network Listener admin-listener started in: 1ms - bound to [/0.0.0.0:4848]|#]

[#|2019-08-27T13:08:31.563+0200|INFO|Payara 5.192|javax.enterprise.system.core|_ThreadID=24;_ThreadName=RunLevelControllerThread-1566904110450;_TimeMillis=1566904111563;_LevelValue=800;_MessageID=NCLS-CORE-00101;|
  Network Listener healthcheck-listener started in: 1ms - bound to [/0.0.0.0:8282]|#]

[#|2019-08-27T13:08:31.565+0200|INFO|Payara 5.192|javax.enterprise.system.core|_ThreadID=24;_ThreadName=RunLevelControllerThread-1566904110450;_TimeMillis=1566904111565;_LevelValue=800;_MessageID=NCLS-CORE-00087;|
  Grizzly 2.4.3 started in: 508ms - bound to [http-listener-1:8080, http-listener-2:8181, admin-listener:4848, healthcheck-listener:8282]|#]

[#|2019-08-27T13:08:31.639+0200|INFO|Payara 5.192|javax.enterprise.system.core|_ThreadID=56;_ThreadName=Thread-11;_TimeMillis=1566904111639;_LevelValue=800;_MessageID=NCLS-CORE-00092;|
  Server shutdown initiated|#]

[#|2019-08-27T13:08:31.723+0200|SEVERE|Payara 5.192|javax.enterprise.system.core|_ThreadID=1;_ThreadName=main;_TimeMillis=1566904111723;_LevelValue=1000;_MessageID=NCLS-CORE-00014;|
  Shutdown required
MultiException stack 1 of 1
MultiException stack 1 of 2
com.sun.enterprise.module.ResolveError: Failed to start OSGiModuleImpl:: Bundle = [fish.payara.micro.payara-micro-service [61]], State = [NEW]
        at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:217)
        at org.jvnet.hk2.osgiadapter.OsgiPopulatorPostProcessor$1.loadClass(OsgiPopulatorPostProcessor.java:78)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2248)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:459)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:478)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.isWouldBlockRightNow(CurrentTaskFuture.java:1194)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1230)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.osgi.framework.BundleException: Unable to acquire global lock for resolve. Unresolved requirements: []
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4368)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2281)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
        at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:209)
        ... 10 more
MultiException stack 2 of 2
java.lang.IllegalStateException: Could not load descriptor SystemDescriptor(
        implementation=fish.payara.appserver.micro.services.PayaraInstanceImpl
        name=payara-instance
        contracts={fish.payara.appserver.micro.services.PayaraInstanceImpl,fish.payara.micro.PayaraInstance}
        scope=org.glassfish.hk2.runlevel.RunLevel
        qualifiers={}
        descriptorType=CLASS
        descriptorVisibility=NORMAL
        metadata=runLevelValue={10},Bundle-SymbolicName={fish.payara.micro.payara-micro-service},Bundle-Version={5.192.0}
        rank=0
        loader=OsgiPopulatorPostProcessor.HK2Loader(OSGiModuleImpl:: Bundle = [fish.payara.micro.payara-micro-service [61]], State = [NEW],1250759846)
        proxiable=null
        proxyForSameScope=null
        analysisName=null
        id=863
        locatorId=0
        identityHashCode=1039417493
        reified=false)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2257)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:459)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:478)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.isWouldBlockRightNow(CurrentTaskFuture.java:1194)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1230)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
|#]

[#|2019-08-27T13:08:31.726+0200|INFO|Payara 5.192|javax.enterprise.system.core|_ThreadID=57;_ThreadName=Thread-12;_TimeMillis=1566904111726;_LevelValue=800;_MessageID=NCLS-CORE-00092;|
  Server shutdown initiated|#]

[#|2019-08-27T13:08:31.726+0200|SEVERE|Payara 5.192|javax.enterprise.system.core|_ThreadID=1;_ThreadName=main;_TimeMillis=1566904111726;_LevelValue=1000;|
  Failed to start, exiting|#]

[#|2019-08-27T13:08:31.727+0200|SEVERE|Payara 5.192||_ThreadID=1;_ThreadName=main;_TimeMillis=1566904111727;_LevelValue=1000;|
  Exception in thread "main" |#]

[#|2019-08-27T13:08:31.728+0200|SEVERE|Payara 5.192||_ThreadID=1;_ThreadName=main;_TimeMillis=1566904111728;_LevelValue=1000;|
  java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:109)
        at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:54)
Caused by: java.lang.RuntimeException: org.glassfish.embeddable.GlassFishException: Server failed to start
        at com.sun.enterprise.v3.server.AppServerStartup.start(AppServerStartup.java:225)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishImpl.start(GlassFishImpl.java:83)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishDecorator.start(GlassFishDecorator.java:63)
        at com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishImpl.start(EmbeddedOSGiGlassFishImpl.java:75)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishDecorator.start(GlassFishDecorator.java:63)
        at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishImpl.start(OSGiGlassFishImpl.java:71)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:130)
        ... 6 more
Caused by: org.glassfish.embeddable.GlassFishException: Server failed to start
        at com.sun.enterprise.v3.server.AppServerStartup.doStart(AppServerStartup.java:237)
        at com.sun.enterprise.v3.server.AppServerStartup.start(AppServerStartup.java:223)
        ... 12 more
|#]
`

## Expected Outcome
no exception, successfully started payara server.

## Current Outcome

server start fails.

## Environment ##

- **Payara Version**: 5.192
- **Edition**: Full
- **JDK Version**: OpenJDK 8
- **Operating System**: docker image openjdk8
- **Database**: postgres

Thanks for help.

Bastian

**Comment by rdebusscher** [comment]
Hi Bastian,

We believe this is a race condition within the Felix OSGI system and we are working on a reliable reproducer and fix for this issue.

Regards
Rudy.

see also https://github.com/payara/docker-payaraserver-full/issues/91

**Comment by andytechdad** [comment]
I'm hitting this in Payara 5.193

**Comment by rdebusscher** [comment]
Fixed as part of 5.193.1 which is released to public.

**Comment by pzygielo** [comment]
> Fixed as part of 5.193.1 which is released to public.

http://repo.maven.apache.org/maven2/fish/payara/distributions/payara/5.193.1/payara-5.193.1.pom:
```xml
<tag>payara-server-5.193.1</tag>
```

Could `payara-server-5.193.1` be pushed to GitHub, please? Can't find it at https://github.com/payara/Payara/tags.

**Comment by rdebusscher** [comment]
Hi @pzygielo 

The 5.193.1 is a special release (not a regular community release) which is performed from a private branch for customers.

Therefor it is not possible to tag a certain commit within the repo. But all commits are present in master branch.

You can download the binaries from the [website](https://www.payara.fish/software/downloads/) and difference with 5.193 tag is limited if you want to debug.

**Comment by andytechdad** [comment]
@rdebusscher I can confirm upgrading to 5.193.1 fixed our issue.

Thanks for the quick release.

**Comment by pzygielo** [comment]
@rdebusscher :+1: Thanks for checking and update.

**Comment by deratzmann** [comment]
Thank you!!!
