### ISSUE TITLE
Not possible to set datasource port as environment variable in web.xml

### ISSUE THREAD

**Issue by dwamara** [payara/Payara#4192]
# Description #

This issue can be related to https://github.com/payara/Payara/issues/1935 but I think that it was at the time not correctly assessed:
When trying to set a placeholder for a variable that should be set for the datasource port in the web.xml, one gets following error

```
 Error occurred
org.xml.sax.SAXParseException; lineNumber: 11; columnNumber: 57; Deployment descriptor file WEB-INF/web.xml in archive [spuvhost-configurator.war].  cvc-datatype-valid.1.2.1: '${ENV=DB_SERVER_PORT}' ist kein gültiger Wert für 'integer'.
	at com.sun.enterprise.deployment.io.DeploymentDescriptorFile.read(DeploymentDescriptorFile.java:322)
	at com.sun.enterprise.deployment.io.DeploymentDescriptorFile.read(DeploymentDescriptorFile.java:239)
	at com.sun.enterprise.deployment.archivist.Archivist.readStandardDeploymentDescriptor(Archivist.java:677)
	at com.sun.enterprise.deployment.archivist.ApplicationFactory.createApplicationFromStandardDD(ApplicationFactory.java:210)
	at org.glassfish.javaee.core.deployment.DolProvider.getNameFor(DolProvider.java:268)
.......
Caused by: org.xml.sax.SAXParseException; lineNumber: 11; columnNumber: 57; cvc-datatype-valid.1.2.1: '${ENV=DB_SERVER_PORT}' ist kein gültiger Wert für 'integer'.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
```
I personally think that this has nothing to do with the placeholder not being replaced but with the fact that the file fails the validation before even the replacement is done (correct me if I am wrong and if there is no validation prior to the replacement) as as soon as I had the placeholder in my web.xml, IntelliJ already complained that something was wrong and that the value should have been an integer.
 
## Expected Outcome

The application starts and the value is correctly set in the web.xml file.

## Current Outcome

``` 
Error occurred
org.xml.sax.SAXParseException; lineNumber: 11; columnNumber: 57; Deployment descriptor file WEB-INF/web.xml in archive [spuvhost-configurator.war].  cvc-datatype-valid.1.2.1: '${ENV=DB_SERVER_PORT}' ist kein gültiger Wert für 'integer'.
	at com.sun.enterprise.deployment.io.DeploymentDescriptorFile.read(DeploymentDescriptorFile.java:322)
	at com.sun.enterprise.deployment.io.DeploymentDescriptorFile.read(DeploymentDescriptorFile.java:239)
	at com.sun.enterprise.deployment.archivist.Archivist.readStandardDeploymentDescriptor(Archivist.java:677)
	at com.sun.enterprise.deployment.archivist.ApplicationFactory.createApplicationFromStandardDD(ApplicationFactory.java:210)
	at org.glassfish.javaee.core.deployment.DolProvider.getNameFor(DolProvider.java:268)
	at org.glassfish.internal.deployment.GenericHandler.getDefaultApplicationName(GenericHandler.java:150)
	at org.glassfish.deployment.admin.DeployCommand.preAuthorization(DeployCommand.java:315)
	at com.sun.enterprise.admin.util.CommandSecurityChecker$1.run(CommandSecurityChecker.java:184)
	at com.sun.enterprise.admin.util.CommandSecurityChecker$1.run(CommandSecurityChecker.java:180)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.admin.util.CommandSecurityChecker.authorize(CommandSecurityChecker.java:180)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1269)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:120)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1877)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1753)
	at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:136)
	at fish.payara.micro.impl.PayaraMicroImpl.deployAll(PayaraMicroImpl.java:1568)
	at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1043)
	at fish.payara.micro.impl.PayaraMicroImpl.create(PayaraMicroImpl.java:210)
	at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:50)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:112)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:71)
	at fish.payara.micro.boot.PayaraMicroLauncher.create(PayaraMicroLauncher.java:87)
	at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:71)
	at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:397)
Caused by: org.xml.sax.SAXParseException; lineNumber: 11; columnNumber: 57; cvc-datatype-valid.1.2.1: '${ENV=DB_SERVER_PORT}' ist kein gültiger Wert für 'integer'.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:453)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3231)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.elementLocallyValidComplexType(XMLSchemaValidator.java:3185)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.elementLocallyValidType(XMLSchemaValidator.java:3154)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.processElementContent(XMLSchemaValidator.java:3056)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleEndElement(XMLSchemaValidator.java:2135)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.endElement(XMLSchemaValidator.java:854)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at com.sun.enterprise.deployment.io.DeploymentDescriptorFile.read(DeploymentDescriptorFile.java:312)
	... 30 more
]]
```
## Steps to reproduce (Only for bug reports) 

1. Create a web.xml with a datasource definition
2. Define the port of the datasource as a placeholder
3. Start the application by passing the environment variables 

## Environment ##

- **Payara Version**: 5.193
- **Edition**: Micro
- **JDK Version**: 8 u181 - Oracle
- **Operating System**: Windows
- **Database**: MySQL

**Comment by OndroMih** [comment]
There are constraints that require an integer value in both web.xml and in the @DataSourceDefinition annotation. These are specified by standards and can't be changed.

There's a workaround to specify the "url" attribute that includes the port number. The "url" attribute can be String and can contain references to multiple env variables, like "jdbc:derby://${ENV=DB_SERVER}:${ENV=DB_SERVER_PORT}/${ENV=DB_NAME}".

We can't modify the standard to allow string values where integer is required. I suggest to close this issue as a simple workaround is available.
