### ISSUE TITLE
Server fails to start -osgi issue

### ISSUE THREAD

**Issue by lennycode** [payara/Payara#4283]
# Description #
----------

 Fresh installation-(I've seen something similar with the docker version, and supposedly it was recently fixed)

C:\payara\bin>asadmin start-domain domain1
Waiting for domain1 to start ..Error starting domain domain1.
The server exited prematurely with exit code 1.
Before it died, it produced the following output:

Launching Payara Server on Felix platform
ERROR: Error parsing system bundle statement.
ERROR: Bundle org.glassfish.hk2.osgi-resource-locator [1] Error starting file:/C:/payara/glassfish/modules/osgi-resource-locator.jar (org.osgi.framework.BundleException: Unable to resolve org.glassfish.hk2.osgi-resource-locator [1](R 1.0): missing requirement [org.glassfish.hk2.osgi-resource-locator [1](R 1.0)] osgi.wiring.package; (&(osgi.wiring.package=org.osgi.framework)(version>=1.5.0)) Unresolved requirements: [[org.glassfish.hk2.osgi-resource-locator [1](R 1.0)] osgi.wiring.package; (&(osgi.wiring.package=org.osgi.framework)(version>=1.5.0))])

## Environment ##

- **Payara Version**: 5.193.1 #badassfish (build 275)
- **Edition**:  Full
- **JDK Version**: JAVA_HOME=C:\Program Files\Java\jdk-12 
- **Operating System**: Windows  10 
- **Database**: N/A

**Comment by chrjohn** [comment]
Don't know if this is related but AFAIK even the Java 11 support on Payara is still work in progress. Did you try with say JDK8?

**Comment by lennycode** [comment]
**Thanks, this solved the issue**.

JDK 8 is the way to go.

If anyone has this issue in the future, I also tried JDK 7 and got this error:
Waiting for domain1 to start .Error starting domain domain1.
The server exited prematurely with exit code 1.
Before it died, it produced the following output:

FATAL ERROR in native method: processing of -javaagent failed
java.lang.UnsupportedClassVersionError: org/glassfish/flashlight/agent/ProbeAgentMain : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:300)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:397)
Exception in thread "main"
Command start-domain failed.
