### ISSUE TITLE
Hibernate Validator Prevents Payara to Restore State After Redeploy

### ISSUE THREAD

**Issue by aosama** [payara/Payara#4346]
#Hibernate Validator Prevents Payara to Restore State After Redeploy #
----------

Give a Jakarta EE 8 web project running within payara micro and while having bean validation annotations and while having keepstate=true configured in payara-web.xml .... the payara is unable to restore session state and throws the below exception.

## Expected Outcome

Expected that payara would be able to restore state after re-deploying.

## Current Outcome

[2019-11-25T03:38:44.996-0500] [] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=33 _ThreadName=payara-executor-service-scheduled-task] [timeMillis: 1574671124996] [levelValue: 900] [[
  Unable to restore sessions for web module [] from previous deployment
org.jboss.weld.exceptions.UnproxyableResolutionException: WELD-001480: Bean type class org.hibernate.validator.internal.engine.ValidatorImpl is not proxyable because it contains a final method public final java.lang.Object org.hibernate.validator.internal.engine.ValidatorImpl.unwrap(java.lang.Class) - ValidatorBean [id=org.hibernate.validator.cdi.internal.ValidatorBean_default].
	at org.jboss.weld.util.Proxies.getUnproxyableClassException(Proxies.java:223)
	at org.jboss.weld.util.Proxies.getUnproxyableTypeException(Proxies.java:178)
	at org.jboss.weld.util.Proxies.getUnproxyableTypesExceptionInt(Proxies.java:190)
	at org.jboss.weld.util.Proxies.getUnproxyableTypesException(Proxies.java:169)
	at org.jboss.weld.bean.proxy.ClientProxyProvider.getClientProxy(ClientProxyProvider.java:213)
	at org.jboss.weld.bean.proxy.util.SerializableClientProxy.readResolve(SerializableClientProxy.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1260)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2078)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
	at java.util.ArrayList.readObject(ArrayList.java:797)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
	at org.apache.catalina.session.StandardSession.readRemainingObject(StandardSession.java:2072)
	at org.apache.catalina.session.StandardSession.readObject(StandardSession.java:1967)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
	at org.apache.catalina.session.StandardSession.deserialize(StandardSession.java:1242)
	at org.apache.catalina.session.StandardManager.readSessions(StandardManager.java:495)
	at com.sun.enterprise.web.WebModule.loadSessions(WebModule.java:1729)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1893)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1596)
	at com.sun.enterprise.web.WebApplication.start(WebApplication.java:107)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:280)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:344)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:574)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:542)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:558)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:554)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:553)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:584)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:576)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:575)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1495)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:120)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1877)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1753)
	at com.sun.enterprise.v3.server.DynamicReloader.reloadApp(DynamicReloader.java:245)
	at com.sun.enterprise.v3.server.DynamicReloader.reloadApps(DynamicReloader.java:169)
	at com.sun.enterprise.v3.server.DynamicReloader.run(DynamicReloader.java:147)
	at com.sun.enterprise.v3.server.DynamicReloadService$1.run(DynamicReloadService.java:166)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]

## Steps to reproduce (Only for bug reports) 

A web project with payara-web.xml having keep state = true and having a class file with @NotNull validation .. then attempt to change the code or xhtml while payaramicro is running. the exception is thrown and payara is unable to restore the session state.

## Environment ##

- **Payara Version**: payara-micro-5.193.1.jar
- **Edition**: Micro
- **JDK Version**: payara-micro-5.193.1.jar
- **Operating System**: Mac 10.15.1 Catalina

**Comment by rdebusscher** [comment]
Hi @aosama 

I could not reproduce your issue, this is what I tried.

I created an application with keep-state defined in the payara-web.xml, a SessionScoped CDI bean which has a property annotated with @NotNull.

I can deploy and redeploy this application on Payara Server (where it is easier to do redeploys and since it is the same codebase this shouldn't make a difference) and the state is kept. No Exception is seen in the log.

So can you give me more information around

- How do you do the redeploy on Payara Micro. Is this through an update of a .reload file in the --domainDir? (Since redeploy on Payara Micro is not a common usecase)
- Are there any configurations made in the web.xml around session state (like <distributable>)
- Are you using a cluster of Payara Micro instances and the DataGrid (Hazelcast) for session storage?
- Is the @NotNull defined in a CDI SessionScoped bean? Is this property 'exposed' on the screen and does this failure only happen after the validation is performed (or also before the NotNull check is done)
- Is the NotNull defined on a specific type, like array or List. Since I see `at java.util.ArrayList.readObject(ArrayList.java:797)` in the stackstrace.

Regards
Rudy

**Comment by aosama** [comment]
Hi @rdebusscher couldnt reproduce in a stand alone project, lets close this issue until i can reproduce in a separate project and upload the code.

**Comment by sgflt** [comment]
We ran into similar issue.

<details>

```
getValue:72, ReentrantMapBackedComputingCache (org.jboss.weld.util.cache)
getCastValue:78, ReentrantMapBackedComputingCache (org.jboss.weld.util.cache)
getClientProxy:211, ClientProxyProvider (org.jboss.weld.bean.proxy)
readResolve:62, SerializableClientProxy (org.jboss.weld.bean.proxy.util)
invoke:-1, GeneratedMethodAccessor340 (jdk.internal.reflect)
invoke:43, DelegatingMethodAccessorImpl (jdk.internal.reflect)
invoke:566, Method (java.lang.reflect)
invokeReadResolve:1265, ObjectStreamClass (java.io)
readOrdinaryObject:2231, ObjectInputStream (java.io)
readObject0:1681, ObjectInputStream (java.io)
defaultReadFields:2490, ObjectInputStream (java.io)
readSerialData:2384, ObjectInputStream (java.io)
readOrdinaryObject:2222, ObjectInputStream (java.io)
readObject0:1681, ObjectInputStream (java.io)
readObject:493, ObjectInputStream (java.io)
readObject:451, ObjectInputStream (java.io)
readObject:1466, HashMap (java.util)
invoke:-1, GeneratedMethodAccessor8 (jdk.internal.reflect)
invoke:43, DelegatingMethodAccessorImpl (jdk.internal.reflect)
invoke:566, Method (java.lang.reflect)
invokeReadObject:1175, ObjectStreamClass (java.io)
readSerialData:2351, ObjectInputStream (java.io)
readOrdinaryObject:2222, ObjectInputStream (java.io)
readObject0:1681, ObjectInputStream (java.io)
readObject:493, ObjectInputStream (java.io)
readObject:451, ObjectInputStream (java.io)
readObject:1466, HashMap (java.util)
invoke:-1, GeneratedMethodAccessor8 (jdk.internal.reflect)
invoke:43, DelegatingMethodAccessorImpl (jdk.internal.reflect)
invoke:566, Method (java.lang.reflect)
invokeReadObject:1175, ObjectStreamClass (java.io)
readSerialData:2351, ObjectInputStream (java.io)
readOrdinaryObject:2222, ObjectInputStream (java.io)
readObject0:1681, ObjectInputStream (java.io)
defaultReadFields:2490, ObjectInputStream (java.io)
readSerialData:2384, ObjectInputStream (java.io)
readOrdinaryObject:2222, ObjectInputStream (java.io)
readObject0:1681, ObjectInputStream (java.io)
readObject:493, ObjectInputStream (java.io)
readObject:451, ObjectInputStream (java.io)
readRemainingObject:2074, StandardSession (org.apache.catalina.session)
readObject:1982, StandardSession (org.apache.catalina.session)
invoke0:-1, NativeMethodAccessorImpl (jdk.internal.reflect)
invoke:62, NativeMethodAccessorImpl (jdk.internal.reflect)
invoke:43, DelegatingMethodAccessorImpl (jdk.internal.reflect)
invoke:566, Method (java.lang.reflect)
invokeReadObject:1175, ObjectStreamClass (java.io)
readSerialData:2351, ObjectInputStream (java.io)
readOrdinaryObject:2222, ObjectInputStream (java.io)
readObject0:1681, ObjectInputStream (java.io)
readObject:493, ObjectInputStream (java.io)
readObject:451, ObjectInputStream (java.io)
deserialize:1234, StandardSession (org.apache.catalina.session)
readSession:289, StoreBase (org.apache.catalina.session)
getSession:566, ReplicationStore (org.glassfish.web.ha.session.management)
getSession:509, ReplicationStore (org.glassfish.web.ha.session.management)
loadFromBackingStore:415, ReplicationStore (org.glassfish.web.ha.session.management)
load:389, ReplicationStore (org.glassfish.web.ha.session.management)
doSwapIn:1045, PersistentManagerBase (org.apache.catalina.session)
swapIn:1005, PersistentManagerBase (org.apache.catalina.session)
findSession:152, ReplicationManagerBase (org.glassfish.web.ha.session.management)
isRequestedSessionIdValid:2747, Request (org.apache.catalina.connector)
parseSessionCookiesId:3542, Request (org.apache.catalina.connector)
postParseRequest:627, CoyoteAdapter (org.apache.catalina.connector)
doService:309, CoyoteAdapter (org.apache.catalina.connector)
service:238, CoyoteAdapter (org.apache.catalina.connector)
call:520, ContainerMapper$HttpHandlerCallable (com.sun.enterprise.v3.services.impl)
service:217, ContainerMapper (com.sun.enterprise.v3.services.impl)
runService:182, HttpHandler (org.glassfish.grizzly.http.server)
doHandle:156, HttpHandler (org.glassfish.grizzly.http.server)
handleRead:218, HttpServerFilter (org.glassfish.grizzly.http.server)
execute:95, ExecutorResolver$9 (org.glassfish.grizzly.filterchain)
executeFilter:260, DefaultFilterChain (org.glassfish.grizzly.filterchain)
executeChainPart:177, DefaultFilterChain (org.glassfish.grizzly.filterchain)
execute:109, DefaultFilterChain (org.glassfish.grizzly.filterchain)
process:88, DefaultFilterChain (org.glassfish.grizzly.filterchain)
execute:53, ProcessorExecutor (org.glassfish.grizzly)
fireIOEvent:524, TCPNIOTransport (org.glassfish.grizzly.nio.transport)
fireIOEvent:89, AbstractIOStrategy (org.glassfish.grizzly.strategies)
run0:94, WorkerThreadIOStrategy (org.glassfish.grizzly.strategies)
access$100:33, WorkerThreadIOStrategy (org.glassfish.grizzly.strategies)
run:114, WorkerThreadIOStrategy$WorkerThreadRunnable (org.glassfish.grizzly.strategies)
doWork:569, AbstractThreadPool$Worker (org.glassfish.grizzly.threadpool)
run:549, AbstractThreadPool$Worker (org.glassfish.grizzly.threadpool)
run:829, Thread (java.lang)
```

</details>


It could be reproduced in JSF bean that is ViewScoped and injects javax.validation.Validator.

After outage of primary instance the session is replicated. If user accesses that bean on different instance, then HA deserialization occurs, but LazyValueHolder for hibernates validator returns Object, that means that the object is not proxiable, which is nonsense, because on primary injection, there is WeldClientProxy made without issues.


ClientProxyProvider:210
```java
        T proxy = beanTypeClosureProxyPool.getCastValue(bean);
        if (proxy == BEAN_NOT_PROXYABLE_MARKER) { // Why there is returned constant instead of some proxy for ValidatorImpl?
            throw Proxies.getUnproxyableTypesException(bean, services());
        }
```

**Comment by sgflt** [comment]
Primary injections calls
 ```java 
    ClientProxyProvider.getClientProxy(final Bean<T> bean, Type requestedType)
```

which has fallback to 

```java

 /*
             *  the bean may have a type that is not proxyable - this is not a problem as long as the unproxyable
             *  type is not in the type closure of the requested type
             *  https://issues.jboss.org/browse/WELD-1052
             */
            proxy = requestedTypeClosureProxyPool.getCastValue(new RequestedTypeHolder(requestedType, bean));
            if (proxy == BEAN_NOT_PROXYABLE_MARKER) {
                throw Proxies.getUnproxyableTypeException(requestedType, services());
            }
```


Session deserialization uses getClientProxy without `requestedType`, which does not have this fallback and fails.

There are possible workarounds:

1. set org.jboss.weld.proxy.ignoreFinalMethods to true (untested)
2. or do not inject javax.validation.Validator into ViewScoped or SessionScoped beans directly
3. or mark field as transient (tested)
