### ISSUE TITLE
Payara admin console doesn't work after enabling secure admin on AdoptOpenJDK

### ISSUE THREAD

**Issue by TeroPihlaja** [payara/Payara#4348]
# Description #
----------

Payara admin console doesn't work after enabling secure admin on AdoptOpenJDK

## Expected Outcome

Payara starts successfully.

## Current Outcome

```
[2019-11-25T13:25:32.506+0200] [Payara 5.193] [WARNING] [] [org.glassfish.grizzly.filterchain.DefaultFilterChain] [tid: _ThreadID=172 _ThreadName=admin-thread-pool::admin-listener(3)] [timeMillis: 1574681132506] [levelValue: 900] [[
  GRIZZLY0013: Exception during FilterChain execution
java.lang.RuntimeException: Could not generate dummy secret
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1550)
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:544)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:818)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:782)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at org.glassfish.grizzly.ssl.SSLUtils.sslEngineUnwrap(SSLUtils.java:441)
	at org.glassfish.grizzly.ssl.SSLConnectionContext.unwrap(SSLConnectionContext.java:170)
	at org.glassfish.grizzly.ssl.SSLUtils.handshakeUnwrap(SSLUtils.java:268)
	at org.glassfish.grizzly.ssl.SSLBaseFilter.doHandshakeStep(SSLBaseFilter.java:649)
	at org.glassfish.grizzly.ssl.SSLBaseFilter.doHandshakeStep(SSLBaseFilter.java:598)
	at org.glassfish.grizzly.ssl.SSLBaseFilter.handleRead(SSLBaseFilter.java:310)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:208)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Could not generate dummy secret
	at sun.security.ssl.RSAClientKeyExchange.<init>(RSAClientKeyExchange.java:200)
	at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:265)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1062)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:995)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:992)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1490)
	at org.glassfish.grizzly.ssl.SSLUtils.executeDelegatedTask(SSLUtils.java:250)
	at org.glassfish.grizzly.ssl.SSLBaseFilter.doHandshakeStep(SSLBaseFilter.java:683)
	... 23 more
Caused by: java.security.NoSuchAlgorithmException: Cannot find any provider supporting RSA/ECB/PKCS1Padding
	at javax.crypto.Cipher.getInstance(Cipher.java:539)
	at sun.security.ssl.JsseJce.getCipher(JsseJce.java:208)
	at sun.security.ssl.RSAClientKeyExchange.<init>(RSAClientKeyExchange.java:143)
	... 31 more
]]
```

## Steps to reproduce (Only for bug reports) 

1. Install AdoptOpenJDK Java on Windows server.
2. Install Payara 5.193.1
3. Enable secure admin
4. Restart domain
5. Try to access the domain admin

## Environment ##

- **Payara Version**: 5.193.1
- **Edition**: Full
- **JDK Version**: AdoptOpenJDK jdk8u202-b08, jdk8u212-b04, jdk8u222-b10, jdk8u232-b09
- **Operating System**: Windows Server 2019

**Note: Works with AdoptOpenJDK jdk8u181-b13**

**Comment by rdebusscher** [comment]
Hi,

I cannot reproduce the problem on my machine (Mac) with the AdoptOpenJDK version

>Rudys-MacBook-Pro-2:bin rubus$ java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)

The `NoSuchAlgorithmException: Cannot find any provider supporting RSA/ECB/PKCS1Padding` indicates that it is a JDK issue. Are there any changes made in the `/conf/security/java.security` file?

Regards
Rudy

**Comment by rdebusscher** [comment]
Any information on this?

**Comment by rdebusscher** [comment]
Closing issue as no response received.
