### ISSUE TITLE
Rolling update leaves modules disabled

### ISSUE THREAD

**Issue by ratcashdev** [payara/Payara#438]
Following #433, i deployed the same WAR twice to an application server, using the following commands:
```
asadmin deploy --name=myproject /home/jenkins/myproject.war
asadmin deploy --enabled=false --name=myproject:4 /home/jenkins/myproject.war
```
so far so good. All the RESTful web services work as indended.
```
asadmin enable myproject:4
```
At this point MOST of the web services work. However, at least one that is using a `Completeable Future` using a `ManagedThreadFactory` and `@Suspended AsyncResponse` fails without any trace of the problem. The only hint is the following message in the logs:
```
[2015-09-14T15:51:25.770+0200] [Payara 4.1] [SEVERE] [] [org.glassfish.enterprise.concurrent] [tid: _ThreadID=175 _ThreadName=concurrent/__defaultManagedThreadFactory-Thread-1] [timeMillis: 1442238685770] [levelValue: 1000] [[
  java.lang.IllegalStateException: Module myproject is disabled]]
```
Checking the management UI, and clicking on the application details, it can be seen, that for app myproject:4 there is no module listed, whatsoever, yet it is shown as active. At this moment the logs say:
```
[2015-09-14T15:58:42.240+0200] [Payara 4.1] [INFO] [] [org.glassfish.admingui] [tid: _ThreadID=71 _ThreadName=admin-listener(2)] [timeMillis: 1442240423484] [levelValue: 800] [[
  Exception in getSubComponents().null]]
```

The following also fails (initial deployment, without any previous version being present on the application server after a fresh start:
```
asadmin deploy --name=myproject:4 /home/jenkins/myproject.war
```
The logs shows the following:
```
[2015-09-14T15:58:42.240+0200] [Payara 4.1] [SEVERE] [] [javax.enterprise.web] [tid: _ThreadID=50 _ThreadName=admin-listener(2)] [timeMil
lis: 1442239122240] [levelValue: 1000] [[
  WebModule[]StandardWrapper.Throwable
java.lang.NullPointerException
        at org.glassfish.jersey.gf.ejb.internal.EjbComponentProvider.registerEjbInterceptor(EjbComponentProvider.java:166)
        at org.glassfish.jersey.gf.ejb.internal.EjbComponentProvider.bind(EjbComponentProvider.java:250)
        at org.glassfish.jersey.server.ApplicationHandler.bindWithComponentProvider(ApplicationHandler.java:982)
        at org.glassfish.jersey.server.ApplicationHandler.bindProvidersAndResources(ApplicationHandler.java:911)
        at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:495)
        at org.glassfish.jersey.server.ApplicationHandler.access$500(ApplicationHandler.java:166)
```

However, the following works (note the lack of the version):
```
asadmin deploy --name=myproject /home/jenkins/myproject.war
```

All tests done on Payara 4.1.152.1

**Comment by ratcashdev** [comment]
Update: It seem Payara 4.1.153 is better in this regard.
```
asadmin deploy --name=myproject:4 /home/jenkins/myproject.war
```
works as expected
