### ISSUE TITLE
Liquibase via CDI does not work anymore after upgrading to Payara 5.194

### ISSUE THREAD

**Issue by mydeadlyvenoms** [payara/Payara#4413]
# Description #
----------

Liquibase via CDI does not work anymore after upgrading to Payara `5.194`. If switching back to Payara `5.193` everything works as intended.

## Current Outcome
```
Exception during lifecycle processing
org.glassfish.deployment.common.DeploymentException: CDI deployment failure:WELD-000049: Unable to invoke public void liquibase.integration.cdi.CDILiquibase.onStartup() on liquibase.integration.cdi.CDILiquibase@28d4c7ec -- WELD-000049: Unable to invoke public void liquibase.integration.cdi.CDILiquibase.onStartup() on liquibase.integration.cdi.CDILiquibase@28d4c7ec
	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:38)
	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:505)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:93)
	at org.glassfish.weld.WeldDeployer.processApplicationLoaded(WeldDeployer.java:514)
	at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:425)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:325)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:531)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:538)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:558)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:554)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:553)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:584)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:576)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:575)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1496)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:120)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1878)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1754)
	at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:137)
	at fish.payara.micro.impl.PayaraMicroImpl.deployAll(PayaraMicroImpl.java:1594)
	at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1055)
	at fish.payara.micro.impl.PayaraMicroImpl.create(PayaraMicroImpl.java:211)
	at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:200)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:50)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:114)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:73)
	at fish.payara.micro.boot.PayaraMicroLauncher.create(PayaraMicroLauncher.java:87)
	at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:71)
	at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:397)
]]
```

### pom.xml
```
        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
            <version>3.8.4</version>
            <exclusions>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-classic</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-cdi</artifactId>
            <version>3.8.4</version>
            <exclusions>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-classic</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

### Liquibase Class
```
@Dependent
public class Liquibase {

    @Resource(name = "java:app/blub/DataSource")
    private DataSource dataSource;

    @Produces
    @LiquibaseType
    public CDILiquibaseConfig createConfig() {
        CDILiquibaseConfig cdiLiquibaseConfig = new CDILiquibaseConfig();
        cdiLiquibaseConfig.setChangeLog("config/liquibase/master.xml");
        return cdiLiquibaseConfig;
    }

    @Produces
    @LiquibaseType
    public DataSource createDataSource() {
        return dataSource;
    }

    @Produces
    @LiquibaseType
    public ResourceAccessor create() {
        return new ClassLoaderResourceAccessor(getClass().getClassLoader());
    }

}
```

## Environment ##

- **Payara Version**: 5.194
- **Edition**: Micro
- **JDK Version**: 1.8.0_192 - OpenJDK 
- **Operating System**: Mac
- **Database**: PostGres

**Comment by rdebusscher** [comment]
Hi Damiano,

I could not reproduce the problem with the information you provided.

I have added the dependencies to the POM file and created the class.

I see in the log that Liquibase tries to do his work.

```
 java:app/blub/DataSource@javax.sql.DataSource@ resolved as: jndi: java:app/blub/DataSource@res principal: null@mail: null
No Runtime properties
Database Vendor : null
Create Tables at Deploy : false
Delete Tables at Undeploy : false

```
So can you create a complete minimal reproducer and link it to this issue?

I also see this in the log file, which means that there is aCDI error in the Liquibase CDI extension.

```
WELD-001473: javax.enterprise.inject.spi.Bean implementation liquibase.integration.cdi.CDIBootstrap$1@556a6320 declared a normal scope but does not implement javax.enterprise.inject.spi.PassivationCapable. It won't be possible to inject this bean into a bean with a passivating scope (@SessionScoped, @ConversationScoped). This can be fixed by assigning the Bean implementation a unique id by implementing the PassivationCapable interface.
```

Regards
Rudy

**Comment by mydeadlyvenoms** [comment]
Hi Rudy

Thank you very much for your response, your investigations gave me the missing hint.
The problem is actually here `@Resource(name = "java:app/blub/DataSource")`, this does not work anymore when upgrading to `5.194`. I had to replace it with `@Resource(lookup = "java:app/blub/DataSource")` now everything seems to work. 

But I can actually not explain why. 

Best regards,
Damiano

**Comment by rdebusscher** [comment]
Hi Damiano,

There is a difference between name() and lookup() for defining the JNDI name. (and I didn't spot it initially in your example)

The value of _name_ is prepended with **java:comp/env/** and _lookup_ is taken as such.

The Payara code is adapted [here](https://github.com/payara/Payara/pull/4210) in order to pass the Jakarta EE TCK (the behaviour in 5.193 and earlier was incorrect as it also supported a complete JNDI name in the name() member).

Rudy

**Comment by mydeadlyvenoms** [comment]
Thank you @rdebusscher  for the explanation.
