### ISSUE TITLE
PayaraGeneratedCacheKey cannot be cast to class java.lang.String

### ISSUE THREAD

**Issue by ThomasSousa96** [payara/Payara#4431]
# Description #
----------

Using JCache with Payara Micro throws a cast error when use a CacheLoader instance with same key type of the cached service.

## Expected Outcome

That the server support a CacheLoader instance with same key type of the cached service.  

## Current Outcome

```java
javax.cache.integration.CacheLoaderException: Exception in CacheLoader during load
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.readThroughCache(AbstractCacheRecordStore.java:998)
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.get(AbstractCacheRecordStore.java:1158)
	at com.hazelcast.cache.impl.operation.CacheGetOperation.run(CacheGetOperation.java:50)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
Caused by: java.lang.ClassCastException: class fish.payara.cdi.jsr107.implementation.PayaraGeneratedCacheKey cannot be cast to class java.lang.String (fish.payara.cdi.jsr107.implementation.PayaraGeneratedCacheKey is in unnamed module of loader fish.payara.micro.boot.loader.ExplodedURLClassloader @67b64c45; java.lang.String is in module java.base of loader 'bootstrap')
        ...
	at fish.payara.nucleus.hazelcast.contextproxy.CompleteConfigurationProxy$1$CacheLoaderImpl.load(CompleteConfigurationProxy.java:95)
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.readThroughCache(AbstractCacheRecordStore.java:995)
	... 8 more
```

## Steps to reproduce (Only for bug reports) 

1. Create a test service

```java
@CacheResult
public String get(@CacheKey String key) {
```

2. Implement a CacheLoader/CacheWrite with same types of the `get` method (above code):
 
```java
implements CacheLoader<String, String>, CacheWriter<String, String>
```

3. Create a cache with a factory that create instances of the class create in the above step:

```java
cacheManager.createCache("test", new MutableConfiguration<String, String>()
				.setExpiryPolicyFactory(expiryPolicyfactory)
				.setReadThrough(true)
				.setCacheLoaderFactory(testStoreFactory)
```

## Environment ##

- **Payara Version**: 5.194
- **Edition**: Micro
- **JDK Version**: 8 - OpenJDK
- **Operating System**: Linux
- **Database**: N/A

**Comment by ThomasSousa96** [comment]
I found the problem. Is necessary use a subtype of `GeneratedCacheKey` as key. This class represents the composing of all parameters used as key of the cache.

Define the `cacheKeyGenerator` in the cached method. The `cacheKeyGenerator` is a factory that create instances of a subtype of `GeneratedCacheKey`.

```java
@CacheResult(name = "myCache", cacheKeyGenerator = MyCacheKeyGenerator.class)
public String get(@CacheKey String key) {
```

The class that implements CacheLoader/CacheWrite must be use a subtype of `GeneratedCacheKey` as key.

```java
implements CacheLoader<MyGeneratedCacheKey, String>, CacheWriter<MyGeneratedCacheKey, String>
```
