### ISSUE TITLE
Payara full 5.194 does not start on JDK 13

### ISSUE THREAD

**Issue by sgerr** [payara/Payara#4434]
# Description #
----------

Payara Server full 5.194 does not start on JDK 13. The same time it stars fine on JDK 11 and JDK 12.

## Expected Outcome

Payara Server Full 5.194 started.

## Current Outcome

**Lot of " Unresolved requirements" messages at OSGI stack, like that:**

```
[root@lab-dev-core ~]# /opt/payara5/bin/asadmin start-domain
Waiting for domain1 to start ..Error starting domain domain1.
The server exited prematurely with exit code 1.
Before it died, it produced the following output:

Launching Payara Server on Felix platform
ERROR: Error parsing system bundle statement.
ERROR: Bundle org.glassfish.hk2.osgi-resource-locator [1] Error starting file:/opt/payara5/glassfish/modules/osgi-resource-locator.jar (org.osgi.framework.BundleException: Unable to resolve org.glassfish.hk2.osgi-resource-locator [1](R 1.0): missing requirement [org.glassfish.hk2.osgi-resource-locator [1](R 1.0)] osgi.wiring.package; (&(osgi.wiring.package=org.osgi.framework)(version>=1.5.0)) Unresolved requirements: [[org.glassfish.hk2.osgi-resource-locator [1](R 1.0)] osgi.wiring.package; (&(osgi.wiring.package=org.osgi.framework)(version>=1.5.0))])
ERROR: Bundle org.objectweb.asm.tree.analysis [35] Error starting file:/opt/payara5/glassfish/modules/asm-analysis.jar (org.osgi.framework.BundleException: Unable to resolve org.objectweb.asm.tree.analysis [35](R 35.0): missing requirement [org.objectweb.asm.tree.analysis [35](R 35.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=1.5.0)) Unresolved requirements: [[org.objectweb.asm.tree.analysis [35](R 35.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=1.5.0))])
ERROR: Bundle org.glassfish.hk2.class-model [67] Error starting file:/opt/payara5/glassfish/modules/class-model.jar (org.osgi.framework.BundleException: Unable to resolve org.glassfish.hk2.class-model [67](R 67.0): missing requirement [org.glassfish.hk2.class-model [67](R 67.0)] osgi.wiring.package; (&(osgi.wiring.package=org.objectweb.asm.signature)(version>=7.1.0)(!(version>=8.0.0))) [caused by: Unable to resolve org.objectweb.asm [172](R 172.0): missing requirement [org.objectweb.asm [172](R 172.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=1.5.0))] Unresolved requirements: [[org.glassfish.hk2.class-model [67](R 67.0)] osgi.wiring.package; (&(osgi.wiring.package=org.objectweb.asm.signature)(version>=7.1.0)(!(version>=8.0.0)))])
ERROR: Bundle fish.payara.server.internal.hk2.config [124] Error starting file:/opt/payara5/glassfish/modules/hk2-config.jar (org.osgi.framework.BundleException: Unable to resolve fish.payara.server.internal.hk2.config [124](R 124.0): missing requirement [fish.payara.server.internal.hk2.config [124](R 124.0)] osgi.wiring.package; (osgi.wiring.package=javax.management) Unresolved requirements: [[fish.payara.server.internal.hk2.config [124](R 124.0)] osgi.wiring.package; (osgi.wiring.package=javax.management)])
ERROR: Bundle org.objectweb.asm.util [135] Error starting file:/opt/payara5/glassfish/modules/asm-util.jar (org.osgi.framework.BundleException: Unable to resolve org.objectweb.asm.util [135](R 135.0): missing requirement [org.objectweb.asm.util [135](R 135.0)] osgi.wiring.package; (&(osgi.wiring.package=org.objectweb.asm.signature)(version>=7.2.0)(!(version>=8.0.0))) [caused by: Unable to resolve org.objectweb.asm [172](R 172.0): missing requirement [org.objectweb.asm [172](R 172.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=1.5.0))] Unresolved requirements: [[org.objectweb.asm.util [135](R 135.0)] osgi.wiring.package; (&(osgi.wiring.package=org.objectweb.asm.signature)(version>=7.2.0)(!(version>=8.0.0)))])
ERROR: Bundle org.glassfish.hk2.runlevel [162] Error starting file:/opt/payara5/glassfish/modules/hk2-runlevel.jar (org.osgi.framework.BundleException: Unable to resolve org.glassfish.hk2.runlevel [162](R 162.0): missing requirement [org.glassfish.hk2.runlevel [162](R 162.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=1.8)) Unresolved requirements: [[org.glassfish.hk2.runlevel [162](R 162.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=1.8))])
ERROR: Bundle org.objectweb.asm [172] Error starting file:/opt/payara5/glassfish/modules/asm.jar (org.osgi.framework.BundleException: Unable to resolve org.objectweb.asm [172](R 172.0): missing requirement [org.objectweb.asm [172](R 172.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=1.5.0)) Unresolved requirements: [[org.objectweb.asm [172](R 172.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=1.5.0))])
ERROR: Bundle fish.payara.server.internal.hk2.config-types [179] Error starting file:/opt/payara5/glassfish/modules/config-types.jar (org.osgi.framework.BundleException: Unable to resolve fish.payara.server.internal.hk2.config-types [179](R 179.0): missing requirement [fish.payara.server.internal.hk2.config-types [179](R 179.0)] osgi.wiring.package; (&(osgi.wiring.package=org.glassfish.hk2.utilities)(version>=2.6.0)(!(version>=3.0.0))) [caused by: Unable to resolve org.glassfish.hk2.api [209](R 209.0): missing requirement [org.glassfish.hk2.api [209](R 209.0)] osgi.wiring.package; (&(osgi.wiring.package=javax.inject)(version>=1.0.0)(!(version>=2.0.0))) [caused by: Unable to resolve org.glassfish.hk2.external.jakarta.inject [323](R 323.0): missing requirement [org.glassfish.hk2.external.jakarta.inject [323](R 323.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=1.8))]] Unresolved requirements: [[fish.payara.server.internal.hk2.config-types [179](R 179.0)] osgi.wiring.package; (&(osgi.wiring.package=org.glassfish.hk2.utilities)(version>=2.6.0)(!(version>=3.0.0)))])

...

ERROR: Bundle org.objectweb.asm.tree [360] Error starting file:/opt/payara5/glassfish/modules/asm-tree.jar (org.osgi.framework.BundleException: Unable to resolve org.objectweb.asm.tree [360](R 360.0): missing requirement [org.objectweb.asm.tree [360](R 360.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=1.5.0)) Unresolved requirements: [[org.objectweb.asm.tree [360](R 360.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=1.5.0))])
org.osgi.framework.BundleException: Exported package names cannot be zero length.
        at org.apache.felix.framework.util.manifestparser.ManifestParser.normalizeExportClauses(ManifestParser.java:865)
        at org.apache.felix.framework.util.manifestparser.ManifestParser.<init>(ManifestParser.java:217)
        at org.apache.felix.framework.ExtensionManager$ExtensionManagerRevision.update(ExtensionManager.java:982)
        at org.apache.felix.framework.ExtensionManager$ExtensionManagerRevision.access$000(ExtensionManager.java:885)
        at org.apache.felix.framework.ExtensionManager.updateRevision(ExtensionManager.java:378)
        at org.apache.felix.framework.Felix.init(Felix.java:748)
        at org.apache.felix.framework.Felix.init(Felix.java:641)
        at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiFrameworkLauncher$1.run(OSGiFrameworkLauncher.java:93)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.felix.framework.URLHandlers (file:/opt/payara5/glassfish/osgi/felix/bin/felix.jar) to constructor sun.net.www.protocol.file.Handler()
WARNING: Please consider reporting this to the maintainers of org.apache.felix.framework.URLHandlers
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Jan 15, 2020 9:26:10 AM com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner createBundleProvisioner
INFO: Create bundle provisioner class = class com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner.
org.osgi.framework.BundleException: Unable to resolve org.glassfish.hk2.osgi-resource-locator [1](R 1.0): missing requirement [org.glassfish.hk2.osgi-resource-locator [1](R 1.0)] osgi.wiring.package; (&(osgi.wiring.package=org.osgi.framework)(version>=1.5.0)) Unresolved requirements: [[org.glassfish.hk2.osgi-resource-locator [1](R 1.0)] osgi.wiring.package; (&(osgi.wiring.package=org.osgi.framework)(version>=1.5.0))]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4368)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2281)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.base/java.lang.Thread.run(Thread.java:830)

...

Caused by: org.glassfish.embeddable.GlassFishException: No GlassFishRuntime available
        at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishRuntimeBuilder.getGlassFishRuntime(OSGiGlassFishRuntimeBuilder.java:208)
        at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishRuntimeBuilder.build(OSGiGlassFishRuntimeBuilder.java:168)
        ... 9 more
```

## Steps to reproduce (Only for bug reports) 

Environment: fresh copy of (Oracle Linux 8 + Oracle JDK 13) or (Fedora 30 + OpenJDK 13).

Download Payara Server Full, unzip it and invoke:

`asadmin start-domain`

## Environment ##

- **Payara Version**: 5.194
- **Edition**: Full
- **JDK Version**:  13 Oracle or OpenJDK
- **Operating System**: Linux

**Comment by chrjohn** [comment]
I think this is "expected" at the moment. Only JDK11 is supported officially.
https://blog.payara.fish/jdk-11-support-available-in-payara-platform-194

**Comment by sgerr** [comment]
@chrjohn, 11**+** is told: https://www.payara.fish/support/openjdk-support/

**Comment by chrjohn** [comment]
Yes, if the following condition is met:

> OpenJDK Support Benefits Through Your Payara Enterprise Contract

At least that's how I understand this. But I guess sooner ot later this will be merged into the community releases.

Maybe someone from Payara team can confirm.

**Comment by sgerr** [comment]
Yes, no problem, just consider this issue as informational, all the more so 5.194 starts fine on JDK 11 and 12.

**Comment by rdebusscher** [comment]
Hi @sgerr 

The page you refer to is about the JDK support, not the Payara support.

As Payara Customer, you also get support for JDK issues when you encounter a problem with the JVM you are using for running Payara or related to the apps running in Payara (like a standalone client for example).

Payara Platform itself is only guaranteed to run on JDK 11. Those standalone clients can maybe run on another version, including JDK 13.

@chrjohn, there is also no Customer only version (in the sense that there is a separate branch with  additional features), except that there is a monthly release for customers and a stability release stream.(see https://www.payara.fish/support/release-streams/)
So all the code we have is released every 3 months in a community release (this might change in the future as customers receive specific features which are not available in the community release)

Customer support is about getting help for your environment/application (knowledge, questions, ...), high priority in fixing bugs you might encounter, implementation of feature requests, Azul Zulu support, etc ...
Also this might change in the future.

Regards
Rudy

**Comment by chrjohn** [comment]
Hi @rdebusscher , thanks for the clarification!

**Comment by sgerr** [comment]
@rdebusscher, got it, thanks.

are there any plans to test across OpenJDK 13?

**Comment by rdebusscher** [comment]
No, as our main goal are the LTS versions.
