### ISSUE TITLE
Possible NPE in request tracing during startup

### ISSUE THREAD

**Issue by jbee** [payara/Payara#4466]
When starting the server with request tracing already enabled a NPE sometimes happens. It might be related to trying to open admin console in the midst of startup.
```
java.lang.NullPointerException
	at fish.payara.nucleus.requesttracing.RequestTracingService.shouldStartTrace(RequestTracingService.java:469)
	at fish.payara.nucleus.requesttracing.RequestTracingService.startTrace(RequestTracingService.java:413)
	at fish.payara.nucleus.requesttracing.RequestTracingService.startTrace(RequestTracingService.java:409)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:184)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
```

Which is this line 
```java
if (executionOptions.getApplicationsOnlyEnabled() == true
```
Pretty sure `executionOptions` is `null` here and some sort of null-check should be used to fix the issue.

**Comment by rdebusscher** [comment]
I created `CUSTCOM-180` to investigate this further.
