### ISSUE TITLE
Payara 5 with DMN and de.odysseus.juel

### ISSUE THREAD

**Issue by danielstrigel** [payara/Payara#4540]
# Description #
We try to migrate from Payara 4 to Payara Server 5.194 #badassfish (build 327)

We use DMN Tabels org/camunda/bpm/dmn/camunda-engine-dmn/7.12.0

`org.camunda.bpm.dmn
imports de.odysseus.juel`

juel-api-2.2.7.jar
juel-impl-2.2.7.jar
juel-spi-2.2.7.jar

## Current Outcome
If we put the juel jars into payara-5.194\glassfish\domains\domain1\lib OR deploy it within our .war we get the following Exception and Payara doesn’t start anymore.

`[[2020-01-24]T10:22:28.024+0100] [Payara 5.194] [SCHWERWIEGEND] [AS-WEB-CORE-00175] [javax.enterprise.web.core] [tid: _ThreadID=157 _ThreadName=Thread-14] [timeMillis: 1579857748024] [levelValue: 1000] [[ Exception during cleanup after start failed org.apache.catalina.LifecycleException: Manager has not yet been started at org.apache.catalina.session.StandardManager.stop(StandardManager.java:868) at org.apache.catalina.core.StandardContext.stop(StandardContext.java:5940) at com.sun.enterprise.web.WebModule.stop(WebModule.java:648) at org.apache.catalina.core.StandardContext.start(StandardContext.java:5756) at com.sun.enterprise.web.WebModule.start(WebModule.java:619) at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:956) at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:939) at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:684) at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1868) at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1604) at com.sun.enterprise.web.WebApplication.start(WebApplication.java:107) at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123) [[2020-01-24]T10:22:28.030+0100] [Payara 5.194] [WARNUNG] [] [javax.enterprise.web] [tid: _ThreadID=157 _ThreadName=Thread-14] [timeMillis: 1579857748030] [levelValue: 900] [[ java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: java.lang.RuntimeException: java.lang.NullPointerException java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: java.lang.RuntimeException: java.lang.NullPointerException at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:960) at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:939) at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:684) at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1868) at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1604) at com.sun.enterprise.web.WebApplication.start(WebApplication.java:107) at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123) Critical error during deployment: java.lang.NullPointerException at javax.el.CompositeELResolver.add(CompositeELResolver.java:76) at com.sun.faces.el.DemuxCompositeELResolver.addRootELResolver(DemuxCompositeELResolver.java:118) at com.sun.faces.el.ELUtils.addEL3_0_Resolvers(ELUtils.java:312) at com.sun.faces.el.ELUtils.buildFacesResolver(ELUtils.java:234) at com.sun.faces.application.ApplicationAssociate.initializeELResolverChains(ApplicationAssociate.java:467) at com.sun.faces.application.applicationimpl.ExpressionLanguage.performOneTimeELInitialization(ExpressionLanguage.java:184) at com.sun.faces.application.applicationimpl.ExpressionLanguage.getELResolver(ExpressionLanguage.java:120) at com.sun.faces.application.ApplicationImpl.getELResolver(ApplicationImpl.java:213) at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:225) at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:5165) at com.sun.enterprise.web.WebModule.contextListenerStart(WebModule.java:683) at org.apache.catalina.core.StandardContext.start(StandardContext.java:5738) at com.sun.enterprise.web.WebModule.start(WebModule.java:619) at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:956) at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:939) at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:684) at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1868) at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1604) at com.sun.enterprise.web.WebApplication.start(WebApplication.java:107) at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123) Startup of context failed due to previous errors]]`

If we exclude the lib in our pom.xml our application is not working:
```
<dependency>
<groupId>org.camunda.bpm.dmn </groupId>
<artifactId>camunda-engine-dmn</artifactId>
<version>7.12.0</version>
<exclusions>
<exclusion>
<groupId>de.odysseus.juel</groupId>
<artifactId>juel-api</artifactId>
</exclusion>
<exclusion>
<groupId>de.odysseus.juel</groupId>
<artifactId>juel-spi</artifactId>
</exclusion>
<exclusion>
<groupId>de.odysseus.juel</groupId>
<artifactId>juel-impl</artifactId>
</exclusion>
</exclusions>
</dependency>
```
------------------
```
Caused by: java.lang.Exception: java.lang.NoClassDefFoundError: de/odysseus/el/util/SimpleContext
at com.sun.ejb.containers.interceptors.CallbackInvocationContext.proceed(CallbackInvocationContext.java:208)
at org.glassfish.jersey.gf.ejb.internal.EjbComponentInterceptor.inject(EjbComponentInterceptor.java:50)
at sun.reflect.GeneratedMethodAccessor429.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:153)
at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.init(SystemInterceptorProxy.java:125)
at sun.reflect.GeneratedMethodAccessor368.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.sun.ejb.containers.interceptors.CallbackInterceptor.intercept(InterceptorManager.java:998)
at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
at com.sun.ejb.containers.interceptors.CallbackInvocationContext.proceed(CallbackInvocationContext.java:204)
at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
at sun.reflect.GeneratedMethodAccessor327.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.sun.ejb.containers.interceptors.CallbackInterceptor.intercept(InterceptorManager.java:998)
at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:417)
at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:380)
at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:2045)
at com.sun.ejb.containers.StatelessSessionContainer.createStatelessEJB(StatelessSessionContainer.java:466)
… 110 more
Caused by: java.lang.NoClassDefFoundError: de/odysseus/el/util/SimpleContext
at com.xxxx.antos.adapter.dmn.DmnLoader.init(DmnLoader.java:36)
at com.xxxx.antos.calc.constraint.component.AbstractConstraint.init(AbstractConstraint.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.sun.ejb.containers.interceptors.BeanCallbackInterceptor.intercept(InterceptorManager.java:1047)
at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
at com.sun.ejb.containers.interceptors.CallbackInvocationContext.proceed(CallbackInvocationContext.java:204)
… 133 more
Caused by: java.lang.ClassNotFoundException: de.odysseus.el.util.SimpleContext
at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1687)
at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1528)
… 142 more
]]

```
## Steps to reproduce (Only for bug reports) 
Just put the jar into payara-5.194\glassfish\domains\domain1\lib and start payara

## Environment ##

- **Payara Version**: 5.194
- **Edition**: Full

**Comment by fturizo** [comment]
@danielstrigel, it seems that the reported error is caused by a missing library in your domain and/or application. Can you provide a full reproducer project that we can use to evidence the error you are reporting? Otherwise we are afraid that we can't be of much help.

**Comment by danielstrigel** [comment]
Put the jar into payara-5.194\glassfish\domains\domain1\lib and start payara
https://repo1.maven.org/maven2/de/odysseus/juel/juel-impl/2.2.7/juel-impl-2.2.7.jar
https://repo1.maven.org/maven2/de/odysseus/juel/juel-api/2.2.7/juel-api-2.2.7.jar
https://repo1.maven.org/maven2/de/odysseus/juel/juel-spi/2.2.7/juel-spi-2.2.7.jar

How to configure the module / class loading so a web app can use these jars?

**Comment by danielstrigel** [comment]
@fturizo Is there something new? Were you able to reproduce this behavior?

**Comment by fturizo** [comment]
@danielstrigel, unfortunately I'm not encountering any error at all when running the reproducer test case you mentioned (adding the referenced JAR files to a default domain installation's `lib` folder). From the way you are phrasing the test scenario, we'd need a WAR file to deploy locally and attest the classloading issue. Please prepare a sample WAR application to deploy and share its code repository with us to review it in order to provide further assistance.

**Comment by danielstrigel** [comment]
@fturizo You need to start https://localhost:4848/common/index.jsf

With this Dockerfile I get the error:
`
FROM payara/server-full:5.194

RUN wget https://repo.maven.apache.org/maven2/de/odysseus/juel/juel-spi/2.2.7/juel-spi-2.2.7.jar -P ${PAYARA_DIR}/glassfish/domains/production/lib/
RUN wget --no-verbose https://repo.maven.apache.org/maven2/de/odysseus/juel/juel-impl/2.2.7/juel-impl-2.2.7.jar -P ${PAYARA_DIR}/glassfish/domains/production/lib/
RUN wget --no-verbose https://repo.maven.apache.org/maven2/de/odysseus/juel/juel-api/2.2.7/juel-api-2.2.7.jar -P ${PAYARA_DIR}/glassfish/domains/production/lib
`
start https://localhost:4848/common/index.jsf

**Comment by fturizo** [comment]
Apologies, @danielstrigel but I cannot reproduce the error with release 5.201. Neither a local startup  of the default `production` domain nor in Docker produces any errors. Can you please try to test your scenario using release 5.201 instead of 5.194. I'm afraid that without a clear reproducer we can't provide any assistance.

**Comment by danielstrigel** [comment]
Hello @fturizo, with the latest version 5.201 the error does not occur anymore. Thanks for your support!
