### ISSUE TITLE
Exception in server.log for payara logback libs

### ISSUE THREAD

**Issue by peterpz1** [payara/Payara#4567]
# Description #
----------

When you have installed logback libs from here:
https://github.com/goodees/goodees/tree/master/payara-logback

## Expected Outcome

No exceptions in server.log during the domain start.

## Current Outcome

We see two exceptions, they disappear when the payara logback libs are deleted from server:
```
2020-03-09 13:17:30 WARNING [org.glassfish.kernel.event.EventsImpl send] Exception while dispatching an event
java.lang.NullPointerException
	at fish.payara.ejb.http.admin.EjbInvokerService.event(EjbInvokerService.java:93)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:525)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.processApplication(ApplicationLoaderService.java:413)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.postConstruct(ApplicationLoaderService.java:246)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:303)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

2020-03-09 13:17:30 INFO   [com.sun.enterprise.v3.server.ApplicationLoaderService processApplication] Loading application payara-logback-delegation done in 2,395 ms
2020-03-09 13:17:30 INFO   [org.hibernate.validator.internal.util.Version <clinit>] HV000001: Hibernate Validator 6.0.16.Final
2020-03-09 13:17:30 WARNING [org.glassfish.kernel.event.EventsImpl send] Exception while dispatching an event
java.lang.NullPointerException
	at fish.payara.ejb.http.admin.EjbInvokerService.event(EjbInvokerService.java:93)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:525)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.processApplication(ApplicationLoaderService.java:413)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.postConstruct(ApplicationLoaderService.java:246)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:303)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

2020-03-09 13:17:30 INFO   [com.sun.enterprise.v3.server.ApplicationLoaderService processApplication] Loading application payara-logback-access done in 259 ms
```
## Steps to reproduce (Only for bug reports) 

1 -**  Start the domain

    ./asadmin start-domain payaradomain

2 -**  Install payara libs as described in the https://github.com/goodees/goodees/tree/master/payara-logback

3 -**  Restart domain and check server.log

-->

## Context (Optional)

The issue was not present in 5.193.1 version and seems to be 5.194 regression.

## Environment ##

- **Payara Version**: 5.194
- **Edition**: Full
- **JDK Version**: 11
- **Operating System**: Linux
- **Database**: n/a

**Comment by svendiedrichsen** [comment]
Shouldn't this bug be posted to https://github.com/goodees/goodees?

**Comment by peterpz1** [comment]
> 
> 
> Shouldn't this bug be posted to https://github.com/goodees/goodees?

I don't think so. The Payara server is one of the most Jakarta EE developed servers currently. So server with so huge aspirations should have official info how to add logback logger into it (the log4j successor). And I don't think that there is one. So the goodees produced something 2 years ago, they are not developing it and we are left with no official way how to add logback into the server? Please provide the official way and we will ditch this goodees product. I tried myself adding the raw logback and slf4j libraries about 1 year ago and I wasn't successfull (everything worked until app was redeployed - then logs disappeared). The only proper working way was this goodees product, which now seems to produce an exception.

**Comment by chrjohn** [comment]
@peterpz1 Did you check if it has to do with https://github.com/goodees/goodees/issues/5 ?

> The system property java.ext.dirs is no longer supported. This also means that JAR files within the <payara-home>/glassfish/domains/<domain>/lib/ext directory are no longer placed on the classpath. The <payara-home>/glassfish/domains/<domain>/lib directory is the preferred place to put these additional JAR files or the asadmin add-library command can be used to place it there for you.

This is from the 5.192 release notes so I wonder why it still worked in 5.193.1. Of course it could be that the ext-dir is not the problem.

**Comment by svendiedrichsen** [comment]
@peterpz1 I'm not working for payara. I'm only a user. But as far as I can see the logback integration library you are mentioning is not provided by payara. There is already an issue posted which requests for a different logging API here https://github.com/payara/Payara/issues/4546 and as far as I can tell from the roadmap posted here https://github.com/orgs/payara/projects/1 there are no plany to support a different logging API.

**Comment by peterpz1** [comment]
The reported exception was not visible until 5.194. We have deployments with the 5.193.1 and there was no exception in server log because of the logback libs. That is why I'm reporting it now. About the issue I see it for payara micro, I don't know if it will be done also for Full version.

About sharing know-how. We have at least 20 deployments with different versions (starting from 5.184) and this https://github.com/goodees/goodees always looked good. As I mentioned after switching from GlassFish I tried to add raw logback and slf4j libs into the payara but wasn't able to make it work stable. The goodees had no issues up to the 5.194 when there is an exception on server start (but apart from that everyting seems to be working properly, we have one production deployment in such config and no issues apart from reported exception).

**Comment by pdudits** [comment]
@peterpz1 Was this `payaradomain` created by configuring either of the pre-configured domains bundled with 5.194? Things around ejb-invoker did change and should be re-enabled again.

**Comment by fturizo** [comment]
@peterpz1, as previouslt stated, the error you are encountering seems to be originated from using the pre-configured domains in 5.194 which seems to cause issues with the `ejb-invoker` application. Can you run your test scenario with a fresh installation of release *5.201*?

**Comment by peterpz1** [comment]
Hello I did tests on 5.201 and there is no exception. So I think we can resolve this issue, we will switch to 201 version. Thank you.

**Comment by fturizo** [comment]
Glad that your issue is gone, @peterpz1. I'll close this issue as requested then
