### ISSUE TITLE
Payara not finding oracle.spatial.geometry.JGeometry in classpath

### ISSUE THREAD

**Issue by el-duderino5** [payara/Payara#4569]
# Description #
----------

I am developing a JSF web application that queries a table in an Oracle database which has a SDO.GEOMETRY, but it's not working since the JGeometry class is not being found and no matter where I put the sdoapi.jar (Oracle's spatial Java API jar) in the directories inside Payara, it won't load it. The application makes use of EclipseLink as JPA implementation.

## Expected Outcome

The application should be able to retrieve the SDO.GEOMETRY type from database.

## Current Outcome

The application can't query the SDO.GEOMETRY because it can't find JGeometry class in classpath when uploaded to Payara Server. It fails with the following exception:

```
java.lang.RuntimeException: java.lang.ClassNotFoundException: oracle.spatial.geometry.JGeometry
	at org.eclipse.persistence.platform.database.oracle.converters.JGeometryConverter.<init>(JGeometryConverter.java:43)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at org.eclipse.persistence.internal.security.PrivilegedAccessHelper.newInstanceFromClass(PrivilegedAccessHelper.java:535)
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.buildObjectForClass(EntityManagerSetupImpl.java:1447)
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.getStructConverters(EntityManagerSetupImpl.java:1379)
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:710)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:219)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:327)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:350)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:313)
	at org.glassfish.persistence.jpa.JPADeployer$2.visitPUD(JPADeployer.java:461)
	at org.glassfish.persistence.jpa.JPADeployer$PersistenceUnitDescriptorIterator.iteratePUDs(JPADeployer.java:525)
	at org.glassfish.persistence.jpa.JPADeployer.iterateInitializedPUsAtApplicationPrepare(JPADeployer.java:507)
	at org.glassfish.persistence.jpa.JPADeployer.event(JPADeployer.java:408)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:562)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:561)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:558)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:554)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:553)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:584)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:576)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:575)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1496)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:120)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1878)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1754)
	at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:564)
	at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:251)
	at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:166)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: oracle.spatial.geometry.JGeometry
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.apache.felix.framework.ExtensionManager$ExtensionManagerWiring.getClassByDelegation(ExtensionManager.java:1179)
	at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1618)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1548)
	at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1982)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at org.eclipse.persistence.platform.database.oracle.converters.JGeometryConverter.<init>(JGeometryConverter.java:41)
```

## Environment ##

- **Payara Version**: 5.201
- **Edition**: Full
- **JDK Version**: 11
- **Operating System**: Linux (Debian Buster)
- **Database**: Oracle 11g

**Comment by rdebusscher** [comment]
Hi,

Can you share a small reproducer project which uses the Oracle's spatial Java API jar and how you have added the jar (asadmin command or location)

Regards
Rudy

**Comment by rdebusscher** [comment]
Hi,

Can you provide us more information on this ticket otherwise I need to close this with "cannot reproduce"?

**Comment by el-duderino5** [comment]
Good afternoon. Please excuse my absence.
I have prepared a project that demonstrates the issue
[oraclegeospatialapp.zip](https://github.com/payara/Payara/files/4806563/oraclegeospatialapp.zip)

You will have to add the sdoapi jar to your local maven repository as it is not available on Maven.

**Comment by rdebusscher** [comment]
Hi @el-duderino5,

Before I try to reproduce this with the actual Oracle additional JAR files, can you update the project to correct a few problems and try again?

The EclipseLink dependencies must be provided since the Payara Server has EclipseLink already included. It is recommended to use the payara-bom artifact (see documentation https://docs.payara.fish/community/docs/5.2020.2/documentation/ecosystem/maven-bom.html#_contents_of_the_bom) so that you are referencing the same version in your project as the one included in the server.

Also, the sdoapi.jar file is included in your war file but you also added it to the server which can lead to problems.

If you need a custom EclipseLink version (instead of the default one of Payara) you need to use the classloader enhancements as described here https://docs.payara.fish/community/docs/5.2020.2/documentation/payara-server/classloading.html

Regards
Rudy

**Comment by el-duderino5** [comment]
Thank you for the reply, @rdebusscher .

I modified the project as per instructions. It is now using the payara BOM: [oraclegeospatialapp.zip](https://github.com/payara/Payara/files/4833985/oraclegeospatialapp.zip) . The result is the same:
```

[2020-06-25 05:55:57,527] Artifact oraclegeospatialapp:war exploded: Artifact is being deployed, please wait...
[2020-06-25 05:56:01,623] Artifact oraclegeospatialapp:war exploded: Error during artifact deployment. See server log for details.
[2020-06-25 05:56:01,625] Artifact oraclegeospatialapp:war exploded: java.io.IOException: com.sun.enterprise.admin.remote.RemoteFailureException: Error occurred during deployment: Exception [EclipseLink-28019] (Eclipse Persistence Services - 2.7.4.payara-p2): org.eclipse.persistence.exceptions.EntityManagerSetupException
Exception Description: Deployment of PersistenceUnit [geospatialPU] failed. Close all factories for this PersistenceUnit.
Internal Exception: java.lang.RuntimeException: java.lang.ClassNotFoundException: oracle.spatial.geometry.JGeometry. Please see server.log for more details.
```

I have tried both not including and including the geospatial API in the lib folder of the server. I am aware that the jar is added to the war, which I verified before creating this issue. Since that didn't work, I opted to include it in the lib folder to see if payara could get it to load.

**Comment by AlanRoth** [comment]
Hi @el-duderino5, 

Could you please provide an updated download link to the sdoapi jar dependency. It seems like it is not available anymore. The reproducer could also be updated to use 5.2020.6.

Thank you,
Alan

**Comment by AlanRoth** [comment]
Hi @el-duderino5, do you have any updates on this?

**Comment by AlanRoth** [comment]
Hi @el-duderino5, do you have any updates? I will have to close this issue due to inactivity soon. Thank you.

**Comment by AlanRoth** [comment]
Hi @el-duderino5, 

I will be closing this issue due to inactivity. If you still believe this is a valid issue and you have an updated reproducer, feel free to reopen. 

Thank you,
Alan
