### ISSUE TITLE
OpenAPI generation fails for bidirectional association /CUSTCOM-249

### ISSUE THREAD

**Issue by fschuerer** [payara/Payara#4583]
# Description #
----------

Two entities with bidirectional association (One2Many and Many2One) produces a StackOverflowError exception when generating the OpenAPI document.

## Expected Outcome

```
openapi: 3.0.0
info:
  title: Deployed Resources
  version: 1.0.0
servers:
- url: http://DU165141.stahl01.com:8080/openapi-bidirectional
  description: Default Server.
- url: https://DU165141.stahl01.com:8181/openapi-bidirectional
  description: Default Server.
paths:
  /resources/sample/one:
    post:
      operationId: createOne
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/One'
      responses:
        default:
          content:
            '*/*':
              schema:
                type: object
          description: Default Response.
components:
  schemas:
    One:
      type: object
      properties:
        name:
          type: string
        many:
          type: array
          items:
            $ref: '#/components/schemas/Many'
    Many:
      type: object
      properties:
        name:
          type: string
        one:
          $ref: '#/components/schemas/One'
```

## Current Outcome

```
paths: {}
components: {}
```

```
OpenAPI document creation failed.
fish.payara.microprofile.openapi.api.OpenAPIBuildException: java.lang.StackOverflowError
	at fish.payara.microprofile.openapi.impl.OpenApiService$OpenApiMapping.buildDocument(OpenApiService.java:296)
	at fish.payara.microprofile.openapi.impl.OpenApiService$OpenApiMapping.getDocument(OpenApiService.java:276)
	at fish.payara.microprofile.openapi.impl.OpenApiService$OpenApiMapping.access$100(OpenApiService.java:259)
	at fish.payara.microprofile.openapi.impl.OpenApiService.getDocument(OpenApiService.java:192)
...
Caused by: java.lang.StackOverflowError
	at java.lang.Class.getEnclosingMethodInfo(Class.java:1072)
	at java.lang.Class.getEnclosingClass(Class.java:1272)
	at java.lang.Class.getSimpleBinaryName(Class.java:1443)
	at java.lang.Class.getSimpleName(Class.java:1309)
	at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.insertObjectReference(ApplicationProcessor.java:1036)
	at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.createSchema(ApplicationProcessor.java:985)
	at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.createSchema(ApplicationProcessor.java:979)
	at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.createSchema(ApplicationProcessor.java:1005)
	at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.visitSchemaClass(ApplicationProcessor.java:539)
	at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.visitSchema(ApplicationProcessor.java:488)
	at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.insertObjectReference(ApplicationProcessor.java:1039)
	at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.createSchema(ApplicationProcessor.java:985)
	at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.createSchema(ApplicationProcessor.java:1005)
	at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.visitSchemaClass(ApplicationProcessor.java:539)
	at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.visitSchema(ApplicationProcessor.java:488)
	at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.insertObjectReference(ApplicationProcessor.java:1039)
```

## Steps to reproduce (Only for bug reports) 

Reproducer application is provided at https://github.com/fschuerer/openapi-bidirectional

## Environment ##

- **Payara Version**: 5.201
- **Edition**: Full
- **JDK Version**: Oracle JDK: 8u212
- **Operating System**: Windows 10

**Comment by rdebusscher** [comment]
Hi,

The OpenAPI document generation results indeed in a StackOverflowError, so I have created the internal issue `CUSTCOM-249` to fix this.

However, this kind of usages will always require some kind of annotation, also because you expect some schemas to be present in the document.

In fact, the follow definition of the `One` and `Many` result in the correct and expected document.

```
@Schema(name = "Many")
public class Many {

    @Schema
    long id;
    @Schema
    public String name;

    @Schema(ref = "One")
    public One one;
}
```

```
@Schema(name = "One")
public class One {

    @Schema
    long id;
    @Schema
    public String name;
    @Schema(implementation = Many.class)
    public List<Many> many;
}
```

Regards
Rudy

**Comment by smillidge** [comment]
Fixed by https://github.com/payara/Payara/pull/4758
