### ISSUE TITLE
Hazelcast - ClassNotFoundException while deserialization object from IQueue

### ISSUE THREAD

**Issue by maksitom** [payara/Payara#4620]
# Description #
----------

I have 2 apllications deployed on the same payara domain. First app creates IQueue and put data to it. Second app has ItemListener and poll data from queue when itemAdded event appears. The problem occurs while pooling data from queue. App cannot deserialize object and throws ClassNotFoundException. I use lookuped hazelcastInstance from payara. Apps use same class which is included from library. This class implements DataSerializable interface.
I think that it is a problem with class loaders and classpath during hazelcast initialization - used class is in war so payara during initialization hazelcast not know about it.

## Expected Outcome

I expect that object pooled from queue deserialize without any problems and workarounds. JMS queue works in that way without problems.

## Current Outcome
```
2020-04-14 11:05:35 SEVERE [com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl] [10.3.33.106]:4900 [development] [3.12.6] hz._hzInstance_1_development.event-3 caught an exception while processing:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@31dbc09
com.hazelcast.nio.serialization.HazelcastSerializationException: Problem while reading DataSerializable, namespace: 0, ID: 0, class: 'org.test.TestData', exception: org.test.TestData
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.rethrowReadException(DataSerializableSerializer.java:183)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:164)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:187)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:114)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:163)
	at com.hazelcast.collection.impl.queue.QueueProxySupport.invokeAndGet(QueueProxySupport.java:177)
	at com.hazelcast.collection.impl.queue.QueueProxySupport.pollInternal(QueueProxySupport.java:128)
	at com.hazelcast.collection.impl.queue.QueueProxyImpl.poll(QueueProxyImpl.java:91)
	at com.hazelcast.collection.impl.queue.QueueProxyImpl.poll(QueueProxyImpl.java:142)
	at org.test.TestQueueListener.itemAdded(TestQueueListener.java:42)
	at com.hazelcast.collection.impl.queue.QueueService.dispatchEvent(QueueService.java:250)
	at com.hazelcast.collection.impl.queue.QueueService.dispatchEvent(QueueService.java:86)
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:64)
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:244)
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:227)
**Caused by: java.lang.ClassNotFoundException: org.test.TestData**
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at com.sun.enterprise.loader.CurrentBeforeParentClassLoader.loadClass(CurrentBeforeParentClassLoader.java:83)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:288)
	at com.hazelcast.nio.ClassLoaderUtil.newInstance0(ClassLoaderUtil.java:212)
	at com.hazelcast.nio.ClassLoaderUtil.newInstance(ClassLoaderUtil.java:193)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:152)
	... 17 more
```

## Steps to reproduce (Only for bug reports) 

**First App:**
```  
@Resource(lookup = "payara/Hazelcast")
private HazelcastInstance hazelcast;
...
IQueue<TestData> testQueue = hazelcast.getQueue("testQueue");
...
TestData testData= new TestData (number, message, timestamp);
testQueue.put(testData);`
```

**Second app:**
```
public class TestQueueListener implements ItemListener<TestData> {
...
Context ctx = new InitialContext();
HazelcastInstance hazelcast = (HazelcastInstance) ctx.lookup("payara/Hazelcast");
this.testQueue = hazelcast.getQueue("testQueue");
this.listenerId = testQueue.addItemListener(this, true);
...
@Override
public void itemAdded(ItemEvent<TestData> item) {
    TestData testData = testQueue.poll(); // throws exception
}
```

**Class used in queue:**
```
@NoArgsConstructor
@AllArgsConstructor
@Getter @Setter
@ToString
public class TestData implements DataSerializable {

    private String number;
    private String message;
    private ZonedDateTime timestamp;

    @Override
    public void writeData(ObjectDataOutput out) throws IOException {
        out.writeUTF(number);
        out.writeUTF(message);
        out.writeLong(timestamp.toInstant().toEpochMilli());
    }

    @Override
    public void readData(ObjectDataInput in) throws IOException {
        this.number = in.readUTF();
        this.message = in.readUTF();
        this.timestamp = ZonedDateTime.ofInstant(Instant.ofEpochMilli(in.readLong()), ZONE_ID);
    }

}
```

## Environment ##

- **Payara Version**: 5.201
- **Edition**: Full
- **JDK Version**: Zulu 11
- **Operating System**: Linux

**Comment by lprimak** [comment]
You have correctly analyzed the issue. There is a new API in Hazelcast called TenantControl that Payara can use to fix this issue, however it had not been done

**Comment by maksitom** [comment]
Is there a chance that it will be done in the next payara release?
How best to solve my problem in the current payara release?

**Comment by lprimak** [comment]
No chance. This is very complicated. 
You can try putting the class that needs to be loaded into a jar in <<domain>>/lib directory so Payara can load it from the common class loader

**Comment by lprimak** [comment]
Or you can serialize your class into a buffer and send the buffer in the queue and deserialize yourself on the other end.

**Comment by maksitom** [comment]
Serializing class into a buffer works ok. Thank you for your help

**Comment by lprimak** [comment]
PR #1879 has first stab at these fixes however, the API has changed significantly since then and it needs to be re-worked

**Comment by smillidge** [comment]
You could also try using this functionality in Payara which is built on top of Hazelcast Topics https://payara.gitbooks.io/payara-server/documentation/payara-server/public-api/cdi-events.html

**Comment by fturizo** [comment]
@maksitom, do you need further assistance with this issue? Or was the solution that @lprimak provided was more than enough?

**Comment by maksitom** [comment]
@lprimak solution is ok
