### ISSUE TITLE
GRIZZLY0013: NoSuchFieldError: nullSession

### ISSUE THREAD

**Issue by theandrewbailey** [payara/Payara#4642]
# Description #
----------

## Expected Outcome

Server returns resource.

## Current Outcome

Client/browser reports connection was reset.

Warning:   GRIZZLY0013: Exception during FilterChain execution
java.lang.NoSuchFieldError: nullSession
	at sun.security.ssl.SSLEngineImpl.init(SSLEngineImpl.java:379)
	at sun.security.ssl.SSLEngineImpl.<init>(SSLEngineImpl.java:367)
	at sun.security.ssl.SSLContextImpl$AbstractTLSContext.createSSLEngineImpl(SSLContextImpl.java:562)
	at sun.security.ssl.SSLContextImpl.engineCreateSSLEngine(SSLContextImpl.java:208)
	at javax.net.ssl.SSLContext.createSSLEngine(SSLContext.java:361)
	at org.glassfish.grizzly.ssl.SSLEngineConfigurator.createSSLEngine(SSLEngineConfigurator.java:190)
	at org.glassfish.grizzly.ssl.SSLEngineConfigurator.createSSLEngine(SSLEngineConfigurator.java:162)
	at org.glassfish.grizzly.ssl.SSLBaseFilter$SSLTransportFilterWrapper.handleRead(SSLBaseFilter.java:1111)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$0(WorkerThreadIOStrategy.java:90)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)

## Steps to reproduce (Only for bug reports) 

1. Start Payara.
2. Request a resource over HTTPS.

## Environment ##

- **Payara Version**: 5.201 (build 512)
- **Edition**: Full
- **JDK Version**: OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~16.04-b09)
    - Also: Azul 1.8.0_252
- **Operating System**: Ubuntu 16.04.6 LTS

**Comment by OndroMih** [comment]
This is a known issue with OpenJDK 8u252 and all JDKs based on it, e.g. Corretto 8.252. It's cause by the same problem as #4623 and  #4625.

Please try the workaround described in #4625 or use an older JDK 8 version, e.g. OpenJDK 8u242. Zulu JDK works with versions older than 8.44 / 1.8.0_242 because it already contains the change added to OpenJDK in 8u252.

I'm going to close this. Please watch #4623 and  #4625.
