### ISSUE TITLE
wscompile NoClassDefFoundError with jdk 8 /FISH-90

### ISSUE THREAD

**Issue by berniegsfc** [payara/Payara#4665]
# Description #
----------
With jdk 8, wscompile fails with a NoClassDefFoundError.

## Expected Outcome
$ wscompile
error: no mode was specified, please use one of -import/-define/-gen
Usage: wscompile [options] configuration_file

Use "wscompile -help" for a detailed description of options.

## Current Outcome

$ wscompile
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/rpc/JAXRPCException
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.sun.xml.rpc.tools.wscompile.CompileTool.initialize(CompileTool.java:99)
	at com.sun.xml.rpc.util.ToolBase.<init>(ToolBase.java:36)
	at com.sun.xml.rpc.tools.wscompile.CompileTool.<init>(CompileTool.java:91)
	at com.sun.xml.rpc.tools.wscompile.Main.main(Main.java:27)
Caused by: java.lang.ClassNotFoundException: javax.xml.rpc.JAXRPCException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 40 more

## Steps to reproduce (Only for bug reports) 

With jdk 8 type
payara5/glassfish/bin/wscompile

## Context (Optional)

Workaround: Change javax.xml.rpc-api.jar to jakarta.xml.rpc-api.jar on line 67 of wscompile script file.

## Environment ##

- **Payara Version**: 5.201
- **Edition**: Full
- **JDK Version**: 8u252 - OpenJDK 
- **Operating System**: Linux / Mac
- **Database**: None

**Comment by berniegsfc** [comment]
Note, a similar problem exists with wsdeploy.

**Comment by khasunuma** [comment]
I could reproduce and raise an internal issue CUSTCOM-283 to investigate further.

**Comment by fturizo** [comment]
Fixed as part of release *5.2020.5* with the ID `FISH-90`
