### ISSUE TITLE
jaxws-tubes-default.xml ] was not found

### ISSUE THREAD

**Issue by peterpz1** [payara/Payara#4678]
I'm trying to move my app to Payara 5.201 with zulu11.37.17-ca-jdk11.0.6-linux_x64 but I'm getting a bit furious...

I have SOAP client configured in build.gradle like that:
wsdl2java {
    wsdlsToGenerate = [
            [ "$projectDir/src/main/resources/wsdl/wsdl.wsdl"]
    ]
    locale = new Locale("pl")
    cxfVersion = "3.3.1"
}

Which generates jax-ws classes. Then I just use the service as a client. It worked on every Payara version with JDK8, but on JDK11 I get:
```pl.orangelabs.pms.nbi.data.manager.downloader.papyrus.cpespecinf.CpeSpecInfoDownloader - Throwable
java.lang.InternalError: MASM0010: Unable to unmarshall metro config file from location [ null ]
	at com.sun.xml.ws.assembler.MetroConfigLoader.loadMetroConfig(MetroConfigLoader.java:234)
	at com.sun.xml.ws.assembler.MetroConfigLoader.init(MetroConfigLoader.java:117)
	at com.sun.xml.ws.assembler.MetroConfigLoader.<init>(MetroConfigLoader.java:91)
	at com.sun.xml.ws.assembler.TubelineAssemblyController.getTubeCreators(TubelineAssemblyController.java:63)
	at com.sun.xml.ws.assembler.MetroTubelineAssembler.createClient(MetroTubelineAssembler.java:88)
	at com.sun.xml.ws.client.Stub.createPipeline(Stub.java:313)
	at com.sun.xml.ws.client.Stub.<init>(Stub.java:280)
	at com.sun.xml.ws.client.Stub.<init>(Stub.java:213)
	at com.sun.xml.ws.client.Stub.<init>(Stub.java:228)
	at com.sun.xml.ws.client.sei.SEIStub.<init>(SEIStub.java:68)
	at com.sun.xml.ws.client.WSServiceDelegate.getStubHandler(WSServiceDelegate.java:791)
	at com.sun.xml.ws.client.WSServiceDelegate.createEndpointIFBaseProxy(WSServiceDelegate.java:780)
	at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:422)
	at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:390)
	at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:372)
	at javax.xml.ws.Service.getPort(Service.java:139)
	at com.francetelecom.papyrus.getcpeinfos.v1.CPEManagementService.getGetCPEInfos(CPEManagementService.java:72)
	at pl.orangelabs.pms.nbi.data.manager.connector.papyrus.PapyrusUtil.buildCpeManagement(PapyrusUtil.java:45)
	at pl.orangelabs.pms.nbi.data.manager.downloader.papyrus.cpespecinf.CpeSpecInfoDownloader.syncDownload(CpeSpecInfoDownloader.java:68)
	at pl.orangelabs.pms.nbi.data.manager.downloader.papyrus.cpespecinf.CpeSpecInfoDownloader.syncDownload(CpeSpecInfoDownloader.java:48)
	at pl.orangelabs.commons.downloader.AbstractDataDownloader.downloadDataSync(AbstractDataDownloader.java:167)
	at pl.orangelabs.commons.downloader.AbstractDataDownloader.lambda$getData$0(AbstractDataDownloader.java:86)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.IllegalStateException: MASM0001: Default configuration file [ jaxws-tubes-default.xml ] was not found
	at com.sun.xml.ws.assembler.MetroConfigLoader.getConfigInputStream(MetroConfigLoader.java:250)
	at com.sun.xml.ws.assembler.MetroConfigLoader.loadMetroConfig(MetroConfigLoader.java:225)
	... 28 common frames omitted
```

I've looked into the webservices.jar boundled with Payara 5.201 and indeed jaxws-tubes-default.xml is missing. I even tried to add it manually and compile library again - the errors were showing that the MetroConfigLoader is not able to read this XML...

What to do? I already lost full day on that :(

A lot of stackoverflow topics are suggesting adding jaxws-tubes-default.xml into the META-INF of my app, but it doesn't help.

Also there is no topics of exactly the same problem caused by JDK11, which makes me wondering what I'm doing wrong?

**Comment by peterpz1** [comment]
What is also really interesting when I make the same code to be executed in contextInitialized event the error is different:
```
java.lang.RuntimeException: MASM0017: Unable to load Tube factory class [ com.sun.xml.internal.ws.assembler.jaxws.HandlerTubeFactory ]
	at com.sun.xml.ws.assembler.TubeCreator.<init>(TubeCreator.java:55)
	at com.sun.xml.ws.assembler.TubelineAssemblyController.initializeTubeCreators(TubelineAssemblyController.java:102)
	at com.sun.xml.ws.assembler.TubelineAssemblyController.getTubeCreators(TubelineAssemblyController.java:64)
	at com.sun.xml.ws.assembler.MetroTubelineAssembler.createClient(MetroTubelineAssembler.java:88)
	at com.sun.xml.ws.client.Stub.createPipeline(Stub.java:313)
	at com.sun.xml.ws.client.Stub.<init>(Stub.java:280)
	at com.sun.xml.ws.client.Stub.<init>(Stub.java:213)
	at com.sun.xml.ws.client.Stub.<init>(Stub.java:228)
	at com.sun.xml.ws.client.sei.SEIStub.<init>(SEIStub.java:68)
	at com.sun.xml.ws.client.WSServiceDelegate.getStubHandler(WSServiceDelegate.java:791)
	at com.sun.xml.ws.client.WSServiceDelegate.createEndpointIFBaseProxy(WSServiceDelegate.java:780)
	at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:422)
	at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:390)
	at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:372)
	at javax.xml.ws.Service.getPort(Service.java:139)
	at pl.orange.hetman.generated.KabestanHetmanIF_Service.getKabestanHetmanIFSOAP(KabestanHetmanIF_Service.java:72)
	at pl.orangelabs.pms.nbi.ContextListener.contextInitialized(ContextListener.java:42)
	at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:5165)
	at com.sun.enterprise.web.WebModule.contextListenerStart(WebModule.java:683)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:5736)
	at com.sun.enterprise.web.WebModule.start(WebModule.java:619)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:958)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:941)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:694)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1877)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1608)
	at com.sun.enterprise.web.WebApplication.start(WebApplication.java:108)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:283)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:362)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:621)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:652)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:643)
	at org.glassfish.deployment.admin.InstanceDeployCommand.execute(InstanceDeployCommand.java:223)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:558)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:554)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:553)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:584)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:576)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:575)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1496)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:120)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1878)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1754)
	at org.glassfish.admin.rest.resources.admin.CommandResource.executeCommand(CommandResource.java:409)
	at org.glassfish.admin.rest.resources.admin.CommandResource.execCommandMultInMultOut(CommandResource.java:258)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356)
	at org.glassfish.admin.rest.adapter.JerseyContainerCommandService$3.service(JerseyContainerCommandService.java:179)
	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:189)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:208)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:208)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.ws.assembler.jaxws.HandlerTubeFactory not found by org.glassfish.metro.webservices-osgi [391]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1597)
	at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1982)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.sun.xml.ws.assembler.TubeCreator.<init>(TubeCreator.java:37)
	... 106 common frames omitted
```

**Comment by peterpz1** [comment]
The code to be executed to generate those erorrs is quite simple. Just get the jax-ws service and get it port:
```
            KabestanHetmanIF_Service kabestanHetmanIF_service = new KabestanHetmanIF_Service();
            KabestanHetmanIF kabestanHetmanIF = kabestanHetmanIF_service.getKabestanHetmanIFSOAP();
```

**Comment by peterpz1** [comment]
After changing JDK to 8 everything starts to work properly...

**Comment by peterpz1** [comment]
So I really think that there is something wrong with metro library in 201 version. Possibly removed JAX-B from JDK9 doesn't help + also maybe some classloader issues? We will be very grateful for help, because because of that we cannot move the app to the JDK11... :(

**Comment by svendiedrichsen** [comment]
@peterpz1 Here is a similar question with the metro project: https://github.com/eclipse-ee4j/metro-jax-ws/issues/101

**Comment by peterpz1** [comment]
@svendiedrichsen my coworker @maksitom already did something really bad to make it work but it is showing that there is a problem with classloader - we are checking our config now. Executing this code:
Thread.currentThread().setContextClassLoader(ContextListener.class.getClassLoader());

Before calling webservice resolves the issue. ContextListener is the weblistener class (called on application startup - so possibly there are differences in classloader between start and normal app work).

**Comment by peterpz1** [comment]
Working classloader, which is available during application startup:
2020-05-25 14:47:30.711 [admin-thread-pool::admin-listener(1)] DEBUG pl.orangelabs.pms.nbi.data.manager.connector.papyrus.PapyrusUtil - currentThread.class.getClassLoader()=fish.payara.server.internal.grizzly.nucleus-grizzly-all [295]

During later work there is no classloader available:
2020-05-25 14:48:07.912 [ForkJoinPool-118-worker-19] DEBUG pl.orangelabs.pms.nbi.data.manager.connector.papyrus.PapyrusUtil - currentThread.class.getClassLoader()=null

**Comment by peterpz1** [comment]
Ok it seems that the root cause was ForkJoinPool which we've used. We are moving the app to the enterprise pool

**Comment by svendiedrichsen** [comment]
@peterpz1 So this was an application bug then. Can this be closed then?

**Comment by peterpz1** [comment]
Yes - it can be closed.
