### ISSUE TITLE
Grizzly NPN Bootstrap does not work with the JDK 8u251 /CUSTCOM-259

### ISSUE THREAD

**Issue by blegger** [payara/Payara#4680]
# Description #
----------
Upgrading from jdk-8u241 to jdk-8u251 breaks site running a Payara 5.201 instance 

## Expected Outcome
Expected outcome is for Grizzly NPN Bootstrap to be able to run with JDK 8u251.

## Current Outcome
The following error is being thrown after upgrading to JDK 8u251 from 8u241:

GRIZZLY0013: Exception during FilterChain execution
java.lang.NoSuchFieldError: nullSession
at sun.security.ssl.SSLEngineImpl.init(SSLEngineImpl.java:379)
at sun.security.ssl.SSLEngineImpl.<init>(SSLEngineImpl.java:367)
at sun.security.ssl.SSLContextImpl$AbstractTLSContext.createSSLEngineImpl(SSLContextImpl.java:562)
at sun.security.ssl.SSLContextImpl.engineCreateSSLEngine(SSLContextImpl.java:208)
at javax.net.ssl.SSLContext.createSSLEngine(SSLContext.java:361)
at org.glassfish.grizzly.ssl.SSLEngineConfigurator.createSSLEngine(SSLEngineConfigurator.java:190)
at org.glassfish.grizzly.ssl.SSLEngineConfigurator.createSSLEngine(SSLEngineConfigurator.java:162)
at org.glassfish.grizzly.ssl.SSLBaseFilter$SSLTransportFilterWrapper.handleRead(SSLBaseFilter.java:1111)
at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerTh

According to Oracle this is due to the following:
"The 8u251 JDK release introduced new APIs to support Application Layer
Protocol Negotiation (ALPN). Java SE changes were permitted given the Java 8
Maintenance Release 3 application which was approved in Februrary 2020.
Here is the bug - https://bugs.openjdk.java.net/browse/JDK-8230977

Please see the 8u251 release note -
https://www.oracle.com/technetwork/java/javase/8u251-relnotes-5972664.html#JDK-8051498

Prior to 8u251, software products on the stack like Grizzly may have added
jars which were pre-appended to the bootclasspath in order to leverage
internal classes in the JDK itself in order to use ALPN. That is no longer
possible.

Since Java 8 now has new API's introduced, the customer could update their
application code to call 'setApplicationProtocols' via
SSLParameters.setApplicationProtocol.

The change required is only minimal.

Please follow 8u docs for examples -
https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLSocket.html#setHandshakeApplicationProtocolSelector-java.util.function.BiFunction-
https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLParameters.html#setApplicationProtocols-java.lang.String:A-

Because of the implementation of
JDK-8230977 JEP 244: TLS Application-Layer Protocol Negotiation Extension (Java SE 8)
affected customer application (in this case, grizzly npn bootstrap) will need to do some
code changes.
"

## Environment ##

- **Payara Version**: 5.201
- **Edition**: Full
- **JDK Version**: 8u251
- **Operating System**: Linux (CentOS 5.6)
- **Database**: MySQL 8

**Comment by theandrewbailey** [comment]
Have you tried the solution suggested in this comment?

https://github.com/payara/Payara/issues/4625#issuecomment-616503463

Granted, this is for 252, not 251, but it might be useful.

**Comment by alecdesjardins** [comment]
> Have you tried the solution suggested in this comment?
> 
> [#4625 (comment)](https://github.com/payara/Payara/issues/4625#issuecomment-616503463)
> 
> Granted, this is for JDK 8u252, not JDK 8u251, but it might be useful.

I can't seem to get it to work.

**Comment by blegger** [comment]
> Have you tried the solution suggested in this comment?
> 
> [#4625 (comment)](https://github.com/payara/Payara/issues/4625#issuecomment-616503463)
> 
> Granted, this is for JDK 8u252, not JDK 8u251, but it might be useful.

I replaced 
        <jvm-options>-Xbootclasspath/p:${com.sun.aas.installRoot}/lib/grizzly-npn-bootstrap-1.8.1.jar</jvm-options>
with
        <jvm-options>-Xbootclasspath/a:${com.sun.aas.installRoot}/lib/grizzly-npn-api.jar</jvm-options>

My site works but tests show that HTTP/2 is not enabled. When I am using Oracle JDK 8u241 and the previous jvm option the same tests show HTTP/2 as being enabled.


This leads me to believe it is failing more gracefully but I am not getting any of the benefits from grizzly.

**Comment by rdebusscher** [comment]
Hi,

Due to various backports of HTTP/S support from JDK11 to JDK8 by OpenJDK, HTTP/2 (and HTTP/2 Push) can fail on recent JDK versions.

Changing the grizzly npn library as indicated fixes this problem in the sense that Payara starts up again but some functionality of HTTP/S is not available.

We are working on the Grizzly project to solve this issue.

Regards
Rudy

**Comment by andreasernst** [comment]
I downloaded grizzly-npn-bootstrap-1.9.jar and replaced grizzly-npn-bootstrap-X.jar with
-Xbootclasspath/a:${com.sun.aas.installRoot}/lib/grizzly-npn-bootstrap-1.9.jar

openjdk version "1.8.0_252"
OpenJDK Runtime Environment (IcedTea 3.16.0) (build 1.8.0_252-b09 suse-lp151.2.12.1-x86_64)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

**Comment by fturizo** [comment]
Fixed as part of release *5.2020.3* and referenced with the ID `FISH-31`
