### ISSUE TITLE
setup AS_ADMIN_MASTERPASSWORD variable is not working

### ISSUE THREAD

**Issue by hantsy** [payara/Payara#4687]
When I setup AS_ADMIN_MASTERPASSWORD  env in my docker-compose.yml, and start up, it will fail.

My docker compose file.

```yaml
version: '3.3' # specify docker-compose version

# Define the services/containers to be run
services:

# see: https://hub.docker.com/r/payara/server-full/
  payara:
    image: payara/server-full
    ports:
      - "8080:8080"
      - "8181:8181" # HTTPS listener
      - "4848:4848" # HTTPS admin listener
      - "9009:9009" # Debug port
    restart: always
    environment:
#    JVM_ARGS: ""
      AS_ADMIN_MASTERPASSWORD: admin
    volumes:
      - ./data/payara/deployments:/opt/payara/deployments
```

The error info is shown in the console.

```bash
  Shutdown required
payara_1  | MultiException stack 1 of 1
payara_1  | MultiException stack 1 of 2
payara_1  | java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Keystore was tampered with, or password was incorrect
payara_1  |     at org.glassfish.security.services.impl.JCEKSPasswordAliasStore.containsKey(JCEKSPasswordAliasStore.java:169)
payara_1  |     at fish.payara.nucleus.microprofile.config.source.PasswordAliasConfigSource.getValue(PasswordAliasConfigSource.java:84)
payara_1  |     at fish.payara.nucleus.microprofile.config.spi.PayaraConfig.getValue(PayaraConfig.java:166)
payara_1  |     at fish.payara.nucleus.microprofile.config.spi.PayaraConfig.getOptionalValue(PayaraConfig.java:88)
payara_1  |     at fish.payara.microprofile.healthcheck.HealthCheckService.postConstruct(HealthCheckService.java:120)
payara_1  |     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
payara_1  |     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
payara_1  |     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
payara_1  |     at java.lang.reflect.Method.invoke(Method.java:498)
payara_1  |     at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1268)
payara_1  |     at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:309)
payara_1  |     at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
payara_1  |     at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
payara_1  |     at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
payara_1  |     at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
payara_1  |     at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
payara_1  |     at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
payara_1  |     at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
payara_1  |     at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
payara_1  |     at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
payara_1  |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
payara_1  |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
payara_1  |     at java.lang.Thread.run(Thread.java:748)
payara_1  | Caused by: java.lang.RuntimeException: java.io.IOException: Keystore was tampered with, or password was incorrect
payara_1  |     at org.glassfish.security.services.impl.JCEKSPasswordAliasStore.pa(JCEKSPasswordAliasStore.java:103)
payara_1  |     at org.glassfish.security.services.impl.JCEKSPasswordAliasStore.containsKey(JCEKSPasswordAliasStore.java:167)
payara_1  |     ... 22 more
payara_1  | Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect
payara_1  |     at com.sun.crypto.provider.JceKeyStore.engineLoad(JceKeyStore.java:879)
payara_1  |     at java.security.KeyStore.load(KeyStore.java:1445)
payara_1  |     at com.sun.enterprise.security.store.PasswordAdapter.loadKeyStore(PasswordAdapter.java:136)
payara_1  |     at com.sun.enterprise.security.store.PasswordAdapter.<init>(PasswordAdapter.java:110)
payara_1  |     at org.glassfish.security.services.impl.JCEKSPasswordAliasStore.pa(JCEKSPasswordAliasStore.java:101)
payara_1  |     ... 23 more
payara_1  | Caused by: java.security.UnrecoverableKeyException: Password verification failed
payara_1  |     ... 28 more
payara_1  | MultiException stack 2 of 2
payara_1  | java.lang.IllegalStateException: Unable to perform operation: post construct on fish.payara.microprofile.healthcheck.HealthCheckService
payara_1  |     at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:369)
payara_1  |     at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
payara_1  |     at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
payara_1  |     at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
payara_1  |     at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
payara_1  |     at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
payara_1  |     at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
payara_1  |     at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
payara_1  |     at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
payara_1  |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
payara_1  |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
payara_1  |     at java.lang.Thread.run(Thread.java:748)
```

If I commentted out the env setttings, it works well.

**Comment by borisheithecker** [comment]
The AS_ADMIN_MASTERPASSWORD variable sets the password for the keystores. The default value is "changeit". If you supply a different value, you have to make sure that the keystores are encrypted using the same password. In docker, this usually means that you either have to write a start-up script which re-encrypts the keystores. Or you put them in a different location, e.g. a mounted docker volume, and set the related java system properties (javax.net.ssl.keyStore, java.net.ssl.trustStore) to point to them. 
The exception you get is thrown because the payara container can't read the keystores because of an incorrect password.

**Comment by hantsy** [comment]
So there is no approach to change the admin password?

**Comment by borisheithecker** [comment]
Why do you want to change it? AFAIK, the only reason to change it is when your keystores (containing the ssl certificates and private keys) are not secured with the default password, which is "changeit".

**Comment by rdebusscher** [comment]
Hi @hantsy ,

Sorry for the delay but the comment by Boris is correct. If you want to change the master password, please create a custom Docker image which includes the command `change-master-password` to change it from the default value.

Regards
Rudy
