### ISSUE TITLE
NPE when starting asadmin using OpenJDK 11

### ISSUE THREAD

**Issue by andy-bailey** [payara/Payara#4714]
Attempting to run asadmin on Ubuntu and Windows using openjdk version "11.0.7" results in an NPE.
----------
Payara version; 5.191 (downloaded on 12.06,2020)

command issued: ./asadmin
The following stacktrace is seen

Exception in thread "main" java.lang.NullPointerException
        at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.initializeServiceLocator(AbstractModulesRegistryImpl.java:152)
        at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.newServiceLocator(AbstractModulesRegistryImpl.java:144)
        at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.createServiceLocator(AbstractModulesRegistryImpl.java:218)
        at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.createServiceLocator(AbstractModulesRegistryImpl.java:224)
        at com.sun.enterprise.module.single.StaticModulesRegistry.createServiceLocator(StaticModulesRegistry.java:88)
        at com.sun.enterprise.admin.cli.CLIContainer.getServiceLocator(CLIContainer.java:212)
        at com.sun.enterprise.admin.cli.CLIContainer.getLocalCommand(CLIContainer.java:244)
        at com.sun.enterprise.admin.cli.CLICommand.getCommand(CLICommand.java:230)
        at com.sun.enterprise.admin.cli.AdminMain.executeCommand(AdminMain.java:362)
        at com.sun.enterprise.admin.cli.AdminMain.doMain(AdminMain.java:298)
        at org.glassfish.admin.cli.AsadminMain.main(AsadminMain.java:56)
4
No log files are generated, this is to be expected as no server was started or an attempt made to start a domain

## Expected Outcome
That the asadmin console starts and is ready to process commands.

## Current Outcome

As described above, asadmin terminates with an NPE, stacktrace above.

## Steps to reproduce (Only for bug reports) 

Running Ubuntu on Windows 10 2004 with the latest sdkman version. This has the following java version installed and selected: 11.0.7.hs-adpt
The asenv.conf file was not amended.
Under Windows native the exact same result is seen. Here the asenv.bat file has been amended to set AS_JAVA to the Windows OpenJDK version equivalent. 
Executing either ./asadmin or asadmin.bat (Windows) has the same result.

No other changes have been made to any configuration files.

## Environment ##

- **Payara Version**: 5.191
- **Edition**: Full
- **JDK Version**: OpenJDK 11.0.7 HotSpot
- **Operating System**: Windows 10 2004 (OS Build 19041.329) native and Ubuntu 20.04 LTS on Windows. SDKMAN 5.8.3+506 is being used under Ubuntu which has the JDK version selected.

The expected behaviour is observed on both Windows native and Ubuntu when JDK 8 is selected.

Please note that a solution to this problem is not urgent nor is it blocking any commercial development. The problem was discovered while playing with some new toys in a private capacity.

**Comment by rdebusscher** [comment]
Hi Andy,

JDK11 support is only available in Payara 5.194 and later. You mention version 5.191. Is that a typo (and you tried 5.201) or did you try it with version 5.191?

Best regards
Rudy.

**Comment by andy-bailey** [comment]
I downloaded the 5.191 version as the latest available from https://www.payara.org/home

Not tried later versions, indeed I have even tried looking for them,

**Comment by andy-bailey** [comment]
Will grab 5.201 and try again. If successful I will comment and close this issue.

Thanks for the info Rudy,

Kind regards,

Andy Bailey

**Comment by rdebusscher** [comment]
The latest downloads can be found at https://www.payara.fish/downloads/

**Comment by andy-bailey** [comment]
Payara 5.201 works!!
I will close this issue.
Please update the available Payara download on payara.org unless there is a reason for having this version there. Better yet, remove the download from payara.org and link from there to payara.fish/downloads.
Once again, many thanks!

Andy Bailey

**Comment by rdebusscher** [comment]
Hi Andy,

I informed Marketing already about the outdated info on that website. 

Thanks for bringing this inconsistency to our attention.

Best Regards
Rudy
