### ISSUE TITLE
payara is running, but payara console can't visit.

### ISSUE THREAD

**Issue by currysu** [payara/Payara#4729]
I don't modify anything,since the payara console is running well few days. But today it can't visit. i find some msg with the server log. how can i do now. 

[2020-06-19T15:46:56.441+0800] [Payara 5.201] [严重] [] [javax.enterprise.network.config] [tid: _ThreadID=212 _ThreadName=admin-thread-pool::admin-listener(3)] [timeMillis: 1592552816441] [levelValue: 1000] [[
  Failed to load keystore type JKS with path null due to null
java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at org.glassfish.grizzly.config.ssl.JSSESocketFactory.getStore(JSSESocketFactory.java:306)
	at org.glassfish.grizzly.config.ssl.JSSESocketFactory.getKeystore(JSSESocketFactory.java:259)
	at org.glassfish.grizzly.config.ssl.JSSE14SocketFactory.getKeyManagers(JSSE14SocketFactory.java:175)
	at org.glassfish.grizzly.config.ssl.JSSE14SocketFactory.init(JSSE14SocketFactory.java:144)
	at org.glassfish.grizzly.config.SSLConfigurator.initializeSSLContext(SSLConfigurator.java:283)
	at org.glassfish.grizzly.config.SSLConfigurator.configureSSL(SSLConfigurator.java:147)
	at org.glassfish.grizzly.config.SSLConfigurator$InternalSSLContextConfigurator.createSSLContext(SSLConfigurator.java:429)
	at org.glassfish.grizzly.ssl.SSLEngineConfigurator.createSSLEngine(SSLEngineConfigurator.java:185)
	at org.glassfish.grizzly.ssl.SSLEngineConfigurator.createSSLEngine(SSLEngineConfigurator.java:162)
	at org.glassfish.grizzly.ssl.SSLBaseFilter.handleRead(SSLBaseFilter.java:300)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:208)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
]]

**Comment by rdebusscher** [comment]
Hi,

Did you set system property `javax.net.ssl.keyStore` to null?  It seems that the config for the key store is no longer present.

Regards
Rudy

**Comment by OndroMih** [comment]
Hi, @currysu, please, can you provide a simple to follow scenario how to reproduce this on the latest version? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. It will greatly help us to find the cause and fix it.

**Comment by khasunuma** [comment]
Hi @currysu, since no reproducer was provided and we weren't able to reproduce this issue, I'm going to close it. We'll reopen this issue if you provide us an easy to follow reproducer for the latest version of Payara. A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/.
