### ISSUE TITLE
Problem deploying a swing client on the Payara server with Java Web Start

### ISSUE THREAD

**Issue by jer63** [payara/Payara#4810]
### Description
Hello, I would like to submit a problem I have when I want to deploy my client application via Java Web Start. It is a Swing application and an ACC application.

### Expected Outcome
The result I expect is this: 
That the client application launches on the client workstation and that the main window of the application is displayed with the message Hello.

### Current Outcome
When running the application, Java Web start throws the following exception:

JreExecException[ Impossible de lancer la version C:\Java\jre1.8.0_261\bin\javaw.exe de Java Runtime Environment]
	at com.sun.javaws.Launcher.relaunch(Unknown Source)
	at com.sun.javaws.Launcher.prepareResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareAllResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.launch(Unknown Source)
	at com.sun.javaws.Main.launchApp(Unknown Source)
	at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
	at com.sun.javaws.Main.access$000(Unknown Source)
	at com.sun.javaws.Main$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Cannot run program "C:\Java\jre1.8.0_261\bin\jp2launcher.exe": CreateProcess error=206, Nom de fichier ou extension trop long
	at java.lang.ProcessBuilder.start(Unknown Source)
	at com.sun.deploy.config.WinPlatform.startProcessBuilder(Unknown Source)
	at com.sun.javaws.JnlpxArgs.execProgram(Unknown Source)
	... 11 more
Caused by: java.io.IOException: CreateProcess error=206, Nom de fichier ou extension trop long
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 14 more

### Steps to reproduce
Deploy the project on the Payara server with Payara Tools.
Launch the server.
Launch the administration console.
Launch the client via the administration console.

### Environment
	Payara Versi
[files.zip](https://github.com/payara/Payara/files/4976978/files.zip)

on: 5.2020.3
	Edition : Community
	JDK Version: 1.8.0_261
	Operating System: Windows 10 Pro
	Database : PostgreSQL 12.3
	Development Environment: Eclipse 2020-06

**Comment by lprimak** [comment]
I do not believe this issue has anything to do with Payara.
Did a quick google search and found this:
https://stackoverflow.com/questions/10519558/createprocess-error-206-the-filename-or-extension-is-too-long-when-running-main

**Comment by jer63** [comment]
Thank you.
I removed all my dependencies on the server and the EJB project, there is nothing left in the build-path. I still have the same error. I have already renamed my projects so that the names are shorter, the Payara server is directly installed under D:/. The error message does not indicate the string too long. Now, it's been a long time that I try to run my client with Java Web Start, first on the GlassFish server, but I have a problem with the grizzly-npn-bootstrap.jar library and now on Payara where this problem is not present, but here I am running out of ideas. One question, when we talk about "class-path", it's not the Windows environment variable? 

If you have an idea, I'll take it, because I don't know how to go on.

With kind regards,
Jérôme

**Comment by lprimak** [comment]
I would suggest taking this to Payra or WebStart forum or something like that. This is clearly not an issue with Payara.

**Comment by rdebusscher** [comment]
Hi,

You can read more about the HTTP/2 support within Payara in this blog: https://blog.payara.fish/http2-payara-5.

Closing the issue as the `jp2launcher.exe` related error is no longer present.  

If you have still an issue please create a small reproducer which clearly shows the problem and attach it to the issue.

Best Regards
Rudy.
