### ISSUE TITLE
Payara Micro 2020.3 can't use Java 14 records

### ISSUE THREAD

**Issue by dsmithau** [payara/Payara#4840]
# Description #
----------

When using Java 14 records (preview functionality) the micro server throws an exception as outlined below:

[2020-08-16T15:13:00.254+0800] [] [ [1;91mSEVERE [0m] [] [ [1;94mjavax.enterprise.system.tools.deployment.common [0m] [tid: _ThreadID=136 _ThreadName=payara-executor-service-task] [timeMillis: 1597561980254] [levelValue: 1000] [[
  Exception while visiting WEB-INF/classes/com/dms/recallagent/entity/Recall.class of size 2310
java.lang.UnsupportedOperationException: This feature requires ASM8_EXPERIMENTAL
        at org.objectweb.asm.ClassVisitor.visitRecordComponentExperimental(ClassVisitor.java:304)
        at org.objectweb.asm.ClassReader.readRecordComponent(ClassReader.java:929)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:704)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
        at org.glassfish.hk2.classmodel.reflect.Parser$5.on(Parser.java:336)
        at com.sun.enterprise.v3.server.ReadableArchiveScannerAdapter.handleEntry(ReadableArchiveScannerAdapter.java:165)
        at com.sun.enterprise.v3.server.ReadableArchiveScannerAdapter.onSelectedEntries(ReadableArchiveScannerAdapter.java:127)
        at org.glassfish.hk2.classmodel.reflect.Parser.doJob(Parser.java:321)
        at org.glassfish.hk2.classmodel.reflect.Parser.access$300(Parser.java:44)
        at org.glassfish.hk2.classmodel.reflect.Parser$3.call(Parser.java:280)
        at org.glassfish.hk2.classmodel.reflect.Parser$3.call(Parser.java:269)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
]]

## Expected Outcome

The expected outcome is to be able to run using records. The command like to start the micro server was:
 java --enable-preview -jar C:\Users\Admin\Downloads\payara-micro-5.2020.3.jar --deploy .\target\RecallAgent-1.0-SNAPSHOT.war --autoBindHttp --contextroot "/agent"

## Steps to reproduce (Only for bug reports) 
Create any data container using records. It doesn't even need to be called - just present. Launch the server and deploy the application for the exception to re-occur

## Environment ##

- **Payara Version**: 5.2020.3-micro
- **Edition**: Micro
- **JDK Version**: OpenJDK 14.0.2
- **Operating System**:  Windows 10
- **Database**: NA

**Comment by pzygielo** [comment]
But https://docs.payara.fish/community/docs/5.2020.4/general-info/supported-platforms.html does not list JDK > 11 as supported. Given that - I don't understand _expected outcome_.

**Comment by rdebusscher** [comment]
Hi,

As mentioned, JDK 14 is not supported and it is expected that Payara Micro isn't functioning properly on this version. Support for JDK 17 (LTS) is planned when it is available.

Regards
Rudy
