### ISSUE TITLE
payara-embedded-all: javax.ejb.embeddable.EJBContainer.createEJBContainer() not working/FISH-394

### ISSUE THREAD

**Issue by Pfiver** [payara/Payara#4844]
## Expected Outcome

I expect the provided Maven build to succeed with Pajara 5.2020.4 and JDK 11.

It _does_ work with Payara 5.181 and JDK 8, but those are _very_ old.

## Current Outcome

The maven build fails.

The maven build also fails, with various other errors, for other combinations of newer JDK and Pajara Versions. I haven't tested all of them.

## Steps to reproduce

I suggest that the focus is put on the errors arising when attempting to start an embedded EJB container instance with JDK 11 (LTS; any distribution, let's try [AdoptOpenJDK](https://adoptopenjdk.net/releases.html)) and Payara 5.2020.4 (which currently is the [latest RELEASE on Maven central](https://search.maven.org/artifact/fish.payara.extras/payara-embedded-all)).

This is what the Maven build [here](https://github.com/Pfiver/ejb-tests) does.

I am testing with [this](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.8%2B10/OpenJDK11U-jdk_x64_mac_hotspot_11.0.8_10.tar.gz) JDK.

Using MacOS 10.15.6, I start the Terminal and do

```
$ git clone 
$ cd ejb-tests
$ mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/patrick/Local/lib/apache-maven
Java version: 11.0.8, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/jdk-11.0.8+10/Contents/Home
Default locale: en_CH, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.6", arch: "x86_64", family: "mac"
$ mvn clean install
```

And get the following error messages:
```
[ ... lots of console logs ...]
WARNING: NCLS-DEPLOYMENT-00009
java.lang.UnsupportedOperationException: This feature requires ASM6
[ ... lots of console logs and stack traces ...]
Failed to deploy EJB modules - see log for details
[...]
BUILD FAILURE
[...]
```

### Samples

https://github.com/Pfiver/ejb-tests

## Context

I would like to write some learning tests to better understand EJB Transaction Semantics in respect to @TransactionAttribute, Checked/Unchecked System/Application Exceptions implications etc.

## Environment ##

- **Payara Version**: 5.2020.4
- **Edition**: Embedded (== Micro ?)
- **JDK Version**: AdoptOpenJDK 11.0.8+10 (suppoorted as per [the docs](https://docs.payara.fish/community/docs/5.2020.4/general-info/supported-platforms.html))
- **Operating System**: MacOS 10.15.6
- **Database**: n/a

**Comment by khasunuma** [comment]
Hi @Pfiver, thank you for the reproducer. I confirmed to reproduce the issue on 5.194 or later versions with both JDK 8 and JDK 11 (on Windows). Then, I've raised the internal issue `FISH-394` to further investigation. Thanks.

**Comment by rrohm** [comment]
Hi, I had a similar issue with payara-embedded-all on Linux (Ubuntu 19.10) with OpenJDK 11 and OpenJDK 8.
At present, it seems to be a workaround to start an embedded Payara instance instead of the embedded container, like

    GlassFishRuntime runtime = GlassFishRuntime.bootstrap();
    GlassFishProperties gfproperties = new GlassFishProperties();
    gfproperties.setPort("http-listener", 8099);
    gf = runtime.newGlassFish(gfproperties);
    gf.start();

That way, I got EJB tests that used the embedded Container running again. The embedded Payara has some advantages (e.g. configuration via CommandRunner), but at present I am not sure about eventual unnecessary overhead(?).
Also, e.g. the NetBeans IDE generates EJB test stubs that use the embedded EJB Container instead - this used to work "out-of-the-box" and has been very elegant tooling. Would be very good to see this working again :-)

**Comment by bh-tt** [comment]
I've run into the same issue, using `JAVA_HOME=/usr/lib/jvm/zulu11-ca-amd64'. I deploy 2 scattered archives to the container, 1 containing the application code and the second one containing only a few EJBs, mostly Producer methods to facilitate stubbing for integration tests. I have tested using payara-embedded-all 5.2020.2 and 5.2020.4

It incorrectly marks the second archive as not being an EJB module. I think it's because [this](https://github.com/payara/Payara/blob/47b2ea68b1103ae7a61d1473addef1133b650e62/appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/embedded/EJBContainerProviderImpl.java#L338) line creates the `this feature requires ASM7` UnsupportedOperationException and then fails to mark the module as an EJB module.

LOG:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.hazelcast.internal.networking.nio.SelectorOptimizer (file:/home/bh/.m2/repository/fish/payara/extras/payara-embedded-all/5.2020.4/payara-embedded-all-5.2020.4.jar) to field sun.nio.ch.SelectorImpl.selectedKeys
WARNING: Please consider reporting this to the maintainers of com.hazelcast.internal.networking.nio.SelectorOptimizer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Sep 21, 2020 4:00:00 PM org.glassfish.ejb.embedded.EJBContainerProviderImpl getValidFile
WARNING: ejb.embedded.instance_location_not_exists
Sep 21, 2020 4:00:00 PM org.glassfish.ejb.embedded.EJBContainerProviderImpl createContainer
INFO: [EJBContainerProviderImpl] Using runtime class: class com.sun.enterprise.glassfish.bootstrap.StaticGlassFishRuntime
Sep 21, 2020 4:00:00 PM org.jvnet.hk2.config.ConfigParser handleElement
SEVERE: Ignoring unrecognized element monitoring-console-configuration at [row,col {unknown-source}]: [25,3]
Sep 21, 2020 4:00:00 PM org.jvnet.hk2.config.ConfigParser handleElement
SEVERE: Ignoring unrecognized element zendesk-support-configuration at [row,col {unknown-source}]: [126,7]
Sep 21, 2020 4:00:00 PM org.jvnet.hk2.config.ConfigParser handleElement
SEVERE: Ignoring unrecognized element rest-monitoring-configuration at [row,col {unknown-source}]: [143,7]
Sep 21, 2020 4:00:01 PM com.sun.enterprise.v3.server.CommonClassLoaderServiceImpl findH2Client
INFO: Cannot find h2db client jar file, h2 jdbc driver will not be available by default.
Sep 21, 2020 4:00:01 PM com.hazelcast.instance.HazelcastInstanceFactory
WARNING: Hazelcast is starting in a Java modular environment (Java 9 and newer) but without proper access to required Java packages. Use additional Java arguments to provide Hazelcast access to Java internal API. The internal API access is used to get the best performance results. Arguments to be used:
 --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
Sep 21, 2020 4:00:02 PM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [development] [3.12.6] Using bind address: /10.247.3.232:8049
Sep 21, 2020 4:00:02 PM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [development] [3.12.6] Using public address: /10.247.3.232:8049
Sep 21, 2020 4:00:02 PM com.hazelcast.system
INFO: [10.247.3.232]:8049 [development] [3.12.6] Hazelcast 3.12.6 (20200130 - be02cc5) starting at [10.247.3.232]:8049
Sep 21, 2020 4:00:02 PM com.hazelcast.system
INFO: [10.247.3.232]:8049 [development] [3.12.6] Copyright (c) 2008-2020, Hazelcast, Inc. All Rights Reserved.
Sep 21, 2020 4:00:02 PM com.hazelcast.instance.Node
INFO: [10.247.3.232]:8049 [development] [3.12.6] A non-empty group password is configured for the Hazelcast member. Since version 3.8.2, members with the same group name, but with different group passwords (that do not use authentication) form a cluster. The group password configuration will be removed completely in a future release.
Sep 21, 2020 4:00:02 PM com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator
INFO: [10.247.3.232]:8049 [development] [3.12.6] Backpressure is disabled
Sep 21, 2020 4:00:03 PM com.hazelcast.instance.Node
INFO: [10.247.3.232]:8049 [development] [3.12.6] Activating Discovery SPI Joiner
Sep 21, 2020 4:00:03 PM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
INFO: [10.247.3.232]:8049 [development] [3.12.6] Starting 48 partition threads and 25 generic threads (1 dedicated for priority tasks)
Sep 21, 2020 4:00:03 PM com.hazelcast.internal.diagnostics.Diagnostics
INFO: [10.247.3.232]:8049 [development] [3.12.6] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
Sep 21, 2020 4:00:03 PM com.hazelcast.core.LifecycleService
INFO: [10.247.3.232]:8049 [development] [3.12.6] [10.247.3.232]:8049 is STARTING
Sep 21, 2020 4:00:03 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.247.3.232]:8049 [development] [3.12.6] Connecting to /172.18.0.1:8059, timeout: 10000, bind-any: true
Sep 21, 2020 4:00:03 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.247.3.232]:8049 [development] [3.12.6] Connecting to /172.17.0.1:8059, timeout: 10000, bind-any: true
Sep 21, 2020 4:00:03 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.247.3.232]:8049 [development] [3.12.6] Connecting to /172.20.0.1:8059, timeout: 10000, bind-any: true
Sep 21, 2020 4:00:03 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.247.3.232]:8049 [development] [3.12.6] Connecting to /10.247.3.232:8059, timeout: 10000, bind-any: true
Sep 21, 2020 4:00:03 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.247.3.232]:8049 [development] [3.12.6] Could not connect to: /172.17.0.1:8059. Reason: SocketException[Connection refused to address /172.17.0.1:8059]
Sep 21, 2020 4:00:03 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.247.3.232]:8049 [development] [3.12.6] Could not connect to: /172.20.0.1:8059. Reason: SocketException[Connection refused to address /172.20.0.1:8059]
Sep 21, 2020 4:00:03 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.247.3.232]:8049 [development] [3.12.6] Could not connect to: /172.18.0.1:8059. Reason: SocketException[Connection refused to address /172.18.0.1:8059]
Sep 21, 2020 4:00:03 PM com.hazelcast.internal.cluster.impl.DiscoveryJoiner
INFO: [10.247.3.232]:8049 [development] [3.12.6] [172.20.0.1]:8059 is added to the blacklist.
Sep 21, 2020 4:00:03 PM com.hazelcast.internal.cluster.impl.DiscoveryJoiner
INFO: [10.247.3.232]:8049 [development] [3.12.6] [172.17.0.1]:8059 is added to the blacklist.
Sep 21, 2020 4:00:03 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.247.3.232]:8049 [development] [3.12.6] Could not connect to: /10.247.3.232:8059. Reason: SocketException[Connection refused to address /10.247.3.232:8059]
Sep 21, 2020 4:00:03 PM com.hazelcast.internal.cluster.impl.DiscoveryJoiner
INFO: [10.247.3.232]:8049 [development] [3.12.6] [172.18.0.1]:8059 is added to the blacklist.
Sep 21, 2020 4:00:03 PM com.hazelcast.internal.cluster.impl.DiscoveryJoiner
INFO: [10.247.3.232]:8049 [development] [3.12.6] [10.247.3.232]:8059 is added to the blacklist.
Sep 21, 2020 4:00:04 PM com.hazelcast.internal.cluster.ClusterService
INFO: [10.247.3.232]:8049 [development] [3.12.6] 

Members {size:1, ver:1} [
	Member [10.247.3.232]:8049 - 50fd19b1-3112-4db1-9536-b64679bd49c1 this
]

Sep 21, 2020 4:00:04 PM com.hazelcast.internal.jmx.ManagementService
INFO: [10.247.3.232]:8049 [development] [3.12.6] Hazelcast JMX agent enabled.
Sep 21, 2020 4:00:04 PM com.hazelcast.core.LifecycleService
INFO: [10.247.3.232]:8049 [development] [3.12.6] [10.247.3.232]:8049 is STARTED
Sep 21, 2020 4:00:04 PM fish.payara.nucleus.hazelcast.HazelcastCore bindToJNDI
INFO: Hazelcast Instance Bound to JNDI at payara/Hazelcast
Sep 21, 2020 4:00:04 PM fish.payara.nucleus.hazelcast.HazelcastCore bindToJNDI
INFO: JSR107 Caching Provider Bound to JNDI at payara/CachingProvider
Sep 21, 2020 4:00:04 PM fish.payara.nucleus.hazelcast.HazelcastCore bindToJNDI
INFO: JSR107 Default Cache Manager Bound to JNDI at payara/CacheManager
Sep 21, 2020 4:00:05 PM com.sun.enterprise.v3.services.impl.GrizzlyProxy start0
INFO: Network Listener http-listener-1 started in: 12ms - bound to [/0.0.0.0:8080]
Sep 21, 2020 4:00:05 PM com.sun.enterprise.v3.services.impl.GrizzlyProxy start0
INFO: Network Listener http-listener-2 started in: 4ms - bound to [/0.0.0.0:8081]
Sep 21, 2020 4:00:05 PM com.sun.enterprise.v3.services.impl.GrizzlyProxy start0
INFO: Network Listener admin-listener started in: 3ms - bound to [/0.0.0.0:8048]
Sep 21, 2020 4:00:05 PM com.sun.enterprise.v3.services.impl.GrizzlyService postConstruct
INFO: Grizzly 2.4.4 started in: 3,436ms - bound to [http-listener-1:8080, http-listener-2:8081, admin-listener:8048]
Sep 21, 2020 4:00:05 PM com.hazelcast.internal.partition.impl.PartitionStateManager
INFO: [10.247.3.232]:8049 [development] [3.12.6] Initializing cluster partition table arrangement...
Sep 21, 2020 4:00:05 PM com.sun.enterprise.v3.services.impl.GrizzlyProxy start0
INFO: Network Listener iiop-service started in: 2ms - bound to [/0.0.0.0:8037]
Sep 21, 2020 4:00:05 PM fish.payara.nucleus.cluster.PayaraCluster logClusterStatus
INFO: Data Grid Status 
Payara Data Grid State: DG Version: 35 DG Name: development DG Size: 1
Instances: {
 DataGrid: development Instance Group: MicroShoal Name: server Lite: false This: true UUID: 50fd19b1-3112-4db1-9536-b64679bd49c1 Address: /10.247.3.232:8049
}
Sep 21, 2020 4:00:05 PM com.sun.enterprise.v3.server.AppServerStartup postStartupJob
INFO: Undefined Product Name - define product and version info in config/branding  0.0.0  (0) startup time : Embedded (1,073ms), startup services(4,496ms), total(5,569ms)
Sep 21, 2020 4:00:05 PM fish.payara.nucleus.notification.NotificationService bootstrapNotificationService
INFO: Payara Notification Service bootstrapped with configuration: NotificationExecutionOptions{enabled=true, notifierConfigurationExecutionOptionsList={LOG=LogNotifierConfigurationExecutionOptions{useSeparateLogFile=false} NotifierConfigurationExecutionOptions{notifierType=LOG, enabled=true, noisy=true}}}
Sep 21, 2020 4:00:05 PM fish.payara.nucleus.healthcheck.HealthCheckService executeTasks
INFO: Scheduling Health Check for task: HEAP
Sep 21, 2020 4:00:05 PM fish.payara.nucleus.healthcheck.HealthCheckService bootstrapHealthCheck
INFO: Payara Health Check Service Started.
Sep 21, 2020 4:00:06 PM org.glassfish.admin.mbeanserver.JMXStartupService$JMXConnectorsStarterThread startConnector
INFO: JMXStartupService has started JMXConnector on JMXService URL service:jmx:rmi://0.0.0.0:8086/jndi/rmi://0.0.0.0:8086/jmxrmi
Sep 21, 2020 4:00:06 PM com.sun.enterprise.connectors.jms.util.JmsRaUtil getInstalledMqVersion
WARNING: Check for a new version of MQ installation failed : /tmp/gfembed1939433432618341871tmp/lib/install/applications/jmsra/../imqjmsra.rar:/tmp/gfembed1939433432618341871tmp/lib/install/applications/jmsra/imqjmsra.rar
Sep 21, 2020 4:00:06 PM com.sun.enterprise.v3.services.impl.GrizzlyProxy start0
INFO: Network Listener JMS_PROXY_default_JMS_host started in: 2ms - bound to [/0.0.0.0:8076]
Sep 21, 2020 4:00:06 PM org.glassfish.deployment.common.GenericAnnotationDetector scanArchive
WARNING: NCLS-DEPLOYMENT-00009
java.lang.UnsupportedOperationException: This feature requires ASM7
	at org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:157)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:559)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at org.glassfish.deployment.common.GenericAnnotationDetector.scanArchive(GenericAnnotationDetector.java:146)
	at org.glassfish.deployment.common.GenericAnnotationDetector.hasAnnotationInArchive(GenericAnnotationDetector.java:96)
	at org.glassfish.ejb.embedded.EJBContainerProviderImpl.getRequestedEJBModuleOrLibrary(EJBContainerProviderImpl.java:338)
	at org.glassfish.ejb.embedded.EJBContainerProviderImpl.addModule(EJBContainerProviderImpl.java:383)
	at org.glassfish.ejb.embedded.EJBContainerProviderImpl.addModule(EJBContainerProviderImpl.java:370)
	at org.glassfish.ejb.embedded.EJBContainerProviderImpl.addModules(EJBContainerProviderImpl.java:273)
	at org.glassfish.ejb.embedded.EJBContainerProviderImpl.createEJBContainer(EJBContainerProviderImpl.java:132)
	at javax.ejb.embeddable.EJBContainer.createEJBContainer(EJBContainer.java:127)
	at com.transtrend.prutser.integrationtest.ContainerInitialization.beforeAll(ContainerInitialization.java:42)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$7(ClassBasedTestDescriptor.java:359)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:359)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:189)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)

Sep 21, 2020 4:00:06 PM org.glassfish.ejb.embedded.DeploymentElement getOrCreateApplication
INFO: [DeploymentElement] adding classes to exploded ear  isEJBModule? true isWebApp? false
Sep 21, 2020 4:00:06 PM org.glassfish.ejb.embedded.DeploymentElement getOrCreateApplication
INFO: [DeploymentElement] adding test-classes to exploded ear  isEJBModule? false isWebApp? false
Sep 21, 2020 4:00:06 PM org.glassfish.ejb.embedded.EJBContainerImpl deploy
INFO: [EJBContainerImpl] Deploying app: /tmp/ejb-app12912212182336186539
Sep 21, 2020 4:00:06 PM org.glassfish.ejb.embedded.EJBContainerImpl deploy
INFO: [EJBContainerImpl] GlassFish status: STARTED
Sep 21, 2020 4:00:06 PM org.glassfish.ejb.embedded.EJBContainerImpl deploy
INFO: [EJBContainerImpl] Deploying as a File
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
Sep 21, 2020 4:00:06 PM org.glassfish.hk2.classmodel.reflect.Parser awaitTermination
INFO: visiting unvisited references
Sep 21, 2020 4:00:09 PM org.glassfish.hk2.classmodel.reflect.Parser awaitTermination
INFO: visiting unvisited references
Sep 21, 2020 4:00:09 PM org.glassfish.enterprise.iiop.api.GlassFishORBHelper postConstruct
INFO: GlassFishORBFactory service initialized.
Sep 21, 2020 4:00:09 PM com.sun.enterprise.security.SecurityLifecycle <init>
INFO: Java security manager is disabled.
Sep 21, 2020 4:00:09 PM com.sun.enterprise.security.SecurityLifecycle onInitialization
INFO: Entering Security Startup Service.
Sep 21, 2020 4:00:09 PM com.sun.enterprise.security.PolicyLoader installPolicyFromClassName
INFO: Loading policy provider com.sun.enterprise.security.provider.PolicyWrapper.
Sep 21, 2020 4:00:09 PM com.sun.enterprise.security.SecurityLifecycle onInitialization
INFO: Security Service(s) started successfully.
```
After this it starts to log Portable JNDI names for beans (from both modules) and then fails to deploy with unsatisfied dependencies relating to beans in the second module that inject beans from the first. These dependencies are very much present in the first module and it works fine when not combining the modules (e.g. when deploying to production).

**Comment by KimGabrielsen** [comment]
The problem is still here with payara-embedded-all 6.2021.1.Alpha1

Is there a workaround? It makes it impossible to test EJB modules.
