### ISSUE TITLE
Missing EJB Timer table on H2

### ISSUE THREAD

**Issue by stf-pay** [payara/Payara#4857]
# Description #
----------

As to:
https://github.com/users/stf-pay/emails/120043784/confirm_verification/850f542a625ca1d4aad9a726028e2ed6a5927469?utm_campaign=github-email-verification&utm_content=html&utm_medium=email&utm_source=verification-email

We are currently looking into using Payara 5.2020 - However when migrating from Glassfish the TimerPool can not be used like before as the Derby version is not supported by Payara 5.2 (removed)

Can you please let me know what you would suggest?
Install (how?) Derby on Payara 5.2020
- or -
Use H2 DB and run the timer scripts (how?)

https://github.com/payara/Payara/issues/4091

?

5T11:51:42.879+0200|INFO|Payara 5.2020|javax.enterprise.system.container.ejb.com.sun.ejb.containers|_ThreadID=19;_ThreadName=RunLevelControllerThread-1598349051281;_TimeMillis=1598349102879;_LevelValue=800;|==> Restoring Timers ... |#]

[#|2020-08-25T11:51:42.943+0200|INFO|Payara 5.2020|org.eclipse.persistence.session./file:/srv/payara5/glassfish/domains/domain1/applications/ejb-timer-service-app/WEB-INF/classes/___EJB__Timer__App|_ThreadID=19;_ThreadName=RunLevelControllerThread-1598349051281;_TimeMillis=1598349102943;_LevelValue=800;|EclipseLink, version: Eclipse Persistence Services - 2.7.6.payara-p1|#]

[#|2020-08-25T11:51:43.992+0200|INFO|Payara 5.2020|javax.enterprise.system.core.transaction.com.sun.jts.CosTransactions|_ThreadID=19;_ThreadName=RunLevelControllerThread-1598349051281;_TimeMillis=1598349103992;_LevelValue=800;|JTS5014: Recoverable JTS instance, serverId=[100]|#]

[#|2020-08-25T11:51:44.348+0200|INFO|Payara 5.2020|org.eclipse.persistence.session./file:/srv/payara5/glassfish/domains/domain1/applications/ejb-timer-service-app/WEB-INF/classes/___EJB__Timer__App.connection|_ThreadID=19;_ThreadName=RunLevelControllerThread-1598349051281;_TimeMillis=1598349104348;_LevelValue=800;|/file:/srv/payara5/glassfish/domains/domain1/applications/ejb-timer-service-app/WEB-INF/classes/___EJB__Timer__App login successful|#]

[#|2020-08-25T11:51:44.426+0200|WARNING|Payara 5.2020|org.eclipse.persistence.session./file:/srv/payara5/glassfish/domains/domain1/applications/ejb-timer-service-app/WEB-INF/classes/___EJB__Timer__App|_ThreadID=19;_ThreadName=RunLevelControllerThread-1598349051281;_TimeMillis=1598349104426;_LevelValue=900;|Local Exception Stack: 

Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.6.payara-p1): org.eclipse.persistence.exceptions.DatabaseException

Internal Exception: java.sql.SQLException: java.lang.reflect.UndeclaredThrowableException

Error Code: 0

Call: SELECT "TIMERID", "APPLICATIONID", "BLOB", "CONTAINERID", "CREATIONTIMERAW", "INITIALEXPIRATIONRAW", "INTERVALDURATION", "LASTEXPIRATIONRAW", "OWNERID", "PKHASHCODE", "SCHEDULE", "STATE" FROM "EJB__TIMER__TBL" WHERE (("OWNERID" = ?) AND ("STATE" = ?))

bind => [2 parameters bound]

Query: ReadAllQuery(name="findTimersByOwnerAndState" referenceClass=TimerState sql="SELECT "TIMERID", "APPLICATIONID", "BLOB", "CONTAINERID", "CREATIONTIMERAW", "INITIALEXPIRATIONRAW", "INTERVALDURATION", "LASTEXPIRATIONRAW", "OWNERID", "PKHASHCODE", "SCHEDULE", "STATE" FROM "EJB__TIMER__TBL" WHERE (("OWNERID" = ?) AND ("STATE" = ?))")

at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:342)

at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:691)

at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:567)

at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2099)

at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:603)

at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:265)

at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:275)

at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:261)

at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:332)

at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectAllRows(DatasourceCallQueryMechanism.java:744)

at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRowsFromTable(ExpressionQueryMechanism.java:2759)

[...]

at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)

at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

at java.base/java.lang.Thread.run(Thread.java:834)

Caused by: java.sql.SQLException: java.lang.reflect.UndeclaredThrowableException

at com.sun.gjc.spi.jdbc40.ProfiledConnectionWrapper40.prepareStatement(ProfiledConnectionWrapper40.java:247)

at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.prepareStatement(DatabaseAccessor.java:1595)

at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.prepareStatement(DatabaseAccessor.java:1544)

at org.eclipse.persistence.internal.databaseaccess.DatabaseCall.prepareStatement(DatabaseCall.java:806)

at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:628)

... 75 more

Caused by: java.lang.reflect.UndeclaredThrowableException

at com.sun.proxy.$Proxy397.prepareStatement(Unknown Source)

at com.sun.gjc.spi.base.ConnectionHolder.prepareStatement(ConnectionHolder.java:609)

at com.sun.gjc.spi.jdbc40.ProfiledConnectionWrapper40.prepareCachedStatement(ProfiledConnectionWrapper40.java:372)

at com.sun.gjc.spi.jdbc40.ProfiledConnectionWrapper40.prepareCachedStatement(ProfiledConnectionWrapper40.java:66)

at com.sun.gjc.spi.ManagedConnectionImpl.prepareCachedStatement(ManagedConnectionImpl.java:1080)

at com.sun.gjc.spi.jdbc40.ProfiledConnectionWrapper40.prepareStatement(ProfiledConnectionWrapper40.java:243)

... 79 more

Caused by: java.lang.reflect.InvocationTargetException

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.base/java.lang.reflect.Method.invoke(Method.java:566)

at com.sun.gjc.spi.JdbcObjectsFactory$1.invoke(JdbcObjectsFactory.java:143)

... 85 more

Caused by: org.h2.jdbc.JdbcSQLException: Table "EJB__TIMER__TBL" not found; SQL statement:

SELECT "TIMERID", "APPLICATIONID", "BLOB", "CONTAINERID", "CREATIONTIMERAW", "INITIALEXPIRATIONRAW", "INTERVALDURATION", "LASTEXPIRATIONRAW", "OWNERID", "PKHASHCODE", "SCHEDULE", "STATE" FROM "EJB__TIMER__TBL" WHERE (("OWNERID" = ?) AND ("STATE" = ?)) [42102-196]

## Expected Outcome

EJB Timer is working - SQL table is created

## Current Outcome

Caused by: org.h2.jdbc.JdbcSQLException: Table "EJB__TIMER__TBL" not found; SQL statement:

Exception and Payara server shutdown on domain start

## Environment ##

- **Payara Version**: 5.2020.2
- **Edition**: Community
- **JDK Version**: openJDK 11
- **Operating System**: Linux
- **Database**: mySQL

**Comment by smillidge** [comment]
I can't reproduce this deploying https://github.com/payara/Payara-Examples/tree/master/javaee/ejb-timer and then restarting the server I see the log below which indicates that timers are being reloaded from the database;

```[2020-08-28T17:54:46.426+0100] [Payara 5.2020.4-SNAPSHOT] [INFO] [AS-WEB-GLUE-00172] [javax.enterprise.web] [tid: _ThreadID=24 _ThreadName=RunLevelControllerThread-1598633674477] [timeMillis: 1598633686426] [levelValue: 800] [[

  Loading application [ejb-timer-service-app] at [/ejb-timer-service-app]]]

[2020-08-28T17:54:46.453+0100] [Payara 5.2020.4-SNAPSHOT] [INFO] [] [javax.enterprise.system.container.ejb.com.sun.ejb.containers] [tid: _ThreadID=24 _ThreadName=RunLevelControllerThread-1598633674477] [timeMillis: 1598633686453] [levelValue: 800] [[

  EJB5109:EJB Timer Service started successfully for data source [jdbc/__TimerPool]]]

[2020-08-28T17:54:46.453+0100] [Payara 5.2020.4-SNAPSHOT] [INFO] [] [javax.enterprise.system.container.ejb.com.sun.ejb.containers] [tid: _ThreadID=24 _ThreadName=RunLevelControllerThread-1598633674477] [timeMillis: 1598633686453] [levelValue: 800] [[

  ==> Restoring Timers ... ]]

[2020-08-28T17:54:46.504+0100] [Payara 5.2020.4-SNAPSHOT] [INFO] [] [org.eclipse.persistence.session./file:/opt/payara5/glassfish/domains/domain1/applications/ejb-timer-service-app/WEB-INF/classes/___EJB__Timer__App] [tid: _ThreadID=24 _ThreadName=RunLevelControllerThread-1598633674477] [timeMillis: 1598633686504] [levelValue: 800] [[

  EclipseLink, version: Eclipse Persistence Services - 2.7.6.payara-p1]]

[2020-08-28T17:54:47.108+0100] [Payara 5.2020.4-SNAPSHOT] [INFO] [] [javax.enterprise.system.core.transaction.com.sun.jts.CosTransactions] [tid: _ThreadID=24 _ThreadName=RunLevelControllerThread-1598633674477] [timeMillis: 1598633687108] [levelValue: 800] [[

  JTS5014: Recoverable JTS instance, serverId=[100]]]

[2020-08-28T17:54:47.233+0100] [Payara 5.2020.4-SNAPSHOT] [INFO] [] [org.eclipse.persistence.session./file:/opt/payara5/glassfish/domains/domain1/applications/ejb-timer-service-app/WEB-INF/classes/___EJB__Timer__App.connection] [tid: _ThreadID=24 _ThreadName=RunLevelControllerThread-1598633674477] [timeMillis: 1598633687233] [levelValue: 800] [[

  /file:/opt/payara5/glassfish/domains/domain1/applications/ejb-timer-service-app/WEB-INF/classes/___EJB__Timer__App login successful]]

[2020-08-28T17:54:47.316+0100] [Payara 5.2020.4-SNAPSHOT] [INFO] [] [] [tid: _ThreadID=24 _ThreadName=RunLevelControllerThread-1598633674477] [timeMillis: 1598633687316] [levelValue: 800] [[

  Cannot find the resource bundle for the name com.sun.logging.enterprise.system.container.ejb for class org.glassfish.ejb.persistent.timer.TimerState using fish.payara.server.internal.ejb.ejb-full-container [344]]]

[2020-08-28T17:54:47.328+0100] [Payara 5.2020.4-SNAPSHOT] [INFO] [] [javax.enterprise.system.container.ejb.com.sun.ejb.containers] [tid: _ThreadID=24 _ThreadName=RunLevelControllerThread-1598633674477] [timeMillis: 1598633687328] [levelValue: 800] [[

  [2] EJB Timers owned by this server will be restored when timeout beans are loaded]]

[2020-08-28T17:54:47.328+0100] [Payara 5.2020.4-SNAPSHOT] [INFO] [] [javax.enterprise.system.container.ejb.com.sun.ejb.containers] [tid: _ThreadID=24 _ThreadName=RunLevelControllerThread-1598633674477] [timeMillis: 1598633687328] [levelValue: 800] [[

  <== ... Timers Restored.]]

[2020-08-28T17:54:47.338+0100] [Payara 5.2020.4-SNAPSHOT] [INFO] [] [javax.enterprise.system.container.ejb.com.sun.ejb.containers] [tid: _ThreadID=24 _ThreadName=RunLevelControllerThread-1598633674477] [timeMillis: 1598633687338] [levelValue: 800] [[

  Rescheduling missed expiration for periodic timer '1@@1598633626172@@server@@domain1' 'TimedObject = ProgrammaticTimer' 'Application = simple-ejb-timer-1.0-SNAPSHOT' 'CREATED' 'PERIODIC' 'Container ID = 104768052893837111' 'Fri Aug 28 17:53:50 BST 2020' '0' '*/10 # * # * # * # * # * # * # null # null # null # true # printSchedule # 0' .  Last timer expiration occurred at Fri Aug 28 17:53:50 BST 2020]]

[2020-08-28T17:54:47.343+0100] [Payara 5.2020.4-SNAPSHOT] [INFO] [] [javax.enterprise.system.container.ejb.com.sun.ejb.containers] [tid: _ThreadID=24 _ThreadName=RunLevelControllerThread-1598633674477] [timeMillis: 1598633687343] [levelValue: 800] [[

  Rescheduling missed expiration for periodic timer '2@@1598633626172@@server@@domain1' 'TimedObject = SimpleTimerBean' 'Application = simple-ejb-timer-1.0-SNAPSHOT' 'CREATED' 'PERIODIC' 'Container ID = 104768052893827384' 'Fri Aug 28 17:53:50 BST 2020' '0' '*/5 # * # * # * # * # * # * # UTC # null # null # true # printSchedule # 0' .  Last timer expiration occurred at Fri Aug 28 17:53:55 BST 2020]]

[2020-08-28T17:54:47.372+0100] [Payara 5.2020.4-SNAPSHOT] [INFO] [] [fish.payara.nucleus.cluster.PayaraCluster] [tid: _ThreadID=123 _ThreadName=Executor-Service-7] [timeMillis: 1598633687372] [levelValue: 800] [[

  Data Grid Status 

Payara Data Grid State: DG Version: 35 DG Name: development DG Size: 1

Instances: {

 DataGrid: development Instance Group: MicroShoal Name: server Lite: false This: true UUID: 6a319a8d-6aab-4d0b-9a56-bc51c5e36796 Address: /172.20.213.124:4900

}]]



[2020-08-28T17:54:47.373+0100] [Payara 5.2020.4-SNAPSHOT] [INFO] [NCLS-CORE-00017] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1598633687373] [levelValue: 800] [[

  Payara Server  5 #badassfish (${build.number}) startup time : Felix (1,932ms), startup services(12,900ms), total(14,832ms)]]
```

**Comment by stf-pay** [comment]
Nevermind.

The cause may have been a backup+restore migration from GF where we may have screwed up the domain.xml this way...

However, the H2 DB was empty (no tables). I do not see why this would have been the case... maybe restore removes the original default DB (that contains the timer DB table)... However, this could be mentioned in the documentation though.
