### ISSUE TITLE
Embedded Payara is unable to start

### ISSUE THREAD

**Issue by sgflt** [payara/Payara#4861]
# Description #
----------
Payara embedded cannot start because of changed logcation of domain.xml. A new domain.xml has been introduced in issue https://github.com/payara/Payara/pull/2735 but the default implementation has the old path.

EmbeddedDomainXml:85
```
        return EmbeddedDomainXml.class.getClassLoader().getResource("org/glassfish/embed/domain.xml");
```

## Current Outcome
```
Caused by: java.lang.NullPointerException
        at org.glassfish.config.support.ServerReaderFilter.<init>(ServerReaderFilter.java:60)
        at org.glassfish.config.support.DasReaderFilter.<init>(DasReaderFilter.java:53)
        at org.glassfish.config.support.DomainXml.parseDomainXml(DomainXml.java:253)
        at org.glassfish.config.support.DomainXml.run(DomainXml.java:121)
        at org.jvnet.hk2.config.ConfigurationPopulator.populateConfig(ConfigurationPopulator.java:58)
        at org.glassfish.hk2.bootstrap.HK2Populator.populateConfig(HK2Populator.java:83)
        at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.populateConfig(AbstractModulesRegistryImpl.java:190)
        at com.sun.enterprise.module.bootstrap.Main.createServiceLocator(Main.java:249)
        at com.sun.enterprise.glassfish.bootstrap.StaticGlassFishRuntime.newGlassFish(StaticGlassFishRuntime.java:108)
        ... 21 more
```

## Context (Optional)
After change of path to  return EmbeddedDomainXml.class.getClassLoader().getResource("config/domain.xml") embedded Payara is able to parse embedded domain.xml.

## Environment ##

- **Payara Version**: 5.2020.4
- **Edition**: Embedded 
- **JDK Version**: OpenJDK 11 
- **Operating System**: Fedora 32

**Comment by dmatej** [comment]
See the class EmbeddedDomainXml - @sgflt  is probably right, but it also means that the EmbeddedDomainXml class wasn't able to find the domain.xml on new path by it's own classloader, then it tried the old path (why? Makes it sense if we know it is not there any more?).

**Comment by sgflt** [comment]
Created simple test case. I found a method StaticGglassfishRuntime#createTempInstanceRoot. If starting Payara with default instanceroot, default files are copied into temp location. If custom paths are provided via glassfish properties then the default domain.xml should be loaded, but it changed location in mentioned issue.

createTempInstanceRoot content:
`                String[] configFiles = new String[]{"config/keyfile", "config/server.policy", "config/cacerts.jks", "config/keystore.jks", "config/login.conf", "config/logging.properties", "config/loggingToFile.properties", "config/admin-keyfile", "org/glassfish/web/embed/default-web.xml", "config/domain.xml"};`

**Comment by sgflt** [comment]
Checkout https://github.com/sgflt/payara-test-case/commit/ba39ad7c6bd9d0e88d1ec04b8f4c1873598b8226 test is in ear module.

**Comment by AlanRoth** [comment]
PR created by @sgflt #4933

**Comment by AlanRoth** [comment]
Created internal issue `FISH-763`

**Comment by AlanRoth** [comment]
Hi @sgflt, the PR has been merged so I'll be closing the issue.
