### ISSUE TITLE
Restarting Payara fails with Micro payara running

### ISSUE THREAD

**Issue by sameencse** [payara/Payara#4866]
# Description #
----------

## Restarting the payara server should start without any issue

 Deploying web application on full payara 5.194, which is deploying fine, now i have one more small web application which i am deploying on micro payara 5.194 on same machine which is also fine, the problems occur when i try to restart the full payar getting the below exception.

Below are the server logs:
[#|2020-09-01T16:26:10.180+0530|INFO|Payara 5.194|com.hazelcast.nio.tcp.TcpIpConnector|_ThreadID=215;_ThreadName=hz._hzInstance_4_development.cached.thread-2;_TimeMillis=1598957770180;_LevelValue=800;|
  [192.168.43.74]:4900 [development] [3.12] Connecting to /10.20.10.30:5900, timeout: 10000, bind-any: true|#]

[#|2020-09-01T16:26:10.184+0530|INFO|Payara 5.194|com.hazelcast.nio.tcp.TcpIpConnection|_ThreadID=217;_ThreadName=hz._hzInstance_4_development.IO.thread-in-0;_TimeMillis=1598957770184;_LevelValue=800;|
  [192.168.43.74]:4900 [development] [3.12] Initialized new cluster connection between /192.168.43.74:55543 and /192.168.43.74:5900|#]

[#|2020-09-01T16:26:19.272+0530|SEVERE|Payara 5.194|com.hazelcast.cluster|_ThreadID=201;_ThreadName=hz._hzInstance_4_development.priority-generic-operation.thread-0;_TimeMillis=1598957779272;_LevelValue=1000;|
  [192.168.43.74]:4900 [development] [3.12] Node could not join cluster. A Configuration mismatch was detected: Incompatible joiners! expected: multicast, found: tcp-ip Node is going to shutdown now!|#]

[#|2020-09-01T16:26:19.272+0530|WARNING|Payara 5.194|com.hazelcast.instance.Node|_ThreadID=201;_ThreadName=hz._hzInstance_4_development.priority-generic-operation.thread-0;_TimeMillis=1598957779272;_LevelValue=900;|
  [192.168.43.74]:4900 [development] [3.12] Terminating forcefully...|#]

[#|2020-09-01T16:26:19.273+0530|INFO|Payara 5.194|com.hazelcast.instance.Node|_ThreadID=201;_ThreadName=hz._hzInstance_4_development.priority-generic-operation.thread-0;_TimeMillis=1598957779273;_LevelValue=800;|
  [192.168.43.74]:4900 [development] [3.12] Shutting down connection manager...|#]

[#|2020-09-01T16:26:19.276+0530|INFO|Payara 5.194|com.hazelcast.nio.tcp.TcpIpConnector|_ThreadID=215;_ThreadName=hz._hzInstance_4_development.cached.thread-2;_TimeMillis=1598957779276;_LevelValue=800;|
  [192.168.43.74]:4900 [development] [3.12] Could not connect to: /10.20.10.30:5900. Reason: AsynchronousCloseException[null]|#]

[#|2020-09-01T16:26:19.277+0530|INFO|Payara 5.194|com.hazelcast.internal.cluster.impl.DiscoveryJoiner|_ThreadID=215;_ThreadName=hz._hzInstance_4_development.cached.thread-2;_TimeMillis=1598957779277;_LevelValue=800;|
  [192.168.43.74]:4900 [development] [3.12] [10.20.10.30]:5900 is added to the blacklist.|#]

[#|2020-09-01T16:26:19.278+0530|INFO|Payara 5.194|com.hazelcast.nio.tcp.TcpIpConnection|_ThreadID=201;_ThreadName=hz._hzInstance_4_development.priority-generic-operation.thread-0;_TimeMillis=1598957779278;_LevelValue=800;|
  [192.168.43.74]:4900 [development] [3.12] Connection[id=1, /192.168.43.74:55543->/192.168.43.74:5900, qualifier=null, endpoint=[192.168.43.74]:5900, alive=false, type=MEMBER] closed. Reason: EndpointManager is stopping|#]

[#|2020-09-01T16:26:19.289+0530|INFO|Payara 5.194|com.hazelcast.instance.Node|_ThreadID=201;_ThreadName=hz._hzInstance_4_development.priority-generic-operation.thread-0;_TimeMillis=1598957779289;_LevelValue=800;|
  [192.168.43.74]:4900 [development] [3.12] Shutting down node engine...|#]

[#|2020-09-01T16:26:19.301+0530|INFO|Payara 5.194|com.hazelcast.instance.NodeExtension|_ThreadID=201;_ThreadName=hz._hzInstance_4_development.priority-generic-operation.thread-0;_TimeMillis=1598957779301;_LevelValue=800;|
  [192.168.43.74]:4900 [development] [3.12] Destroying node NodeExtension.|#]

[#|2020-09-01T16:26:19.301+0530|INFO|Payara 5.194|com.hazelcast.instance.Node|_ThreadID=201;_ThreadName=hz._hzInstance_4_development.priority-generic-operation.thread-0;_TimeMillis=1598957779301;_LevelValue=800;|
  [192.168.43.74]:4900 [development] [3.12] Hazelcast Shutdown is completed in 29 ms.|#]

[#|2020-09-01T16:26:20.258+0530|SEVERE|Payara 5.194|com.hazelcast.instance.Node|_ThreadID=23;_ThreadName=RunLevelControllerThread-1598957650901;_TimeMillis=1598957780258;_LevelValue=1000;|
  [192.168.43.74]:4900 [development] [3.12] Could not join cluster. Shutting down now!|#]

[#|2020-09-01T16:26:20.259+0530|INFO|Payara 5.194|com.hazelcast.core.LifecycleService|_ThreadID=23;_ThreadName=RunLevelControllerThread-1598957650901;_TimeMillis=1598957780259;_LevelValue=800;|
  [192.168.43.74]:4900 [development] [3.12] [192.168.43.74]:4900 is SHUTTING_DOWN|#]

[#|2020-09-01T16:26:20.259+0530|INFO|Payara 5.194|com.hazelcast.instance.Node|_ThreadID=23;_ThreadName=RunLevelControllerThread-1598957650901;_TimeMillis=1598957780259;_LevelValue=800;|
  [192.168.43.74]:4900 [development] [3.12] Node is already shutting down... Waiting for shutdown process to complete...|#]

[#|2020-09-01T16:26:20.260+0530|INFO|Payara 5.194|com.hazelcast.core.LifecycleService|_ThreadID=23;_ThreadName=RunLevelControllerThread-1598957650901;_TimeMillis=1598957780260;_LevelValue=800;|
  [192.168.43.74]:4900 [development] [3.12] [192.168.43.74]:4900 is SHUTDOWN|#]

[#|2020-09-01T16:26:20.261+0530|WARNING|Payara 5.194|com.hazelcast.util.PhoneHome|_ThreadID=23;_ThreadName=RunLevelControllerThread-1598957650901;_TimeMillis=1598957780261;_LevelValue=900;|
  [192.168.43.74]:4900 [development] [3.12] Could not schedule phone home task! Most probably Hazelcast failed to start.|#]

[#|2020-09-01T16:26:20.267+0530|INFO|Payara 5.194|com.hazelcast.instance.Node|_ThreadID=23;_ThreadName=RunLevelControllerThread-1598957650901;_TimeMillis=1598957780267;_LevelValue=800;|
  [192.168.43.74]:4900 [development] [3.12] Node is already shutting down... Waiting for shutdown process to complete...|#]

[#|2020-09-01T16:26:20.267+0530|WARNING|Payara 5.194|javax.enterprise.system.core|_ThreadID=23;_ThreadName=RunLevelControllerThread-1598957650901;_TimeMillis=1598957780267;_LevelValue=900;_MessageID=NCLS-CORE-00069;|
  Exception while dispatching an event
java.lang.IllegalStateException: Node failed to start!
        at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:138)
        at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:228)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:207)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:157)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57)
        at fish.payara.nucleus.hazelcast.HazelcastCore.bootstrapHazelcast(HazelcastCore.java:478)
        at fish.payara.nucleus.hazelcast.HazelcastCore.event(HazelcastCore.java:264)
        at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
        at com.sun.enterprise.v3.server.ApplicationLoaderService.postConstruct(ApplicationLoaderService.java:329)
        at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:303)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
        at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
|#]

[#|2020-09-01T16:26:20.386+0530|SEVERE|Payara 5.194|javax.enterprise.system.core|_ThreadID=1;_ThreadName=main;_TimeMillis=1598957780386;_LevelValue=1000;_MessageID=NCLS-CORE-00014;|
  Shutdown required
MultiException stack 1 of 2
MultiException stack 1 of 2
java.lang.IllegalStateException: Node failed to start!
        at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:138)
        at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:228)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:207)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:157)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57)
        at fish.payara.nucleus.hazelcast.HazelcastCore.bootstrapHazelcast(HazelcastCore.java:478)
        at fish.payara.nucleus.hazelcast.HazelcastCore.getInstance(HazelcastCore.java:234)
        at fish.payara.monitoring.store.InMemoryMonitoringDataRepository.init(InMemoryMonitoringDataRepository.java:147)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1268)
        at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:309)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
        at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpOneLevel.run(CurrentTaskFuture.java:762)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
MultiException stack 2 of 2
java.lang.IllegalStateException: Unable to perform operation: post construct on fish.payara.monitoring.store.InMemoryMonitoringDataRepository
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:369)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
        at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpOneLevel.run(CurrentTaskFuture.java:762)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
MultiException stack 2 of 2
MultiException stack 1 of 2
java.lang.IllegalStateException: Node failed to start!
        at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:138)
        at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:228)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:207)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:157)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57)
        at fish.payara.nucleus.hazelcast.HazelcastCore.bootstrapHazelcast(HazelcastCore.java:478)
        at fish.payara.nucleus.hazelcast.HazelcastCore.getInstance(HazelcastCore.java:234)
        at fish.payara.nucleus.store.ClusteredStore.get(ClusteredStore.java:184)
        at fish.payara.nucleus.microprofile.config.source.ClusterConfigSource.getValue(ClusterConfigSource.java:80)
        at fish.payara.nucleus.microprofile.config.spi.PayaraConfig.getValue(PayaraConfig.java:166)
        at fish.payara.nucleus.microprofile.config.spi.PayaraConfig.getOptionalValue(PayaraConfig.java:88)
        at fish.payara.microprofile.healthcheck.HealthCheckService.postConstruct(HealthCheckService.java:120)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1268)
        at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:309)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
        at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
MultiException stack 2 of 2
java.lang.IllegalStateException: Unable to perform operation: post construct on fish.payara.microprofile.healthcheck.HealthCheckService
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:369)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
        at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
|#]

[#|2020-09-01T16:26:20.387+0530|SEVERE|Payara 5.194|javax.enterprise.system.core|_ThreadID=1;_ThreadName=main;_TimeMillis=1598957780387;_LevelValue=1000;|
  Failed to start, exiting|#]

[#|2020-09-01T16:26:20.388+0530|INFO|Payara 5.194||_ThreadID=1;_ThreadName=main;_TimeMillis=1598957780388;_LevelValue=800;|
  FileMonitoring shutdown|#]

[#|2020-09-01T16:26:20.455+0530|INFO|Payara 5.194||_ThreadID=23;_ThreadName=RunLevelControllerThread-1598957650901;_TimeMillis=1598957780455;_LevelValue=800;|
  JdbcRuntimeExtension,  getAllSystemRAResourcesAndPools = [GlassFishConfigBean.org.glassfish.jdbc.config.JdbcResource, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcResource, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcResource, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcResource]|#]

[#|2020-09-01T16:26:20.464+0530|INFO|Payara 5.194|javax.enterprise.resource.resourceadapter.com.sun.enterprise.connectors.service|_ThreadID=239;_ThreadName=Thread-17;_TimeMillis=1598957780464;_LevelValue=800;|
  RAR7094: __ds_jdbc_ra shutdown successful.|#]

## Context (Optional)

Want to run full payara and micro payara on same machine with different web application to be deployed on  
## Environment ##

- **Payara Version**: 5.194
- **Edition**: Full
- **JDK Version**: Java/AdoptOpenJDK/11
- **Operating System**: Windows
- **Database**: SQL Server

Could you please help me to resolve this issue ASAP

**Comment by sgflt** [comment]
Did you tried the latest version?

**Comment by sameencse** [comment]
nope

**Comment by sameencse** [comment]
Disabling the Hazelcast works fine with the above scenario, issue is happening when the hazelcast is enabled..could you please confirm is this an issue with the payara?

**Comment by smillidge** [comment]
This isn't an issue with Payara this is an issue with your configuration. Payara Server and Payara Micro are trying to form a cluster together. As stated by the SEVERE log message.

You can fix by running Payara Micro with `--nocluster` command option.

```[#|2020-09-01T16:26:19.272+0530|SEVERE|Payara 5.194|com.hazelcast.cluster|_ThreadID=201;_ThreadName=hz._hzInstance_4_development.priority-generic-operation.thread-0;_TimeMillis=1598957779272;_LevelValue=1000;|
[192.168.43.74]:4900 [development] [3.12] Node could not join cluster. A Configuration mismatch was detected: Incompatible joiners! expected: multicast, found: tcp-ip Node is going to shutdown now!|#]```

**Comment by sameencse** [comment]
@smillidge Thanks for your response..with --nocluster it is working fine(i am able to restart the full payara)
Incase if want to administer micro payara from payara server then what is the solution.

**Comment by sameencse** [comment]
This issue is closed without proper solution,(Incase if want to administer micro payara from payara server then what is the solution.)

**Comment by OndroMih** [comment]
Payara Micro uses a different Data Grid joiner (multicast joiner) than Payara Server (domain joiner). To connect them together, they must use the same joiner. The recommended way is to use the domain joiner for both: https://docs.payara.fish/community/docs/5.2021.1/documentation/payara-micro/clustering/clustering-with-full-server.html
