### ISSUE TITLE
Payara Micro fails to run using payara-micro-maven-plugin on Windows

### ISSUE THREAD

**Issue by sharpedavid** [payara/Payara#4943]
# Description #
----------

I can't run Payara Micro on Windows 10 using the example from https://start.microprofile.io/. It's the same issue as https://github.com/payara/Payara/issues/4445, but that was closed with no real resolution, unless the answer is "Payara Micro is incompatible with Windows".

I should emphasize this that demo code is **minimal**. It contains a single JAX-RS resource. There are no configuration files. It's built using `payara-micro-maven-plugin`. **This bug is not about bad demo code, it's about Payara Micro or perhaps the `payara-micro-maven-plugin`.**

## Expected Outcome

Payara Micro should run on Windows.

## Current Outcome

Payara Micro does not run.

```
$ java -jar target/demo-microbundle.jar
Oct. 09, 2020 9:05:32 A.M. fish.payara.micro.PayaraMicro main
SEVERE: null
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:50)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:114)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:73)
        at fish.payara.micro.boot.PayaraMicroLauncher.create(PayaraMicroLauncher.java:87)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:71)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:467)
Caused by: java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
        at java.base/java.util.Properties.loadConvert(Properties.java:675)
        at java.base/java.util.Properties.load0(Properties.java:452)
        at java.base/java.util.Properties.load(Properties.java:404)
        at fish.payara.micro.impl.PayaraMicroImpl.setBootProperties(PayaraMicroImpl.java:2577)
        at fish.payara.micro.impl.PayaraMicroImpl.create(PayaraMicroImpl.java:213)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:208)
        ... 10 more
```

## Steps to reproduce (Only for bug reports) 

Generate a project on https://start.microprofile.io/

![image](https://user-images.githubusercontent.com/1767127/95607705-fae50680-0a10-11eb-9863-cfa0d10e4aee.png)

Unzip. 
`mvn clean package`
` java -jar target/demo-microbundle.jar`

## Environment ##

- **Payara Version**: 5.2020.2
- **Edition**: Micro
- **JDK Version**: $ openjdk version "11.0.5" 2019-10-15
- **Operating System**: Windows 10
- **Database**: None

**Comment by sharpedavid** [comment]
Here's my theory. Based on https://github.com/payara/Payara/issues/4445, it seems likely to me that this is caused by files like `target\demo-microbundle.jar\MICRO-INF\payara-boot.properties`, which contains file paths like `java.library.path=C:\Dev\AdoptOpenJDK11\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Users\david.a.sharpe`. The theory is paths containing `\u` causes unicode interpretation, which causes the "Malformed \uxxxx encoding" error. The problem is this isn't a configuration file in the demo itself: it's a generated file. I assume generated by the `payara-micro-maven-plugin`. There is nothing wrong with the demo code, and there's no opportunity for a user to fix it.

**Comment by AlanRoth** [comment]
Hi @sharpedavid, I was not able to reproduce this in the latest release using the details you have provided. The only thing I can suggest currently is to try to reproduce the issue in the latest release, and if you're still having troubles in the latest release is to try the advice in #4445 or tp provide a alternative reproducer - otherwise the issue will have to be closed.

**Comment by sharpedavid** [comment]
Thanks for getting back to me @AlanRoth. I'll try this morning (PST) with the latest version.

**Comment by sharpedavid** [comment]
@AlanRoth you were right, this works with the latest release of `payara-micro-maven-plugin`. If you create a project from https://start.microprofile.io/, it uses version 1.0.1, but the latest version is 1.0.5. I will open an issue on that project.
