### ISSUE TITLE
SOAP webservice can not respond if deployed into embedded Payara

### ISSUE THREAD

**Issue by sgflt** [payara/Payara#4953]
# Description #
----------
After migration from Payara 4 to Payara 5 an integration test fails because embedded Payara cannot handle SOAP request.

## Expected Outcome
SOAP request processed without NullPointerException.

## Current Outcome
```
MonitoringPipe:172

if (seiModel instanceof SOAPSEIModel) {
           SOAPSEIModel soapSEIModel = (SOAPSEIModel) seiModel;
            Globals.get(MonitorFilter.class)
                   .filterRequest( // throws NPE
```

```
20:31:14,906  INFO [main] test.client.WSClient:48  : url=http://localhost:34687/webservice/test-url
říj 15, 2020 8:31:14 ODP. com.sun.enterprise.security.webservices.CommonServerSecurityPipe processRequest
SEVERE: Request processing failed.
java.lang.NullPointerException
        at org.glassfish.webservices.MonitoringPipe.firePreInvocation(MonitoringPipe.java:173)
        at org.glassfish.webservices.MonitoringPipe.process(MonitoringPipe.java:134)
        at com.sun.xml.ws.api.pipe.helper.PipeAdapter.processRequest(PipeAdapter.java:89)
        at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:1106)
        at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:1020)
        at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:989)
        at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:847)
        at com.sun.xml.ws.api.pipe.helper.AbstractTubeImpl.process(AbstractTubeImpl.java:106)
        at com.sun.enterprise.security.webservices.CommonServerSecurityPipe.processRequest(CommonServerSecurityPipe.java:195)
        at com.sun.enterprise.security.webservices.CommonServerSecurityPipe.process(CommonServerSecurityPipe.java:134)
        at com.sun.xml.ws.api.pipe.helper.PipeAdapter.processRequest(PipeAdapter.java:89)
        at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:1106)
        at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:1020)
        at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:989)
        at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:847)
        at com.sun.xml.ws.server.WSEndpointImpl$2.process(WSEndpointImpl.java:389)
        at com.sun.xml.ws.transport.http.HttpAdapter$HttpToolkit.handle(HttpAdapter.java:838)
        at com.sun.xml.ws.transport.http.HttpAdapter.handle(HttpAdapter.java:392)
        at com.sun.xml.ws.transport.http.servlet.ServletAdapter.handle(ServletAdapter.java:139)
        at org.glassfish.webservices.Ejb3MessageDispatcher.handlePost(Ejb3MessageDispatcher.java:110)
        at org.glassfish.webservices.Ejb3MessageDispatcher.invoke(Ejb3MessageDispatcher.java:80)
        at org.glassfish.webservices.EjbWebServiceServlet.dispatchToEjbEndpoint(EjbWebServiceServlet.java:244)
        at org.glassfish.webservices.EjbWebServiceServlet.service(EjbWebServiceServlet.java:169)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.glassfish.grizzly.servlet.ServletHandler.doServletService(ServletHandler.java:204)
        at org.glassfish.grizzly.servlet.ServletHandler.service(ServletHandler.java:154)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

## Context (Optional)

Tried to enable opentracing but the NPE is still thrown.

```
   runCommand(
        "set-requesttracing-configuration",
        "--enabled=true",
        "--dynamic=true"
    );
    runCommand(
        "bootstrap-requesttracing"
    );
```
```

říj 15, 2020 8:31:13 ODP. org.glassfish.deployment.admin.DeployCommand execute
INFO: app-1.4-SNAPSHOT was successfully deployed in 4 568 milliseconds.

```

## Environment ##

- **Payara Version**: 5.2020.4
- **Edition**: Embedded 
- **JDK Version**: OpenJDK 11 
- **Operating System**: Fedora 32

**Comment by AlanRoth** [comment]
Hi @sgflt, can you please provide a simple to follow scenario how to reproduce this on 5.2020.6 release of Payara Community Edition? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. It will greatly help us to find the cause and fix it.

**Comment by AlanRoth** [comment]
Hi @sgflt, are you able to provide a reproducer?

**Comment by sgflt** [comment]
Hi @AlanRoth, of course I should be able to do it, but I need more time to extract test case.

**Comment by AlanRoth** [comment]
Hi @sgflt, any updates?

**Comment by sgflt** [comment]
Trying to run through Arquillian hell. I've just found that the failing code in embedded returns in server-full JaxwsContainerRequestTracing instance. So it is definitely related to initialization of request tracing.

Now I am trying to understand where is request tracing being initialized and how.

**Comment by sgflt** [comment]
ServiceLocatorImpl#internalGetDescriptor returns null for MonitorFilter.class in embedded.

**Comment by sgflt** [comment]
Caused by PAYARA-3385.  Seems it is only packaging problem. Will create PR with fix.

**Comment by AlanRoth** [comment]
Hi @sgflt, thank you very much for offering to create a PR, we really do appreciate it!

**Comment by AlanRoth** [comment]
Hi @sgflt, any status updates?

**Comment by sgflt** [comment]
Hi @AlanRoth, commits are already merged so we can close this issue. Anyway I have to do embedded test case for another issue related to Arquillian and JUnit5. The test case could be used to verify this issue.
