### ISSUE TITLE
SSLEngine Consuming 100% CPU

### ISSUE THREAD

**Issue by mzaum** [payara/Payara#4987]
# Description #
----------

With TLSv1.3 enabled, threads in the connection thread pool can get stuck spinning indefinitely, consuming 100% CPU.

Using top & jcmd, I was able to grab a stack trace of one of the offending threads:

`"engineering-thread-pool::engineering-listener(10)" #201 daemon prio=5 os_prio=0 tid=0x00007f7ae0a5b000 nid=0x6b2d runnable [0x00007f79f25a1000]
   java.lang.Thread.State: RUNNABLE
        at sun.security.ssl.SSLEngineImpl.wrap(SSLEngineImpl.java:130)
        - locked <0x00000005c97691b8> (a sun.security.ssl.SSLEngineImpl)
        at sun.security.ssl.SSLEngineImpl.wrap(SSLEngineImpl.java:110)
        - locked <0x00000005c97691b8> (a sun.security.ssl.SSLEngineImpl)
        at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:471)
        at org.glassfish.grizzly.ssl.SSLUtils.sslEngineWrap(SSLUtils.java:427)
        at org.glassfish.grizzly.ssl.SSLConnectionContext.wrap(SSLConnectionContext.java:337)
        at org.glassfish.grizzly.ssl.SSLUtils.handshakeWrap(SSLUtils.java:303)
        at org.glassfish.grizzly.ssl.SSLBaseFilter.doHandshakeStep(SSLBaseFilter.java:678)
        at org.glassfish.grizzly.ssl.SSLBaseFilter.doHandshakeSync(SSLBaseFilter.java:583)
        at org.glassfish.grizzly.ssl.SSLBaseFilter.silentRehandshake(SSLBaseFilter.java:801)
        at org.glassfish.grizzly.ssl.SSLBaseFilter.unwrapAll(SSLBaseFilter.java:415)
        at org.glassfish.grizzly.ssl.SSLBaseFilter.handleRead(SSLBaseFilter.java:297)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.lang.Thread.run(Thread.java:748) 
`

## Expected Outcome

Reasonable CPU usage.

## Current Outcome

100% CPU usage.

## Steps to reproduce (Only for bug reports) 

Enable TLSv1.3 and add load to the server.

## Environment ##

- **Payara Version**: 5.2020.5
- **Edition**:  Web
- **JDK Version**:  OpenJDK 64-Bit Server VM Corretto-8.275.01.1 (build 25.275-b01, mixed mode)
- **Operating System**: Ubuntu 16.04
- **Database**:  MySQL

**Comment by dmatej** [comment]
I'm not sure if this could be a bug in Payara, so I tried to seach in OpenJDK's JIRA:
https://bugs.openjdk.java.net/browse/JDK-8237578?jql=project%20%3D%20JDK%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20New)%20AND%20component%20%3D%20security-libs%20AND%20text%20~%20%22wrap%22%20AND%20Subcomponent%20in%20(javax.net.ssl%2C%20javax.net.ssl%2C%20javax.net.ssl%2C%20javax.net.ssl)
It might be also an issue of Grizzly, we have to dig deeper ... but I would expect that more probable is a bug in JDK ...

**Comment by MeroRai** [comment]
Hi @mzaum, 

Could you test it on the latest release of the Zulu JDK to confirm if it is an issue in the Payara Server?

Kind regards,
Susan Rai

**Comment by MeroRai** [comment]
Hi @mzaum,

Could I get an update on this issue? Have you managed to test it on the latest release of the Zulu JDK?

Kind regards,
Susan Rai

**Comment by MeroRai** [comment]
Hi @mzaum,

Hi, since we haven’t received any updates from you, we’ll proceed to close this issue. Feel free to re-open it in the future if you are able to reproduce the problem successfully using the current release of Payara Community Edition and the latest release of the Zulu JDK. 

Kind regards,
Susan Rai
