### ISSUE TITLE
Payara micro docker post boot command create-jvm-options always fails to parse correctly / FISH-757

### ISSUE THREAD

**Issue by fkaempfer** [payara/Payara#4992]
# Description #
----------
I'm trying to create jvm options in a post boot script for payara micro's docker image. I tried several ways of escaping the jvm options but it never seems to work. Here's how to test it:
Create a `postbootcommands` file:

`create-jvm-options -server:-Xmx2048:-Xms2048` 

(example from https://docs.payara.fish/enterprise/docs/5.22.0/documentation/payara-micro/asadmin/pre-and-post-boot-scripts.html)

Boot up payara micro:
`docker run -v $(pwd)/postbootcommands:/pb:ro,Z --rm -it payara/micro:latest --postbootcommandfile /pb`

This produces the following exception:
```
[2020-11-14T09:17:31.211+0000] [] [WARNING] [] [fish.payara.boot.runtime.BootCommand] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1605345451211] [levelValue: 900] [[
  Boot Command create-jvm-options failed Exception while executing command. 
org.glassfish.api.admin.CommandValidationException: Invalid option: -server:-Xmx2048:-Xms2048
        at com.sun.enterprise.admin.cli.Parser.parseCommandLine(Parser.java:254)
        at com.sun.enterprise.admin.cli.Parser.<init>(Parser.java:96)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.getParameters(CommandExecutorImpl.java:116)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:177)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:96)
        at fish.payara.boot.runtime.BootCommand.execute(BootCommand.java:69)
        at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:136)
        at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:130)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1050)
        at fish.payara.micro.impl.PayaraMicroImpl.create(PayaraMicroImpl.java:227)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:214)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:50)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:114)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:73)
        at fish.payara.micro.boot.PayaraMicroLauncher.create(PayaraMicroLauncher.java:88)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:72)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:467)
]]
```
It seems like it's trying to parse the jvm option as part of the asadmin command. Or perhaps I did something wrong?

## Expected Outcome

The JVM options should be created without error.

## Current Outcome

The exception above.

## Steps to reproduce (Only for bug reports) 
See docker command above

## Context (Optional)

Podman 2.1.1

## Environment ##

payara:micro-latest (fresh pull)

**Comment by AlanRoth** [comment]
Hi @fkaempfer, I have reproduced this issue in the latest version, as well as previous versions. I have created an internal issue `FISH-757` to resolve this.

**Comment by silvafabio** [comment]
Hey Guys

Same problem here with payara/server-full:5.194.

For me the workaround was to add an (\) in the first (-).

From: create-jvm-options -Xmx1024m:-Xms1024m
To: create-jvm-options \-Xmx1024m:-Xms1024m

Hope that's help ;-)

**Comment by thehpi** [comment]
The problem is that the post boot commands are being processed by

    com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl

which uses

    com.sun.enterprise.admin.cli.Parser

and this class handles the arguments as if they were given to the asadmin command which accepts options and operands and the - is seen as an option while it is an operand.

Putting -- right after create-jvm-options also tells it to handle all arguments as operands.

The backslash works too but this could be seen as a but because only the first char is checked and if it doesn't start with a - then its seen as an operand.

I guess fixing this problem will actually break the startup of a lot of people who are using boot scripts so maybe its better change the docs :)

**Comment by helmchen** [comment]
Thanks @thehpi 

Your suggestions works in my case. create-jvm-options is now parsed correctly as well as delete-jvm-options 

```
delete-jvm-options --target=server-config -- "-client"
delete-jvm-options --target=server-config -- "-Xmx1024"
delete-jvm-options --target=server-config -- "-Xms512"
create-jvm-options --target=server-config -- "-Djava.awt.headless\=true"
create-jvm-options --target=server-config -- "-Djava.security.manager\=true"
create-jvm-options --target=server-config -- "-server"
create-jvm-options --target=server-config -- "-Xmx2048"
create-jvm-options --target=server-config -- "-Xms2048"
create-jvm-options --target=server-config -- "-Djdk.tls.rejectClientInitiatedRenegotiation\=true"
create-jvm-options --target=server-config -- "-Dfish.payara.classloading.delegate\=false"
create-jvm-options --target=server-config -- "-XX\:+UseG1GC"
create-jvm-options --target=server-config -- "-XX\:+DisableExplicitGC"
```

**Comment by AlanRoth** [comment]
Hi @fkaempfer,

As @thehpi, it may be better to update our documentation to cover this use case - as the 'workaround' shared by @silvafabio and tested by @helmchen are the expected ways of escaping and configuring the parameters.

We will update our documentation, there is no further action needed.

Thank you for your patience,
Alan
