### ISSUE TITLE
EjbDeployer.event logic is incorrect on creation of EJB Timers

### ISSUE THREAD

**Issue by dmatej** [payara/Payara#509]
Code is readable, but there is too many variants. Our case is that we have only nonpersistent timers in clustered application. But application does not start in clustered instances due to missing tables in timer database.
I think I can fix this problem (check schedules and if all are not persistent, we don't need the database), but there is another one - if we would use the persistent timers, problem would be back again.
This will take a little bit more time to check all conditions around that ...

**Comment by dmatej** [comment]
There is also some "voodoo" in EjbDeployer line 583 (method getOwnerId) - zero is not allowed as upper bound: int useInstance = random.nextInt(instances.size()); It causes IllegalArgumentException if there are no instances in cluster (but this is valid!), what should be an owner? Do we need an owner?
What if we start another instance as the first one?

**Comment by dmatej** [comment]
In method clean is also some manipulation with the policy ... it may be connected somehow with the problem with redeploys ... Another our applications without timers have no such problem ...

**Comment by smillidge** [comment]
We are doing some work in the depths of the EJBTimer code as well as with deployment of timers at the moment. There are a number of issues with this code and we are considering a complete refactoring.

**Comment by smillidge** [comment]
Clustered Persistent EJB Timers only fire on a single node in the cluster therefore there is code in there to work out the owner (via the database). I would need to check the semantics of clustered non-persistent EJB Timers. What semantics are you expecting?

We are also in the middle of integrating the embedded Hazelcast Data Grid as a "persistent" EJB Timer store.

**Comment by dmatej** [comment]
Okay, this is nice to hear. I don't know if I can help somehow ... I got only this server log from one instance:
```
[2015-11-03T17:53:50.116+0100] [Payara 4.1] [INFO] [] [javax.enterprise.system.container.ejb.com.sun.ejb.containers] [tid: _ThreadID=15 _ThreadName=RunLevelControllerThread-1446569598689] [timeMillis: 1446569630116] [levelValue: 800] [[
  Loading EJBTimerService. Please wait.]]

[2015-11-03T17:53:50.750+0100] [Payara 4.1] [INFO] [AS-EJB-00054] [javax.enterprise.ejb.container] [tid: _ThreadID=15 _ThreadName=RunLevelControllerThread-1446569598689] [timeMillis: 1446569630750] [levelValue: 800] [[
  Portable JNDI names for EJB TimerBean: [java:global/ejb-timer-service-app/TimerBean, java:global/ejb-timer-service-app/TimerBean!org.glassfish.ejb.persistent.timer.TimerLocal]]]

[2015-11-03T17:53:50.871+0100] [Payara 4.1] [INFO] [] [] [tid: _ThreadID=15 _ThreadName=Thread-8] [timeMillis: 1446569630871] [levelValue: 800] [[
  name=com.sun.logging.enterprise.system.container.web, classLoader=org.glassfish.main.security.websecurity [30]]]

[2015-11-03T17:53:50.898+0100] [Payara 4.1] [INFO] [AS-WEB-GLUE-00172] [javax.enterprise.web] [tid: _ThreadID=15 _ThreadName=RunLevelControllerThread-1446569598689] [timeMillis: 1446569630898] [levelValue: 800] [[
  Loading application [ejb-timer-service-app] at [/ejb-timer-service-app]]]

[2015-11-03T17:53:50.907+0100] [Payara 4.1] [INFO] [] [javax.enterprise.system.container.ejb.com.sun.ejb.containers] [tid: _ThreadID=15 _ThreadName=RunLevelControllerThread-1446569598689] [timeMillis: 1446569630907] [levelValue: 800] [[
  EJB5109:EJB Timer Service started successfully for data source [jdbc/__TimerPool]]]

[2015-11-03T17:53:50.908+0100] [Payara 4.1] [INFO] [] [javax.enterprise.system.container.ejb.com.sun.ejb.containers] [tid: _ThreadID=15 _ThreadName=RunLevelControllerThread-1446569598689] [timeMillis: 1446569630908] [levelValue: 800] [[
  ==> Restoring Timers ... ]]

[2015-11-03T17:53:50.954+0100] [Payara 4.1] [WARNING] [] [org.eclipse.persistence.default] [tid: _ThreadID=15 _ThreadName=RunLevelControllerThread-1446569598689] [timeMillis: 1446569630954] [levelValue: 900] [[
  
java.lang.NullPointerException
        at org.eclipse.persistence.platform.server.ServerPlatformUtils.createServerPlatform(ServerPlatformUtils.java:99)
        at org.eclipse.persistence.sessions.factories.SessionManager.init(SessionManager.java:77)
        at org.eclipse.persistence.sessions.factories.SessionManager.<clinit>(SessionManager.java:71)
...
[2015-11-03T17:53:50.978+0100] [Payara 4.1] [INFO] [] [org.eclipse.persistence.session./file:/app/appservers/payara4.1.1.161-ICZ151103/glassfish/nodes/karma-cisas1/cis-web/applications/ejb-timer-service-app/WEB-INF/classes/___EJB__Timer__App] [tid: _ThreadID=15 _ThreadName=RunLevelControllerThread-1446569598689] [timeMillis: 1446569630978] [levelValue: 800] [[
  EclipseLink, version: Eclipse Persistence Services - 2.6.1.qualifier]]
```
Oracle said that the NPE is only log message, not error ...
Note two minute delay between next two logs. There is no delay on non-clustered instance.
```
[2015-11-03T17:53:53.144+0100] [Payara 4.1] [WARNING] [] [javax.enterprise.resource.resourceadapter.org.glassfish.jdbc.util] [tid: _ThreadID=199 _ThreadName=Recovery Helper Thread] [timeMillis: 1446569633144] [levelValue: 900] [[
  RAR8068: Using default datasource : __ds_jdbc_ra for pool : ifxCisSis2]]

[2015-11-03T17:55:53.269+0100] [Payara 4.1] [INFO] [] [org.eclipse.persistence.session./file:/app/appservers/payara4.1.1.161-ICZ151103/glassfish/nodes/karma-cisas1/cis-web/applications/ejb-timer-service-app/WEB-INF/classes/___EJB__Timer__App.connection] [tid: _ThreadID=15 _ThreadName=RunLevelControllerThread-1446569598689] [timeMillis: 1446569753269] [levelValue: 800] [[
  /file:/app/appservers/payara4.1.1.161-ICZ151103/glassfish/nodes/karma-cisas1/cis-web/applications/ejb-timer-service-app/WEB-INF/classes/___EJB__Timer__App login successful]]

[2015-11-03T17:55:53.387+0100] [Payara 4.1] [WARNING] [] [org.eclipse.persistence.session./file:/app/appservers/payara4.1.1.161-ICZ151103/glassfish/nodes/karma-cisas1/cis-web/applications/ejb-timer-service-app/WEB-INF/classes/___EJB__Timer__App] [tid: _ThreadID=15 _ThreadName=RunLevelControllerThread-1446569598689] [timeMillis: 1446569753387] [levelValue: 900] [[
  
Local Exception Stack: 
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.1.qualifier): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLSyntaxErrorException: Table/View 'EJB__TIMER__TBL' does not exist.
Error Code: 30000
Call: SELECT "TIMERID", "APPLICATIONID", "BLOB", "CONTAINERID", "CREATIONTIMERAW", "INITIALEXPIRATIONRAW", "INTERVALDURATION", "LASTEXPIRATIONRAW", "OWNERID", "PKHASHCODE", "SCHEDULE", "STATE" FROM "EJB__TIMER__TBL" WHERE (("OWNERID" = ?) AND ("STATE" = ?))
        bind => [2 parameters bound]
Query: ReadAllQuery(name="findTimersByOwnerAndState" referenceClass=TimerState sql="SELECT "TIMERID", "APPLICATIONID", "BLOB", "CONTAINERID", "CREATIONTIMERAW", "INITIALEXPIRATIONRAW", "INTERVALDURATION", "LASTEXPIRATIONRAW", "OWNERID", "PKHASHCODE", "SCHEDULE", "STATE" FROM "EJB__TIMER__TBL" WHERE (("OWNERID" = ?) AND ("STATE" = ?))")
        at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:340)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:684)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:560)
        at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2055)
        at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:570)
        at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:258)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:299)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectAllRows(DatasourceCallQueryMechanism.java:694)
        at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRowsFromTable(ExpressionQueryMechanism.java:2740)
        at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRows(ExpressionQueryMechanism.java:2693)
        at org.eclipse.persistence.queries.ReadAllQuery.executeObjectLevelReadQuery(ReadAllQuery.java:559)
        at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1175)
        at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:904)
        at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1134)
        at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:460)
        at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1222)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1857)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1839)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1804)
        at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:258)
        at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:473)
        at org.glassfish.ejb.persistent.timer.TimerBean.findTimersByOwnerAndState(TimerBean.java:211)
        at org.glassfish.ejb.persistent.timer.TimerBean.findActiveTimersOwnedByThisServer(TimerBean.java:523)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1080)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1152)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:824)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:823)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
        at com.sun.proxy.$Proxy284.findActiveTimersOwnedByThisServer(Unknown Source)
        at org.glassfish.ejb.persistent.timer.PersistentEJBTimerService.restoreEJBTimers(PersistentEJBTimerService.java:367)
        at org.glassfish.ejb.persistent.timer.PersistentEJBTimerService.resetEJBTimers(PersistentEJBTimerService.java:1398)
        at com.sun.ejb.containers.EJBTimerService.initEJBTimerService(EJBTimerService.java:236)
        at com.sun.ejb.containers.EJBTimerService.getEJBTimerService(EJBTimerService.java:205)
        at com.sun.ejb.containers.EJBTimerService.getEJBTimerService(EJBTimerService.java:187)
        at com.sun.ejb.containers.BaseContainer.<init>(BaseContainer.java:825)
        at com.sun.ejb.containers.AbstractSingletonContainer.<init>(AbstractSingletonContainer.java:127)
        at com.sun.ejb.containers.CMCSingletonContainer.<init>(CMCSingletonContainer.java:76)
        at com.sun.ejb.containers.SingletonContainerFactory.createContainer(SingletonContainerFactory.java:68)
        at org.glassfish.ejb.startup.EjbApplication.loadContainers(EjbApplication.java:225)
        at org.glassfish.ejb.startup.EjbDeployer.load(EjbDeployer.java:289)
        at org.glassfish.ejb.startup.EjbDeployer.load(EjbDeployer.java:99)
        at org.glassfish.internal.data.ModuleInfo.load(ModuleInfo.java:206)
        at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:314)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:496)
        at com.sun.enterprise.v3.server.ApplicationLoaderService.processApplication(ApplicationLoaderService.java:406)
        at com.sun.enterprise.v3.server.ApplicationLoaderService.postConstruct(ApplicationLoaderService.java:243)
        at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:326)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:374)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:228)
        at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLSyntaxErrorException: Table/View 'EJB__TIMER__TBL' does not exist.
        at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedPreparedStatement20.<init>(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedPreparedStatement30.<init>(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedPreparedStatement40.<init>(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source)
        at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
        at org.apache.derby.iapi.jdbc.BrokeredConnection.prepareStatement(Unknown Source)
        at com.sun.gjc.spi.base.ConnectionHolder.prepareStatement(ConnectionHolder.java:586)
        at com.sun.gjc.spi.jdbc40.ConnectionWrapper40.prepareCachedStatement(ConnectionWrapper40.java:255)
        at com.sun.gjc.spi.jdbc40.ConnectionWrapper40.prepareCachedStatement(ConnectionWrapper40.java:52)
        at com.sun.gjc.spi.ManagedConnectionImpl.prepareCachedStatement(ManagedConnectionImpl.java:992)
        at com.sun.gjc.spi.jdbc40.ConnectionWrapper40.prepareStatement(ConnectionWrapper40.java:173)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.prepareStatement(DatabaseAccessor.java:1565)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.prepareStatement(DatabaseAccessor.java:1514)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseCall.prepareStatement(DatabaseCall.java:778)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:621)
        ... 78 more
Caused by: java.sql.SQLException: Table/View 'EJB__TIMER__TBL' does not exist.
        at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
        ... 102 more
Caused by: ERROR 42X05: Table/View 'EJB__TIMER__TBL' does not exist.
        at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
        at org.apache.derby.impl.sql.compile.FromBaseTable.bindTableDescriptor(Unknown Source)
        at org.apache.derby.impl.sql.compile.FromBaseTable.bindNonVTITables(Unknown Source)
        at org.apache.derby.impl.sql.compile.FromList.bindTables(Unknown Source)
        at org.apache.derby.impl.sql.compile.SelectNode.bindNonVTITables(Unknown Source)
        at org.apache.derby.impl.sql.compile.DMLStatementNode.bindTables(Unknown Source)
        at org.apache.derby.impl.sql.compile.DMLStatementNode.bind(Unknown Source)
        at org.apache.derby.impl.sql.compile.CursorNode.bindStatement(Unknown Source)
        at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
        at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
        at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
        ... 96 more
```

**Comment by smillidge** [comment]
2 minute delay is likely to be due to the main problem we are investigating at the moment. Do you have TX recovery enabled? If so the delay is because the EJB Timer subsystem tries to access the database before the transaction recovery manager has been run. It therefore waits for 2 minutes for the TX recovery manager which has not yet been initialised. It then gives up after 2 minutes.

**Comment by dmatej** [comment]
It depends on wanted target ... our is only checking for a new configuration, each instance has it's own cfg. So in this case there is no persistence needed and no replication needed.

And yet one note - when I create the cluster, default datasource is automatically enabled there, but timer datasource not. I did not find why ...

**Comment by smillidge** [comment]
Derby is not really recommended for clustered persistent timers as they require a shared database. I would recommend a new datasource be configured for the EJBTimer subsystem.

**Comment by dmatej** [comment]
Yes, TX recovery was enabled, without that it was much faster:
```
Caused by: ERROR XBM0A: The database directory '/app/appservers/payara4.1.1.161-ICZ151103/glassfish/nodes/karma-cisas1/cis-web/lib/databases/ejbtimer' exists. However, it does not contain the expected 'service.properties' file. Perhaps Derby was brought down in the middle of creating this database. You may want to delete this directory and try creating the database again.
        at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
        at org.apache.derby.impl.services.monitor.StorageFactoryService.vetService(Unknown Source)
        at org.apache.derby.impl.services.monitor.StorageFactoryService.access$900(Unknown Source)
        at org.apache.derby.impl.services.monitor.StorageFactoryService$10.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.apache.derby.impl.services.monitor.StorageFactoryService.createServiceRoot(Unknown Source)
        at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(Unknown Source)
        at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(Unknown Source)
        at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Unknown Source)
```
And after deleteing and creating the instance again ...
```
[2015-11-03T18:30:24.639+0100] [Payara 4.1] [INFO] [] [org.eclipse.persistence.session./file:/app/appservers/payara4.1.1.161-ICZ151103/glassfish/nodes/karma-cisas1/cis-web/applications/ejb-timer-service-app/WEB-INF/classes/___EJB__Timer__App.connection] [tid: _ThreadID=15 _ThreadName=RunLevelControllerThread-1446571794715] [timeMillis: 1446571824639] [levelValue: 800] [[
  /file:/app/appservers/payara4.1.1.161-ICZ151103/glassfish/nodes/karma-cisas1/cis-web/applications/ejb-timer-service-app/WEB-INF/classes/___EJB__Timer__App login successful]]

[2015-11-03T18:30:24.706+0100] [Payara 4.1] [WARNING] [] [org.eclipse.persistence.session./file:/app/appservers/payara4.1.1.161-ICZ151103/glassfish/nodes/karma-cisas1/cis-web/applications/ejb-timer-service-app/WEB-INF/classes/___EJB__Timer__App] [tid: _ThreadID=15 _ThreadName=RunLevelControllerThread-1446571794715] [timeMillis: 1446571824706] [levelValue: 900] [[
  
Local Exception Stack: 
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.1.qualifier): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLSyntaxErrorException: Table/View 'EJB__TIMER__TBL' does not exist.
Error Code: 30000
Call: SELECT "TIMERID", "APPLICATIONID", "BLOB", "CONTAINERID", "CREATIONTIMERAW", "INITIALEXPIRATIONRAW", "INTERVALDURATION", "LASTEXPIRATIONRAW", "OWNERID", "PKHASHCODE", "SCHEDULE", "STATE" FROM "EJB__TIMER__TBL" WHERE (("OWNERID" = ?) AND ("STATE" = ?))
        bind => [2 parameters bound]
Query: ReadAllQuery(name="findTimersByOwnerAndState" referenceClass=TimerState sql="SELECT "TIMERID", "APPLICATIONID", "BLOB", "CONTAINERID", "CREATIONTIMERAW", "INITIALEXPIRATIONRAW", "INTERVALDURATION", "LASTEXPIRATIONRAW", "OWNERID", "PKHASHCODE", "SCHEDULE", "STATE" FROM "EJB__TIMER__TBL" WHERE (("OWNERID" = ?) AND ("STATE" = ?))")
```
Yes, but ...
1) We don't need any sharing now
2) I tried to obey that with our Informix database, but it was unsuccessful again.

**Comment by mikecroft** [comment]
Is there still work to do on this, @smillidge? I know the 2 min delay issue has been addressed and we have now [implemented the Hazelcast store for persistent EJB timers in Payara Micro](http://blog.payara.fish/persistent-ejb-timers-in-payara-micro), are there still outstanding items in this to address?

**Comment by fturizo** [comment]
@smillidge, what is the current status of this issue? Is the main problem solved as @mikecroft suggested?

**Comment by smillidge** [comment]
Done as far as I remember
