### ISSUE TITLE
[com.sun.enterprise.module.ResolveError: Failed to start OSGiModuleImpl:: Bundle], and [java.lang.IllegalStateException: Could not load descriptor SystemDescriptor]

### ISSUE THREAD

**Issue by aii-goto-yusaku** [payara/Payara#5108]
# Description #
----------

This is bug(?) report.

I have just downloaded Payara5 2020.7 and started it.
However, it shutdown immediately.

Do you know if this is a problem with my version of Java or if I need to change some settings for domain.xml, environment variables, etc... ?

By the way, the word "情報" in the following log means "Information".

```
//opt/payara5/bin via 🐍 v2.7.16 on ☁️  ap-northeast-1 
15:32:22 ❯ sdk use java 8.0.252-amzn

Using java version 8.0.252-amzn in this shell.
//opt/payara5/bin via 🐍 v2.7.16 on ☁️  ap-northeast-1 
15:32:29 ❯ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment Corretto-8.252.09.1 (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM Corretto-8.252.09.1 (build 25.252-b09, mixed mode)

//opt/payara5/bin via 🐍 v2.7.16 on ☁️  ap-northeast-1 
15:32:33 ❯ ./asadmin start-domain domain1
Waiting for domain1 to start ..Error starting domain domain1.
The server exited prematurely with exit code 1.
Before it died, it produced the following output:

Launching Payara Server on Felix platform
Registered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishRuntime@7cec6e85 in service registry.
Completed shutdown of GlassFish runtime
We are in non-embedded mode, so fish.payara.server.internal.core.glassfish [380] has nothing to do.
Feb 01, 2021 3:32:45 PM com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner createBundleProvisioner
情報: Create bundle provisioner class = class com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner.
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:109)
        at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:54)
Caused by: A MultiException has 2 exceptions.  They are:
1. com.sun.enterprise.module.ResolveError: Failed to start OSGiModuleImpl:: Bundle = [fish.payara.server.internal.payara-appserver-modules.notification-slack-core [324]], State = [NEW]
2. java.lang.IllegalStateException: Could not load descriptor SystemDescriptor(
        implementation=fish.payara.notification.slack.SlackNotifierConfigurationInjector
        name=slack-notifier-configuration
        contracts={fish.payara.notification.slack.SlackNotifierConfigurationInjector,org.jvnet.hk2.config.ConfigInjector}
        scope=javax.inject.Singleton
        qualifiers={org.jvnet.hk2.config.InjectionTarget}
        descriptorType=CLASS
        descriptorVisibility=NORMAL
        metadata=@token3={required,datatype\:java.lang.String,leaf},@noisy={optional,default\:true,datatype\:java.lang.Boolean,leaf},@token2={required,datatype\:java.lang.String,leaf},@token1={required,datatype\:java.lang.String,leaf},@enabled={optional,default\:false,datatype\:java.lang.Boolean,leaf},target={fish.payara.notification.slack.SlackNotifierConfiguration},Bundle-SymbolicName={fish.payara.server.internal.payara-appserver-modules.notification-slack-core},Bundle-Version={5.201.0}
        rank=0
        loader=OsgiPopulatorPostProcessor.HK2Loader(OSGiModuleImpl:: Bundle = [fish.payara.server.internal.payara-appserver-modules.notification-slack-core [324]], State = [NEW],1475759966)
        proxiable=null
        proxyForSameScope=null
        analysisName=null
        id=564
        locatorId=0
        identityHashCode=1096682443
        reified=false)

        at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2247)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:438)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:457)
        at org.jvnet.hk2.config.DomDocument$InjectionTargetFilter.matches(DomDocument.java:184)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getDescriptors(ServiceLocatorImpl.java:347)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getDescriptors(ServiceLocatorImpl.java:389)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getBestDescriptor(ServiceLocatorImpl.java:397)
        at org.jvnet.hk2.config.DomDocument.buildModel(DomDocument.java:135)
        at org.jvnet.hk2.config.ConfigModel.parseValue(ConfigModel.java:959)
        at org.jvnet.hk2.config.ConfigModel.<init>(ConfigModel.java:875)
        at org.jvnet.hk2.config.DomDocument.buildModel(DomDocument.java:114)
        at org.jvnet.hk2.config.DomDocument.getModelByElementName(DomDocument.java:162)
        at org.jvnet.hk2.config.ConfigParser.handleElement(ConfigParser.java:165)
        at org.jvnet.hk2.config.ConfigParser.parse(ConfigParser.java:101)
        at org.jvnet.hk2.config.ConfigParser.parse(ConfigParser.java:95)
        at org.glassfish.config.support.DomainXml.parseDomainXml(DomainXml.java:271)
        at org.glassfish.config.support.DomainXml.run(DomainXml.java:121)
        at org.jvnet.hk2.config.ConfigurationPopulator.populateConfig(ConfigurationPopulator.java:58)
        at org.glassfish.hk2.bootstrap.HK2Populator.populateConfig(HK2Populator.java:83)
        at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.populateConfig(AbstractModulesRegistryImpl.java:190)
        at com.sun.enterprise.module.bootstrap.Main.createServiceLocator(Main.java:249)
        at org.jvnet.hk2.osgiadapter.HK2Main.createServiceLocator(HK2Main.java:95)
        at com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishRuntime.newGlassFish(EmbeddedOSGiGlassFishRuntime.java:95)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishRuntimeDecorator.newGlassFish(GlassFishRuntimeDecorator.java:68)
        at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishRuntime.newGlassFish(OSGiGlassFishRuntime.java:91)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:125)
        ... 6 more
Caused by: com.sun.enterprise.module.ResolveError: Failed to start OSGiModuleImpl:: Bundle = [fish.payara.server.internal.payara-appserver-modules.notification-slack-core [324]], State = [NEW]
        at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:193)
        at org.jvnet.hk2.osgiadapter.OsgiPopulatorPostProcessor$1.loadClass(OsgiPopulatorPostProcessor.java:54)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2239)
        ... 31 more
Caused by: org.osgi.framework.BundleException: Unable to resolve fish.payara.server.internal.payara-appserver-modules.notification-slack-core [324](R 324.0): missing requirement [fish.payara.server.internal.payara-appserver-modules.notification-slack-core [324](R 324.0)] osgi.wiring.package; (&(osgi.wiring.package=fish.payara.nucleus.notification.configuration)(version>=5.201.0)(!(version>=6.0.0))) Unresolved requirements: [[fish.payara.server.internal.payara-appserver-modules.notification-slack-core [324](R 324.0)] osgi.wiring.package; (&(osgi.wiring.package=fish.payara.nucleus.notification.configuration)(version>=5.201.0)(!(version>=6.0.0)))]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4368)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2281)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
        at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.startBundle(OSGiModuleImpl.java:227)
        at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:185)
        ... 33 more

Command start-domain failed.

```

## Expected Outcome

Payara should continue to run without shutting down since started.

## Current Outcome

Payara shutdown immediately.

## Steps to reproduce (Only for bug reports) 

1 -**  Start the domain

    ./asadmin start-domain domain1

Already described in Description.

2 -**  Configure an HTTP network listener in the admin console:

This is impossible because the server is shutting down.

3 -**  Make changes to the domain.xml configuration:

```
<java-config classpath-suffix="" debug-options="-agentlib:jdwp=transport=dt_socket,address=9009,server=n,suspend=y" java-home="/Users/yusaku/.sdkman/candidates/java/8.0.252-amzn" system-classpath="">
```

> java-home="/Users/yusaku/.sdkman/candidates/java/8.0.252-amzn"

The above is the only change I made.
I also tried other versions of Java with the same result.
- 8.0.252-amzn
- 8.0.265-amzn
- 8.282.08.1-amzn

## Environment ##

- **Payara Version**: 5.2020.7.x
- **Edition**: Full
- **JDK Version**: 8.0.252-amzn, 8.0.265-amzn and 8.282.08.1-amzn. (I'm using SDKman, and Global is set to 11.0.7-amzn)
- **Operating System**: macOS Catalina 10.15.7

**Comment by MeroRai** [comment]
Hi @aii-goto-yusaku,

I can't reproduce the issue you described. JDK doesn't seem to be the issue as I tested it using the JDK versions you mentioned and also tested it using Oracle and Zulu JDKs. Payara should work out of the box and doesn't require any changes to the domain.xml file.

**Comment by MeroRai** [comment]
Hi, since we haven’t received any updates from you, we’ll proceed to close this issue. Feel free to re-open it in the future if you are able to reproduce the problem successfully using the current release of Payara Community Edition at that point in time.

**Comment by manish-manghwani** [comment]
Hi @MeroRai,

I am getting the exact same error now, can't pinpoint the root cause as it abruptly happened after working for couple of days. 
Let me know what additional details are required. I am adding few details here.

**Payara Version**: 5.2022.3
**JDK Version** : jdk1.8.0_202
**Operating System** : Windows 10  

### Invocation

`JVM invocation command line:
C:\Program Files\Java\jdk1.8.0_202\bin\java.exe
-cp
D:/server-upgrade/payara5/glassfish/modules/glassfish.jar
-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9009
-XX:+UnlockDiagnosticVMOptions
-XX:NewRatio=2
-Xmx512m
-Xbootclasspath/p:D:\server-upgrade\payara5\glassfish/lib/grizzly-npn-bootstrap-1.8.1.jar
-server
-javaagent:D:/server-upgrade/payara5/glassfish/lib/monitor/flashlight-agent.jar
-Djavax.xml.accessExternalSchema=all
-Djavax.net.ssl.trustStore=D:\server-upgrade\payara5\glassfish\domains\domain1/config/cacerts.jks
-Djdk.tls.rejectClientInitiatedRenegotiation=true
-Djdk.corba.allowOutputStreamSubclass=true
-Dfelix.fileinstall.dir=D:\server-upgrade\payara5\glassfish/modules/autostart/
-Dorg.glassfish.additionalOSGiBundlesToStart=org.apache.felix.shell,org.apache.felix.gogo.runtime,org.apache.felix.gogo.shell,org.apache.felix.gogo.command,org.apache.felix.shell.remote,org.apache.felix.fileinstall
-Dcom.sun.aas.installRoot=D:\server-upgrade\payara5\glassfish
-Dfelix.fileinstall.poll=5000
-Djava.security.policy=D:\server-upgrade\payara5\glassfish\domains\domain1/config/server.policy
-Djava.endorsed.dirs=D:\server-upgrade\payara5\glassfish/modules/endorsed;D:\server-upgrade\payara5\glassfish/lib/endorsed
-Dosgi.shell.telnet.maxconn=1
-Dfelix.fileinstall.bundles.startTransient=true
-Dcom.sun.enterprise.config.config_environment_factory_class=com.sun.enterprise.config.serverbeans.AppserverConfigEnvironmentFactory
-Dfelix.fileinstall.log.level=2
-Djavax.net.ssl.keyStore=D:\server-upgrade\payara5\glassfish\domains\domain1/config/keystore.jks
-Djava.security.auth.login.config=D:\server-upgrade\payara5\glassfish\domains\domain1/config/login.conf
-Dfelix.fileinstall.disableConfigSave=false
-Dorg.glassfish.grizzly.DEFAULT_MEMORY_MANAGER=org.glassfish.grizzly.memory.HeapMemoryManager
-Dfelix.fileinstall.bundles.new.start=true
-Dcom.sun.aas.instanceRoot=D:\server-upgrade\payara5\glassfish\domains\domain1
-Dosgi.shell.telnet.port=6666
-Dgosh.args=--nointeractive
-Dcom.sun.enterprise.security.httpsOutboundKeyAlias=s1as
-Dorg.jboss.weld.serialization.beanIdentifierIndexOptimization=false
-Dosgi.shell.telnet.ip=127.0.0.1
-DANTLR_USE_DIRECT_CLASS_LOADING=true
-Djava.awt.headless=true
-Dcom.ctc.wstx.returnNullForDefaultNamespace=true
-Djava.ext.dirs=C:\Program Files\Java\jdk1.8.0_202/lib/ext;C:\Program Files\Java\jdk1.8.0_202/jre/lib/ext;D:\server-upgrade\payara5\glassfish\domains\domain1/lib/ext
-Djdbc.drivers=org.h2.Driver
-Dorg.glassfish.grizzly.nio.DefaultSelectorHandler.force-selector-spin-detection=true
-Djava.library.path=D:/server-upgrade/payara5/glassfish/lib;C:/Program Files (x86)/Common Files/Oracle/Java/javapath;C:/Windows/Sun/Java/bin;C:/Windows/System32;C:/Windows;C:/Windows/System32/wbem;C:/Windows/System32/WindowsPowerShell/v1.0;C:/Windows/System32/OpenSSH;C:/Program Files/dotnet;C:/Program Files/nodejs;D:/Custom Commands;D:/apache-maven-3.6.3/bin;C:/Program Files/Java/jdk1.8.0_202/bin;C:/Program Files/PuTTY;C:/Users/manish.m/AppData/Local/Microsoft/WindowsApps;C:/Users/manish.m/AppData/Local/Programs/Git/cmd;C:/Users/manish.m/AppData/Roaming/npm;D:/server-upgrade/payara5/bin
com.sun.enterprise.glassfish.bootstrap.ASMain
-upgrade
false
-domaindir
D:/server-upgrade/payara5/glassfish/domains/domain1
-read-stdin
true
-asadmin-args
--host,,,localhost,,,--port,,,4848,,,--secure=false,,,--terse=false,,,--extraterse=false,,,--echo=false,,,--interactive=true,,,--autoname=false,,,start-domain,,,--verbose=false,,,--watchdog=false,,,--debug=true,,,--domaindir,,,D:\server-upgrade\payara5\glassfish\domains,,,domain1
-domainname
domain1
-instancename
server
-type
DAS
-verbose
false
-asadmin-classpath
D:/server-upgrade/payara5/glassfish/lib/client/appserver-cli.jar
-debug
true
-asadmin-classname
com.sun.enterprise.admin.cli.AdminMain
-watchdog
false]]`

###Output
`asadmin start-domain --debug domain1
Waiting for domain1 to start ........................Error starting domain domain1.
The server exited prematurely with exit code 1.
Before it died, it produced the following output:

Listening for transport dt_socket at address: 9009
Launching Payara Server on Felix platform
Registered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishRuntime@6fecacab in service registry.
Completed shutdown of GlassFish runtime
We are in non-embedded mode, so fish.payara.server.internal.core.glassfish [113] has nothing to do.
Sep 20, 2022 6:41:38 PM com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner createBundleProvisioner
INFO: Create bundle provisioner class = class com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner.
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:121)
        at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:54)
Caused by: A MultiException has 2 exceptions.  They are:
1. com.sun.enterprise.module.ResolveError: Failed to start OSGiModuleImpl:: Bundle = [fish.payara.server.internal.batch.glassfish-batch-connector [102]], State = [NEW]
2. java.lang.IllegalStateException: Could not load descriptor SystemDescriptor(
        implementation=org.glassfish.batch.spi.impl.BatchRuntimeConfigurationInjector
        name=batch-runtime-configuration
        contracts={org.glassfish.batch.spi.impl.BatchRuntimeConfigurationInjector,org.jvnet.hk2.config.ConfigInjector}
        scope=javax.inject.Singleton
        qualifiers={org.jvnet.hk2.config.InjectionTarget}
        descriptorType=CLASS
        descriptorVisibility=NORMAL
        metadata=@table-suffix={optional,default\:,datatype\:java.lang.String,leaf},@data-source-lookup-name={optional,datatype\:java.lang.String,leaf},@table-prefix={optional,default\:,datatype\:java.lang.String,leaf},@schema-name={optional,default\:APP,datatype\:java.lang.String,leaf},@executor-service-lookup-name={optional,default\:concurrent/__defaultManagedExecutorService,datatype\:java.lang.String,leaf},target={org.glassfish.batch.spi.impl.BatchRuntimeConfiguration},Bundle-SymbolicName={fish.payara.server.internal.batch.glassfish-batch-connector},Bundle-Version={5.2022.3}
        rank=0
        loader=OsgiPopulatorPostProcessor.HK2Loader(OSGiModuleImpl:: Bundle = [fish.payara.server.internal.batch.glassfish-batch-connector [102]], State = [NEW],843803222)
        proxiable=null
        proxyForSameScope=null
        analysisName=null
        id=188
        locatorId=0
        identityHashCode=1109218483
        reified=false)

        at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2247)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:438)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:457)
        at org.jvnet.hk2.config.DomDocument$InjectionTargetFilter.matches(DomDocument.java:184)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getDescriptors(ServiceLocatorImpl.java:347)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getDescriptors(ServiceLocatorImpl.java:389)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getBestDescriptor(ServiceLocatorImpl.java:397)
        at org.jvnet.hk2.config.DomDocument.buildModel(DomDocument.java:135)
        at org.jvnet.hk2.config.ConfigModel.parseValue(ConfigModel.java:959)
        at org.jvnet.hk2.config.ConfigModel.<init>(ConfigModel.java:875)
        at org.jvnet.hk2.config.DomDocument.buildModel(DomDocument.java:114)
        at org.jvnet.hk2.config.DomDocument.getModelByElementName(DomDocument.java:162)
        at org.jvnet.hk2.config.ConfigParser.handleElement(ConfigParser.java:166)
        at org.jvnet.hk2.config.ConfigParser.parse(ConfigParser.java:102)
        at org.jvnet.hk2.config.ConfigParser.parse(ConfigParser.java:96)
        at org.glassfish.config.support.DomainXml.parseDomainXml(DomainXml.java:271)
        at org.glassfish.config.support.DomainXml.run(DomainXml.java:121)
        at org.jvnet.hk2.config.ConfigurationPopulator.populateConfig(ConfigurationPopulator.java:58)
        at org.glassfish.hk2.bootstrap.HK2Populator.populateConfig(HK2Populator.java:83)
        at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.populateConfig(AbstractModulesRegistryImpl.java:190)
        at com.sun.enterprise.module.bootstrap.Main.createServiceLocator(Main.java:249)
        at org.jvnet.hk2.osgiadapter.HK2Main.createServiceLocator(HK2Main.java:95)
        at com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishRuntime.newGlassFish(EmbeddedOSGiGlassFishRuntime.java:95)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishRuntimeDecorator.newGlassFish(GlassFishRuntimeDecorator.java:68)
        at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishRuntime.newGlassFish(OSGiGlassFishRuntime.java:91)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:137)
        ... 6 more
Caused by: com.sun.enterprise.module.ResolveError: Failed to start OSGiModuleImpl:: Bundle = [fish.payara.server.internal.batch.glassfish-batch-connector [102]], State = [NEW]
        at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:193)
        at org.jvnet.hk2.osgiadapter.OsgiPopulatorPostProcessor$1.loadClass(OsgiPopulatorPostProcessor.java:54)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2239)
        ... 31 more
Caused by: org.osgi.framework.BundleException: Unable to resolve fish.payara.server.internal.batch.glassfish-batch-connector [102](R 102.0): missing requirement [fish.payara.server.internal.batch.glassfish-batch-connector [102](R 102.0)] osgi.wiring.package; (osgi.wiring.package=com.ibm.jbatch.spi) [caused by: Unable to resolve fish.payara.server.internal.batch.payara-jbatch [316](R 316.0): missing requirement [fish.payara.server.internal.batch.payara-jbatch [316](R 316.0)] osgi.wiring.package; (osgi.wiring.package=org.glassfish.weld) [caused by: Unable to resolve fish.payara.server.internal.web.weld-integration [381](R 381.0): missing requirement [fish.payara.server.internal.web.weld-integration [381](R 381.0)] osgi.wiring.package; (&(osgi.wiring.package=org.glassfish.web.deployment.descriptor)(version>=5.2022.0)(!(version>=6.0.0))) [caused by: Unable to resolve fish.payara.server.internal.web.glue [369](R 369.0): missing requirement [fish.payara.server.internal.web.glue [369](R 369.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.catalina)(version>=5.2022.0)(!(version>=6.0.0))) [caused by: Unable to resolve fish.payara.server.internal.web.core [367](R 367.0): missing requirement [fish.payara.server.internal.web.core [367](R 367.0)] osgi.wiring.package; (&(osgi.wiring.package=org.glassfish.web.loader)(version>=5.2022.0)(!(version>=6.0.0)))]]]] Unresolved requirements: [[fish.payara.server.internal.batch.glassfish-batch-connector [102](R 102.0)] osgi.wiring.package; (osgi.wiring.package=com.ibm.jbatch.spi)]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4398)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:1006)
        at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.startBundle(OSGiModuleImpl.java:227)
        at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:185)
        ... 33 more

Command start-domain failed.`
