### ISSUE TITLE
Hazelcast - ClassNotFoundException on my impl of MapStore

### ISSUE THREAD

**Issue by Rome89** [payara/Payara#5135]
# Description #
----------

I would like to integrate Mongodb with Hazelcast through the MapStore Hazelcast implementation. I would like to use Hazelcast Embedded into Payara. I overrode Hazelcast's xml config by introducing MapStore tag and everything seems to work.
The error occurs when I call the set function on the map, classNotFound of my impl MapStore. I can't putting the class into a jar in domain-dir / lib because it has too many dependencies. If I use method newhazelcast instance it works fine.
How can I solve this problem?

## Expected Outcome

 I expect lookuped hazelcastInstance to be able to retrieve the MapStore impl correctly. 

## Current Outcome

 ```
 com.hazelcast.core.HazelcastException: java.lang.ClassNotFoundException: com.brainy.business.cluster.dao.MongoMapStore
	at com.hazelcast.internal.util.ExceptionUtil.lambda$static$0(ExceptionUtil.java:55)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:133)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:76)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:138)
	at com.hazelcast.map.impl.mapstore.StoreConstructor.getStoreFromClassOrNull(StoreConstructor.java:83)
	at com.hazelcast.map.impl.mapstore.StoreConstructor.createStore(StoreConstructor.java:46)
	at com.hazelcast.map.impl.mapstore.BasicMapStoreContext.create(BasicMapStoreContext.java:123)
	at com.hazelcast.map.impl.mapstore.MapStoreContextFactory.createMapStoreContext(MapStoreContextFactory.java:48)
	at com.hazelcast.map.impl.MapContainer.<init>(MapContainer.java:137)
	at com.hazelcast.map.impl.MapServiceContextImpl.createMapContainer(MapServiceContextImpl.java:205)
	at com.hazelcast.map.impl.MapServiceContextImpl.lambda$createMapConstructor$0(MapServiceContextImpl.java:196)
	at com.hazelcast.internal.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:126)
	at com.hazelcast.map.impl.MapServiceContextImpl.getMapContainer(MapServiceContextImpl.java:287)
	at com.hazelcast.map.impl.PartitionContainer.createRecordStore(PartitionContainer.java:90)
	at com.hazelcast.map.impl.PartitionContainer.lambda$new$0(PartitionContainer.java:56)
	at com.hazelcast.internal.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:126)
	at com.hazelcast.map.impl.PartitionContainer.getRecordStore(PartitionContainer.java:158)
	at com.hazelcast.map.impl.operation.MapOperation.getRecordStoreOrNull(MapOperation.java:169)
	at com.hazelcast.map.impl.operation.MapOperation.beforeRun(MapOperation.java:86)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:235)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:160)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:138)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
Caused by: java.lang.ClassNotFoundException: com.brainy.business.cluster.dao.MongoMapStore
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.sun.enterprise.loader.CurrentBeforeParentClassLoader.loadClass(CurrentBeforeParentClassLoader.java:83)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.hazelcast.internal.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:287)
	at com.hazelcast.internal.nio.ClassLoaderUtil.newInstance0(ClassLoaderUtil.java:211)
	at com.hazelcast.internal.nio.ClassLoaderUtil.newInstance(ClassLoaderUtil.java:192)
	at com.hazelcast.map.impl.mapstore.StoreConstructor.getStoreFromClassOrNull(StoreConstructor.java:81)
	... 20 more 
```

## Steps to reproduce (Only for bug reports) 

**1 - Put hazelcast-mapstore-config.xml in domain-dir / config and change the configuration file on payara console.**

```
<hazelcast xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hazelcast.com/schema/config
           http://www.hazelcast.com/schema/config/hazelcast-config-4.1.xsd">		   
    <map name="customers">
        <map-store enabled="true">
            <class-name>com.brainy.business.cluster.dao.MongoMapStore</class-name>
            <properties>
                <property name="my-prop-1">true</property>
                <property name="my-prop-2">foo</property>
            </properties>
        </map-store>
    </map>
</hazelcast>
```

![hazelcast-config](https://user-images.githubusercontent.com/6709404/108601424-c27d0e00-739c-11eb-8296-2b01cc9b4655.PNG)

**2 - Singleton to retrieve Hazelcast Instance (If I use setConfig () to retrieve it works! )**

```
@Singleton
@Startup
public class HazelcastProvider {

    private static final Logger LOG = Logger.getLogger(HazelcastProvider.class.getName());

    private HazelcastInstance instance;

    @PostConstruct
    public void init() {
        try {
            Context ctx = new InitialContext();
            instance = (HazelcastInstance) ctx.lookup("payara/Hazelcast");
            //instance = setConfig();
        } catch (NamingException ex) {
            Logger.getLogger(HazelcastProvider.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public HazelcastInstance getInstance() {
        return instance;
    }

    public <K extends Object, V extends Object> IMap<K, V> getMap(String name) {
        if (isNull()) {
            LOG.log(Level.SEVERE, "Hazelcast Instance cannot be null");
            return null;
        }
        return this.instance.getMap(name);
    }

    private HazelcastInstance setConfig() {
        Config config = new Config();
        ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
        //config.setClassLoader(classLoader);
        config.getCPSubsystemConfig().setCPMemberCount(3);
        final MapConfig supplementsMapConfig = config.getMapConfig("customers");
        final MapStoreConfig mapStoreConfig = supplementsMapConfig.getMapStoreConfig();
        mapStoreConfig
                .setEnabled(true)
                .setClassName("com.brainy.business.cluster.dao.MongoMapStore")
                .setWriteDelaySeconds(30)
                .setProperty("mongo.url", "mongodb://192.168.107.41:27017")
                .setProperty("mongo.db", "alessi")
                .setProperty("mongo.collection", "customers");

        final HazelcastInstance hazelcastInstance = newHazelcastInstance(config);
        return hazelcastInstance;
    }

    private boolean isNull() {
        return instance == null;
    }

}
```

**3 -  Impl MapStore**

```
public class MongoMapStore implements MapStore<String, Customer>, MapLoaderLifecycleSupport, Serializable {

    private static final Logger LOG = Logger.getLogger(MongoMapStore.class.getName());

    private MongoClient mongoClient;
    private MongoCollection collection;


    @Override
    public void init(HazelcastInstance hi, Properties properties, String string) {
        LOG.log(Level.INFO, "Init MongoMapStore");
        
    }

    @Override
    public void destroy() {
        LOG.log(Level.INFO, "Destroy MongoMapStore");
        <-- my code -->
    }

    @Override
    public Customer load(String key) {
        LOG.log(Level.INFO, "Load {0}", key);
        <-- my code -->
    }

    @Override
    public Map<String, Customer> loadAll(Collection<String> keys) {
        LOG.log(Level.INFO, "LoadAll {0}", keys.toString());
        <-- my code -->
    }

    @Override
    public Iterable<String> loadAllKeys() {
        LOG.log(Level.INFO, "LoadAllKeys");
        <-- my code -->
    }

    @Override
    public void store(String key, Customer customer) {
        LOG.log(Level.INFO, "Store {0}", key);
        <-- my code -->
    }

    @Override
    public void storeAll(Map<String, Customer> map) {
        LOG.log(Level.INFO, "Store All {0}", map.keySet().toString());
        <-- my code -->
    }

    @Override
    public void delete(String key) {
        <-- my code -->
    }

    @Override
    public void deleteAll(Collection<String> keys) {
        <-- my code -->
    }

}
```

**4 - Retrieve and call set method on IMap**

```

@Inject
private HazelcastProvider provider;


IMap<String, Customer> map = provider.getMap("customers");                    
map.set(customer.getId(), customer);

```

## Environment ##

- **Payara Version**:  5.192  to 5.2021.1
- **Edition**: Full
- **JDK Version**: 8 u251
- **Operating System**:  Windows
- **Database**:  MongoDB

**Comment by AlanRoth** [comment]
Hi @Rome89, we aren't able to provide debugging support for your application. If you require assistance with your application head over to the [Payara Forum ](https://groups.google.com/g/payara-forum) or enquire about a Payara Enterprise license that grants you access to support.

Thank you for your understanding,
Alan
