### ISSUE TITLE
No Current Invocation present if using Hazelcast backed cache from another module

### ISSUE THREAD

**Issue by sgflt** [payara/Payara#5159]
# Description #
----------
Begining with Payara 5.2021.1 a quartz job started throwing exceptions during access to cache.

If all code from "job" module is moved to "core" module, the access to the cache from quartz job is OK.

## Expected Outcome ##
No exception

## Current Outcome ##

[2021-03-11T15:26:38.507+0100] [Payara 5.2021.1] [INFO] [] [] [tid: _ThreadID=770 _ThreadName=Scheduler_Worker-1] [timeMillis: 1615472798507] [levelValue: 800] [[
  15:26:38.506 [Scheduler_Worker-1] ERROR org.quartz.core.ErrorLogger - Job (DEFAULT.job-with-cache threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:234) [org.quartz-scheduler-quartz-1.8.6.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549) [org.quartz-scheduler-quartz-1.8.6.jar:?]
Caused by: java.lang.IllegalStateException: No Current Invocation present
	at fish.payara.appserver.context.JavaEEContextUtilImpl.currentInvocation(JavaEEContextUtilImpl.java:90) ~[gf-web-connector.jar:?]
	at fish.payara.nucleus.hazelcast.contextproxy.CacheManagerProxy.getCache(CacheManagerProxy.java:87) ~[hazelcast-bootstrap.jar:?]
	at cz.i.quartz.JobUsingCache.getCache(JobUsingCache.java:43) ~[job_jar/:?]
	at cz.i.quartz.JobUsingCache.execute(JobUsingCache.java:60) ~[job_jar/:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:223) ~[org.quartz-scheduler-quartz-1.8.6.jar:?]
	... 1 more
]]

## Steps to reproduce ## 

1. checkout https://github.com/sgflt/payara-test-case
2. deploy app
3. wait 10 seconds
4. exception will appear

## Environment ##

- **Distribution**: Full
- **JDK Version**:OpenJDK 11
- **Operating System**: Fedora 33

**Comment by lprimak** [comment]
This is due to `JavaEEContextUtilImpl.currentInvocation()` catching a legit issue
Once Hazelcast 4.2 is released CacheManagerProxy.java and all of it's companions will be removed, and this issue fixed.
Not sure if it's worth fixing the old code currently though

**Comment by MeroRai** [comment]
Hi @sgflt, as @lprimak suggested it is not worth fixing the current code as the issue will be fixed once Hazelcast is upgraded to 4,2.
