### ISSUE TITLE
Bug Report:  java.lang.IllegalArgumentException: IllegalJndiNameEnvironment : env for JSR 107/Hazelcast cache

### ISSUE THREAD

**Issue by sgflt** [payara/Payara#5221]
# Description #
----------

## Expected Outcome ##
No exception caused by access to JSR 107 cache.

## Current Outcome ##
<details>

```
java.lang.IllegalArgumentException: IllegalJndiNameEnvironment : env
	at com.sun.enterprise.deployment.util.DOLUtils.getModuleName(DOLUtils.java:899)
	at fish.payara.appserver.context.JavaEEContextUtilImpl.isLoaded(JavaEEContextUtilImpl.java:156)
	at fish.payara.appserver.context.JavaEEContextUtilImpl.access$700(JavaEEContextUtilImpl.java:69)
	at fish.payara.appserver.context.JavaEEContextUtilImpl$InstanceImpl.isLoaded(JavaEEContextUtilImpl.java:307)
	at fish.payara.nucleus.hazelcast.PayaraHazelcastTenant.isAvailable(PayaraHazelcastTenant.java:135)
	at com.hazelcast.spi.impl.operationservice.Operation.isTenantAvailable(Operation.java:806)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:245)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:175)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:139)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:279)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:100)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:617)
	at com.hazelcast.cache.impl.CacheProxy.get(CacheProxy.java:486)
	at com.hazelcast.cache.impl.CacheProxy.get(CacheProxy.java:104)
	at fish.payara.cdi.jsr107.CacheResultInterceptor.cacheResult(CacheResultInterceptor.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68)
```
</details>

`DOLUtils.getModuleName(env)` expects following instances:

- EjbDescriptor
- EjbBundleDescriptor
- WebBundleDescriptor
- ApplicationClientDescriptor
- ManagedBeanDescriptor

but `com.sun.enterprise.deployment.Application` is provided at runtime.

Application is deployed as EAR.

## Environment ##

- **Distribution**: 5.2021.4-SNAPSHOT 
- **JDK Version**: OpenJDK 11 
- **Operating System**: Fedora 33

**Comment by lprimak** [comment]
Can you attach a reproduced please?

**Comment by sgflt** [comment]
Sure.

**Comment by sgflt** [comment]
Checkout https://github.com/sgflt/payara-test-case/commit/ebd7f192a805ff2ffa69cff31259dd4d475162cf, build, deploy, and in browser open http://localhost:8080/bug/jsr107.

**Comment by lprimak** [comment]
Ok thanks

**Comment by lprimak** [comment]
Good job on the reproducer. I was able to use it with no fuss!

**Comment by sgflt** [comment]
Fix seems to be incomplete.

Exception is gone, but application stucks inside of isAvailable(tenantable).

BLOCKED: tenant not available "earname", module "earname". Operation: com.hazelcast.cache.impl.operation.CachePutOperation

[2021-05-25T18:34:28.469+0200] [Payara 5.2021.5-SNAPSHOT] [WARNING] [] [com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetector] [tid: _ThreadID=68 _ThreadName=hz.cocky_ardinghelli.SlowOperationDetectorThread] [timeMillis: 1621960468469] [levelValue: 900] [[
  [192.168.0.227]:5900 [development] [4.2] Slow operation detected: com.hazelcast.cache.impl.operation.CachePutOperation (2 invocations)]]


It is related only to cluster/dg variant. Single standalone instance without DAS is not affected by this.

I have created cluster with single instance and all HZ commmunication is frozen.

**Comment by lprimak** [comment]
@sgflt ah you are killing me with this :)

For now use system property `fish.payara.tenantcontrol.blocking.disable`=true

**Comment by sgflt** [comment]
@lprimak Workaround seems to be working :)

**Comment by lprimak** [comment]
is the application deployed on all instances including DAS that communicate with the same Hazelcast cluster?
This may not be a bug. The issue is that Hazelcast puts objects onto all nodes by default. If a particular node doesn't have the application deployed, it doesn't know the classes and how to deal with the application, so it blocks until the application is deployed. You need to configure partitions in such a way that objects are not stored on DAS if the application is not deployed there

**Comment by lprimak** [comment]
See https://docs.hazelcast.com/imdg/4.2/clusters/partition-group-configuration.html
you may have to use custom partitioning to separate DAS from a partition group

**Comment by lprimak** [comment]
In addition to the above, found another issue

**Comment by sgflt** [comment]
> is the application deployed on all instances including DAS that communicate with the same Hazelcast cluster?
> This may not be a bug. The issue is that Hazelcast puts objects onto all nodes by default. If a particular node doesn't have the application deployed, it doesn't know the classes and how to deal with the application, so it blocks until the application is deployed. You need to configure partitions in such a way that objects are not stored on DAS if the application is not deployed there

I was on the same trace. I have removed DAS from cluster and on one cluster it worked, on a second one it was still broken. Application has been deployed only on instances in the same hazelcast cluster.

**Comment by sgflt** [comment]
Anyway, the fix seem to be working without workaround.

**Comment by lprimak** [comment]
- Instance groups will work in domain discovery once I publish another fix to this PR
- Otherwise you will need to do this: https://docs.hazelcast.com/imdg/4.2/clusters/partition-group-configuration.html#custom to make sure that Hazelcast doesn't put partitions where apps are not deployed

Of course this depends on merging the open PR that I published today

**Comment by lprimak** [comment]
Looks like this won't make it into .4, will have to wait

**Comment by lprimak** [comment]
Relates to #5276
