### ISSUE TITLE
Bug Report: NPE in ByteChunk.append via FormAuthenticator.saveRequest upon receiving unauthorized POST/PUT-request

### ISSUE THREAD

**Issue by bseiller** [payara/Payara#5263]
# Description #
Upon receiving an unauthorized POST/PUT-request with a body size of at least 4096 bytes (depending on the server config) a NPE is thrown in ByteChunk.append, which might be logged in the server.log.

This issue seems to have been around for a while - in upstream versions of the involved classes as well:
https://issues.apache.org/jira/browse/GERONIMO-2133
https://community.oracle.com/tech/developers/discussion/1730129/page-becomes-blank-if-i-make-a-request-after-session-is-expired
https://groups.google.com/g/payara-forum/c/kjAEs5VbbRU/m/qmhOnIW_BAAJ

### In all cases (request body size exactly as big or bigger than maxPostSaveSize
The processing of the request is properly finished and a 401/403-response is being sent.
The access log does contain the original request, the server.log does not contain a stacktrace.

### In the edge-case of a request that has a body size exactly as big as the maxPostSaveSize
The request is saved in the session for later restoration.

### In all cases: 
The processing of the request is interrupted and no 401/403-response is being sent.
The access log does not contain the original request, the server.log might contain a similar exception and stacktrace to the following one:
```
[2021-05-12T14:38:21.662+0200] [Payara 5.201] [SEVERE] [AS-WEB-CORE-00037] [javax.enterprise.web.core] [tid: _ThreadID=46809 _ThreadName=http-thread-pool::http-listener-2(18)] [timeMillis: 1620823101662] [levelValue: 1000] [[
  An exception or error occurred in the container during the request processing
java.lang.NullPointerException
        at org.glassfish.grizzly.http.util.ByteChunk.append(ByteChunk.java:389)
        at org.apache.catalina.authenticator.FormAuthenticator.saveRequest(FormAuthenticator.java:569)
        at org.apache.catalina.authenticator.FormAuthenticator.authenticate(FormAuthenticator.java:252)
        at com.sun.web.security.RealmAdapter.invokeAuthenticateDelegate(RealmAdapter.java:493)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:468)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:726)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:368)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.lang.Thread.run(Thread.java:748)
]]
```

### In the edge-case of a request that has a body size as big or smaller than the maxPostSaveSize
**The request is not saved in the session for later restoration and thus lost.**

## Steps to reproduce ## 
See the unit-test here
https://github.com/bseiller/FormAuthenticator_NPE/blob/main/src/test/java/FormAuthenticatorTest.java
for different permutations of maxPostSaveSize and request body size and the different outcomes.

To break it down - the NPE is triggered if the following conditions are met:
- form based authentication must be configured/used
- server receives a request that is not authorized and would result in a response with a 401/403 HTTP status code
- maxPostSizeData (request.getConnector().getMaxSavePostSize()) has the default value of 4096 bytes **or** smaller
- original request (POST, PUT) has body which has >= maxPostSizeData bytes

## Environment ##
We encountered this bug using Payara 5.201, but using newer versions e.g. 5.2021.3 (via payara-embedded-web) and inspecting the code of newer versions suggests that the problem exists in current versions as well.

## Possible Solution ##
ByteChunk.out (ByteOutputChannel) is not being initialized in FormAuthenticator.saveRequest, while ByteChunk.optimizedWrite is true by default.
Setting ByteChunk.optimizedWrite to false in FormAuthenticator.saveRequest (around here https://github.com/payara/Payara/blob/master/appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/FormAuthenticator.java#L562) will prevent the NPE. In all cases where the body is > maxPostSizeData this will lead to an IOException which is currently not being handled locally but could be handled like here
https://github.com/apache/tomcat/blob/master/java/org/apache/catalina/authenticator/FormAuthenticator.java#L222
This also could result in a log entry that might help to find the problem with too big POST/PUT-requests and/or a maxPostSizeData that must be increased.
Also having ByteChunk.append throw an IOException if ByteChunk.optimizedWrite == true and ByteChunk.out == null (see  ByteChunk.flushBuffers) would make it more consistent.
See here:
https://github.com/eclipse-ee4j/grizzly/issues/2127

**I could provide a PR with fixes, but it might take me a while.**

PS: ByteChunk contains at least one more source for potential NPEs namely hashCode - this could be fixed as a package deal.
~I could provide a sscce for that as well if requested. ~That is if there is a patched version in some Payara-owned repository.~
Should I create a issue at https://github.com/eclipse-ee4j/grizzly
as I can't do that here: https://github.com/payara/patched-src-grizzly?~
See here: https://github.com/eclipse-ee4j/grizzly/issues/2128

**Comment by shub8968** [comment]
Hi @bseiller,

Would you be able to provide a proper reproducer app in order to investigate the issue? I appreciate your efforts in providing a possible solution to the cause but it would be great if you can open a pull request in this regard.
