### ISSUE TITLE
sentry logging handler for Payara itself

### ISSUE THREAD

**Issue by gulbinas** [payara/Payara#530]
Using Payara Server 4.1.1.154 #badassfish (build 270)

Tried to update file domains/payaradomain/config/logging.properties according to this

```
handlers=net.kencochrane.raven.jul.SentryHandler
net.kencochrane.raven.jul.SentryHandler.dsn=https://publicKey:secretKey@host:port/1?options
```

as per sentry-raven documentation [here](https://github.com/getsentry/raven-java/tree/master/raven)

no indications that something changed, log file(logs/server.log) still gets populated with same messages even if I replace default handler with SentryHandler...

Additional dependencies to modules and lib folder... Nothing changes.

Need some info or directions. Willing to debug

**Comment by smillidge** [comment]
Dumb question here are you starting Payara with 
```shell
asadmin start-domain payaradomain
```

**Comment by gulbinas** [comment]
yes

`````
asadmin start-domain --verbose payaradomain
`````
gives

````
#!## LogManagerService.postConstruct : rootFolder=/home/glassfish/payara41/glassfish
#!## LogManagerService.postConstruct : templateDir=/home/glassfish/payara41/glassfish/lib/templates
#!## LogManagerService.postConstruct : src=/home/glassfish/payara41/glassfish/lib/templates/logging.properties
#!## LogManagerService.postConstruct : dest=/home/glassfish/payara41/glassfish/domains/payaradomain/config/logging.properties
`````

maybe I'm editing wrong config file...

**Comment by smillidge** [comment]
If it is the DAS that you are trying to change the logging.properties file for then /home/glassfish/payara41/glassfish/domains/payaradomain/config/logging.properties is the correct file. If you are wiling to debug the class https://github.com/payara/Payara/blob/8a403bf75d3734e564a9fb95d60498987cc4287e/nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java is the class to debug with a breakpoint in the postConstruct method.

**Comment by gulbinas** [comment]
and what would be correct path to put raven-6.0.0.jar ?

looks i've messed too much logging.properties at first. Now in fresh install i'm getting this
````
Can't load log handler "net.kencochrane.raven.jul.SentryHandler"
java.lang.ClassNotFoundException: net.kencochrane.raven.jul.SentryHandler
java.lang.ClassNotFoundException: net.kencochrane.raven.jul.SentryHandler
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.util.logging.LogManager$4.run(LogManager.java:808)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:802)
        at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:1406)
        at java.util.logging.LogManager.access$1500(LogManager.java:148)
        at java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:1493)
        at java.util.logging.Logger.getHandlers(Logger.java:1350)
        at com.sun.enterprise.server.logging.LogManagerService.postConstruct(LogManagerService.java:355)
        at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:326)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:374)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:228)
        at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
[#|2015-11-19T19:54:27.105+0200|INFO|Payara 4.1|javax.enterprise.logging|_ThreadID=15;_ThreadName=RunLevelControllerThread-1447955667033;_TimeMillis=1447955667105;_LevelValue=800;_MessageID=NCLS-LOGGING-00009;|
  Running Payara Version: Payara Server  4.1.1.154 #badassfish (build 270)|#]
````

**Comment by smillidge** [comment]
Should be /home/glassfish/payara41/glassfish/domains/payaradomain/lib or for all domains
/home/glassfish/payara41/glassfish/lib

**Comment by gulbinas** [comment]
probably related https://github.com/getsentry/raven-java/issues/140

**Comment by gulbinas** [comment]
Still same error, need more debugging

**Comment by mikecroft** [comment]
Hi @gulbinas is this still an issue for you? If you haven't already tried, we have improved classloading in Payara Server, so you could package your JAR with the application
https://payara.gitbooks.io/payara-server/content/documentation/extended-documentation/classloading.html#4-solutions-to-the-class-loading-issue

**Comment by OndrejM** [comment]
@gulbinas, try to put `raven-6.0.0.jar` into the `lib/ext` directory, like `/home/glassfish/payara41/glassfish/domains/payaradomain/lib/ext`. It is also recommended in this [tutorial for custom log handlers](https://blogs.oracle.com/naman/entry/configure_my_custom_log_handler).

**Comment by OndrejM** [comment]
I suggest that the classloader hierachy is better documented. I will close this issue now, as it was created very long time ago, and it should the above comment answers the question.

**Comment by gulbinas** [comment]
Sentry provided jul Logging handler now works with Payara 4.1.1.164 version.
Sentry raven version: 7.8.2

Got it working when placed libs in <payara_domain>/lib and <payara_domain>/lib/ext folders
