### ISSUE TITLE
Bug Report:  NoSuchElementException when using redirectURI in config file

### ISSUE THREAD

**Issue by LarsBrenker** [payara/Payara#5320]
# Description #
----------

Starting with Payara 5.2021.1 (including 5.2021.2 , 5.2021.3, 5.2021.4) there is an error when using OpenID Connect.

If you use the "redirect URI" parameter in the OpenIdAuthenticationDefinition Annotation, it works fine.

However, if you configure the parameter in the ConfigFile, there is an error.

It worked flawlessly up to version 5.2020.7

## Expected Outcome ##

Correct forwarding to the OAuth provider

## Current Outcome ##

```java
[2021-06-24T14:10:15.483+0000] [] [WARNING] [] [javax.enterprise.system.container.web.com.sun.web.security] [tid: _ThreadID=68 _ThreadName=http-thread-pool::http-listener(1)] [timeMillis: 1624543815483] [levelValue: 900] [[
  JASPIC: http msg authentication fail
java.util.NoSuchElementException: Unable to resolve expression ${baseURL}/OAuthCallback
	at fish.payara.nucleus.microprofile.config.spi.ConfigExpressionResolver.resolveExpression(ConfigExpressionResolver.java:214)
	at fish.payara.nucleus.microprofile.config.spi.ConfigExpressionResolver.getValue(ConfigExpressionResolver.java:122)
	at fish.payara.nucleus.microprofile.config.spi.ConfigExpressionResolver.resolve(ConfigExpressionResolver.java:101)
	at fish.payara.nucleus.microprofile.config.spi.ConfigExpressionResolver.resolve(ConfigExpressionResolver.java:83)
	at fish.payara.nucleus.microprofile.config.spi.PayaraConfig.searchConfigSources(PayaraConfig.java:307)
	at fish.payara.nucleus.microprofile.config.spi.PayaraConfig.lambda$getConfigValue$1(PayaraConfig.java:232)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
	at fish.payara.nucleus.microprofile.config.spi.PayaraConfig.getConfigValue(PayaraConfig.java:228)
	at fish.payara.nucleus.microprofile.config.spi.PayaraConfig.getValue(PayaraConfig.java:212)
	at fish.payara.nucleus.microprofile.config.spi.PayaraConfig.getValueInternal(PayaraConfig.java:188)
	at fish.payara.nucleus.microprofile.config.spi.PayaraConfig.getOptionalValue(PayaraConfig.java:160)
	at fish.payara.security.openid.OpenIdUtil.getConfiguredValue(OpenIdUtil.java:65)
	at fish.payara.security.openid.controller.ConfigurationController.buildConfig(ConfigurationController.java:174)
	at fish.payara.security.openid.controller.ConfigurationController$Proxy$_$$_WeldClientProxy.buildConfig(Unknown Source)
	at fish.payara.security.openid.OpenIdAuthenticationMechanism.setConfiguration(OpenIdAuthenticationMechanism.java:194)
	at fish.payara.security.openid.OpenIdExtension.lambda$null$1(OpenIdExtension.java:144)
	at org.glassfish.soteria.cdi.CdiProducer.create(CdiProducer.java:104)
	at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:96)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:102)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:105)
	at org.jboss.weldx.security.enterprise.authentication.mechanism.http.HttpAuthenticationMechanism$37414984$Proxy$_$$_WeldClientProxy.validateRequest(Unknown Source)
	at org.glassfish.soteria.mechanisms.jaspic.HttpBridgeServerAuthModule.validateRequest(HttpBridgeServerAuthModule.java:151)
	at org.glassfish.soteria.mechanisms.jaspic.DefaultServerAuthContext.validateRequest(DefaultServerAuthContext.java:76)
	at com.sun.web.security.realmadapter.JaspicRealm.validateRequest(JaspicRealm.java:391)
	at com.sun.web.security.realmadapter.JaspicRealm.validateRequest(JaspicRealm.java:358)
	at com.sun.web.security.realmadapter.JaspicRealm.validateRequest(JaspicRealm.java:181)
	at com.sun.web.security.RealmAdapter.invokeAuthenticateDelegate(RealmAdapter.java:487)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:468)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:726)
	at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:581)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.base/java.lang.Thread.run(Thread.java:834)
]]


```

## Steps to reproduce ## 

Try this (works):

```java
@OpenIdAuthenticationDefinition(
        clientSecret = "${ENV=XX}",
        clientId = "${ENV=YY}",
        tokenAutoRefresh = true,
        redirectURI = "${baseURL}/OAuthCallback"
)
```

When using the attribute in the config, the error mentioned above occurs

```properties
payara.security.openid.redirectURI=${baseURL}/OAuthCallback
```

## Environment ##

- **Distribution**:  payara/micro:5.2021.1-jdk11 Docker Image
- **JDK Version**: jdk11
- **Operating System**: payara/micro:5.2021.1-jdk11

**Comment by rdebusscher** [comment]
Hi Lars,

This is related to the introduction of MicroProfile Config 2.0 (MP 4.0) where variable replacement is introduced. When defined in as config value, the MP Config system tries to resolve the `$baseURL` which is not found (as config value).

We will have a look at it how this can be handled.

Thanks for the report
Rudy

**Comment by LarsBrenker** [comment]
Hi Rudy, thanks for the info. I already thought of that. I'm curious. The problem is that we would have liked to switch to 5.2021.4 because of the Metro (JAX-WS implementation) remote code vulnerability.

**Comment by rdebusscher** [comment]
Hi Lars,

Can you try to escape the value in the config?

`payara.security.openid.redirectURI=\\${baseURL}/OAuthCallback`

**Comment by LarsBrenker** [comment]
Hi Rudy, thanks this is how it works. Will this be the future solution or will there be another bug fix? **Thank you for your quick help!**

**Comment by rdebusscher** [comment]
Hi Lars,

I don't think we can fix this as MP Config is supposed to expand variables but the `baseURL` variable can only be resolved outside of MP Config.
