### ISSUE TITLE
Bug Report:  MDB causing issues with JAX-RS and JSON

### ISSUE THREAD

**Issue by emmanuel-lopez** [payara/Payara#5340]
# Description #
----------

When a MessageDrivenBean is added/enabled Json responses from JAX-RS no longer work properly.

## Expected Outcome ##

MDB and JAX-RS shouldn't conflict with each other.
Calling a JAX-RS REST end point responds with Json output.

## Current Outcome ##

If MDB isn't activated everything works as expected.
If MDB is activated it throws an exception being invalid Json even though that is not the case..

```
java.lang.UnsupportedOperationException
	at javax.json.JsonWriter.write(JsonWriter.java:117)
	at org.glassfish.json.jaxrs.JsonValueBodyWriter.writeTo(JsonValueBodyWriter.java:95)
	at org.glassfish.json.jaxrs.JsonValueBodyWriter.writeTo(JsonValueBodyWriter.java:48)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:242)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:227)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
	at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:85)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:61)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1116)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:638)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:371)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:361)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1636)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:259)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: javax.json.stream.JsonGenerationException: Invalid json
		at org.apache.johnzon.core.JsonGeneratorImpl.close(JsonGeneratorImpl.java:437)
		at org.apache.johnzon.core.JsonWriterImpl.close(JsonWriterImpl.java:63)
		at org.glassfish.json.jaxrs.JsonValueBodyWriter.writeTo(JsonValueBodyWriter.java:94)
		... 54 more
```

## Steps to reproduce ## 

I've uploaded the minimal code to: https://github.com/emmanuel-lopez/JaxRsMdbTest
When built, then deployed and called at the REST endpoint at /rest
It will return a very basic Json output working output from:

```java
package com.company.abc.test;

import javax.json.*;
import javax.ws.rs.*;
import javax.ws.rs.core.*;

@Path("rest")
public class RestResource {
    
    @GET
    @Produces({MediaType.APPLICATION_JSON})
    public Response get(){
        
        JsonObject jo = Json.createObjectBuilder()
                .add("key", "value")
                .build();
        
        return Response.ok(jo)
                .build();
    }
}
```

Afterwards take down the app and uncomment the activation of the MDB.
Save, rebuild then redeploy. Call the same REST endpoint and it will throw and exception.

```java
package com.company.abc.test;

import javax.ejb.*;
import javax.jms.*;

//@MessageDriven(activationConfig = {
//    @ActivationConfigProperty(propertyName = "resourceAdapter", propertyValue = "artemis-rar"),
//    @ActivationConfigProperty(propertyName = "destinationType", propertyValue = "javax.jms.Queue"),
//    @ActivationConfigProperty(propertyName = "destination", propertyValue = "SOMEQUEUE")})
public class MdbConsumer implements MessageListener {

    @Override
    public void onMessage(Message message) {
        
        System.out.println("Got some message");
    }    
}
```

The server will complain about the queue/adapter not being available but I can still generate the same issue when the resources are available.

## Environment ##

- **Distribution**: Full (5.2021.2) and Micro (5.2021.2)
- **JDK Version**: 11.0.2 (Oracle) and 11 (Azul)
- **Operating System**:  Windows and Linux (Docker)

**Comment by shub8968** [comment]
Hi @emmanuel-lopez,

I am tried it using `activemq-rar-5.12.0` and It got deployed on Payara 5.2021.5. Would you be able to check it properly?

**Comment by shub8968** [comment]
@emmanuel-lopez 

I have closed the issue as of now. Feel free to open it if you find the potential issue.

**Comment by emmanuel-lopez** [comment]
@shub8968 thank you for looking in to this issue.
The deployment of the rar file wasn't the issue. Sorry if my wording was confusing.

The issue was the REST endpoint throwing exception if MDB is used.

**Comment by shub8968** [comment]
Hi @emmanuel-lopez,

I have checked REST endpoint is working fine.

**Comment by shub8968** [comment]
@emmanuel-lopez Yes, I have tested it with MDB enabled. It ideally should also work for Artemis.
