### ISSUE TITLE
AsyncSupported = true in servlet annoation results in error

### ISSUE THREAD

**Issue by pbelbin** [payara/Payara#537]
I tried doing what is documented here:

http://www.oracle.com/webfolder/technetwork/tutorials/obe/java/HTML5andServlet31/HTML5andServlet%203.1.html#section3

to create a servlet that can be used to upload files to the server.

but, when I try to run the code, I see the following message on the server:

Warning:   StandardWrapperValve[UploadServlet]: Servlet.service() for servlet UploadServlet threw exception
java.lang.IllegalStateException: Request is within the scope of a filter or servlet that does not support asynchronous operations
	at org.apache.catalina.connector.Request.startAsync(Request.java:4252)
	at org.apache.catalina.connector.Request.startAsync(Request.java:4214)
	at org.apache.catalina.connector.RequestFacade.startAsync(RequestFacade.java:1043)
	at javax.servlet.ServletRequestWrapper.startAsync(ServletRequestWrapper.java:432)
	at net.ke5stl.uploadfile.UploadServlet.doPost(UploadServlet.java:31)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.netbeans.modules.web.monitor.server.MonitorFilter.doFilter(MonitorFilter.java:393)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:536)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)

**Comment by pbelbin** [comment]
Ok, just tested with 4.1.1.154, and am happy to report that this does not happen any more!  Yay!

**Comment by pbelbin** [comment]
hmmmm.  I *thought* it was working, but, now it's not.

I'm using JDK8u66, NetBeans 8.1, Payara 4.1.1.154.

It seemed to work initially, but, now doesn't.... so, you may experience something like this, where it works initially, but not afterwards.

**Comment by pbelbin** [comment]
[UploadTest.TXT](https://github.com/payara/Payara/files/45421/UploadTest.TXT)

note: the UploadTest.TXT file is really a 7-zip of the sample project that demonstrates the issue.

**Comment by pbelbin** [comment]
oops.... wrong button.  there really is a problem!

**Comment by pbelbin** [comment]
hmmmm.  looks like this issue is actually created by the netbeans ide adding 2 .jars to the domain lib folder, and those jars are causing issues.

the jars appear when you enable http monitoring.

I've removed those jars, and now, it's working as it should!  So, it appears that the http monitoring interferes with the async requests.

regards,
peter
