### ISSUE TITLE
Bug Report:  Hazelcast kubernetes DNS discovery fails

### ISSUE THREAD

**Issue by jbndbc** [payara/Payara#5379]
# Description #
----------

In Payara server 5.2021.5 hazelcast kubernetes DNS discovery fails with `java.lang.NoClassDefFoundError: com/hazelcast/cluster/Address`

## Expected Outcome ##

I expect the Payara server instance to become a member of a data grid.

## Current Outcome ##

The following stacktrace is thrown during startup, and the server enters shutdown mode.

```text
[#|2021-08-11T09:43:49.363+0200|SEVERE|Payara 5.2021.5|com.hazelcast.internal.cluster.impl.DiscoveryJoiner|_ThreadID=27;_ThreadName=RunLevelControllerThread-1628667828054;_TimeMillis=1628667829363;_LevelValue=1000;|
  [xxx.xxx.xxx.xxx]:5701 [javaee-reference-implementation-1-0-headless.user-jbn.svc.cloud.dbc.dk] [4.2] com/hazelcast/cluster/Address
java.lang.NoClassDefFoundError: com/hazelcast/cluster/Address
        at com.hazelcast.kubernetes.DnsEndpointResolver.lookup(DnsEndpointResolver.java:111)
        at com.hazelcast.kubernetes.DnsEndpointResolver.resolve(DnsEndpointResolver.java:77)
        at com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy.discoverNodes(HazelcastKubernetesDiscoveryStrategy.java:108)
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.discoverNodes(DefaultDiscoveryService.java:72)
        at com.hazelcast.internal.cluster.impl.DiscoveryJoiner.getPossibleAddresses(DiscoveryJoiner.java:71)
        at com.hazelcast.internal.cluster.impl.DiscoveryJoiner.getPossibleAddressesForInitialJoin(DiscoveryJoiner.java:60)
        at com.hazelcast.internal.cluster.impl.TcpIpJoiner.joinViaPossibleMembers(TcpIpJoiner.java:136)
        at com.hazelcast.internal.cluster.impl.TcpIpJoiner.doJoin(TcpIpJoiner.java:96)
        at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:137)
        at com.hazelcast.instance.impl.Node.join(Node.java:810)
        at com.hazelcast.instance.impl.Node.start(Node.java:473)
        at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:123)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57)
        at fish.payara.nucleus.hazelcast.HazelcastCore.bootstrapHazelcast(HazelcastCore.java:504)
        at fish.payara.nucleus.hazelcast.HazelcastCore.getInstance(HazelcastCore.java:239)
        at fish.payara.nucleus.config.ClusteredConfig.postConstruct(ClusteredConfig.java:100)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1268)
        at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:309)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
        at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:667)
        at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:54)
        at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:188)
        at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:211)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:334)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
        at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:759)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:722)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:692)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.<init>(ContainerMapper.java:113)
        at com.sun.enterprise.v3.services.impl.GlassfishNetworkListener.configureHttpProtocol(GlassfishNetworkListener.java:165)
        at org.glassfish.grizzly.config.GenericGrizzlyListener.configureSubProtocol(GenericGrizzlyListener.java:456)
        at org.glassfish.grizzly.config.GenericGrizzlyListener.configureProtocol(GenericGrizzlyListener.java:445)
        at org.glassfish.grizzly.config.GenericGrizzlyListener.configure(GenericGrizzlyListener.java:341)
        at com.sun.enterprise.v3.services.impl.GrizzlyProxy.initialize(GrizzlyProxy.java:126)
        at com.sun.enterprise.v3.services.impl.GrizzlyService.createNetworkProxy(GrizzlyService.java:673)
        at com.sun.enterprise.v3.services.impl.GrizzlyService.postConstruct(GrizzlyService.java:595)
        at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:303)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
        at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpOneLevel.run(CurrentTaskFuture.java:762)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: com.hazelcast.cluster.Address not found by com.hazelcast.kubernetes [109]
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1597)
        at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1982)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 64 more
|#]
```

## Steps to reproduce ## 

Start the server with the following command

` payara5/bin/asadmin start-domain -v --postbootcommandfile /path/to/postboot.txt domain1`

when postboot.txt contains

`set-hazelcast-configuration --enabled=true -f "hazelcast.xml" --dynamic=true`

and hazelcast.xml contains

```xml
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hazelcast.com/schema/config https://hazelcast.com/schema/config/hazelcast-config-4.2.xsd">
  <cluster-name>javaee-reference-implementation-1-0-headless.user-jbn.svc.cloud.dbc.dk</cluster-name>
  <network>
    <join>
      <auto-detection enabled="false"/>
      <multicast enabled="false"/>
      <tcp-ip enabled="false"/>
      <aws enabled="false"/>
      <gcp enabled="false"/>
      <eureka enabled="false"/>
      <azure enabled="false"/>
      <kubernetes enabled="true">
        <service-dns>javaee-reference-implementation-1-0-headless.user-jbn.svc.cloud.dbc.dk</service-dns>
      </kubernetes>
    </join>
  </network>
</hazelcast>
```
Be advised that the chosen service-dns must exist for this error to occur. Using a non-existing dns name does not produce this error.

## Environment ##

- **Distribution**: Server Full Profile
- **JDK Version**: OpenJDK Runtime Environment Zulu11.50+19-CA (build 11.0.12+7-LTS)
- **Operating System**: Linux

**Comment by fturizo** [comment]
First, allow me to offer apologies for the delay in this reply, @jbndbc, but this issue fell under the cracks in the past months. On a further review of the use case that you've described, we lack some context and a proper reproducer setup of the Kubernetes that allows us to understand the issue. However, it seems that you are a registered contact for Payara Enterprise support, so would you be willing to raise an official request that we can investigate this issue in more detail?

**Comment by jbndbc** [comment]
I'm currently unable to reproduce since I don't seem to be able to get 5.2021.9 full server to react to anything I put in my hazelcast xml configuration file, and therefore I am not able to configure kubernetes dns discovery at all.

We need to use DNS discovery (as opposed to API discovery) as described here https://github.com/hazelcast/hazelcast-kubernetes#dns-lookup. The hazelcast configuration I have posted in this issue works when using payara micro.

**Comment by fturizo** [comment]
@jbndbc, thanks for the clarification. Unfortunately, the scope of community support requires that in order to proceed with the escalation of this bug report, we need a proper reproducer of the scenario you described. Also, the official Kubernetes discovery mode mechanism for Payara Server only supports the use of Kubernetes API, and DNS discovery is not supported yet. For these reasons I'm afraid that there's not much we can do to proceed on this case.

However, as mentioned earlier, you are a registered Payara Enterprise customer contact, so you can raise an official Payara Enterprise request (even if it applies to Payara Community edition) so we can investigate the issue in more detail.

**Comment by svendiedrichsen** [comment]
This problem also affects my company trying to migrate from 5.2020.5 when the discovery mode `kubernetes` did work to 5.2021.10. Also referenced in the forum https://forum.payara.fish/t/cannot-run-payara-with-kubernetes-discovery-mode/75

**Comment by svendiedrichsen** [comment]
The problem also shows up when using the Kubernetes API lookup on Payara 5.2021.10.
