### ISSUE TITLE
Bug Report:  EJBs can't be initialised/found when injected into and Interceptor in an EAR/FISH-5888

### ISSUE THREAD

**Issue by CarlosMOGoncalves** [payara/Payara#5393]
# Description #
----------
Hello there,

I have found an issue when injecting EJBs into an Interceptor that occurs when we are in an EAR project. In sum, the EJB cannot be found via annotation BUT can be found if we do a manual lookup.

This happens only in EAR projects, even if the EJB is in the same module as the Interceptor. It works fine when packaged into a single WAR, for example on Payara Micro or a single WAR deployed into the Server.

This behaviour was found in Payara Server **5.2020.6** but I tested it with **5.2021.6** and it remains the same

## Expected Outcome ##

Injected EJB into an Interceptor is found and initialised normally.

## Current Outcome ##

When an injected EJB is a Stateless bean an EJBException (that comes from a NameNotFoundException) is thrown that reads:
```
2021-08-26T17:49:27.759+0100|WARNING: javax.ejb.EJBException: javax.ejb.EJBException: javax.ejb.CreateException: Could not create stateless EJB
	at com.sun.ejb.containers.StatelessSessionContainer._getContext(StatelessSessionContainer.java:399)
	at com.sun.ejb.containers.BaseContainer.getContext(BaseContainer.java:2598)
	at com.sun.ejb.containers.BaseContainer.preInvoke(BaseContainer.java:2019)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:210)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
       ...(ommited)
       ...(ommited)
Caused by: javax.naming.NameNotFoundException: No object bound to name java:comp/env/pt.test.ejbs.interceptors.FunctionLoggerInterceptor/dataCache
	at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.lookup(GlassfishNamingManagerImpl.java:765)
	at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.lookup(GlassfishNamingManagerImpl.java:738)
	at com.sun.enterprise.naming.impl.JavaURLContext.lookup(JavaURLContext.java:159)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:476)
```

When the EJB is a Singleton an EJBException (that comes from a NameNotFoundException) is thrown:

```
2021-08-26T17:46:02.230+0100|WARNING: javax.ejb.EJBException: javax.ejb.CreateException: Initialization failed for Singleton PeriodicService
	at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:689)
	at com.sun.ejb.containers.AbstractSingletonContainer.instantiateSingletonInstance(AbstractSingletonContainer.java:421)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:219)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:180)
	at com.sun.ejb.containers.AbstractSingletonContainer.checkInit(AbstractSingletonContainer.java:395)
	at com.sun.ejb.containers.AbstractSingletonContainer._getContext(AbstractSingletonContainer.java:185)
	at com.sun.ejb.containers.CMCSingletonContainer._getContext(CMCSingletonContainer.java:120)
	at com.sun.ejb.containers.BaseContainer.getContext(BaseContainer.java:2598)
	at com.sun.ejb.containers.BaseContainer.preInvoke(BaseContainer.java:2019)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:210)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
        ...(ommited)
        ...(ommited)
Caused by: javax.naming.NameNotFoundException: No object bound to name java:comp/env/pt.test.ejbs.interceptors.FunctionLoggerInterceptor/dataCache
	at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.lookup(GlassfishNamingManagerImpl.java:765)
	at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.lookup(GlassfishNamingManagerImpl.java:738)
	at com.sun.enterprise.naming.impl.JavaURLContext.lookup(JavaURLContext.java:159)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:476)
	... 123 more
```

## Steps to reproduce ## 

First, it must be an EAR project.

Then, all it is needed is a simple Interceptor that has an EJB **injected** into it and then somehow try to initialise that interceptor, for example invoking any bean that is intercepted by it from an endpoint. The server won't be able to initialise it and will throw one of the above exceptions.

You can always use these two projects here: [server ear](https://github.com/CarlosMOGoncalves/payara-test-ear) and this [micro ear](https://github.com/CarlosMOGoncalves/payara-test-war).

The first one is a simple app packaged as an **EAR** meant to be run in **Payara Server**. 

1. It has an endpoint in **webservices module** on a JAX-RS resources called **InterceptorResource**
2. That endpoint calls an EJB called **PeriodicService**
3. That EJB is intercepted by a **FunctionLoggerInterceptor** 
4. That interceptor has a **Singleton EJB** injectd called **DataCacheService**
5. **When** that Interceptor is called it fails with above exception
6. **When** DataCacheService is changed into a Stateless EJB it fails anyway, but the exception is the above refered to Stateless
7. **When** we inject a CDI bean instead (which is commented in the code) it works fine
8. **When** we comment the EJB injection and uncomment the programmatic lookup to try to find it by JNDI, it works perfectly

```
@Interceptor
@FunctionLogger
@Priority(Interceptor.Priority.APPLICATION + 5)
public class FunctionLoggerInterceptor {

    private static final Logger LOGGER = Logger.getLogger(FunctionLoggerInterceptor.class.getSimpleName());

    @EJB
    private DataCacheService dataCache;

    //    @Inject
    //    private CDIServiceBean cdiService;

    @AroundInvoke
    public Object logFunctionResult(InvocationContext invocationContext) throws Exception {

        //        Context context = new InitialContext();
        //        DataCacheService ejbService = (DataCacheService) context.lookup("java:global/application/ejbs/DataCacheService");
        //        ejbService.loadCache();

        Long start = System.currentTimeMillis();
        Object result = invocationContext.proceed();
        Long end = System.currentTimeMillis();
        LOGGER.info("Took " + (end - start) + " milliseconds to complete");

        return result;
    }

}
```

The second project is a WAR packaged application meant to be run in an uber jar in **Payara Micro**.
It can be run by starting it with the payara micro maven plugin after packaging:
`payara-micro:start`

It has a similar structure as the above, except all that code is spread into packages and not modules.
With the same endpoint, calling the same beans, it will work just fine. It will find the EJB, inject it and use it.

I did not investigate any possible cause any further because of time constraints, sadly.

## Environment ##

- **Distribution**: Server Full - Community Edition version `5.2020.6` to `5.2021.7`
- **JDK Version**: 1.8.0_282 - AdoptOpenJDK
- **Operating System**: Windows 10

**Comment by shub8968** [comment]
Hi @CarlosMOGoncalves,

Thanks for clarifying. The JSR  318 | Interceptors 1.2 ref docs read -  "An interceptor instance **may be the target** of dependency injection. Dependency injection is performed when the interceptor instance is created, using the naming context of the associated target class".  However, I have created an internal JIRA with `FISH-5888` pertaining to it. Our platform development team will investigate it further.  It may take a while to fix the issue. You are free to submit a PR to fix this issue if you feel confident to do so. Thanks.

**Comment by CarlosMOGoncalves** [comment]
Hello @shub8968 

I am sorry if it was a bit confusing. Thanks for proceeding with this.
If I am getting it right, it seems the specification does not enforce injection on interceptors, so it becomes a bit of a grey area. I understand. 
Since it works fine on a a single .war I think it would be really nice if it could also be made to work on .ear based projects.

Thank you for your work,
Cheers.
