### ISSUE TITLE
Bug Report:  EJBContainer initialization throws "java.lang.UnsupportedOperationException: This feature requires ASM6"

### ISSUE THREAD

**Issue by gprado-ionos** [payara/Payara#5403]
# Description #
----------

Hi.

I am currently working on a migration of a project from Glassfish to Payara and also moving from java 8 to 11.
Some of our tests uses starts the EjbContainer and the following exceptions appears during the initialization:

```
java.lang.UnsupportedOperationException: This feature requires ASM6
	at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:137)
	at org.objectweb.asm.ClassReader.readModuleAttributes(ClassReader.java:754)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:553)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at org.glassfish.deployment.common.GenericAnnotationDetector.scanArchive(GenericAnnotationDetector.java:146)
	at org.glassfish.deployment.common.GenericAnnotationDetector.hasAnnotationInArchive(GenericAnnotationDetector.java:96)
	at org.glassfish.ejb.embedded.EJBContainerProviderImpl.getRequestedEJBModuleOrLibrary(EJBContainerProviderImpl.java:338)
	at org.glassfish.ejb.embedded.EJBContainerProviderImpl.addModule(EJBContainerProviderImpl.java:383)
	at org.glassfish.ejb.embedded.EJBContainerProviderImpl.addModules(EJBContainerProviderImpl.java:286)
	at org.glassfish.ejb.embedded.EJBContainerProviderImpl.createEJBContainer(EJBContainerProviderImpl.java:132)
	at javax.ejb.embeddable.EJBContainer.createEJBContainer(EJBContainer.java:127)
```

```
java.lang.UnsupportedOperationException: This feature requires ASM7
	at org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:157)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:559)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at org.glassfish.deployment.common.GenericAnnotationDetector.scanArchive(GenericAnnotationDetector.java:146)
	at org.glassfish.deployment.common.GenericAnnotationDetector.hasAnnotationInArchive(GenericAnnotationDetector.java:96)
	at org.glassfish.ejb.embedded.EJBContainerProviderImpl.getRequestedEJBModuleOrLibrary(EJBContainerProviderImpl.java:338)
	at org.glassfish.ejb.embedded.EJBContainerProviderImpl.addModule(EJBContainerProviderImpl.java:383)
	at org.glassfish.ejb.embedded.EJBContainerProviderImpl.addModules(EJBContainerProviderImpl.java:286)
	at org.glassfish.ejb.embedded.EJBContainerProviderImpl.createEJBContainer(EJBContainerProviderImpl.java:132)
	at javax.ejb.embeddable.EJBContainer.createEJBContainer(EJBContainer.java:127)
	```

There was an old issue opened and resolved that was very similar: https://github.com/payara/Payara/issues/4046
Unfortunately, after moving maven dependencies to use `payara-bom` and make use of the patched-jersey version, the exceptions persisted.

After locally patching payara-embedded-all library changing the following class: `org.glassfish.deployment.common.AnnotationScanner` and changing the Opcode declared in the constructor from `Opcodes.ASM5` to `Opcodes.ASM7` tests succeeded.

My question is:  Should this patch be done officially because it is truly a bug or there might be some wrong configuration done on our project that triggered this unexpected exception ?

## Expected Outcome ##

Tests executes successfuly as in the older java version

## Current Outcome ##

```
java.lang.IllegalArgumentException: Cannot resolve reference [Remote ejb-ref name=SOME_NAME,Remote 3.x interface =SOME_INTERFACE,ejb-link=null,lookup=,mappedName=,jndi-name=,refType=Session] because there are [5] ejbs in the application with interface SOME_INTERFACE 
Some of the possible causes: 
1. The EJB bean class was packaged in an ear lib library (or through any other library mechanism which makes the library visible to all component modules), this makes all the component modules include this bean class indirectly. 
2. The EJB bean class was packaged in a component module which references the EJB, either directly or indirectly through Manifest, WEB-INF/lib. 
The EJB bean class should only be packaged in the declaring ejb module and not the referencing modules. The referencing modules should only include EJB interfaces.
	at com.sun.enterprise.deployment.util.ComponentValidator.accept(ComponentValidator.java:353)
	at org.glassfish.ejb.deployment.util.EjbBundleValidator.accept(EjbBundleValidator.java:426)
	at org.glassfish.ejb.deployment.descriptor.EjbDescriptor.visit(EjbDescriptor.java:2798)
	at org.glassfish.ejb.deployment.descriptor.EjbDescriptor.visit(EjbDescriptor.java:2786)
	at org.glassfish.ejb.deployment.util.EjbBundleValidator.accept(EjbBundleValidator.java:117)
	at com.sun.enterprise.deployment.BundleDescriptor.visit(BundleDescriptor.java:618)
	at org.glassfish.ejb.deployment.descriptor.EjbBundleDescriptorImpl.visit(EjbBundleDescriptorImpl.java:736)
```

## Steps to reproduce ## 

If needed, I can try to isolate the configuration in a self contained project.

## Environment ##

- **Distribution**: payara embedded all 5.2021.6
- **JDK Version**: openjdk version "11" 2018-09-25 - OpenJDK Runtime Environment 18.9 (build 11+28)
- **Operating System**: Linux  5.4.0-81-generic #91-Ubuntu SMP

**Comment by shub8968** [comment]
Hi @gprado-ionos,

Will you be able to provide the proper reproducer for the issue?

**Comment by gprado-ionos** [comment]
@shub8968  Sorry for the delay.
I was able to create a small project out of the same code used in the original problem where I faced the issue for the first time.
If you execute the test (which will not succeed), you should be able to see the same exception I described above.
There are some other exceptions that are not related to the original problem.

[asm_error.zip](https://github.com/payara/Payara/files/7137231/asm_error.zip)

**Comment by fturizo** [comment]
Greetings @gprado-ionos, apologies for not coming back to you on this issue for quite a while, it kinda fell under the cracks since it was reported. Indeed the issue that you have encountered has been previously reported in #4844, so we'll proceed to close this one as a duplicate. Since that issue was reported quite a while ago, we are going to prioritize in the upcoming releases so that our Platform Development engineers work on providing a proper solution.
