### ISSUE TITLE
Help: Cannot cast object to itself?!

### ISSUE THREAD

**Issue by mkarg** [payara/Payara#5451]
I noticed the following stack trace in my Payara 5 log:

```
[2021-10-13T15:51:49.073+0200] [Payara 5.2021.7] [WARNUNG] [] [javax.enterprise.web] [tid: _ThreadID=78 _ThreadName=http-thread-pool::http-listener-1(2)] [timeMillis: 1634133109073] [levelValue: 900] [[
  StandardWrapperValve[my.Server]: Servlet.service() for servlet my.Server threw exception
java.lang.ClassCastException: my.ObjectSeries cannot be cast to my.ObjectSeries
	at my.ObjectSeriesJsonbSerializer.serialize(ObjectSeriesJsonbSerializer.java:38)
	at org.eclipse.yasson.internal.serializer.UserSerializerSerializer.serialize(UserSerializerSerializer.java:53)
```

Apparently Payara 5 is unable to cast an object to the same class it already is!

The strange thing is:
* In an isolated Java SE VM  (without Payara) **the exact same binary** (which does an invocation of JSON-B using custom serializer) works pretty well *unchanged* using yasson 1.0.6!
* The line ObjectSeriesJsonbSerializer.java:38 is *the method signature* of the serializer, hence does not contain any executable code; the body itself does not contain *any* casting operations!

**Has anybody an idea why this happens and what could be done to make the code execute in Payara 5 just as fine as on Java SE?**

**Comment by mkarg** [comment]
> I am no Payara expert but IIRC the EAR and WAR classloaders are separate ones. Your archive does ONLY contain your own classes, no libraries?

Yes, my EAR contains only WARs and the WARs only contain my own libs.

I will look into providing a reproducer later this year -- need to finish the current project first.
