### ISSUE TITLE
Bug Report:  simple JSP crashes compiler with JDK11

### ISSUE THREAD

**Issue by dbbernstein** [payara/Payara#5487]
# Description #
  ----------
  
  A very short and simple JSP that worked when compiled for source/target JDK 8 using the JDK11 version of the most recent full server Payara crashes the java compiler when the source and target VM JSP compilation flags are set to Java 11.
  
  ## Expected Outcome ##
  
  There should be no crash and the JSP should be normally compiled and served. In this test case that means a page with a single 'X' character displayed.
  
  ## Current Outcome ##
  
  The java compiler crashes with `unexpected tag: 18` .
  
  ## Steps to reproduce ## 

The `Dockerfile` used changes the values for `compilerSourceVM` and `compilerTargetVM` in `default-web.xml` from `1.8` to `11`.
  
  Command sequence:
  
  ```
  $ # ASSUMES git, mvn, docker, and a local web browser ALREADY INSTALLED
  $ #  AND BROWSER WILL ALLOW HTTPS CONNECTION TO LOCAL HOST SERVING DEFAULT PAYARA CERT
  $ mkdir sandbox
  $ cd sandbox
  $ git clone https://github.com/dbbernstein/tag18
  $ cd tag18/tag18/
  $ mvn package
  $ cp target/tag18.war .
  $ jar xvf tag18.war Dockerfile docker-compose.yml
  $ docker-compose up --build --detach
  $ # ENTER URL https://<my-local-host>:8181/tag18/tag18.jsp IN BROWSER
  ```
  
  Actual run:
  
  ```
  amber:tag18 dbb$ mkdir sandbox
  amber:tag18 dbb$ cd sandbox
  amber:sandbox dbb$ git clone https://github.com/dbbernstein/tag18
  Cloning into 'tag18'...
  remote: Enumerating objects: 26, done.
  remote: Counting objects: 100% (26/26), done.
  remote: Compressing objects: 100% (16/16), done.
  remote: Total 26 (delta 3), reused 26 (delta 3), pack-reused 0
  Unpacking objects: 100% (26/26), done.
  amber:sandbox dbb$ cd tag18/tag18/
  amber:tag18 dbb$ mvn package
  [INFO] Scanning for projects...
  [INFO] 
  [INFO] --------------------------< com.orgmob:tag18 >--------------------------
  [INFO] Building tag18 0.0.1-SNAPSHOT
  [INFO] --------------------------------[ war ]---------------------------------
  [INFO] 
  [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ tag18 ---
  [INFO] Using 'UTF-8' encoding to copy filtered resources.
  [INFO] skip non existing resourceDirectory /Users/dbb/bugsext/tag18/sandbox/tag18/tag18/src/main/resources
  [INFO] 
  [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ tag18 ---
  [INFO] No sources to compile
  [INFO] 
  [INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ tag18 ---
  [INFO] Using 'UTF-8' encoding to copy filtered resources.
  [INFO] skip non existing resourceDirectory /Users/dbb/bugsext/tag18/sandbox/tag18/tag18/src/test/resources
  [INFO] 
  [INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ tag18 ---
  [INFO] No sources to compile
  [INFO] 
  [INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ tag18 ---
  [INFO] No tests to run.
  [INFO] 
  [INFO] --- maven-war-plugin:3.2.2:war (default-war) @ tag18 ---
  [INFO] Packaging webapp
  [INFO] Assembling webapp [tag18] in [/Users/dbb/bugsext/tag18/sandbox/tag18/tag18/target/tag18]
  [INFO] Processing war project
  [INFO] Copying webapp resources [/Users/dbb/bugsext/tag18/sandbox/tag18/tag18/src/main/webapp]
  [INFO] Webapp assembled in [50 msecs]
  [INFO] Building war: /Users/dbb/bugsext/tag18/sandbox/tag18/tag18/target/tag18.war
  [INFO] ------------------------------------------------------------------------
  [INFO] BUILD SUCCESS
  [INFO] ------------------------------------------------------------------------
  [INFO] Total time:  1.381 s
  [INFO] Finished at: 2021-11-04T13:25:23-07:00
  [INFO] ------------------------------------------------------------------------
  amber:tag18 dbb$ cp target/tag18.war .
  amber:tag18 dbb$ jar xvf tag18.war Dockerfile docker-compose.yml
   inflated: Dockerfile
   inflated: docker-compose.yml
  amber:tag18 dbb$ docker-compose up --build --detach
  Building tag18
  [+] Building 0.9s (8/8) FINISHED                                                                                                                                          
   => [internal] load build definition from Dockerfile                                                                                                                 0.1s
   => => transferring dockerfile: 2.00kB                                                                                                                               0.0s
   => [internal] load .dockerignore                                                                                                                                    0.0s
   => => transferring context: 2B                                                                                                                                      0.0s
   => [internal] load metadata for docker.io/payara/server-full:5.2021.8-jdk11                                                                                         0.0s
   => CACHED [1/3] FROM docker.io/payara/server-full:5.2021.8-jdk11                                                                                                    0.0s
   => [internal] load build context                                                                                                                                    0.0s
   => => transferring context: 3.29kB                                                                                                                                  0.0s
   => [2/3] COPY TAG18.WAR /opt/payara/appserver/glassfish/domains/domain1/autodeploy/                                                                                 0.1s
   => [3/3] RUN             sed -z -i.bak   -e "s,\(compilerSourceVM</param-name>\n[ \t]*<param-value>\).*<,\111<,mg"   -e "s,\(compilerTargetVM</param-name>\n[ \t]*  0.4s
   => exporting to image                                                                                                                                               0.1s
   => => exporting layers                                                                                                                                              0.1s
   => => writing image sha256:188ed15baeb1879b4d65e5e8ef4bb2c6cfba95dcf80504e23a8b96dfcb380012                                                                         0.0s
   => => naming to docker.io/library/tag18_tag18                                                                                                                       0.0s
  Successfully built 188ed15baeb1879b4d65e5e8ef4bb2c6cfba95dcf80504e23a8b96dfcb380012
  Creating tag18 ... done
  amber:tag18 dbb$ 
  amber:tag18 dbb$ # GO TO BROWSER THEN GO TO URL https://amber.local:8181/tag18/tag18.jsp
  amber:tag18 dbb$ # RETURNED PAGE IS:
  ```
  
  > **HTTP Status 500 - Internal Server Error**
  > 
  > **type** Exception report
  > 
  > **message** Internal Server Error
  > 
  > **description** The server encountered an internal error that prevented it from fulfilling this request.
  > 
  > **exception**
  > 
  > `org.apache.jasper.JasperException: PWC6033: Error in Javac compilation for JSP`
  > **root cause**
  > 
  > `java.io.IOException: unexpected tag: 18`
  > **note** The full stack traces of the exception and its root causes are available in the Payara Server 5.2021.8 #badassfish logs.
  > 
  > **Payara Server 5.2021.8 #badassfish**
  
  ```
  amber:tag18 dbb$ 
  amber:tag18 dbb$ # LOOK AT PAYARA LOG TO SEE EXCEPTION STACK TRACE
  amber:tag18 dbb$ 
  amber:tag18 dbb$ docker exec -it tag18 bash --login
  payara@11d7bbc3d6d4:~$ cd appserver/glassfish/domains/domain1/logs/
  payara@11d7bbc3d6d4:~/appserver/glassfish/domains/domain1/logs$ tail -66 server.log 
  [2021-11-04T20:30:08.277+0000] [Payara 5.2021.8] [INFO] [NCLS-DEPLOYMENT-02035] [javax.enterprise.system.tools.deployment.autodeploy] [tid: _ThreadID=110 _ThreadName=payara-executor-service-scheduled-task] [timeMillis: 1636057808277] [levelValue: 800] [[
    [AutoDeploy] Successfully autodeployed : /opt/payara/appserver/glassfish/domains/domain1/autodeploy/tag18.war.]]
  
  [2021-11-04T20:32:03.511+0000] [Payara 5.2021.8] [SEVERE] [] [] [tid: _ThreadID=85 _ThreadName=http-thread-pool::http-listener-2(4)] [timeMillis: 1636057923511] [levelValue: 1000] [[
    java.io.IOException: unexpected tag: 18
	  at org.apache.jasper.compiler.SmapUtil$SDEInstaller.copyConstantPool(SmapUtil.java:459)
	  at org.apache.jasper.compiler.SmapUtil$SDEInstaller.addSDE(SmapUtil.java:304)
	  at org.apache.jasper.compiler.SmapUtil$SDEInstaller.<init>(SmapUtil.java:257)
	  at org.apache.jasper.compiler.SmapUtil$SDEInstaller.install(SmapUtil.java:246)
	  at org.apache.jasper.compiler.SmapUtil.installSmap(SmapUtil.java:167)
	  at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:406)
	  at org.apache.jasper.compiler.Compiler.compile(Compiler.java:453)
	  at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:627)
	  at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:375)
	  at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
	  at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
	  at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	  at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1637)
	  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:259)
	  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	  at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
	  at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
	  at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
	  at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
	  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	  at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	  at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	  at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200)
	  at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	  at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	  at java.base/java.lang.Thread.run(Thread.java:834)
  ]]
  
  [2021-11-04T20:32:03.521+0000] [Payara 5.2021.8] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=85 _ThreadName=http-thread-pool::http-listener-2(4)] [timeMillis: 1636057923521] [levelValue: 900] [[
    StandardWrapperValve[jsp]: Servlet.service() for servlet jsp threw exception
  java.io.IOException: unexpected tag: 18
	  at org.apache.jasper.compiler.SmapUtil$SDEInstaller.copyConstantPool(SmapUtil.java:459)
	  at org.apache.jasper.compiler.SmapUtil$SDEInstaller.addSDE(SmapUtil.java:304)
	  at org.apache.jasper.compiler.SmapUtil$SDEInstaller.<init>(SmapUtil.java:257)
	  at org.apache.jasper.compiler.SmapUtil$SDEInstaller.install(SmapUtil.java:246)
	  at org.apache.jasper.compiler.SmapUtil.installSmap(SmapUtil.java:167)
	  at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:406)
	  at org.apache.jasper.compiler.Compiler.compile(Compiler.java:453)
	  at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:627)
	  at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:375)
	  at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
	  at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
	  at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	  at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1637)
	  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:259)
	  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	  at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
	  at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
	  at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
	  at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
	  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	  at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	  at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	  at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200)
	  at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	  at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	  at java.base/java.lang.Thread.run(Thread.java:834)
  ]]
  
payara@11d7bbc3d6d4:~/appserver/glassfish/domains/domain1/logs$ # SHOW DIFFERENCE IN default-web.xml
payara@11d7bbc3d6d4:~/appserver/glassfish/domains/domain1/logs$ cd /opt/payara/appserver/glassfish/domains/domain1/config
payara@11d7bbc3d6d4:~/appserver/glassfish/domains/domain1/config$ diff default-web.xml.bak default-web.xml
309c309
<       <param-value>1.8</param-value>
---
>       <param-value>11</param-value>
313c313
<       <param-value>1.8</param-value>
---
>       <param-value>11</param-value>
payara@11d7bbc3d6d4:~/appserver/glassfish/domains/domain1/config$ 
  ```
  
  ## Environment ##
  
  - **Distribution**: docker hub image payara/server-full:5.2021.8-jdk11, so Server Full Profile
  - **JDK Version**: docker hub image payara/server-full:5.2021.8-jdk11, so 11 - OpenJDK
  - **Operating System**: dockerized Payara, so Linux
  
  [tag18.jsp attached as .txt](https://github.com/payara/Payara/files/7478672/tag18.jsp.txt)
[Dockerfile attached as .txt](https://github.com/payara/Payara/files/7479284/Dockerfile.txt)
[docker-compose.yml attached as.txt](https://github.com/payara/Payara/files/7479285/docker-compose.yml.txt)

**Comment by rdebusscher** [comment]
I think we can only fix this for Payara 6. (will be based on JDK 11)

Payara 5 is still JDK 8 based and we can't update the Jasper Compiler for JDK 11.

To be investigated further.

**Comment by shub8968** [comment]
Hi @dbbernstein,

We would require some time to verify if the Jasper compiler is no longer working as per the use case mentioned. It is not a priority as per Payara Platform Roadmap at the moment. If you are interested in getting support for this scenario, please contact Payara Enterprise in this regard.

**Comment by dbbernstein** [comment]
I think that closing the issue is wrong.

I'm not sure why it would require any significant amount of time to verify that the use case doesn't work. I spent hours creating an amazingly pared down example that matches Payara's criteria for test case submission. The extremely detailed few commands I included in my submission show the bug. The entire task ought to require less than five minutes.

The image is marked as "JDK 11", it seems reasonable to expect that Java 11 code should work in a JSP. Was there even any documentation explicitly saying don't use Java 11 in a JSP for Payara 5?

If the Payara team has decided that it will not fix the issue currently, then it should leave the issue open and marked for Payara 6 review. When Payara 6 happens, verify that the test case works and close the issue then.

**Comment by shub8968** [comment]
Hi @dbbernstein,

My apology if you get me wrong. It was not about verifying that the use case doesn't work(I have verified it already before commenting) but about verifying that it can be fixed for Java 11 without breaking the functionality on Java 8.  For now, we are marking this issue as open.

**Comment by fturizo** [comment]
@dbbernstein, apologies for the back and forth on this issue, but we have to let it be closed due to the following reasons:

* As previously mentioned, the cause of the error that you are encountering is due to the Apache Jasper compiler not supporting JSP compilation using JDK 11, due to Payara Server being strictly built on top of JDK 8.
* We have intentions to make Payara Server 6.x being built using Java 11, but we have no explicit timetable for achieving this milestone yet. Even if this condition is met, we have to investigate whether we can properly support the Apache Jasper compiler using JDK 11+.
* We understand that you'd like to have this issue remaining open until Payara 6.x is officially out in the open, but our community support process clearly states that we only support the current release of the Community Edition. Instead of leaving this issue open indefinitely, we'd like you to properly open an enhancement request to support the Apache Jasper Compiler on JDK 11+ when Payara Server 6.x is fully out in the open.

Many thanks for your understanding and again let me offer apologies for the inconvience.
