### ISSUE TITLE
In Payara 5.2021.1 running web app with Hazelcast 3.x raises an error

### ISSUE THREAD

**Issue by apanazzolo** [payara/Payara#5501]
# Description #
----------
I've deployed a web application that includes Hazelcast 3.5.4 in Payara 5.2020.7 and it works. But when I've moved the application to the new version 5.2121.1 (the first one that incluides Hazelcast 4.0) my application raises an Exception.
I've also try to disable delegation of classloader, but the error persists.
```
nested exception is com.hazelcast.core.HazelcastException: java.lang.ClassCastException: Cannot cast com.hazelcast.cp.internal.datastructures.atomicr
ef.AtomicRefDataSerializerHook to com.hazelcast.nio.serialization.DataSerializerHook
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1420)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:291)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:190)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:580)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:895)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:425)
        at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:276)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:197)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:47)
        at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:5178)
        at com.sun.enterprise.web.WebModule.contextListenerStart(WebModule.java:681)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:5756)
        at com.sun.enterprise.web.WebModule.start(WebModule.java:619)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:958)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:941)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:694)
        at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1851)
        at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1603)
        at com.sun.enterprise.web.WebApplication.start(WebApplication.java:108)
        at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123)
        at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:293)
        at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:364)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:623)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:654)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:645)
        at org.glassfish.deployment.admin.InstanceDeployCommand.execute(InstanceDeployCommand.java:223)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:556)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:552)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
```

## Expected Outcome ##

Application up and running

## Current Outcome ##

`Caused by: com.hazelcast.core.HazelcastException: java.lang.ClassCastException: Cannot cast com.hazelcast.cp.internal.datastructures.atomicref.AtomicRefDataSerializerHook to com.hazelcast.nio.serialization.DataSerializerHook
	at com.hazelcast.util.ServiceLoader$1.next(ServiceLoader.java:99)
	at com.hazelcast.nio.serialization.DataSerializer.<init>(DataSerializer.java:49)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.<init>(SerializationServiceImpl.java:132)
	at com.hazelcast.nio.serialization.DefaultSerializationServiceBuilder.createSerializationService(DefaultSerializationServiceBuilder.java:221)
	at com.hazelcast.nio.serialization.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:194)
	at com.hazelcast.instance.DefaultNodeExtension.createSerializationService(DefaultNodeExtension.java:113)
	at com.hazelcast.instance.Node.<init>(Node.java:160)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:120)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:152)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:135)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:111)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
	at it.hcare.nlp.orion.hazelcast.HazelcastHolder.load(HazelcastHolder.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1544)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1485)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1417)
	... 102 more
Caused by: java.lang.ClassCastException: Cannot cast com.hazelcast.cp.internal.datastructures.atomicref.AtomicRefDataSerializerHook to com.hazelcast.nio.serialization.DataSerializerHook
	at java.lang.Class.cast(Class.java:3369)
	at com.hazelcast.util.ServiceLoader$1.next(ServiceLoader.java:97)
	... 121 more
`

## Environment ##

- **Distribution**:  Payara 5.2121.1 Full Community Edition
- **JDK Version**:  Oracle (ex Sun) jdk1.8.0_202
- **Operating System**: CentoOs 7.x

**Comment by shub8968** [comment]
HIi @apanazzolo,

Would you be able to verify it on the latest release of the Payara  Server? Also, would you be kind enough to share the sample reproducer app?

**Comment by apanazzolo** [comment]
> HIi @apanazzolo,
> 
> Would you be able to verify it on the latest release of the Payara Server? Also, would you be kind enough to share the sample reproducer app?

I'm not able to run my web app with the latest version, because I need JEE8 and versions after 5.2021.1 have Jakarta
Attached a simple maven web project. Simply build and deploy on payara 5.2021.1. In the server log you will see the Exception.
[hz.zip](https://github.com/payara/Payara/files/7563595/hz.zip)

.

**Comment by AleksNo** [comment]
@apanazzolo

Java EE 8 and Jakarta EE 8 are binary compatible. Jakarta EE 8 uses also the javax.* namespace because Jakarta EE 8 compatible servers pass the Java EE 8 TCK. So you could give a try.

Cheers

**Comment by apanazzolo** [comment]
I've tried to start the sample applicaiton in payara 5.2121.9 but the error remains
I've also try to add glassfish-web.xml to load class from war but the error remains.

```
<glassfish-web-app>
	<parameter-encoding default-charset="UTF-8" />
	<class-loader delegate="false"/>
</glassfish-web-app>
```

**Comment by shub8968** [comment]
Hi @apanazzolo,

I am unable to deploy the provided reproducer app on Payara `5.2020.7` (according to you it is working on it). Would you be able to verify if it is the correct one and provide steps to build if any?

**Comment by apanazzolo** [comment]
the zip file contians a maven project. simply unzip and perform mvn package. I've attached the compiled war to this post
[hz_war.zip](https://github.com/payara/Payara/files/7582322/hz_war.zip)

**Comment by apanazzolo** [comment]
Hi, any news about this topic?

**Comment by shub8968** [comment]
Hi @apanazzolo,

The use case which you are trying to achieve is not practical. Payara Server supports configuring Hazelcast through the Admin Console and asadmin commands.

**Comment by shub8968** [comment]
Closing due to inactivity.
