### ISSUE TITLE
Problem with mcAddress on payara micro

### ISSUE THREAD

**Issue by koduki** [payara/Payara#555]
I want to change multicast address group of Hazelcast.
But some errors are raised. Is this correct work?

payara-version: payara-micro-4.1.1.154.jar 
java-version: Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
OS: Mac OS 10.11.1

```
% java -jar ~/Downloads/payara-micro-4.1.1.154.jar --deploy target/example-payara_micro.war --mcAddress 224.2.2.4 --mcPort 2904
Dec 07, 2015 8:23:52 PM org.glassfish.security.services.impl.authorization.AuthorizationServiceImpl initialize
INFO: Authorization Service has successfully initialized.
Dec 07, 2015 8:23:52 PM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 5.1.2.Final
Exception in thread "main" fish.payara.micro.BootstrapException: PlainTextActionReporterFAILURENo configuration found for server.hazelcast-runtime-configuration
	at fish.payara.micro.PayaraMicro.bootStrap(PayaraMicro.java:714)
	at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:105)
Caused by: org.glassfish.embeddable.GlassFishException: PlainTextActionReporterFAILURENo configuration found for server.hazelcast-runtime-configuration
	at com.sun.enterprise.glassfish.bootstrap.ConfiguratorImpl.configure(ConfiguratorImpl.java:75)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishImpl.configure(GlassFishImpl.java:71)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishImpl.<init>(GlassFishImpl.java:65)
	at com.sun.enterprise.glassfish.bootstrap.StaticGlassFishRuntime$1.<init>(StaticGlassFishRuntime.java:116)
	at com.sun.enterprise.glassfish.bootstrap.StaticGlassFishRuntime.newGlassFish(StaticGlassFishRuntime.java:116)
	at fish.payara.micro.PayaraMicro.bootStrap(PayaraMicro.java:694)
```

**Comment by smillidge** [comment]
This is a bug. You can use --hzConfigFile to specify an alternative Hazelcast configuration to change the port and address
