### ISSUE TITLE
Bug Report:  java.lang.LinkageError in Payara 5.2021.10 when using slf4j/logback for logging and Apache Santuario/FISH-5981

### ISSUE THREAD

**Issue by gessnerfl** [payara/Payara#5554]
# Description #
I currently face the issue with my enterprise application on Payara 5.2021.10. I currently get a `java.lang.LinkageError` when using log message is created from Apache Santuario library which is used by both the application and the application server.

```
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of org/apache/felix/framework/BundleWiringImpl$BundleClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of sun/misc/Launcher$ExtClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:423)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
	at org.apache.xml.security.Init.<clinit>(Init.java:57)
       ...
```

SLF4J is included in the patched version of `webservices-osgi.jar` because the updated version of Apache Santuario is now using SLF4J as logging facade. In this bundle SLF4J is private and not exported to other OSGi bundles. 

In the Payara server I install SLF4J together with logback as a shaded JAR to the ext classloader and make it also available to osgi with bundle which should exports the versions provided through the ext classloader (inspired by https://github.com/goodees/goodees/tree/master/payara-logback).

I already tried to align SLF4J version or to provide Apache Santuario through the application but all does not fix the issue. I think the problem is that the `ILoggerFactory` loaded by the osgi bundle is a different object compared to the one used by logback.

How can I resolve this? Currently the only option I see is to go back to Payara version 5.2021.9.

## Expected Outcome ##

SLF4J/Logback should working as it was the case with version 5.2021.9

## Current Outcome ##

SLF4J used by Apache Santuario fails to initialize do to issue mentioned above

## Steps to reproduce ## 

I created a sample application including a docker image and docker compose in the github repository: https://github.com/gessnerfl/payara_5_2021_10_slf4j_issue

## Environment ##

- **Distribution**: Server Full Profile 
- **JDK Version**: 8 u312 - Amazon Corretto
- **Operating System**: Linux

**Comment by shub8968** [comment]
Hi @gessnerfl,

Would you be able to provide the proper reproducer app? I am getting  build error  `Non-resolvable parent POM for de.gessnerfl:payara-slf4j-issue:1.0.0-SNAPSHOT: com.tis:parent:pom:1.0.7 was not found in  ......`

**Comment by gessnerfl** [comment]
Hi @shub8968

Sorry forgot to remove the unneeded parent pom. I pushed a change. Should work now.

**Comment by shub8968** [comment]
Hi @gessnerfl,

I am getting below trace while executing `docker-compose up`.  

Starting payara_5_2021_10_slf4j_issue_sample-app_1 ... done
Attaching to payara_5_2021_10_slf4j_issue_sample-app_1
sample-app_1  | startup.sh: set: line 2: illegal option -
payara_5_2021_10_slf4j_issue_sample-app_1 exited with code 2

**Comment by gessnerfl** [comment]
This is strange. I executed the same steps again on my MacBook and it worked perfectly fine. 
Nevertheless I cleanup the script and removed the `set -e` option.
I hope this is working now properly. Sorry for the inconvenience.

**Comment by shub8968** [comment]
Hi @gessnerfl,

Recently we have to component upgrade due to a security fix - https://docs.payara.fish/community/docs/release-notes/release-notes-2021-10.html#_security_fixes.  
I have raised an internal JIRA `FISH-5981` in order to address this issue. Also, it is recommended to consider Payara Enterprise for running Enterprise-grade applications and for a fix to the earliest.

**Comment by gessnerfl** [comment]
Any update on this topic? Checked the current release and it seems that slf4j ist still bundled in the same way as reported in this bug report.
