### ISSUE TITLE
Bug Report: GRIZZLY exception when a trustore is used with PKCS11

### ISSUE THREAD

**Issue by Tenariel** [payara/Payara#5571]
## Description ##
Hi everyone,
I wanted to upgrade my payara server (from 5.2020.2 to the latest version) but I found a strange exception when I try to connect with any HTTPS page in my application. After many tests, it appears that the bug only occurs when I use a PKCS11 configuration with the provider SUNPKCS11. The switch version of this bug is in the version 5.2021.5 (before the software work and after I have an exception). 
## Steps to reproduce ## 
I create a simple procedure to reproduce the bug. This procedure required a PKCS11 HSM (soft or hard) with a certificate name s1as inside
1*) create an empty web project on netbeans (it's a simple project that show a http page hello world). Any project that use https can work. But if needed i can provide the project and/or the war file. 
2°) unzip the official payara v5.2021.4
3°) deploy the application
4°) check if the https page work
6°) stop the server
7°) change the configuration file :
-	Remove the jvm option : 
o	asadmin delete-jvm-options '-Djavax.net.ssl.keyStore=${com.sun.aas.instanceRoot}/config/keystore.jks'
o	asadmin delete-jvm-options '-Djavax.net.ssl.trustStore=${com.sun.aas.instanceRoot}/config/cacerts.jks'
-	add the jvm option :
o	create-jvm-options -Djavax.net.ssl.keyStoreType=PKCS11
o	create-jvm-options -Djavax.net.ssl.trustStoreType=PKCS11

8°) change the java security file to add the correct HSM configuration file
For example, here's a fragment of the java.security file that installs the SunPKCS11 provider with the configuration file /opt/bar/cfg/pkcs11.cfg. 
	configuration for security providers 1-12 omitted
	security.provider.13=SunPKCS11 /opt/bar/cfg/pkcs11.cfg
9°) start the server
10°) check if the https page work
11°) redo all the step but with the server V5.2021.5 (or later)
## Expected Outcome ##
The expected outcome is the same behavior between the version V5.2021.4 and V5.2021.5

The test is created to check if the page work in https with and without pkcs11 in all version. 
## Current Outcome ##
The V5.2021.4 work correctly but the version V5.2021.5 have the following exception

[2022-01-19T10:06:37.015+0000] [Payara 5.2021.5] [WARNING] [] [javax.enterprise.network.config] [tid: _ThreadID=74 _ThreadName=http-thread-pool::http-listener-2(1)] [timeMillis: 1642586797015] [levelValue: 900] [[
  GRIZZLY0050: SSL support could not be configured!
java.io.IOException: TrustManagerFactoryImpl is not initialized
        at org.glassfish.grizzly.config.ssl.JSSE14SocketFactory.init(JSSE14SocketFactory.java:163)
        at org.glassfish.grizzly.config.SSLConfigurator.initializeSSLContext(SSLConfigurator.java:320)
        at org.glassfish.grizzly.config.SSLConfigurator.configureSSL(SSLConfigurator.java:180)
        at org.glassfish.grizzly.config.SSLConfigurator$InternalSSLContextConfigurator.createSSLContext(SSLConfigurator.java:466)
        at org.glassfish.grizzly.ssl.SSLEngineConfigurator.createSSLEngine(SSLEngineConfigurator.java:185)
        at org.glassfish.grizzly.ssl.SSLEngineConfigurator.createSSLEngine(SSLEngineConfigurator.java:162)
        at org.glassfish.grizzly.ssl.SSLBaseFilter$SSLTransportFilterWrapper.handleRead(SSLBaseFilter.java:1122)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.base/java.lang.Thread.run(Thread.java:834)
]]

[2022-01-19T10:06:37.021+0000] [Payara 5.2021.5] [WARNING] [] [org.glassfish.grizzly.filterchain.DefaultFilterChain] [tid: _ThreadID=74 _ThreadName=http-thread-pool::http-listener-2(1)] [timeMillis: 1642586797021] [levelValue: 900] [[
  GRIZZLY0013: Exception during FilterChain execution
java.lang.NullPointerException
        at org.glassfish.grizzly.ssl.SSLEngineConfigurator.createSSLEngine(SSLEngineConfigurator.java:190)
        at org.glassfish.grizzly.ssl.SSLEngineConfigurator.createSSLEngine(SSLEngineConfigurator.java:162)
        at org.glassfish.grizzly.ssl.SSLBaseFilter$SSLTransportFilterWrapper.handleRead(SSLBaseFilter.java:1122)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.base/java.lang.Thread.run(Thread.java:834)
]]
## Environment ##

- **Distribution**: Server Full Profile
- **JDK Version**:  11.0.8+11  -OpenJDK
- **Operating System**:  linux alpine

If you need information or answers, i will be happy to help you.

Regards,

Tenariel

**Comment by shub8968** [comment]
Hi @Tenariel,

Would you be able to verify it on the latest Payara release i.e,  `5.2021.10`? Also if you can provide the sample PKCS11 file.

**Comment by Tenariel** [comment]
i tested with the following version (only changed the payara version between the test); 
- 5.2021.1 => no exception and my program work
- 5.2021.3 => no exception and my program work
- 5.2021.4 => no exception and my program work
- 5.2021.5 => exception found when we access with any https connection
- 5.2021.6 => exception found when we access with any https connection
- 5.2021.10 => exception found when we access with any https connection

for the PKCS11 file i am not sure what you want so here my pkcs11.cfg (it's the file that are link with the sunpkcs11 provider in the java security file):


name = netHSM
library = /tw/netHsmDist/libnethsmpkcs11.so
slot = 1
attributes(*,*,*) = {
        CKA_TOKEN = true
}

the line in my java.security.file ; security.provider.12=SunPKCS11 /opt/project/etc/pkcs11.cfg

**Comment by OndroMih** [comment]
This was most probably introduced by https://docs.payara.fish/community/docs/documentation/payara-server/server-configuration/ssl-certificates.html#loading-certificates-from-multiple-keystores, which modifies the `SSLConfigurator` and `JSSE14SocketFactory` classes. Try using the new feature to add [multiple keystores](https://docs.payara.fish/community/docs/documentation/payara-server/server-configuration/ssl-certificates.html#loading-certificates-from-multiple-keystores) if you want to use a keystore defined in the JDK.

**Comment by Tenariel** [comment]
I tested your solution and it seems to work with this configuration. From what I understand, I just need to use the <-Dfish.payara.ssl.additionalKeyStores=/path/to/keystore.jks> option by replacing the path with the path of the PKCS11 configuration file.

On the other hand from what I see, it is necessary to have the option javax.ssl.keystore (and trustore). How to be sure that payara will not use them?

**Comment by shub8968** [comment]
Hi @Tenariel,

When specifying the key or trust store for a specific listener, this (-Dfish.payara.ssl.additionalKeyStores) is deemed as an absolute and any additional key or trust stores are not considered.
