### ISSUE TITLE
Bug Report: Reployment of EAR makes a calling WAR failing because of Class instance mismatch

### ISSUE THREAD

**Issue by StefanKock** [payara/Payara#5597]
# Description #
----------

When deploying applications via autodeploy feature (`<domain-root>/autodeploy`), after the second deployment of an EAR file with Remote EJBs the following calls from WARs (same domain) result in exceptions because of class instance checks where `A.class != A.class` because they are coming from different class loader instances.

This was working with versions 5.192 and 5.194, but not any newer version we tested. 
One suspicion is that the [Hot Deploy Feature (v5.201)](https://blog.payara.fish/hot-deploy-feature-in-payara-platform-5.201) caused this behaviour.

## Expected Outcome ##

Redeployment of applications should work so that inter-application invocations do not result in ClassLoader problems.

## Current Outcome ##

A class instance comparison fails: When initializing the EJBs the ClassLoaders and Classes to check differ.
Debug with break point on `UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)` to see this.

<details>
<summary>Resulting exception (StackTrace)</summary>

```bash
sormas-docker-sormas-1    | [2022-02-02T09:44:19.425+0100] [Payara 5.2021.10] [SEVERE] [AS-WEB-CORE-00108] [javax.enterprise.web.core] [tid: _ThreadID=109 _ThreadName=payara-executor-service-scheduled-task] [timeMillis: 1643791459425] [levelValue: 1000] [[
sormas-docker-sormas-1    |   ContainerBase.addChild: start:
sormas-docker-sormas-1    | org.apache.catalina.LifecycleException: javax.ejb.EJBException: javax.ejb.EJBException: javax.ejb.CreateException: Could not create stateless EJB
sormas-docker-sormas-1    |     at org.apache.catalina.core.StandardContext.start(StandardContext.java:5778)
sormas-docker-sormas-1    |     at com.sun.enterprise.web.WebModule.start(WebModule.java:619)
sormas-docker-sormas-1    |     at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:958)
sormas-docker-sormas-1    |     at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:941)
sormas-docker-sormas-1    |     at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:694)
sormas-docker-sormas-1    |     at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1851)
sormas-docker-sormas-1    |     at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1603)
sormas-docker-sormas-1    |     at com.sun.enterprise.web.WebApplication.start(WebApplication.java:107)
sormas-docker-sormas-1    |     at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123)
sormas-docker-sormas-1    |     at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:292)
sormas-docker-sormas-1    |     at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:361)
sormas-docker-sormas-1    |     at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:623)
sormas-docker-sormas-1    |     at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:592)
sormas-docker-sormas-1    |     at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:556)
sormas-docker-sormas-1    |     at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:552)
sormas-docker-sormas-1    |     at java.base/java.security.AccessController.doPrivileged(Native Method)
sormas-docker-sormas-1    |     at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
sormas-docker-sormas-1    |     at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:551)
sormas-docker-sormas-1    |     at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:582)
sormas-docker-sormas-1    |     at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:574)
sormas-docker-sormas-1    |     at java.base/java.security.AccessController.doPrivileged(Native Method)
sormas-docker-sormas-1    |     at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
sormas-docker-sormas-1    |     at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:573)
sormas-docker-sormas-1    |     at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1497)
sormas-docker-sormas-1    |     at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:120)
sormas-docker-sormas-1    |     at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1879)
sormas-docker-sormas-1    |     at org.glassfish.deployment.autodeploy.AutoOperation.run(AutoOperation.java:149)
sormas-docker-sormas-1    |     at org.glassfish.deployment.autodeploy.AutoDeployer.deploy(AutoDeployer.java:532)
sormas-docker-sormas-1    |     at org.glassfish.deployment.autodeploy.AutoDeployer.deployAll(AutoDeployer.java:437)
sormas-docker-sormas-1    |     at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:371)
sormas-docker-sormas-1    |     at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:362)
sormas-docker-sormas-1    |     at org.glassfish.deployment.autodeploy.AutoDeployService$1.run(AutoDeployService.java:231)
sormas-docker-sormas-1    |     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
sormas-docker-sormas-1    |     at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
sormas-docker-sormas-1    |     at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
sormas-docker-sormas-1    |     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
sormas-docker-sormas-1    |     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
sormas-docker-sormas-1    |     at java.base/java.lang.Thread.run(Thread.java:829)
sormas-docker-sormas-1    | Caused by: javax.ejb.EJBException: javax.ejb.EJBException: javax.ejb.CreateException: Could not create stateless EJB
sormas-docker-sormas-1    |     at com.sun.ejb.containers.StatelessSessionContainer._getContext(StatelessSessionContainer.java:399)
sormas-docker-sormas-1    |     at com.sun.ejb.containers.BaseContainer.getContext(BaseContainer.java:2607)
sormas-docker-sormas-1    |     at com.sun.ejb.containers.BaseContainer.preInvoke(BaseContainer.java:2024)
sormas-docker-sormas-1    |     at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:204)
sormas-docker-sormas-1    |     at com.sun.ejb.containers.EJBObjectInvocationHandlerDelegate.invoke(EJBObjectInvocationHandlerDelegate.java:79)
sormas-docker-sormas-1    |     at com.sun.proxy.$Proxy964.getAuthenticationProvider(Unknown Source)
sormas-docker-sormas-1    |     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sormas-docker-sormas-1    |     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sormas-docker-sormas-1    |     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
sormas-docker-sormas-1    |     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
sormas-docker-sormas-1    |     at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie.dispatchToMethod(ReflectiveTie.java:143)
sormas-docker-sormas-1    |     at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie._invoke(ReflectiveTie.java:173)
sormas-docker-sormas-1    |     at com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatchToServant(ServerRequestDispatcherImpl.java:528)
sormas-docker-sormas-1    |     at com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatch(ServerRequestDispatcherImpl.java:199)
sormas-docker-sormas-1    |     at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequestRequest(MessageMediatorImpl.java:1565)
sormas-docker-sormas-1    |     at com.sun.corba.ee.impl.protocol.SharedCDRClientRequestDispatcherImpl.marshalingComplete(SharedCDRClientRequestDispatcherImpl.java:128)
sormas-docker-sormas-1    |     at com.sun.corba.ee.impl.protocol.ClientDelegateImpl.invoke(ClientDelegateImpl.java:258)
sormas-docker-sormas-1    |     at com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.privateInvoke(StubInvocationHandlerImpl.java:188)
sormas-docker-sormas-1    |     at com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.invoke(StubInvocationHandlerImpl.java:140)
sormas-docker-sormas-1    |     at com.sun.corba.ee.impl.presentation.rmi.codegen.CodegenStubBase.invoke(CodegenStubBase.java:226)
sormas-docker-sormas-1    |     at de.symeda.sormas.api.__ConfigFacade_Remote_DynamicStub.getAuthenticationProvider(de/symeda/sormas/api/__ConfigFacade_Remote_DynamicStub.java)
sormas-docker-sormas-1    |     at de.symeda.sormas.api._ConfigFacade_Wrapper.getAuthenticationProvider(de/symeda/sormas/api/_ConfigFacade_Wrapper.java)
sormas-docker-sormas-1    |     at de.symeda.sormas.rest.RestConfig$FilterStartupListener.contextInitialized(RestConfig.java:101)
sormas-docker-sormas-1    |     at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:5178)
sormas-docker-sormas-1    |     at com.sun.enterprise.web.WebModule.contextListenerStart(WebModule.java:681)
sormas-docker-sormas-1    |     at org.apache.catalina.core.StandardContext.start(StandardContext.java:5756)
sormas-docker-sormas-1    |     ... 37 more
sormas-docker-sormas-1    | Caused by: javax.ejb.EJBException: javax.ejb.CreateException: Could not create stateless EJB
sormas-docker-sormas-1    |     at com.sun.ejb.containers.StatelessSessionContainer$SessionContextFactory.create(StatelessSessionContainer.java:653)
sormas-docker-sormas-1    |     at com.sun.ejb.containers.util.pool.NonBlockingPool.getObject(NonBlockingPool.java:219)
sormas-docker-sormas-1    |     at com.sun.ejb.containers.StatelessSessionContainer._getContext(StatelessSessionContainer.java:395)
sormas-docker-sormas-1    |     ... 62 more
sormas-docker-sormas-1    | Caused by: javax.ejb.CreateException: Could not create stateless EJB
sormas-docker-sormas-1    |     at com.sun.ejb.containers.StatelessSessionContainer.createStatelessEJB(StatelessSessionContainer.java:473)
sormas-docker-sormas-1    |     at com.sun.ejb.containers.StatelessSessionContainer.access$000(StatelessSessionContainer.java:100)
sormas-docker-sormas-1    |     at com.sun.ejb.containers.StatelessSessionContainer$SessionContextFactory.create(StatelessSessionContainer.java:651)
sormas-docker-sormas-1    |     ... 64 more
sormas-docker-sormas-1    | Caused by: java.lang.IllegalStateException: Exception attempting to inject Env-Prop: de.symeda.sormas.backend.common.ConfigFacadeEjb/props@Field-Injectable Resource. Class name = de.symeda.sormas.backend.common.ConfigFacadeEjb Field name=props@java.lang.String@@@ into class de.symeda.sormas.backend.common.ConfigFacadeEjb: Can not set java.util.Properties field de.symeda.sormas.backend.common.ConfigFacadeEjb.props to de.symeda.sormas.backend.common.ConfigFacadeEjb
sormas-docker-sormas-1    |     at org.glassfish.weld.services.InjectionServicesImpl.aroundInject(InjectionServicesImpl.java:194)
sormas-docker-sormas-1    |     at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:46)
sormas-docker-sormas-1    |     at org.jboss.weld.injection.producer.DefaultInjector.inject(DefaultInjector.java:73)
sormas-docker-sormas-1    |     at org.jboss.weld.module.ejb.DynamicInjectionPointInjector.inject(DynamicInjectionPointInjector.java:61)
sormas-docker-sormas-1    |     at org.jboss.weld.module.ejb.SessionBeanInjectionTarget.inject(SessionBeanInjectionTarget.java:138)
sormas-docker-sormas-1    |     at org.glassfish.weld.services.JCDIServiceImpl$JCDIInjectionContextImpl.inject(JCDIServiceImpl.java:581)
sormas-docker-sormas-1    |     at org.glassfish.weld.services.JCDIServiceImpl.injectEJBInstance(JCDIServiceImpl.java:328)
sormas-docker-sormas-1    |     at com.sun.ejb.containers.BaseContainer.injectEjbInstance(BaseContainer.java:1818)
sormas-docker-sormas-1    |     at com.sun.ejb.containers.StatelessSessionContainer.createStatelessEJB(StatelessSessionContainer.java:437)
sormas-docker-sormas-1    |     ... 66 more
sormas-docker-sormas-1    | Caused by: com.sun.enterprise.container.common.spi.util.InjectionException: Exception attempting to inject Env-Prop: de.symeda.sormas.backend.common.ConfigFacadeEjb/props@Field-Injectable Resource. Class name = de.symeda.sormas.backend.common.ConfigFacadeEjb Field name=props@java.lang.String@@@ into class de.symeda.sormas.backend.common.ConfigFacadeEjb: Can not set java.util.Properties field de.symeda.sormas.backend.common.ConfigFacadeEjb.props to de.symeda.sormas.backend.common.ConfigFacadeEjb
sormas-docker-sormas-1    |     at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl._inject(InjectionManagerImpl.java:638)
sormas-docker-sormas-1    |     at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl.inject(InjectionManagerImpl.java:439)
sormas-docker-sormas-1    |     at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl.injectInstance(InjectionManagerImpl.java:153)
sormas-docker-sormas-1    |     at org.glassfish.weld.services.InjectionServicesImpl.aroundInject(InjectionServicesImpl.java:184)
sormas-docker-sormas-1    |     ... 74 more
sormas-docker-sormas-1    | Caused by: java.lang.IllegalArgumentException: Can not set java.util.Properties field de.symeda.sormas.backend.common.ConfigFacadeEjb.props to de.symeda.sormas.backend.common.ConfigFacadeEjb
sormas-docker-sormas-1    |     at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
sormas-docker-sormas-1    |     at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
sormas-docker-sormas-1    |     at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
sormas-docker-sormas-1    |     at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:75)
sormas-docker-sormas-1    |     at java.base/java.lang.reflect.Field.set(Field.java:780)
sormas-docker-sormas-1    |     at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl._inject(InjectionManagerImpl.java:594)
sormas-docker-sormas-1    |     ... 77 more
```
</details>

The problem occurs no matter if we use packaged artifacts or deploying the applications (exploded) with Eclipse IDE or IntelliJ.

## Steps to reproduce ## 

Reproduce the problem with [SORMAS-Docker (quick start)](https://github.com/hzi-braunschweig/SORMAS-Docker#quick-start):

```bash

# Preparation: Configure in your hosts file:
127.0.0.1	sormas-docker-test.com

# Checkout repo
git clone https://github.com/hzi-braunschweig/SORMAS-Docker.git
cd SORMAS-Docker
### We want to test 1.67.0+ with payara-5.2021.10
git checkout development

# 1. Start SORMAS (first sync of images will take some minutes)
docker-compose up

# 2. Watch log in a separate console 
docker logs -f sormas-docker-sormas-1

# 3. Go into container with running SORMAS-Project
docker exec -ti sormas-docker-sormas-1 bash
cd /opt/domains/sormas/autodeploy

# 4. Redeploy of a sormas WAR works (try several times if you want)
rm sormas-rest.war
cp ../deployments/sormas-rest.war .

# 5. Redeploy sormas-ear.ear works in itself
rm sormas-ear.ear
cp ../deployments/sormas-ear.ear .

# 6. Produce exception: Repeating step 4 results in exception and autodeploy failing
rm sormas-rest.war
cp ../deployments/sormas-rest.war .

# Note: It seems that at some point health checks kick in and restart sormas-docker-sormas-1 indefinitely
```
### Workaround for docker-compose parsing problem ###
If you run into exceptions like this:
```bash
docker-compose up
error while interpolating services.base-keycloak.mem_limit: failed to cast to expected type: strconv.ParseInt: parsing "1024M": invalid syntax
```

then append these values in the `.env`:
```
APPSERVER_JVM_MAX=4096000000
APPSERVER_MEM=4300000000
APPSERVER_MEM_RESERVED=1500000000
WEBSERVER_MEM=1000000000
WEBSERVER_MEM_RESERVED=200000000

KEYCLOAK_MEM=1024000000
KEYCLOAK_MEM_RESERVED=512000000
DB_MEM=2000000000
DB_MEM_RESERVED=1000000000

KEYCLOAK_DB_MEM=2000000000
KEYCLOAK_DB_MEM_RESERVED=1000000000

DB_DUMP_MEM=500000000
DB_DUMP_MEM_RESERVED=100000000
```

## Environment ##

- **Distribution**:   Server Full Profile (versions 5.2020.2, 5.2021.6, 5.2021.10)
- **JDK Version**:  11
- **Operating System**:  Windows, Linux

**Comment by fturizo** [comment]
@StefanKock, the reproducer that you have submitted is too complex and seems to operate based on a custom Payara Server Docker image that is not based on [our official Docker images](https://docs.payara.fish/community/docs/documentation/ecosystem/docker-images/server-image-overview.html). As per our support policy, we only support scenarios that make use of our official images, so if you can rework your reproducer into a far simpler project that uses the official images and clearly showcases the problem, please do so in order to understand the issue in detail.

Other than that,  I'll also point out that the **auto-deploymen**t feature is not a recommended feature to use in production scenarios, hence why the official server Docker image relies on an internal script to deploy applications when the image is launched.

**Comment by StefanKock** [comment]
Thanks for your reply, I will see what I can do to simplify the setup to reproduce the problem. 
Concerning the **auto-deployment** feature: We don't rely on being able to redeploy in production (it's currently used for initial deployment, but not mandatory), but for faster development with locally installed payara. The given reproducer only used SORMAS-Docker for faster reproduction.

**Comment by fturizo** [comment]
@StefanKock, as soon as you share a self-contained reproducer we should be good to review it in detail. Please, do remember to use the official Docker images to build your reproducer as well.

**Comment by StefanKock** [comment]
Since we point out a problem with **re-autodeployment** the question is if we can use an official docker image at all. I understood that we need to prove the point with an unzipped Payara. The problem is reproducable with that already (just with regular setup [as described here](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/docs/SERVER_SETUP.md)), but I wanted to reduce the hassle to have to set up databases.

**Comment by fturizo** [comment]
@StefanKock, have you been able to work on the self-contained reproducer that we requested? If so, please share as soon as possible to investigate it in detail.

**Comment by StefanKock** [comment]
I'll be capable to do so, but got other time constraints to follow up on this quickly. I hope I can deliver it within the next weeks.

**Comment by fturizo** [comment]
@StefanKock, we'll proceed to close this issue as there's no valid reproducer that we can use to investigate the issue you are encountering. Feel free to request the re-opening of this issue when you are able to share a valid, self-contained reproducer.
