### ISSUE TITLE
Bug Report:  Asadmin deploy fails if http-listener-1 is Security [X] Enabled

### ISSUE THREAD

**Issue by mkarg** [payara/Payara#5602]
# Description #
----------

Just noticed that when http-listener-1 is Security [X] Enabled, asadmin deploy fails with an exception in the server log:

```
Caused by: java.lang.NullPointerException
	at com.sun.enterprise.deployment.WebServiceEndpoint.composeEndpointAddress(WebServiceEndpoint.java:679)
	at com.sun.enterprise.deployment.WebServiceEndpoint.composeEndpointAddress(WebServiceEndpoint.java:675)
	at com.sun.enterprise.deployment.WebServiceEndpoint.composeFinalWsdlUrl(WebServiceEndpoint.java:731)
	at org.glassfish.webservices.WebServicesDeployer.doWebServicesDeployment(WebServicesDeployer.java:560)
	at org.glassfish.webservices.WebServicesDeployer.prepare(WebServicesDeployer.java:166)
	... 84 more
```

I can perfectly asadmin deploy when temporarily setting disabling Security [ ] Enabled and enable it afterwards! It is 100% repeatable using Payara Community 5.2021.8. HTTPS works perfectly well then with the deployed application.

Side note, I am using a PKCS #12 certificate file directly as the keystore, and have not imported the own public key in the separate Java keystore.

## Expected Outcome ##

Deployment succeeds without any error message / exception thrown even if only HTTPS is enabled at all listeners at deploy time.

## Current Outcome ##

Deployment succeeds if at least one listener is non-HTTPS at deploy time.

## Steps to reproduce ## 

Set both listeners to HTTPS, then deploy web application *not enforcing (but allowing)* transport security in web.xml.

## Environment ##

- **Distribution**: Server Full Profile
- **JDK Version**: 11 (Zulu)
- **Operating System**: Windows

**Comment by mkarg** [comment]
Please find more info here: https://forum.payara.fish/t/asadmin-deploy-fails-if-http-listener-1-is-security-x-enabled/209

Ondro's idea to fix it by *enforcing* transport security in web.xml is invalid, as according to his referenced source https://docs.oracle.com/cd/E13222_01/wls/docs81/webapp/web_xml.html, the application is free to *not enforce* (but allow) HTTPS.

**Comment by shub8968** [comment]
Hi @mkarg,

Would you be able to provide the sample reproducer app which you have used?

**Comment by mkarg** [comment]
Possibly related to https://github.com/payara/Payara/issues/5670.

**Comment by mkarg** [comment]
This issue can be reproduced using https://github.com/mkarg/payara-bugs/tree/master/PAYARA-5602.

**Comment by shub8968** [comment]
Hi @mkarg,

I am able to reproduce this issue. I have raised an internal issue with JIRA FISH-6207. Thanks. It may take a while to fix the issue. You are free to submit a PR to fix this issue if you feel confident to do so.

**Comment by mkarg** [comment]
> You are free to submit a PR to fix this issue if you feel confident to do so.

As much as I loved to, I neither feel confident nor have the time currently, so I would really appreciate if you could fix this. Thanks.
