### ISSUE TITLE
Bug Report:  payara-micro:start fails to disable Hazelcast with boot commands

### ISSUE THREAD

**Issue by johnmanko** [payara/Payara#5744]
# Description #
----------

Cannot start Payara Micro using the `payara-micro-maven-plugin:1.4..0` plugin, neither through the specific `payara-micro:start` goal, nor using Netbeans' default action when "running" the project.

Maven command:
```
JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64 M2_HOME=/usr/share/maven /usr/share/maven/bin/mvn -Dnetbeans.deploy=false -Dversion.payara=5.2022.2 -Dexec.vmArgs= -Dexec.appArgs= -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true resources:resources compiler:compile war:exploded payara-micro:start -X
```

Plugin configuration:
```xml
            <plugin>
                <groupId>fish.payara.maven.plugins</groupId>
                <artifactId>payara-micro-maven-plugin</artifactId>
                <version>1.4.0</version>
                <configuration>
                    <useUberJar>false</useUberJar>
                    <contextRoot>/app</contextRoot>
                    <payaraVersion>5.2022.2</payaraVersion>
                    <deployWar>true</deployWar>
                    <artifactItem>
                        <groupId>fish.payara.extras</groupId>
                        <artifactId>payara-micro</artifactId>
                        <version>5.2022.2</version>
                    </artifactItem>
                    <javaCommandLineOptions>
                        <option>
                            <value>-Xdebug</value>
                        </option>
                    </javaCommandLineOptions>
                    <commandLineOptions>
                        <option>
                            <key>--autoBindHttp</key>
                        </option>
                        <option>
                            <key>--prebootcommandfile</key>
                            <value>${project.basedir}/src/main/resources/pre-boot-commands.txt</value>
                        </option>
                    </commandLineOptions>
                </configuration>
            </plugin>
```

`pre-boot-commands.txt`:

```
set-network-listener-configuration --listenerport=8085 --listenerPortRange=8085,8090 http-listener
set-hazelcast-configuration --disabled=true
```
and I even tried with 

```
set-hazelcast-configuration --disabled=true
```

```
set-hazelcast-configuration --enabled=false
```

## Expected Outcome ##

Application should successful deploy/run on Payara Micro as a non-bundled app.

## Current Outcome ##

```

[INFO] NETBEANS-ExecEvent:{"mojo":{"impl":"fish.payara.maven.plugins.micro.StartMojo","goal":"start","id":"fish.payara.maven.plugins:payara-micro-maven-plugin:1.4.0","source":"CLI","execId":"default-cli"},"type":"MojoStarted"}
[INFO] 
[INFO] --- payara-micro-maven-plugin:1.4.0:start (default-cli) @ payara-micro-plugin-example ---
[INFO] Starting payara-micro from path: /home/john/.m2/repository/fish/payara/extras/payara-micro/5.2022.2/payara-micro-5.2022.2.jar
[2022-05-09T16:04:13.374-0400] [] [WARNING] [] [PayaraMicro] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1652126653374] [levelValue: 900] You are running the product on an unsupported JDK version and might see unexpected results or exceptions.

[2022-05-09T16:04:13.394-0400] [] [WARNING] [] [PayaraMicro] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1652126653394] [levelValue: 900] Payara Micro Runtime directory is located in a temporary file location which can be cleaned by system processes.

[2022-05-09T16:04:13.395-0400] [] [INFO] [] [PayaraMicro] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1652126653395] [levelValue: 800] Payara Micro Runtime directory is located at /tmp/payaramicro-rt3212496119343229057tmp

[2022-05-09T16:04:13.401-0400] [] [INFO] [] [fish.payara.micro.boot.runtime.PayaraMicroRuntimeBuilder] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1652126653401] [levelValue: 800] Built Payara Micro Runtime

[2022-05-09T16:04:13.962-0400] [] [INFO] [] [fish.payara.boot.runtime.BootCommand] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1652126653962] [levelValue: 800] Boot Command set-network-listener-configuration returned with result SUCCESS : PlainTextActionReporterSUCCESSNo monitoring data to report.


[2022-05-09T16:04:13.967-0400] [] [SEVERE] [] [] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1652126653967] [levelValue: 1000] [[
  NCLS-CORE-00002
MultiException stack 1 of 3
java.lang.IllegalStateException: Service fish.payara.nucleus.hazelcast.HazelcastCore was started at level -2 but it has a run level of 10.  The full descriptor is SystemDescriptor(
	implementation=fish.payara.nucleus.hazelcast.HazelcastCore
	name=hazelcast-core
	contracts={fish.payara.nucleus.hazelcast.HazelcastCore,org.jvnet.hk2.config.ConfigListener}
	scope=org.glassfish.hk2.runlevel.RunLevel
	qualifiers={}
	descriptorType=CLASS
	descriptorVisibility=NORMAL
	metadata=runLevelValue={10}
	rank=0
	loader=org.glassfish.hk2.bootstrap.impl.Hk2LoaderPopulatorPostProcessor$1@1d71006f
	proxiable=null
	proxyForSameScope=null
	analysisName=null
	id=463
	locatorId=0
	identityHashCode=585878713
	reified=true)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.validate(AsyncRunLevelContext.java:422)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:275)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:667)
	at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:54)
	at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:188)
	at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:211)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:334)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
	at org.jvnet.hk2.internal.PerLookupContext.findOrCreate(PerLookupContext.java:46)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:759)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:722)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:709)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.getModel(CommandRunnerImpl.java:196)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.getModel(CommandRunnerImpl.java:180)
	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.getParameters(CommandExecutorImpl.java:104)
	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:177)
	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:96)
	at fish.payara.boot.runtime.BootCommand.execute(BootCommand.java:69)
	at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:141)
	at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:135)
	at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1048)
	at fish.payara.micro.impl.PayaraMicroImpl.create(PayaraMicroImpl.java:231)
	at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:218)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:50)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:114)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:73)
	at fish.payara.micro.boot.PayaraMicroLauncher.create(PayaraMicroLauncher.java:88)
	at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:72)
	at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:456)
MultiException stack 2 of 3
java.lang.IllegalArgumentException: While attempting to resolve the dependencies of fish.payara.nucleus.hazelcast.admin.SetHazelcastConfiguration errors were found
	at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:224)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:334)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
	at org.jvnet.hk2.internal.PerLookupContext.findOrCreate(PerLookupContext.java:46)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:759)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:722)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:709)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.getModel(CommandRunnerImpl.java:196)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.getModel(CommandRunnerImpl.java:180)
	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.getParameters(CommandExecutorImpl.java:104)
	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:177)
	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:96)
	at fish.payara.boot.runtime.BootCommand.execute(BootCommand.java:69)
	at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:141)
	at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:135)
	at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1048)
	at fish.payara.micro.impl.PayaraMicroImpl.create(PayaraMicroImpl.java:231)
	at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:218)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:50)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:114)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:73)
	at fish.payara.micro.boot.PayaraMicroLauncher.create(PayaraMicroLauncher.java:88)
	at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:72)
	at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:456)
MultiException stack 3 of 3
java.lang.IllegalStateException: Unable to perform operation: resolve on fish.payara.nucleus.hazelcast.admin.SetHazelcastConfiguration
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:363)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
	at org.jvnet.hk2.internal.PerLookupContext.findOrCreate(PerLookupContext.java:46)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:759)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:722)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:709)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.getModel(CommandRunnerImpl.java:196)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.getModel(CommandRunnerImpl.java:180)
	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.getParameters(CommandExecutorImpl.java:104)
	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:177)
	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:96)
	at fish.payara.boot.runtime.BootCommand.execute(BootCommand.java:69)
	at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:141)
	at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:135)
	at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1048)
	at fish.payara.micro.impl.PayaraMicroImpl.create(PayaraMicroImpl.java:231)
	at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:218)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:50)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:114)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:73)
	at fish.payara.micro.boot.PayaraMicroLauncher.create(PayaraMicroLauncher.java:88)
	at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:72)
	at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:456)
]]

[2022-05-09T16:04:13.968-0400] [] [WARNING] [] [fish.payara.boot.runtime.BootCommand] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1652126653968] [levelValue: 900] [[
  Boot Command set-hazelcast-configuration failed Exception while executing command. 
org.glassfish.api.admin.CommandException: Command lookup failed for command set-hazelcast-configuration
	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.getParameters(CommandExecutorImpl.java:106)
	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:177)
	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:96)
	at fish.payara.boot.runtime.BootCommand.execute(BootCommand.java:69)
	at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:141)
	at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:135)
	at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1048)
	at fish.payara.micro.impl.PayaraMicroImpl.create(PayaraMicroImpl.java:231)
	at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:218)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:50)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:114)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:73)
	at fish.payara.micro.boot.PayaraMicroLauncher.create(PayaraMicroLauncher.java:88)
	at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:72)
	at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:456)
]]

[2022-05-09T16:04:13.995-0400] [] [INFO] [] [fish.payara.boot.runtime.BootCommand] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1652126653995] [levelValue: 800] [[
  Boot Command set returned with result SUCCESS : PlainTextActionReporterSUCCESSDescription: set AdminCommandnull
    configs.config.server-config.network-config.network-listeners.network-listener.http-listener.port-range=8080,8085
]]

[2022-05-09T16:04:14.000-0400] [] [INFO] [] [fish.payara.boot.runtime.BootCommand] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1652126654000] [levelValue: 800] [[
  Boot Command set returned with result SUCCESS : PlainTextActionReporterSUCCESSDescription: set AdminCommandnull
    configs.config.server-config.network-config.network-listeners.network-listener.http-listener.enabled=true
]]

[2022-05-09T16:04:14.011-0400] [] [INFO] [] [fish.payara.boot.runtime.BootCommand] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1652126654011] [levelValue: 800] [[
  Boot Command set returned with result SUCCESS : PlainTextActionReporterSUCCESSDescription: set AdminCommandnull
    configs.config.server-config.hazelcast-config-specific-configuration.lite=false
]]

[2022-05-09T16:04:14.021-0400] [] [INFO] [] [fish.payara.boot.runtime.BootCommand] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1652126654021] [levelValue: 800] [[
  Boot Command set returned with result SUCCESS : PlainTextActionReporterSUCCESSDescription: set AdminCommandnull
    hazelcast-runtime-configuration.host-aware-partitioning=true
]]

[2022-05-09T16:04:14.023-0400] [] [INFO] [] [fish.payara.boot.runtime.BootCommand] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1652126654023] [levelValue: 800] [[
  Boot Command set returned with result SUCCESS : PlainTextActionReporterSUCCESSDescription: set AdminCommandnull
    hazelcast-runtime-configuration.discovery-mode=multicast
]]

```

## Sample Project (Optional) ## 

https://github.com/johnmanko/payara-micro-plugin-example

## Environment ##

* Ubuntu `22.04 LTS`
* Apache Netbeans `13.0`
* Payara Micro `5.2022.2`
* Java `1.8.0_312`
* Maven `3.6.3`
* payara-micro-maven-plugin `1.4.0`

**Java** version:
```
/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -version 
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
```

**Maven** version:
```
/usr/share/maven/bin/mvn -version
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 18-ea, vendor: Private Build, runtime: /usr/lib/jvm/java-18-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-27-generic", arch: "amd64", family: "unix"
```

**Comment by AlanRoth** [comment]
Hi @johnmanko,

This is functioning as expected. Hazelcast cannot be configured using the pre-boot file, hence the exception you are experiencing.

You can configure Hazelcast options in the post boot file instead.

If you wish to disable Hazelcast entirely for that instance, you can use the `--nocluster` command line option - be aware that some services that depend on it may not work.

I will be closing this issue as it appears to be a misconfiguration, if you think I misunderstood your issue and you believe it is a genuine bug, feel free to re-open it and we can discuss further.

Thank you,
Alan

**Comment by johnmanko** [comment]
@AlanRoth What services rely on Hazelcast?  Where is that documented?  In the past it was perfectly acceptable to disable it, since a single instance more likely than not doesn't require it in many use cases.

**Comment by AlanRoth** [comment]
Hi @johnmanko,

Distributed CDI Event Bus, Persistent Timers, Integrated JCache Resources, are some examples, and of course, clustering.

Payara Micro will function, it is acceptable to disable it if you so wish - hence we make it a option, `--nocluster`, however you may not be able to rely on the services that rely on Hazelcast, as Hazelcast will be disabled.

Thank you,
Alan
