### ISSUE TITLE
Enhancement: Bouncy castle fips integration for https connection / FISH-6336

### ISSUE THREAD

**Issue by Tenariel** [payara/Payara#5761]
Hello everyone,

I want to configure payara (payara 5.2022.1) to use bouncy castle JCE and JSSE in fips mode but i found a little issue with the integration. After i have deployed my server application, any https connection fails with the following exception:
`
AVERTISSEMENT:   GRIZZLY0050: SSL support could not be configured!
java.io.IOException: SSLContext has not been initialized.
	at org.glassfish.grizzly.config.ssl.JSSE14SocketFactory.init(JSSE14SocketFactory.java:163)
	at org.glassfish.grizzly.config.SSLConfigurator.initializeSSLContext(SSLConfigurator.java:320)
	at org.glassfish.grizzly.config.SSLConfigurator.configureSSL(SSLConfigurator.java:180)
	at org.glassfish.grizzly.config.SSLConfigurator$InternalSSLContextConfigurator.createSSLContext(SSLConfigurator.java:466)
	at org.glassfish.grizzly.ssl.SSLEngineConfigurator.createSSLEngine(SSLEngineConfigurator.java:185)
	at org.glassfish.grizzly.ssl.SSLEngineConfigurator.createSSLEngine(SSLEngineConfigurator.java:162)
	at org.glassfish.grizzly.ssl.SSLBaseFilter$SSLTransportFilterWrapper.handleRead(SSLBaseFilter.java:1122)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.base/java.lang.Thread.run(Thread.java:829)
`

After research i found an integration issue. Bouncy castle wants the sslcontext to be initialized before any use while payara uses sslcontext before it is initialized. 

To fix this issue i rebuilt payara with a little tweak. I changed the following code inside the init method of org.glassfish.grizzly.config.ssl.JSSE14SocketFactory class :
		
Origin:	

		// START SJSAS 6439313
        context = SSLContext.getInstance(protocol);
		// END SJSAS 6439313 
		// Configure SSL session timeout and cache size
		configureSSLSessionContext(context.getServerSessionContext());
		String trustAlgorithm = (String) attributes.get("truststoreAlgorithm");
		if (trustAlgorithm == null) {
			trustAlgorithm = TrustManagerFactory.getDefaultAlgorithm();
		}
		context.init(getKeyManagers(algorithm,
			(String) attributes.get("keyAlias")),
			getTrustManagers(trustAlgorithm),
			new SecureRandom()); 
			
Tweak : 

		// START SJSAS 6439313
		context = SSLContext.getInstance(protocol);
		// END SJSAS 6439313 
		// Configure SSL session timeout and cache size
		String trustAlgorithm = (String) attributes.get("truststoreAlgorithm");
		if (trustAlgorithm == null) {
			trustAlgorithm = TrustManagerFactory.getDefaultAlgorithm();
		}
		context.init(getKeyManagers(algorithm,
			(String) attributes.get("keyAlias")),
			getTrustManagers(trustAlgorithm),
			new SecureRandom());
		configureSSLSessionContext(context.getServerSessionContext());

With this modification, the bouncycastle library work correctly and every https handshake work as expected.		

Can we have this change integrated in the main payara branch ? this would allow to use payara with bouncy castle fips provider out of the box.

Regards,

Tenariel

**Comment by smillidge** [comment]
Hi @Tenariel can you make a PR? Looks like good work.

**Comment by Tenariel** [comment]
Hi,

i am happy to open a PR request. Since this is my first time doing it, i hope i didn't make a mistake. If i did something worng you can delete my action.

**Comment by AlanRoth** [comment]
Hi @Tenariel,

Thank you for the PR, it looks all good. I left a comment on the PR as we require a CLA. 

I have created issue `FISH-6336` to keep track of this issue internally.

Thank you,
Alan
