### ISSUE TITLE
Bug Report:  HashiCorp Secrets Config Source not working in Payara Micro

### ISSUE THREAD

**Issue by kazablock** [payara/Payara#5924]
# Description #
----------

When using Hashicorp vault as config source always throws NPE in startup while reading password alias in Payara Micro. Same process works in Payara Server Full.

## Expected Outcome ##

Shouldn't throw NPE and should be able to read the Injected Config correctly

## Current Outcome ##

 Exception while running a command
java.lang.NullPointerException
        at org.glassfish.config.support.TranslatedConfigView.getRealPasswordFromAlias(TranslatedConfigView.java:311)
        at fish.payara.microprofile.config.extensions.hashicorp.HashiCorpSecretsConfigSource.bootstrap(HashiCorpSecretsConfigSource.java:102)
        at fish.payara.nucleus.microprofile.config.source.extension.ExtensionConfigSourceHandler.bootstrap(ExtensionConfigSourceHandler.java:127)
        at fish.payara.nucleus.microprofile.config.source.extension.ExtensionConfigSourceHandler.reconfigure(ExtensionConfigSourceHandler.java:100)
        at fish.payara.nucleus.microprofile.config.source.extension.ExtensionConfigSourceService.reconfigure(ExtensionConfigSourceService.java:204)
        at fish.payara.nucleus.microprofile.config.source.extension.BaseSetConfigSourceConfigurationCommand.configureDynamically(BaseSetConfigSourceConfigurationCommand.java:182)
        at fish.payara.nucleus.microprofile.config.source.extension.BaseSetConfigSourceConfigurationCommand.execute(BaseSetConfigSourceConfigurationCommand.java:150)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:556)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:552)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:551)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:582)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:574)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:573)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1497)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:120)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1879)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1755)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:183)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:96)
        at fish.payara.boot.runtime.BootCommand.execute(BootCommand.java:69)
        at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:136)
        at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:130)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1043)
        at fish.payara.micro.impl.PayaraMicroImpl.create(PayaraMicroImpl.java:230)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:217)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:50)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:114)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:73)
        at fish.payara.micro.boot.PayaraMicroLauncher.create(PayaraMicroLauncher.java:88)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:72)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:456)
]]

## Steps to reproduce ## 

[hashicorpreproducer.zip](https://github.com/payara/Payara/files/9493846/hashicorpreproducer.zip)

### Install Vault

    docker run --cap-add=IPC_LOCK -p 8200:8200 -e 'VAULT_DEV_ROOT_TOKEN_ID=myroot' -d --name=dev-vault vault

### Run in Local

Download payara micro 5.2021.7 from
https://search.maven.org/artifact/fish.payara.extras/payara-micro/5.2021.7/jar

    mvn clean install
    java -jar payara-micro-5.2021.7.jar --prebootcommandfile ./exec_pre-boot-commands.txt --deploy target/hashicorpreproducer.war 

## Environment ##

- **Payara Micro 5.2021.7/ 5.2022.3**: 
- **8  Oracle**: 
- **Anything**:

**Comment by JamesHillyard** [comment]
Hi @kazablock,

Thank you for raising an issue with us and providing a comprehensive reproducer, it's much appreciated.

As per the community support policy, we will only investigate and escalate bugs found on the latest version of Payara. Could you please test if this issue is still present on Payara Micro 5.2022.3? After you have confirmed this issue is present on the latest version, I will gladly attempt to reproduce this bug.

Best Regards,
James

**Comment by kazablock** [comment]
Hi @JamesHillyard 

Thank you for your reply. Sure let me try with latest version

**Comment by kazablock** [comment]
Hi @JamesHillyard 
Downloaded Latest verion From https://search.maven.org/artifact/fish.payara.extras/payara-micro/5.2022.3/jar 
and still able to reproduce the error

java -jar payara-micro-5.2022.3.jar  --prebootcommandfile ./exec_pre-boot-commands.txt --deploy target/hashicorpreproducer.war --port 8083

**Comment by JamesHillyard** [comment]
Hi @kazablock,

Thank you for your quick reply and confirming this issue is still present, again it's much appreciated. I was able to reproduce this issue with the exact configuration you have used. Before escalating this to our development team though, I would like to make a quick clarification:

Is there a reason you chose to use `prebootcommandfile` over `postbootcommandfile`? Due to the execution order, preboot command files have a very limited number of commands they can execute, as a significant number of services haven't started yet. Looking at your command file, it would seem to be more suitable to use it as a `postbootcommandfile`, which doesn't cause the issue you are facing.

I wasn't able to get this fully working when making the suggested change, however I believe the issue to be a lack of vault configuration, not an issue with Payara itself. Could you please try executing the following command instead, does this resolve your issue?

`java -jar .\payara-micro-5.2022.3.jar --postbootcommandfile .\exec_pre-boot-commands.txt --deploy .\target\hashicorpreproducer.war`

Thanks,
James

**Comment by JamesHillyard** [comment]
Hi @kazablock,

I'm glad to hear that solved your problem! Generally I would only use the preboot files for the `asadmin get` and `asadmin set` commands on existing resources like network listeners, standard domain configuration and such, if you need these changes to take effect before Payara is fully booted and ready. 

For any configurations which need setting before the application is loaded but can wait until Payara is ready (Eg. Configuring password aliases or a JDBC connection pool and creating any new resources), then a postboot command is the way to go.

For almost all scenarios, a postboot script would be most suitable.

Thanks,
James

**Comment by kazablock** [comment]
Thank you @JamesHillyard 🥇
