### ISSUE TITLE
payara-micro-6.2022.1.Alpha4 does not contains correct runtime/schemas.jar / FISH-6576

### ISSUE THREAD

**Issue by jluisromtz** [payara/Payara#5975]
### Brief Summary

When I try run an example, log shows:
org.xml.sax.SAXParseExceptionpublicId: jar:file:/C:/Users/my_user/AppData/Local/Temp/payaramicro-rt3350712236904098486tmp/runtime/schemas.jar!/schemas/web-app_6_0.xsd; lineNumber: 264; columnNumber: 50; Deployment descriptor file WEB-INF/web.xml in archive [testing].  src-resolve: Cannot resolve the name 'jakartaee:web-commonType' to a(n) 'group' component.
org.xml.sax.SAXParseExceptionpublicId: jar:file:/C:/Users/jromero/AppData/Local/Temp/payaramicro-rt3350712236904098486tmp/runtime/schemas.jar!/schemas/web-app_6_0.xsd; lineNumber: 264; columnNumber: 50; Deployment descriptor file WEB-INF/web.xml in archive [testing].  src-resolve: Cannot resolve the name 'jakartaee:web-commonType' to a(n) 'group' component.

I unzipped the payara-micro-6.2022.1.Alpah4.jar/MICRO-INF/runtime/schemas.jar. The schemas package does not contains web-common_6_0.xsd that Glassfish 7.0.0 M8 contains.

### Expected Outcome

Payara deploying my web-app.

### Current Outcome

[2022-10-09T16:57:44.983-0500] [] [←[1;91mSEVERE←[0m] [] [←[1;94mjavax.enterprise.system.core←[0m] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1665352664983] [levelValue: 1000] [[
  Exception while deploying the app [testing] : org.xml.sax.SAXParseExceptionpublicId: jar:file:/C:/Users/my_user/AppData/Local/Temp/payaramicro-rt3350712236904098486tmp/runtime/schemas.jar!/schemas/web-app_6_0.xsd; lineNumber: 264; columnNumber: 50; Deployment descriptor file WEB-INF/web.xml in archive [testing].  src-resolve: Cannot resolve the name 'jakartaee:web-commonType' to a(n) 'group' component.
org.xml.sax.SAXParseExceptionpublicId: jar:file:/C:/Users/my_user/AppData/Local/Temp/payaramicro-rt3350712236904098486tmp/runtime/schemas.jar!/schemas/web-app_6_0.xsd; lineNumber: 264; columnNumber: 50; Deployment descriptor file WEB-INF/web.xml in archive [testing].  src-resolve: Cannot resolve the name 'jakartaee:web-commonType' to a(n) 'group' component.
        at com.sun.enterprise.deployment.io.DeploymentDescriptorFile.read(DeploymentDescriptorFile.java:322)
        at com.sun.enterprise.deployment.io.DeploymentDescriptorFile.read(DeploymentDescriptorFile.java:239)
        at com.sun.enterprise.deployment.archivist.Archivist.readStandardDeploymentDescriptor(Archivist.java:713)
        at com.sun.enterprise.deployment.archivist.Archivist.readDeploymentDescriptors(Archivist.java:390)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:271)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:280)
        at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:240)
        at com.sun.enterprise.deployment.archivist.ApplicationFactory.openArchive(ApplicationFactory.java:161)
        at org.glassfish.javaee.core.deployment.DolProvider.processDOL(DolProvider.java:221)
        at org.glassfish.javaee.core.deployment.DolProvider.load(DolProvider.java:246)
        at org.glassfish.javaee.core.deployment.DolProvider.load(DolProvider.java:97)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.loadDeployer(ApplicationLifecycle.java:1155)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.loadDeployers(ApplicationLifecycle.java:1123)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.setupContainerInfos(ApplicationLifecycle.java:938)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:447)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:611)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:556)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:552)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/javax.security.auth.Subject.doAs(Subject.java:376)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:551)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:582)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:574)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/javax.security.auth.Subject.doAs(Subject.java:376)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:573)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1497)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1879)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1755)
        at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:131)
        at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:104)
        at fish.payara.micro.impl.PayaraMicroImpl.deployAll(PayaraMicroImpl.java:1696)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1058)
        at fish.payara.micro.impl.PayaraMicroImpl.create(PayaraMicroImpl.java:231)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:218)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:50)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:114)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:73)
        at fish.payara.micro.boot.PayaraMicroLauncher.create(PayaraMicroLauncher.java:88)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:72)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:456)
Caused by: org.xml.sax.SAXParseException; systemId: jar:file:/C:/Users/my_user/AppData/Local/Temp/payaramicro-rt3350712236904098486tmp/runtime/schemas.jar!/schemas/web-app_6_0.xsd; lineNumber: 264; columnNumber: 50; src-resolve: Cannot resolve the name 'jakartaee:web-commonType' to a(n) 'group' component.
        at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
        at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:135)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:4254)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaError(XSDHandler.java:4237)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getGlobalDecl(XSDHandler.java:1791)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDGroupTraverser.traverseLocal(XSDGroupTraverser.java:80)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDAbstractParticleTraverser.traverseSeqChoice(XSDAbstractParticleTraverser.java:232)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDAbstractParticleTraverser.traverseChoice(XSDAbstractParticleTraverser.java:184)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.processComplexContent(XSDComplexTypeTraverser.java:1053)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseComplexTypeDecl(XSDComplexTypeTraverser.java:335)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseGlobal(XSDComplexTypeTraverser.java:191)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.traverseGlobalDecl(XSDHandler.java:1939)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getGlobalDecl(XSDHandler.java:1826)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDElementTraverser.traverseNamedElement(XSDElementTraverser.java:405)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDElementTraverser.traverseGlobal(XSDElementTraverser.java:242)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.traverseSchemas(XSDHandler.java:1483)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:663)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:618)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.findSchemaGrammar(XMLSchemaValidator.java:2711)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:2070)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:830)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3079)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:836)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
        at com.sun.enterprise.deployment.io.DeploymentDescriptorFile.read(DeploymentDescriptorFile.java:312)
        ... 44 more

### Reproducer

Create a new jakarta ee 10 project named my_project, compile and execute

java -jar payara-micro-6.2022.1.Alpha4.jar my_project.jar

### Operating System

Windows 10 Pro

### JDK Version

Java HotSpot(TM) 64-Bit Server VM (build 17.0.4.1+1-LTS-2, mixed mode, sharing)

### Payara Distribution

Payara Micro

**Comment by JamesHillyard** [comment]
Hi @jluisromtz,

Could you please provide the complete war you are trying to deploy, as the reproducer you provided seems incomplete. This will greatly help us confirm the fix will resolve your issue.

I am able to see this schema is missing, so with a confirmed reproducer I will be able to escalate this to our development team.

Best Regards,
James

**Comment by JamesHillyard** [comment]
Hi @jluisromtz,

Thank you very much for providing the sample application, I have been able to verify this issue locally and have escalated this issue to our development team with the internal ID `FISH-6601`. We always encourage you to contribute, so if you feel confident to do so you can raise a PR to fix this issue and our development team will gladly review it, if not we will pick this issue up in the future.

Best Regards,
James

**Comment by JamesHillyard** [comment]
Hi @jluisromtz,

This issue has actually been resolved a few days ago by `FISH-6576`, specifically PR https://github.com/payara/Payara/pull/5964. Your sample application has been tested against our current master branch and confirmed to work as expected. This fix will be available for you to use in Payara Community 6.2022.1 

Your patience in the meantime is much appreciated

Best Regards,
James
