### ISSUE TITLE
Payara Server 5.2022.3 deserialization ConcurrentHashMap error.

### ISSUE THREAD

**Issue by wuxinbin** [payara/Payara#6015]
### Brief Summary

I created two domains, offset the ports of domain2, and then started domain1 and domain2. I have two projects, one as the client and the other as the server, which are deployed to two domains for ejb calls. Then access the client and find the following error.

### Expected Outcome

[2022-11-04T13:26:06.351+0800] [Payara 5.2022.3] [警告] [] [javax.enterprise.web] [tid: _ThreadID=80 _ThreadName=http-thread-pool::http-listener-1(2)] [timeMillis: 1667539566351] [levelValue: 900] [[
  StandardWrapperValve[TestListServlet]: Servlet.service() for servlet TestListServlet threw exception
org.omg.CORBA.MARSHAL: ----------BEGIN server-side stack trace----------
org.omg.CORBA.MARSHAL: 警告: 00810010: Error from readValue on ValueHandler in CDRInputStream  vmcid: OMG  minor code: 10 completed: Maybe
	at com.sun.proxy.$Proxy224.valuehandlerReadError(Unknown Source)
	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.readRMIIIOPValueType(CDRInputStream_1_0.java:835)
	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.read_value(CDRInputStream_1_0.java:928)
	at com.sun.corba.ee.impl.encoding.CDRInputObject.read_value(CDRInputObject.java:518)
	at com.sun.corba.ee.impl.io.IIOPInputStream.inputObjectField(IIOPInputStream.java:2091)
	at com.sun.corba.ee.impl.io.IIOPInputStream.inputClassFields(IIOPInputStream.java:2333)
	at com.sun.corba.ee.impl.io.IIOPInputStream.inputObject(IIOPInputStream.java:1156)
	at com.sun.corba.ee.impl.io.IIOPInputStream.simpleReadObject(IIOPInputStream.java:350)
	at com.sun.corba.ee.impl.io.ValueHandlerImpl.readValueInternal(ValueHandlerImpl.java:311)
	at com.sun.corba.ee.impl.io.ValueHandlerImpl.readValue(ValueHandlerImpl.java:277)
	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.readRMIIIOPValueType(CDRInputStream_1_0.java:826)
	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.read_value(CDRInputStream_1_0.java:928)
	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.read_value(CDRInputStream_1_0.java:746)
	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.read_abstract_interface(CDRInputStream_1_0.java:739)
	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.read_abstract_interface(CDRInputStream_1_0.java:729)
	at com.sun.corba.ee.impl.encoding.CDRInputObject.read_abstract_interface(CDRInputObject.java:544)
	at com.sun.corba.ee.impl.io.IIOPInputStream.readObjectDelegate(IIOPInputStream.java:316)
	at com.sun.corba.ee.impl.io.IIOPInputStream.readObjectOverride(IIOPInputStream.java:468)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:492)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:459)
	at java.util.ArrayList.readObject(ArrayList.java:799)
	at com.sun.corba.ee.impl.io.IIOPInputStream.invokeObjectReader(IIOPInputStream.java:1764)
	at com.sun.corba.ee.impl.io.IIOPInputStream.inputObject(IIOPInputStream.java:1146)
	at com.sun.corba.ee.impl.io.IIOPInputStream.simpleReadObject(IIOPInputStream.java:350)
	at com.sun.corba.ee.impl.io.ValueHandlerImpl.readValueInternal(ValueHandlerImpl.java:311)
	at com.sun.corba.ee.impl.io.ValueHandlerImpl.readValue(ValueHandlerImpl.java:277)
	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.readRMIIIOPValueType(CDRInputStream_1_0.java:826)
	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.read_value(CDRInputStream_1_0.java:928)
	at com.sun.corba.ee.impl.encoding.CDRInputObject.read_value(CDRInputObject.java:518)
	at com.sun.corba.ee.impl.presentation.rmi.DynamicMethodMarshallerImpl$14.read(DynamicMethodMarshallerImpl.java:383)
	at com.sun.corba.ee.impl.presentation.rmi.DynamicMethodMarshallerImpl.readArguments(DynamicMethodMarshallerImpl.java:450)
	at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie._invoke(ReflectiveTie.java:171)
	at com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatchToServant(ServerRequestDispatcherImpl.java:528)
	at com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatch(ServerRequestDispatcherImpl.java:199)
	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequestRequest(MessageMediatorImpl.java:1565)
	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequest(MessageMediatorImpl.java:1441)
	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleInput(MessageMediatorImpl.java:946)
	at com.sun.corba.ee.impl.protocol.giopmsgheaders.RequestMessage_1_2.callback(RequestMessage_1_2.java:213)
	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequest(MessageMediatorImpl.java:710)
	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.dispatch(MessageMediatorImpl.java:509)
	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.doWork(MessageMediatorImpl.java:2238)
	at com.sun.corba.ee.impl.threadpool.ThreadPoolImpl$TaskRunner.run(ThreadPoolImpl.java:189)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.getConvertedChars(CDRInputStream_1_0.java:2090)
	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.internalReadString(CDRInputStream_1_0.java:472)
	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.readStringOrIndirection(CDRInputStream_1_0.java:458)
	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.read_repositoryId(CDRInputStream_1_0.java:1718)
	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.read_repositoryIds(CDRInputStream_1_0.java:1700)
	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.readRepositoryIds(CDRInputStream_1_0.java:811)
	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.readRepositoryIds(CDRInputStream_1_0.java:776)
	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.read_value(CDRInputStream_1_0.java:877)
	at com.sun.corba.ee.impl.encoding.CDRInputObject.read_value(CDRInputObject.java:518)
	at com.sun.corba.ee.impl.io.IIOPInputStream.inputObjectField(IIOPInputStream.java:2091)
	at com.sun.corba.ee.impl.io.IIOPInputStream.inputClassFields(IIOPInputStream.java:2333)
	at com.sun.corba.ee.impl.io.IIOPInputStream.defaultReadObjectDelegate(IIOPInputStream.java:525)
	at com.sun.corba.ee.impl.io.InputStreamHook.defaultReadObject(InputStreamHook.java:233)
	at java.util.concurrent.ConcurrentHashMap.readObject(ConcurrentHashMap.java:1438)
	at java.lang.invoke.LambdaForm$DMH/155307362.invokeVirtual_LL_V(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$BMH/1404177920.reinvoke(LambdaForm$BMH)
	at java.lang.invoke.LambdaForm$MH/69569169.invoke_MT(LambdaForm$MH)
	at com.sun.corba.ee.impl.io.IIOPInputStream.invokeObjectReader(IIOPInputStream.java:1764)
	at com.sun.corba.ee.impl.io.IIOPInputStream.inputObject(IIOPInputStream.java:1146)
	at com.sun.corba.ee.impl.io.IIOPInputStream.simpleReadObject(IIOPInputStream.java:350)
	at com.sun.corba.ee.impl.io.ValueHandlerImpl.readValueInternal(ValueHandlerImpl.java:311)
	at com.sun.corba.ee.impl.io.ValueHandlerImpl.readValue(ValueHandlerImpl.java:277)
	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.readRMIIIOPValueType(CDRInputStream_1_0.java:826)
	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.read_value(CDRInputStream_1_0.java:928)
	at com.sun.corba.ee.impl.encoding.CDRInputObject.read_value(CDRInputObject.java:518)
	at com.sun.corba.ee.impl.io.IIOPInputStream.inputObjectField(IIOPInputStream.java:2091)
	at com.sun.corba.ee.impl.io.IIOPInputStream.inputClassFields(IIOPInputStream.java:2333)
	at com.sun.corba.ee.impl.io.IIOPInputStream.inputObject(IIOPInputStream.java:1156)
	at com.sun.corba.ee.impl.io.IIOPInputStream.simpleReadObject(IIOPInputStream.java:350)
	at com.sun.corba.ee.impl.io.ValueHandlerImpl.readValueInternal(ValueHandlerImpl.java:311)
	at com.sun.corba.ee.impl.io.ValueHandlerImpl.readValue(ValueHandlerImpl.java:277)
	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.readRMIIIOPValueType(CDRInputStream_1_0.java:826)

----------END server-side stack trace----------  vmcid: OMG  minor code: 10 completed: Maybe
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.sun.corba.ee.impl.protocol.giopmsgheaders.MessageBase.getSystemException(MessageBase.java:813)
	at com.sun.corba.ee.impl.protocol.giopmsgheaders.ReplyMessage_1_2.getSystemException(ReplyMessage_1_2.java:131)
	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.getSystemExceptionReply(MessageMediatorImpl.java:610)
	at com.sun.corba.ee.impl.protocol.ClientRequestDispatcherImpl.processResponse(ClientRequestDispatcherImpl.java:506)
	at com.sun.corba.ee.impl.protocol.ClientRequestDispatcherImpl.marshalingComplete(ClientRequestDispatcherImpl.java:378)
	at com.sun.corba.ee.impl.protocol.ClientDelegateImpl.invoke(ClientDelegateImpl.java:258)
	at com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.privateInvoke(StubInvocationHandlerImpl.java:188)
	at com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.invoke(StubInvocationHandlerImpl.java:140)
	at com.sun.corba.ee.impl.presentation.rmi.codegen.CodegenStubBase.invoke(CodegenStubBase.java:226)
	at test.__BenchMarkRemote_Remote_DynamicStub.getList(test/__BenchMarkRemote_Remote_DynamicStub.java)
	at test._BenchMarkRemote_Wrapper.getList(test/_BenchMarkRemote_Wrapper.java)
	at test.TestListServlet.doGet(TestListServlet.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1637)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:259)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:372)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:239)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:201)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
]]

### Current Outcome

This is an example of my ejb call.
In the compressed file, WebClient.war is the client and ejb.jar is the server.
After the client deployment is completed, you need to modify the WebClient/WEB-INF/classes/ejb-jndi. properties file to the IP address of your machine and the iiop port of the payara server, for example:

java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory
java.naming.factory.url.pkgs=com.sun.enterprise.naming
org.omg.CORBA.ORBInitialHost=192.168.1.1
org.omg.CORBA.ORBInitialPort=3700
ejb.jndiName=java:global/ejb/BenchMarkBean

Then visit http://localhost:8080/WebClient/TestListServlet,page is blank,error is reported in server.log.
[test.zip](https://github.com/payara/Payara/files/9935460/test.zip)

### Reproducer

[test.zip](https://github.com/payara/Payara/files/9935520/test.zip)

### Operating System

Windows 10

### JDK Version

JDK1.8.0_291-b10

### Payara Distribution

Payara Server Full Profile

**Comment by svendiedrichsen** [comment]
The stacktrace shows that you are out of memory: `Caused by: java.lang.OutOfMemoryError: Java heap space`

**Comment by wuxinbin** [comment]
> The stacktrace shows that you are out of memory: `Caused by: java.lang.OutOfMemoryError: Java heap space`

I know that there is an OutOfMemoryError, but I think this error is caused by the defect of corba serialization and deserialization. When debugging the source code, I found that corba serialized three fields when it serialized ConcurrentHashMap, but did not deserialize the first two int type fields (semgentMask and segmentShift), resulting in an error in deserializing the byteBuffer later, thus reporting an OutOfMemoryError. I think this is the main reason. I think it should be a corba bug. The following is a screenshot of my debugging corba source code.

The source code for serializing ConcurrentHashMap is located at com. sun. corpa. ee. impl. io. OutStreamHook. java (139lines)
![Serialize](https://user-images.githubusercontent.com/58963409/200208571-218a8cc7-4ad4-4875-8164-245654d435c2.jpg)

The source code for deserializing ConcurrentHashMap is located at com.sun.corba.ee.impl.io.IIOPInputStream.java (2311 lines)
![Deserialize](https://user-images.githubusercontent.com/58963409/200208846-b1b01fdd-816a-4401-aced-f13736bab5bf.jpg)

I think you can debug this code with my example, so that you can more clearly understand the problems I said. Thank you for your reply and look forward to your reply.

**Comment by svendiedrichsen** [comment]
The OOM error might be related to the content of the map you are trying to serialize/deserialize. But anyway.
I think that the Payara project is the wrong project to file CORBA bugs. IHMO you should file a bug at https://github.com/eclipse-ee4j/orb

**Comment by shub8968** [comment]
Hi @wuxinbin,

Please share the source code of your reproducer.

**Comment by wuxinbin** [comment]
> Hi @wuxinbin,
> 
> Please share the source code of your reproducer.

Hi @shub8968,
This is the source code of my example.
[SourceCode.zip](https://github.com/payara/Payara/files/10037095/SourceCode.zip)

**Comment by pzygielo** [comment]
I fail to see `BenchMarkBean` to be `Serializable`.

**Comment by wuxinbin** [comment]
> ~I fail to see `BenchMarkBean` to be `Serializable`.~

I don't understand what you mean.

**Comment by pzygielo** [comment]
@wuxinbin - my mistake

**Comment by pzygielo** [comment]
Sounds like [JDK-8068721](https://bugs.openjdk.org/browse/JDK-8068721).
