### ISSUE TITLE
Bug Report: 5.2022.4 accessing /metrics results in Internal Server Error

### ISSUE THREAD

**Issue by jbndbc** [payara/Payara#6041]
### Brief Summary

Accessing the /metrics endpoint in a running instance produces Internal Server error due to Health-Check service healthcheck-cpool/jdbc/service-db/pool#usedConnection not being found, where jdbc/service-db is the JNDI name of the JDBC resource configured for the particular service.

### Expected Outcome

Normal metrics output

### Current Outcome

12:41:27 [http-thread-pool::http-listener(1)] WARN  dk.dbc.PAYARA.javax.enterprise.web - StandardWrapperValve[microprofile-metrics-resource]: Servlet.service() for servlet microprofile-metrics-resource threw exception
java.lang.IllegalStateException: Health-Check service not found : healthcheck-cpool/jdbc/service-db/pool#usedConnection
        at fish.payara.microprofile.metrics.jmx.MetricsMetadataHelper.registerMetadata(MetricsMetadataHelper.java:148)
        at fish.payara.microprofile.metrics.impl.MetricsServiceImpl.initMetadataConfig(MetricsServiceImpl.java:423)
        at fish.payara.microprofile.metrics.impl.MetricsServiceImpl.bootstrap(MetricsServiceImpl.java:530)
        at fish.payara.microprofile.metrics.impl.MetricsServiceImpl.refresh(MetricsServiceImpl.java:438)
        at fish.payara.microprofile.metrics.rest.MetricsResource.processRequest(MetricsResource.java:112)
        at fish.payara.microprofile.metrics.rest.MetricsResource.doGet(MetricsResource.java:288)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1637)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:282)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:167)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:372)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:239)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:201)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.base/java.lang.Thread.run(Thread.java:829)

### Reproducer

Access /metrics endpoint when a JDBC resource connection pool is configured.

### Operating System

debian 11

### JDK Version

openjdk 11.0.13 2021-10-19

### Payara Distribution

Payara Server Full Profile, Payara Micro

**Comment by shub8968** [comment]
Hi @jbndbc,

I am unable to reproduce it. Can you provide a simple-to-follow scenario on how to reproduce this on the latest version? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. It will greatly help us to find the cause and fix it.

**Comment by shub8968** [comment]
Closing due to inactivity.

**Comment by jerwaz** [comment]
Hello,

I had the same issue, solved it by removing the "/" from the jdbc-connection-pool name that I had. 
I guess there is an issue in `fish.payara.microprofile.metrics.healthcheck.ServiceExpression`, that makes `expression.getServiceId()` in `fish.payara.microprofile.metrics.jmx.MetricsMetadataHelper` return a bad value

regards
