### ISSUE TITLE
Bug Report: asadmin CLI - start/stop/restart deployment groups or clusters times out

### ISSUE THREAD

**Issue by surpriselawn** [payara/Payara#6057]
### Brief Summary

With Payara 5.2022.4 (Full), if you attempt to use start/stop/restart-deployment-group or start/stop/restart-cluster from the asadmin CLI the asadmin client hangs for 10 minutes before reporting similar to along the lines of 

Read timed out
Command <one of commands from above> failed

These commands from the CLI are working OK under the previous version 5.2022.3 (Full)

### Expected Outcome

Commands such as asadmin start/stop/restart-deployment-group or asadmin start/stop/restart-cluster should be able to execute without running into Read timed out errors. Example below of 5.2022.3 starting of deployment group successfully using system property -DAS_TRACE=true for the asadmin client with the deployment group started successfully.

**Command start-deployment-group executed successfully.**

```
asadmin start-deployment-group testdeploymentgroup
CLICommand not found for name start-deployment-group
Assuming it's a remote command: start-deployment-group
RemoteCLICommand executes
Prepare
Command model for command start-deployment-group is not in cache. It must be fatched from server.
URI: /command/start-deployment-group
URL: http://localhost:4848/command/start-deployment-group
Method: GET
Password options: null
Using auth info: null
Response code: 200
------- RAW METADATA RESPONSE ---------
ETag: pAP4FnDrwmG/kptW3tN63Q==
{"command":{"@name":"start-deployment-group","@managed-job":true,"option":[{"@name":"deploymentGroup","@type":"STRING","@primary":true},{"@name":"verbose","@type":"BOOLEAN","@optional":true,"@short":"v","@default":"false"},{"@name":"instanceTimeout","@type":"STRING","@optional":true},{"@name":"timeout","@type":"STRING","@optional":true}]}}
------- RAW METADATA RESPONSE ---------
Command model for start-deployment-group command fetched from remote server. [Duration: 54,168,500 nanos]
doHttpCommand succeeds
Process program options
Parse command options
params: {}
operands: [testdeploymentgroup]
Prevalidate command options
Inject command options
Validate command options
asadmin --host localhost --port 4848 --interactive=true --echo=false --terse=false --extraterse=false --autoname=false start-deployment-group --verbose=false testdeploymentgroup
Execute command
RemoteCLICommand.executeCommand()
RemoteRestAdminCommand.executeCommand() - name: start-deployment-group
doUpload set to false
URI: /command/start-deployment-group
URL: http://localhost:4848/command/start-deployment-group
Method: POST
Password options: null
Using auth info: null
Writer to use com.sun.enterprise.admin.remote.writer.ParameterMapFormProprietaryWriter
Response code: 200
Result type is text/event-stream;charset=UTF-8
URL connection is sun.net.www.protocol.http.HttpURLConnection
Response is SSE - about to read events
Event: AdminCommandInstance/stateChanged
Command instance ID: 1
Event: ProgressStatus/state
  0%: start-deployment-group: Starting
Event: ProgressStatus/change
Event: ProgressStatus/change
  0%: start-deployment-group: Executing start-instance on 1 instances.
Event: ProgressStatus/change
100%: start-deployment-group: testinstance1
Event: ProgressStatus/change
Event: AdminCommandInstance/stateChanged
Command instance ID: 1
------ ACTION REPORT ------
ACTION REPORT - 0 [SUCCESS]
 actionDescription: start-deployment-group AdminCommand
    MESSAGE - 0.M0


---- END ACTION REPORT ----
doHttpCommand succeeds

Command start-deployment-group executed successfully.
```

### Current Outcome

Using 5.2022.4 with same start-deployment-group group command and system property of -DAS_TRACE=true you get this with a read time out at the end after 10 minutes.

Key area is this part in trace -

**Response is SSE - about to read events
Read timed out
Command start-deployment-group failed.**

The thread stack shows where the client is blocked - 

**at com.sun.enterprise.admin.remote.sse.GfSseEventReceiver.readEvent(GfSseEventReceiver.java:83)**

```
asadmin start-deployment-group testdeploymentgroup
CLICommand not found for name start-deployment-group
Assuming it's a remote command: start-deployment-group
RemoteCLICommand executes
Prepare
Cached command model ETag is pAP4FnDrwmG/kptW3tN63Q==
------- RAW METADATA RESPONSE ---------
ETag: pAP4FnDrwmG/kptW3tN63Q==
{"command":{"@name":"start-deployment-group","@managed-job":true,"option":[{"@name":"deploymentGroup","@type":"STRING","@primary":true},{"@name":"verbose","@type":"BOOLEAN","@optional":true,"@short":"v","@default":"false"},{"@name":"instanceTimeout","@type":"STRING","@optional":true},{"@name":"timeout","@type":"STRING","@optional":true}]}}
------- RAW METADATA RESPONSE ---------
Command model for command start-deployment-group was successfully loaded from the cache. [Duration: 27,762,000 nanos]
Process program options
Parse command options
params: {}
operands: [testdeploymentgroup]
Prevalidate command options
Inject command options
Validate command options
asadmin --host localhost --port 4848 --interactive=true --echo=false --terse=false --extraterse=false --autoname=false start-deployment-group --verbose=false testdeploymentgroup
Execute command
RemoteCLICommand.executeCommand()
RemoteRestAdminCommand.executeCommand() - name: start-deployment-group
doUpload set to false
URI: /command/start-deployment-group
URL: http://localhost:4848/command/start-deployment-group
Method: POST
Password options: null
Using auth info: null
CommandModel ETag: pAP4FnDrwmG/kptW3tN63Q==
Writer to use com.sun.enterprise.admin.remote.writer.ParameterMapFormProprietary
```Writer
Response code: 200
Result type is text/event-stream;charset=UTF-8
URL connection is sun.net.www.protocol.http.HttpURLConnection
Response is SSE - about to read events
Read timed out
Command start-deployment-group failed.

```

```
"main" #1 prio=5 os_prio=0 tid=0x000001bfa036c000 nid=0x30f8 runnable [0x00000041b73fe000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        - locked <0x000000076f2e6060> (a java.io.BufferedInputStream)
        at sun.net.www.http.ChunkedInputStream.readAheadBlocking(ChunkedInputStream.java:552)
        at sun.net.www.http.ChunkedInputStream.readAhead(ChunkedInputStream.java:609)
        at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:696)
        - locked <0x000000076f2ea8a0> (a sun.net.www.http.ChunkedInputStream)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3454)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3447)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3435)
        at com.sun.enterprise.admin.remote.sse.GfSseEventReceiver.readEvent(GfSseEventReceiver.java:83)
        at com.sun.enterprise.admin.remote.RemoteRestAdminCommand$1.useConnection(RemoteRestAdminCommand.java:826)
        at com.sun.enterprise.admin.remote.RemoteRestAdminCommand.doHttpCommand(RemoteRestAdminCommand.java:1164)
        at com.sun.enterprise.admin.remote.RemoteRestAdminCommand.doHttpCommand(RemoteRestAdminCommand.java:1027)
        at com.sun.enterprise.admin.remote.RemoteRestAdminCommand.executeRemoteCommand(RemoteRestAdminCommand.java:776)
        at com.sun.enterprise.admin.remote.RemoteRestAdminCommand.executeCommand(RemoteRestAdminCommand.java:587)
        at com.sun.enterprise.admin.cli.remote.RemoteCLICommand.executeCommand(RemoteCLICommand.java:762)
        at com.sun.enterprise.admin.cli.CLICommand.execute(CLICommand.java:340)
        at com.sun.enterprise.admin.cli.remote.RemoteCLICommand.execute(RemoteCLICommand.java:597)
        at com.sun.enterprise.admin.cli.AdminMain.executeCommand(AdminMain.java:348)
        at com.sun.enterprise.admin.cli.AdminMain.doMain(AdminMain.java:282)
        at org.glassfish.admin.cli.AsadminMain.main(AsadminMain.java:56)
```

### Reproducer

Download Payara 5.2022.4 (Full) 

Then run the folllowing - 

- asadmin start-domain
- asadmin create-instance --node=localhost-domain1 testinstance1
- asadmin create-deployment-group testdeploymentgroup
- asadmin add-instance-to-deployment-group --instance=testinstance1 --deploymentGroup=testdeploymentgroup 
- Add in System property -DAS_TRACE=true for asadmin client
- asadmin start-deployment-group testdeploymentgroup

You will then get a Read time out after 10 miniutes and instances have failed to start.

Similar read timed out problem can be found with clusters do same download of Payara 5.2022.4 (Full)

- asadmin start-domain 
- asadmin copy-config default-config testcluster-config
- asadmin create-cluster --config=testcluster-config testcluster
- asadmin create-instance --node=localhost-domain1 --cluster=testcluster testinstance1
- Add in System property -DAS_TRACE=true for asadmin client
- asadmin start-cluster testcluster

### Operating System

Windows 10

### JDK Version

openjdk version "1.8.0_302"

### Payara Distribution

Payara Server Full Profile

**Comment by shub8968** [comment]
Hi @surpriselawn,

I have escalated this issue to our platform development team as `FISH-6815`. It may take a while to fix the issue, feel free to submit the PR.

**Comment by magikmw** [comment]
It's likely I have a similar/same issue with remotely initiated `undeploy` command. The 10 min timeout is not consistent, as sometimes the command goes through in the usual pace.
`show-component-status` used seconds earlier works fine every time.

Using payara version `5.2022.5`
