### ISSUE TITLE
Bug Report: Exception while dispatching an event

### ISSUE THREAD

**Issue by tuerker** [payara/Payara#6099]
### Brief Summary

Log: After having upgraded from Payara 5.2022.1 to Payara 5.2022.4, a warning is thrown although Payara 5.2022.4 deploys the application successfully as in Payara 5.2022.1:

```
[Payara 5.2022.4] [INFO] [] [javax.enterprise.system.core] [tid: _ThreadID=110 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1669982993937] [levelValue: 800] [[
  ... was successfully deployed in 21,927 milliseconds.]]

```
The warning looks as follows:

```
[Payara 5.2022.4] [WARNING] [NCLS-CORE-00069] [javax.enterprise.system.core] [tid: _ThreadID=110 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1669982993937] [levelValue: 900] [[
  Exception while dispatching an event
java.lang.NullPointerException
	at com.sun.enterprise.web.WebContainer.event(WebContainer.java:632)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:638)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:552)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:551)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:582)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:574)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:573)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1497)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1200(CommandRunnerImpl.java:120)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1869)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1755)
	at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:604)
	at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:256)
	at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:166)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:201)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:750)
```

Is this a bug? If not, how can i get rid of this warning?

Many thanks in advance.

### Expected Outcome

The warning described above should not be thrown.

### Current Outcome

The described warning.

### Reproducer

none

### Operating System

Ubuntu 22.04.1

### JDK Version

openjdk version "1.8.0_352" OpenJDK Runtime Environment (Zulu 8.66.0.15-CA-linux64) (build 1.8.0_352-b08)

### Payara Distribution

Payara Server Full Profile

**Comment by elcodedocle** [comment]
We are (occassionally) seeing something similar, also after upgrading to 2022.4, from 2022.2, on Debian bullseye (dockerized) with OpenJDK 11. Leaving the stacktrace in case it is relevant:

```
payara-test-server-1  | 2022-12-05T13:29:05.968222579Z [#|2022-12-05T13:29:05.965+0000[1;91m|SEVERE|[0mPayara 5.2022.4|[1;94mjavax.enterprise.system.core.ee|[0m_ThreadID=27;_ThreadName=RunLevelControllerThread-1670246933333;_TimeMillis=1670246945965;_LevelValue=1000;|
payara-test-server-1  | 2022-12-05T13:29:05.968227195Z   Unable to start container com.sun.enterprise.web.WebContainer
payara-test-server-1  | 2022-12-05T13:29:05.968231094Z MultiException stack 1 of 2
payara-test-server-1  | 2022-12-05T13:29:05.968235128Z java.lang.NullPointerException
payara-test-server-1  | 2022-12-05T13:29:05.968239097Z 	at com.sun.enterprise.web.WebContainer.createHttpListener(WebContainer.java:896)
payara-test-server-1  | 2022-12-05T13:29:05.968242921Z 	at com.sun.enterprise.web.WebContainer.createHttpListener(WebContainer.java:871)
payara-test-server-1  | 2022-12-05T13:29:05.968246749Z 	at com.sun.enterprise.web.WebContainer.postConstruct(WebContainer.java:575)
payara-test-server-1  | 2022-12-05T13:29:05.968250372Z 	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:303)
payara-test-server-1  | 2022-12-05T13:29:05.968253985Z 	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
payara-test-server-1  | 2022-12-05T13:29:05.968257624Z 	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
payara-test-server-1  | 2022-12-05T13:29:05.968261336Z 	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59)
payara-test-server-1  | 2022-12-05T13:29:05.968264957Z 	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47)
payara-test-server-1  | 2022-12-05T13:29:05.968268560Z 	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74)
payara-test-server-1  | 2022-12-05T13:29:05.968272317Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
payara-test-server-1  | 2022-12-05T13:29:05.968276063Z 	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131)
payara-test-server-1  | 2022-12-05T13:29:05.968279692Z 	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176)
payara-test-server-1  | 2022-12-05T13:29:05.968283285Z 	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98)
payara-test-server-1  | 2022-12-05T13:29:05.968286923Z 	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
payara-test-server-1  | 2022-12-05T13:29:05.968290629Z 	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
payara-test-server-1  | 2022-12-05T13:29:05.968294254Z 	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
payara-test-server-1  | 2022-12-05T13:29:05.968297917Z 	at org.glassfish.internal.data.EngineInfo.getContainer(EngineInfo.java:86)
payara-test-server-1  | 2022-12-05T13:29:05.968302703Z 	at org.glassfish.kernel.javaee.WebContainerStarter.startWebContainer(WebContainerStarter.java:235)
payara-test-server-1  | 2022-12-05T13:29:05.968306546Z 	at org.glassfish.kernel.javaee.WebContainerStarter.postConstruct(WebContainerStarter.java:174)
payara-test-server-1  | 2022-12-05T13:29:05.968318276Z 	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:303)
payara-test-server-1  | 2022-12-05T13:29:05.968322412Z 	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
payara-test-server-1  | 2022-12-05T13:29:05.968326107Z 	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
payara-test-server-1  | 2022-12-05T13:29:05.968329787Z 	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
payara-test-server-1  | 2022-12-05T13:29:05.968333474Z 	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
payara-test-server-1  | 2022-12-05T13:29:05.968337092Z 	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
payara-test-server-1  | 2022-12-05T13:29:05.968340698Z 	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
payara-test-server-1  | 2022-12-05T13:29:05.968344430Z 	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
payara-test-server-1  | 2022-12-05T13:29:05.968348109Z 	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
payara-test-server-1  | 2022-12-05T13:29:05.968351816Z 	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
payara-test-server-1  | 2022-12-05T13:29:05.968355505Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
payara-test-server-1  | 2022-12-05T13:29:05.968359259Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
payara-test-server-1  | 2022-12-05T13:29:05.968362917Z 	at java.base/java.lang.Thread.run(Thread.java:829)
payara-test-server-1  | 2022-12-05T13:29:05.968366511Z MultiException stack 2 of 2
payara-test-server-1  | 2022-12-05T13:29:05.968370066Z java.lang.IllegalStateException: Unable to perform operation: post construct on com.sun.enterprise.web.WebContainer
payara-test-server-1  | 2022-12-05T13:29:05.968373876Z 	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:369)
payara-test-server-1  | 2022-12-05T13:29:05.968377494Z 	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
payara-test-server-1  | 2022-12-05T13:29:05.968381156Z 	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59)
payara-test-server-1  | 2022-12-05T13:29:05.968384783Z 	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47)
payara-test-server-1  | 2022-12-05T13:29:05.968388534Z 	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74)
payara-test-server-1  | 2022-12-05T13:29:05.968392186Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
payara-test-server-1  | 2022-12-05T13:29:05.968395778Z 	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131)
payara-test-server-1  | 2022-12-05T13:29:05.968399438Z 	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176)
payara-test-server-1  | 2022-12-05T13:29:05.968403540Z 	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98)
payara-test-server-1  | 2022-12-05T13:29:05.968407311Z 	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
payara-test-server-1  | 2022-12-05T13:29:05.968410949Z 	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
payara-test-server-1  | 2022-12-05T13:29:05.968416898Z 	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
payara-test-server-1  | 2022-12-05T13:29:05.968420822Z 	at org.glassfish.internal.data.EngineInfo.getContainer(EngineInfo.java:86)
payara-test-server-1  | 2022-12-05T13:29:05.968424512Z 	at org.glassfish.kernel.javaee.WebContainerStarter.startWebContainer(WebContainerStarter.java:235)
payara-test-server-1  | 2022-12-05T13:29:05.968428149Z 	at org.glassfish.kernel.javaee.WebContainerStarter.postConstruct(WebContainerStarter.java:174)
payara-test-server-1  | 2022-12-05T13:29:05.968431788Z 	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:303)
payara-test-server-1  | 2022-12-05T13:29:05.968435430Z 	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
payara-test-server-1  | 2022-12-05T13:29:05.968439067Z 	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
payara-test-server-1  | 2022-12-05T13:29:05.968442695Z 	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
payara-test-server-1  | 2022-12-05T13:29:05.968446392Z 	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
payara-test-server-1  | 2022-12-05T13:29:05.968450009Z 	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
payara-test-server-1  | 2022-12-05T13:29:05.968453621Z 	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
payara-test-server-1  | 2022-12-05T13:29:05.968457234Z 	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
payara-test-server-1  | 2022-12-05T13:29:05.968460858Z 	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
payara-test-server-1  | 2022-12-05T13:29:05.968464613Z 	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
payara-test-server-1  | 2022-12-05T13:29:05.968468302Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
payara-test-server-1  | 2022-12-05T13:29:05.968471966Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
payara-test-server-1  | 2022-12-05T13:29:05.968475637Z 	at java.base/java.lang.Thread.run(Thread.java:829)
payara-test-server-1  | 2022-12-05T13:29:05.968479307Z |#]
payara-test-server-1  | 2022-12-05T13:29:05.968482832Z 
payara-test-server-1  | 2022-12-05T13:29:11.955124839Z [#|2022-12-05T13:29:11.920+0000[1;91m|SEVERE|[0mPayara 5.2022.4|[1;94mjavax.enterprise.web.core|[0m_ThreadID=56;_ThreadName=GF Domain XML;_TimeMillis=1670246951920;_LevelValue=1000;_MessageID=AS-WEB-CORE-00035;|
payara-test-server-1  | 2022-12-05T13:29:11.955157603Z   Coyote connector has not been started|#]
payara-test-server-1  | 2022-12-05T13:29:11.955162828Z 
```

**Comment by shub8968** [comment]
Hi @tuerker, @elcodedocle,

Would you be kind enough to share the reproducer app with us? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. It will significantly help us to find the cause and fix it.

Thanks,
Shubham

**Comment by elcodedocle** [comment]
Hi @shub8968 ,

Unfortunately this bug seems to be quite elusive. I've only seen it on our CI pipeline, rather unfrequently (maybe 1 out of 5-6 times).

I've failed to reproduce it on [the shortest SSCCE I could come up with](https://github.com/elcodedocle/payara-sscce), no matter how many times I run it: This is a simple maven project that builds a minimal jax-rs application and deploys it on payara's official dockerhub image, then runs a junit integration test to confirm correct deployment without severe log traces. I never get this error or any other (SEVERE) errors running this example.

Obviously our project does deploy a much more complex application with several extra asadmin configuration options, but none of them seem related: I think it is more of a race condition that depends on the timing of the app deployment (in relation to Payara initialization with start domain command), and the app initialization sequence itself.

**Comment by tuerker** [comment]
Dear all,
i have now upgraded from  Payara 5.2022.4 to Payara 5.2022.5 and this issue is gone in this version.
Cheers,
Can
