### ISSUE TITLE
Problem with jndi lookup from remote machine

### ISSUE THREAD

**Issue by andreas513** [payara/Payara#610]
Hello,

I have an Problem with the jndi lookup. I make an call from my simple Java Client application to the remote Payara Server Open Source Edition 4.1.152.1 #badassfish (build 193) on an Linux System.

Here is the code of the java client:

```Java
package fmg;

import java.util.Properties;

import javax.jms.Connection;
import javax.jms.DeliveryMode;
import javax.jms.JMSException;
import javax.jms.MessageProducer;
import javax.jms.Session;
import javax.jms.TextMessage;
import javax.jms.Topic;
import javax.jms.TopicConnectionFactory;
import javax.naming.InitialContext;

public class TestJMSQueue 
{
	 public static void main(String a[]) throws Exception { 
		  String msg = "Hello from remote JMS Client";       
		  TestJMSQueue test = new TestJMSQueue();       
		  System.out.println("==============================");   
		  System.out.println("Sending message to Queue");   
		  System.out.println("==============================");   
		  System.out.println();   
		  test.sendMessage2Queue(msg);   
		  System.out.println();   
		  System.out.println("==============================");   
		  System.exit(0);  
	 }
	 
	 private void sendMessage2Queue(String msg) throws Exception
	 {                
		 Properties props = new Properties();   
		 props = new Properties();
		 props.setProperty("java.naming.factory.initial",
             "com.sun.enterprise.naming.SerialInitContextFactory");
		 props.setProperty("java.naming.factory.url.pkgs",
             "com.sun.enterprise.naming");
		 props.setProperty("java.naming.factory.state",
             "com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl");
		 props.setProperty("org.omg.CORBA.ORBInitialHost", "prodweb4");
		 props.setProperty("org.omg.CORBA.ORBInitialPort", "3700");
		 props.setProperty("com.sun.corba.ee.transport.ORBTCPTimeouts", 
		       "500:30000:30:999999");
		 props.setProperty("com.sun.jndi.ldap.connect.timeout", "500");   
		 // Create the initial context for remote JMS server   
		 InitialContext cntxt = new InitialContext(props);   
		 System.out.println("Context Created");       
		 // JNDI Lookup for TopicConnectionFactory in remote JMS Provider  
		 TopicConnectionFactory factory = (TopicConnectionFactory)cntxt.lookup("jms/LmuTopicConnectionFactory");
		 System.out.println("Factory available");
		 // Create a Connection from TopicConnectionFactory
		 Connection connection = factory.createConnection();   
		 
		 // Initialise the communication session    
		 Session session = connection.createSession(false, Session.AUTO_ACKNOWLEDGE);       
		 // Create the message   
		 TextMessage message = session.createTextMessage();   
		 message.setJMSDeliveryMode(DeliveryMode.NON_PERSISTENT);   
		 message.setText(msg);       
		 // JNDI Lookup for the Queue in remote JMS Provider   
		 Topic topic = (Topic)cntxt.lookup("jms/LmuTopic");       
		 // Create the MessageProducer for this communication    
		 // Session on the Queue we have   
		 MessageProducer mp = session.createProducer(topic);       
		 // Send the message to Queue   
		 mp.send(message);   
		 System.out.println("Message Sent: " + msg);       
		 // Make sure all the resources are released    
		 mp.close();   
		 session.close();   
		 cntxt.close();      
	 }
}
```

At the point I want to create the connection I receive an failure.

This is the Output on the console of the Client Programm:

```
==============================
Sending message to Queue
==============================

Context Created
Jan 20, 2016 10:51:17 AM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 5.1.2.Final
Jan 20, 2016 10:51:17 AM com.sun.messaging.jms.ra.ResourceAdapter start
INFORMATION: MQJMSRA_RA1101: GlassFish MQ JMS Resource Adapter: Version:  5.1.1  (Build 2-c) Compile:  March 17 2015 1045
Jan 20, 2016 10:51:17 AM com.sun.messaging.jms.ra.ResourceAdapter start
INFORMATION: MQJMSRA_RA1101: GlassFish MQ JMS Resource Adapter starting: broker is REMOTE, connection mode is TCP
Jan 20, 2016 10:51:17 AM com.sun.messaging.jms.ra.ResourceAdapter start
INFORMATION: MQJMSRA_RA1101: GlassFish MQ JMS Resource Adapter Started:REMOTE
Factory available
org.omg.CORBA.COMM_FAILURE: FEIN: 00410001: Connection failure: socketType: IIOP_CLEAR_TEXT; hostname: localhost; port: 3700  vmcid: OMG  minor code: 1  completed: No
	at com.sun.proxy.$Proxy19.connectFailure(Unknown Source)
	at com.sun.corba.ee.impl.transport.ConnectionImpl.<init>(ConnectionImpl.java:253)
	at com.sun.corba.ee.impl.transport.ConnectionImpl.<init>(ConnectionImpl.java:276)
	at com.sun.corba.ee.impl.transport.ContactInfoImpl.createConnection(ContactInfoImpl.java:129)
	at com.sun.corba.ee.impl.protocol.ClientRequestDispatcherImpl.beginRequest(ClientRequestDispatcherImpl.java:242)
	at com.sun.corba.ee.impl.protocol.ClientDelegateImpl.request(ClientDelegateImpl.java:220)
	at com.sun.corba.ee.impl.protocol.ClientDelegateImpl.is_a(ClientDelegateImpl.java:378)
	at org.omg.CORBA.portable.ObjectImpl._is_a(ObjectImpl.java:130)
	at org.omg.CosNaming.NamingContextHelper.narrow(NamingContextHelper.java:69)
	at com.sun.enterprise.naming.impl.SerialContext$ProviderCacheKey.getNameService(SerialContext.java:1205)
	at com.sun.enterprise.naming.impl.SerialContext.getRemoteProvider(SerialContext.java:393)
	at com.sun.enterprise.naming.impl.SerialContext.getProvider(SerialContext.java:329)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:477)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:438)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at org.glassfish.resourcebase.resources.naming.ResourceNamingService.lookup(ResourceNamingService.java:238)
	at com.sun.enterprise.connectors.service.ConnectorConnectionPoolAdminServiceImpl.getConnectorConnectionPool(ConnectorConnectionPoolAdminServiceImpl.java:883)
	at com.sun.enterprise.connectors.service.ConnectorConnectionPoolAdminServiceImpl.getConnectorConnectionPool(ConnectorConnectionPoolAdminServiceImpl.java:865)
	at com.sun.enterprise.connectors.service.ConnectorConnectionPoolAdminServiceImpl.getPoolType(ConnectorConnectionPoolAdminServiceImpl.java:1136)
	at com.sun.enterprise.connectors.ConnectorRuntime.getPoolType(ConnectorRuntime.java:1167)
	at com.sun.enterprise.resource.allocator.AbstractConnectorAllocator.createResourceHandle(AbstractConnectorAllocator.java:209)
	at com.sun.enterprise.resource.allocator.ConnectorAllocator.createResource(ConnectorAllocator.java:164)
	at com.sun.enterprise.resource.pool.ConnectionPool.createSingleResource(ConnectionPool.java:907)
	at com.sun.enterprise.resource.pool.ConnectionPool.createResource(ConnectionPool.java:1189)
	at com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.addResource(RWLockDataStructure.java:98)
	at com.sun.enterprise.resource.pool.ConnectionPool.addResource(ConnectionPool.java:282)
	at com.sun.enterprise.resource.pool.ConnectionPool.createResourceAndAddToPool(ConnectionPool.java:1512)
	at com.sun.enterprise.resource.pool.ConnectionPool.createResources(ConnectionPool.java:944)
	at com.sun.enterprise.resource.pool.ConnectionPool.initPool(ConnectionPool.java:230)
	at com.sun.enterprise.resource.pool.ConnectionPool.internalGetResource(ConnectionPool.java:511)
	at com.sun.enterprise.resource.pool.ConnectionPool.getResource(ConnectionPool.java:381)
	at com.sun.enterprise.resource.pool.PoolManagerImpl.getResourceFromPool(PoolManagerImpl.java:245)
	at com.sun.enterprise.resource.pool.PoolManagerImpl.getResource(PoolManagerImpl.java:171)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.getResource(ConnectionManagerImpl.java:354)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.internalGetConnection(ConnectionManagerImpl.java:307)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:196)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:171)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:166)
	at com.sun.messaging.jms.ra.ConnectionFactoryAdapter._allocateConnection(ConnectionFactoryAdapter.java:204)
	at com.sun.messaging.jms.ra.ConnectionFactoryAdapter.createConnection(ConnectionFactoryAdapter.java:162)
	at com.sun.messaging.jms.ra.ConnectionFactoryAdapter.createConnection(ConnectionFactoryAdapter.java:144)
	at fmg.TestJMSQueue.sendMessage2Queue(TestJMSQueue.java:52)
	at fmg.TestJMSQueue.main(TestJMSQueue.java:24)
Caused by: java.lang.RuntimeException: java.net.ConnectException: Connection refused: connect
	at org.glassfish.enterprise.iiop.impl.IIOPSSLSocketFactory.createSocket(IIOPSSLSocketFactory.java:344)
	at com.sun.corba.ee.impl.transport.ConnectionImpl.<init>(ConnectionImpl.java:250)
	... 41 more
Caused by: java.net.ConnectException: Connection refused: connect
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at com.sun.corba.ee.impl.misc.ORBUtility.openSocketChannel(ORBUtility.java:110)
	at org.glassfish.enterprise.iiop.impl.IIOPSSLSocketFactory.createSocket(IIOPSSLSocketFactory.java:329)
	... 42 more
Jan 20, 2016 10:52:38 AM com.sun.enterprise.resource.allocator.AbstractConnectorAllocator createResourceHandle
WARNUNG: RAR8067: Unable to determine pool type for pool [ jms/LmuTopicConnectionFactory-Connection-Pool ], using default pool type
org.omg.CORBA.COMM_FAILURE: FEIN: 00410001: Connection failure: socketType: IIOP_CLEAR_TEXT; hostname: localhost; port: 3700  vmcid: OMG  minor code: 1  completed: No
	at com.sun.proxy.$Proxy19.connectFailure(Unknown Source)
	at com.sun.corba.ee.impl.transport.ConnectionImpl.<init>(ConnectionImpl.java:253)
	at com.sun.corba.ee.impl.transport.ConnectionImpl.<init>(ConnectionImpl.java:276)
	at com.sun.corba.ee.impl.transport.ContactInfoImpl.createConnection(ContactInfoImpl.java:129)
	at com.sun.corba.ee.impl.protocol.ClientRequestDispatcherImpl.beginRequest(ClientRequestDispatcherImpl.java:242)
	at com.sun.corba.ee.impl.protocol.ClientDelegateImpl.request(ClientDelegateImpl.java:220)
	at com.sun.corba.ee.impl.protocol.ClientDelegateImpl.is_a(ClientDelegateImpl.java:378)
	at org.omg.CORBA.portable.ObjectImpl._is_a(ObjectImpl.java:130)
	at org.omg.CosNaming.NamingContextHelper.narrow(NamingContextHelper.java:69)
	at com.sun.enterprise.naming.impl.SerialContext$ProviderCacheKey.getNameService(SerialContext.java:1205)
	at com.sun.enterprise.naming.impl.SerialContext.getRemoteProvider(SerialContext.java:393)
	at com.sun.enterprise.naming.impl.SerialContext.getProvider(SerialContext.java:329)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:477)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:438)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at com.sun.enterprise.resource.naming.AdministeredObjectFactory.getObjectInstance(AdministeredObjectFactory.java:98)
	at javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:321)
	at com.sun.enterprise.naming.impl.SerialContext.getObjectInstance(SerialContext.java:527)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:487)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:438)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at fmg.TestJMSQueue.sendMessage2Queue(TestJMSQueue.java:61)
	at fmg.TestJMSQueue.main(TestJMSQueue.java:24)
Caused by: java.lang.RuntimeException: java.net.ConnectException: Connection refused: connect
	at org.glassfish.enterprise.iiop.impl.IIOPSSLSocketFactory.createSocket(IIOPSSLSocketFactory.java:344)
	at com.sun.corba.ee.impl.transport.ConnectionImpl.<init>(ConnectionImpl.java:250)
	... 21 more
Caused by: java.net.ConnectException: Connection refused: connect
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at com.sun.corba.ee.impl.misc.ORBUtility.openSocketChannel(ORBUtility.java:110)
	at org.glassfish.enterprise.iiop.impl.IIOPSSLSocketFactory.createSocket(IIOPSSLSocketFactory.java:329)
	... 22 more
Exception in thread "main" javax.naming.CommunicationException: Communication exception for SerialContext[myEnv={org.omg.CORBA.ORBInitialPort=3700, java.naming.factory.initial=com.sun.enterprise.naming.SerialInitContextFactory, com.sun.jndi.ldap.connect.timeout=500, com.sun.corba.ee.transport.ORBTCPTimeouts=500:30000:30:999999, org.omg.CORBA.ORBInitialHost=prodweb4, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming} [Root exception is com.sun.appserv.connectors.internal.api.ConnectorRuntimeException: Failed to look up ConnectorDescriptor from JNDI]
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:513)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:438)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at fmg.TestJMSQueue.sendMessage2Queue(TestJMSQueue.java:61)
	at fmg.TestJMSQueue.main(TestJMSQueue.java:24)
Caused by: com.sun.appserv.connectors.internal.api.ConnectorRuntimeException: Failed to look up ConnectorDescriptor from JNDI
	at com.sun.enterprise.resource.naming.AdministeredObjectFactory.getObjectInstance(AdministeredObjectFactory.java:104)
	at javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:321)
	at com.sun.enterprise.naming.impl.SerialContext.getObjectInstance(SerialContext.java:527)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:487)
	... 4 more
```

How do I configure the payara to publish not localhost? Or do I have an mistake in my Java-Code? I want to use the Topic on the Linux System prodweb4.

I have this entries in the /etc/Hosts of the Linux System:

```
-bash-4.1$ more /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
134.247.132.200 prodweb4
```

Thanks for answering my request

**Comment by abhirockzz** [comment]
You are trying to connect from your machine1 (hosting Java client) to a remote Linux box. You are using prodweb4 as host name in your Java client code. You should have a host name mapping on machine1 which maps the IP of your remote Linux (hosting Payara) machine to the host name - prodweb4 (which you are using in the code)

Unless I am missing/misunderstanding anything...

**Comment by andreas513** [comment]
I have the same behavior with the IP Adresse. At the point I try to create the Connection

```
// Create a Connection from TopicConnectionFactory
         Connection connection = factory.createConnection();   
```
I receive the org.omg.CORBA.COMM_FAILURE and in my eyes it is not understandable that hostname is directed to localhost

```
IIOP_CLEAR_TEXT; hostname: localhost; port: 3700
```

**Comment by abhirockzz** [comment]
Do you mind posting a test application ? I can try debugging it.
Thanks!

**Comment by smillidge** [comment]
Given that you have made a connection to Payara and managed to lookup the initial objects in the JNDI tree my feeling this is a JMS infrastructure error. As @abhirockzz says a simpe test example would be great.

**Comment by smillidge** [comment]
Also can you check the imqAddressList property of the JMS Connection Factory in the Payara Server

**Comment by andreas513** [comment]
Thank you for the Response. I can provide the test program, however I can not grant an access to the application server prodweb4.

I do not have the property imqAddressList in my JMS ConnectionFactory. I try to add this entry

![payara-connectionfactory](https://cloud.githubusercontent.com/assets/16795210/12508166/b746ee2a-c0fa-11e5-98c8-37cfb8579ec8.GIF)

![payara_connectionfactory-properties](https://cloud.githubusercontent.com/assets/16795210/12508438/31fdb6d4-c0fc-11e5-9697-6b3d2b18089b.GIF)


and got this Warnings in the Client log

```
Context Created {org.omg.CORBA.ORBInitialPort=3700, java.naming.factory.initial=com.sun.enterprise.naming.SerialInitContextFactory, com.sun.jndi.ldap.connect.timeout=500, com.sun.corba.ee.transport.ORBTCPTimeouts=500:30000:30:999999, org.omg.CORBA.ORBInitialHost=134.247.132.200, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming}
Jan 22, 2016 11:27:16 AM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 5.1.2.Final
Jan 22, 2016 11:27:16 AM com.sun.messaging.jms.ra.ResourceAdapter start
INFORMATION: MQJMSRA_RA1101: GlassFish MQ JMS Resource Adapter: Version:  5.1.1  (Build 2-c) Compile:  March 17 2015 1045
Jan 22, 2016 11:27:16 AM com.sun.messaging.jms.ra.ResourceAdapter start
INFORMATION: MQJMSRA_RA1101: GlassFish MQ JMS Resource Adapter starting: broker is REMOTE, connection mode is TCP
Jan 22, 2016 11:27:16 AM com.sun.messaging.jms.ra.ResourceAdapter start
INFORMATION: MQJMSRA_RA1101: GlassFish MQ JMS Resource Adapter Started:REMOTE
Jan 22, 2016 11:27:16 AM com.sun.enterprise.connectors.util.SetMethodAction getMutatorMethod
WARNUNG: RAR8000 : The method setImqAddressList is not present in the class : com.sun.messaging.jms.ra.ManagedConnectionFactory
Jan 22, 2016 11:27:16 AM com.sun.enterprise.connectors.util.SetMethodAction run
WARNUNG: RAR7097: No setter method present for the property imqAddressList in the class com.sun.messaging.jms.ra.ManagedConnectionFactory
Jan 22, 2016 11:27:16 AM com.sun.enterprise.connectors.util.SetMethodAction getMutatorMethod
WARNUNG: RAR8000 : The method setImqAddressList is not present in the class : com.sun.messaging.jms.ra.ManagedConnectionFactory
Jan 22, 2016 11:27:16 AM com.sun.enterprise.connectors.util.SetMethodAction run
WARNUNG: RAR7097: No setter method present for the property imqAddressList in the class com.sun.messaging.jms.ra.ManagedConnectionFactory
Factory available com.sun.messaging.jms.ra.ConnectionFactoryAdapter@5b7aa898
```

And have at the end the same behavior

```
org.omg.CORBA.COMM_FAILURE: FEIN: 00410001: Connection failure: socketType: IIOP_CLEAR_TEXT; hostname: localhost; port: 3700  vmcid: OMG  minor code: 1  completed: No
```

Did I have the false ConnectionFactory in my Java code?

**Comment by smillidge** [comment]
OK I did some playing around to confirm. 

First you need to set the addresslist property, NOT imgAddressList which I said earlier, of the ConnectionFactory to be the hostname:port of the server hosting the MQ Broker as I mentioned above.

Second you must have a jndi.properties on the classpath of your client with the correct Hostname and port or run code like below;

```java
        System.setProperty("org.omg.CORBA.ORBInitialHost", "192.168.0.30");
        System.setProperty("org.omg.CORBA.ORBInitialPort", "3700");
        InitialContext ctx = new InitialContext();
        QueueConnectionFactory qcf = (QueueConnectionFactory)  ctx.lookup("jms/__defaultConnectionFactory");
        QueueConnection qc = qcf.createQueueConnection();
        Queue queue = (Queue) ctx.lookup("test");
        QueueSession session = qc.createQueueSession(true, Session.AUTO_ACKNOWLEDGE);
        QueueSender sender = session.createSender(queue);
        for (int i = 0; i < 10; i++) {
            sender.send(session.createTextMessage("Hello World"));
            System.out.println("Sent Message " + i);
        }
```

**Comment by andreas513** [comment]
Hello smillidge,

thank you for your response. I try your modification and set in the Resources -> JMS Resources -> jms/LmuTopicConnectionFactory the property

![editjmsconnectionfactory_additionalproperties](https://cloud.githubusercontent.com/assets/16795210/12575249/501e4680-c40b-11e5-80c0-1cdb3271750e.GIF)

and set

```
System.setProperty("org.omg.CORBA.ORBInitialHost", "prodweb4");
System.setProperty("org.omg.CORBA.ORBInitialPort", "3700");
InitialContext cntxt = new InitialContext();
```
instead of
```
Properties props = new Properties();
props.setProperty("org.omg.CORBA.ORBInitialHost", "prodweb4");
props.setProperty("org.omg.CORBA.ORBInitialPort", "3700");
InitialContext cntxt = new InitialContext(props);
```
and this fixes the problem. I try to remove the addresslist property in the TopicConnectionFactory and it also works. It seems there is a different behavior between Properties und System.setProperty and Default-Constructor of InitialContext() and InitialContext(Properties props). 

**In my case it works with System.setProperty and InitialContext()!**

**Comment by smillidge** [comment]
Great news. 

You don't always need the addresslist property if the Payara Server hosting the JMS connection factory has the DefaultJMSHost configured correctly.

**Comment by Osahamed** [comment]
@smillidge
I had the same problem, and using the System.setProperty fixed the issue, 
thank you,

**Comment by davidandradeb** [comment]
Hello, I need implement this, but doesnt work.

Machine A (10.142.0.10):
Payara
Application with method:

System.setProperty("org.omg.CORBA.ORBInitialHost", "10.142.0.12);
        System.setProperty("org.omg.CORBA.ORBInitialPort", "3700");
        InitialContext ctx = new InitialContext();
        QueueConnectionFactory qcf = (QueueConnectionFactory) ctx.lookup("jms/__defaultConnectionFactory");
        QueueConnection qc = qcf.createQueueConnection();
        Queue queue = (Queue) ctx.lookup("exampleQ");
        QueueSession session = qc.createQueueSession(true, Session.AUTO_ACKNOWLEDGE);
        QueueSender sender = session.createSender(queue);

        sender.send(session.createTextMessage("Hello World"));

Machine B (10.142.0.12)
EJB application:

@MessageDriven(
        activationConfig = {
            @ActivationConfigProperty(propertyName = "destination", propertyValue = "exampleQ"),
            @ActivationConfigProperty(propertyName = "destinationType", propertyValue = "javax.jms.Queue")
        }, mappedName = "exampleQ")
public class JMSManage implements MessageListener {
    
    protected final Logger LOG = Logger.getLogger(JMSManage.class);
    
    public JMSManage() {
        LOG.info("JMS Starts ...");
    }
    
    @Override
    public void onMessage(Message objMessageJMS_p) {
}


The message never arrived.

Please help me

**Comment by davidandradeb** [comment]
Mar 30, 2020 11:51:51 AM com.sun.enterprise.v3.server.CommonClassLoaderServiceImpl findDerbyClient
INFO: Cannot find javadb client jar file, derby jdbc driver will not be available by default.
Mar 30, 2020 11:51:51 AM com.sun.enterprise.v3.server.CommonClassLoaderServiceImpl findH2Client
INFO: Cannot find h2db client jar file, h2 jdbc driver will not be available by default.
Mar 30, 2020 11:51:51 AM org.glassfish.enterprise.iiop.api.GlassFishORBHelper postConstruct
INFO: GlassFishORBFactory service initialized.
Mar 30, 2020 11:51:55 AM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator null
Mar 30, 2020 11:51:55 AM com.sun.messaging.jms.ra.ResourceAdapter start
INFO: MQJMSRA_RA1101: GlassFish MQ JMS Resource Adapter: Version:  5.1.1  (Build 6-a) Compile:  June 28 2018 0917
Mar 30, 2020 11:51:55 AM com.sun.messaging.jms.ra.ResourceAdapter start
INFO: MQJMSRA_RA1101: GlassFish MQ JMS Resource Adapter starting: broker is REMOTE, connection mode is TCP
Mar 30, 2020 11:51:55 AM com.sun.messaging.jms.ra.ResourceAdapter start
INFO: MQJMSRA_RA1101: GlassFish MQ JMS Resource Adapter Started:REMOTE
Sending message: asd a: 10.142.0.12, port 3700

But the EJB never recieve this message
