### ISSUE TITLE
Bug Report: ConcurrentModificationException

### ISSUE THREAD

**Issue by thehpi** [payara/Payara#6101]
### Brief Summary

When using payara 5.2022.4 I sometimes see the following during startup. I tried to reproduce without success. 

at fish.payara.microprofile.faulttolerance.service.FaultToleranceServiceImpl.postConstruct(FaultToleranceServiceImpl.java:120)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1268)
at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:309)
at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)

Caused by: java.util.ConcurrentModificationException
at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
at org.jvnet.hk2.config.Transactions.addTransaction(Transactions.java:512)
at org.jvnet.hk2.config.Transactions.addTransaction(Transactions.java:497)
at org.jvnet.hk2.config.Transaction.commit(Transaction.java:125)
at org.jvnet.hk2.config.ConfigSupport._apply(ConfigSupport.java:186)
... 58 more

I looked at org.jvnet.hk2.config.Transactions.java and see several synchronized methods which access the 'listeners' instance variable.

So it looks like this array is supposed to be protected from concurrent access.

However this means that every method is synchronized so multiple threads can access different methods and still can access the 'listeners' object concurrently. This could be the cause of the problem. 

To be honest I have no idea what is happening here exactly but it seems to be related to microprofile fault tolerance initialization.

In my application I'm not using fault tolerance so it does not cause an immediate problem but if I start using e.g. bulkheads then I might be in trouble.

### Expected Outcome

no exception

### Current Outcome

the exception

### Reproducer

I cannot reproduce 

### Operating System

debian linux 11.5

### JDK Version

openjdk version "11.0.16" 2022-07-19

### Payara Distribution

Payara Server Full Profile

**Comment by elcodedocle** [comment]
A couple of possibly related example stack traces from different initializations on different instances of the same dockerized Payara 2022.4/OpenJDK 11/Debian Bullseye environment image and application:

Example A (same stack trace, extended, on fault tolerance):
```
[0m_ThreadID=27;_ThreadName=RunLevelControllerThread-1670204060247;_TimeMillis=1670204062869;_LevelValue=1000;_MessageID=NCLS-CFGAPI-00123;|
|2022-12-05T01:34:22.885202516ZCannotaddnewconfigurationextensiontotheextensionpoint.
|2022-12-05T01:34:22.885207378Zorg.jvnet.hk2.config.TransactionFailure
|2022-12-05T01:34:22.885211305Z	at org.jvnet.hk2.config.ConfigSupport._apply(ConfigSupport.java:215)
|2022-12-05T01:34:22.885215359Z	at org.jvnet.hk2.config.ConfigSupport.apply(ConfigSupport.java:143)
|2022-12-05T01:34:22.885219320Z	at org.jvnet.hk2.config.ConfigSupport.apply(ConfigSupport.java:121)
|2022-12-05T01:34:22.885223406Z	at com.sun.enterprise.config.modularity.parser.ConfigurationParser.parseAndSetConfigBean(ConfigurationParser.java:128)
|2022-12-05T01:34:22.885227453Z	at com.sun.enterprise.config.modularity.ConfigBeanInstaller.applyConfigIfNeeded(ConfigBeanInstaller.java:113)
|2022-12-05T01:34:22.885231637Z	at com.sun.enterprise.config.modularity.ConfigBeanInstaller.postConstruct(ConfigBeanInstaller.java:94)
|2022-12-05T01:34:22.885235657Z	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:303)
|2022-12-05T01:34:22.885239340Z	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
|2022-12-05T01:34:22.885243075Z	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
|2022-12-05T01:34:22.885246819Z	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59)
|2022-12-05T01:34:22.885250471Z	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47)
|2022-12-05T01:34:22.885254163Z	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74)
|2022-12-05T01:34:22.885257938Z	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
|2022-12-05T01:34:22.885261688Z	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131)
|2022-12-05T01:34:22.885265439Z	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176)
|2022-12-05T01:34:22.885269060Z	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98)
|2022-12-05T01:34:22.885276358Z	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
|2022-12-05T01:34:22.885280097Z	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
|2022-12-05T01:34:22.885283841Z	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:680)
|2022-12-05T01:34:22.885294882Z	at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:54)
|2022-12-05T01:34:22.885300274Z	at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:188)
|2022-12-05T01:34:22.885304229Z	at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:211)
|2022-12-05T01:34:22.885308038Z	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:334)
|2022-12-05T01:34:22.885311676Z	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
|2022-12-05T01:34:22.885315349Z	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59)
|2022-12-05T01:34:22.885319016Z	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47)
|2022-12-05T01:34:22.885322787Z	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74)
|2022-12-05T01:34:22.885326483Z	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
|2022-12-05T01:34:22.885330158Z	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131)
|2022-12-05T01:34:22.885333921Z	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176)
|2022-12-05T01:34:22.885337643Z	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98)
|2022-12-05T01:34:22.885341351Z	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
|2022-12-05T01:34:22.885344973Z	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
|2022-12-05T01:34:22.885348630Z	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
|2022-12-05T01:34:22.885352435Z	at com.sun.enterprise.naming.impl.NamedNamingObjectManager.tryNamedProxies(NamedNamingObjectManager.java:127)
|2022-12-05T01:34:22.885356164Z	at com.sun.enterprise.naming.impl.JavaURLContext.lookup(JavaURLContext.java:164)
|2022-12-05T01:34:22.885359877Z	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:476)
|2022-12-05T01:34:22.885363596Z	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:442)
|2022-12-05T01:34:22.885367359Z	at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
|2022-12-05T01:34:22.885371011Z	at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
|2022-12-05T01:34:22.885374707Z	at fish.payara.microprofile.faulttolerance.service.FaultToleranceServiceImpl.postConstruct(FaultToleranceServiceImpl.java:120)
|2022-12-05T01:34:22.885378461Z	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethod)
|2022-12-05T01:34:22.885382261Z	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
|2022-12-05T01:34:22.885386005Z	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
|2022-12-05T01:34:22.885392229Z	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
|2022-12-05T01:34:22.885396628Z	at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1268)
|2022-12-05T01:34:22.885400531Z	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:309)
|2022-12-05T01:34:22.885404260Z	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
|2022-12-05T01:34:22.885407897Z	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
|2022-12-05T01:34:22.885411560Z	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
|2022-12-05T01:34:22.885415321Z	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
|2022-12-05T01:34:22.885419028Z	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
|2022-12-05T01:34:22.885422682Z	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
|2022-12-05T01:34:22.885426376Z	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
|2022-12-05T01:34:22.885430097Z	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
|2022-12-05T01:34:22.885433828Z	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
|2022-12-05T01:34:22.885437574Z	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
|2022-12-05T01:34:22.885441349Z	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
|2022-12-05T01:34:22.885445120Z	at java.base/java.lang.Thread.run(Thread.java:829)
|2022-12-05T01:34:22.885448879ZCausedby:java.util.ConcurrentModificationException
|2022-12-05T01:34:22.885452499Z	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
|2022-12-05T01:34:22.885456231Z	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
|2022-12-05T01:34:22.885459865Z	at org.jvnet.hk2.config.Transactions.addTransaction(Transactions.java:512)
|2022-12-05T01:34:22.885463508Z	at org.jvnet.hk2.config.Transactions.addTransaction(Transactions.java:497)
|2022-12-05T01:34:22.885467185Z	at org.jvnet.hk2.config.Transaction.commit(Transaction.java:125)
|2022-12-05T01:34:22.885470899Z	at org.jvnet.hk2.config.ConfigSupport._apply(ConfigSupport.java:186)
|2022-12-05T01:34:22.885474634Z	...58more
|2022-12-05T01:34:22.885478261Z|#]
```

Example B (also array list concurrent modification exception, [here](https://github.com/payara/Payara/blob/b263fb8b7eab9fee664cd8b0a9457ed3dc96cdd0/appserver/transaction/jta/src/main/java/com/sun/enterprise/transaction/JavaEETransactionManagerSimplified.java#L1489)):
```
[0m_ThreadID=376;_ThreadName=__ejb-thread-pool1;_TimeMillis=1670012995036;_LevelValue=1000;|
2022-12-02T20:29:55.037299962Z   DTX5001:Exception in enlistComponentResources.
2022-12-02T20:29:55.037305193Z java.util.ConcurrentModificationException
2022-12-02T20:29:55.037309188Z 	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
2022-12-02T20:29:55.037313280Z 	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
2022-12-02T20:29:55.037317366Z 	at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.enlistComponentResources(JavaEETransactionManagerSimplified.java:1488)
2022-12-02T20:29:55.037321565Z 	at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.postInvoke(JavaEETransactionManagerSimplified.java:740)
2022-12-02T20:29:55.037325457Z 	at com.sun.enterprise.transaction.TransactionInvocationHandler.beforePostInvoke(TransactionInvocationHandler.java:88)
2022-12-02T20:29:55.037329323Z 	at org.glassfish.api.invocation.InvocationManagerImpl$ListComponentInvocationHandler.lambda$beforePostInvoke$2(InvocationManagerImpl.java:430)
2022-12-02T20:29:55.037333303Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2022-12-02T20:29:55.037337054Z 	at org.glassfish.api.invocation.InvocationManagerImpl$ListComponentInvocationHandler.beforePostInvoke(InvocationManagerImpl.java:430)
2022-12-02T20:29:55.037346356Z 	at org.glassfish.api.invocation.InvocationManagerImpl.postInvoke(InvocationManagerImpl.java:198)
2022-12-02T20:29:55.037350757Z 	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2126)
2022-12-02T20:29:55.037354631Z 	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2104)
2022-12-02T20:29:55.037358388Z 	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
2022-12-02T20:29:55.037362117Z 	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
2022-12-02T20:29:55.037365902Z 	at com.sun.proxy.$Proxy565.getSessionBySessionId(Unknown Source)
...
2022-12-02T20:29:55.037373677Z 	at jdk.internal.reflect.GeneratedMethodAccessor987.invoke(Unknown Source)
2022-12-02T20:29:55.037378222Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-12-02T20:29:55.037382262Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-12-02T20:29:55.037385995Z 	at org.jboss.weld.util.reflection.Reflections.invokeAndUnwrap(Reflections.java:410)
2022-12-02T20:29:55.037389788Z 	at org.jboss.weld.module.ejb.EnterpriseBeanProxyMethodHandler.invoke(EnterpriseBeanProxyMethodHandler.java:134)
2022-12-02T20:29:55.037405892Z 	at org.jboss.weld.bean.proxy.EnterpriseTargetBeanInstance.invoke(EnterpriseTargetBeanInstance.java:56)
2022-12-02T20:29:55.037409926Z 	at org.jboss.weld.module.ejb.InjectionPointPropagatingEnterpriseTargetBeanInstance.invoke(InjectionPointPropagatingEnterpriseTargetBeanInstance.java:68)
2022-12-02T20:29:55.037413952Z 	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
...
...
...
...
2022-12-02T20:29:55.037433307Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
...
...
...
2022-12-02T20:29:55.037450367Z 	at jdk.internal.reflect.GeneratedMethodAccessor1196.invoke(Unknown Source)
2022-12-02T20:29:55.037454440Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-12-02T20:29:55.037458296Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-12-02T20:29:55.037461961Z 	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
2022-12-02T20:29:55.037465806Z 	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)
2022-12-02T20:29:55.037469600Z 	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4835)
2022-12-02T20:29:55.037473841Z 	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)
2022-12-02T20:29:55.037477813Z 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
2022-12-02T20:29:55.037481685Z 	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
2022-12-02T20:29:55.037485420Z 	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
2022-12-02T20:29:55.037489199Z 	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
2022-12-02T20:29:55.037493091Z 	at jdk.internal.reflect.GeneratedMethodAccessor492.invoke(Unknown Source)
2022-12-02T20:29:55.037496783Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-12-02T20:29:55.037503926Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-12-02T20:29:55.037507645Z 	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
2022-12-02T20:29:55.037511546Z 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
2022-12-02T20:29:55.037515320Z 	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
2022-12-02T20:29:55.037519049Z 	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:81)
2022-12-02T20:29:55.037522855Z 	at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
2022-12-02T20:29:55.037526662Z 	at jdk.internal.reflect.GeneratedMethodAccessor471.invoke(Unknown Source)
2022-12-02T20:29:55.037530353Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-12-02T20:29:55.037534116Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-12-02T20:29:55.037537814Z 	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
2022-12-02T20:29:55.037541654Z 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
2022-12-02T20:29:55.037545375Z 	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)
2022-12-02T20:29:55.037551739Z 	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4807)
2022-12-02T20:29:55.037555753Z 	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4795)
2022-12-02T20:29:55.037559601Z 	at com.sun.ejb.containers.EjbAsyncTask.call(EjbAsyncTask.java:101)
2022-12-02T20:29:55.037563243Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-12-02T20:29:55.037567333Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-12-02T20:29:55.037571097Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-12-02T20:29:55.037574874Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-12-02T20:29:55.037578542Z |#]
```
