### ISSUE TITLE
Bug Report: Get NPE when trying to use OpenIdAuthenticationMechanismDefinition/FISH-7201

### ISSUE THREAD

**Issue by arrenping** [payara/Payara#6159]
### Brief Summary

I'm trying to migrate my codes from `fish.payara.security.annotations.OpenIdAuthenticationDefinition` to `jakarta.security.enterprise.authentication.mechanism.http.OpenIdAuthenticationMechanismDefinition`.

The annotation declaration is as follows:
1. From `OpenIdAuthenticationDefinition` of Payara private API
```java
@OpenIdAuthenticationDefinition(
        providerURI = "#{openIdContext.provider}",
        clientId = "#{openIdContext.clientId}",
        clientSecret = "#{openIdContext.clientSecret}",
        redirectURI = "${baseURL}/callback",
        claimsDefinition = @ClaimsDefinition(callerGroupsClaim = "#{openIdContext.callerGroups}")
)
```
2. To `OpenIdAuthenticationMechanismDefinition` of Jakarta EE 10
```java
@OpenIdAuthenticationMechanismDefinition(
        providerURI = "${openIdContext.provider}",
        clientId = "${openIdContext.clientId}",
        clientSecret = "${openIdContext.clientSecret}",
        redirectURI = "${baseURL}/callback",
        claimsDefinition = @ClaimsDefinition(callerGroupsClaim = "#{openIdContext.callerGroups}")
)
```

### Expected Outcome

These two annotations I think should have the same behavior.

### Current Outcome

Get a NPE exceptions as follows:

```
[2023-01-20T23:44:49.366+0800] [] [警告] [] [javax.enterprise.system.container.web.com.sun.web.security] [tid: _ThreadID=76 _ThreadName=http-thread-pool::http-listener(2)] [timeMillis: 1674229489366] [levelValue: 900] [[
  JASPIC: http msg authentication fail
java.lang.NullPointerException: Cannot invoke "com.nimbusds.jwt.JWTClaimsSet.getClaims()" because "jwtClaimsSet" is null
	at org.glassfish.soteria.mechanisms.openid.domain.AccessTokenImpl.<init>(AccessTokenImpl.java:64)
	at org.glassfish.soteria.mechanisms.openid.OpenIdCredential.<init>(OpenIdCredential.java:58)
	at org.glassfish.soteria.mechanisms.OpenIdAuthenticationMechanism.validateAuthorizationCode(OpenIdAuthenticationMechanism.java:359)
	at org.glassfish.soteria.mechanisms.OpenIdAuthenticationMechanism.authenticate(OpenIdAuthenticationMechanism.java:278)
	at org.glassfish.soteria.mechanisms.OpenIdAuthenticationMechanism.validateRequest(OpenIdAuthenticationMechanism.java:176)
	at org.glassfish.soteria.mechanisms.OpenIdAuthenticationMechanism$Proxy$_$$_WeldClientProxy.validateRequest(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
	at org.jboss.weld.generated.proxies.security.enterprise.authentication.mechanism.http.HttpAuthenticationMechanism$2070706998$Proxy$_$$_WeldClientProxy.validateRequest(Unknown Source)
	at org.glassfish.soteria.mechanisms.jaspic.HttpBridgeServerAuthModule.validateRequest(HttpBridgeServerAuthModule.java:114)
	at com.sun.jaspic.config.factory.DefaultServerAuthContext.validateRequest(DefaultServerAuthContext.java:52)
	at com.sun.web.security.realmadapter.JaspicRealm.validateRequest(JaspicRealm.java:391)
	at com.sun.web.security.realmadapter.JaspicRealm.validateRequest(JaspicRealm.java:358)
	at com.sun.web.security.realmadapter.JaspicRealm.validateRequest(JaspicRealm.java:181)
	at com.sun.web.security.RealmAdapter.invokeAuthenticateDelegate(RealmAdapter.java:487)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:468)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:726)
	at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:581)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:372)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:239)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:833)
]]
```

### Reproducer

Any open id service providers response an opaque access token should hit this issue.

### Operating System

macOS 13.1

### JDK Version

Zulu17.38+21-CA (build 17.0.5+8-LTS)

### Payara Distribution

Payara Micro

**Comment by arrenping** [comment]
I checked the source code in [soteria](https://github.com/eclipse-ee4j/soteria), the line `this.claims = jwtClaimsSet.getClaims()` throws the NPE.

```java
try {
    this.tokenJWT = JWTParser.parse(token);
    jwtClaimsSet = tokenJWT.getJWTClaimsSet();
    this.claims = jwtClaimsSet.getClaims();
} catch (ParseException ex) {
    // Access token doesn't need to be JWT at all
}
```
https://github.com/eclipse-ee4j/soteria/blob/24a427c19f3600e1738946c2d46ec904842e0549/impl/src/main/java/org/glassfish/soteria/mechanisms/openid/domain/AccessTokenImpl.java#L64

---
I also check the AccessTokenImpl.java in Payara, there is a little different, the implementation in Payara for `@ OpenIdAuthenticationDefinition` would not throw the NPE
```java
try {
    this.tokenJWT = JWTParser.parse(token);
    jwtClaimsSet = tokenJWT.getJWTClaimsSet();
    this.claims = jwtClaimsSet == null ? null : jwtClaimsSet.getClaims();
} catch (ParseException ex) {
    // Access token doesn't need to be JWT at all
}
```
https://github.com/payara/ecosystem-security-connectors/blob/73c4436fddd581b6f64d83c2f03dbba188006a72/openid/src/main/java/fish/payara/security/openid/domain/AccessTokenImpl.java#L90

**Comment by smillidge** [comment]
@shub8968 looks like we need to patch Soteria can you raise an internal ticket for it?

**Comment by shub8968** [comment]
Hi @arrenping,

I have escalated this issue with an internal JIRA F`ISH-7202`.

**Comment by arrenping** [comment]
> Hi @arrenping,
> 
> I have escalated this issue with an internal JIRA `FISH-7201`.

Thank you👍👍👍
