### ISSUE TITLE
Bug Report: Creating DCOM node failse

### ISSUE THREAD

**Issue by mirozitnansky** [payara/Payara#6251]
### Brief Summary

When creating new node using admin portal, after setting all necessary data, I will get error 

> An error has occurred remote failure: The j-interop and Jcifs libraries are not available.  To use native Windows components, the j-interop-repackaged.jar JAR file is required: This JAR file is available in all GlassFish Server distributions. The libraries in this JAR file are released under the GNU Lesser General Public License (LGPL).
 An error has occurred
remote failure: The j-interop and Jcifs libraries are not available. To use native Windows components, the j-interop-repackaged.jar JAR file is required: This JAR file is available in all GlassFish Server distributions. The libraries in this JAR file are released under the GNU Lesser General Public License (LGPL).

It seems that payara is missing libraries needed to be able to create DCOM node. Payara installation is already created on destination system.
Libraries mentioned in error are  not longer mantained.

How one should proceed when running environment for deployment groups is windows 11.

### Expected Outcome

Node sucessfully created.

### Current Outcome

Error on node creation.

### Reproducer

Using hyper-v windows eval instalation as vitual machine for node creation.

### Operating System

Windows 11 pro

### JDK Version

Zulu 11

### Payara Distribution

Payara Server Full Profile

**Comment by felixif** [comment]
Hello @mirozitnansky,

I am currently checking the DCOM nodes issue. Our recommendation, for now, would be to try OpenSSH (officially supported by Microsoft:  [Getting started with OpenSSH](https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse?tabs=gui), and use SSH nodes rather than DCOM.

**Comment by mirozitnansky** [comment]
Hello @felixif,

already tried that, after installing https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v9.2.0.0p1-Beta on node machine, node is created but creating instance fails with error

```[2023-04-12T13:26:06.914+0200] [Payara 6.2023.3] [INFO] [] [javax.enterprise.system.core] [tid: _ThreadID=379 _ThreadName=admin-thread-pool::admin-listener(13)] [timeMillis: 1681298766914] [levelValue: 800] [[
  Command _validate-das-options executed successfully.]]

[2023-04-12T13:26:08.304+0200] [Payara 6.2023.3] [INFO] [] [javax.enterprise.system.core] [tid: _ThreadID=379 _ThreadName=admin-thread-pool::admin-listener(13)] [timeMillis: 1681298768304] [levelValue: 800] [[
  Command _create-instance-filesystem executed successfully.]]

[2023-04-12T13:26:08.792+0200] [Payara 6.2023.3] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=379 _ThreadName=admin-thread-pool::admin-listener(13)] [timeMillis: 1681298768792] [levelValue: 1000] [[
  Successfully created instance kioks-inst1 in the DAS configuration, but failed to install configuration files for the instance on node kiosk during bootstrap.

SSH configuration information 

 Additional failure info: com.sun.enterprise.v3.admin.cluster.SecureAdminBootstrapHelper$BootstrapException: com.trilead.ssh2.SFTPException: Failure (SSH_FX_FAILURE: An error occurred, but no specific error code exists to describe the failure.).
com.sun.enterprise.v3.admin.cluster.SecureAdminBootstrapHelper$BootstrapException: com.sun.enterprise.v3.admin.cluster.SecureAdminBootstrapHelper$BootstrapException: com.trilead.ssh2.SFTPException: Failure (SSH_FX_FAILURE: An error occurred, but no specific error code exists to describe the failure.)
	at com.sun.enterprise.v3.admin.cluster.SecureAdminBootstrapHelper.bootstrapInstance(SecureAdminBootstrapHelper.java:205)
	at com.sun.enterprise.v3.admin.cluster.CreateInstanceCommand.bootstrapSecureAdminRemotely(CreateInstanceCommand.java:415)
	at com.sun.enterprise.v3.admin.cluster.CreateInstanceCommand.createInstanceFilesystem(CreateInstanceCommand.java:507)
	at com.sun.enterprise.v3.admin.cluster.CreateInstanceCommand.execute(CreateInstanceCommand.java:280)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:552)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:551)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:582)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:574)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:573)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1497)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1879)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1755)
	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:272)
	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:240)
	at org.glassfish.admin.rest.resources.TemplateExecCommand.executeCommandLegacyFormat(TemplateExecCommand.java:156)
	at org.glassfish.admin.rest.resources.TemplateCommandPostResource.processPostLegacyFormat(TemplateCommandPostResource.java:100)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:367)
	at org.glassfish.admin.rest.adapter.RestAdapter$2.service(RestAdapter.java:335)
	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:189)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:193)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:193)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.sun.enterprise.v3.admin.cluster.SecureAdminBootstrapHelper$BootstrapException: com.trilead.ssh2.SFTPException: Failure (SSH_FX_FAILURE: An error occurred, but no specific error code exists to describe the failure.)
	at com.sun.enterprise.v3.admin.cluster.SecureAdminBootstrapHelper$SSHHelper.backdateInstanceDomainXML(SecureAdminBootstrapHelper.java:393)
	at com.sun.enterprise.v3.admin.cluster.SecureAdminBootstrapHelper.bootstrapInstance(SecureAdminBootstrapHelper.java:202)
	... 76 more
Caused by: com.trilead.ssh2.SFTPException: Failure (SSH_FX_FAILURE: An error occurred, but no specific error code exists to describe the failure.)
	at com.trilead.ssh2.SFTPv3Client.expectStatusOKMessage(SFTPv3Client.java:555)
	at com.trilead.ssh2.SFTPv3Client.setstat(SFTPv3Client.java:583)
	at com.sun.enterprise.v3.admin.cluster.SecureAdminBootstrapHelper$SSHHelper.setLastModified(SecureAdminBootstrapHelper.java:405)
	at com.sun.enterprise.v3.admin.cluster.SecureAdminBootstrapHelper$SSHHelper.backdateInstanceDomainXML(SecureAdminBootstrapHelper.java:390)
	... 77 more
]]

[2023-04-12T13:26:08.795+0200] [Payara 6.2023.3] [WARNING] [] [org.glassfish.admingui] [tid: _ThreadID=371 _ThreadName=admin-thread-pool::admin-listener(8)] [timeMillis: 1681298768795] [levelValue: 900] [[
  RestResponse.getResponse() gives WARNING.  endpoint = 'https://localhost:4848/management/domain/create-instance'; attrs = '{node=kiosk-node1, name=kioks-inst1, deploymentgroup=null}']]```

It seems to be some kind of incompatibility between com.trilead.ssh2 client and windows openssh implementation.
Will try to dig deeper into into it.

**Comment by mirozitnansky** [comment]
My error is already identified and reported https://github.com/payara/Payara/issues/3700#issuecomment-1456047960
Date on domain.xml is not set
![image](https://user-images.githubusercontent.com/22233613/231808051-9e1683ff-62b3-4317-acc5-8311a12940db.png)

**Comment by mirozitnansky** [comment]
Hello @felixif , any comments on this issue? Do you plan to fix it, or will DCOM be removed from payara?

**Comment by felixif** [comment]
Hello @mirozitnansky, apologies for not replying to the issue earlier.

My initial reply is not entirely accurate. As you found out from[ https://github.com/payara/Payara/issues/3700](url), the only supported ssh node is Cygwin's OpenSSH and not Windows' OpenSSH. DCOM nodes do not work on Payara Community, but is available for Payara Enterprise. I raised a request to the Product Management team with the internal code: `PROD-170`, to deprecate the DCOM nodes on Payara Community.
