### ISSUE TITLE
Bug Report: ConnectionLeakDetector missing translation key and default value is broken

### ISSUE THREAD

**Issue by drame1499** [payara/Payara#6457]
### Brief Summary

When the connection `com.sun.enterprise.resource.pool.ConnectionLeakDetector ` identifies a possible leak, it tries to log the stack trace with a presceding message.
But this ultimately results in this: 
`  java.lang.IllegalArgumentException: can't parse argument number:  PoolInfo : (name=java:app/post-gre-sql_ppcs_postgresPool)
	at java.base/java.text.MessageFormat.makeFormat(MessageFormat.java:1454)
	at java.base/java.text.MessageFormat.applyPattern(MessageFormat.java:492)
	at java.base/java.text.MessageFormat.<init>(MessageFormat.java:371)
	at com.sun.enterprise.util.i18n.StringManagerBase.getStringWithDefault(StringManagerBase.java:205)
	at com.sun.enterprise.resource.pool.ConnectionLeakDetector.printConnectionLeakTrace(ConnectionLeakDetector.java:181)
	at com.sun.enterprise.resource.pool.ConnectionLeakDetector.potentialConnectionLeakFound(ConnectionLeakDetector.java:161)
	at com.sun.enterprise.resource.pool.ConnectionLeakDetector$ConnectionLeakTask.run(ConnectionLeakDetector.java:226)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
Caused by: java.lang.NumberFormatException: For input string: " PoolInfo : (name=java:app/post-gre-sql_ppcs_postgresPool)"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:654)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at java.base/java.text.MessageFormat.makeFormat(MessageFormat.java:1452)
	... 8 more
]]`

This is because firstly the message string "potential.connection.leak.msg" is missing.
Additionally the supplied default value instead of using {0} for the supplied parameter, it already includes the `" + connectionPoolInfo + "`.
In our case the connecion pool info is printed as { PoolInfo : (name=java:app/post-gre-sql_ppcs_postgresPool), (applicationName=customer-server-1.23.03) }.
This is then fed into new MessageFormat() which tries to parse everythin between the two {} as a numerial parameter and fails.
This causes the actual stack trace to never get printed. 

### Expected Outcome

The correctly formated message followed by the stack trace.

### Current Outcome

NumberFormatException

### Reproducer

This can be reproduced by enabling connection leak detection through glassfish-resource.xml and not closing a UnitOfWork or Connection in an application. 

### Operating System

Windows 10 and Ubuntu 22.04.3 LTS

### JDK Version

Adoptium jdk-17.0.5.8-hotspot

### Payara Distribution

Payara Server Full Profile

**Comment by artur-mal** [comment]
Hello @drame1499 

I apologise for not replying to you earlier.

Could you please provide a simple-to-follow scenario on how to reproduce this on the latest version?
**A reproducer should follow the SSCCE rules: http://www.sscce.org/.** Finding and fixing the cause would be much easier with your help.

Thank you,
Artur
