### ISSUE TITLE
Bug Report: Weird exception, JTA expected on my Application Managed Transaction MapStore

### ISSUE THREAD

**Issue by cidylong** [payara/Payara#6467]
### Brief Summary

I'm trying to migrate my Payara-5 application to Payara-6. I developed a set of customer MapStore implementations to handle my Hazelcast IMaps to backend Postgresql database.

I developed all MapStore implementations by using well configured JDBC datasources and my persistence.xml as:

    <persistence-unit name="PG15_OZSSC_NONJTAPU" transaction-type="RESOURCE_LOCAL">
        <provider>org.eclipse.persistence.jpa.PersistenceProvider</provider>
        <non-jta-data-source>jdbc/PG15_ozssc_150</non-jta-data-source>
        <class>com.longz.thss.lib.jpa.jpa.entity.Abn</class> 
        .......

my MapStore as:

    public class PaymentitemMapStore implements MapStore<String, Paymentitem>, MapLoaderLifecycleSupport, Serializable {
        .......
        @PersistenceUnit(unitName = PU_NAME)
        private EntityManagerFactory emf;
        @PersistenceContext(unitName = PU_NAME)
        private EntityManager em;
        ........
        @Override
       public synchronized void store(String s, Paymentitem entity) {
        em.getTransaction().begin();
        storeEntityToDB(entity);
        em.flush();
        em.getTransaction().commit();
    }
    .......

I put the MapStore into package and develop JSF web application to access Hazelcast map.

### Expected Outcome

web application should be deployed properly and working well.

### Current Outcome

When I tried to deploy my web application to Payara server. Payara throws:

[2023-10-25T18:08:28.355+1100] [Payara 6.2023.10] [SEVERE] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=344 _ThreadName=admin-thread-pool::admin-listener(7)] [timeMillis: 1698217708355] [levelValue: 1000] [[
  Exception during lifecycle processing
java.lang.RuntimeException: The persistence-context-ref-name [com.longz.thss.lib.jpa.jpa.store.PaymentitemMapStore/em] in module [OzsscWebApp] resolves to a persistence unit called [PG15_OZSSC_NONJTAPU] which is of type RESOURCE_LOCAL. Only persistence units with transaction type JTA can be used as a container managed entity manager. Please verify your application.
	at com.sun.enterprise.deployment.BundleDescriptor.findReferencedPUViaEMRef(BundleDescriptor.java:726)
	at com.sun.enterprise.deployment.BundleDescriptor.findReferencedPUsViaPCRefs(BundleDescriptor.java:707)
	at org.glassfish.web.deployment.descriptor.WebBundleDescriptorImpl.findReferencedPUs(WebBundleDescriptorImpl.java:1190)
	at org.glassfish.persistence.jpa.JPADeployer.createEMFs(JPADeployer.java:201)
	at org.glassfish.persistence.jpa.JPADeployer.prepare(JPADeployer.java:183)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.prepareModule(ApplicationLifecycle.java:1255)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:514)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:570)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:552)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:376)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:551)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:582)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:574)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:376)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:573)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1497)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1879)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1755)
	at org.glassfish.admin.rest.resources.admin.CommandResource.executeCommand(CommandResource.java:409)
	at org.glassfish.admin.rest.resources.admin.CommandResource.execCommandSimpInMultOut(CommandResource.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:367)
	at org.glassfish.admin.rest.adapter.JerseyContainerCommandService$3.service(JerseyContainerCommandService.java:179)
	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:189)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:193)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:193)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:833)
]]

[2023-10-25T18:08:28.375+1100] [Payara 6.2023.10] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=344 _ThreadName=admin-thread-pool::admin-listener(7)] [timeMillis: 1698217708375] [levelValue: 1000] [[
  Exception while preparing the app : The persistence-context-ref-name [com.longz.thss.lib.jpa.jpa.store.PaymentitemMapStore/em] in module [OzsscWebApp] resolves to a persistence unit called [PG15_OZSSC_NONJTAPU] which is of type RESOURCE_LOCAL. Only persistence units with transaction type JTA can be used as a container managed entity manager. Please verify your application.]]

### Reproducer

This issue maybe very hard to reproduce, When I deploy it to Payara most time will throws [com.longz.thss.lib.jpa.jpa.store.PaymentitemMapStore/em] error, but some time throws other MapStore/em as well

### Operating System

Rocky Linux 9.1

### JDK Version

Oracle JDK 17.0.7

### Payara Distribution

Payara Server Full Profile

**Comment by cidylong** [comment]
I am using Payara-6.2023.10 for testing.

**Comment by Elifzeynepedman** [comment]
Hi @cidylong,

Could you please provide a simple-to-follow scenario on how to reproduce this on the latest version? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. It will greatly help us to find the cause and fix it.

Thank you,
Elif

**Comment by cidylong** [comment]
@Elifzeynepedman ， I will create a simple individual GitHub project to test it. My original project is too big. There are about 7 sub-module in it.

Once I created it, I will post it to you.

**Comment by cidylong** [comment]
@Elifzeynepedman , It is very hard to reproduce the rise issue. As you can see from the log file, javax.enterprise.system.core is rising the problem. But seems there is old enterprise (module) from Javax namespace is still in using. 

it is very confused.

I have created a simple new application project that not use application managed transaction (which cause this issue), as this issue cause me can't deploy any web application at all.

But the newly developed application (using JTA persistence unit) not write database at all.

Please find the new issue that I just raised. #6470

**Comment by Elifzeynepedman** [comment]
Hi @cidylong,

I have taken a look at your reproducer but the reproducer you provided needs to be self-contained and needs to include everything including the database itself. For this reason being, could you please provide a complete reproducer?  A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/


Thank you,
Elif

**Comment by cidylong** [comment]
@Elifzeynepedman ，Database schema was dumped to sql file in my GitHub project and stated in Development guide.
https://github.com/cidylong/JTAMapStoreEJB was developed under NetBeans 19 with maven. It be able to compile and deploy properly under Payara 6.2023.10.

As you know in Jakarta EE 9 or newer,  to use @Schedule, XA Datasource and JTA Transaction type must be used, otherwise, LOCAL_RESOURCE configuration (Application managed transaction in my custom MapStore implementation) will works fine in my previous version (Payara 5).

Problem is still here, my test result is fully confirmed issue #6450 existing.

Actually, There are quite lots implementation not working well or not tested in Payara 6
1. @PersistenceContext not work at all.
2. JPA persistence.xml loader (load entity manager factory by Jakarta.persistence programmatically), not load JPA version 3 properly, for example, not recognise JTA datasource and set it up properly.
3.  jakarta.persistence.jtaDataSource not implemented at all, datasource was loaded to com.sun.gjc.spi.jdbc40.DataSource40, it can't be cast to jakarta.persistence.jtaDataSource or javax.sql.XADataSource

Above issues cause Payara 6 not support JTA Entity Manager to handle Container Managed Transaction at all. As result, Payara 6 not support @Schedule or @Timer thing.

**Comment by Elifzeynepedman** [comment]
Hi @cidylong,

We regret to inform you that due to the complexity and specificity of your issue, particularly with your custom implementation of a Hazelcast configuration object, we are currently unable to provide the level of assistance you require.

To better assist you, we kindly request one of the following options:

1. **Fully Self-Contained Reproducer:** Please provide a complete, self-contained code sample that replicates the error you are experiencing. This will enable us to understand the context and pinpoint the issue more effectively.
2. **Upgrade to Enterprise:** If creating a reproducer is not feasible, we recommend considering an upgrade to our enterprise-level service. This upgrade would provide you with more comprehensive support and resources tailored to complex and custom implementations like yours.

Thank you,
Elif
