### ISSUE TITLE
java.lang.UnsupportedClassVersionError: com/sun/xml/ws/transport/Headers : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by lucioalmeida** [payara/Payara#675]
This error occurred on Web Service call (JAX-WS) using JDK 1.7. If you run on JDK 1.8 this erro not occurred.

Stack:
  java.lang.UnsupportedClassVersionError: com/sun/xml/ws/transport/Headers : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2279)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1501)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:75)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1955)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.sun.xml.ws.client.RequestContext.mergeRequestHeaders(RequestContext.java:337)
	at com.sun.xml.ws.client.RequestContext.fill(RequestContext.java:301)
	at com.sun.xml.ws.client.Stub.configureRequestPacket(Stub.java:492)
	at com.sun.xml.ws.client.Stub.process(Stub.java:450)
	at com.sun.xml.ws.client.sei.SEIStub.doProcess(SEIStub.java:191)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:108)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:92)
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:161)

I replace webservices-osgi.jar in modules folder to 
https://github.com/payara/Payara_PatchedProjects/blob/master/org/glassfish/metro/webservices-osgi/2.3.2-b608.payara-p3/webservices-osgi-2.3.2-b608.payara-p3.jar and this error not occurred more.

I think it was compiled on JDK 1.8 so the error occurred.

Att,
Lucio Costa de Almeida
Developer

**Comment by smillidge** [comment]
Thanks for the heads up the latest Jenkins build http://www.payara.fish/upstream_builds is using webservices-osgi-2.3.2-b608.payara-p3.jar.

**Comment by smillidge** [comment]
Resolved in 4.1.1.161.1
