### ISSUE TITLE
Bug Report: Seems Payara Micro 6.2024.6 (but not Server) is broken (to be investigated where exactly) comparing to Payara Micro 6.2024.5/FISH-9110

### ISSUE THREAD

**Issue by AndrewG10i** [payara/Payara#6779]
### Brief Summary

After upgrading Payara Micro 6.2024.5 to 6.2024.6 our app gets some weird behavior. We currently do not have reproducer, as no specific error is logged in the error log at the moment error occurs. Just after 4th of 5th open page app stops responding properly to page navigation and the shown below error start appearing.

It seems to me that something is happening with User Session, as user gets logged out or not able to navigate to other pages or navigate to the home page.

Reverting back to Payara Micro 6.2024.5 resolves the issue. Also app works fine on Payara Server (full) 6.2024.6, issue only appears when deployed on Payara Micro 6.2024.6.

At this moment reporting this issues as is, I will try to provide more details in case we are able to get minimal reproducer, but cannot promise that it will be quick due to tough schedule.

### Expected Outcome

No error.

### Current Outcome

After navigating over few pages user may get logged out or pages are not open and error log start reporting some weird errors like:
```
[2024-06-21 17:14:40] [WARNING] [com.sun.faces.lifecycle.InvokeApplicationPhase execute]
 Cannot invoke "java.util.Map.put(Object, Object)" because "this.innerMap" is null
java.lang.NullPointerException: Cannot invoke "java.util.Map.put(Object, Object)" because "this.innerMap" is null
	at com.sun.faces.context.flash.ELFlash$PreviousNextFlashInfoManager.initializeBaseCase(ELFlash.java:1226)
	at com.sun.faces.context.flash.ELFlash.getCurrentFlashManager(ELFlash.java:1117)
	at com.sun.faces.context.flash.ELFlash.loggingGetPhaseMapForWriting(ELFlash.java:802)
	at com.sun.faces.context.flash.ELFlash.setKeepMessages(ELFlash.java:318)
	at com.sun.faces.application.NavigationHandlerImpl.handleNavigation(NavigationHandlerImpl.java:235)
	at com.sun.faces.application.NavigationHandlerImpl.handleNavigation(NavigationHandlerImpl.java:200)
	at com.sun.faces.application.ActionListenerImpl.invokeNavigationHandling(ActionListenerImpl.java:93)
	at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:62)
	at jakarta.faces.component.UIViewAction.broadcast(UIViewAction.java:506)
	at jakarta.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:858)
	at jakarta.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1332)
	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:56)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:159)
	at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:691)
	at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1554)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:83)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211
        ...
```

### Reproducer

Not availbale at this moment - we will try to provide reproducer once have more time for troubleshooting.

### Operating System

Windows and Linux - same behaviour

### JDK Version

Zulu JDK 17 - latest version availbale

### Payara Distribution

Payara Micro

**Comment by felixif** [comment]
Hello @AndrewG10i,

Thank you for your bug report! Unfortunately, without a minimal reproducer, I cannot verify that the issue occurs and escalate it to be solved. If you have time to provide a reproducer, I would be happy to assist.

Best regards,
Felix

**Comment by AndrewG10i** [comment]
The same issue repeats with Payara Micro 6.2024.7 as well (but still Payara Micro 6.2024.5 works fine). I am planning to work on reproducer during next 2-3 weeks. Thanks!

**Comment by AndrewG10i** [comment]
Hello!

Reproducer was published here:
[https://github.com/AndrewG10i/jakartaFacesTestApp/](https://github.com/AndrewG10i/jakartaFacesTestApp/)

Steps to reproduce the issue:
1) Click on any of the availbale records
2) On the new page click the Delete button
3) You can see errors appearing in console (see the [video recording](https://1drv.ms/v/s!Au5Nx8QxzTDak8wJVVVTRRYnUH9tyA) demonstrating the issue)

NOTE: Issue reproduces only on the Payara Micro 6.2024.6 and 6.2024.7. Payara Micro 6.2024.5 and below, and Payara Server 6.2024.5,6,7 - all work fine.

**Comment by felixif** [comment]
Hello @AndrewG10i,

Thank you very much for the excellent reproducer! I was able to quickly see the problem after testing across the three versions that you mentioned above. I have raised an internal issue, codename `FISH-9110`, and our Platform Development team will analyse and fix the bug.

Thank you very much for your report!

Best regards,
Felix

**Comment by AndrewG10i** [comment]
Hello Payara team! Seem this issue still present even in the recently released version `6.2024.10`. Any chnaces to have it fixed soon as well? As we still forced to stay with `6.2024.5` as result not able to try & test your latest releases and help with stabilizing Enterprise version. ;) Thanks in advance!

**Comment by AndrewG10i** [comment]
> Hello Payara team! Any updates here? Can you pls provide any insights so we try to collaborate on the fix for this issue? Thanks!

Hey Payara guys! Any updates please?

**Comment by AndrewG10i** [comment]
> Hello Payara team! Any updates here? Can you pls provide any insights so we try to collaborate on the fix for this issue? Thanks!

Hey Payara guys (@felixif, @MeroRai, @smillidge)! Any updates please?

**Comment by artur-mal** [comment]
The issue doesn't exist in the latest release.
