### ISSUE TITLE
Fix GLASSFISH-21522 - NullPointerException during WebDirContext.lookupFromJars

### ISSUE THREAD

**Issue by strmer15** [payara/Payara#693]
I just logged an upstream bug for this, details copied more coherently below - https://java.net/jira/browse/GLASSFISH-21522

When my application starts, the ServletContextListener is called and starts up several threads to run in the background. Sometimes it works, and sometimes I get NPEs that keep the application from starting correctly:

```
Caused by: java.lang.NullPointerException
at org.apache.naming.resources.WebDirContext.lookupFromJars(WebDirContext.java:325)
at org.apache.naming.resources.WebDirContext.getAttributes(WebDirContext.java:298)
at org.apache.naming.resources.BaseDirContext.getAttributes(BaseDirContext.java:787)
at org.apache.naming.resources.ProxyDirContext.cacheLoad(ProxyDirContext.java:1533)
at org.apache.naming.resources.ProxyDirContext.cacheLookup(ProxyDirContext.java:1456)
at org.apache.naming.resources.ProxyDirContext.lookup(ProxyDirContext.java:274)
at org.glassfish.web.loader.WebappClassLoader.findResourceInternalFromRepositories(WebappClassLoader.java:2892)
at org.glassfish.web.loader.WebappClassLoader.findResourceInternal(WebappClassLoader.java:2842)
at org.glassfish.web.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2736)
at org.glassfish.web.loader.WebappClassLoader.findClass(WebappClassLoader.java:1194)
at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1750)
at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1633)
```

After extensive debugging with the sources for Glassfish 4.1.1, I found that there are two competing methods inside of appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java:

```
    protected boolean openJARs() {
        if (started && (jarFiles.length > 0)) {
            lastJarAccessed = System.currentTimeMillis();
            if (jarFiles[0] == null) {
                for (int i = 0; i < jarFiles.length; i++) {
                    try {
                        jarFiles[i] = new JarFile(jarRealFiles[i]);
                    } catch (IOException e) {
                        if (logger.isLoggable(Level.FINE)) {
                            logger.log(Level.FINE, "Failed to open JAR", e);
                        }
                        for (int j = 0; j < i; j++) {
                            try {
                                jarFiles[j].close();
                            } catch (Throwable t) { // Ignore }
                            }
                            return false;
                        }
                    }
                }
            }
            return true;
        }
    }
```

```
    public void closeJARs(boolean force) {
        if (jarFiles.length > 0) {
            synchronized (jarFiles) {
                if (force || (System.currentTimeMillis()
                        > (lastJarAccessed + 90000))) {
                    for (int i = 0; i < jarFiles.length; i++) {
                        try {
                            if (jarFiles[i] != null)
                            { jarFiles[i].close(); jarFiles[i] = null; }
                        } catch (IOException e) {
                            if (logger.isLoggable(Level.FINE))
                            { logger.log(Level.FINE, "Failed to close JAR", e); }
                        }
                    }
                }
            }
        }
    }
```

It turns out that closeJARs() is called from appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.start(), at the end of the startup routine:

```
// Close all JARs right away to avoid always opening a peak number
// of files on startup
if (getLoader() instanceof WebappLoader)
{ ((WebappLoader) getLoader()).closeJARs(true); }
```

The obvious problem is that while closeJARs() is being run in the startup thread, the openJARs() method is also being run by the ServletContextListener as it loads classes during its own initialization routines. Since openJARs() is not synchronized on the jarFiles object like closeJARs() is, both methods run concurrently and overwrite the array items, creating an array with 'holes' in it, where some items are null and some are not. Thus, while doing a lookup in WebDirContext.lookupFromJars, we hit a null array item in the jarFiles array and get an NPE.

It seems like the fix for this should be to simply add a 'synchronized' block in openJARs() after the first 'if' check; however, using jarFiles as the lock for all these operations seems like a poor choice, especially because the addJar() and stop() methods also don't synchronize access and change the object reference for the lock. It seems like a different, final Object should be used instead.

**Comment by OndrejM** [comment]
Hi @strmer15, the fix you suggested seems reasonable. Would you mind posting a simplified test application which illustrates the problem? Specifically, code in the ServletContextListener, which starts several threads, would be very helpful. Once we can reproduce the problem reliably enough (probably not 100% time, as it is a race condition), it would be easier to figure out what\s going on and to prove that the problem is fixed.

**Comment by strmer15** [comment]
Ok, I'll see if I can find some time today or tomorrow to pare down our application's startup into something like that - the best way I've found to reproduce is to set breakpoints inside closeJARs and openJARs where the array items are being overwritten; it's pretty easy to see then.

**Comment by strmer15** [comment]
[GlassfishTest.zip](https://github.com/payara/Payara/files/168101/GlassfishTest.zip)

I finally got a test application up and running - you should only need to run 'mvn clean package' to create an EAR file that can be deployed on Payara.  I installed a clean version of 4.1.1.161.1, and used these commands to start it:

(terminal 1) : payara41/glassfish/bin/asadmin start-domain --debug=true --verbose=true domain1

(terminal 2) : mvn clean package
(terminal 2) : payara41/glassfish/bin/asadmin deploy ear/target/test-glassfish-ear.ear

The web app context listener starts up a couple of threads nested within each other and attempts to just load classes like crazy while the glassfish container starts up.  It's difficult to get the NPE to happen without putting breakpoints into closeJARs() and openJARs() at the right time; usually I put a breakpoint into StandardContext.start() at line 6014 to know when the closeJARs() is about to happen, then enable the breakpoints at WebappClassLoader at lines 2048 and 2750.  Even then, sometimes the thread scheduler doesn't interleave the two invocations.

Also, I did just see this exception on one attempt:

```
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:669)
	at java.util.zip.ZipFile.getEntry(ZipFile.java:309)
	at java.util.jar.JarFile.getEntry(JarFile.java:240)
	at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
	at org.apache.naming.resources.WebDirContext.lookupFromJars(WebDirContext.java:325)
	at org.apache.naming.resources.WebDirContext.getAttributes(WebDirContext.java:298)
	at org.apache.naming.resources.BaseDirContext.getAttributes(BaseDirContext.java:787)
	at org.apache.naming.resources.ProxyDirContext.cacheLoad(ProxyDirContext.java:1533)
	at org.apache.naming.resources.ProxyDirContext.cacheLookup(ProxyDirContext.java:1456)
	at org.apache.naming.resources.ProxyDirContext.lookup(ProxyDirContext.java:274)
	at org.glassfish.web.loader.WebappClassLoader.findResourceInternalFromRepositories(WebappClassLoader.java:2941)
	at org.glassfish.web.loader.WebappClassLoader.findResourceInternal(WebappClassLoader.java:2891)
	at org.glassfish.web.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2785)
	at org.glassfish.web.loader.WebappClassLoader.findClass(WebappClassLoader.java:1206)
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1762)
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1645)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at org.glassfish.web.loader.WebappClassLoader.findClass(WebappClassLoader.java:1232)
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1762)
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1645)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at org.glassfish.web.loader.WebappClassLoader.findClass(WebappClassLoader.java:1232)
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1762)
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1645)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at org.glassfish.web.loader.WebappClassLoader.findClass(WebappClassLoader.java:1232)
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1762)
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1645)
	at glassfish.Worker.loadClasses(Worker.java:237)
	at glassfish.Worker.access$500(Worker.java:22)
	at glassfish.Worker$WorkerExecutorRunnable.run(Worker.java:224)
	at java.util.concurrent.ThreadPoolExecutor$CallerRunsPolicy.rejectedExecution(ThreadPoolExecutor.java:2022)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at glassfish.Worker$WorkerConsumerThread.run(Worker.java:207)
```

It has the same root cause in the two interleaved method invocations; instead of an NPE, a jar that we thought was opened was closed instead.

**Comment by OndrejM** [comment]
Thanks, it is giving me the same error on recent version of Payara server. We will try to fix it.

**Comment by smillidge** [comment]
Internal engineering defect number PAYARA-664

**Comment by lprimak** [comment]
I am not sure that starting threads from ServletContextListener is supported by the JavaEE specification.
@strmer15 have you tried moving the thread-starting code to JavaEE concurrency utilities available in JavaEE 7 (ManagedExecutorService)?

**Comment by lprimak** [comment]
I am getting a different errors when deploying attached application:
```
Info:   started initializing
Warning:   could not create Dir using directory from url file:/Users/lprimak/Documents/devel/glassfish-domains/payara/generated/ear/test-glassfish-war_war/. skipping.
java.lang.NullPointerException
	at org.reflections.vfs.Vfs$DefaultUrlTypes$3.matches(Vfs.java:233)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:97)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:90)
	at org.reflections.Reflections.scan(Reflections.java:236)
	at org.reflections.Reflections.scan(Reflections.java:203)
	at org.reflections.Reflections.<init>(Reflections.java:128)
	at glassfish.Worker.<clinit>(Worker.java:40)
	at glassfish.GlassfishTestListener.contextInitialized(GlassfishTestListener.java:54)
	at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:5394)
	at com.sun.enterprise.web.WebModule.contextListenerStart(WebModule.java:744)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:5963)
	at com.sun.enterprise.web.WebModule.start(WebModule.java:692)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1041)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:1024)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:747)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:2296)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1942)
	at com.sun.enterprise.web.WebApplication.start(WebApplication.java:139)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:122)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:291)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:353)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:501)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:487)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
	at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:534)
	at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:224)
	at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:189)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)

Info:   Using "/var/folders/97/v3vhvcks5wncyqx3l5g8k22w0000gp/T/vfs_cache" as temporary files store.
Warning:   could not create Vfs.Dir from url. ignoring the exception and continuing
org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/Users/lprimak/Documents/devel/glassfish-domains/payara/generated/ear/test-glassfish-war_war/]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:108)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:90)
	at org.reflections.Reflections.scan(Reflections.java:236)
	at org.reflections.Reflections.scan(Reflections.java:203)
	at org.reflections.Reflections.<init>(Reflections.java:128)
	at glassfish.Worker.<clinit>(Worker.java:40)
	at glassfish.GlassfishTestListener.contextInitialized(GlassfishTestListener.java:54)
	at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:5394)
	at com.sun.enterprise.web.WebModule.contextListenerStart(WebModule.java:744)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:5963)
	at com.sun.enterprise.web.WebModule.start(WebModule.java:692)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1041)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:1024)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:747)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:2296)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1942)
	at com.sun.enterprise.web.WebApplication.start(WebApplication.java:139)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:122)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:291)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:353)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:501)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:487)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
	at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:534)
	at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:224)
	at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:189)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)

Warning:   could not create Vfs.Dir from url. ignoring the exception and continuing
org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/Users/lprimak/Documents/devel/glassfish-domains/payara/lib/ext/.gitkeep]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:108)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:90)
	at org.reflections.Reflections.scan(Reflections.java:236)
	at org.reflections.Reflections.scan(Reflections.java:203)
	at org.reflections.Reflections.<init>(Reflections.java:128)
	at glassfish.Worker.<clinit>(Worker.java:40)
	at glassfish.GlassfishTestListener.contextInitialized(GlassfishTestListener.java:54)
	at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:5394)
	at com.sun.enterprise.web.WebModule.contextListenerStart(WebModule.java:744)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:5963)
	at com.sun.enterprise.web.WebModule.start(WebModule.java:692)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1041)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:1024)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:747)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:2296)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1942)
	at com.sun.enterprise.web.WebApplication.start(WebApplication.java:139)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:122)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:291)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:353)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:501)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:487)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
	at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:534)
	at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:224)
	at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:189)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by OndrejM** [comment]
I think it is essential to put a breakpoint into `appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.start()` at line 6014 (on sources of 164.1).
I was able to reproduce the errors using the breakpoint now.

However, @lprimak is correct, spawning threads in Java EE is allowed only when using the Concurrency API. Other means are forbidden and should not be used. Please refactor the code to use only [ManagedExecutorService](http://docs.oracle.com/javaee/7/api/javax/enterprise/concurrent/ManagedExecutorService.html) as an `Executor`, instead of `consumerThreadPool` and any instance of `Thread` (such as `WorkerConsumerThread`)
---
Just a side note - I reproduced the problem with following steps:

When the server stopped on the breakpoint, I waited couple of seconds and resumed the processing. I was able to reproduce the errors couple of times in a row, although sometimes they did not appear. It was also not consistent in the error message, sometimes giving the `java.lang.IllegalStateException: zip file closed` and sometimes `NullPointerException at org.apache.naming.resources.WebDirContext.lookupFromJars` was raised.

Without the breakpoint I never got the exceptions.

The error about VFS clearly comes from the application being deployed, and it is always there, even if the reported exceptions happen.

**Comment by lprimak** [comment]
I am able to reproduce this now.  It happens whether threads are started from ManagedExecutorService or not, so will fix the issue in Payara.

**Comment by lprimak** [comment]
Fixed
