### ISSUE TITLE
Bug Report: NullPointerException in Payara 6.2024.11 / FISH-10136

### ISSUE THREAD

**Issue by ctabin** [payara/Payara#7077]
### Brief Summary

Hello,

During the bootstrap of the server, the following `WARNING` is displayed in the logs:

```
WARNING: Error clearing BeanELResolver cache
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because the return value of "org.glassfish.web.loader.CachingReflectionUtil.getFieldFromCache(java.lang.Class, String, boolean)" is null
        at org.glassfish.web.loader.WebappClassLoader.clearBeanResolver(WebappClassLoader.java:2677)
        at org.glassfish.web.loader.WebappClassLoader.clearBeanELResolverCache(WebappClassLoader.java:2666)
        at org.glassfish.web.loader.WebappClassLoader.stop(WebappClassLoader.java:2054)
        at org.glassfish.web.loader.WebappClassLoader.preDestroy(WebappClassLoader.java:2017)
        at org.glassfish.deployment.common.DeploymentContextImpl.getClassLoader(DeploymentContextImpl.java:293)
        at org.glassfish.deployment.common.DeploymentContextImpl.getClassLoader(DeploymentContextImpl.java:235)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:571)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:570)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:556)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:552)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/javax.security.auth.Subject.doAs(Subject.java:453)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:551)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:582)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:574)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/javax.security.auth.Subject.doAs(Subject.java:453)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:573)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1497)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1879)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1755)
        at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:131)
        at ch.saierp.sainet.embedded.server.SAINetServer.deployMobile(SAINetServer.java:2130)
        at ch.saierp.sainet.embedded.server.SAINetServer.start(SAINetServer.java:2082)
        at ch.saierp.sainet.embedded.server.cli.SAINetServerMain.lambda$startServer$27(SAINetServerMain.java:1288)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

This was not present in version 6.2024.10 and previous.

### Expected Outcome

No warning log.

### Current Outcome

A warning stacktrace during the bootstrap of the server.

### Reproducer

Start an instance with payara-embedded-all.

### Operating System

Linux Debian 12

### JDK Version

JDK 21

### Payara Distribution

Payara Embedded All

**Comment by lprimak** [comment]
This is most likely related to Faces or EL component upgrades. I’ll take a look as I can.

**Comment by lprimak** [comment]
Fixed by #7065

**Comment by Elifzeynepedman** [comment]
Hi @ctabin,

This issue has been acknowledged and escalated to the platform development team as `FISH-10136`.

Thank you,
Elif

**Comment by lprimak** [comment]
This can now be closed

**Comment by ctabin** [comment]
@lprimak Thank you very much !
