### ISSUE TITLE
org.glassfish.deployment.common.DeploymentException: Error in generating security policy for __admingui -- null

### ISSUE THREAD

**Issue by rajumca43** [payara/Payara#753]
Hi-

I am trying to create File based authentication with customized JAAC provider and realms. i configured realm and JAAC provider as default and when i restarted the server, It is unable to start the server.

And in Error console below is the error i am facing. Please help us from this issue.

```
2016-04-15T11:35:31.540+0530|Info: Entering Security Startup Service.
2016-04-15T11:35:31.544+0530|Info: Loading policy provider com.bmw.security.jaaf.jacc.JAAFPolicyProvider.
2016-04-15T11:35:31.571+0530|Info: [JAAFPolicyProvider] Initializing the JAAF Policy Provider
2016-04-15T11:35:31.663+0530|Info: Security Service(s) started successfully.
2016-04-15T11:35:34.612+0530|Info: [JAAFPolicyConfigurationFactory] Loading JAAF policy configuration factory.
2016-04-15T11:35:39.922+0530|Severe: Exception during lifecycle processing
org.glassfish.deployment.common.DeploymentException: Error in generating security policy for __admingui -- null 
---------------------------
---------------------------

at com.sun.enterprise.security.web.integration.WebSecurityManager.loadPolicyConfiguration(WebSecurityManager.java:309)
	at com.sun.enterprise.security.web.integration.WebSecurityManager.initialise(WebSecurityManager.java:273)
	at com.sun.enterprise.security.web.integration.WebSecurityManager.<init>(WebSecurityManager.java:171)
	at com.sun.enterprise.security.web.integration.WebSecurityManagerFactory.createManager(WebSecurityManagerFactory.java:293)
	at com.sun.enterprise.security.ee.SecurityDeployer.loadPolicy(SecurityDeployer.java:234)
	at com.sun.enterprise.security.ee.SecurityDeployer.access$000(SecurityDeployer.java:87)
	at com.sun.enterprise.security.ee.SecurityDeployer$AppDeployEventListener.event(SecurityDeployer.java:135)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at org.glassfish.internal.data.ModuleInfo.load(ModuleInfo.java:233)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:314)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:496)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.processApplication(ApplicationLoaderService.java:406)
	at com.sun.enterprise.v3.admin.adapter.InstallerThread.load(InstallerThread.java:211)
	at com.sun.enterprise.v3.admin.adapter.InstallerThread.run(InstallerThread.java:100)
```

**Comment by mikecroft** [comment]
Hi, it looks like your BMW policy provider is badly configured. Payara is trying to use it to set the security policy for the admin console which isn't working.

Can you give more details on what exactly it is that you've done?

**Comment by mikecroft** [comment]
Hi @rajumca43 is this still an issue for you? Do you have any more details?

**Comment by mikecroft** [comment]
Hi @rajumca43 we can't help you on this without more details. If you can give us a sample which reproduces the problem, we can take a look. I'll close this for now, but feel free to reopen if you can give us a test case.
