### ISSUE TITLE
Payara 4.1.1.162 no longer works with SQL Server drivers

### ISSUE THREAD

**Issue by realityforge** [payara/Payara#800]
Hi,

It looks like sql server no longer gracefully works with drivers that are only jdbc3 compliant. Unfortunately the main production ready driver that works with SQL server is still only jdbc3 compliant. The jTDS driver explicitly throws the AbstractMethodError error in getClientInfoProperties and it looks like payara used to catch Throwables but now only catches Exceptions. 

A sample exception trace is below:

```
java.lang.AbstractMethodError
	at net.sourceforge.jtds.jdbc.JtdsDatabaseMetaData.getClientInfoProperties(JtdsDatabaseMetaData.java:3551)
	at com.sun.gjc.spi.jdbc40.ConnectionHolder40.isSupportClientInfo(ConnectionHolder40.java:405)
	at com.sun.gjc.spi.jdbc40.ConnectionHolder40.init(ConnectionHolder40.java:105)
	at com.sun.gjc.spi.jdbc40.ConnectionHolder40.<init>(ConnectionHolder40.java:96)
	at com.sun.gjc.spi.jdbc40.ConnectionWrapper40.<init>(ConnectionWrapper40.java:64)
	at com.sun.gjc.spi.jdbc40.Jdbc40ObjectsFactory.getConnection(Jdbc40ObjectsFactory.java:92)
	at com.sun.gjc.spi.ManagedConnectionImpl.getConnection(ManagedConnectionImpl.java:465)
	at com.sun.enterprise.resource.allocator.LocalTxConnectorAllocator.fillInResourceObjects(LocalTxConnectorAllocator.java:119)
	at com.sun.enterprise.resource.pool.ConnectionPool.getResource(ConnectionPool.java:488)
	at com.sun.enterprise.resource.pool.PoolManagerImpl.getResourceFromPool(PoolManagerImpl.java:245)
	at com.sun.enterprise.resource.pool.PoolManagerImpl.getResource(PoolManagerImpl.java:170)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.getResource(ConnectionManagerImpl.java:360)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.internalGetConnection(ConnectionManagerImpl.java:307)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:196)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:171)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:166)
	at com.sun.gjc.spi.base.AbstractDataSource.getConnection(AbstractDataSource.java:114)
	at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:135)
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.setOrDetectDatasource(DatabaseSessionImpl.java:207)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:760)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:265)
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:731)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:205)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:305)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:337)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:303)
	at org.glassfish.persistence.jpa.JPADeployer$2.visitPUD(JPADeployer.java:451)
	at org.glassfish.persistence.jpa.JPADeployer$PersistenceUnitDescriptorIterator.iteratePUDs(JPADeployer.java:510)
	at org.glassfish.persistence.jpa.JPADeployer.iterateInitializedPUsAtApplicationPrepare(JPADeployer.java:492)
	at org.glassfish.persistence.jpa.JPADeployer.event(JPADeployer.java:398)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:488)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:487)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:356)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:356)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:169)
	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:94)
```

**Comment by dmatej** [comment]
1) Why you use so old driver?
2) JDBC3 drivers should not be used with ConnectionHolder40 etc. There was an option JDBC30DATASOURCE=true for these old drivers.
3) You can try my adapter project I have created for Informix JDBC which is extremely obsolete (and Derby). But I think it has not much sense, because Microsoft releases drivers compliant with actual specifications of JDBC (even 4.2). https://github.com/dmatej/jdbc-adapter

Catching a Throwable is generally an error, but AbstractMethodError should be catched when detecting the compliance. It seems I have some older sources, I will look at it after update.

**Comment by dmatej** [comment]
https://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=11774

**Comment by realityforge** [comment]
We use this driver as it is the only open source driver for microsoft databases that I am aware of and we are on the latest version of that library. We have tried to move to the microsoft driver in the past but due to lots of performance issues and bugs we had to move back to jTDS.

Is there an advantage to dropping open source support for SQL server?

**Comment by lprimak** [comment]
Hi,

Have you tried `JDBC30DATASOURCE=true` as David suggested?
I feel your pain regarding the MS-SQL JDBC drivers (I went through that pain before using I-Net Merlia drivers) which I would recommend.

Let me know if that works for you, and if not, will figure something else out.

**Comment by realityforge** [comment]
That seems to have fixes the problem. Thanks!

**Comment by mikecroft** [comment]
Documentation issue created

**Comment by anaelcarvalho** [comment]
I'm having issues with the proposed solution - it appears that connection validation no longer works when setting `JDBC30DATASOURCE=true`. Note that this is different than driver level validation which requires JDBC 4. Has anyone observed this behavior?

**Comment by lprimak** [comment]
@anaelcarvalho Please open a separate issue with the log files for the errors you are getting please
thank you
