### ISSUE TITLE
Payara 4.1.1.162 NullPointer Batch job execution on Cluster setup only

### ISSUE THREAD

**Issue by figolino** [payara/Payara#814]
Hi with the new version of payara 162 on cluster setup only we have a nullPointer when we try to start a batch job.

for detail see stack trace:

2016-05-13T11:40:32.787+0000] [Payara 4.1] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=33 _ThreadName=http-listener-1(4)] [timeMillis: 1463139632787] [levelValue: 900] [[
  StandardWrapperValve[Faces Servlet]: Servlet.service() for servlet Faces Servlet threw exception
java.lang.NullPointerException
        at fish.payara.jbatch.persistence.rdbms.LazyBootPersistenceManager.jobOperatorGetJobInstanceIds(LazyBootPersistenceManager.java:79)
        at com.ibm.jbatch.container.api.impl.JobOperatorImpl.getJobInstances(JobOperatorImpl.java:249)
        at ch.incamail.batch.RemoteJobOperatorImpl.getJobInstances(RemoteJobOperatorImpl.java:33)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4789)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
        at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
        at sun.reflect.GeneratedMethodAccessor159.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)

**Comment by smillidge** [comment]
Could you let me know what your datasource configuration is for the JBatch on the cluster?

**Comment by figolino** [comment]
Hi yes
I Guess the problem is that on the cluster config the 

Server config: => i guess OK
Instance Name:
server
Executor Service Lookup Name: concurrent/__defaultManagedExecutorService

Instance congi: => I guess the problem
 Cluster Name:
	imcluster
Executor Service Lookup Name: **Drop down is EMPTY!**

**Comment by figolino** [comment]
And im not able to select a lookup name for the executor Service

**Comment by figolino** [comment]
# setting up connection/jdbc pools
${asbin} ${creds}  create-jdbc-connection-pool  --datasourceclassname=org.postgresql.xa.PGXADataSource --restype=javax.sql.XADataSource --validationclassname=org.glassfish.api.jdbc.validation.PostgresConnectionValidation --isconnectvalidatereq=true --validationmethod=custom-validation --property=databaseName=*****-db-master:user=*********:password=******:port=5432:serverName=localhost glassfish-db-psql

# set batch runtime DB to external DB (psql)
${asbin} ${creds}  delete-jdbc-resource jdbc/__default
${asbin} ${creds}  create-jdbc-resource --connectionpoolid=glassfish-db-psql  jdbc/__default
${asbin} ${creds}  create-resource-ref --target server jdbc/__default
${asbin} ${creds}  set-batch-runtime-configuration --datasourcelookupname jdbc/__default --schemaName glassfish

**Comment by smillidge** [comment]
you will need to target the datasource to the cluster name.

**Comment by figolino** [comment]
yes i guess this is the problem to i have to target the batch runntime configuration like this
${asbin} ${creds} set-batch-runtime-configuration --target imcluster --datasourcelookupname jdbc/__default --schemaName glassfish

**Comment by figolino** [comment]
ok problem solved thanks ;-) closed
