### ISSUE TITLE
Cluster JMS issue

### ISSUE THREAD

**Issue by Mephysto666** [payara/Payara#863]
Hi there,
after installing a payara cluster, in server.log of remote cluster node, I have 	continuously this java exception:

```
[2016-06-16T22:47:38.020+0200] [Payara 4.1] [SEVERE] [] [] [tid: _ThreadID=121 _ThreadName=JMS_PROXY_default_JMS_host-kernel(1) SelectorRunner] [timeMillis: 1466110058020] [levelValue: 1000] [[
  java.lang.IllegalAccessException: Cannot create broker instance.  A broker instance is already created.
	at com.sun.messaging.jmq.jmsclient.runtime.impl.BrokerInstanceImpl.createInstance(BrokerInstanceImpl.java:137)
	at com.sun.messaging.jmq.jmsclient.runtime.impl.ClientRuntimeImpl.createBrokerInstance(ClientRuntimeImpl.java:82)
	at com.sun.messaging.jms.blc.EmbeddedBrokerRunner.createTheInVMBrokerInstance(EmbeddedBrokerRunner.java:291)
	at com.sun.messaging.jms.blc.EmbeddedBrokerRunner.<init>(EmbeddedBrokerRunner.java:130)
	at com.sun.messaging.jms.blc.LifecycleManagedBroker.start(LifecycleManagedBroker.java:452)
	at com.sun.messaging.jms.ra.ResourceAdapter.start(ResourceAdapter.java:365)
	at com.sun.enterprise.connectors.jms.system.ActiveJmsResourceAdapter$1.run(ActiveJmsResourceAdapter.java:550)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.enterprise.connectors.jms.system.ActiveJmsResourceAdapter.startResourceAdapter(ActiveJmsResourceAdapter.java:541)
	at com.sun.enterprise.connectors.ActiveOutboundResourceAdapter.init(ActiveOutboundResourceAdapter.java:130)
	at com.sun.enterprise.connectors.inbound.ActiveInboundResourceAdapterImpl.init(ActiveInboundResourceAdapterImpl.java:90)
	at com.sun.enterprise.connectors.ActiveRAFactory.instantiateActiveResourceAdapter(ActiveRAFactory.java:141)
	at com.sun.enterprise.connectors.ActiveRAFactory.createActiveResourceAdapter(ActiveRAFactory.java:108)
	at com.sun.enterprise.connectors.service.ResourceAdapterAdminServiceImpl.createActiveResourceAdapter(ResourceAdapterAdminServiceImpl.java:210)
	at com.sun.enterprise.connectors.service.ResourceAdapterAdminServiceImpl.createActiveResourceAdapter(ResourceAdapterAdminServiceImpl.java:346)
	at com.sun.enterprise.connectors.ConnectorRuntime.createActiveResourceAdapter(ConnectorRuntime.java:405)
	at com.sun.enterprise.connectors.jms.system.ActiveJmsResourceAdapter.initializeService(ActiveJmsResourceAdapter.java:2600)
	at com.sun.enterprise.v3.services.impl.ServiceInitializerFilter.handleAccept(ServiceInitializerFilter.java:129)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$7.execute(ExecutorResolver.java:103)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
	at org.glassfish.grizzly.nio.transport.TCPNIOServerConnection$RegisterAcceptedChannelCompletionHandler.completed(TCPNIOServerConnection.java:346)
	at org.glassfish.grizzly.nio.transport.TCPNIOServerConnection$RegisterAcceptedChannelCompletionHandler.completed(TCPNIOServerConnection.java:313)
	at org.glassfish.grizzly.nio.DefaultSelectorHandler.registerChannel0(DefaultSelectorHandler.java:336)
	at org.glassfish.grizzly.nio.DefaultSelectorHandler.registerChannelAsync(DefaultSelectorHandler.java:192)
	at org.glassfish.grizzly.nio.RoundRobinConnectionDistributor.registerChannelAsync(RoundRobinConnectionDistributor.java:101)
	at org.glassfish.grizzly.nio.transport.TCPNIOServerConnection.registerAcceptedChannel(TCPNIOServerConnection.java:206)
	at org.glassfish.grizzly.nio.transport.TCPNIOServerConnection.onAccept(TCPNIOServerConnection.java:243)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:508)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.SameThreadIOStrategy.executeIoEvent(SameThreadIOStrategy.java:103)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.executeIoEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.nio.SelectorRunner.iterateKeyEvents(SelectorRunner.java:415)
	at org.glassfish.grizzly.nio.SelectorRunner.iterateKeys(SelectorRunner.java:384)
	at org.glassfish.grizzly.nio.SelectorRunner.doSelect(SelectorRunner.java:348)
	at org.glassfish.grizzly.nio.SelectorRunner.run(SelectorRunner.java:279)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)]]


[2016-06-16T22:47:38.021+0200] [Payara 4.1] [SEVERE] [] [javax.enterprise.resource.resourceadapter.com.sun.enterprise.connectors] [tid: _ThreadID=121 _ThreadName=JMS_PROXY_default_JMS_host-kernel(1) SelectorRunner] [timeMillis: 1466110058021] [levelValue: 1000] [[
  RAR6035 : Resource adapter start failed.
javax.resource.spi.ResourceAdapterInternalException: java.security.PrivilegedActionException: javax.resource.spi.ResourceAdapterInternalException: MQJMSRA_RA4001: start:Aborting:Exception starting EMBEDDED broker=Cannot create broker instance.  A broker instance is already created.
	at com.sun.enterprise.connectors.jms.system.ActiveJmsResourceAdapter.startResourceAdapter(ActiveJmsResourceAdapter.java:559)
	at com.sun.enterprise.connectors.ActiveOutboundResourceAdapter.init(ActiveOutboundResourceAdapter.java:130)
	at com.sun.enterprise.connectors.inbound.ActiveInboundResourceAdapterImpl.init(ActiveInboundResourceAdapterImpl.java:90)
	at com.sun.enterprise.connectors.ActiveRAFactory.instantiateActiveResourceAdapter(ActiveRAFactory.java:141)
	at com.sun.enterprise.connectors.ActiveRAFactory.createActiveResourceAdapter(ActiveRAFactory.java:108)
	at com.sun.enterprise.connectors.service.ResourceAdapterAdminServiceImpl.createActiveResourceAdapter(ResourceAdapterAdminServiceImpl.java:210)
	at com.sun.enterprise.connectors.service.ResourceAdapterAdminServiceImpl.createActiveResourceAdapter(ResourceAdapterAdminServiceImpl.java:346)
	at com.sun.enterprise.connectors.ConnectorRuntime.createActiveResourceAdapter(ConnectorRuntime.java:405)
	at com.sun.enterprise.connectors.jms.system.ActiveJmsResourceAdapter.initializeService(ActiveJmsResourceAdapter.java:2600)
	at com.sun.enterprise.v3.services.impl.ServiceInitializerFilter.handleAccept(ServiceInitializerFilter.java:129)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$7.execute(ExecutorResolver.java:103)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
	at org.glassfish.grizzly.nio.transport.TCPNIOServerConnection$RegisterAcceptedChannelCompletionHandler.completed(TCPNIOServerConnection.java:346)
	at org.glassfish.grizzly.nio.transport.TCPNIOServerConnection$RegisterAcceptedChannelCompletionHandler.completed(TCPNIOServerConnection.java:313)
	at org.glassfish.grizzly.nio.DefaultSelectorHandler.registerChannel0(DefaultSelectorHandler.java:336)
	at org.glassfish.grizzly.nio.DefaultSelectorHandler.registerChannelAsync(DefaultSelectorHandler.java:192)
	at org.glassfish.grizzly.nio.RoundRobinConnectionDistributor.registerChannelAsync(RoundRobinConnectionDistributor.java:101)
	at org.glassfish.grizzly.nio.transport.TCPNIOServerConnection.registerAcceptedChannel(TCPNIOServerConnection.java:206)
	at org.glassfish.grizzly.nio.transport.TCPNIOServerConnection.onAccept(TCPNIOServerConnection.java:243)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:508)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.SameThreadIOStrategy.executeIoEvent(SameThreadIOStrategy.java:103)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.executeIoEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.nio.SelectorRunner.iterateKeyEvents(SelectorRunner.java:415)
	at org.glassfish.grizzly.nio.SelectorRunner.iterateKeys(SelectorRunner.java:384)
	at org.glassfish.grizzly.nio.SelectorRunner.doSelect(SelectorRunner.java:348)
	at org.glassfish.grizzly.nio.SelectorRunner.run(SelectorRunner.java:279)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.security.PrivilegedActionException: javax.resource.spi.ResourceAdapterInternalException: MQJMSRA_RA4001: start:Aborting:Exception starting EMBEDDED broker=Cannot create broker instance.  A broker instance is already created.
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.enterprise.connectors.jms.system.ActiveJmsResourceAdapter.startResourceAdapter(ActiveJmsResourceAdapter.java:541)
	... 34 more
Caused by: javax.resource.spi.ResourceAdapterInternalException: MQJMSRA_RA4001: start:Aborting:Exception starting EMBEDDED broker=Cannot create broker instance.  A broker instance is already created.
	at com.sun.messaging.jms.blc.LifecycleManagedBroker.start(LifecycleManagedBroker.java:461)
	at com.sun.messaging.jms.ra.ResourceAdapter.start(ResourceAdapter.java:365)
	at com.sun.enterprise.connectors.jms.system.ActiveJmsResourceAdapter$1.run(ActiveJmsResourceAdapter.java:550)
	... 36 more
Caused by: java.lang.IllegalAccessException: Cannot create broker instance.  A broker instance is already created.
	at com.sun.messaging.jmq.jmsclient.runtime.impl.BrokerInstanceImpl.createInstance(BrokerInstanceImpl.java:137)
	at com.sun.messaging.jmq.jmsclient.runtime.impl.ClientRuntimeImpl.createBrokerInstance(ClientRuntimeImpl.java:82)
	at com.sun.messaging.jms.blc.EmbeddedBrokerRunner.createTheInVMBrokerInstance(EmbeddedBrokerRunner.java:291)
	at com.sun.messaging.jms.blc.EmbeddedBrokerRunner.<init>(EmbeddedBrokerRunner.java:130)
	at com.sun.messaging.jms.blc.LifecycleManagedBroker.start(LifecycleManagedBroker.java:452)
	... 38 more
]]



[2016-06-16T23:00:26.638+0200] [Payara 4.1] [SEVERE] [] [javax.resourceadapter.mqjmsra.lifecycle] [tid: _ThreadID=121 _ThreadName=JMS_PROXY_default_JMS_host-kernel(1) SelectorRunner] [timeMillis: 1466110826638] [levelValue: 1000] [[
  MQJMSRA_RA4001: start:Aborting:Exception starting EMBEDDED broker=Cannot create broker instance.  A broker instance is already created.]]


```

Can anyone help me to resolve this issue?

On the first node I do not have these messages.

Thanks in advance.

Meph

**Comment by lprimak** [comment]
Are you on AWS by any chance?
AWS (and other cloud providers) as well as other networks do not allow multicast.
I think that this is a problem you are running into
See this: https://docs.oracle.com/cd/E26576_01/doc.312/e24934/clusters.htm#GSHAG00101

**Comment by Mephysto666** [comment]
For now I tried to disable JMS in remote node, and log error message disappeared.

JMS is required for in memory replication of cluster?

**Comment by lprimak** [comment]
@Mephysto666 are you on AWS or any other cloud server that doesn't allow multicast?
If not, clusters won't work unless you follow instructions here:  https://docs.oracle.com/cd/E26576_01/doc.312/e24934/clusters.htm#GSHAG00101

JMS doesn't enter into it here, it's just an error message that you got as a consequence of not available multicast.

Hazelcast also relies on multicast unless configured differently (Hazelcast can discover AWS nodes if configured correctly)

**Comment by Mephysto666** [comment]
Hi Iprimark,
at the moment I'm using citrix VMs of OVH provider.

I'm not in a cloud service.

Regards.

Meph

**Comment by lprimak** [comment]
@Mephysto666 it still sounds like you are not getting multicast services.  Please verify as stated in the documentation link above.

**Comment by Mephysto666** [comment]
@lprimak this is output of validate-multicast command for my cluster:

asadmin> validate-multicast
Will use port 2048
Will use address 228.9.3.1
Will use bind interface null
Will use wait period 2,000 (in milliseconds)

Listening for data...
Sending message with content "payara-2" every 2,000 milliseconds
Received data from payara-2 (loopback)
Exiting after 20 seconds. To change this timeout, use the --timeout command line option.
Command validate-multicast executed successfully.


So, to use cluster and session persistence for EJB, do I have to do any particular settings for JMS?

**Comment by lprimak** [comment]
Judging by the output above, multicast isn't working.  When multicast works, you will receive messages from more than just loopback interface.

**Comment by OndrejM** [comment]
Hi @Mephysto, as far as I know, JMS is not related to session replication in cluster at all. The only thing you would need JMS for is replication of 2nd level JPA cache, if you are using it. If you are not using 2nd level JPA cache and not using JMS itself, you may disable JMS completely.

**Comment by mikecroft** [comment]
@Mephysto666 Looking at the original error, there is a message that the server cannot create a broker instance. Have you configured JMS to run in `REMOTE` mode? As Ondrej has said, you can completely disable OpenMQ in Payara as described in Steve's blog:
http://blog.payara.fish/disabling-openmq-in-payara-server

**Comment by mikecroft** [comment]
Hi @Mephysto666 have you tried disabling OpenMQ?

**Comment by mikecroft** [comment]
Is this still a problem @Mephysto666 ?

**Comment by mikecroft** [comment]
Closing this issue as no longer a problem. If, after disabling OpenMQ, this problem still exists, then the issue can be reopened.
