### ISSUE TITLE
Hazelcast activation 

### ISSUE THREAD

**Issue by Mephysto666** [payara/Payara#866]
Hi there,
I'm trying hazelcast in a payara cluster: I have enable it in hazelcast configuration tab of my cluster (two node). When I open cluster members tab, there is a message that specifies hazelcast is not enabled in both cluster members.

Why is this message showed? Are there other steps to do for enable hazelcast?

Thanks in advance.

Meph

**Comment by Mephysto666** [comment]
Hi there,
I made other tests with an EJB and these are results:

I used this code:

```
private static void instanceHazelcast() throws Throwable {
            Context ctx = new InitialContext();  
            HazelcastInstance instance =  (com.hazelcast.core.HazelcastInstance)ctx.lookup("payara/Hazelcast"); 
    }
```

This is my hazelcast configuration:

![image](https://cloud.githubusercontent.com/assets/3337127/16209227/563b54a6-3736-11e6-9021-6c63ba655212.png)



But in logs I found this exception:


```
17-06-2016 17:59:17 FATAL [http-listener-1(3)] (StartupHelper.java:78): ERROR in application startup. Application is not running.
javax.naming.NamingException: Lookup failed for 'payara/Hazelcast' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, org.osjava.jndi.root=classpath://config, org.osjava.jndi.delimiter=/, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming} [Root exception is javax.naming.NameNotFoundException: payara]
        at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:491)
        at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:438)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at it.redevogames.redevoserver.classes.utilities.startup.StartupHelper.instanceHazelcast(StartupHelper.java:90)
        at it.redevogames.redevoserver.classes.utilities.startup.StartupHelper.applicationStartUp(StartupHelper.java:65)
        at it.redevogames.redevoserver.classes.utilities.startup.StartupHelper.checkServerStatus(StartupHelper.java:495)
        at it.redevogames.redevoserver.webservices.TranslationManagement.getErrorMessages(TranslationManagement.java:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4789)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:73)
        at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
```



So, what is my error?



Many thanks.

Meph

**Comment by mikecroft** [comment]
I'm actually in the process of writing a blog about this!

Currently, the configuration of Hazelcast from the Admin console might be a bit confusing. The configuration belongs in the sidebar on the left, along with other config resources and it will be moving there for the 163 version.

As for your particular problems, the way to use Hazelcast for clustering in Payara should be to use **standalone** instances. If you'd like them to be controllable like a traditional (shoal-based) cluster is, then you will need to make sure they reference the same configuration. Once you've **copied** the default-config for your first instance, make sure you **reference** the new configuration when creating the subsequent instances.

Hopefully I'll get my blog out in the next couple of weeks and you'll have some screenshots to go with the explanation!

**Comment by Mephysto666** [comment]
Hi Mike,
I used standalone instances as you suggested and a the moment Hazelcast seems to work correctly.

Thank you very much.

Meph

**Comment by mikecroft** [comment]
Thanks for confirming!
