### ISSUE TITLE
Migrating from JEE6/GF 3.1.2.2 webapp to Payara 4.1

### ISSUE THREAD

**Issue by edilmar** [payara/Payara#888]
My actual environment is:
- GF 3.1.2.2
- CDI Weld 1.1.8
- DeltaSpike 1.6.0
- JSF Mojarra javax.faces.jar 2.1.29
- RichFaces 4.5.15
- JPA 2
- Hibernate 4.2.7 
- JasperReports 6.1.0
- JDBC drivers Jaybird/Firebird and PostgreSQL
Is there some different config to do, to run this JEE6 webapp in Payara 4.1?
I have this webapp running for many years.
I got to deploy the webapp, but when I try to run, the first login page (with login/pass required="true" fields) doesn't work properly. I type the values for login/pass and JSF page arises an error message that fields login/pass are required.

**Comment by lprimak** [comment]
@edilmar I am not sure there is anywhere near enough information above to offer any help or a solution.
Do you have any kind of errors in the log?  JavaScript errors?

**Comment by edilmar** [comment]
I look at Web JS Console in Firefox and Chrome, and the messages are the same in GF 3.1.2.2 and Payara 4.1.1. My main doubt is: does Payara run JEE6 apps? Because I had problems to deploy and run JEE6 apps in GF 4.x.

**Comment by lprimak** [comment]
@edilmar 
Yes, Payara runs JEE6 apps just fine.
What I did find that some applications do not fully comply with the spec, and Payara (and GF 4.1.1) do not allow this anymore when GF 3.1.x did.  This is what trips up most upgrades.

**Comment by edilmar** [comment]
@lprimak I think the problem is that my app is JSF 2.1, it should run with Mojarra javax.faces.jar 2.1.29 and no 2.2.13 default file. I changed this file in .../glassifsh/modules but Payara is still showing "Inicializing Mojarra 2.2.13". Is the JSF API built in another file, not javax.faces.jar is used?

**Comment by mulderbaba** [comment]
@edilmar can you purge your osgi-cache before downgrading the javax.faces.jar? folder resides under glassfish/domains/%your_domain%/osgi-cache

**Comment by edilmar** [comment]
@mulderbaba now I did this:
1) clean osgi-cache
2) start Payara
It didn't started and arised this exception:
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:97)
	at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:54)
Caused by: com.sun.enterprise.module.ResolveError: Failed to start OSGiModuleImpl:: Bundle = [org.glassfish.main.batch.glassfish-batch-connector [42]], State = [NEW]
	at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:217)
	at org.jvnet.hk2.osgiadapter.OsgiPopulatorPostProcessor$1.loadClass(OsgiPopulatorPostProcessor.java:78)
	at org.jvnet.hk2.config.ConfigModel.getProxyType(ConfigModel.java:171)
	at org.jvnet.hk2.config.Dom.getImplementationClass(Dom.java:1015)
	at org.jvnet.hk2.config.Dom.register(Dom.java:223)
	at org.jvnet.hk2.config.ConfigParser.handleElement(ConfigParser.java:253)
	at org.jvnet.hk2.config.ConfigParser.handleElement(ConfigParser.java:191)
	at org.jvnet.hk2.config.ConfigParser.handleElement(ConfigParser.java:232)
	at org.jvnet.hk2.config.ConfigParser.handleElement(ConfigParser.java:239)
	at org.jvnet.hk2.config.ConfigParser.handleElement(ConfigParser.java:239)
	at org.jvnet.hk2.config.ConfigParser.handleElement(ConfigParser.java:191)
	at org.jvnet.hk2.config.ConfigParser.parse(ConfigParser.java:101)
	at org.jvnet.hk2.config.ConfigParser.parse(ConfigParser.java:95)
	at org.glassfish.config.support.DomainXml.parseDomainXml(DomainXml.java:259)
	at org.glassfish.config.support.DomainXml.run(DomainXml.java:117)
	at org.jvnet.hk2.config.ConfigurationPopulator.populateConfig(ConfigurationPopulator.java:58)
	at org.glassfish.hk2.bootstrap.HK2Populator.populateConfig(HK2Populator.java:107)
	at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.populateConfig(AbstractModulesRegistryImpl.java:211)
	at com.sun.enterprise.module.bootstrap.Main.createServiceLocator(Main.java:273)
	at org.jvnet.hk2.osgiadapter.HK2Main.createServiceLocator(HK2Main.java:119)
	at com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishRuntime.newGlassFish(EmbeddedOSGiGlassFishRuntime.java:95)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishRuntimeDecorator.newGlassFish(GlassFishRuntimeDecorator.java:68)
	at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishRuntime.newGlassFish(OSGiGlassFishRuntime.java:91)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:113)
	... 6 more
Caused by: org.osgi.framework.BundleException: Unresolved constraint in bundle org.glassfish.main.batch.glassfish-batch-connector [42]: Unable to resolve 42.0: missing requirement [42.0] osgi.wiring.package; (osgi.wiring.package=com.ibm.jbatch.container.context.impl) [caused by: Unable to resolve 198.0: missing requirement [198.0] osgi.wiring.package; (osgi.wiring.package=org.glassfish.weld) [caused by: Unable to resolve 37.0: missing requirement [37.0] osgi.wiring.package; (&(osgi.wiring.package=com.sun.faces.spi)(version>=2.2.0)(!(version>=3.0.0)))]]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:3974)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2037)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:955)
	at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:209)
	... 29 more
Completed shutdown of GlassFish runtime
We are in non-embedded mode, so org.glassfish.main.core.glassfish [13] has nothing to do.

Then, I come back the original javax.faces.jar file 2.2.13, it starts fine, but my app doesn't run.

**Comment by lprimak** [comment]
@edilmar you may not be able to "downgrade" JSF in Payara / GlassFish without changing more than javax.faces.jar  JSF 2.2 should be backwards-compatible with JSF 2.1

What problems are you getting with the stock Payara when running your application?
Whatever problems you are getting, you should fix them in the application itself.  It is probably something that doesn't comply fully with JEE 6 (or JEE 7 spec)

**Comment by edilmar** [comment]
@lprimak is it possible the problem is DeltaSpike? I use @ConversationScoped from it.

**Comment by lprimak** [comment]
Anything is possible, but I doubt it.

**Comment by mikecroft** [comment]
I think there has been at least one issue with DeltaSpike reported, no idea whether it's related to this though. I'll see what I can find out.

**Comment by lprimak** [comment]
If would be very helpful if you provide a simplest app that fails in stock Payara (no modifications in modules/ directory) and the fish.payara.classloading.delegate system property set to false

See http://stackoverflow.com/questions/38570837/how-to-activate-payara-class-loading-parameter-fish-payara-classloading-delegate for details

**Comment by mikecroft** [comment]
Hi @edilmar - have you had chance to verify that this fails in an unmodified Payara Server with the `fish.payara.classloading.delegate` system property set to false? I don't think this is related to any other DeltaSpike issue we've encountered so that should be OK.

**Comment by edilmar** [comment]
@mikecroft  I solve my problem using new versions of DeltaSpike and RichFaces. Now all runs fine!
