### ISSUE TITLE
failure to deploy an application on Payara that includes its own Hazelcast version

### ISSUE THREAD

**Issue by dbbtwom** [payara/Payara#890]
When trying to migrate from Glassfish 4.1.1 to Payara 4.1 an issue occurred with a JEE application which uses vert.x 3.2.1 and its Hazelcast back-end (depending on Hazelcast 3.5.2) for clustering.

When that JEE application tries to connect to the vert.x cluster on startup, the following error is seen in the Payara log and deployment fails:

```
Info:   [LOCAL] [dev] [3.6.2] Interfaces is enabled, trying to pick one address matching to one of: [192.168.56.*]
Info:   [LOCAL] [dev] [3.6.2] Prefer IPv4 stack is true.
Info:   [LOCAL] [dev] [3.6.2] Picked Address[192.168.56.1]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true
Info:   [192.168.56.1]:5701 [dev] [3.6.2] Hazelcast 3.6.2 (20160405 - 0f88699) starting at Address[192.168.56.1]:5701
Info:   [192.168.56.1]:5701 [dev] [3.6.2] Copyright (c) 2008-2016, Hazelcast, Inc. All Rights Reserved.
Info:   [192.168.56.1]:5701 [dev] [3.6.2] Configured Hazelcast Serialization version : 1
Severe:   Failed to join cluster
java.lang.IllegalArgumentException: PortableFactory[-16] is already registered! com.hazelcast.concurrent.semaphore.client.SemaphorePortableHook$1@250d8a93 -> com.hazelcast.concurrent.semaphore.client.SemaphorePortableHook$1@285b6081
	at com.hazelcast.internal.serialization.impl.PortableHookLoader.register(PortableHookLoader.java:87)
	at com.hazelcast.internal.serialization.impl.PortableHookLoader.load(PortableHookLoader.java:54)
	at com.hazelcast.internal.serialization.impl.PortableHookLoader.<init>(PortableHookLoader.java:44)
	at com.hazelcast.internal.serialization.impl.SerializationServiceV1.<init>(SerializationServiceV1.java:88)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.createSerializationService(DefaultSerializationServiceBuilder.java:264)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:218)
	at com.hazelcast.instance.DefaultNodeExtension.createSerializationService(DefaultNodeExtension.java:125)
	at com.hazelcast.instance.Node.<init>(Node.java:174)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:125)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:160)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:143)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:111)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
	at io.vertx.spi.cluster.hazelcast.HazelcastClusterManager.lambda$join$3(HazelcastClusterManager.java:117)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$17(ContextImpl.java:296)
	at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$265(OrderedExecutorFactory.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

I assume this is due to two different Hazelcast versions being in the classpath.
As long as one does not need any of the Hazelcast-specific features of Payara, it would be good if it would not interfere with Hazelcast from any deployed apps.

Note: no Payara clustering is used, the clustering is purely inside the JEE app, done via vert.x3.

**Comment by mikecroft** [comment]
Have you disabled the delegating classloader so the Hazelcast version from your app is preferred over the server implementation?

[See the docs for reference](https://payara.gitbooks.io/payara-server/content/documentation/extended-documentation/classloading.html)

**Comment by dbbtwom** [comment]
Thanks for the hint, this actually did improve things. Deployment does work now, but strangely when another vert.x node (non-JEE) joins the cluster, that node throws the following exception:
```
Jul 04, 2016 1:00:43 PM com.hazelcast.cache.impl.operation.PostJoinCacheOperation
SEVERE: [192.168.56.1]:5702 [dev] [3.5.2] Service with name 'hz:impl:cacheService' not found!
com.hazelcast.core.HazelcastException: Service with name 'hz:impl:cacheService' not found!
    at com.hazelcast.spi.Operation.getService(Operation.java:213)
    at com.hazelcast.cache.impl.operation.PostJoinCacheOperation.run(PostJoinCacheOperation.java:44)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:137)
    at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.runOnCallingThread(ClassicOperationExecutor.java:380)
    at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.runOperationOnCallingThread(OperationServiceImpl.java:252)
    at com.hazelcast.cluster.impl.operations.PostJoinOperation.run(PostJoinOperation.java:93)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:137)
    at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.runOnCallingThread(ClassicOperationExecutor.java:380)
    at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.runOperationOnCallingThread(OperationServiceImpl.java:252)
    at com.hazelcast.cluster.impl.operations.FinalizeJoinOperation.run(FinalizeJoinOperation.java:99)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:137)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:315)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:142)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:115)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:101)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:76)
```

Running the JEE app on Glassfish instead does not exhibit this behavior in the other (non-JEE) vert.x nodes.

**Comment by mikecroft** [comment]
How are you configuring Hazelcast for the vert.x nodes? Do you have a hazelcast-config.xml file you're using? Can you make sure that this is being picked up in the app deployed to Payara Server?

**Comment by dbbtwom** [comment]
In both cases (JEE and non-JEE) the entire cluster configuration is done explicitly in Java code instead of relying on a hazelcast-config.xml file.

Cluster setup works basically like this (with host, subnet and members being configured identically for the non-JEE nodes as well as in Glassfish and Payara via JNDI vars used by the JEE app):
```
ClusterManager clusterManager = new HazelcastClusterManager(); 
Config clusterConfig = new Config();

NetworkConfig networkConfig = new NetworkConfig();
InterfacesConfig interfacesConfig = new InterfacesConfig();
interfacesConfig.addInterface(subnet);  // e.g. "192.168.56.*"
interfacesConfig.setEnabled(true);
networkConfig.setInterfaces(interfacesConfig);

JoinConfig joinConfig = new JoinConfig();

TcpIpConfig tcpIpConfig = new TcpIpConfig();
tcpIpConfig.setEnabled(true);
tcpIpConfig.setMembers(members); // e.g. "192.168.56.1" if all nodes on the same machine
joinConfig.setTcpIpConfig(tcpIpConfig);

MulticastConfig multicastConfig = new MulticastConfig();
multicastConfig.setEnabled(false);
joinConfig.setMulticastConfig(multicastConfig);

networkConfig.setJoin(joinConfig);
clusterConfig.setNetworkConfig(networkConfig);
clusterManager.setConfgi(clusterConfig);

VertxOptions vertxOptions = new VertxOptions();
vertxOptions.setClustered(true);
vertxOptions.setClusterHost(host); // e.g. "192.168.56.1"
vertxOptions.setClusterManager(clusterManager);

Vertx.clusteredVertx(vertxOptions, resultHandler);
```

I somehow suspect that due to the fact that Glassfish does not use Hazelcast at all, but Payara does, that there may be some things Payara does with Hazelcast in the background that somehow affect the cluster, even if no Hazelcast-dependent feature is explicitly enabled in Payara.
Maybe there is some general setup that is always happening regardless.

**Comment by dbbtwom** [comment]
Here is a complete example, both JEE and non-JEE:

PlainClusterNode.java (put this into a regular Java application project as main class)

```
package com.example.vertxnodeplain;

import com.hazelcast.config.Config;
import com.hazelcast.config.InterfacesConfig;
import com.hazelcast.config.JoinConfig;
import com.hazelcast.config.MulticastConfig;
import com.hazelcast.config.NetworkConfig;
import com.hazelcast.config.TcpIpConfig;
import io.vertx.core.AsyncResult;
import io.vertx.core.Vertx;
import io.vertx.core.VertxOptions;
import io.vertx.spi.cluster.hazelcast.HazelcastClusterManager;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Logger;

public class PlainClusterNode {

    private final static Logger LOGGER = Logger.getLogger(PlainClusterNode.class.getName());

    public static void main(String[] args) {
        PlainClusterNode node = new PlainClusterNode();
        node.init();
    }

    public void init() {
        HazelcastClusterManager clusterManager = new HazelcastClusterManager();
        Config clusterConfig = new Config();

        NetworkConfig networkConfig = new NetworkConfig();
        InterfacesConfig interfacesConfig = new InterfacesConfig();
        interfacesConfig.addInterface("127.0.0.*");
        interfacesConfig.setEnabled(true);
        networkConfig.setInterfaces(interfacesConfig);

        JoinConfig joinConfig = new JoinConfig();

        TcpIpConfig tcpIpConfig = new TcpIpConfig();
        tcpIpConfig.setEnabled(true);
        List<String> members = new LinkedList<>();
        members.add("127.0.0.1");
        tcpIpConfig.setMembers(members);
        joinConfig.setTcpIpConfig(tcpIpConfig);

        MulticastConfig multicastConfig = new MulticastConfig();
        multicastConfig.setEnabled(false);
        joinConfig.setMulticastConfig(multicastConfig);

        networkConfig.setJoin(joinConfig);
        clusterConfig.setNetworkConfig(networkConfig);
        clusterManager.setConfig(clusterConfig);

        VertxOptions vertxOptions = new VertxOptions();
        vertxOptions.setClustered(true);
        vertxOptions.setClusterHost("127.0.0.1");
        vertxOptions.setClusterManager(clusterManager);

        LOGGER.info("Plain node joining...");
        Vertx.clusteredVertx(vertxOptions, (AsyncResult<Vertx> result) -> {
            if (result.succeeded()) {
                LOGGER.info("Plain node joined cluster");
            } else {
                LOGGER.severe("Plain node failed to join");
            }
        });
    }

}

```

JeeClusterNode.java (put this into an EJB project referenced by an EAR project and deploy the EAR,
don't forget the beans.xml)

```
package com.example.vertxnodejee;

import com.hazelcast.config.Config;
import com.hazelcast.config.InterfacesConfig;
import com.hazelcast.config.*;
import io.vertx.core.AsyncResult;
import io.vertx.core.Vertx;
import io.vertx.core.VertxOptions;
import io.vertx.spi.cluster.hazelcast.HazelcastClusterManager;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.ejb.Singleton;
import javax.ejb.Startup;

@Startup
@Singleton
public class JeeClusterNode {

    private final static Logger LOGGER = Logger.getLogger(JeeClusterNode.class.getName());

    @PostConstruct
    public void init() {
        HazelcastClusterManager clusterManager = new HazelcastClusterManager();
        Config clusterConfig = new Config();

        NetworkConfig networkConfig = new NetworkConfig();
        InterfacesConfig interfacesConfig = new InterfacesConfig();
        interfacesConfig.addInterface("127.0.0.*");
        interfacesConfig.setEnabled(true);
        networkConfig.setInterfaces(interfacesConfig);

        JoinConfig joinConfig = new JoinConfig();

        TcpIpConfig tcpIpConfig = new TcpIpConfig();
        tcpIpConfig.setEnabled(true);
        List<String> members = new LinkedList<>();
        members.add("127.0.0.1");
        tcpIpConfig.setMembers(members);
        joinConfig.setTcpIpConfig(tcpIpConfig);

        MulticastConfig multicastConfig = new MulticastConfig();
        multicastConfig.setEnabled(false);
        joinConfig.setMulticastConfig(multicastConfig);

        networkConfig.setJoin(joinConfig);
        clusterConfig.setNetworkConfig(networkConfig);
        clusterManager.setConfig(clusterConfig);

        VertxOptions vertxOptions = new VertxOptions();
        vertxOptions.setClustered(true);
        vertxOptions.setClusterHost("127.0.0.1");
        vertxOptions.setClusterManager(clusterManager);
        
        LOGGER.info("JEE node joining...");
        Vertx.clusteredVertx(vertxOptions, (AsyncResult<Vertx> result) -> {
            if (result.succeeded()) {
                LOGGER.info("JEE node joined cluster");
            } else {
                LOGGER.severe("JEE node failed to join");
            }
        });
    }

}

```

common dependencies:

```
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-core</artifactId>
            <version>3.2.1</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-hazelcast</artifactId>
            <version>3.2.1</version>
            <type>jar</type>
        </dependency>
```

**Comment by dbbtwom** [comment]
Adding 
```
        <dependency>
            <groupId>javax.cache</groupId>
            <artifactId>cache-api</artifactId>
            <version>1.0.0</version>
        </dependency>
```
on the non-JEE side solves the problem.

**Comment by mikecroft** [comment]
Thanks for the update, I hadn't got round to looking at this yet. Good to know it's all working as it should, though.
