### ISSUE TITLE
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by baldodavi** [payara/Payara#904]
I'm using hazelcast on payara trying to work on ReplicatedMap to be sure data will be availables at same time on nodes.
Trying ejb code on a single Payara don't cause any issue.
Trying ebj code on our cluster give us this issue:

``` java
05-07-2016 19:26:37 DEBUG [http-listener-1(4)] (Room.java:83): com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: it.redevogames.redevoserver.classes.gamerules.MatchList
        at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:224)
        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:170)
        at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:234)
        at com.hazelcast.replicatedmap.impl.record.ObjectReplicatedRecordStorage.marshall(ObjectReplicatedRecordStorage.java:41)
        at com.hazelcast.replicatedmap.impl.record.AbstractReplicatedRecordStore.put(AbstractReplicatedRecordStore.java:136)
        at com.hazelcast.replicatedmap.impl.operation.PutOperation.run(PutOperation.java:61)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:172)
        at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processOperation(OperationThread.java:198)
        at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:132)
        at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124)
        at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99)
Caused by: java.lang.ClassNotFoundException: it.redevogames.redevoserver.classes.gamerules.MatchList
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at com.sun.enterprise.loader.CurrentBeforeParentClassLoader.loadClass(CurrentBeforeParentClassLoader.java:82)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:137)
        at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:115)
        at com.hazelcast.nio.IOUtil$1.resolveClass(IOUtil.java:114)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
        at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:219)
        ... 11 more
```

Obliviously MatchList extends Serializable.
Here you can find the code:

``` java
    private void instanceRoomHazelcast() {
        MatchList matchAttempts = new MatchList();
        MatchList ongoingMatches = new MatchList();

        try {
            getMatchMap().put(MATCH_ATTEMPTS_HAZELCAST_NAME, matchAttempts);
            getMatchMap().put(MATCH_ONGOING_HAZELCAST_NAME, ongoingMatches);
            _usersInRoom = _hazeInstance.getList("usersInRoom");
        } catch (Exception ex) {
            LogHelper.getLogHelperObject().debug(ex);
        }
    }

    private ReplicatedMap<String, MatchList> getMatchMap() {
        return _hazeInstance.getReplicatedMap(MATCH_MAP_NAME);
    }
```

Any idea about? MatchList is an Object coded into ejb, not got from a library, we load on all cluster instances.

Thanks for your time, David.

**Comment by mulderbaba** [comment]
@baldodavi how do you create your _hazeInstance? how do you provide your config into it? this is obviously a classloader issue that needs to be taken care of while creating HZ instance.

**Comment by baldodavi** [comment]
I create my _hazeInstance in this way, as reported in specifications.
```java
Context hazeCtx = new InitialContext();
_hazeInstance = (com.hazelcast.core.HazelcastInstance) hazeCtx.lookup("payara/Hazelcast");
```
This bug is very similar to another bug affecting some times ago JCache #318

**Comment by smillidge** [comment]
Have you tried using JCache api rather than Hazelcast directly. For example you could inject a named cache;

@NamedCache(cacheName = MATCH_MAP_NAME)
@Inject
Cache cache;

This looks like a similar problem in Hazelcast to the one you mentioned. Hazelcast spawns a bunch of internal threads for operations and they inherit the application server core classloader and there's no easy way for us to get the application classloader onto these threads. Although I do have an idea for a fix in Payara Server.

**Comment by baldodavi** [comment]
@smillidge reading JCache Hazelcast documents I understood that the only structure permit to have same data in each cluster instance is ReplicatedMap. Can JChace give us this kind of service? If I understood data on JChace are partitioned.

Thanks, David.

**Comment by fturizo** [comment]
Hello @baldodavi. Sorry after coming back to you after all this time, this issue fell through the cracks. Regarding your question, it is indeed possible to replicate other structures than `ReplicatedMap`s using a distributed **JCache** cache. However if doing this, is recommended that all nodes in the cache have access to the class the value corresponds to avoid the bug that @smillidge mentioned.

Let us know if this answers your question correctly.

**Comment by lprimak** [comment]
Relates to https://github.com/hazelcast/hazelcast/issues/10875

**Comment by lprimak** [comment]
This should be resolved as of 2018 Payara
