### ISSUE TITLE
after running asadmin enable-secure-admin , encounter problem stop/start glassfish

### ISSUE THREAD

**Issue by wsaxton** [payara/Payara#911]
After I enable secure admin on the system, start-domain/stop-domain is broken.  stop-domain does not appear to be able to tell that the domain is up and running.

```
fuggles:/payara/payara-4.1.1.162/glassfish/bin$ ./asadmin --host localhost --port 4848 enable-secure-admin
You must restart all running servers for the change in secure admin to take effect.
Command enable-secure-admin executed successfully.
fuggles:/payara/payara-4.1.1.162/glassfish/bin$ ./asadmin stop-domain
Waiting for the domain to stop .
Command stop-domain executed successfully.
fuggles:/payara/payara-4.1.1.162/glassfish/bin$ ./asadmin start-domain
Waiting for domain1 to start ..........
Successfully started the domain : domain1
domain  Location: /payara/payara-4.1.1.162/glassfish/domains/domain1
Log File: /payara/payara-4.1.1.162/glassfish/domains/domain1/logs/server.log
Admin Port: 4848
Command start-domain executed successfully.
fuggles:/payara/payara-4.1.1.162/glassfish/bin$ ./asadmin stop-domain
CLI306: Warning - The server located at /payara/payara-4.1.1.162/glassfish/domains/domain1 is not running.
Command stop-domain executed successfully.
fuggles:/payara/payara-4.1.1.162/glassfish/bin$ ps -ef | grep payara
wsaxton  10981     1  4 13:46 pts/0    00:00:12 /import/java/latest/bin/../linux/bin/java -cp 
...
```

**Comment by mikecroft** [comment]
Is there anything significant in the server logs? I would be interested to see what actually happens with the server when all these commands are run, I suspect there is something more going on here

**Comment by mikecroft** [comment]
Hi - do you have any more details on this? Is it still a problem for you?

**Comment by wsaxton** [comment]
Hi Mike,  Sorry, I was pulled off onto a different project.  Will get back to this within the next day or so.

**Comment by wsaxton** [comment]
Here's the output from "asadmin start-domain". 

$ cat server.log
[2016-07-28T09:32:19.773-0700] [] [INFO] [NCLS-GFLAUNCHER-00005] [javax.enterprise.launcher] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1469723539773] [levelValue: 800] [[
  JVM invocation command line:
/import/swr-dev-local/java/latest/bin/java
-cp
/import/swr-dev/ws/wsaxton/payara/payara-4.1.1.162/glassfish/modules/glassfish.jar
-XX:+UnlockDiagnosticVMOptions
-XX:NewRatio=2
-XX:MaxPermSize=192m
-Xmx512m
-client
-javaagent:/import/swr-dev/ws/wsaxton/payara/payara-4.1.1.162/glassfish/lib/monitor/flashlight-agent.jar
-Djavax.xml.accessExternalSchema=all
-Djavax.net.ssl.trustStore=/import/swr-dev/ws/wsaxton/payara/payara-4.1.1.162/glassfish/domains/domain1/config/cacerts.jks
-Djdk.tls.rejectClientInitiatedRenegotiation=true
-Djdk.corba.allowOutputStreamSubclass=true
-Dfelix.fileinstall.dir=/import/swr-dev/ws/wsaxton/payara/payara-4.1.1.162/glassfish/modules/autostart/
-Dorg.glassfish.additionalOSGiBundlesToStart=org.apache.felix.shell,org.apache.felix.gogo.runtime,org.apache.felix.gogo.shell,org.apache.felix.gogo.command,org.apache.felix.shell.remote,org.apache.felix.fileinstall
-Dcom.sun.aas.installRoot=/import/swr-dev/ws/wsaxton/payara/payara-4.1.1.162/glassfish
-Dfelix.fileinstall.poll=5000
-Djava.endorsed.dirs=/import/swr-dev/ws/wsaxton/payara/payara-4.1.1.162/glassfish/modules/endorsed:/import/swr-dev/ws/wsaxton/payara/payara-4.1.1.162/glassfish/lib/endorsed
-Djava.security.policy=/import/swr-dev/ws/wsaxton/payara/payara-4.1.1.162/glassfish/domains/domain1/config/server.policy
-Dosgi.shell.telnet.maxconn=1
-Dfelix.fileinstall.bundles.startTransient=true
-Dcom.sun.enterprise.config.config_environment_factory_class=com.sun.enterprise.config.serverbeans.AppserverConfigEnvironmentFactory
-Dfelix.fileinstall.log.level=2
-Djavax.net.ssl.keyStore=/import/swr-dev/ws/wsaxton/payara/payara-4.1.1.162/glassfish/domains/domain1/config/keystore.jks
-Djava.security.auth.login.config=/import/swr-dev/ws/wsaxton/payara/payara-4.1.1.162/glassfish/domains/domain1/config/login.conf
-Dfelix.fileinstall.disableConfigSave=false
-Dfelix.fileinstall.bundles.new.start=true
-Dcom.sun.aas.instanceRoot=/import/swr-dev/ws/wsaxton/payara/payara-4.1.1.162/glassfish/domains/domain1
-Dosgi.shell.telnet.port=6666
-Dgosh.args=--nointeractive
-Dcom.sun.enterprise.security.httpsOutboundKeyAlias=s1as
-Dorg.jboss.weld.serialization.beanIdentifierIndexOptimization=false
-Dosgi.shell.telnet.ip=127.0.0.1
-DANTLR_USE_DIRECT_CLASS_LOADING=true
-Djava.awt.headless=true
-Dcom.ctc.wstx.returnNullForDefaultNamespace=true
-Djava.ext.dirs=/import/swr-dev-local/java/latest/lib/ext:/import/swr-dev-local/java/latest/jre/lib/ext:/import/swr-dev/ws/wsaxton/payara/payara-4.1.1.162/glassfish/domains/domain1/lib/ext
-Djdbc.drivers=org.apache.derby.jdbc.ClientDriver
-Djava.library.path=/import/swr-dev/ws/wsaxton/payara/payara-4.1.1.162/glassfish/lib:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
com.sun.enterprise.glassfish.bootstrap.ASMain
-upgrade
false
-domaindir
/import/swr-dev/ws/wsaxton/payara/payara-4.1.1.162/glassfish/domains/domain1
-read-stdin
true
-asadmin-args
--host,,,localhost,,,--port,,,4848,,,--secure=false,,,--terse=false,,,--echo=false,,,--interactive=true,,,start-domain,,,--verbose=false,,,--watchdog=false,,,--debug=false,,,--domaindir,,,/import/swr-dev/ws/wsaxton/payara/payara-4.1.1.162/glassfish/domains,,,domain1
-domainname
domain1
-instancename
server
-type
DAS
-verbose
false
-asadmin-classpath
/import/swr-dev/ws/wsaxton/payara/payara-4.1.1.162/glassfish/lib/client/appserver-cli.jar
-debug
false
-asadmin-classname
com.sun.enterprise.admin.cli.AdminMain
-watchdog
false]]

[2016-07-28T09:32:22.626-0700] [Payara 4.1] [INFO] [NCLS-LOGGING-00009] [javax.enterprise.logging] [tid: _ThreadID=28 _ThreadName=RunLevelControllerThread-1469723542537] [timeMillis: 1469723542626] [levelValue: 800] [[
  Running Payara Version: Payara Server  4.1.1.162 #badassfish (build 116)]]

[2016-07-28T09:32:22.627-0700] [Payara 4.1] [INFO] [NCLS-LOGGING-00010] [javax.enterprise.logging] [tid: _ThreadID=28 _ThreadName=RunLevelControllerThread-1469723542537] [timeMillis: 1469723542627] [levelValue: 800] [[
  Server log file is using Formatter class: com.sun.enterprise.server.logging.ODLLogFormatter]]

[2016-07-28T09:32:22.850-0700] [Payara 4.1] [INFO] [] [org.glassfish.ha.store.spi.BackingStoreFactoryRegistry] [tid: _ThreadID=30 _ThreadName=RunLevelControllerThread-1469723542546] [timeMillis: 1469723542850] [levelValue: 800] [[
  Registered org.glassfish.ha.store.adapter.cache.ShoalBackingStoreProxy for persistence-type = replicated in BackingStoreFactoryRegistry]]

[2016-07-28T09:32:22.994-0700] [Payara 4.1] [INFO] [SEC-SVCS-00100] [javax.enterprise.security.services] [tid: _ThreadID=28 _ThreadName=RunLevelControllerThread-1469723542537] [timeMillis: 1469723542994] [levelValue: 800] [[
  Authorization Service has successfully initialized.]]

[2016-07-28T09:32:23.008-0700] [Payara 4.1] [INFO] [] [org.glassfish.ha.store.spi.BackingStoreFactoryRegistry] [tid: _ThreadID=30 _ThreadName=RunLevelControllerThread-1469723542546] [timeMillis: 1469723543008] [levelValue: 800] [[
  Registered fish.payara.ha.hazelcast.store.HazelcastBackingStoreFactoryProxy for persistence-type = hazelcast in BackingStoreFactoryRegistry]]

[2016-07-28T09:32:23.009-0700] [Payara 4.1] [INFO] [] [fish.payara.ha.hazelcast.store.HazelcastBackingStoreFactory] [tid: _ThreadID=30 _ThreadName=RunLevelControllerThread-1469723542546] [timeMillis: 1469723543009] [levelValue: 800] [[
  Registered Hazelcast BackingStoreFactory with persistence-type = hazelcast]]

[2016-07-28T09:32:23.032-0700] [Payara 4.1] [INFO] [NCLS-SECURITY-01115] [javax.enterprise.system.core.security] [tid: _ThreadID=29 _ThreadName=RunLevelControllerThread-1469723542546] [timeMillis: 1469723543032] [levelValue: 800] [[
  Realm [admin-realm] of classtype [com.sun.enterprise.security.auth.realm.file.FileRealm] successfully created.]]

[2016-07-28T09:32:23.034-0700] [Payara 4.1] [INFO] [NCLS-SECURITY-01115] [javax.enterprise.system.core.security] [tid: _ThreadID=29 _ThreadName=RunLevelControllerThread-1469723542546] [timeMillis: 1469723543034] [levelValue: 800] [[
  Realm [file] of classtype [com.sun.enterprise.security.auth.realm.file.FileRealm] successfully created.]]

[2016-07-28T09:32:23.038-0700] [Payara 4.1] [INFO] [NCLS-SECURITY-01115] [javax.enterprise.system.core.security] [tid: _ThreadID=29 _ThreadName=RunLevelControllerThread-1469723542546] [timeMillis: 1469723543038] [levelValue: 800] [[
  Realm [certificate] of classtype [com.sun.enterprise.security.auth.realm.certificate.CertificateRealm] successfully created.]]

[2016-07-28T09:32:23.068-0700] [Payara 4.1] [INFO] [NCLS-CORE-00087] [javax.enterprise.system.core] [tid: _ThreadID=27 _ThreadName=RunLevelControllerThread-1469723542536] [timeMillis: 1469723543068] [levelValue: 800] [[
  Grizzly Framework 2.3.24 started in: 22ms - bound to [/0.0.0.0:8080]]]

[2016-07-28T09:32:23.090-0700] [Payara 4.1] [INFO] [NCLS-CORE-00087] [javax.enterprise.system.core] [tid: _ThreadID=27 _ThreadName=RunLevelControllerThread-1469723542536] [timeMillis: 1469723543090] [levelValue: 800] [[
  Grizzly Framework 2.3.24 started in: 1ms - bound to [/0.0.0.0:8181]]]

[2016-07-28T09:32:23.116-0700] [Payara 4.1] [INFO] [NCLS-CORE-00087] [javax.enterprise.system.core] [tid: _ThreadID=27 _ThreadName=RunLevelControllerThread-1469723542536] [timeMillis: 1469723543116] [levelValue: 800] [[
  Grizzly Framework 2.3.24 started in: 2ms - bound to [/0.0.0.0:4848]]]

[2016-07-28T09:32:23.158-0700] [Payara 4.1] [INFO] [NCLS-CORE-00087] [javax.enterprise.system.core] [tid: _ThreadID=30 _ThreadName=RunLevelControllerThread-1469723542546] [timeMillis: 1469723543158] [levelValue: 800] [[
  Grizzly Framework 2.3.24 started in: 1ms - bound to [/0.0.0.0:3700]]]

[2016-07-28T09:32:23.160-0700] [Payara 4.1] [INFO] [NCLS-CORE-00017] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1469723543160] [levelValue: 800] [[
  Payara Server  4.1.1.162 #badassfish (116) startup time : Felix (2,466ms), startup services(631ms), total(3,097ms)]]

[2016-07-28T09:32:23.161-0700] [Payara 4.1] [INFO] [] [fish.payara.nucleus.util.CleanupPostBoot] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1469723543161] [levelValue: 800] [[
  Cleaning JarFileFactory Cache to prevent jar FD leaks]]

[2016-07-28T09:32:23.358-0700] [Payara 4.1] [INFO] [NCLS-CORE-00087] [javax.enterprise.system.core] [tid: _ThreadID=28 _ThreadName=RunLevelControllerThread-1469723542537] [timeMillis: 1469723543358] [levelValue: 800] [[
  Grizzly Framework 2.3.24 started in: 1ms - bound to [/0.0.0.0:7677]]]

[2016-07-28T09:32:23.384-0700] [Payara 4.1] [INFO] [NCLS-BOOTSTRAP-00027] [javax.enterprise.bootstrap] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1469723543384] [levelValue: 800] [[
  Registered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishImpl@474fae39 as OSGi service registration: org.apache.felix.framework.ServiceRegistrationImpl@56ac5c80.]]

[2016-07-28T09:32:23.411-0700] [Payara 4.1] [INFO] [] [] [tid: _ThreadID=25 _ThreadName=FelixStartLevel] [timeMillis: 1469723543411] [levelValue: 800] [[
  /import/swr-dev/ws/wsaxton/payara/payara-4.1.1.162/glassfish/domains/domain1/autodeploy/bundles does not exist, please create it.]]

[2016-07-28T09:32:23.471-0700] [Payara 4.1] [INFO] [NCLS-JMX-00024] [javax.enterprise.system.jmx] [tid: _ThreadID=69 _ThreadName=Thread-14] [timeMillis: 1469723543471] [levelValue: 800] [[
  Creating a SecureRMIServerSocketFactory @ 0.0.0.0 with ssl config = GlassFishConfigBean.org.glassfish.grizzly.config.dom.Ssl]]

[2016-07-28T09:32:23.477-0700] [Payara 4.1] [INFO] [] [] [tid: _ThreadID=69 _ThreadName=Thread-14] [timeMillis: 1469723543477] [levelValue: 800] [[
  SSLParams =org.glassfish.admin.mbeanserver.ssl.SSLParams@8b5fc40]]

[2016-07-28T09:32:23.477-0700] [Payara 4.1] [WARNING] [NCLS-JMX-00020] [javax.enterprise.system.jmx] [tid: _ThreadID=69 _ThreadName=Thread-14] [timeMillis: 1469723543477] [levelValue: 900] [[
  All SSL cipher suites disabled for network-listener(s).  Using SSL implementation specific defaults]]

[2016-07-28T09:32:23.484-0700] [Payara 4.1] [INFO] [] [] [tid: _ThreadID=69 _ThreadName=Thread-14] [timeMillis: 1469723543484] [levelValue: 800] [[
  SSLParams =org.glassfish.admin.mbeanserver.ssl.SSLParams@8b5fc40]]

[2016-07-28T09:32:23.484-0700] [Payara 4.1] [WARNING] [NCLS-JMX-00020] [javax.enterprise.system.jmx] [tid: _ThreadID=69 _ThreadName=Thread-14] [timeMillis: 1469723543484] [levelValue: 900] [[
  All SSL cipher suites disabled for network-listener(s).  Using SSL implementation specific defaults]]

[2016-07-28T09:32:23.607-0700] [Payara 4.1] [INFO] [NCLS-JMX-00025] [javax.enterprise.system.jmx] [tid: _ThreadID=69 _ThreadName=Thread-14] [timeMillis: 1469723543607] [levelValue: 800] [[
  SSLServerSocket /0.0.0.0:8686 and [SSL: ServerSocket[addr=/0.0.0.0,localport=8686]] created]]

[2016-07-28T09:32:23.671-0700] [Payara 4.1] [WARNING] [NCLS-JMX-00007] [javax.enterprise.system.jmx] [tid: _ThreadID=69 _ThreadName=Thread-14] [timeMillis: 1469723543671] [levelValue: 900] [[
  Cannot start JMX connector JmxConnector config: { name = system, Protocol = rmi_jrmp, Address = 0.0.0.0, Port = 8686, AcceptAll = false, AuthRealmName = admin-realm, SecurityEnabled = true} due to exception java.io.IOException: Cannot bind to URL [rmi://sca-lx-18.example.com:8686/jmxrmi]: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is: 
    javax.net.ssl.SSLKeyException: RSA premaster secret error]]]

[2016-07-28T09:32:23.674-0700] [Payara 4.1] [SEVERE] [] [] [tid: _ThreadID=69 _ThreadName=Thread-14] [timeMillis: 1469723543674] [levelValue: 1000] [[
  java.io.IOException: Cannot bind to URL [rmi://sca-lx-18.example.com:8686/jmxrmi]: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is: 
    javax.net.ssl.SSLKeyException: RSA premaster secret error]
    at javax.management.remote.rmi.RMIConnectorServer.newIOException(RMIConnectorServer.java:827)
    at javax.management.remote.rmi.RMIConnectorServer.start(RMIConnectorServer.java:432)
    at org.glassfish.admin.mbeanserver.RMIConnectorStarter.start(RMIConnectorStarter.java:319)
    at org.glassfish.admin.mbeanserver.JMXStartupService$JMXConnectorsStarterThread.startConnector(JMXStartupService.java:313)
    at org.glassfish.admin.mbeanserver.JMXStartupService$JMXConnectorsStarterThread.run(JMXStartupService.java:350)
Caused by: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is: 
    javax.net.ssl.SSLKeyException: RSA premaster secret error]
    at com.sun.jndi.rmi.registry.RegistryContext.rebind(RegistryContext.java:163)
    at com.sun.jndi.toolkit.url.GenericURLContext.rebind(GenericURLContext.java:251)
    at javax.naming.InitialContext.rebind(InitialContext.java:433)
    at javax.naming.InitialContext.rebind(InitialContext.java:433)
    at javax.management.remote.rmi.RMIConnectorServer.bind(RMIConnectorServer.java:642)
    at javax.management.remote.rmi.RMIConnectorServer.start(RMIConnectorServer.java:427)
    ... 3 more
Caused by: java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is: 
    javax.net.ssl.SSLKeyException: RSA premaster secret error
    at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:304)
    at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
    at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:342)
    at sun.rmi.registry.RegistryImpl_Stub.rebind(Unknown Source)
    at com.sun.jndi.rmi.registry.RegistryContext.rebind(RegistryContext.java:161)
    ... 8 more
Caused by: javax.net.ssl.SSLKeyException: RSA premaster secret error
    at sun.security.ssl.RSAClientKeyExchange.<init>(RSAClientKeyExchange.java:86)
    at sun.security.ssl.ClientHandshaker.serverHelloDone(ClientHandshaker.java:918)
    at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:348)
    at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
    at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
    at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:747)
    at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
    at java.io.DataOutputStream.flush(DataOutputStream.java:123)
    at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:229)
    ... 12 more
Caused by: java.security.NoSuchAlgorithmException: SunTlsRsaPremasterSecret KeyGenerator not available
    at javax.crypto.KeyGenerator.<init>(KeyGenerator.java:169)
    at javax.crypto.KeyGenerator.getInstance(KeyGenerator.java:223)
    at sun.security.ssl.JsseJce.getKeyGenerator(JsseJce.java:272)
    at sun.security.ssl.RSAClientKeyExchange.<init>(RSAClientKeyExchange.java:77)
    ... 24 more]]

**Comment by wsaxton** [comment]
Here is the output from "asadmin stop-domain":

[2016-07-28T09:36:36.278-0700] [Payara 4.1] [WARNING] [] [org.glassfish.grizzly.filterchain.DefaultFilterChain] [tid: _ThreadID=57 _ThreadName=admin-listener(4)] [timeMillis: 1469723796278] [levelValue: 900] [[
  GRIZZLY0013: Exception during FilterChain execution
java.lang.RuntimeException: Could not generate dummy secret
    at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1429)
    at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535)
    at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813)
    at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
    at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
    at org.glassfish.grizzly.ssl.SSLUtils.sslEngineUnwrap(SSLUtils.java:465)
    at org.glassfish.grizzly.ssl.SSLConnectionContext.unwrap(SSLConnectionContext.java:192)
    at org.glassfish.grizzly.ssl.SSLUtils.handshakeUnwrap(SSLUtils.java:291)
    at org.glassfish.grizzly.ssl.SSLBaseFilter.doHandshakeStep(SSLBaseFilter.java:661)
    at org.glassfish.grizzly.ssl.SSLBaseFilter.doHandshakeStep(SSLBaseFilter.java:610)
    at org.glassfish.grizzly.ssl.SSLBaseFilter.handleRead(SSLBaseFilter.java:318)
    at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
    at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
    at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:231)
    at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
    at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
    at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
    at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Could not generate dummy secret
    at sun.security.ssl.RSAClientKeyExchange.<init>(RSAClientKeyExchange.java:132)
    at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:246)
    at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
    at sun.security.ssl.Handshaker$1.run(Handshaker.java:919)
    at sun.security.ssl.Handshaker$1.run(Handshaker.java:916)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1369)
    at org.glassfish.grizzly.ssl.SSLUtils.executeDelegatedTask(SSLUtils.java:274)
    at org.glassfish.grizzly.ssl.SSLBaseFilter.doHandshakeStep(SSLBaseFilter.java:696)
    ... 23 more
Caused by: java.security.NoSuchAlgorithmException: Cannot find any provider supporting RSA/ECB/PKCS1Padding
    at javax.crypto.Cipher.getInstance(Cipher.java:540)
    at sun.security.ssl.JsseJce.getCipher(JsseJce.java:229)
    at sun.security.ssl.RSAClientKeyExchange.<init>(RSAClientKeyExchange.java:115)
    ... 31 more
]]

**Comment by mikecroft** [comment]
Thanks! A few other questions:

* what JDK are you using? Oracle? IBM? OpenJDK? 
* have you replaced the key/trust stores at all? 
* have you imported your own certificates into the existing key/trust store files? 

It looks like SSL is a bit broken. I haven't seen this sort of thing before, so it might be environment related. Have you tried downloading or extracting a fresh version?

**Comment by wsaxton** [comment]
- JDK is Oracle
- I have not touch the key/trust stores
- I haven't imported anything


This is a completely new install.  These are the only commands I have run:
```
$ unzip payara-4.1.1.162.zip
$ mv payara41 payara-4.1.1.162
$ cd payara-4.1.1.162/glassfish/bin
$ ./asadmin start-domain 
$ ./asadmin --host localhost --port 4848 change-admin-password
$ ./asadmin --host localhost --port 4848 enable-secure-admin
$ ./asadmin stop-domain
$ ./asadmin start-domain <-- see log output provided
$ ./asadmin stop-domain <-- see log output provided
```

**Comment by mikecroft** [comment]
Ah, I was on my phone earlier, I missed this bit:

```
[2016-07-28T09:32:23.671-0700] [Payara 4.1] [WARNING] [NCLS-JMX-00007] [javax.enterprise.system.jmx] [tid: _ThreadID=69 _ThreadName=Thread-14] [timeMillis: 1469723543671] [levelValue: 900] [[
Cannot start JMX connector JmxConnector config: { name = system, Protocol = rmi_jrmp, Address = 0.0.0.0, Port = 8686, AcceptAll = false, AuthRealmName = admin-realm, SecurityEnabled = true} due to exception java.io.IOException: Cannot bind to URL [rmi://sca-lx-18.example.com:8686/jmxrmi]: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is: 
javax.net.ssl.SSLKeyException: RSA premaster secret error]]]
```

I'm wondering if there could be a problem with your hostname settings. Does your hostname resolve to `sca-lx-18.example.com`?

**Comment by wsaxton** [comment]
I removed the real domain name to protect the anonymity of my company.  Yes, it is the correct FQDN.

**Comment by wsaxton** [comment]
Not sure if this is helpful, but I tried disabling the secure admin function and got the following errors:

``` 
$ ./asadmin disable-secure-admin
java.net.SocketException: Connection reset
Command disable-secure-admin failed.
```

```
$ ./asadmin --host localhost --port 4848 disable-secure-admin
NCLS-ADMIN-00010
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
Command disable-secure-admin failed.
```

Perhaps there is an issue with communicating with the administration port once secure admin is enabled?

**Comment by wsaxton** [comment]
Okay, so tried these exact steps with a different UNIX account which has MINIMAL configuration/environment settings and...it worked just fine.

So something tells me its a problem with my environment.

I went ahead and removed all .asadmin* files in my home directory.

Are there any other artifacts lying around somewhere that I should look to remove?

**Comment by wsaxton** [comment]
Here is the place in server.log where it fails using my account:

> [2016-10-17T18:48:20.972-0700] [Payara 4.1] [WARNING] [NCLS-JMX-00007] [javax.enterprise.system.jmx] [tid: _ThreadID=51 _ThreadName=Thread-15] [timeMillis: 1476755300972] [levelValue: 900] [[
>   Cannot start JMX connector JmxConnector config: { name = system, Protocol = rmi_jrmp, Address = 0.0.0.0, Port = 8686, AcceptAll = false, AuthRealmName = admin-realm, SecurityEnabled = true} due to exception java.io.IOException: Cannot bind to URL [rmi://fuggles.example.com:8686/jmxrmi]: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is: 
> 	javax.net.ssl.SSLKeyException: RSA premaster secret error]]]

Here is the place is the server.log where it succeeds using the bare-bones account:

> 2016-10-17T18:43:48.450-0700] [Payara 4.1] [INFO] [NCLS-JMX-00005] [javax.enterprise.system.jmx] [tid: _ThreadID=52 _ThreadName=Thread-15] [timeMillis: 1476755028450] [levelValue: 800] [[
>   JMXStartupService has started JMXConnector on JMXService URL service:jmx:rmi://fuggles.example.com:8686/jndi/rmi://fuggles.example.com:8686/jmxrmi]]

**Comment by wsaxton** [comment]
Figured it out.  My $JAVA_HOME was set incorrectly somehow.  Once I fixed it everything worked fine.  Sorry for wasting your time!

**Comment by RjEcho217** [comment]
IM getting the same issue but my JAVA_HOME is correct and in the domain.xml file java home is set correctly.... I will run the asadmin start-domain1 and it will execute successfully then i run a list-domains and  domain1 is not running. 

This is frustrating, Ive enabled secure admin and made some jvm changes as well as setup password alias for another user account. Why will the application port not stay up?

**Comment by wfsaxton** [comment]
The only thing I can suggest is making sure your JAVA_HOME is REALLY set properly (I thought mine was because I just looked at it and it looked fine).

Make sure this actually returns proper output:

```
$ $JAVA_HOME/bin/java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

**Comment by mikecroft** [comment]
@RjEcho217 if you look back at the server.log that @wfsaxton posted, the very first thing to get logged is the JVM used to start Payara Server, so you can use that to check:

```
$ cat server.log
[2016-07-28T09:32:19.773-0700] [] [INFO] [NCLS-GFLAUNCHER-00005] [javax.enterprise.launcher] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1469723539773] [levelValue: 800] [[
JVM invocation command line:
/import/swr-dev-local/java/latest/bin/java
```

Is the behaviour you see *exactly* the same as described in this issue? You get the same SSL errors?

**Comment by RjEcho217** [comment]
Looks like for one of my issues it was the a different java version was starting the jvm, I'm not sure how because the other domains are running fine that use a different JDK.

**Comment by JozsefKuti** [comment]
We had the same Exception, after we enabled the secure admin and also when we tried to create a node to this host:
"NCLS-ADMIN-00010
javax.net.ssl.SSLException: java.lang.RuntimeException: java.lang.RuntimeException: java.io.EOFException"

What we found is:
**There is a ~/.gfclient directory under the executor user's home. Delete it** and restart what you just can and it will be fine!

Our issue was caused by an EOFException which means "Signals that an end of file or end of stream has been reached unexpectedly" and it is because under this ~/.gfclient/truststore was an 0 byte long file...
