### ISSUE TITLE
Web fragment definitions cannot be overriden in web.xml

### ISSUE THREAD

**Issue by pdudits** [payara/Payara#936]
A servlet or filter mapping for a servlet that is defined in a fragment cannot be changed in `web.xml`. It appears to be validated sooner than fragments are processed, resulting in error:

```
java.lang.RuntimeException: There is no web component by the name of s4 here.
    at org.glassfish.web.deployment.node.WebCommonNode.endElement(WebCommonNode.java:248)
    at org.glassfish.web.deployment.node.WebBundleNode.endElement(WebBundleNode.java:158)
    at com.sun.enterprise.deployment.node.SaxParserHandler.endElement(SaxParserHandler.java:622)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
    at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.endElement(XMLSchemaValidator.java:857)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1783)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2970)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
    at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
    at com.sun.enterprise.deployment.io.DeploymentDescriptorFile.read(DeploymentDescriptorFile.java:318)
    at com.sun.enterprise.deployment.io.DeploymentDescriptorFile.read(DeploymentDescriptorFile.java:245)
    at com.sun.enterprise.deployment.archivist.Archivist.readStandardDeploymentDescriptor(Archivist.java:666)
    at com.sun.enterprise.deployment.archivist.ApplicationFactory.createApplicationFromStandardDD(ApplicationFactory.java:210)
    at org.glassfish.javaee.core.deployment.DolProvider.getNameFor(DolProvider.java:269)
    at org.glassfish.internal.deployment.GenericHandler.getDefaultApplicationName(GenericHandler.java:152)
    at org.glassfish.deployment.admin.DeployCommand.preAuthorization(DeployCommand.java:262)
    at com.sun.enterprise.admin.util.CommandSecurityChecker$1.run(CommandSecurityChecker.java:187)
    at com.sun.enterprise.admin.util.CommandSecurityChecker$1.run(CommandSecurityChecker.java:183)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:360)
    at com.sun.enterprise.admin.util.CommandSecurityChecker.authorize(CommandSecurityChecker.java:183)
    at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1239)
    at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
    at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
    at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
    at org.glassfish.admin.rest.resources.admin.CommandResource.executeCommand(CommandResource.java:407)
```

Discussion of this behaviour (per Servet 3.0 spec Chapter 8.2.3) as well as sample project can be seen in [this Jetty issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=439663).

**Comment by mikecroft** [comment]
Confirmed in 164; created internal issue `PAYARA-1197`

**Comment by lprimak** [comment]
Closing.. this should be fixed in the next release
