### ISSUE TITLE
Exception deploying JAX-WS webservice on Payara Blue 4.1.1.162

### ISSUE THREAD

**Issue by michaelpaesold** [payara/Payara#937]
We are migrating our application from Glassfish 3.1.2 (AIX) to Payara Blue 4.1.1.162. This is actually not AIX, but IBM i (aka AS400), but they share the same IBM Java VM (we are running on IBM J9 VM 1.7.0 SR9 FP40, class library based on Oracle jdk7u101-b14)

When deploying a WAR with JAX-WS web service endpoints, we get a java.lang.ClassNotFoundException for the class com.sun.org.apache.xml.internal.resolver.CatalogManager.

Top part of stack trace (full stack trace [attached](https://github.com/payara/Payara/files/377856/CatalogManager-stacktrace.txt)):
```
  Deployment failed
java.lang.NoClassDefFoundError: com.sun.org.apache.xml.internal.resolver.CatalogManager
	at java.lang.J9VMInternals.verifyImpl(Native Method)
	at java.lang.J9VMInternals.verify(J9VMInternals.java:94)
	at java.lang.J9VMInternals.initialize(J9VMInternals.java:169)
	at com.sun.xml.ws.api.server.WSEndpoint.create(WSEndpoint.java:639)
	at org.glassfish.webservices.WSServletContextListener.registerEndpoint(WSServletContextListener.java:267)
	at org.glassfish.webservices.WSServletContextListener.contextInitialized(WSServletContextListener.java:104)
	at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:5396)
        ...
```

The class is neither in aixporting-repackaged.jar (based on maven artifact com.sun.xml.parser:jaxp-ri:1.4.5), nor in webservices-osgi-aix.jar, which both contain com.sun private classes.

The missing package `com.sun.org.apache.xml.internal.resolver` can be found in [com.sun.xml.bind:jaxb-xjc:2.2.6](https://mvnrepository.com/artifact/com.sun.xml.bind/jaxb-xjc/2.2.6). This is the latest version that contains the classes, newer versions don't. The classes have been part of Oracle JDK since at least Java SE 6.

I guess it would be an option to copy those classes in the aixporting-repackaged.jar build? If you can give me a hint where to find the sources for aixporting-repackaged.jar I can try to add them there and see if anything else is missing for JAX-WS webservices to work on Payara Blue.

**Comment by michaelpaesold** [comment]
For verification, I tried putting a jar with the missing classes from `com.sun.org.apache.xml.internal.resolver.*` into lib/ext of the domain. The ClassNotFoundException is gone now, but I get a different Exception then:
```
[2016-07-22T12:17:01.845+0200] [Payara 4.1] [WARNING] [AS-WSJSR109IMPL-00082] [javax.enterprise.webservices] [tid: _ThreadID=65 _ThreadName=admin-listener(5)] [timeMillis: 1469182621845] [levelValue: 900] [[
  Deployment failed
java.lang.IllegalStateException: MASM0001: Default configuration file [ jaxws-tubes-default.xml ] was not found
	at com.sun.xml.ws.assembler.MetroConfigLoader.init(MetroConfigLoader.java:141)
	at com.sun.xml.ws.assembler.MetroConfigLoader.<init>(MetroConfigLoader.java:118)
	at com.sun.xml.ws.assembler.TubelineAssemblyController.getTubeCreators(TubelineAssemblyController.java:122)
	at com.sun.xml.ws.assembler.MetroTubelineAssembler.createServer(MetroTubelineAssembler.java:173)
	at com.sun.xml.ws.server.WSEndpointImpl.<init>(WSEndpointImpl.java:193)
	at com.sun.xml.ws.server.EndpointFactory.create(EndpointFactory.java:337)
	at com.sun.xml.ws.server.EndpointFactory.create(EndpointFactory.java:332)
	at com.sun.xml.ws.server.EndpointFactory.createEndpoint(EndpointFactory.java:164)
	at com.sun.xml.ws.api.server.WSEndpoint.create(WSEndpoint.java:577)
	at com.sun.xml.ws.api.server.WSEndpoint.create(WSEndpoint.java:560)
	at com.sun.xml.ws.api.server.WSEndpoint.create(WSEndpoint.java:639)
	at org.glassfish.webservices.WSServletContextListener.registerEndpoint(WSServletContextListener.java:267)
	at org.glassfish.webservices.WSServletContextListener.contextInitialized(WSServletContextListener.java:104)
	at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:5396)
```

Has anyone successfully deploy webservice endpoints on Payara Blue, yet?

**Comment by smillidge** [comment]
We test Payara Blue on the same test suite as the other Payara versions on the Power Development Platform which includes jaxws tests. Do you have a simple test case we can try?

**Comment by michaelpaesold** [comment]
I will have to create a simple test case. Is any of those test cases you are referring to public? If so, I could try to deploy that one in our environment and see if it works.

**Comment by smillidge** [comment]
Can you try Payara 161 and see if you have the same problem?

**Comment by michaelpaesold** [comment]
Yeah, I will try and report back. A co-worker is also preparing a simple test project to reproduce the issue.

**Comment by smillidge** [comment]
OK we are also getting a test failure on the latest pre-release which we are investigating so something may have slipped through into the 162 release.

**Comment by michaelpaesold** [comment]
As promised, attached is a very simple JAX-WS web service endpoint in a .war archive, which fails with the same exception as our production app on the 162 release. Can you try this on the Power Development Platform?

[HelloWorldWebService.war.zip](https://github.com/payara/Payara/files/403925/HelloWorldWebService.war.zip)

**Comment by michaelpaesold** [comment]
I just tried release 161.1 now, same issue. Btw., the internal app `__wstx-services` fails with the same exception on deployment, at least in release 161.1. I will try 161 and 154 releases, too.

**Comment by smillidge** [comment]
Thanks for the feedback looks like our testing is broken in this area of Payara Blue as we didn't pick this up. We'll fix this for the next release due imminently.

**Comment by michaelpaesold** [comment]
Great! I would be happy to test a pre-release as soon as one integrating the fixes is available.

Some more notes I took when looking around a bit more before the weekend: You probably know that already, but the `org.glassfish.metro:webservices-extra-jdk-packages` artifact in glassfish/modules is the one referencing the extra JDK packages missing in the IBM JDK. It's named _Extra JDK 6 packages required by Metro Web Services OSGi  bundle_.

It has the following OSGi exports (with `system.bundle;extension:=framework`):
- com.sun.org.apache.xml.internal.resolver.tools
- com.sun.org.apache.xml.internal.resolver
- com.sun.source.tree
- com.sun.source.util
- com.sun.tools.javac.processing
- com.sun.tools.javac.util

None of these are in in the IBM JDK.

For the `com.sun.org.apache.xml.internal.resolver` package, IBM has older versions of those classes (`Catalog`, `CatalogManager`, etc.) in `com.ibm.xml.resolver` in a separate jre\lib\xml.jar.

I just wanted to add these notes in case there are further issues integrating Metro on the IBM JDK.

**Comment by michaelpaesold** [comment]
Tested on Payara blue release 163, works well so far! Thanks!

**Comment by smillidge** [comment]
That's great news. Payara Blue 163 passes all our WS tests.

**Comment by michaelpaesold** [comment]
By the way, this also fixes the Metro JAX-WS client in Payara Blue! (Didn't work before, either.)
