### ISSUE TITLE
deploying a JEE app fails in payara micro

### ISSUE THREAD

**Issue by avasseur-pivotal** [payara/Payara#984]
Sounds like it does expect old namespaces
Is there any configuration?

```
[2016-08-02T15:29:07.822+0200] [Payara Micro 4.1] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1470144547822] [levelValue: 1000] [[
  Exception while deploying the app [tracks] : org.xml.sax.SAXParseExceptionpublicId: jar:file:/Users/avasseur/s2/jee/payara/lib/payara-micro-4.1.1.162.jar!/schemas/web-app_3_1.xsd; lineNumber: 8; columnNumber: 27; Deployment descriptor file WEB-INF/web.xml in archive [tracks].  TargetNamespace.1: Expecting namespace 'http://java.sun.com/xml/ns/javaee', but the target namespace of the schema document is 'http://xmlns.jcp.org/xml/ns/javaee'.
org.xml.sax.SAXParseExceptionpublicId: jar:file:/Users/avasseur/s2/jee/payara/lib/payara-micro-4.1.1.162.jar!/schemas/web-app_3_1.xsd; lineNumber: 8; columnNumber: 27; Deployment descriptor file WEB-INF/web.xml in archive [tracks].  TargetNamespace.1: Expecting namespace 'http://java.sun.com/xml/ns/javaee', but the target namespace of the schema document is 'http://xmlns.jcp.org/xml/ns/javaee'.
	at com.sun.enterprise.deployment.io.DeploymentDescriptorFile.read(DeploymentDescriptorFile.java:328)
...
Caused by: org.xml.sax.SAXParseException; systemId: jar:file:/Users/avasseur/s2/jee/payara/lib/payara-micro-4.1.1.162.jar!/schemas/web-app_3_1.xsd; lineNumber: 8; columnNumber: 27; TargetNamespace.1: Expecting namespace 'http://java.sun.com/xml/ns/javaee', but the target namespace of the schema document is 'http://xmlns.jcp.org/xml/ns/javaee'.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)

```

**Comment by smillidge** [comment]
I think the error is saying your web.xml namespace is http://java.sun.com/xml/ns/javaee

**Comment by avasseur-pivotal** [comment]
Oh you are right - I read as if the error message said the opposite.
web.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<web-app version="3.1" xmlns="http://java.sun.com/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_1.xsd">
    <context-param>
```
